### ISSUE TITLE
AttributeError: 'module' object has no attribute 'constant'

### ISSUE THREAD

**Issue by k3nnywilliam** [tensorflow/tensorflow#3369]
Hi everyone, I tried to run Tensorflow 0.9.0 with Python 3.4 but I've received this error:
 

Python 3.4.5 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:47:57)
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
import tensorflow as tf
hello = tf.constant('Hello, TensorFlow!')
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'constant'

### Steps to reproduce
1. Installed Anaconda 64-bit Python 3.5
2. Installed Tensorflow following these [instructions](https://www.tensorflow.org/versions/r0.9/get_started/os_setup.html#anaconda-installation)

### What have you tried?
Tried with Python 3.5 but no luck as well. Version 2.7 works fine but I need to use version 3.x as part of my coursework requirement.

### Environment info
Operating System: OSX 10.11.1

**Comment by dstu** [comment]
I'm also running into this problem, after having followed the instructions for installing TensorFlow via pip on www.tensorflow.org, under Python 3.5.2 in Debian unstable. Here's what `dir(tf)` says after I `import tensorflow as tf`:

`['__doc__', '__loader__', '__name__', '__package__', '__path__', '__spec__']`

`help(tf)` is similarly unhelpful, giving some simple boilerplate and nothing else.

**Comment by concretevitamin** [comment]
I just tried to follow the Anaconda 64-bit Python 3.4 on my Ubuntu, and it worked fine.  One thing to check: if you used `sudo` in the installation process, directly launching `python3` might fail to find tensorflow; instead try `sudo python3`.

Did you use the GPU version or CPU-only version?

**Comment by dstu** [comment]
`sudo python3` gives me a full tensorflow module. See my edit about RE the CPU version vs. the GPU version.

It looks like `/usr/local/lib/python3.5/dist-packages/tensorflow/` is set `drwxr-S---` for some bizarre reason. This might not be a problem with your packaging; if I install another third-party module (like flask) using `pip3 install`, I also have problems viewing its contents as a non-root user. I'll try using a virtualenv, instead.

**Comment by dstu** [comment]
Actually, as per http://caligari.treboada.net/2014/09/23/python-pip-and-the-staff-group/, it should be sufficient to add your user to the group `staff` and then install with `pip/pip3 install` (rather than `sudo pip/pip3`).

**Comment by k3nnywilliam** [comment]
Since I'm using OSX, the binary provided is CPU-only therefore I'm not having any problem with GPU vs CPU version. 

Ok, so far I got python 3.5 working by installing TF via pip. Which means it has something to do with the conda package manager maybe...? It works with python 2.7 so I'm not sure. Tried sudo python3, nothing worked.

**Comment by concretevitamin** [comment]
Looks like it has been workaround-ed.  Closing for now.

**Comment by victoriastuart** [comment]
In case this helps others:

Related: I had an issue (tensorflow 0.9), in that scripts stopped working: " AttributeError: 'module' object has no attribute 'constant' ". Thanks to this answer [http://stackoverflow.com/questions/37383812/tensorflow-module-object-has-no-attribute-placeholder], I looked and noticed that I had a folder named "tensorflow". I renamed that folder, and my scripts are working again.

**Comment by tahirahmad2030** [comment]
In my case i had named the file as "tensorflow.py" which was the cause of above Error. I changed the file name which fixed the problem. Also deleted mt script file "tensorflow.py".

**Comment by gallybaba** [comment]
i have the same issue and I am not using a file name and nor am i under a source tree. problem goes away if i install tensorflow-gpu but comes back when i install native build from source using bazel. I also notice that __https://www.tensorflow.org/install/install_linux#InstallingAnaconda__ had a LOT more files than local pip package create from bazel.
I have ubuntu 16 xenial with nvidia ge force 780i. I built local pip package following https://www.tensorflow.org/install/install_sources
i have python as anaconda3.

issue
python
Python 3.6.0 |Anaconda 4.3.1 (64-bit)| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> hello = tf.constant("Hello, TensorFlow!")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'constant'
>>> hello = tf.constant('Hello, TensorFlow!')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'constant'


The directory permissions look ok as well where this package was distributed. Am i missing something?

**Comment by Antigonus** [comment]
Same thing.  Simple direct install.

-----
$ lsb_release --> Ubuntu 17.04
$ sudo su -l
# pip3 install tensorflow
    <many messages all good>
    Successfully installed backports.weakref-1.0rc1 bleach-1.5.0 html5lib-0.9999999 markdown-2.6.8 numpy-1.13.1 protobuf-3.3.0 tensorflow-1.2.1 werkzeug-0.12.2
^d

$ Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> python.el: native completion setup loaded
>>> import tensorflow as tf
>>> hello = tf.constant('Hello, TensorFlow!')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'constant'

-------

So how should I proceed??

**Comment by fauliath** [comment]
@Antigonus, you're misspelling the command. You have tensoflow instead of tensorflow.

It should be;
`pip3 install tensorflow --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.2.1-cp35-cp35m-linux_x86_64.whl`

**Comment by Antigonus** [comment]
@faullath,   thank you!   I suspect the first problem was something about permissions having run pip3 as root.   That mispelling is incredible as the command was cut and paste from the dialog. Somehow a character was deleted, or wasn't there in the first place.  I didn't think to examine it closely.   I ended up replacing Ubuntu 17  with a Debian Stretch,  ran pip3 as a user on the new system,  and everything went smoothly.

**Comment by wednesy** [comment]
After directly installing with pip3 install tensorflow, AttributeError: 'module' object has no attribute 'constant' has been solved. But a new problem popped up.

```
Python 3.6.3 (v3.6.3:2c5fed86e0, Oct  3 2017, 00:32:08) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> hello = tf.constant("hello world")
>>> sess = tf.Session()
2017-10-18 08:30:29.868808: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-18 08:30:29.868853: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-10-18 08:30:29.868873: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-18 08:30:29.868889: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
```

**Comment by Brenndoerfer** [comment]
Run into the same error.
Reason: File was named `logging.py`
Solution: Rename file

**Comment by sketch34** [comment]
Same problem, installed on OSX exactly as per instrucitons: https://www.tensorflow.org/install/install_mac

```
>>> import tensorflow as tf
>>> hello = tf.constant('Hello, TensorFlow!')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'constant'
```

Tried `sudo python3` with same result.

**Comment by betelgeuseMsi** [comment]
I installed tensorflow from Source had the same problem. I noticed that while executing the command "sudo pip install /tmp/tensorflow_pkg/tensorflow-1.5.0-py2-none-any.whl", I was executing it by copying and pasting it directly which was wrong because the term "tensorflow-1.5.0-py2-none-any.whl" need to be replaced with the right name of the .whl file. First time running it gave some error but when I ran it again, it worked like a charm. You can find it in location /tmp/tensorflow_pkg. Just putting it here hoping it would save someone else's load of time.

**Comment by ujjwalrathod007** [comment]
@concretevitamin  sudo python helps!!

I had an error

> python
Python 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 23:32:55) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ujjval/anaconda2/lib/python2.7/site-packages/tensorflow/__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/ujjval/anaconda2/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/ujjval/anaconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/ujjval/anaconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/ujjval/anaconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/ujjval/anaconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
