### ISSUE TITLE
[Keras] TimeDistributed wrapper error:  'NoneType' object has no attribute 'as_list'

### ISSUE THREAD

**Issue by footh** [tensorflow/tensorflow#14054]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: built from master pulled on 10/26
- **Python version**: 3.6
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: See below

### Describe the problem
Issue arises when using TimeDistributed wrapper in release *1.4*. See simple code example below which works fine in version *1.3*.

### Source code / logs
```
def td():
    model = tf.keras.models.Sequential()
    model.add(tf.keras.layers.Dense(8, input_shape=(16,)))
    model.add(tf.keras.layers.Dense(4))
    model.summary()
    
    frame_input = tf.keras.layers.Input(shape=(10, 16))
    x = tf.keras.layers.TimeDistributed(model)(frame_input)
    x = tf.keras.layers.Flatten()(x)
    
    full_model = tf.keras.models.Model(inputs=frame_input, outputs=x)
    full_model.summary()
```
produces this trace:

```
     x = tf.keras.layers.TimeDistributed(model)(frame_input)
  File "/Users/guest/dev/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 252, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "/Users/guest/dev/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 575, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/Users/guest/dev/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/wrappers.py", line 238, in call
    output_shape = self._compute_output_shape(input_shape).as_list()
  File "/Users/guest/dev/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/wrappers.py", line 193, in _compute_output_shape
    child_input_shape).as_list()
AttributeError: 'NoneType' object has no attribute 'as_list'
```

**Comment by facaiy** [comment]
Run the code `td()` on tf 1.5-nightly, it seems good?

```bash
~/Downloads ❯❯❯ python a.py
1.5.0-dev20171021
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_1 (Dense)              (None, 8)                 136
_________________________________________________________________
dense_2 (Dense)              (None, 4)                 36
=================================================================
Total params: 172
Trainable params: 172
Non-trainable params: 0
_________________________________________________________________
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
input_1 (InputLayer)         (None, 10, 16)            0
_________________________________________________________________
time_distributed_1 (TimeDist (None, 10, 4)             172
_________________________________________________________________
flatten_1 (Flatten)          (None, 40)                0
=================================================================
Total params: 172
Trainable params: 172
Non-trainable params: 0
_________________________________________________________________
```

**Comment by footh** [comment]
I built tensorflow from master so I assumed I had the latest. Where do you get the nightly builds from?

**Comment by footh** [comment]
I verified that I'm getting the same issue in a python 3.5 environment. Must be some other issue with my setup? 😕 

```
    x = tf.keras.layers.TimeDistributed(model)(frame_input)
  File "/home/guest/anaconda3/envs/tf35/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 253, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "/home/guest/anaconda3/envs/tf35/lib/python3.5/site-packages/tensorflow/python/layers/base.py", line 591, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/guest/anaconda3/envs/tf35/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/layers/wrappers.py", line 238, in call
    output_shape = self._compute_output_shape(input_shape).as_list()
  File "/home/guest/anaconda3/envs/tf35/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/layers/wrappers.py", line 193, in _compute_output_shape
    child_input_shape).as_list()
AttributeError: 'NoneType' object has no attribute 'as_list'
```

**Comment by jart** [comment]
@fchollet If you have a moment our friend is reporting an API regression in `tf.keras.layers.TimeDistributed` from 1.3 -> 1.4.

**Comment by footh** [comment]
So...while trying to debug this I discovered something odd. It works fine when I put a breakpoint in the `_compute_output_shape` method in TimeDistributed. When I remove the breakpoint and just run it, I get the error. This seems to be some kind of race condition. Can someone who can get this to work describe their environment? (I'm using the anaconda python 3.6 dist). Anyone have insight as to why this might be happening?

**Comment by footh** [comment]
I found out what the issue is. It's a bug in tensorflow. I have a PR that fixes it. I just am awaiting permission to push it up.

**Comment by footh** [comment]
@jart What is the procedure for getting permission to push up a PR? I filled out the form and was expecting an email or something but haven't received anything yet.

**Comment by jart** [comment]
I wasn't aware there was a form. Is that for the Google CLA? If that's signed, you should be able to just write the code and send us the PR. Then someone on the team should hopefully review it in a day or so.

Please note you can't push to tensorflow/tensorflow. Typically people click the fork button, push to their personal repo, and then use that to create the PR.

**Comment by footh** [comment]
Yes it was the Google CLA.

Thanks for the tip, the PR is up.

**Comment by hcchengithub** [comment]
Amazing, [tooth's solution](https://github.com/tensorflow/tensorflow/commit/d34c1d2978ec43f6600fc2f59d24055a972e09c6) has really fixed the problem happening on tensorflow 1.4. 

I suffered the problem when trying to play the demo 
"Integrating Keras & TensorFlow - The Keras workflow, expanded (TensorFlow Dev Summit 2017)"
YouTube ID: UeheTiBJ0Io

Error message :  
%USERPROFILE%\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\keras\_impl\keras\layers\wrappers.py in _compute_output_shape(self, input_shape)
    191                                                  input_shape[2:])
    192     child_output_shape = self.layer._compute_output_shape(  # pylint: disable=protected-access
--> 193         child_input_shape).as_list()
    194     timesteps = input_shape[1]
    195     return tensor_shape.TensorShape([child_output_shape[0], timesteps] +

AttributeError: 'NoneType' object has no attribute 'as_list'

If you are looking for solution for the same problem this is it.
