### ISSUE TITLE
micro: null-dereference warning breaks Makefile build on g++ 10.2

### ISSUE THREAD

**Issue by rkuester** [tensorflow/tensorflow#45381]
@tensorflow/micro

### Description

Changes merged yesterday in 17130a8f trigger a warning treated as an error that breaks a Makefile build on g++10.2:
```
% git describe --all --long
heads/master-0-g34f2adacdbe

% make -f tensorflow/lite/micro/tools/make/Makefile test
tensorflow/lite/micro/tools/make/downloads/flatbuffers already exists, skipping the download.
tensorflow/lite/micro/tools/make/Makefile:478: warning: overriding recipe for target 'tensorflow/lite/micro/tools/make/downloads/person_model_int8'
tensorflow/lite/micro/tools/make/Makefile:478: warning: ignoring old recipe for target 'tensorflow/lite/micro/tools/make/downloads/person_model_int8'
g++ -std=c++11 -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-unwind-tables -ffunction-sections -fdata-sections -fmessage-length=0 -DTF_LITE_STATIC_MEMORY -DTF_LITE_DISABLE_X86_NEON -O3 -Werror -Wsign-compare -Wdouble-promotion -Wshadow -Wunused-variable -Wmissing-field-initializers -Wunused-function -Wswitch -Wvla -Wall -Wextra -Wstrict-aliasing -Wno-unused-parameter   -DTF_LITE_USE_CTIME -I. -Itensorflow/lite/micro/tools/make/downloads/gemmlowp -Itensorflow/lite/micro/tools/make/downloads/flatbuffers/include -Itensorflow/lite/micro/tools/make/downloads/ruy -Itensorflow/lite/micro/tools/make/downloads/kissfft -c tensorflow/lite/micro/kernels/detection_postprocess.cc -o tensorflow/lite/micro/tools/make/gen/linux_x86_64/obj/tensorflow/lite/micro/kernels/detection_postprocess.o
tensorflow/lite/micro/kernels/detection_postprocess.cc: In function ‘TfLiteStatus tflite::{anonymous}::Eval(TfLiteContext*, TfLiteNode*)’:
tensorflow/lite/micro/kernels/detection_postprocess.cc:590:58: error: potential null pointer dereference [-Werror=null-dereference]
  590 |   tflite::micro::GetTensorData<float>(num_detections)[0] =
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
  591 |       size_of_sorted_indices;
      |       ~~~~~~~~~~~~~~~~~~~~~~
tensorflow/lite/micro/kernels/detection_postprocess.cc:686:58: error: potential null pointer dereference [-Werror=null-dereference]
  686 |   tflite::micro::GetTensorData<float>(num_detections)[0] = output_box_index;
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make: *** [tensorflow/lite/micro/tools/make/Makefile:490: tensorflow/lite/micro/tools/make/gen/linux_x86_64/obj/tensorflow/lite/micro/kernels/detection_postprocess.o] Error 1
```

This does not trigger a build error on tests run via `bazel test tensorflow/lite/micro/kernels:all:`. Perhaps that uses a different compiler than the `make`-initiated build.

### System information

This is with the native g++ in Debian bullseye:
```
% g++ --version
g++ (Debian 10.2.0-19) 10.2.0
[....]
```

**Comment by rkuester** [comment]
@mansnils, bringing this to your attention since 17130a8 is attributed to you.

**Comment by advaitjain** [comment]
PR https://github.com/tensorflow/tensorflow/pull/45286 updated the patching to fix the underlying issue but needs the downloaded flatbuffers directory to be removed so that the updated patching can be used.

This should hopefully fix your issue:
```
rm -rf tensorflow/lite/tools/make/downloads/flatbuffers
make -f tensorflow/lite/tools/make/Makefile test
```

I'm going to close this issue but please reopen if it is not resolved with my suggestion.

**Comment by advaitjain** [comment]
Note that the reason why the error does not show up with bazel is that make and bazel use different versions of the flatbuffers library and only the make version had the patch from https://github.com/tensorflow/tensorflow/pull/45040, which was then fixed with https://github.com/tensorflow/tensorflow/pull/45286. 

See [this comment](https://github.com/tensorflow/tensorflow/issues/44971#issuecomment-736130061) for additional context.

**Comment by rkuester** [comment]
I see, it has nothing to do with a change in warnings in g++ 10.2, but rather a diagnostic pragma that was improperly cleared (see fix in 87b03eeb).

Thank you. Your suggestion did indeed fix the build issue. Leaving this issue closed and closing the linked PR #45382.
