### ISSUE TITLE
'TFLiteConverter' object has no attribute 'experimental_new_quantizer' - TF 2.2.0-rc2

### ISSUE THREAD

**Issue by feranick** [tensorflow/tensorflow#38082]
**System information** 
- Have I written custom code: See below.
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or
binary): source
- TensorFlow version (use command below): 2.2.0-rc2
- Python version: 3.6.9
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version : XCode 11.4
- CUDA/cuDNN version: - GPU model and memory: 10.2, GTX1080ti

**Describe the current behavior**
Using the current code:
`
    converter = tf.compat.v1.lite.TFLiteConverter.from_keras_model_file(dP.model_name) 
    converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
    converter.representative_dataset = representative_dataset_gen
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.uint8
    converter.inference_output_type = tf.uint8
    tflite_quant_model = converter.convert()
`

I get the following error and crash using TF 2.2.0-rc2:
`
    tflite_quant_model = converter.convert()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py", line 1094, in convert
    result, inference_input_type, inference_output_type)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py", line 267, in _calibrate_quantize_model
    inference_output_type, allow_float, self.experimental_new_quantizer)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py", line 944, in __getattribute__
    return object.__getattribute__(self, name)
AttributeError: 'TFLiteConverter' object has no attribute 'experimental_new_quantizer'
`

**Describe the expected behavior**
NOTE: This error is specific to TF 2.2.0-rc2. All works well with TF 2.2.0-rc1.

**Comment by feranick** [comment]
The issue seems to be related to the [commit](https://github.com/tensorflow/tensorflow/commit/e6895b3648595080143e8f5dd6f56c16e7852e91). In particular, the line 267:

` inference_output_type, allow_float, self.experimental_new_quantizer)`

has not been updated to the new private API. Should it be?:

` inference_output_type, allow_float, self._experimental_new_quantizer)`

**Comment by liufengdb** [comment]
Good catch. The cherry picked cl was not include all the changes. Let me fix it now.

**Comment by liufengdb** [comment]
Created a fix here: https://github.com/tensorflow/tensorflow/pull/38139

**Comment by feranick** [comment]
Tested with fix, and all is working now. Since the fix has been merged, I close this bug.
