### ISSUE TITLE
TensorFlowLiteC and TensorFlowLiteSelectOps iOS Pods :: Duplicate symbols

### ISSUE THREAD

**Issue by swittk** [tensorflow/tensorflow#52042]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS X Mojave (10.14.6)
- TensorFlow installed from (source or binary): Cocoapods (nightly pod)
- TensorFlow version: Tensorflow Lite 0.0.1-nightly.20210915

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

(Following the comment over [here](https://github.com/tensorflow/tensorflow/issues/41876#issuecomment-921400513))

Experiencing duplicate symbols with the current nightly builds, this doesn't occur with pod versions set to 2.6.0.

Current podfile
```
'TensorFlowLiteObjC', '~> 0.0.1-nightly'
'TensorFlowLiteObjC/Metal', '~> 0.0.1-nightly'
'TensorFlowLiteSelectTfOps', '~> 0.0.1-nightly'
```
Resolves to lockfile
```
  - TensorFlowLiteC (0.0.1-nightly.20210915):
    - TensorFlowLiteC/Core (= 0.0.1-nightly.20210915)
  - TensorFlowLiteC/Core (0.0.1-nightly.20210915)
  - TensorFlowLiteC/Metal (0.0.1-nightly.20210915):
    - TensorFlowLiteC/Core
  - TensorFlowLiteObjC (0.0.1-nightly.20210915):
    - TensorFlowLiteObjC/Core (= 0.0.1-nightly.20210915)
  - TensorFlowLiteObjC/Core (0.0.1-nightly.20210915):
    - TensorFlowLiteC (= 0.0.1-nightly.20210915)
  - TensorFlowLiteObjC/Metal (0.0.1-nightly.20210915):
    - TensorFlowLiteC/Metal (= 0.0.1-nightly.20210915)
    - TensorFlowLiteObjC/Core (= 0.0.1-nightly.20210915)
  - TensorFlowLiteSelectTfOps (0.0.1-nightly.20210915)
```

The duplicate symbols are `_TfLiteXNNPackDelegateCreate `, `_TfLiteXNNPackDelegateDelete `, `_TfLiteXNNPackDelegateGetThreadPool `, and `_TfLiteXNNPackDelegateOptionsDefault`. 

They're duplicated between `/Pods/TensorFlowLiteSelectTfOps/Frameworks/TensorFlowLiteSelectTfOps.framework/TensorFlowLiteSelectTfOps(xnnpack_delegate.o)` and `Pods/TensorFlowLiteC/Frameworks/TensorFlowLiteC.framework/TensorFlowLiteC`.

(If pod versions are specified as 2.6.0 then they work fine)

**Comment by yyoon** [comment]
This looks related to the recent change where XNNPack is enabled by default.
@multiverse-tf Could you please take a look?

Also cc-ing @thaink who has more experience in these duplicate symbol issues on iOS side.

**Comment by multiverse-tf** [comment]
@Maratyszcza just fyi.

**Comment by multiverse-tf** [comment]
> _Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template_
> 
> **System information**
> 
> * OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS X Mojave (10.14.6)
> * TensorFlow installed from (source or binary): Cocoapods (nightly pod)
> * TensorFlow version: Tensorflow Lite 0.0.1-nightly.20210915
> 
> **Describe the problem**
> 
> **Provide the exact sequence of commands / steps that you executed before running into the problem**
> 
> (Following the comment over [here](https://github.com/tensorflow/tensorflow/issues/41876#issuecomment-921400513))
> 
> Experiencing duplicate symbols with the current nightly builds, this doesn't occur with pod versions set to 2.6.0.
> 
> Current podfile
> 
> ```
> 'TensorFlowLiteObjC', '~> 0.0.1-nightly'
> 'TensorFlowLiteObjC/Metal', '~> 0.0.1-nightly'
> 'TensorFlowLiteSelectTfOps', '~> 0.0.1-nightly'
> ```
> 
> Resolves to lockfile
> 
> ```
>   - TensorFlowLiteC (0.0.1-nightly.20210915):
>     - TensorFlowLiteC/Core (= 0.0.1-nightly.20210915)
>   - TensorFlowLiteC/Core (0.0.1-nightly.20210915)
>   - TensorFlowLiteC/Metal (0.0.1-nightly.20210915):
>     - TensorFlowLiteC/Core
>   - TensorFlowLiteObjC (0.0.1-nightly.20210915):
>     - TensorFlowLiteObjC/Core (= 0.0.1-nightly.20210915)
>   - TensorFlowLiteObjC/Core (0.0.1-nightly.20210915):
>     - TensorFlowLiteC (= 0.0.1-nightly.20210915)
>   - TensorFlowLiteObjC/Metal (0.0.1-nightly.20210915):
>     - TensorFlowLiteC/Metal (= 0.0.1-nightly.20210915)
>     - TensorFlowLiteObjC/Core (= 0.0.1-nightly.20210915)
>   - TensorFlowLiteSelectTfOps (0.0.1-nightly.20210915)
> ```
> 
> The duplicate symbols are `_TfLiteXNNPackDelegateCreate `, `_TfLiteXNNPackDelegateDelete `, `_TfLiteXNNPackDelegateGetThreadPool `, and `_TfLiteXNNPackDelegateOptionsDefault`.
> 
> They're duplicated between `/Pods/TensorFlowLiteSelectTfOps/Frameworks/TensorFlowLiteSelectTfOps.framework/TensorFlowLiteSelectTfOps(xnnpack_delegate.o)` and `Pods/TensorFlowLiteC/Frameworks/TensorFlowLiteC.framework/TensorFlowLiteC`.
> 
> (If pod versions are specified as 2.6.0 then they work fine)

Thx for reporting this! Could you help find the culprit commit? As @yyoon mentioned, we recently enabled XNNPACK backend by default on iOS (see 6fa4ddfd459386d9fa32ce5c19813f9aff56ae2a and 418156b52654f66b0286096cf8f58531f7473b1d for details). It's possible one of these two commits has caused this issue.

**Comment by domvie** [comment]
I'm getting the same issues with the most recent TensorFlowLiteSelectTfOps (0.0.1-nightly.20211013) and TensorFlowLiteSwift 2.6.0 as well as 2.4.0. In another project with an older TensorFlowLiteSelectTfOps (0.0.1-nightly.20210202) and TFLiteSwift 2.4.0 it works. Is there a way to downgrade/choose another TensorFlowLiteSelectTfOps version?

**Comment by gklka** [comment]
Version 2.7 still has the issue. Any plans to resolve it?

**Comment by normano** [comment]
@yyoon Can you reopen this and possibly reassign to someone else. The issue may be stale, but the problem is still exists.

**Comment by mohantym** [comment]
ok @normano ! Reopening this issue as requested.

**Comment by yyoon** [comment]
The fixed version of the SelectTfOps framework will be available soon via nightly builds (unfortunately, this problem will remain in 2.8.0). Will notify this thread once again when the nightly build is published.

**Comment by MoonshotQuest** [comment]
@yyoon @terryheo Hi, I'm experiencing the exact same issue on 2.8.0 with the 4 duplicate symbols.

I tried your fix by adding `"//tensorflow/lite/delegates/xnnpack:xnnpack_delegate"` to `avoid_deps` like
[this](https://github.com/tensorflow/tensorflow/commit/282772e0c27e302be91e060587dbe99289832365)

I re-run:
`bazel build -c opt --config=ios_arm64 tensorflow/lite/ios:TensorFlowLiteSelectTfOps_framework`

The 4 symbols are no longer duplicated but I'm facing a different problem now with a lot of missing symbols (see below).
In case this can help, I generated my `TensorFlowLiteC_framework` file wih:
`bazel build --config=ios_arm64 -c opt tensorflow/lite/ios:TensorFlowLiteC_framework `

Is there any tweak I can make to get these symbols back into `TensorFlowLiteSelectTfOps_framework` ?
```

Error (Xcode): Undefined symbol: tflite::logging_internal::MinimalLogger::LogFormatted(tflite::LogSeverity, char const*, char*)

Error (Xcode): Undefined symbol: ruy::ScopedSuppressDenormals::ScopedSuppressDenormals()

Error (Xcode): Undefined symbol: ruy::ScopedSuppressDenormals::~ScopedSuppressDenormals()

Error (Xcode): Undefined symbol: tflite::tensor_utils::Sub1Vector(short const*, int, short*)

Error (Xcode): Undefined symbol: tflite::tensor_utils::CwiseAdd(short const*, short const*, int, int, short*)

Error (Xcode): Undefined symbol: tflite::tensor_utils::CwiseClipping(short*, int, short)

Error (Xcode): Undefined symbol: tflite::tensor_utils::MatrixBatchVectorMultiply(signed char const*, int, signed char const*, int, int, int, int, int, signed char*, signed char)

Error (Xcode): Undefined symbol: tflite::tensor_utils::VectorScalarMultiply(signed char const*, int, float, float*)

Error (Xcode): Undefined symbol: tflite::tensor_utils::TwoGateSaturatingAdd(signed char const*, signed char, signed char const*, signed char, int, int, int, int, int, int, short*)

Error (Xcode): Undefined symbol: tflite::tensor_utils::ApplyLayerNormFloat(short const*, short const*, int, int, int const*, int, int, short*)

Error (Xcode): Undefined symbol: tflite::tensor_utils::ApplySigmoidFloat(short const*, int, int, short*)

Error (Xcode): Undefined symbol: tflite::tensor_utils::CwiseMul(short const*, short const*, int, int, int, short*)

Error (Xcode): Undefined symbol: tflite::tensor_utils::MatrixBatchVectorMultiply(short const*, signed char const*, int, int, int const*, int, int, int, int, signed char*)

Error (Xcode): Undefined symbol: tflite::tensor_utils::ApplyLayerNorm(short const*, short const*, int const*, int, int, int, int, int, short*)

Error (Xcode): Undefined symbol: tflite::tensor_utils::CwiseClipping(float*, int, float)

Error (Xcode): Undefined symbol: tflite::tensor_utils::BatchVectorBatchVectorDotProduct(short const*, short const*, int, int, int*)

Error (Xcode): Undefined symbol: tflite::tensor_utils::MatrixBatchVectorMultiplyAccumulate(signed char const*, int const*, signed char const*, int, int, int, int, int, int, int*, short*, tflite::CpuBackendContext*)

Error (Xcode): Undefined symbol: tflite::tensor_utils::MatrixBatchVectorMultiplyAccumulate(signed char const*, int, int, signed char const*, float const*, int, float*, float const*, int const*, int*, int*, bool*, tflite::CpuBackendContext*)

Error (Xcode): Undefined symbol: tflite::tensor_utils::ReductionSumVector(int const*, int*, int, int)

Error (Xcode): Undefined symbol: ruy::Pack8bitColMajorForNeonA55ish(void const*, void const*, void const*, void const*, int, int, int, int, int, int, signed char*, int*, int)

Error (Xcode): Undefined symbol: tflite::GetIntermediatesSafe(TfLiteContext const*, TfLiteNode const*, int, TfLiteTensor**)

Error (Xcode): Undefined symbol: tflite::DynamicBuffer::WriteToTensorAsVector(TfLiteTensor*)

Error (Xcode): Undefined symbol: tflite::PreprocessLogSoftmaxScalingExp(double, double, int, int*, int*, int*, int*)

Error (Xcode): Undefined symbol: tflite::GetOutput(TfLiteContext*, TfLiteNode const*, int)

Error (Xcode): Undefined symbol: tflite::DynamicBuffer::AddString(tflite::StringRef const&)

Error (Xcode): Undefined symbol: tflite::tensor_utils::SparseMatrixBatchVectorMultiplyAccumulate1x4(float const*, int const*, int const*, int, int, float const*, int, float*)

Error (Xcode): Undefined symbol: tflite::tensor_utils::MatrixBatchVectorMultiplyAccumulate(float const*, int, int, float const*, int, float*)

Error (Xcode): Undefined symbol: tflite::NudgeQuantizationRange(float, float, int, int, float*, float*, float*)

Error (Xcode): Undefined symbol: tflite::DetectArmNeonDotprod()

Error (Xcode): Undefined symbol: ruy::Allocator::AllocateBytes(long)

Error (Xcode): Undefined symbol: tflite::internal::sparsity::FormatConverter<signed char>::FormatConverter(std::__1::vector<int, std::__1::allocator<int> > const&, TfLiteSparsity const&)

Error (Xcode): Undefined symbol: tflite::tensor_utils::ApplySigmoid(short const*, int, int, short*)

Error (Xcode): Undefined symbol: ruy::Ctx::SelectPath(ruy::Path)

Error (Xcode): Undefined symbol: tflite::tensor_utils::MatrixBatchVectorMultiplyAccumulate(signed char const*, int, int, signed char const*, float const*, int, int*, float*, tflite::CpuBackendContext*)

Error (Xcode): Undefined symbol: tflite::internal::sparsity::FormatConverter<signed char>::SparseToDense(signed char const*, unsigned long, signed char*, TfLiteContext*)

Error (Xcode): Undefined symbol: tflite::FakeQuantizeArray(float, float, float, float const*, float*, float)

Error (Xcode): Undefined symbol: tflite::IsMobilePlatform()

Error (Xcode): Undefined symbol: tflite::internal::sparsity::FormatConverter<float>::FormatConverter(std::__1::vector<int, std::__1::allocator<int> > const&, TfLiteSparsity const&)

Error (Xcode): Undefined symbol: tflite::tensor_utils::MeanStddevNormalization(float const*, float*, int, int)

Error (Xcode): Undefined symbol: tflite::PopulateConvolutionQuantizationParams(TfLiteContext*, TfLiteTensor const*, TfLiteTensor const*, TfLiteTensor const*, TfLiteTensor*, TfLiteFusedActivation const&, int*, int*, int*, int*, int*, int*, int)

Error (Xcode): Undefined symbol: tflite::HaveSameShapes(TfLiteTensor const*, TfLiteTensor const*)

Error (Xcode): Undefined symbol: ruy::PackFloatColMajorForNeon(float const*, float const*, float const*, float const*, int, int, int, int, int, float*)

Error (Xcode): Undefined symbol: tflite::tensor_utils::MatrixScalarMultiplyAccumulate(signed char const*, int, int, int, int*)

Error (Xcode): Undefined symbol: tflite::GetOptionalInputTensor(TfLiteContext const*, TfLiteNode const*, int)

Error (Xcode): Undefined symbol: tflite::logging_internal::MinimalLogger::Log(tflite::LogSeverity, char const*, ...)

Error (Xcode): Undefined symbol: tflite::tensor_utils::CwiseClipping(signed char*, int, signed char)

Error (Xcode): Undefined symbol: tflite::tensor_utils::Sub1Vector(float const*, int, float*)

Error (Xcode): Undefined symbol: tflite::internal::sparsity::FormatConverter<float>::SparseToDense(float const*)

Error (Xcode): Undefined symbol: ruy::detail::MultiplyByQuantizedMultiplier(int, int, int)

Error (Xcode): Undefined symbol: ruy::Kernel8bitNeon1Col(ruy::KernelParams8bit<4, 4> const&)

Error (Xcode): Undefined symbol: tflite::transpose_utils::IsTranspose2DApplicable(tflite::TransposeParams const&, tflite::RuntimeShape const&, int*, int*)

Error (Xcode): Undefined symbol: ruy::Kernel8bitNeon(ruy::KernelParams8bit<4, 4> const&)

Error (Xcode): Undefined symbol: ruy::Pack8bitColMajorForNeon(void const*, void const*, void const*, void const*, int, int, int, int, int, int, signed char*, int*, int)

Error (Xcode): Undefined symbol: ruy::Kernel8bitNeonDotprod1Col(ruy::KernelParams8bit<8, 8> const&)

Error (Xcode): Undefined symbol: tflite::GetQuantizedConvolutionMultipler(TfLiteContext*, TfLiteTensor const*, TfLiteTensor const*, TfLiteTensor const*, TfLiteTensor*, double*)

Error (Xcode): Undefined symbol: ruy::Pack8bitRowMajorForNeon(unsigned char const*, int, int, int, int, int, int, signed char*, int, int, int*, int, int)

Error (Xcode): Undefined symbol: tflite::tensor_utils::VectorBatchVectorCwiseProductAccumulate(short const*, int, short const*, int, int, int, short*)

Error (Xcode): Undefined symbol: tflite::GetOutputShapeFromInput(TfLiteContext*, TfLiteTensor const*, TfLiteIntArray**)

Error (Xcode): Undefined symbol: ruy::Kernel8bitNeonDotprodX1(ruy::KernelParams8bit<8, 8> const&)

Error (Xcode): Undefined symbol: tflite::internal::sparsity::FormatConverter<Eigen::half>::SparseToDense(Eigen::half const*, unsigned long, Eigen::half*, TfLiteContext*)

Error (Xcode): Undefined symbol: ruy::Kernel8bitNeonDotprod(ruy::KernelParams8bit<8, 8> const&)

Error (Xcode): Undefined symbol: ruy::Pack8bitColMajorForNeonDotprodA55ish(void const*, void const*, void const*, void const*, int, int, int, int, int, int, signed char*, int*, int)

Error (Xcode): Undefined symbol: ruy::Ctx::clear_performance_advisories()

Error (Xcode): Undefined symbol: ruy::Pack8bitRowMajorForNeonDotprod(void const*, void const*, void const*, void const*, int, int, int, int, int, int, signed char*, int, int*, int)

Error (Xcode): Undefined symbol: tflite::DynamicBuffer::WriteToTensor(TfLiteTensor*, TfLiteIntArray*)

Error (Xcode): Undefined symbol: ruy::KernelFloatNeonDotprodA55ish(ruy::KernelParamsFloat<8, 8> const&)

Error (Xcode): Undefined symbol: tflite::tensor_utils::SparseMatrixBatchVectorMultiplyAccumulate(signed char const*, unsigned char const*, int, int, signed char const*, float const*, int, float*)

Error (Xcode): Undefined symbol: tflite::GetInput(TfLiteContext const*, TfLiteNode const*, int)

Error (Xcode): Undefined symbol: ruy::KernelFloatNeonX1(ruy::KernelParamsFloat<8, 8> const&)

Error (Xcode): Undefined symbol: tflite::GetInputSafe(TfLiteContext const*, TfLiteNode const*, int, TfLiteTensor const**)

Error (Xcode): Undefined symbol: tflite::TfLiteTypeGetSize(TfLiteType)

Error (Xcode): Undefined symbol: tflite::GetQuantizedConvolutionMultipler(TfLiteContext*, TfLiteTensor const*, TfLiteTensor const*, TfLiteTensor*, double*)

Error (Xcode): Undefined symbol: ruy::ThreadPool::ExecuteImpl(int, int, ruy::Task*)

Error (Xcode): Undefined symbol: ruy::KernelFloatNeon(ruy::KernelParamsFloat<8, 8> const&)

Error (Xcode): Undefined symbol: tflite::tensor_utils::ReductionSumVector(signed char const*, int*, int, int)

Error (Xcode): Undefined symbol: ruy::PackFloatColMajorForNeonA55ish(float const*, float const*, float const*, float const*, int, int, int, int, int, float*)

Error (Xcode): Undefined symbol: tflite::CheckedLog2(float, int*)

Error (Xcode): Undefined symbol: tflite::tensor_utils::ApplyTanh(int, short const*, int, int, short*)

Error (Xcode): Undefined symbol: tflite::GetTemporarySafe(TfLiteContext const*, TfLiteNode const*, int, TfLiteTensor**)

Error (Xcode): Undefined symbol: ruy::KernelFloatNeonA55ish(ruy::KernelParamsFloat<8, 8> const&)

Error (Xcode): Undefined symbol: ruy::Kernel8bitNeonDotprodA55ish(ruy::KernelParams8bit<8, 8> const&)

Error (Xcode): Undefined symbol: tflite::ExternalCpuBackendContext::ExternalCpuBackendContext()

Error (Xcode): Undefined symbol: ruy::get_ctx(ruy::Context*)

Error (Xcode): Undefined symbol: ruy::Ctx::GetMainAllocator()

Error (Xcode): Undefined symbol: tflite::transpose_utils::RemoveOneSizeDimensions(tflite::RuntimeShape*, tflite::RuntimeShape*, tflite::TransposeParams*)

Error (Xcode): Undefined symbol: ruy::Pack8bitColMajorForNeonDotprod(void const*, void const*, void const*, void const*, int, int, int, int, int, int, signed char*, int*, int)

Error (Xcode): Undefined symbol: tflite::CalculateInputRadius(int, int, int)

Error (Xcode): Undefined symbol: tflite::transpose_utils::Flatten(tflite::RuntimeShape const&, tflite::RuntimeShape const&, tflite::TransposeParams const&, tflite::RuntimeShape*, tflite::RuntimeShape*, tflite::TransposeParams*)

Error (Xcode): Undefined symbol: tflite::internal::sparsity::FormatConverter<float>::SparseToDense(float const*, unsigned long, float*, TfLiteContext*)

Error (Xcode): Undefined symbol: tflite::CalculateShapeForBroadcast(TfLiteContext*, TfLiteTensor const*, TfLiteTensor const*, TfLiteTensor const*, TfLiteIntArray**)

Error (Xcode): Undefined symbol: tflite::internal::sparsity::FormatConverter<Eigen::half>::FormatConverter(std::__1::vector<int, std::__1::allocator<int> > const&, TfLiteSparsity const&)

Error (Xcode): Undefined symbol: tflite::GetTemporary(TfLiteContext*, TfLiteNode const*, int)

Error (Xcode): Undefined symbol: tflite::tensor_utils::ApplyTanhFloat(short const*, int, int, int, short*)

Error (Xcode): Undefined symbol: tflite::CpuBackendContext::GetFromContext(TfLiteContext*)

Error (Xcode): Undefined symbol: ruy::Kernel8bitNeonA55ish(ruy::KernelParams8bit<4, 4> const&)

Error (Xcode): Undefined symbol: tflite::QuantizeMultiplier(double, int*, int*)

Error (Xcode): Undefined symbol: tflite::CalculateActivationRangeQuantized(TfLiteContext*, TfLiteFusedActivation, TfLiteTensor*, int*, int*)

Error (Xcode): Undefined symbol: tflite::GetString(TfLiteTensor const*, int)

Error (Xcode): Undefined symbol: tflite::tensor_utils::VectorVectorDotProduct(float const*, float const*, int)

Error (Xcode): Undefined symbol: tflite::tensor_utils::CwiseMul(short const*, short const*, int, int, int, int, int, signed char*)

```

**Comment by w3sip** [comment]
Still a problem with 2.14.1. Other than `XNNPack`-related exports that seem to be duplicated between `TensorFlowLiteC` and `TensorFlowLiteSelectTfOps`, there are also all the `libz.a` symbols that `TensorFlowLiteSelectTfOps` is exporting.
