### ISSUE TITLE
import of DistributedDatasetInterface not valid anymore

### ISSUE THREAD

**Issue by bogdan-galileo** [tensorflow/tensorflow#61204]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

tf.2.13.0

### Custom code

No

### OS platform and distribution

Mac OS Ventura 13.4

### Python version

3.9.13

### Current behavior?

Instantiating `DataHandler`  from `tensorflow.python.keras.engine.data_adapter` throws an error 

`AttributeError: module 'tensorflow.python.distribute.input_lib' has no attribute 'DistributedDatasetInterface'`

The type `DistributedDatasetInterface` can now be found in [‎tensorflow/python/types/distribute.py](https://github.com/tensorflow/tensorflow/blob/9a1f8bb2ce3de3f57c9c141f23b9c8e4faeea387/tensorflow/python/types/distribute.py#L308)

### Standalone code to reproduce the issue

```shell
link: https://colab.research.google.com/drive/11rHWrwrAjbVzKjM6KZBBp_KemTOyf2Pp?usp=sharing

code:
!pip install -U tensorflow==2.13.0
from tensorflow.python.keras.engine import data_adapter
from tensorflow import range as tfrange
data_handler = data_adapter.DataHandler(x=tfrange(10))
```

### Relevant log output

```shell
/usr/local/lib/python3.10/dist-packages/tensorflow/python/keras/engine/data_adapter.py in __init__(self, x, y, sample_weight, batch_size, steps_per_epoch, initial_epoch, epochs, shuffle, class_weight, max_queue_size, workers, use_multiprocessing, model, steps_per_execution, distribute)
   1150       self._steps_per_execution_value = steps_per_execution.numpy().item()
   1151 
-> 1152     adapter_cls = select_data_adapter(x, y)
   1153     self._adapter = adapter_cls(
   1154         x,

/usr/local/lib/python3.10/dist-packages/tensorflow/python/keras/engine/data_adapter.py in select_data_adapter(x, y)
    986 def select_data_adapter(x, y):
    987   """Selects a data adapter than can handle a given x and y."""
--> 988   adapter_cls = [cls for cls in ALL_ADAPTER_CLS if cls.can_handle(x, y)]
    989   if not adapter_cls:
    990     # TODO(scottzhu): This should be a less implementation-specific error.

/usr/local/lib/python3.10/dist-packages/tensorflow/python/keras/engine/data_adapter.py in <listcomp>(.0)
    986 def select_data_adapter(x, y):
    987   """Selects a data adapter than can handle a given x and y."""
--> 988   adapter_cls = [cls for cls in ALL_ADAPTER_CLS if cls.can_handle(x, y)]
    989   if not adapter_cls:
    990     # TODO(scottzhu): This should be a less implementation-specific error.

/usr/local/lib/python3.10/dist-packages/tensorflow/python/keras/engine/data_adapter.py in can_handle(x, y)
    705   def can_handle(x, y=None):
    706     return (isinstance(x, (data_types.DatasetV1, data_types.DatasetV2)) or
--> 707             _is_distributed_dataset(x))
    708 
    709   def __init__(self,

/usr/local/lib/python3.10/dist-packages/tensorflow/python/keras/engine/data_adapter.py in _is_distributed_dataset(ds)
   1697 
   1698 def _is_distributed_dataset(ds):
-> 1699   return isinstance(ds, input_lib.DistributedDatasetInterface)

AttributeError: module 'tensorflow.python.distribute.input_lib' has no attribute 'DistributedDatasetInterface'
```

**Comment by franz101** [comment]
Same here

**Comment by sushreebarsa** [comment]
@SuryanarayanaY I was able to replicate this issue in TF v2.13, please find the attached logs below;
```
>>> data_handler = data_adapter.DataHandler(x=tfrange(10))
2023-07-13 14:56:46.518030: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1 Pro
2023-07-13 14:56:46.518111: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2023-07-13 14:56:46.518130: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.33 GB
2023-07-13 14:56:46.518309: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:303] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-07-13 14:56:46.518647: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:269] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jpratik/miniconda3/envs/TF2.13/lib/python3.10/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 1152, in __init__
    adapter_cls = select_data_adapter(x, y)
  File "/Users/jpratik/miniconda3/envs/TF2.13/lib/python3.10/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 988, in select_data_adapter
    adapter_cls = [cls for cls in ALL_ADAPTER_CLS if cls.can_handle(x, y)]
  File "/Users/jpratik/miniconda3/envs/TF2.13/lib/python3.10/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 988, in <listcomp>
    adapter_cls = [cls for cls in ALL_ADAPTER_CLS if cls.can_handle(x, y)]
  File "/Users/jpratik/miniconda3/envs/TF2.13/lib/python3.10/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 707, in can_handle
    _is_distributed_dataset(x))
  File "/Users/jpratik/miniconda3/envs/TF2.13/lib/python3.10/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 1699, in _is_distributed_dataset
    return isinstance(ds, input_lib.DistributedDatasetInterface)
AttributeError: module 'tensorflow.python.distribute.input_lib' has no attribute 'DistributedDatasetInterface'. Did you mean: 'DistributedDatasetSpec'?
version 2.13


```
Thank you!

**Comment by SuryanarayanaY** [comment]
@bogdan-galileo ,

Thanks for reporting. This seems regression issue as it is working in TF2.12v but breaking in TF2.13v. Attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/b875e09b66e0071ab2b953d57d590061/61204.ipynb) for reference. Again this issue is not just Mac OS specific.

**Comment by bertsky** [comment]
Still not fixed in current [master](https://github.com/tensorflow/tensorflow/blob/7cc3274ca16f82c60b624799b538adfe0b534469/tensorflow/python/keras/engine/data_adapter.py#L1696)!

**Comment by Dynery** [comment]
Hello @SuryanarayanaY , this problem doesn't occur in TF2.12.1, but there is still an error in the current version. I would greatly appreciate it if this could be addressed. Thank you!

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.


From the example shared, this appears to be related to internal API changes around DistributedDatasetInterface in TensorFlow 2.13. In the reproducer, data_adapter.py still references input_lib.DistributedDatasetInterface, while the interface itself appears to have moved under tensorflow.python.types.distribute, which results in the reported AttributeError. Since tensorflow.python.* modules are internal implementation details and are not part of the stable public API surface, compatibility issues like this can occur across TensorFlow releases. Using the public tf.keras APIs instead of importing from internal tensorflow.python.* modules should help avoid this issue. It may also help to verify the behavior on the latest TensorFlow release.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
