### ISSUE TITLE
Is unpack of TensorFlow deprecated?

### ISSUE THREAD

**Issue by cheyang** [tensorflow/tensorflow#8143]
I noticed that when I run the following code in v1.0.0 which was working well in v0.11.0 and v0.12.0, it's failed and told me that 

```
 new_shape = [batch_size, new_rows, new_cols, num_filters]
 tf_shape = tf.pack(new_shape)
```
error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'pack'
```

And I also can't find that in [tf api docs](https://www.tensorflow.org/api_guides/python/array_ops). I  am wondering what API to replace it? I didn't see any deprecated hint in [v0.12 api docs](https://www.tensorflow.org/versions/r0.12/api_docs/python/array_ops/)

**Comment by asimshankar** [comment]
Yes, you want to use `tf.unstack` instead.

This was mentioned in the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md), though perhaps could have been advertised more.

**Comment by cheyang** [comment]
Thanks.
