### ISSUE TITLE
Cannot link to built tensorflow_cc.lib with Visual C++ -- undefined symbols; r2.0

### ISSUE THREAD

**Issue by Kramax** [tensorflow/tensorflow#32997]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
   Windows 10 1903 Build 18362.356
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
  NA
- TensorFlow installed from (source or binary): 
  source
- TensorFlow version: 
  r2.0 as of 29-Sep-2019
- Python version: 
  3.6
- Installed using virtualenv? pip? conda?: 
  No
- Bazel version (if compiling from source): 
  0.29.1
- GCC/Compiler version (if compiling from source): 
  Visual C++ 2017 14.16.27023
- CUDA/cuDNN version: 
  10.1, 7.6.4.38
- GPU model and memory: 
  NVIDIA Quadro P2000, 5GB

**Describe the problem**
First off, I know I am not using the version of Bazel called for in the build instructions. In fact the version of bazel called for is a little ambiguous, but none of the versions called for would work for me. They just did not work with Visual C++ 2017 as I have it installed. But 0.29.1 did work in that it could build "successfully".

I am building r2.0 from source to use the C++ API with an external program in a plugin DLL. I built tensorflow_cc.dll and tensorflow_cc.lib using bazel (after much struggle). But when I tried to link to tensorflow_cc.lib (and no other tensorflow objects) I get unresolved symbols from tensorflow packages. With the vanilla r2.0 source, I get unresolved symbols for the following:
```
?_TensorShapeProto_default_instance_@tensorflow@@3VTensorShapeProtoDefaultTypeInternal@1@A

??0SessionOptions@tensorflow@@QEAA@XZ

?LoadSavedModel@tensorflow@@YA?AVStatus@1@AEBUSessionOptions@1@AEBVRunOptions@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$unordered_set@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@U?$hash@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@U?$equal_to@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@6@QEAUSavedModelBundle@1@@Z
```

which coresponds to the following when demangled:
```
class tensorflow::TensorShapeProtoDefaultTypeInternal tensorflow::_TensorShapeProto_default_instance_

public: __cdecl tensorflow::SessionOptions::SessionOptions(void) __ptr64

class tensorflow::Status __cdecl tensorflow::LoadSavedModel(struct tensorflow::SessionOptions const & __ptr64,class tensorflow::RunOptions const & __ptr64,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __ptr64,class std::unordered_set<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct std::hash<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,struct std::equal_to<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > const & __ptr64,struct tensorflow::SavedModelBundle * __ptr64 const)
```
I read some other github bug reports and discovered that there is a complex method used to export a subset of the global symbols into the .lib file that involves a python program tensorflow/tools/def_file_filter/def_file_filter.py.tpl and someone showed how to put extra symbols in that to add to the set exported. I went ahead and did that:
```
diff --git a/tensorflow/tools/def_file_filter/def_file_filter.py.tpl ...
@@ -154,6 +154,9 @@ def main():
       else:
         def_fp.write("\t" + decorated + " DATA\n")
       taken.add(decorated)
+    def_fp.write("\t??0SessionOptions@tensorflow@@QEAA@XZ\n")
+    def_fp.write("\t?_TensorShapeProto_default_instance_@tensorflow@@3VTensorShapeProtoDefaultTypeInternal@1@A DATA\n")
+    def_fp.write("\t?LoadSavedModel@tensorflow@@YA?AVStatus@1@AEBUSessionOptions@1@AEBVRunOptions@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$unordered_set@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@U?$hash@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@U?$equal_to@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@6@QEAUSavedModelBundle@1@@Z\n")
     def_fp.close()

   exit_code = proc.wait()
```
This fixed 2 of the 3 unresolved, but the following was still undefined:
```
?_TensorShapeProto_default_instance_@tensorflow@@3VTensorShapeProtoDefaultTypeInternal@1@A
```
The only way I could get it to work was to actually link to the object file that defined that global object (tensor_shape.pb.o) and two ".a" libraries for protobuf (libprotobuf_lite.a & libprotobuf.a):
```
cl.exe -MD ... plugin.obj .wsl.obj/segTask.obj .wsl.obj/tfseg.obj /link /dll ... c:/root/tensorflow/bazel-out/x64_windows-opt/bin/tensorflow/core/_objs/protos_all_proto_cc_impl/tensor_shape.pb.o c:/root/tensorflow/bazel-out/x64_windows-opt/bin/external/com_google_protobuf/libprotobuf.a c:/root/tensorflow/bazel-out/x64_windows-opt/bin/external/com_google_protobuf/libprotobuf_lite.a c:/root/tensorflow/bazel-bin/tensorflow/tensorflow_cc.lib 
```
I am not using any exotic tensorflow calls in my C++ code and it seems that it should just work. There are clearly other similar issues with unresolved symbols with Visual C++ builds and I am hoping the above will help to resolve those. As it is, it seems that anyone trying to deploy an inference engine using C++ on Windows will struggle mightily. I think the first issue that was solved with def_file_filter.py.tpl is simple to solve. But I just could not figure out why the 3rd symbol would never resolve. Clearly, linking in the .o file is totally bogus. I looked at the generated def file tensorflow_filtered_def_file.def and it seemed the symbol was actually in that file already without my changes to def_file_filter.py.tpl, but it still would not work.

(BTW, I also posted a stackoverflow question about this https://stackoverflow.com/questions/58176287/cannot-link-c-using-tensorflow-c-api-tensorflow-cc-lib-on-windows-10-visual/58188482#58188482)

**Provide the exact sequence of commands / steps that you executed before running into the problem**
bazel build --config=monolithic //tensorflow:tensorflow_cc.dll  --verbose_failures
bazel build --config=monolithic //tensorflow:tensorflow_cc.lib  --verbose_failures

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
Logs of the bazel link-stage builds of the DLL and LIB are attached.
[build-dll.txt](https://github.com/tensorflow/tensorflow/files/3682666/build-dll.txt)
[build-lib.txt](https://github.com/tensorflow/tensorflow/files/3682667/build-lib.txt)

**Comment by angerson** [comment]
Thanks for your report and especially for attaching the command logs. Can you try and replicate this at `master`, please? (`master` is newer than `r2.0`, but has not had the default flags switched over yet, IIRC. If there were any bug fixes that would have helped this, they will have been made to `master`).

**Comment by Kramax** [comment]
I tried building the master branch checked out Oct 16, 2019. I could not build it with bazel 0.26.1 either. It did build with bazel 0.29.1. I got the same unresolved symbols when linking with my code as above and one more unresolved:
`
tfseg.obj : error LNK2019: unresolved external symbol "public: virtual __cdecl tensorflow::SavedModelBundleInterface::~SavedModelBundleInterface(void)" (??1SavedModelBundleInterface@tensorflow@@UEAA@XZ) referenced in function "int public: __cdecl tensorflow::SavedModelBundle::SavedModelBundle(void)::1'::dtor$0" (?dtor$0@?0???0SavedModelBundle@tensorflow@@QEAA@XZ@4HA)
`

**Comment by conradjones** [comment]
`I'm having similar issues.

**Comment by 07rafix** [comment]
Here is simple solution, I don't get it, it hangs for 2 weeks or more https://github.com/tensorflow/tensorflow/issues/23542, you can easily get rebuild import library .LIB with all missing symbols in a few seconds.

**Comment by amahendrakar** [comment]
@Kramax,
Is this still an issue?

Could you please update TensorFlow to the latest stable version v2.4.1 and check if you are facing the same error. Thanks!

**Comment by magondra** [comment]
Hi, 
I am struggling since several days with the same error as described above (except I use VS2019 and TF.2.4.1).

System information

    OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
    Windows 10
    Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
    NA
    TensorFlow installed from (source or binary):
    source
    TensorFlow version:
    r2.4.1
    Python version:
    3.6
    Installed using virtualenv? pip? conda?:
    No
    Bazel version (if compiling from source):
    3.1.0
    GCC/Compiler version (if compiling from source):
    Visual C++ 2019 
    CUDA/cuDNN version:
    10.2, 7.6.5
    GPU model and memory:
    NVIDIA Quadro P400
    
    Describe the problem
I am struggling since several days with the same error as described above (except I use VS2019 and TF.2.4.1).
I build tensorflow.dll, tensorflow.lib and install_headers thanks to Bazel. The three "Build completed successfully" (see the three logs).

When I try to link to tensorflow.lib I get unresolved symbols 
error LNK2019: "public: virtual __cdecl tensorflow::SavedModelBundleInterface::~SavedModelBundleInterface(void)" (??1SavedModelBundleInterface@tensorflow@@UEAA@XZ) référencé dans la fonction "int `public: __cdecl tensorflow::SavedModelBundleLite::SavedModelBundleLite(void)'::`1'::dtor$0" (?dtor$0@?0???0SavedModelBundleLite@tensorflow@@QEAA@XZ@4HA)".

I do not thing it is a link problem as the function TF_Version() works and return "2.4.1"

Provide the exact sequence of commands / steps that you executed before running into the problem

python ./configure.py
You have bazel 3.1.0 installed.
Please specify the location of python. [Default is C:\Users\bob\AppData\Local\Programs\Python\Python38\python.exe]:


Found possible Python library paths:
  C:\Users\bob\AppData\Local\Programs\Python\Python38\lib\site-packages
Please input the desired Python library path to use.  Default is [C:\Users\bob\AppData\Local\Programs\Python\Python38\lib\site-packages]

Do you wish to build TensorFlow with ROCm support? [y/N]: N
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: N
No CUDA support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]: 


Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]:
Eigen strong inline overridden.

Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: N
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=mkl_aarch64    # Build with oneDNN support for Aarch64.
        --config=monolithic     # Config for mostly static monolithic build.
        --config=ngraph         # Build with Intel nGraph support.
        --config=numa           # Build with NUMA support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
        --config=v2             # Build TensorFlow 2.x instead of 1.x.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=noaws          # Disable AWS S3 filesystem support.
        --config=nogcp          # Disable GCP support.
        --config=nohdfs         # Disable HDFS support.
        --config=nonccl         # Disable NVIDIA NCCL support.

bazel build --config=opt tensorflow:tensorflow.dll
bazel build --config=opt tensorflow:tensorflow.lib
bazel build --config=opt tensorflow:install_headers

Any other info / logs
Logs :
[dll.log](https://github.com/tensorflow/tensorflow/files/6459108/dll.log)
[headers.log](https://github.com/tensorflow/tensorflow/files/6459109/headers.log)
[lib.log](https://github.com/tensorflow/tensorflow/files/6459110/lib.log)
