### PR TITLE
Change TFL_MINIMUM_OS_VERSION to build TensorFlowLiteCMetal_framework on XCode 14.3

### PR DESCRIPTION
**Pull request by gastonmc**
The TensorFlow Lite framework build for Metal fails with the Xcode Version 14.3 (14E222b) when running the command: 
`bazel build -c opt --config=ios_fat --cxxopt=--std=c++17 //tensorflow/lite/ios:TensorFlowLiteCMetal_framework`

```
ERROR: /tensorflow/tensorflow/lite/delegates/gpu/common/transformations/BUILD:123:11: Compiling tensorflow/lite/delegates/gpu/common/transformations/global_pooling_to_reduce_op.cc failed: (Aborted): wrapped_clang_pp failed: error executing command external/local_config_cc/wrapped_clang_pp '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 -DNDEBUG ... (remaining 37 arguments skipped)

tensorflow/lite/delegates/gpu/common/transformations/global_pooling_to_reduce_op.cc:59:15: error: 'any_cast<const tflite::gpu::Pooling2DAttributes &>' is unavailable: introduced in iOS 12.0
        absl::any_cast<const Pooling2DAttributes&>(node->operation.attributes);
```

To solve the problem, you need to change the TFL_MINIMUM_OS_VERSION = "11.0" to TFL_MINIMUM_OS_VERSION = "12.0".

### CODE REVIEW

**Comment by gastonmc** [comment]
Hi @haozha111 ! Is there any way I can help accelerate this? let me know!

**Review by yishuangP — APPROVED** [review]

**Comment by gastonmc** [comment]
Fails on CI builds are not related to this changes, can we merge? @gbaned @haozha111

**Review by yishuangP — APPROVED** [review]

**Comment by gastonmc** [comment]
Hi @gbaned @yishuangP, this PR passed all the checks, can we marge?

**Review by gbaned — APPROVED** [review]

**Comment by gastonmc** [comment]
Hi @gbaned @yishuangP, why is this PR is blocked? It passed all the checks, can we marge?

**Comment by gbaned** [comment]
> Hi @gbaned @yishuangP, why is this PR blocked? It passed all the checks, can we marge?

Hi @gastonmc Sorry for the delay in response. It is getting the import error. 
Hi @yishuangP Can you please help on this PR?

**Comment by gbaned** [comment]
Hi @yishuangP Can you please help on this PR import?  Thank you!

**Comment by gbaned** [comment]
Hi @yishuangP Can you please help on this PR import? Thank you!

**Comment by gbaned** [comment]
Hi @yishuangP Can you please help on this PR import? Thank you!

**Comment by gbaned** [comment]
Hi @yishuangP Can you please help on this PR import? Thank you!

**Review by gbaned — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Comment by gbaned** [comment]
Hi @yishuangP Import/copybara check is showing it didn't affect any internal file. Can you please help to import these changes? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @yishuangP  Any update on this PR ? Please. Thank you!

**Comment by keerthanakadiri** [comment]
Hi @yishuangP Any update on this PR ? Please. Thank you!

**Comment by keerthanakadiri** [comment]
Hi @yishuangP Any update on this PR ? Please. Thank you!

**Comment by keerthanakadiri** [comment]
Hi @yishuangP Any update on this PR ? Please. Thank you!

**Comment by keerthanakadiri** [comment]
Hi @yishuangP, Any update on this PR ? Please. Thank you!

**Comment by keerthanakadiri** [comment]
Hi @yishuangP, Any update on this PR ? Please. Thank you!

**Comment by keerthanakadiri** [comment]
Hi @yishuangP, Any update on this PR ? Please. Thank you!

**Comment by keerthanakadiri** [comment]
Hi @yishuangP, Any update on this PR ? Please. Thank you!

**Comment by keerthanakadiri** [comment]
Hi @yishuangP, Any update on this PR ? Please. Thank you!

**Comment by keerthanakadiri** [comment]
Hi @yishuangP, Can you please take a look into this PR? Thank you!

**Comment by keerthanakadiri** [comment]
Hi @yishuangP, Can you please take a look into this PR? Thank you!

**Comment by keerthanakadiri** [comment]
I'm going  ahead and closing this PR, because there seems to be no response for a long time. If you're still interested in pursuing this , please feel free to reopen!
