### ISSUE TITLE
Build Tensorflow-master with sycl support - error computecpp

### ISSUE THREAD

**Issue by ferlix9o** [tensorflow/tensorflow#19393]
- Ubuntu 18.04
- TensorFlow installed from source 1.80
- Python version 2.7
- Bazel version 0.13.0
- GCC/Compiler 7.3
- OpenCL 1.2 AMD-APP 
- AMD Vega FE
- bazel build --config=sycl --verbose_failures --test_timeout 1600 //tensorflow/tools/pip_package:build_pip_package

I am trying to compile Tensorflow for my amd GPU, when i set it to --config=sycl it fails with the error :

`
INFO: Found 1 target...
ERROR: /home/frankie/Downloads/TENSORFLOW_BUILDs/tensorflow/tensorflow/contrib/tensor_forest/hybrid/BUILD:72:1: C++ compilation of rule '//tensorflow/contrib/tensor_forest/hybrid:utils' failed (Exit 1): computecpp failed: error executing command
  (cd /home/frankie/.cache/bazel/_bazel_frankie/d74dd7347ab17909423a2342e3b420ce/execroot/org_tensorflow && \
  exec env - \
    COMPUTECPP_TOOLKIT_PATH=/usr/local/computecpp \
    HOST_CXX_COMPILER=/usr/bin/g++ \
    HOST_C_COMPILER=/usr/bin/gcc \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python \
    PYTHON_LIB_PATH=/usr/local/lib/python2.7/dist-packages \
    TF_DOWNLOAD_CLANG=0 \
    TF_NEED_COMPUTECPP=1 \
    TF_NEED_CUDA=0 \
    TF_NEED_OPENCL_SYCL=1 \
  external/local_config_sycl/crosstool/computecpp -fPIE -fno-omit-frame-pointer -Wall -msse3 -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-std=c++11' -MD -MF bazel-out/k8-opt/bin/tensorflow/contrib/tensor_forest/hybrid/_objs/utils/tensorflow/contrib/tensor_forest/hybrid/core/ops/utils.pic.d '-frandom-seed=bazel-out/k8-opt/bin/tensorflow/contrib/tensor_forest/hybrid/_objs/utils/tensorflow/contrib/tensor_forest/hybrid/core/ops/utils.pic.o' -fPIC -DEIGEN_MPL2_ONLY -iquote . -iquote bazel-out/k8-opt/genfiles -iquote external/bazel_tools -iquote bazel-out/k8-opt/genfiles/external/bazel_tools -iquote external/eigen_archive -iquote bazel-out/k8-opt/genfiles/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/k8-opt/genfiles/external/local_config_sycl -iquote external/protobuf_archive -iquote bazel-out/k8-opt/genfiles/external/protobuf_archive -isystem external/eigen_archive -isystem bazel-out/k8-opt/genfiles/external/eigen_archive -isystem bazel-out/k8-opt/bin/external/eigen_archive -isystem external/local_config_sycl/sycl -isystem bazel-out/k8-opt/genfiles/external/local_config_sycl/sycl -isystem bazel-out/k8-opt/bin/external/local_config_sycl/sycl -isystem external/local_config_sycl/sycl/include -isystem bazel-out/k8-opt/genfiles/external/local_config_sycl/sycl/include -isystem bazel-out/k8-opt/bin/external/local_config_sycl/sycl/include -isystem external/protobuf_archive/src -isystem bazel-out/k8-opt/genfiles/external/protobuf_archive/src -isystem bazel-out/k8-opt/bin/external/protobuf_archive/src -DGEMMLOWP_ALLOW_SLOW_SCALAR_FALLBACK -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fno-canonical-system-headers -c tensorflow/contrib/tensor_forest/hybrid/core/ops/utils.cc -o bazel-out/k8-opt/bin/tensorflow/contrib/tensor_forest/hybrid/_objs/utils/tensorflow/contrib/tensor_forest/hybrid/core/ops/utils.pic.o)
In file included from tensorflow/contrib/tensor_forest/hybrid/core/ops/utils.cc:15:
In file included from ./tensorflow/contrib/tensor_forest/hybrid/core/ops/utils.h:20:
In file included from ./tensorflow/core/framework/tensor.h:19:
In file included from ./third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1:
In file included from external/eigen_archive/unsupported/Eigen/CXX11/Tensor:99:
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorDeviceSycl.h:163:19: error: no matching member function for call to 'get_access'
    auto ptr =buf.get_access<cl::sycl::access::mode::discard_write, cl::sycl::access::target::host_buffer>().get_pointer();
              ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/local_config_sycl/crosstool/../sycl/include/SYCL/buffer.h:593:3: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'accessMode'
  get_access() {
  ^
external/local_config_sycl/crosstool/../sycl/include/SYCL/buffer.h:611:53: note: candidate function template not viable: requires single argument 'cgh', but no arguments were provided
  accessor<T, dimensions, accessMode, accessTarget> get_access(
                                                    ^
external/local_config_sycl/crosstool/../sycl/include/SYCL/buffer.h:633:53: note: candidate function template not viable: requires 3 arguments, but 0 were provided
  accessor<T, dimensions, accessMode, accessTarget> get_access(
                                                    ^
external/local_config_sycl/crosstool/../sycl/include/SYCL/buffer.h:653:53: note: candidate function template not viable: requires at least 2 arguments, but 0 were provided
  accessor<T, dimensions, accessMode, accessTarget> get_access(
                                                    ^
external/local_config_sycl/crosstool/../sycl/include/SYCL/buffer.h:670:68: note: candidate function template not viable: requires 2 arguments, but 0 were provided
  accessor<T, dimensions, accessMode, access::target::host_buffer> get_access(
                                                                   ^
external/local_config_sycl/crosstool/../sycl/include/SYCL/buffer.h:684:68: note: candidate function template not viable: requires at least argument 'range', but no arguments were provided
  accessor<T, dimensions, accessMode, access::target::host_buffer> get_access(
                                                                   ^
In file included from tensorflow/contrib/tensor_forest/hybrid/core/ops/utils.cc:15:
In file included from ./tensorflow/contrib/tensor_forest/hybrid/core/ops/utils.h:20:
In file included from ./tensorflow/core/framework/tensor.h:19:
In file included from ./third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1:
In file included from external/eigen_archive/unsupported/Eigen/CXX11/Tensor:99:
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorDeviceSycl.h:195:61: error: no member named 'map_allocator' in namespace 'cl::sycl'
      auto src_buf = cl::sycl::buffer<uint8_t, 1, cl::sycl::map_allocator<uint8_t> >(static_cast<uint8_t*>(static_cast<void*>(const_cast<Index*>(src))), cl::sycl::range<1>(n));
                                                  ~~~~~~~~~~^
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorDeviceSycl.h:195:75: error: unexpected type name 'uint8_t': expected expression
      auto src_buf = cl::sycl::buffer<uint8_t, 1, cl::sycl::map_allocator<uint8_t> >(static_cast<uint8_t*>(static_cast<void*>(const_cast<Index*>(src))), cl::sycl::range<1>(n));
                                                                          ^
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorDeviceSycl.h:195:86: warning: expression result unused [-Wunused-value]
      auto src_buf = cl::sycl::buffer<uint8_t, 1, cl::sycl::map_allocator<uint8_t> >(static_cast<uint8_t*>(static_cast<void*>(const_cast<Index*>(src))), cl::sycl::range<1>(n));
                                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorDeviceSycl.h:198:31: error: expected unqualified-id
        auto src_acc =src_buf.template get_access<cl::sycl::access::mode::read, cl::sycl::access::target::global_buffer>(cgh);
                              ^
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorDeviceSycl.h:198:107: error: nested name specifier 'cl::sycl::access::target::' for declaration does not refer into a class, class templat
e or class template partial specialization
        auto src_acc =src_buf.template get_access<cl::sycl::access::mode::read, cl::sycl::access::target::global_buffer>(cgh);
                                                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~^
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorDeviceSycl.h:198:120: error: expected ';' at end of declaration
        auto src_acc =src_buf.template get_access<cl::sycl::access::mode::read, cl::sycl::access::target::global_buffer>(cgh);
                                                                                                                       ^
                                                                                                                       ;
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorDeviceSycl.h:217:62: error: no member named 'map_allocator' in namespace 'cl::sycl'
      auto dest_buf = cl::sycl::buffer<uint8_t, 1, cl::sycl::map_allocator<uint8_t> >(static_cast<uint8_t*>(dst), cl::sycl::range<1>(n));
                                                   ~~~~~~~~~~^
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorDeviceSycl.h:217:76: error: unexpected type name 'uint8_t': expected expression
      auto dest_buf = cl::sycl::buffer<uint8_t, 1, cl::sycl::map_allocator<uint8_t> >(static_cast<uint8_t*>(dst), cl::sycl::range<1>(n));
                                                                           ^
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorDeviceSycl.h:217:87: warning: expression result unused [-Wunused-value]
      auto dest_buf = cl::sycl::buffer<uint8_t, 1, cl::sycl::map_allocator<uint8_t> >(static_cast<uint8_t*>(dst), cl::sycl::range<1>(n));
                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorDeviceSycl.h:220:32: error: expected unqualified-id
        auto dst_acc =dest_buf.template get_access<cl::sycl::access::mode::discard_write, cl::sycl::access::target::global_buffer>(cgh);
                               ^
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorDeviceSycl.h:220:117: error: nested name specifier 'cl::sycl::access::target::' for declaration does not refer into a class, class templat
e or class template partial specialization
        auto dst_acc =dest_buf.template get_access<cl::sycl::access::mode::discard_write, cl::sycl::access::target::global_buffer>(cgh);
                                                                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~^
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorDeviceSycl.h:220:130: error: expected ';' at end of declaration
        auto dst_acc =dest_buf.template get_access<cl::sycl::access::mode::discard_write, cl::sycl::access::target::global_buffer>(cgh);
                                                                                                                                 ^
                                                                                                                                 ;
2 warnings and 11 errors generated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 8.290s, Critical Path: 7.83s
INFO: 2 processes, local.
FAILED: Build did NOT complete successfully
`

It compile well without sycl.

I have installed computecpp downloading the files from the official website (ComputeCpp-CE-0.8.0-Ubuntu.16.04-64bit.tar.gz) and coping them to /usr/local/computecpp, adding the variable with 

`export COMPUTECPP_PACKAGE_ROOT_DIR=/usr/local/computecpp/`

am i missing something ?
thanks !

**Comment by ferlix9o** [comment]
i got tensorflow compile using the right sources.

 i used this branch :

> https://github.com/lukeiwanski/tensorflow/tree/dev/amd_gpu


and Bazel 0.11.1

> https://github.com/bazelbuild/bazel/releases/download/0.11.1/bazel_0.11.1-linux-x86_64.deb

**Comment by inferrna** [comment]
Same error with ComputeCpp-CE-0.9.1.

**Comment by Rbiessy** [comment]
@inferrna the official TensorFlow repository doesn't have the recent changes needed by SYCL yet.
Please use the eigen_sycl branch of https://github.com/codeplaysoftware/tensorflow for now. It only supports TF 1.6 for now but we are working towards merging 1.9.

**Comment by gianks** [comment]
Hi i'm unable to compile with bazel 0.11.1/0.18.0 and computecpp 0.61/0.8/1.0.1 and using both  https://github.com/codeplaysoftware/tensorflow on the eigen_sycl branch and https://github.com/lukeiwanski/tensorflow/ on branch dev/amd_gpu. 

```
ERROR: /home/mlnode/tensorflowd1/tensorflow/python/eager/BUILD:190:1: C++ compilation of rule '//tensorflow/python/ea ger:python_eager_op_gen' failed (Exit 1)
In file included from tensorflow/python/eager/python_eager_op_gen.cc:27:
In file included from ./tensorflow/core/framework/types.h:23:
In file included from ./third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1:
In file included from external/eigen_archive/unsupported/Eigen/CXX11/Tensor:99:
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorDeviceSycl.h:163:19: error: no matching member functi on for call to 'get_access'
    auto ptr =buf.get_access<cl::sycl::access::mode::discard_write, cl::sycl::access::target::host_buffer>().get_poin ter();

```

I couldn't find any combination of repo/version that made the build happen.

**Comment by Rbiessy** [comment]
Hello @gianks,
I'm guessing you don't see this exact same error with the eigen_sycl branch as the TensorDeviceSycl.h file shouldn't look like that anymore.
Regarding my previous comment, TF 1.9 has now been merged :) As a rule you should always use the latest version of ComputeCpp and of the eigen_sycl branch from the [official Codeplay repository](https://github.com/codeplaysoftware/tensorflow). We used bazel 0.16.0, it seems bazel 0.17 and above don't work yet even with the most recent version of TF.
Lastly, we don't support Ubuntu 18.04 nor AmdGpuPro 18.30 but it could always work! If you have any issue please create a ticket in the Codeplay repository.

**Comment by gianks** [comment]
Hi @Rbiessy, thanks for the reply.
I'm confused, when you say you don't support 18.30, does it mean it is too new or you don't support AmdGpu?
I have installed in the last hour a new fresh 16.04 but the build is not succeding too so i don't understand which driver version is ok.

**Comment by Rbiessy** [comment]
Sorry, I meant it is too new. I am using amdgpu-pro 17.50 which you can get with
`wget --referer http://support.amd.com/ https://www2.ati.com/drivers/linux/ubuntu/amdgpu-pro-17.50-511655.tar.xz`
The driver won't affect your compile error though so feel free to create an issue for that. Make sure that your remove your cache folder, sometimes even a `bazel clean --expunge` is not enough.
It's good that you are trying Ubuntu 16.04. I know the build instructions aren't very clear yet, we are still working on updating the ones on the website!

**Comment by gianks** [comment]
Ok, here i am again...
TensorDeviceSycl.h:163:19: error: no matching member function for call to 'get_access'

Build fails here, last ComputeCpp 1.0.1.
As far as i have understood this is caused by a mismatch in the SYCL interface which got updated recently... but i don't know how to proceed more.

**Comment by gianks** [comment]
Something is still not working but we made a bunch of progresses!
Build was successful and running the MNIST convnet was done using GPU0!
But... i have 5 GPUs in my system and while clinfo and computecpp_info show all of them, querying tensorflow for available gpus reports just the first!
See here a list of the gpus according to TF:

> $ python3 list_gpus.py
> 2018-10-17 23:52:44.268968: I ./tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
> 2018-10-17 23:52:44.385308: I ./tensorflow/core/common_runtime/sycl/sycl_device.h:70] Found following OpenCL devices:
> 2018-10-17 23:52:44.385342: I ./tensorflow/core/common_runtime/sycl/sycl_device.h:72] id: 0, type: GPU, name: Ellesmere, vendor: Advanced Micro Devices, Inc., profile: FULL_PROFILE
> [name: "/device:CPU:0"
> device_type: "CPU"
> memory_limit: 268435456
> locality {
> }
> incarnation: 5429869323017416982
> , name: "/device:SYCL:0"
> device_type: "SYCL"
> memory_limit: 268435456
> locality {
> }
> incarnation: 7347791393919061653
> physical_device_desc: "id: 0, type: GPU, name: Ellesmere, vendor: Advanced Micro Devices, Inc., profile: FULL_PROFILE"
> ]
> 

See here computecpp_info:

> ********************************************************************************
> 
> ComputeCpp Info (CE 1.0.1)
> 
> SYCL 1.2.1 revision 3
> 
> ********************************************************************************
> 
> Toolchain information:
> 
> GLIBC version: 2.23
> GLIBCXX: 20160609
> This version of libstdc++ is supported.
> 
> ********************************************************************************
> 
> 
> Device Info:
> 
> Discovered 5 devices matching:
>   platform	: <any>
>   device type : <any>
> 
> --------------------------------------------------------------------------------
> Device 0:
> 
>   Device is supported                 	: UNTESTED - Vendor not tested on this OS
>   CL_DEVICE_NAME                      	: Ellesmere
>   CL_DEVICE_VENDOR                    	: Advanced Micro Devices, Inc.
>   CL_DRIVER_VERSION                   	: 2527.3
>   CL_DEVICE_TYPE                      	: CL_DEVICE_TYPE_GPU
> --------------------------------------------------------------------------------
> Device 1:
> 
>   Device is supported                 	: UNTESTED - Vendor not tested on this OS
>   CL_DEVICE_NAME                      	: Ellesmere
>   CL_DEVICE_VENDOR                    	: Advanced Micro Devices, Inc.
>   CL_DRIVER_VERSION                   	: 2527.3
>   CL_DEVICE_TYPE                      	: CL_DEVICE_TYPE_GPU
> --------------------------------------------------------------------------------
> Device 2:
> 
>   Device is supported                 	: UNTESTED - Vendor not tested on this OS
>   CL_DEVICE_NAME                      	: Ellesmere
>   CL_DEVICE_VENDOR                    	: Advanced Micro Devices, Inc.
>   CL_DRIVER_VERSION                   	: 2527.3
>   CL_DEVICE_TYPE                      	: CL_DEVICE_TYPE_GPU
> --------------------------------------------------------------------------------
> Device 3:
> 
>   Device is supported                 	: UNTESTED - Vendor not tested on this OS
>   CL_DEVICE_NAME                      	: Ellesmere
>   CL_DEVICE_VENDOR                    	: Advanced Micro Devices, Inc.
>   CL_DRIVER_VERSION                   	: 2527.3
>   CL_DEVICE_TYPE                      	: CL_DEVICE_TYPE_GPU
> --------------------------------------------------------------------------------
> Device 4:
> 
>   Device is supported                 	: UNTESTED - Vendor not tested on this OS
>   CL_DEVICE_NAME                      	: Ellesmere
>   CL_DEVICE_VENDOR                    	: Advanced Micro Devices, Inc.
>   CL_DRIVER_VERSION                   	: 2527.3
>   CL_DEVICE_TYPE                      	: CL_DEVICE_TYPE_GPU
> 
> If you encounter problems when using any of these OpenCL devices, please consult
> this website for known issues:
> https://computecpp.codeplay.com/releases/v1.0.1/platform-support-notes
> 
> ********************************************************************************

**Comment by Rbiessy** [comment]
Good to know that it built.
Unfortunately we don't support multiple GPUs at the moment. It would be a really good feature to have but it is not a priority for now. If all your devices reported by clinfo are the same and you want to use them all, I think we would just need to register all SYCL-compatible devices instead of just the first one.
In the more general case, if the SYCL devices are different, the user has way to know which SYCL device is which on the python side. As far as I know the user would only see "SYCL:0" and "SYCL:1" so we're limited by that.
I'll have a closer look at the simpler case to see if it really is as easy as I think it is.
