### ISSUE TITLE
TimeDistributed wrapper around DepthwiseConv2D broken (AttributeError) in 1.13

### ISSUE THREAD

**Issue by tjh48** [tensorflow/tensorflow#29438]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- Linux Ubuntu 18.04:
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from pip3:
- TensorFlow version b'v1.13.1-0-g6612da8951' 1.13.1
- Python version:
- CUDA/cuDNN version: 10.0.130 / 7.4.1
- GPU model and memory: NVIDIA K80; 11GB

**Describe the current behavior**
TimeDistributed wrapper around DepthwiseConv2D fails with AttributeError: 'tuple' object has no attribute 'dims'

**Describe the expected behavior**
Wrapper should succesfully apply to layer; previously worked in TF 1.11.0.

**Code to reproduce the issue**
```python
import tensorflow as tf
from tensorflow.keras.layers import Input, Conv2D, DepthwiseConv2D, TimeDistributed

test_td_input = Input(shape=(None, 1, 128, 8))
TimeDistributed(DepthwiseConv2D(depth_multiplier=1,
                                      kernel_size=(1, 4), strides=(1, 1)))(test_td_input)


**Other info / logs**
Traceback (most recent call last):
  File "time_distributed_bug.py", line 12, in <module>
    kernel_size=(1, 4), strides=(1, 1)))(test_td_input))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 538, in __call__
    self._maybe_build(inputs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 1603, in _maybe_build
    self.build(input_shapes)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/wrappers.py", line 216, in build
    self.layer.build(tuple(child_input_shape))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/convolutional.py", line 1811, in build
    if input_shape.dims[channel_axis].value is None:
AttributeError: 'tuple' object has no attribute 'dims'

```

**Comment by gadagashwini** [comment]
I am able to reproduce the issue with tf 1.13.1 on colab. Thanks!

**Comment by tanzhenyu** [comment]
Thanks for reporting this.
Roughly looking through stack trace, I think the issue is that TimeDistributed layer does not wrap input shape as TensorShape before calling Conv2D.build

I will see if I can fix it

**Comment by tanzhenyu** [comment]
Sorry I meant DepthWiseConv2D

**Comment by tanzhenyu** [comment]
Fixed and should be available in tf nightly. Let me know if it doesn't work for you.
