### ISSUE TITLE
ValueError: Cannot add function '__inference_Dataset_map_<lambda>_12' because a different function with the same name already exists.

### ISSUE THREAD

**Issue by dardaa** [tensorflow/tensorflow#47149]
Hi
 I am using ubuntu 16.04 , and tensorflow-gpu==1.14.0, I obtained this error 
" ValueError: Cannot add function '__inference_Dataset_map_<lambda>_12' because a different function with the same name already exists."

Please let me know if you have idea how I can resolve it? thank you in advance.

**Comment by Saduf2019** [comment]
@dardaa 
There is no support for tf 1.x, please upgrade to tf 2.x and let us know if you face nay issues.

**Comment by dardaa** [comment]
@Saduf2019 
thank you for your reply. the code is written with tf 1.x  so when i upgraded tensorflow, I obtained a lot of error, anyway i tried to correct some bugs but I did not able to resolve the following error """""""  TypeError: Dimension value must be integer or None or have an __index__ method, got value 'tf.float32' with type '<class 'tensorflow.python.framework.dtypes.DType'>'"""""""
I will attach the script python, please let me know if you know how i can resolve it.


[predict.txt](https://github.com/tensorflow/tensorflow/files/5981401/predict.txt)

**Comment by Saduf2019** [comment]
@dardaa 
I ran the code shared but face a different error, please find the [gist](https://colab.research.google.com/gist/Saduf2019/e983882514862d98280d15a585e9016c/untitled538.ipynb) here and share all dependencies such that we can replicate the issue faced.

**Comment by dardaa** [comment]
@Saduf2019 
I appreciate your time
so I need to share all the files and the weights, the datasets.. anyway I will attach a screenshot for the output maybe you can understand well the reason of the bug.
![Screenshot from 2021-02-15 23-48-32](https://user-images.githubusercontent.com/23746643/107999824-b7b32980-6fe8-11eb-8541-c3c537f4e479.png)

for the this """""     iterator = tf.data.Iterator.from_structure(tf.data.get_output_types(valDataset), tf.data.get_output_types(valDataset))
"""" 
it was """"""""""""""" iterator = tf.data.Iterator.from_structure(valDataset.output_types, valDataset.output_shapes)"""""""""""""""""""
but when i updated the tensorflow from 1.x to 2.x i did some modification.
i am for your reply.

**Comment by jvishnuvardhan** [comment]
@dardaa Can you please simple standalone code (with any public data) to reproduce the issue? The code code is too long and not complete. We recommend this kind of support related questions in Stackoverflow where there is a large community to support issues. GitHub is mainly for bugs and performance related issues. Thanks!

**Comment by dardaa** [comment]
hi 
i resolved the  previous error but i meet another error .
even i tried on colab server and i obtain the same issue: 
AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'decode'


	 [[{{node EagerPyFunc}}]]
	 [[IteratorGetNext]]

**Comment by dardaa** [comment]
the lines of codes caused the error are:
  # read image and label
    image = self.read_image(image_path.decode("utf-8"))
    label = self.read_image(label_path.decode("utf-8"))

**Comment by jvishnuvardhan** [comment]
I am closing this issue as this is more of a support type issue without a simple standalone code. Thanks!
 
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks
