### ISSUE TITLE
Tensor Flow not working as expected

### ISSUE THREAD

**Issue by chowdri** [tensorflow/tensorflow#91845]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

v2.17.0-4548-g0d5d03d2e83 2.17.0

### Custom code

No

### OS platform and distribution

elementary OS 7.1 (ubuntu 22.04)

### Current behavior?

My issue is similar to this: https://github.com/tensorflow/tensorflow/issues/79798
 However the solution of setting environment variable `ROCM_PATH` does not work for me. 

I'm using this guide to install and test tensorflow : https://rocm.docs.amd.com/projects/radeon/en/latest/docs/install/native_linux/install-tensorflow.html

in the code tensortest.py consists of the following: 

```
import tensorflow as tf
print("TensorFlow version:", tf.__version__)
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
model = tf.keras.models.Sequential([ tf.keras.layers.Flatten(input_shape=(28, 28)), tf.keras.layers.Dense(128, activation='relu'), tf.keras.layers.Dropout(0.2), tf.keras.layers.Dense(10)])
predictions = model(x_train[:1]).numpy()
tf.nn.softmax(predictions).numpy()
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()
model.compile(optimizer='adam',loss=loss_fn, metrics=['accuracy'])
model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test,  y_test, verbose=2)

```

### Standalone code to reproduce the issue

```shell
$ echo $ROCM_PATH

$ python3 tensortest.py
```

### Relevant log output

```shell
/opt/rocm-6.3.4/

2025-04-21 15:15:44.686577: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE3 SSE4.1 SSE4.2 AVX AVX2 AVX512F AVX512_VNNI AVX512_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
TensorFlow version: 2.17.0
/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
2025-04-21 15:15:45.795712: I external/local_xla/xla/stream_executor/rocm/rocm_executor.cc:920] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2025-04-21 15:15:45.795764: I external/local_xla/xla/stream_executor/rocm/rocm_executor.cc:920] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2025-04-21 15:15:47.712177: I external/local_xla/xla/stream_executor/rocm/rocm_executor.cc:920] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2025-04-21 15:15:47.712224: I external/local_xla/xla/stream_executor/rocm/rocm_executor.cc:920] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2025-04-21 15:15:47.712250: I external/local_xla/xla/stream_executor/rocm/rocm_executor.cc:920] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2025-04-21 15:15:47.712281: I external/local_xla/xla/stream_executor/rocm/rocm_executor.cc:920] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2025-04-21 15:15:47.713309: I external/local_xla/xla/stream_executor/rocm/rocm_executor.cc:920] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2025-04-21 15:15:47.713346: I external/local_xla/xla/stream_executor/rocm/rocm_executor.cc:920] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2025-04-21 15:15:47.713384: I external/local_xla/xla/stream_executor/rocm/rocm_executor.cc:920] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2025-04-21 15:15:47.713407: I external/local_xla/xla/stream_executor/rocm/rocm_executor.cc:920] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2025-04-21 15:15:47.713429: I external/local_xla/xla/stream_executor/rocm/rocm_executor.cc:920] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2025-04-21 15:15:47.713452: I external/local_xla/xla/stream_executor/rocm/rocm_executor.cc:920] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2025-04-21 15:15:47.713490: I external/local_xla/xla/stream_executor/rocm/rocm_executor.cc:920] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2025-04-21 15:15:47.713515: I external/local_xla/xla/stream_executor/rocm/rocm_executor.cc:920] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2025-04-21 15:15:47.713540: I external/local_xla/xla/stream_executor/rocm/rocm_executor.cc:920] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2025-04-21 15:15:47.713565: I external/local_xla/xla/stream_executor/rocm/rocm_executor.cc:920] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2025-04-21 15:15:47.713592: I external/local_xla/xla/stream_executor/rocm/rocm_executor.cc:920] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2025-04-21 15:15:47.713604: I tensorflow/core/common_runtime/gpu/gpu_device.cc:2021] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 15310 MB memory:  -> device: 0, name: Radeon RX 7900 GRE, pci bus id: 0000:03:00.0
2025-04-21 15:15:47.865754: I external/local_xla/xla/stream_executor/rocm/rocm_executor.cc:920] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2025-04-21 15:15:47.865781: I tensorflow/core/common_runtime/gpu/gpu_device.cc:2021] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 7660 MB memory:  -> device: 1, name: Radeon RX Vega, pci bus id: 0000:19:00.0
error: Failure when generating HSACO
error: Failure when generating HSACO
error: Failure when generating HSACO
error: Failure when generating HSACO
error: Failure when generating HSACO
error: Failure when generating HSACO
error: Failure when generating HSACO
error: Failure when generating HSACO
error: Failure when generating HSACO
error: Failure when generating HSACO
error: Failure when generating HSACO
error: Failure when generating HSACO
error: Failure when generating HSACO
2025-04-21 15:15:48.325635: E tensorflow/compiler/mlir/tools/kernel_gen/tf_framework_c_interface.cc:228] INTERNAL: Generating device code failed.
2025-04-21 15:15:48.326358: W tensorflow/core/framework/op_kernel.cc:1828] UNKNOWN: JIT compilation failed.
2025-04-21 15:15:48.326374: I tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: UNKNOWN: JIT compilation failed.
Traceback (most recent call last):
  File "/home/praful/tensortest.py", line 6, in <module>
    model = tf.keras.models.Sequential([ tf.keras.layers.Flatten(input_shape=(28, 28)), tf.keras.layers.Dense(128, activation='relu'), tf.keras.layers.Dropout(0.2), tf.keras.layers.Dense(10)])
  File "/usr/local/lib/python3.10/dist-packages/keras/src/models/sequential.py", line 76, in __init__
    self._maybe_rebuild()
  File "/usr/local/lib/python3.10/dist-packages/keras/src/models/sequential.py", line 141, in _maybe_rebuild
    self.build(input_shape)
  File "/usr/local/lib/python3.10/dist-packages/keras/src/layers/layer.py", line 228, in build_wrapper
    original_build_method(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/src/models/sequential.py", line 187, in build
    x = layer(x)
  File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/keras/src/backend/tensorflow/random.py", line 19, in _cast_seed
    seed = tf.cast(tf.math.floormod(seed, tf.int32.max - 1), dtype="int32")
tensorflow.python.framework.errors_impl.UnknownError: {{function_node __wrapped__FloorMod_device_/job:localhost/replica:0/task:0/device:GPU:0}} JIT compilation failed. [Op:FloorMod] name:
```

**Comment by Venkat6871** [comment]
Hi @chowdri ,
Apologies for the delay, and thank you for raising your concern here. I tried running your code on Colab using TensorFlow versions 2.17.0 and 2.18.0, and I did not encounter any issues. Could you please check on your end as well? I am providing a [gist](https://colab.sandbox.google.com/gist/Venkat6871/32b60c2436665918e39aacb48bf58f48/91845_tf_2-17-0-2-18-0-v.ipynb) for your reference. Please let me know if I made any mistakes.

Thank you!

**Comment by chowdri** [comment]
Yes. the code in tensortest.py ought to be correct. 
It's drawn from the rocm guide for tensorflow I have linked in the issue. 
I cant debug the problem by myself: whether it's an installation issue, pre-requisite issue, an environment issue or a driver issue. 
Having checked prior issues of this sort, the indicated solution was to explicitly state the rocm installation as an environment variable. I have exhausted that solution and yet have this problem continue. 
I have posted on tensorflow github because that's where the errors are pointing. I don't have the technical competence to isolate the issue on my own. 
The errors shown in the issue are repeatable on my system. 
If any system specific details are necessary, let me know. 

Any guidance in this matter is much appreciated.

**Comment by chowdri** [comment]
nevermind, this works with tensorflow 2.19.0. Please feel free to close the issue.

**Comment by Kayyuri** [comment]
Hi @chowdri,

Could you please confirm whether this issue has been resolved with the latest versions? If it has been resolved on your end and there are no further concerns, please feel free to close the issue.

Thanks!
