### PR TITLE
use 'typedef' instead of 'using' to compile on gcc4.8.2

### PR DESCRIPTION
**Pull request by raingo**
Currently, gcc 4.8.2 complains with the following error message:

```
In file included from tensorflow/core/distributed_runtime/rpc/grpc_master_service.cc:38:0:
./tensorflow/core/distributed_runtime/rpc/grpc_call.h:251:35: error: 'Tag' is not a class, namespace, or enumeration
   Tag request_received_tag_{this, Tag::kRequestReceived};
                                   ^
./tensorflow/core/distributed_runtime/rpc/grpc_call.h:252:32: error: 'Tag' is not a class, namespace, or enumeration
   Tag response_sent_tag_{this, Tag::kResponseSent};
                                ^
./tensorflow/core/distributed_runtime/rpc/grpc_call.h:253:28: error: 'Tag' is not a class, namespace, or enumeration
   Tag cancelled_tag_{this, Tag::kCancelled};                            ^
```

This PR proposes to use old fashioned typedef, and the build has passed with gcc4.8.2

### CODE REVIEW

File: tensorflow/core/distributed_runtime/rpc/grpc_call.h [hunk 1]
```diff
@@ -247,10 +247,10 @@ class Call : public UntypedCall<Service> {
 
   // Used as void* completion markers from grpc to indicate different
   // events of interest for a Call.
-  using typename UntypedCall<Service>::Tag;
-  Tag request_received_tag_{this, Tag::kRequestReceived};
-  Tag response_sent_tag_{this, Tag::kResponseSent};
-  Tag cancelled_tag_{this, Tag::kCancelled};
+  typedef typename UntypedCall<Service>::Tag _TTag;
```
Comment (mrry) [inline tensorflow/core/distributed_runtime/rpc/grpc_call.h]: Does the following work?

```c++
typedef typename UntypedCall<Service>::Tag Tag;
```

...and then can you revert the next three lines? (I don't have a copy of GCC 4.8.2 handy to test this.)

**Comment by raingo** [comment]
@mrry Yes, it works. Only one line is changed now.

**Comment by mrry** [comment]
Great, thanks!

**Comment by mrry** [comment]
@tensorflow-jenkins test this please.

**Comment by mrry** [comment]
@tensorflow-jenkins test this please.

**Comment by mrry** [comment]
That failure looks like a flake, but let's roll the dice again to see if we can get a clean build before submitting....
