### ISSUE TITLE
Build TF 2.9.1 with use ROCM 5.2.3 with GCC 12.2.0 failed, but succesfull build with use ROCM 5.2.3 with GCC 11.3.0 or with GCC 12.2.0 without use ROCM

### ISSUE THREAD

**Issue by perestoronin** [tensorflow/tensorflow#57371]
Build TF 2.9.1 with use ROCM 5.2.3 with GCC 12.2.0 failed,

but succesfull build with use ROCM 5.2.3 with GCC 11.3.0
or with GCC 12.2.0 without use ROCM

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

tf 2.9.1

### Custom Code

No

### OS Platform and Distribution

Gentoo

### Python version

3.10.6

### Bazel version

5.0.2

### GCC/Compiler version

12.2.0

### CUDA/cuDNN version

11.7.1/8.5.0.96

### GPU model and memory

AMD Vega Frontier 16Gb

### Current Behaviour?

```shell
Succesfull buid with gcc 12.2.0 as this done by use old gcc 11.3.0
```

### Standalone code to reproduce the issue

```shell
# Execution platform: @local_execution_config_platform//:platform
SUBCOMMAND: # //tensorflow:libtensorflow.so.2.9.1 [action 'Linking tensorflow/libtensorflow.so.2.9.1',
configuration: bazel-out/k8-collect2: error: ld returned 1 exit status
INFO: Elapsed time: 3957.177s, Critical Path: 165.85s
```

### Relevant log output

```shell
# Execution platform: @local_execution_config_platform//:platform
SUBCOMMAND: # //tensorflow:libtensorflow.so.2.9.1 [action 'Linking tensorflow/libtensorflow.so.2.9.1', configuration: e9286302664b4ab1cd1341b866a623627f93e9b8c897b9c18eb12e802620134e, execution platform: @local_execution_config_platform//:platform]
(cd /var/tmp/portage/sci-libs/tensorflow-2.9.1-r3/work/tensorflow-2.9.1-python3_10-bazel-base/execroot/org_tensorflow && \
  exec env - \
    GLIBCXX_USE_CXX11_ABI=0 \
    HOME=/var/tmp/portage/sci-libs/tensorflow-2.9.1-r3/homedir \
    KERAS_HOME=/var/tmp/portage/sci-libs/tensorflow-2.9.1-r3/temp/.keras \
    MLIR_CRASH_REPRODUCER_DIRECTORY=/var/tmp/portage/sci-libs/tensorflow-2.9.1-r3/temp/.crash \
    PATH=/var/tmp/portage/sci-libs/tensorflow-2.9.1-r3/temp/python3.10/bin:/usr/lib/portage/python3.10/ebuild-helpers/xattr:/usr/lib/portage/python3.10/ebuild-helpers:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/lib/llvm/14/bin:/usr/lib64/subversion/bin:/opt/cuda/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python3.10 \
    PYTHON_LIB_PATH=/usr/lib/python3.10/site-packages \
    ROCBLAS_TENSILE_LIBPATH=/usr/lib64/rocblas/library \
    ROCM_PATH=/usr \
    TF2_BEHAVIOR=1 \
    TF_SYSTEM_LIBS=curl,cython,gif,icu,libjpeg_turbo,lmdb,nasm,png,pybind11,zlib \
  external/local_config_rocm/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc @bazel-out/k8-opt/bin/tensorflow/libtensorflow.so.2.9.1-2.params)build.log here: https://gist.github.com/raw/c94573f1badbff781eabc359dfef20c2
# Configuration: e9286302664b4ab1cd1341b866a623627f93e9b8c897b9c18eb12e802620134e
# Execution platform: @local_execution_config_platform//:platform
ERROR: /var/tmp/portage/sci-libs/tensorflow-2.9.1-r3/work/tensorflow-2.9.1-python3_10/tensorflow/BUILD:1003:20: Linking tensorflow/libtensorflow.so.2.9.1 failed: (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /var/tmp/portage/sci-libs/tensorflow-2.9.1-r3/work/tensorflow-2.9.1-python3_10-bazel-base/execroot/org_tensorflow && \
  exec env - \
    GLIBCXX_USE_CXX11_ABI=0 \
    HOME=/var/tmp/portage/sci-libs/tensorflow-2.9.1-r3/homedir \
    KERAS_HOME=/var/tmp/portage/sci-libs/tensorflow-2.9.1-r3/temp/.keras \
    MLIR_CRASH_REPRODUCER_DIRECTORY=/var/tmp/portage/sci-libs/tensorflow-2.9.1-r3/temp/.crash \
    PATH=/var/tmp/portage/sci-libs/tensorflow-2.9.1-r3/temp/python3.10/bin:/usr/lib/portage/python3.10/ebuild-helpers/xattr:/usr/lib/portage/python3.10/ebuild-helpers:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/lib/llvm/14/bin:/usr/lib64/subversion/bin:/opt/cuda/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python3.10 \
    PYTHON_LIB_PATH=/usr/lib/python3.10/site-packages \
    ROCBLAS_TENSILE_LIBPATH=/usr/lib64/rocblas/library \
    ROCM_PATH=/usr \
    TF2_BEHAVIOR=1 \
    TF_SYSTEM_LIBS=curl,cython,gif,icu,libjpeg_turbo,lmdb,nasm,png,pybind11,zlib \
  external/local_config_rocm/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc @bazel-out/k8-opt/bin/tensorflow/libtensorflow.so.2.9.1-2.params)
# Configuration: e9286302664b4ab1cd1341b866a623627f93e9b8c897b9c18eb12e802620134e
# Execution platform: @local_execution_config_platform//:platform
bazel-out/k8-opt/bin/tensorflow/core/kernels/sparse/_objs/kernels/mat_mul_op.pic.o:mat_mul_op.cc:function tensorflow::CSRMatMulGPUOp<std::complex<float> >::Compute(tensorflow::OpKernelContext*): error: undefined reference to 'tensorflow::functor::CSRSparseMatrixTranspose<Eigen::GpuDevice, std::complex<float> >::operator()(tensorflow::OpKernelContext*, bool, tensorflow::CSRSparseMatrix const&, tensorflow::CSRSparseMatrix*)'
bazel-out/k8-opt/bin/tensorflow/core/kernels/sparse/_objs/kernels/mat_mul_op.pic.o:mat_mul_op.cc:function tensorflow::CSRMatMulGPUOp<double>::Compute(tensorflow::OpKernelContext*): error: undefined reference to 'tensorflow::functor::CSRSparseMatrixTranspose<Eigen::GpuDevice, double>::operator()(tensorflow::OpKernelContext*, bool, tensorflow::CSRSparseMatrix const&, tensorflow::CSRSparseMatrix*)'
bazel-out/k8-opt/bin/tensorflow/core/kernels/sparse/_objs/kernels/mat_mul_op.pic.o:mat_mul_op.cc:function tensorflow::CSRMatMulGPUOp<std::complex<double> >::Compute(tensorflow::OpKernelContext*): error: undefined reference to 'tensorflow::functor::CSRSparseMatrixTranspose<Eigen::GpuDevice, std::complex<double> >::operator()(tensorflow::OpKernelContext*, bool, tensorflow::CSRSparseMatrix const&, tensorflow::CSRSparseMatrix*)'
bazel-out/k8-opt/bin/tensorflow/core/kernels/sparse/_objs/kernels/mat_mul_op.pic.o:mat_mul_op.cc:function tensorflow::CSRMatMulGPUOp<float>::Compute(tensorflow::OpKernelContext*): error: undefined reference to 'tensorflow::functor::CSRSparseMatrixTranspose<Eigen::GpuDevice, float>::operator()(tensorflow::OpKernelContext*, bool, tensorflow::CSRSparseMatrix const&, tensorflow::CSRSparseMatrix*)'
bazel-out/k8-opt/bin/tensorflow/core/kernels/sparse/_objs/kernels/sparse_mat_mul_op.pic.o:sparse_mat_mul_op.cc:function tensorflow::CSRSparseMatMulGPUOp<Eigen::GpuDevice, float>::Compute(tensorflow::OpKernelContext*): error: undefined reference to 'tensorflow::functor::CSRSparseMatrixTranspose<Eigen::GpuDevice, float>::operator()(tensorflow::OpKernelContext*, bool, tensorflow::CSRSparseMatrix const&, tensorflow::CSRSparseMatrix*)'
bazel-out/k8-opt/bin/tensorflow/core/kernels/sparse/_objs/kernels/sparse_mat_mul_op.pic.o:sparse_mat_mul_op.cc:function tensorflow::CSRSparseMatMulGPUOp<Eigen::GpuDevice, float>::Compute(tensorflow::OpKernelContext*): error: undefined reference to 'tensorflow::functor::CSRSparseMatrixTranspose<Eigen::GpuDevice, float>::operator()(tensorflow::OpKernelContext*, bool, tensorflow::CSRSparseMatrix const&, tensorflow::CSRSparseMatrix*)'
bazel-out/k8-opt/bin/tensorflow/core/kernels/sparse/_objs/kernels/sparse_mat_mul_op.pic.o:sparse_mat_mul_op.cc:function tensorflow::CSRSparseMatMulGPUOp<Eigen::GpuDevice, double>::Compute(tensorflow::OpKernelContext*): error: undefined reference to 'tensorflow::functor::CSRSparseMatrixTranspose<Eigen::GpuDevice, double>::operator()(tensorflow::OpKernelContext*, bool, tensorflow::CSRSparseMatrix const&, tensorflow::CSRSparseMatrix*)'
bazel-out/k8-opt/bin/tensorflow/core/kernels/sparse/_objs/kernels/sparse_mat_mul_op.pic.o:sparse_mat_mul_op.cc:function tensorflow::CSRSparseMatMulGPUOp<Eigen::GpuDevice, double>::Compute(tensorflow::OpKernelContext*): error: undefined reference to 'tensorflow::functor::CSRSparseMatrixTranspose<Eigen::GpuDevice, double>::operator()(tensorflow::OpKernelContext*, bool, tensorflow::CSRSparseMatrix const&, tensorflow::CSRSparseMatrix*)'
bazel-out/k8-opt/bin/tensorflow/core/kernels/sparse/_objs/kernels/sparse_mat_mul_op.pic.o:sparse_mat_mul_op.cc:function tensorflow::CSRSparseMatMulGPUOp<Eigen::GpuDevice, std::complex<float> >::Compute(tensorflow::OpKernelContext*): error: undefined reference to 'tensorflow::functor::CSRSparseMatrixTranspose<Eigen::GpuDevice, std::complex<float> >::operator()(tensorflow::OpKernelContext*, bool, tensorflow::CSRSparseMatrix const&, tensorflow::CSRSparseMatrix*)'
bazel-out/k8-opt/bin/tensorflow/core/kernels/sparse/_objs/kernels/sparse_mat_mul_op.pic.o:sparse_mat_mul_op.cc:function tensorflow::CSRSparseMatMulGPUOp<Eigen::GpuDevice, std::complex<float> >::Compute(tensorflow::OpKernelContext*): error: undefined reference to 'tensorflow::functor::CSRSparseMatrixTranspose<Eigen::GpuDevice, std::complex<float> >::operator()(tensorflow::OpKernelContext*, bool, tensorflow::CSRSparseMatrix const&, tensorflow::CSRSparseMatrix*)'
bazel-out/k8-opt/bin/tensorflow/core/kernels/sparse/_objs/kernels/sparse_mat_mul_op.pic.o:sparse_mat_mul_op.cc:function tensorflow::CSRSparseMatMulGPUOp<Eigen::GpuDevice, std::complex<double> >::Compute(tensorflow::OpKernelContext*): error: undefined reference to 'tensorflow::functor::CSRSparseMatrixTranspose<Eigen::GpuDevice, std::complex<double> >::operator()(tensorflow::OpKernelContext*, bool, tensorflow::CSRSparseMatrix const&, tensorflow::CSRSparseMatrix*)'
bazel-out/k8-opt/bin/tensorflow/core/kernels/sparse/_objs/kernels/sparse_mat_mul_op.pic.o:sparse_mat_mul_op.cc:function tensorflow::CSRSparseMatMulGPUOp<Eigen::GpuDevice, std::complex<double> >::Compute(tensorflow::OpKernelContext*): error: undefined reference to 'tensorflow::functor::CSRSparseMatrixTranspose<Eigen::GpuDevice, std::complex<double> >::operator()(tensorflow::OpKernelContext*, bool, tensorflow::CSRSparseMatrix const&, tensorflow::CSRSparseMatrix*)'
collect2: error: ld returned 1 exit status
INFO: Elapsed time: 3957.177s, Critical Path: 165.85s
```
</details>

build.log here: https://gist.github.com/raw/c94573f1badbff781eabc359dfef20c2

**Comment by tilakrayal** [comment]
@perestoronin,
Could you please lower the GCC version to 9.3.1 and try to build Tensorflow, as 9.3.1 is a compatible version for tf v2.9. Thank you!

**Comment by perestoronin** [comment]
> @perestoronin, Could you please lower the GCC version to 9.3.1 and try to build Tensorflow, as 9.3.1 is a compatible version for tf v2.9. Thank you!

GCC 11.3.0 as 9.3.1 build TF 2.9.1 with TF_ROCM=1 succesfull, but only with GCC 12.2.0 and with TF_ROCM=1 failed build.

PS. GCC 12.2.0 build TF succesfull TF_ROCM=0, failed only if TF_ROCM=1 and GCC 12.2.0

**Comment by sanguinariojoe** [comment]
Same problem here, with ROCM 5.4.1. It fails with GCC 12.2.0 but works with GCC 11.3.0
