### ISSUE TITLE
SSL certification error

### ISSUE THREAD

**Issue by Rajendra-Gage** [tensorflow/tensorflow#1553]
I install the SSL certification but still got this error

please notify what i have to do

/usr/bin/pip run on Sat Mar 19 15:15:43 2016
Downloading/unpacking https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl
Cleaning up...
  Removing temporary dir /tmp/pip_build_trutech...
**Exception:**
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1198, in prepare_files
    do_download,
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1376, in unpack_url
    self.session,
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 546, in unpack_http_url
    resp = session.get(target_url, stream=True)
  File "/usr/share/python-wheels/requests-2.2.1-py2.py3-none-any.whl/requests/sessions.py", line 467, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 237, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/share/python-wheels/requests-2.2.1-py2.py3-none-any.whl/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python-wheels/requests-2.2.1-py2.py3-none-any.whl/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/python-wheels/requests-2.2.1-py2.py3-none-any.whl/requests/adapters.py", line 385, in send
    raise SSLError(e)
**SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed**

**Comment by YonatanSimson** [comment]
I got the same problem when trying to install tensorflow:

    sudo pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp27-none-linux_x86_64.whl

Try this solution:
http://stackoverflow.com/a/35277748/3481173
It worked for me on ubuntu

**Comment by girving** [comment]
@martinwicke: Have you seen this one?  @YonatanSimson: Do you know if this is still an issue?  Apologies for letting it fall through the cracks.

**Comment by YonatanSimson** [comment]
Hi Martin,

Thanks for the response. 

I typed in 
```
export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.9.0rc0-cp27-none-linux_x86_64.whl
sudo pip install --upgrade $TF_BINARY_URL
```

Both installation and import of tensorflow in python were successful. I am working on ubuntu 14.04 LTS in a virtual machine.

**Comment by girving** [comment]
Thanks @YonatanSimson!  Closing for now since it seems fixed.

**Comment by ods94065** [comment]
I've just run into this problem too, downloading the latest version of TensorFlow (Linux, x86_64, no-GPU, Python 3.4). In my case, downloading separately via curl didn't work either, and I got an error:

```
curl: (60) SSL certificate problem: certificate is not yet valid
```

Not yet valid??

In short, the problem was my clock was way behind. Resyncing my VM's clock fixed the problem.
