### ISSUE TITLE
centos7 gcc: error: unrecognized command line option '-std=c++14'

### ISSUE THREAD

**Issue by cheneyweb** [tensorflow/tensorflow#39633]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):CentOS Linux release 7.6.1810 (Core)
- TensorFlow installed from (source or binary): source
- TensorFlow version: r2.2
- Python version: 3.7
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 2.0
- GCC/Compiler version (if compiling from source):  7.3.1

**Describe the problem**

I follow the official build flow，but I met the the problem with 

gcc: error: unrecognized command line option '-std=c++14'

I have try install 
yum install devtoolset-7
scl enable devtoolset-7 bash

And when I type gcc --version，it show me 7.3.1

But when I run
./configure
bazel build --config=opt --config=monolithic //tensorflow/tools/lib_package:libtensorflow

It still show me 

gcc: error: unrecognized command line option '-std=c++14'

I have no idea how to solve this problem,please help me,thanks

**Comment by Saduf2019** [comment]
@cheneyweb 
Can you please refer to these links and let us know if it helps:
[Link](https://stackoverflow.com/questions/36245428/c-error-unrecognized-command-line-option-std-c14) [link2](https://unix.stackexchange.com/questions/265668/g-doesnt-recognize-standard-14-std-c14) #32677 #36892 #36896

**Comment by cheneyweb** [comment]
@Saduf2019 
I have read all the link before,the most close to my problem is 

https://github.com/tensorflow/tensorflow/issues/32677

I think the reason to cause this problem is the gcc of centos7 is 4.8.5，and official doc say tensorflow need to be build with gcc 7.3.1

and I follow issues/32677 to install gcc 7.3.1 by follow steps

yum install devtoolset-7
scl enable devtoolset-7 bash

after run above commands，I type gcc --version， it show me gcc version with 7.3.1

but it seem doesn't work with bazel build?

And then I try to copy gcc from /opt/rh/devtoolset-7/root/usr/bin/gcc to  /usr/bin/gcc  (cover)

and I run bazel build again, the -std=c++14 error change，and it show me another error

I guess it because gcc is not the only one I need to move，but I don't know how to move all fo the gcc 7.3.1

is there anyway to set gccpath for tensorflow build? or it hardcode gcc path for bazel?

**Comment by cheneyweb** [comment]
@Saduf2019 
when I run 

bazel clean --expunge

it's seem work and begin to compile

but when the progress come to [3000/6000]

it break and show me an error:

ERROR: /root/.cache/bazel/_bazel_root/b984a59284261e4303e87b6b828afcba/external/com_google_protobuf/BUILD:406:1: Linking of rule '@com_google_protobuf//:protoc' failed (Exit 1)
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/code_generator.o:code_generator.cc:function google::protobuf::compiler::ParseGeneratorParameter(std::string const&, std::vector<std::pair<std::string, std::string>, std::allocator<std::pair<std::string, std::string> > >*): error: undefined reference to 'std::__throw_out_of_range_fmt(char const*, ...)'
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/command_line_interface.o:command_line_interface.cc:function google::protobuf::io::StringOutputStream::~StringOutputStream(): error: undefined reference to 'operator delete(void*, unsigned long)'
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/command_line_interface.o:command_line_interface.cc:function non-virtual thunk to google::protobuf::compiler::CommandLineInterface::ErrorPrinter::~ErrorPrinter(): error: undefined reference to 'operator delete(void*, unsigned long)'
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/command_line_interface.o:command_line_interface.cc:function non-virtual thunk to google::protobuf::compiler::CommandLineInterface::ErrorPrinter::~ErrorPrinter(): error: undefined reference to 'operator delete(void*, unsigned long)'
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/command_line_interface.o:command_line_interface.cc:function google::protobuf::compiler::CommandLineInterface::ErrorPrinter::~ErrorPrinter(): error: undefined reference to 'operator delete(void*, unsigned long)'
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/command_line_interface.o:command_line_interface.cc:function google::protobuf::compiler::(anonymous namespace)::PluginName(std::string const&, std::string const&): error: undefined reference to 'std::__throw_out_of_range_fmt(char const*, ...)'
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/command_line_interface.o:command_line_interface.cc:function google::protobuf::compiler::CommandLineInterface::MemoryOutputStream::~MemoryOutputStream(): error: undefined reference to 'std::__throw_out_of_range_fmt(char const*, ...)'
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/command_line_interface.o:command_line_interface.cc:function google::protobuf::compiler::CommandLineInterface::GenerateDependencyManifestFile(std::vector<google::protobuf::FileDescriptor const*, std::allocator<google::protobuf::FileDescriptor const*> > const&, std::unordered_map<std::string, google::protobuf::compiler::CommandLineInterface::GeneratorContextImpl*, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, google::protobuf::compiler::CommandLineInterface::GeneratorContextImpl*> > > const&, google::protobuf::compiler::DiskSourceTree*): error: undefined reference to 'std::__throw_out_of_range_fmt(char const*, ...)'
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/java_helpers.o:java_helpers.cc:function google::protobuf::compiler::java::SortFieldsByNumber(google::protobuf::Descriptor const*): error: undefined reference to '__cxa_throw_bad_array_new_length'
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/objectivec_message.o:objectivec_message.cc:function google::protobuf::compiler::objectivec::(anonymous namespace)::SortFieldsByNumber(google::protobuf::Descriptor const*): error: undefined reference to '__cxa_throw_bad_array_new_length'
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/objectivec_message.o:objectivec_message.cc:function google::protobuf::compiler::objectivec::MessageGenerator::GenerateSource(google::protobuf::io::Printer*): error: undefined reference to '__cxa_throw_bad_array_new_length'
bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf/dynamic_message.o:dynamic_message.cc:function google::protobuf::DynamicMessageFactory::GetPrototypeNoLock(google::protobuf::Descriptor const*): error: undefined reference to '__cxa_throw_bad_array_new_length'
bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf_lite/extension_set.o:extension_set.cc:function google::protobuf::internal::ExtensionSet::~ExtensionSet(): error: undefined reference to 'operator delete[](void*, unsigned long)'
bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf_lite/extension_set.o:extension_set.cc:function google::protobuf::internal::ExtensionSet::GrowCapacity(unsigned long): error: undefined reference to 'operator delete[](void*, unsigned long)'
collect2: error: ld returned 1 exit status

**Comment by daverim** [comment]
If you want to change your version of gcc, try cleaning your bazel bazel clean --expunge or bazel sync before you try to build again.

**Comment by daverim** [comment]
Ah sorry, didn't see the previous message, looks like you can try

`BAZEL_LINKLIBS=-l%:libstdc++.a  bazel build --config=opt --config=monolithic //tensorflow/tools/lib_package:libtensorflow` 

according to #35867

**Comment by cheneyweb** [comment]
@daverim thank you very much. I have notice to #35867 too

And After I run the BAZEL_LINKLIBS=-l%:libstdc++.a     as prefix，it still gone show me another error:

/usr/local/node/tensorflow-r2.2/tensorflow/core/kernels/BUILD:3683:1: C++ compilation of rule '//tensorflow/core/kernels:matrix_square_root_op' failed (Exit 4)
gcc: internal compiler error: Killed (program cc1plus)

the final progress is [4,713 / 6,306]

**Comment by cheneyweb** [comment]
It finish !!!
@daverim  @Saduf2019 ,thank you very much.

the reason of above problem is memory out

I close this issue
