### ISSUE TITLE
cannot import name '__version__' from 'keras'

### ISSUE THREAD

**Issue by lmocsi** [tensorflow/tensorflow#55921]
Please go to Stack Overflow for help and support:

https://stackoverflow.com/questions/tagged/tensorflow

If you open a GitHub issue, here is our policy:

1.  It must be a bug, a feature request, or a significant problem with the
    documentation (for small docs fixes please send a PR instead).
2.  The form below must be filled out.
3.  It shouldn't be a TensorBoard issue. Those go
    [here](https://github.com/tensorflow/tensorboard/issues).

**Here's why we have that policy**: TensorFlow developers respond to issues. We want to focus on work that benefits the whole community, e.g., fixing bugs and adding features. Support only helps individuals. GitHub also notifies thousands of people when issues are filed. We want them to see you communicating an interesting problem, rather than being redirected to Stack Overflow.

------------------------

### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**:
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**:
-   **TensorFlow installed from (source or binary)**:
-   **TensorFlow version (use command below)**:
-   **Python version**:
-   **Bazel version (if compiling from source)**:
-   **GCC/Compiler version (if compiling from source)**:
-   **CUDA/cuDNN version**:
-   **GPU model and memory**:
-   **Exact command to reproduce**:

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with:

```bash
python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
```

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by lmocsi** [comment]
tf.version.GIT_VERSION: v2.8.0-rc1-32-g3f878cff5b6
tf.version.VERSION: 2.8.0
TF installed from binary
OS: win11
Python: 3.7.5
CUDA: cuda_11.6.2_511.65_windows.exe
cuDNN: cudnn-windows-x86_64-8.4.0.27_cuda11.6-archive.zip
GPU: MSI Nvidia Geforce RTX 3060, 12 GB 

These imports worked on TF 2.3.4, but give "cannot import name '__version__' from 'keras'" on TF 2.8:
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import Activation
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Dense
from tensorflow.keras import backend as K

**Comment by chunduriv** [comment]
@lmocsi, 

I don't see any issue in your imports and I was able to execute the code successfully using `TF2.8`. 

Can you please run the code snippet below on your machine and let me know the output?

```
import tensorflow as tf
print (tf.__version__)
from tensorflow import keras
print (keras.__version__)
```
According to [tested build configurations](https://www.tensorflow.org/install/source_windows#gpu) the compatible versions for `TF2.8` are as shown below

![image](https://user-images.githubusercontent.com/74177924/166859564-7cf87555-41b3-4312-9fb4-c82a049a5bdb.png)


To investigate further, Can you please let us know the steps that you have followed to install Keras/ Tensorflow? Thank you.

**Comment by lmocsi** [comment]
I had Keras / Tensorflow installed for a while now, I always used 'pip install --upgrade xxx' to keep them up-to-date.

The result of the above code are:
2.8.0
Traceback (most recent call last):
  File "a.py", line 4, in <module>
    print (keras.__version__)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow\python\util\lazy_loader.py", line 58, in __getattr__
    module = self._load()
  File "C:\Program Files\Python37\lib\site-packages\tensorflow\python\util\lazy_loader.py", line 41, in _load
    module = importlib.import_module(self.__name__)
  File "C:\Program Files\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Program Files\Python37\lib\site-packages\keras\__init__.py", line 25, in <module>
    from keras import models
  File "C:\Program Files\Python37\lib\site-packages\keras\models.py", line 20, in <module>
    from keras import metrics as metrics_module
  File "C:\Program Files\Python37\lib\site-packages\keras\metrics.py", line 24, in <module>
    from keras import activations
  File "C:\Program Files\Python37\lib\site-packages\keras\activations.py", line 20, in <module>
    from keras.layers import advanced_activations
  File "C:\Program Files\Python37\lib\site-packages\keras\layers\__init__.py", line 23, in <module>
    from keras.engine.input_layer import Input
  File "C:\Program Files\Python37\lib\site-packages\keras\engine\input_layer.py", line 21, in <module>
    from keras.engine import base_layer
  File "C:\Program Files\Python37\lib\site-packages\keras\engine\base_layer.py", line 43, in <module>
    from keras.mixed_precision import loss_scale_optimizer
  File "C:\Program Files\Python37\lib\site-packages\keras\mixed_precision\loss_scale_optimizer.py", line 18, in <module>
    from keras import optimizers
  File "C:\Program Files\Python37\lib\site-packages\keras\optimizers\__init__.py", line 1, in <module>
    from tensorflow.keras.optimizers import *
  File "C:\Program Files\Python37\lib\site-packages\keras\api\_v2\keras\__init__.py", line 8, in <module>
    from keras import __version__
ImportError: cannot import name '__version__' from 'keras' (C:\Program Files\Python37\lib\site-packages\keras\__init__.py)

**Comment by chunduriv** [comment]
@lmocsi,

It seems there was an issue in `keras` upgrade. Please can you uninstall both Tensorflow and Keras from your machine and install tensorflow only as shown below 

`!pip install tensorflow
`

After successful installation of Tensorflow, Please can you run below code snippet again and let us know your output?

```
import tensorflow as tf
print (tf.__version__)
from tensorflow import keras
print (keras.__version__)
```
Thank you.

**Comment by RatanPrakash** [comment]
2.13.0-rc1
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[29], line 4
      2 print (tf.__version__)
      3 from tensorflow import keras
----> 4 print (keras.__version__)

AttributeError: module 'tensorflow.keras' has no attribute '__version__'

**Comment by liuxi1998** [comment]
AttributeError: module 'tensorflow.keras' has no attribute '__version__'

**Comment by parsanoori** [comment]
Still have this problem on 2024.

**Comment by Soleonmon** [comment]
Problem solved for my case:

my issues were these two libraries:
from keras.models import Sequential
from keras.layers import Dense

problem solved, after changing to these:
from keras.api.models import Sequential
from keras.api.layers import Dense

please look back on your keras file, if you have multiple model and layers files in your keras folder then you should change it accordingly. My models and layers were inside keras.api.models, then it works for my case.

Hope this will help, thanks
