### PR TITLE
Fix the name property for the _UnreadVariable class in eager mode

### LINKED ISSUE #21384: _UnreadVariable name property fails in TF 1.10-rc1
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOSX 10.13.6
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.10.0-rc0-18-ge5e9a8f4e9 1.10.0-rc1
- **Python version**: 3.6.5
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: `tfe.Variable(1).assign(2).name` in eager mode.

### Describe the problem
In eager mode, the result of an assignment is an instance of the class `tensorflow.python.ops.resource_variable_ops._UnreadVariable`. When you call its `name` property, it tries to access `self._parent_op.name`, but its `_parent_op` attribute is `None`, so there is an exception. This is a regression in TF 1.10-rc1, since it worked fine in TF 1.9.0.

### Source code / logs

```python
import tensorflow as tf
import tensorflow.contrib.eager as tfe
tf.enable_eager_execution()

tfe.Variable(1).assign(2).name
```

Outputs the following exception:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ageron/.virtualenvs/ml/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1082, in name
    return self._parent_op.name
AttributeError: 'NoneType' object has no attribute 'name'
```

Since `str()` and `repr()` use the `name` property, they fail as well. This makes it impossible to call `assign()` in a Python shell, since the shell automatically tries to display the output:

```python
>>> import tensorflow as tf
>>> import tensorflow.contrib.eager as tfe
>>> tf.enable_eager_execution()
>>> tfe.Variable(1).assign(2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ageron/.virtualenvs/ml/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 264, in __repr__
    self.name, self.get_shape(), self.dtype.name,
  File "/Users/ageron/.virtualenvs/ml/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1082, in name
    return self._parent_op.name
AttributeError: 'NoneType' object has no attribute 'name'
```

### PR DESCRIPTION
**Pull request by ageron**
Fixes #21384 
This works, but I'm not entirely sure this solution is the right approach, your comments are most welcome.

### CODE REVIEW

**Comment by alextp** [comment]
Can you add a test?

Also, I think returning self in eager mode is perfectly fine and simpler than this.

**Review by alextp — APPROVED** [review]
I think merging this is fine, but a test in the future would be better.

**Comment by ageron** [comment]
Thanks for merging, I'll make sure to add tests next time.  Cheers!
