### ISSUE TITLE
Error while compiling tensorflow from sources

### ISSUE THREAD

**Issue by AnabelGRios** [tensorflow/tensorflow#8462]
Hello, I am trying to install tensorflow from sources in a server where I haven't root access, so I can't update Cuda nor cuDNN. However, the versions installed are currently supported as said [here](https://www.tensorflow.org/install/install_sources).

### Environment info
Operating System: Ubuntu 14.04.4 LTS
gcc version: 4.8.4
python 2.7

Installed version of CUDA and cuDNN:
Cuda compilation tools, release 7.5, V7.5.17
CUDNN_MAJOR 5  CUDNN_MINOR 0  CUDNN_PATCHLEVEL 4
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
```
ls -l /usr/local/cuda/lib64/libcud*
-rw-r--r-- 1 root root 322936 Aug 15  2015 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root     16 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root     19 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root 383336 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so.7.5.18
-rw-r--r-- 1 root root 720192 Aug 15  2015 /usr/local/cuda/lib64/libcudart_static.a
```

If installed from source, provide

1. The commit hash (`git rev-parse HEAD`): 12a98726e769e988f6368a029ec2f5b0ac3ccbd4
2. The output of `bazel version`:  Build label: 0.4.4

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
[#5191](https://github.com/tensorflow/tensorflow/issues/5191)
[#817](https://github.com/tensorflow/tensorflow/issues/817)
http://stackoverflow.com/questions/42756614/tensorflow-compiling-from-source-c-compilation-of-rule-tensorflow-stream-e
[#3074](https://github.com/tensorflow/tensorflow/issues/3074)
[#3360](https://github.com/tensorflow/tensorflow/issues/3360)
[#8061](https://github.com/tensorflow/tensorflow/issues/8061)

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
The configure works fine but when I run `bazel build --config=opt --config=cuda --verbose_failures  //tensorflow/tools/pip_package:build_pip_package` I get the following error:

```
ERROR: /home/angomez/tensorflow_cuda/tensorflow/tensorflow/stream_executor/BUILD:39:1: C++ compilation of rule '//tensorflow/stream_executor:cuda_platform' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command
  (cd /home/angomez/.cache/bazel/_bazel_angomez/95301c24f4425af6d9c850e03508fc5b/execroot/tensorflow && \
  exec env - \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-march=native' -D_FORCE_INLINES '-std=c++11' '-march=native' -MD -MF bazel-out/local_linux-opt/bin/tensorflow/stream_executor/_objs/cuda_platform/tensorflow/stream_executor/cuda/cuda_dnn.pic.d '-frandom-seed=bazel-out/local_linux-opt/bin/tensorflow/stream_executor/_objs/cuda_platform/tensorflow/stream_executor/cuda/cuda_dnn.pic.o' -fPIC -DEIGEN_MPL2_ONLY -DTENSORFLOW_USE_JEMALLOC -iquote . -iquote bazel-out/local_linux-opt/genfiles -iquote external/jemalloc -iquote bazel-out/local_linux-opt/genfiles/external/jemalloc -iquote external/bazel_tools -iquote bazel-out/local_linux-opt/genfiles/external/bazel_tools -iquote external/protobuf -iquote bazel-out/local_linux-opt/genfiles/external/protobuf -iquote external/eigen_archive -iquote bazel-out/local_linux-opt/genfiles/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/local_linux-opt/genfiles/external/local_config_sycl -iquote external/gif_archive -iquote bazel-out/local_linux-opt/genfiles/external/gif_archive -iquote external/jpeg -iquote bazel-out/local_linux-opt/genfiles/external/jpeg -iquote external/com_googlesource_code_re2 -iquote bazel-out/local_linux-opt/genfiles/external/com_googlesource_code_re2 -iquote external/farmhash_archive -iquote bazel-out/local_linux-opt/genfiles/external/farmhash_archive -iquote external/highwayhash -iquote bazel-out/local_linux-opt/genfiles/external/highwayhash -iquote external/png_archive -iquote bazel-out/local_linux-opt/genfiles/external/png_archive -iquote external/zlib_archive -iquote bazel-out/local_linux-opt/genfiles/external/zlib_archive -iquote external/local_config_cuda -iquote bazel-out/local_linux-opt/genfiles/external/local_config_cuda -isystem external/jemalloc/include -isystem bazel-out/local_linux-opt/genfiles/external/jemalloc/include -isystem external/bazel_tools/tools/cpp/gcc3 -isystem external/protobuf/src -isystem bazel-out/local_linux-opt/genfiles/external/protobuf/src -isystem external/eigen_archive -isystem bazel-out/local_linux-opt/genfiles/external/eigen_archive -isystem external/gif_archive/lib -isystem bazel-out/local_linux-opt/genfiles/external/gif_archive/lib -isystem external/farmhash_archive/src -isystem bazel-out/local_linux-opt/genfiles/external/farmhash_archive/src -isystem external/png_archive -isystem bazel-out/local_linux-opt/genfiles/external/png_archive -isystem external/zlib_archive -isystem bazel-out/local_linux-opt/genfiles/external/zlib_archive -isystem external/local_config_cuda/cuda -isystem bazel-out/local_linux-opt/genfiles/external/local_config_cuda/cuda -isystem external/local_config_cuda/cuda/include -isystem bazel-out/local_linux-opt/genfiles/external/local_config_cuda/cuda/include -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fno-canonical-system-headers -c tensorflow/stream_executor/cuda/cuda_dnn.cc -o bazel-out/local_linux-opt/bin/tensorflow/stream_executor/_objs/cuda_platform/tensorflow/stream_executor/cuda/cuda_dnn.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
tensorflow/stream_executor/cuda/cuda_dnn.cc: In instantiation of 'cudnnStatus_t perftools::gputools::cuda::wrap::WrapperShim__cudnnSetRNNDescriptor::operator()(perftools::gputools::cuda::CUDAExecutor*, Args ...) [with Args = {cudnnRNNStruct*, int, int, cudnnDropoutStruct*, cudnnRNNInputMode_t, cudnnDirectionMode_t, cudnnRNNMode_t, cudnnDataType_t}]':
tensorflow/stream_executor/cuda/cuda_dnn.cc:986:50:   required from here
tensorflow/stream_executor/cuda/cuda_dnn.cc:140:46: error: invalid conversion from 'cudnnDropoutStruct*' to 'int' [-fpermissive]
       cudnnStatus_t retval = ::__name(args...);                    \
...
```
The complete error log is here http://pastebin.com/VXKnh8ga

### What other attempted solutions have you tried?
I've tried to compile with gcc version 4.8 since I've seen [this](http://stackoverflow.com/questions/37313212/tensorflow-bazel-build-failing), but it didn't work.

Thank you!

**Comment by PhilJd** [comment]
Hi,
to me this looks like cudnn isn't installed on your machine or is located at a different path than ` /usr/local/cuda/lib64/`. If it's installed in the cuda directory, `ls -l /path/to/cuda/lib/libcud*` should usually also include some output like `/usr/local/cuda/lib64/libcudnn.so.5 -> libcudnn.so.5.1.5`.
So you either need to find the path where cudnn lives or you could try the solution below.

To install cuda and cudnn you don't need root permissions on your machine, as long as your drivers are recent enough to support a specific cuda version:

### Local installation of cuda and cudnn
Download [Cuda](https://developer.nvidia.com/cuda-downloads) (download the .run file) and [Cudnn](https://developer.nvidia.com/cudnn) (needs an account). 

- Execute the cuda run file and install cuda to a local path, for example $HOME/lib/cuda-7.5/
    - Don't create a symlink to /usr/local/cuda.
    - Don't install the nvidia-driver, ignore the incomplete installation warning at the end of the cuda installation.
- Extract the cudnn folder and copy the files in the cudnn-subfolder to the same cuda-8.0 subfolders.

Now you can specify ` $HOME/lib/cuda-7.5/` or whatever your directory is when running the tensorflow configure script.

**Comment by AnabelGRios** [comment]
Hi! 
No, Cudnn isn't installed in `/usr/local/cuda/lib64`, it is installed in `/opt/cuda/lib64`, which is the path I give to the tensorflow configure script when asking for Cudnn directory. Is it necessary for Cudnn to be installed in `/usr/local/cuda/lib64` i.e., the same directory as Cuda?

I'm going to try the local installation of Cuda and Cudnn.
Thank you for your answer!

**Comment by AnabelGRios** [comment]
Hello,
I asked the system operator to copy the cudnn files to the cuda directory, `/usr/local/cuda`, and now the output of `ls -l /path/to/cuda/lib/libcud*` is the following:
```
ls -l /usr/local/cuda/lib64/libcud*
-rw-r--r-- 1 root root 322936 Aug 15  2015 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root     16 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root     19 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root 383336 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so.7.5.18
-rw-r--r-- 1 root root 720192 Aug 15  2015 /usr/local/cuda/lib64/libcudart_static.a
lrwxrwxrwx 1 root root     27 Mar 21 16:03 /usr/local/cuda/lib64/libcudnn.so -> /opt/cuda/lib64/libcudnn.so
lrwxrwxrwx 1 root root     29 Mar 21 16:04 /usr/local/cuda/lib64/libcudnn.so.5 -> /opt/cuda/lib64/libcudnn.so.5
lrwxrwxrwx 1 root root     33 Mar 21 16:04 /usr/local/cuda/lib64/libcudnn.so.5.0.4 -> /opt/cuda/lib64/libcudnn.so.5.0.4
lrwxrwxrwx 1 root root     33 Mar 21 16:04 /usr/local/cuda/lib64/libcudnn_static.a -> /opt/cuda/lib64/libcudnn_static.a
```
However, the error in the bazel build command is still there.

**Comment by PhilJd** [comment]
Hi,
some ideas to debug:
- Maybe your cudnn version is somehow incompatible with the cuda version, for example if cuda was installed via apt and cudnn was installed manually. Ubuntu 14.04 currently has cudnn version 5.0.{5,6} and 5.1.{3, 5, 10} in the repos (says `apt-cache madison libcudnn5`. You seem to have version 5.0.4. Probably try the local solution with one of the versions above.
- Try to run bazel clean manually before running ./configure
- Explicitly state the cuda version, or maybe even better overwrite all default values (even if they match your requirements)
- Did you try a local install of cuda-8.0? #5447 mentions the tensorflow team only tests with cuda 8.0. This issue also seems to be related to yours.

If all of the above doesn't work, it might be useful to paste the output of the ./configure script.

Good luck!

**Comment by nmoenning** [comment]
I get the same error when compiling from code.

I want to update my TF from 0.12.0 (which I had compiled myself, too) to the most recent version. The current settings work fine: Ubuntu 16.04 LTS with gcc 4.9.3, TF 0.12.0, Cuda 8.0, cudNN 5.1.5, python 3.5 But compiling the most recent version of TF (with the same setup) returns the following error:

`ni@WV8782:~/Downloads/tensorflow$ bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package` produces 
```
ERROR: /home/ni/Downloads/tensorflow/tensorflow/stream_executor/BUILD:39:1: C++ compilation of rule '//tensorflow/stream_executor:cuda_platform' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /home/ni/.cache/bazel/_bazel_ni/ee42072b03580a9e2812c30ca6c3e85a/execroot/tensorflow && \
  exec env - \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-march=native' '-std=c++11' '-march=native' -MD -MF bazel-out/local_linux-py3-opt/bin/tensorflow/stream_executor/_objs/cuda_platform/tensorflow/stream_executor/cuda/cuda_blas.pic.d '-frandom-seed=bazel-out/local_linux-py3-opt/bin/tensorflow/stream_executor/_objs/cuda_platform/tensorflow/stream_executor/cuda/cuda_blas.pic.o' -fPIC -DEIGEN_MPL2_ONLY -DTENSORFLOW_USE_JEMALLOC -iquote . -iquote bazel-out/local_linux-py3-opt/genfiles -iquote external/jemalloc -iquote bazel-out/local_linux-py3-opt/genfiles/external/jemalloc -iquote external/bazel_tools -iquote bazel-out/local_linux-py3-opt/genfiles/external/bazel_tools -iquote external/protobuf -iquote bazel-out/local_linux-py3-opt/genfiles/external/protobuf -iquote external/eigen_archive -iquote bazel-out/local_linux-py3-opt/genfiles/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/local_linux-py3-opt/genfiles/external/local_config_sycl -iquote external/gif_archive -iquote bazel-out/local_linux-py3-opt/genfiles/external/gif_archive -iquote external/jpeg -iquote bazel-out/local_linux-py3-opt/genfiles/external/jpeg -iquote external/com_googlesource_code_re2 -iquote bazel-out/local_linux-py3-opt/genfiles/external/com_googlesource_code_re2 -iquote external/farmhash_archive -iquote bazel-out/local_linux-py3-opt/genfiles/external/farmhash_archive -iquote external/highwayhash -iquote bazel-out/local_linux-py3-opt/genfiles/external/highwayhash -iquote external/png_archive -iquote bazel-out/local_linux-py3-opt/genfiles/external/png_archive -iquote external/zlib_archive -iquote bazel-out/local_linux-py3-opt/genfiles/external/zlib_archive -iquote external/local_config_cuda -iquote bazel-out/local_linux-py3-opt/genfiles/external/local_config_cuda -isystem external/jemalloc/include -isystem bazel-out/local_linux-py3-opt/genfiles/external/jemalloc/include -isystem external/bazel_tools/tools/cpp/gcc3 -isystem external/protobuf/src -isystem bazel-out/local_linux-py3-opt/genfiles/external/protobuf/src -isystem external/eigen_archive -isystem bazel-out/local_linux-py3-opt/genfiles/external/eigen_archive -isystem external/gif_archive/lib -isystem bazel-out/local_linux-py3-opt/genfiles/external/gif_archive/lib -isystem external/farmhash_archive/src -isystem bazel-out/local_linux-py3-opt/genfiles/external/farmhash_archive/src -isystem external/png_archive -isystem bazel-out/local_linux-py3-opt/genfiles/external/png_archive -isystem external/zlib_archive -isystem bazel-out/local_linux-py3-opt/genfiles/external/zlib_archive -isystem external/local_config_cuda/cuda -isystem bazel-out/local_linux-py3-opt/genfiles/external/local_config_cuda/cuda -isystem external/local_config_cuda/cuda/include -isystem bazel-out/local_linux-py3-opt/genfiles/external/local_config_cuda/cuda/include -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fno-canonical-system-headers -c tensorflow/stream_executor/cuda/cuda_blas.cc -o bazel-out/local_linux-py3-opt/bin/tensorflow/stream_executor/_objs/cuda_platform/tensorflow/stream_executor/cuda/cuda_blas.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
```


Thanks for your help, PhilJd.

> Maybe your cudnn version is somehow incompatible with the cuda version, for example if cuda was installed via apt and cudnn was installed manually. Ubuntu 14.04 currently has cudnn version 5.0.{5,6} and 5.1.{3, 5, 10} in the repos (says apt-cache madison libcudnn5. You seem to have version 5.0.4. Probably try the local solution with one of the versions above.

Doesn't seem to be the case considering that previous TensorFlow version runs smoothly.

> Try to run bazel clean manually before running ./configure

Tried this. Sadly, the same error.

> Explicitly state the cuda version, or maybe even better overwrite all default values (even if they match your requirements)

Tried this, too. Same error.

Does anyone have some recommendations or even a solution? I appreciate your help.

**Comment by PhilJd** [comment]
It seems your error message is incomplete - does the same `invalid conversion` error follow?

**Comment by AnabelGRios** [comment]
Hi, I've been trying to install tensorflow with the ideas you gave me.
I tried this

> Try to run bazel clean manually before running ./configure

and this

> Explicitly state the cuda version, or maybe even better overwrite all default values (even if they match your requirements)

but it didn't work. Then I tried this

> Maybe your cudnn version is somehow incompatible with the cuda version, for example if cuda was installed via apt and cudnn was installed manually. Ubuntu 14.04 currently has cudnn version 5.0.{5,6} and 5.1.{3, 5, 10} in the repos (says apt-cache madison libcudnn5. You seem to have version 5.0.4. Probably try the local solution with one of the versions above.

I installed cudNN version 5.1.10 locally. The error changes, but still failing.

I couldn't try this

> Did you try a local install of cuda-8.0? #5447 mentions the tensorflow team only tests with cuda 8.0. This issue also seems to be related to yours.

because of the nvidia drivers installed.

At the end, the system operator updated the global cudnn version and now it works.

Thank you so much for your help.
