### PR TITLE
Extend TF:TRT C++ API to handle non-frozen models

### PR DESCRIPTION
**Pull request by tfeher**
This PR extends the C++ converter API of TF-TRT #52012 to handle models that are not frozen (i.e. contains variables).

Depends on #53310 . Tracker #45481.

### CODE REVIEW

**Comment by rthadur** [comment]
@tfeher could you please resolve conflicts ?

**Comment by tfeher** [comment]
Conflicts resolved, tagging @bixia1 for review.

**Review by bixia1 — APPROVED** [review]

**Comment by gbaned** [comment]
@tfeher Can you please address Ubuntu Sanity errors? Thanks!

**Comment by tfeher** [comment]
Addressed sanity errors. Also rebased and fixed missing argument that was introduced in #53507.

**Review by bixia1 — APPROVED** [review]

File: tensorflow/compiler/tf2tensorrt/BUILD [hunk 1]
```diff
@@ -127,6 +127,7 @@ cc_library(
     deps = [
         ":trt_parameters",
         ":trt_resources",
+        "//tensorflow/cc/tools:freeze_saved_model",
```
Comment (bixia1) [inline tensorflow/compiler/tf2tensorrt/BUILD:130]: this causes a cycle in dependency.

**Review by bixia1 — CHANGES_REQUESTED** [review]

**Review by tfeher — COMMENTED** [review]
@bixia1 I have fixed the issue. Let me know if you have a different suggestion for resolving the cycle.

**Review by bixia1 — APPROVED** [review]

File: tensorflow/compiler/tf2tensorrt/BUILD [hunk 2]
```diff
@@ -136,6 +137,13 @@ cc_library(
     ] + if_tensorrt([":tensorrt_lib"]),
 )
 
+filegroup(
+    name = "headers",
+    srcs = [
+        "trt_convert_api.h",
+    ],
+)
+
```
Comment (bixia1) [inline tensorflow/compiler/tf2tensorrt/BUILD:146]: This filegroup is not used?

File: tensorflow/compiler/tf2tensorrt/BUILD [hunk 3]
```diff
@@ -370,7 +384,6 @@ cc_library(
     name = "trt_op_libs",
     deps = [
         ":get_calibration_data_op_op_lib",
-        ":trt_convert_api",
```
Comment (bixia1) [inline tensorflow/compiler/tf2tensorrt/BUILD:373]: Can you pass tensorflow/compiler/tf2tensorrt:convert_qdq_test_gpu?
I got this error: third_party/tensorflow/compiler/tf2tensorrt/convert/ops/quantization_ops_test.cc:33:10: fatal error: 'third_party/tensorflow/compiler/tf2tensorrt/trt_convert_api.h' file not found
#include "third_party/tensorflow/compiler/tf2tensorrt/trt_convert_api.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

File: tensorflow/compiler/tf2tensorrt/trt_convert_api.h [hunk 4]
```diff
@@ -19,6 +19,7 @@ limitations under the License.
 #include <string>
 #include <vector>
 
+#include "tensorflow/cc/saved_model/loader.h"
```
Comment (bixia1) [inline tensorflow/compiler/tf2tensorrt/trt_convert_api.h:22]: I need to remove this line, and instead just add a forward declaration
struct SavedModelBundle;

**Comment by gbaned** [comment]
@tfeher Can you please check @bixia1's comments and keep us posted ? Thanks!
