### ISSUE TITLE
TimeDistributed (keras) wrapper broken in 1.4rc1

### ISSUE THREAD

**Issue by footh** [tensorflow/tensorflow#13957]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS Sierra
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.4rc1
- **Python version**: 3.6
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: See below

### Describe the problem
Two issues I've found when testing the TimeDistributed wrapper in release *1.4rc1*. I figure I'd wrap them (pun intended?) in one issue since they're both occur on the TimeDistributed wrapper. See simple code examples below which both work fine in version *1.3*.

### Source code / logs
```
def td():
    model = tf.keras.models.Sequential()
    model.add(tf.keras.layers.Dense(8, input_shape=(16,)))
    model.add(tf.keras.layers.Dense(4))
    model.summary()
    
    frame_input = tf.keras.layers.Input(shape=(10, 16))
    x = tf.keras.layers.TimeDistributed(model)(frame_input)
    x = tf.keras.layers.Flatten()(x)
    
    full_model = tf.keras.models.Model(inputs=frame_input, outputs=x)
    full_model.summary()
```
produces this trace:

```
     x = tf.keras.layers.TimeDistributed(model)(frame_input)
  File "/Users/guest/dev/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 252, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "/Users/guest/dev/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 575, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/Users/guest/dev/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/wrappers.py", line 238, in call
    output_shape = self._compute_output_shape(input_shape).as_list()
  File "/Users/guest/dev/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/wrappers.py", line 193, in _compute_output_shape
    child_input_shape).as_list()
AttributeError: 'NoneType' object has no attribute 'as_list'
```
and...

```
def td2():
    vgg16_model = tf.keras.applications.VGG16(weights='imagenet', include_top=False, input_shape=(100, 100, 3))
    
    frame_input = tf.keras.layers.Input(shape=(10, 100, 100, 3))
    
    x = tf.keras.layers.TimeDistributed(vgg16_model)(frame_input)
    model = tf.keras.models.Model(inputs=frame_input, outputs=x)
    model.summary()
```
produces this trace:

```
    x = tf.keras.layers.TimeDistributed(vgg16_model)(frame_input)
  File "/Users/guest/dev/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 252, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "/Users/guest/dev/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 575, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/Users/guest/dev/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/wrappers.py", line 234, in call
    y = self.layer.call(inputs, **kwargs)
  File "/Users/guest/dev/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 1920, in call
    output_tensors, _, _ = self._run_internal_graph(inputs, masks)
  File "/Users/guest/dev/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 2084, in _run_internal_graph
    output_tensors = _to_list(layer.call(computed_tensor, **kwargs))
  File "/Users/guest/dev/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/layers/convolutional.py", line 171, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/Users/guest/dev/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 835, in __call__
    return self.conv_op(inp, filter)
  File "/Users/guest/dev/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 499, in __call__
    return self.call(inp, filter)
  File "/Users/guest/dev/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 187, in __call__
    name=self.name)
  File "/Users/guest/dev/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 631, in conv2d
    data_format=data_format, name=name)
  File "/Users/guest/dev/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/guest/dev/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2959, in create_op
    self._add_op(ret)
  File "/Users/guest/dev/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2599, in _add_op
    "is already used" % op.name)
ValueError: cannot add op with name block1_conv1/convolution as that name is already used
```

**Comment by fchollet** [comment]
This is a bug in convolutional layers that was introduced in relation to eager mode; the same issue as [here](https://github.com/tensorflow/tensorflow/issues/13822#issuecomment-338880215). It has already been fixed and the fix will be backported into TF 1.4.

**Comment by footh** [comment]
Awesome, thanks for the quick reply. Does that explain the first issue though? (Perhaps I should've split them into separate reports.)
