### ISSUE TITLE
Tensorflow 2.3 Conversion to .tflite fails if last layer is Reshape (tf.keras.functional API)

### ISSUE THREAD

**Issue by AIWintermuteAI** [tensorflow/tensorflow#45305]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 or Colab
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3
- Python version: 3.6 or 3.7

**Describe the current behavior**
I made an easily reproducible example in this notebook
https://colab.research.google.com/drive/12Wj60KVP-cMxteiZXdZRmSxJaPX37D4c?usp=sharing

I'm currently porting my framework for ML on the edge, aXeleRate to tf.keras. You can find the code for converters here
https://github.com/AIWintermuteAI/aXeleRate/blob/8e66a39dadb469998a62c365c37c39984b30de4d/axelerate/networks/common_utils/convert.py#L180

Currently the issue is that when converting Keras model to .tflite, if last layer of the model is Reshape, the conversion fails silently. It doesn't output any errors, but the resulting model is not usable by Coral Edge TPU converter and also is deipalyed as wrong file type in Ubuntu, see the screenshot:
![Screenshot from 2020-12-02 01-27-06](https://user-images.githubusercontent.com/32562299/100774882-8ab99680-343d-11eb-972a-99188a0247d8.png)
This conversion works fine with Tensorflow 1.15. I think I can make it work by using old converter, but I'd like to report the issue regardless, in case it affects other users.

**Describe the expected behavior**
Keras model converting properly to .tflite format regardless of last layer used in the model.

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/12Wj60KVP-cMxteiZXdZRmSxJaPX37D4c?usp=sharing

For converter code, refer to 
https://github.com/AIWintermuteAI/aXeleRate/blob/8e66a39dadb469998a62c365c37c39984b30de4d/axelerate/networks/common_utils/convert.py#L180

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
Possibly has relation to
https://stackoverflow.com/questions/62783988/reshape-cc55-stretch-dim-1-node-number-x-reshape-failed-to-prepare

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/158b722b71285b42608f3fc1eb89a598/45305.ipynb).


Running with [TF v1.15](https://colab.research.google.com/gist/amahendrakar/4686c65d5f46c60cac2e98dd6ce9b801/45305-1-15.ipynb#scrollTo=awR7r4ILzrmb) throws an error stating `AttributeError: type object 'TFLiteConverter' has no attribute 'from_keras_model'`.

Whereas, running with [TF-nightly](https://colab.research.google.com/gist/amahendrakar/3c110d7a4935dcaf96cecef1aeec2326/45305-tf-nightly.ipynb#scrollTo=y07yAbYbjV2s) throws the error `AttributeError: module 'tensorflow' has no attribute 'python'`. Please check the linked gist for reference. Thanks!

**Comment by AIWintermuteAI** [comment]
Hi! You've encountered issues different from the one I described:
in tf 1.15 there is no from_keras_model method of TFLiteConverter - instead from_keras_model _file should be used with Keras model file as argument. Then conversion should work with Keras 2.3 and Tensorflow 1.15.
I have not yet tried tf-nightly, but module 'tensorflow' has no attribute 'python' likely points to 
import tensorflow.python.keras.backend as k
here
https://github.com/AIWintermuteAI/aXeleRate/blob/8e66a39dadb469998a62c365c37c39984b30de4d/axelerate/networks/common_utils/convert.py#L2

**Comment by MeghnaNatraj** [comment]
Re-open the issue if it's still not fixed. It looks like the model gets generated without a Reshape in the last layer using TF 2.4.0. Could you verify if this is the case for you?
