### ISSUE TITLE
Unit test fails to build, others fail on AARCH64 after XLA CPU backend enhancements

### ISSUE THREAD

**Issue by elfringham** [tensorflow/tensorflow#56673]
### Issue Type

Bug

### Source

source

### Tensorflow Version

git HEAD

### Custom Code

No

### OS Platform and Distribution

CentOS 7

### Mobile device

n/a

### Python version

3.8.10

### Bazel version

5.1.1

### GCC/Compiler version

10.2.1

### CUDA/cuDNN version

n/a

### GPU model and memory

n/a

### Current Behaviour?

```shell
Compiling with --config=mkl_aarch64 the unit test //tensorflow/python/tools:aot_compiled_test fails to build with

ERROR: /tmp/workspace/tensorflow-oneDNN-ACL-git/tensorflow/python/tools/BUILD:498:11: Linking tensorflow/python/tools/aot_compiled_test failed: (Exit 1): gcc failed: error executing command
(cd /root/.cache/bazel/_bazel_root/7043a081cadd05f91bd91c35f2a2c120/execroot/org_tensorflow &&
exec env -
LD_LIBRARY_PATH=/opt/rh/devtoolset-10/root/usr/lib64:/opt/rh/devtoolset-10/root/usr/lib:/opt/rh/devtoolset-10/root/usr/lib64/dyninst:/opt/rh/devtoolset-10/root/usr/lib/dyninst:/usr/local/lib64
PATH=/root/.cache/bazelisk/downloads/bazelbuild/bazel-5.1.1-linux-arm64/bin:/tmp/workspace/venv-cp38-cp38/bin:/opt/rh/devtoolset-10/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/proc/self/cwd
PYTHON_BIN_PATH=/tmp/workspace/venv-cp38-cp38/bin/python3
PYTHON_LIB_PATH=/tmp/workspace/venv-cp38-cp38/lib/python3.8/site-packages
TF2_BEHAVIOR=1
/opt/rh/devtoolset-10/root/usr/bin/gcc @bazel-out/aarch64-opt/bin/tensorflow/python/tools/aot_compiled_test-2.params)
Configuration: 3f75d29a2f4aef411fd2f59b82df7437222f52171a4aa87840162de83074dda9
Execution platform: @local_execution_config_platform//:platform

bazel-out/aarch64-opt/bin/_solib_aarch64/libtensorflow_Spython_Stools_Slibaot_Ucompiled_Ux_Umatmul_Uy_Ularge_Umultithreaded.so: error: undefined reference to '__xla_cpu_runtime_ACLMatMulF32'
collect2: error: ld returned 1 exit status
Target //tensorflow/python/tools:aot_compiled_test failed to build
INFO: Elapsed time: 430.002s, Critical Path: 383.37s
INFO: 509 processes: 6 internal, 503 local.
FAILED: Build did NOT complete successfully
//tensorflow/python/tools:aot_compiled_test FAILED TO BUILD

FAILED: Build did NOT complete successfully

Also other unit tests now fail.
//tensorflow/compiler/tests:conv2d_test_cpu_mlir_bridge_test
//tensorflow/compiler/xla/service/cpu/tests:cpu_eigen_dot_operation_test
//tensorflow/compiler/tests:depthwise_conv_op_test_cpu
//tensorflow/compiler/tests:depthwise_conv_op_test_cpu_mlir_bridge_test
//tensorflow/compiler/tests:conv2d_test_cpu
//tensorflow/compiler/xla/tests:convolution_dimension_numbers_test_cpu
//tensorflow/compiler/xla/tests:convolution_variants_test_cpu
//tensorflow/compiler/xla/tests:convolution_test_cpu
//tensorflow/compiler/xla/tests:conv_depthwise_backprop_filter_test_cpu
```

### Standalone code to reproduce the issue

```shell
bazel test --test_timeout=300,500,-1,-1 --flaky_test_attempts=3 --test_output=all --cache_test_results=no --noremote_accept_cached --config=nonccl --config=mkl_aarch64 --copt="-mtune=generic" --copt="-march=armv8-a" --copt="-O3" --test_env=TF_ENABLE_ONEDNN_OPTS=1 --copt="-fopenmp" --linkopt="-lgomp" --build_tag_filters=-no_oss,-oss_serial,-gpu,-tpu,-benchmark-test,-v1only,-no_aarch64,-requires-gpu --test_tag_filters=-no_oss,-oss_serial,-gpu,-tpu,-benchmark-test,-v1only,-no_aarch64,-requires-gpu --verbose_failures --jobs=75 --build_tests_only -- //tensorflow/python/tools:aot_compiled_test
```

### Relevant log output

```shell
https://ci.linaro.org/job/ldcg-python-manylinux-tensorflow-onednn-nightly/108/consoleText

ERROR: /tmp/workspace/tensorflow-oneDNN-ACL-git/tensorflow/python/tools/BUILD:498:11: Linking tensorflow/python/tools/aot_compiled_test failed: (Exit 1): gcc failed: error executing command
      (cd /root/.cache/bazel/_bazel_root/7043a081cadd05f91bd91c35f2a2c120/execroot/org_tensorflow && \
      exec env - \
        LD_LIBRARY_PATH=/opt/rh/devtoolset-10/root/usr/lib64:/opt/rh/devtoolset-10/root/usr/lib:/opt/rh/devtoolset-10/root/usr/lib64/dyninst:/opt/rh/devtoolset-10/root/usr/lib/dyninst:/usr/local/lib64 \
        PATH=/root/.cache/bazelisk/downloads/bazelbuild/bazel-5.1.1-linux-arm64/bin:/tmp/workspace/venv-cp37-cp37m/bin:/opt/rh/devtoolset-10/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
        PWD=/proc/self/cwd \
        PYTHON_BIN_PATH=/tmp/workspace/venv-cp37-cp37m/bin/python3 \
        PYTHON_LIB_PATH=/tmp/workspace/venv-cp37-cp37m/lib/python3.7/site-packages \
        TF2_BEHAVIOR=1 \
      /opt/rh/devtoolset-10/root/usr/bin/gcc @bazel-out/aarch64-opt/bin/tensorflow/python/tools/aot_compiled_test-2.params)
    # Configuration: 4e7de1e342fde1b2946298612567ae8e6e1dc07899c92f6eb687f4d6e2fb7650
    # Execution platform: @local_execution_config_platform//:platform
    bazel-out/aarch64-opt/bin/_solib_aarch64/libtensorflow_Spython_Stools_Slibaot_Ucompiled_Ux_Umatmul_Uy_Ularge_Umultithreaded.so: error: undefined reference to '__xla_cpu_runtime_ACLMatMulF32'
    collect2: error: ld returned 1 exit status
    INFO: Elapsed time: 2135.511s, Critical Path: 497.42s
    INFO: 20956 processes: 9447 internal, 11509 local.
    FAILED: Build did NOT complete successfully
    FAILED: Build did NOT complete successfully
```

**Comment by elfringham** [comment]
@cfRod @nSircombe

**Comment by elfringham** [comment]
Introduced by https://github.com/tensorflow/tensorflow/commit/c7bfba1d8a8700168c24d18f869886466ce0d54a

**Comment by elfringham** [comment]
PR that was merged https://github.com/tensorflow/tensorflow/pull/55534

**Comment by nSircombe** [comment]
@snadampal

**Comment by snadampal** [comment]
Hi @elfringham , @nSircombe , I'm able to reproduce this, will look into it.

**Comment by mohantym** [comment]
Hi @gadagashwini !
Could you look at this issue. Attached colab gist in [2.8](https://colab.sandbox.google.com/gist/mohantym/81a0e5a2cad734eb7b9b369aeca0515a/tensorflow-ranking.ipynb#scrollTo=skRg4_WPi616), [2.9](https://colab.sandbox.google.com/gist/mohantym/7cbd8a7803d8ec7cf0b48fee162c943e/tensorflow-ranking.ipynb#scrollTo=skRg4_WPi616) and [nightly ](https://colab.sandbox.google.com/gist/mohantym/f65ecb02b973d37ab2afaedd531ddaca/tensorflow-ranking.ipynb#scrollTo=tlf7PgzQ2JtS)for reference.
Thank you!

**Comment by elfringham** [comment]
@gadagashwini Unfortunately the colab gists referenced above by @mohantym are not relevant, you cannot build with --config=mkl_aarch64 on x86.
Full log from an AARCH64 build is here
https://ci.linaro.org/job/ldcg-python-manylinux-tensorflow-onednn-nightly/108/consoleText

**Comment by snadampal** [comment]
Hi @elfringham , I've fixed the unit test build issue and tested the below few scenarios manually.  No more build issues, however, one of the 5 tests in aot_compiled_test suite is failing with the error threshold mismatch (only for the  'mkl_aarch64' + xla cpu enhancements),  I will put a separate patch for that.
Before I raise a PR for this build issue fix, would you be able to take it through the automation and let me know if there are any side effects from this? Thank you!
Patch:

> https://github.com/snadampal/tensorflow/commit/75f4ec888fb03e4ff4fcc57252efacaa4d25b191

Tests covered on aarch64 system:
```
bazel test --config=mkl_aarch64 -c opt //tensorflow/compiler/xla/tests:dot_operation_test_cpu
bazel test -c opt //tensorflow/compiler/xla/tests:dot_operation_test_cpu

bazel test --config=mkl_aarch64 -c opt //tensorflow/python/tools:aot_compiled_test 
bazel test -c opt //tensorflow/python/tools:aot_compiled_test

bazel test --test_timeout=300,500,-1,-1 --flaky_test_attempts=3 --test_output=all --cache_test_results=no --noremote_accept_cached --config=nonccl --config=mkl_aarch64 --copt="-mtune=generic" --copt="-march=armv8-a" --copt="-O3" --test_env=TF_ENABLE_ONEDNN_OPTS=1 --copt="-fopenmp" --linkopt="-lgomp" --build_tag_filters=-no_oss,-oss_serial,-gpu,-tpu,-benchmark-test,-v1only,-no_aarch64,-requires-gpu --test_tag_filters=-no_oss,-oss_serial,-gpu,-tpu,-benchmark-test,-v1only,-no_aarch64,-requires-gpu --verbose_failures --jobs=75 --build_tests_only -- //tensorflow/python/tools:aot_compiled_test
```

**Comment by elfringham** [comment]
@snadampal Thanks for the patch. Unfortunately I don't currently have any means to run a patch through the full automated CI run. I can do a local run though and will give that a go. However I would suggest that you create the PR anyway. That will at least run it through the ARM_CI workflow.

**Comment by snadampal** [comment]
@elfringham , here is the PR: https://github.com/tensorflow/tensorflow/pull/56715
Please keep me posted on your test runs.

**Comment by snadampal** [comment]
ARM CI workflow passed for this PR.

**Comment by elfringham** [comment]
@snadampal Local tests on the above patch have all passed. However your PR seems to have failed some of the pre-submit checks, unfortunately it is not clear why.

**Comment by elfringham** [comment]
@snadampal Found a problem that might cause at least one of the checks to fail, you added a line that is not in alphabetical order.
` ✗ Check buildifier formatting on BUILD files
   (in test file /tmp/workspace/tf-build/tf_sig_build_dockerfiles/devel.usertools/code_check_changed_files.bats, line 26)
     `| xargs buildifier -v -mode=diff -diff_command="git diff --no-index"' failed with status 123
   buildifier formatting is recommended. Here are the suggested fixes:
   =============================
   tensorflow/compiler/xla/service/cpu/BUILD:
   diff --git a/tensorflow/compiler/xla/service/cpu/BUILD b/tmp/buildifier-tmp-739525505
   index f3899df7ebe..3f68a3027d1 100644
   --- a/tensorflow/compiler/xla/service/cpu/BUILD
   +++ b/tmp/buildifier-tmp-739525505
   @@ -1043,8 +1043,8 @@ tf_cc_test(
            ":cpu_runtime",
            ":runtime_custom_call_status",
            ":runtime_matmul",
   -        ":runtime_matmul_mkl",
            ":runtime_matmul_acl",
   +        ":runtime_matmul_mkl",
            ":runtime_single_threaded_matmul",
            "//tensorflow/compiler/xla:array2d",
            "//tensorflow/compiler/xla:types",
   exit status 1
`

**Comment by snadampal** [comment]
Thanks @elfringham , I will update the PR.

**Comment by snadampal** [comment]
Hi @elfringham, I have updated the [PR](https://github.com/tensorflow/tensorflow/issues/56673).

**Comment by elfringham** [comment]
@snadampal , that's good, thank you, However the PR is now showing merge conflicts. You should rebase to git HEAD on master to fix that.

**Comment by snadampal** [comment]
I rebased yesterday, looks like master moved. Will rebase it again.

**Comment by elfringham** [comment]
Fixed by above merges.
