### ISSUE TITLE
Build issue tenserflow 2.11.0 for tensorflow quantum

### ISSUE THREAD

**Issue by Gaurang-Belekar** [tensorflow/tensorflow#61924]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 2.11.0

### Custom code

Yes

### OS platform and distribution

Mac OS M1

### Python version

3.9

### Bazel version

bazel 5.3.0

### GCC/compiler version

Apple clang version 14.0.3 (clang-1403.0.22.14.1) Target: arm64-apple-darwin22.5.0 Thread model: posix

### Current behavior?

Trying to build package using bazel compiler, as given [here](https://www.tensorflow.org/quantum/install).  Fails to build the file. Gives the following output mentioned in log output, after running the given command.

Output: 
<img width="1680" alt="Screenshot 2023-09-20 at 11 47 36" src="https://github.com/tensorflow/tensorflow/assets/69144860/e699f11d-fc31-49af-83b7-34e3330f3358">

### Standalone code to reproduce the issue

```shell
bazel build -c opt --cxxopt="-O3" --cxxopt="-march=native" --cxxopt="-std=c++17" --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=1" //tensorflow/tools/pip_package:build_pip_package
```

### Relevant log output

```shell
ERROR: /private/var/tmp/_bazel_gb/4de1e45218bdc87c870302861e9b2675/external/boringssl/BUILD:161:11: Compiling src/crypto/x509/t_x509.c [for host] failed: (Exit 1): cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics ... (remaining 44 arguments skipped)
external/boringssl/src/crypto/x509/t_x509.c:321:18: error: variable 'l' set but not used [-Werror,-Wunused-but-set-variable]
    int ret = 0, l, i;
                 ^
1 error generated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 709.728s, Critical Path: 52.92s
INFO: 4419 processes: 1508 internal, 2911 local.
FAILED: Build did NOT complete successfully
```

**Comment by SuryanarayanaY** [comment]
Hi @Gaurang-Belekar ,

This issue observed in Tf2.12v also. Its due to issue in compilation problem in boringssl and it was fixed in nightly at that time. Please refer to similar issue #60191 which resolved subsequently in nightly version. 

Could you please check the build with Tf2.13v as the changes might not be cherry picked in Tf2.12 and earlier.

Thank you!
