### PR TITLE
Added a check

### LINKED ISSUE #49225: Can't call deprecated functions when embedding Python
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5.0
- Python version: 3.8.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
When calling deprecated functions using Python C API, they fail with

> AttributeError: 'NoneType' object has no attribute 'f_back'

Because there's not enough Python stack to be walked

Any deprecated function will fail with this error.

**Describe the expected behavior**

It should be possible to call deprecated functions using Python C APIs.

**[Contributing](https://www.tensorflow.org/community/contribute)**
- Do you want to contribute a PR? (yes/no): yes
- Briefly describe your candidate solution (if contributing): revert [offending commit](https://github.com/tensorflow/tensorflow/commit/42aab9b1f03713757d7c027b23f1113ea80f73ad) or add a check for `f == None` in [this line](https://github.com/tensorflow/tensorflow/blob/704610e1d21288482bf77923b387f9bb6c119318/tensorflow/python/util/deprecation.py#L105)

**Standalone code to reproduce the issue**

```c
Py_Initialize();
PyObject* tf_test = PyImport_ImportModule("tensorflow.test");
PyObject* is_gpu_available = PyObject_GetAttrString(tf_test, "is_gpu_available");
PyObject* haveGpu = PyObject_CallObject(is_gpu_available, NULL); // will return NULL and set Python error state
```

### PR DESCRIPTION
**Pull request by AdeshChoudhar**
Fixes #49225

### CODE REVIEW

**Comment by AdeshChoudhar** [comment]
@googlebot I signed it!

**Comment by lostmsu** [comment]
This does not seem to be fixing the issue.

**Comment by AdeshChoudhar** [comment]
@lostmsu Ok. can you explain me more about what is expected?

File: tensorflow/python/util/deprecation.py [hunk 1]
```diff
@@ -107,7 +107,7 @@ def _call_location(outer=False):
   # DISABLE_IMPORT_INSPECT_CHECK=TRUE to your cl description. Using it caused
   # test timeouts (b/189384061).
   f = inspect.currentframe().f_back.f_back
-  parent = f.f_back
+  parent = f and f.f_back
```
Comment (mdanatg) [inline tensorflow/python/util/deprecation.py:110]: This would change the type of parent. Try this instead:

```
parent = f.f_back if f is not None else None
```

**Review by mdanatg — CHANGES_REQUESTED** [review]

File: tensorflow/python/util/deprecation.py (hunk 1 above)
Comment (AdeshChoudhar) [reply tensorflow/python/util/deprecation.py:110]: @mdanatg Thank you for your feedback. I am using short-circuiting to do the same thing which you mentioned and I thought it would look cleaner. Please check the screenshot below, I know it is a small change, but I'm not sure how type would change for the parent. Kindly correct me if I'm going wrong.
Screenshot from 2021-09-14 01-06-35

Comment (mdanatg) [reply tensorflow/python/util/deprecation.py:110]: Ah I forgot about the short circuiting. LGTM then.

**Review by mdanatg — APPROVED** [review]

File: tensorflow/python/util/deprecation.py (hunk 1 above)
Comment (AdeshChoudhar) [reply tensorflow/python/util/deprecation.py:110]: Yes. Thank you!

**Comment by AdeshChoudhar** [comment]
@mdanatg May I ask why `Windows Bazel` test failed?

**Comment by mdanatg** [comment]
The windows build seems broken atm. We'll need to wait a bit until it gets fixed.

**Comment by AdeshChoudhar** [comment]
Should I delete this branch?

**Comment by mdanatg** [comment]
Yep, it's merged so it should be safe to delete.

**Comment by AdeshChoudhar** [comment]
@mdanatg Thank you for helping me through my first PR!
