### ISSUE TITLE
the tf.repeat function can not be converted to tflite?

### ISSUE THREAD

**Issue by cookingbear** [tensorflow/tensorflow#44497]
I tested the newest tf-nightly==2.5.0-dev20201029,
the tf.repeat function would cause the errors below:

tensorflow.lite.python.convert.ConverterError: ...../lib/python3.6/site-packages/tensorflow/python/saved_model/load.py:890:0: error: 'tf.Reshape' op requires 'shape' to have at most one dynamic dimension, but got multiple dynamic dimensions at indices 1 and 2

........

Exception ignored in: <bound method Buckets.del of <tensorflow.python.eager.monitoring.ExponentialBuckets object at 0x7f6e852aa4c8>>
Traceback (most recent call last):
File "......./lib/python3.6/site-packages/tensorflow/python/eager/monitoring.py", line 407, in del
AttributeError: 'NoneType' object has no attribute 'TFE_MonitoringDeleteBuckets'

The code has been shown in https://github.com/tensorflow/tensorflow/issues/40504

At the same time, according to the colab(https://colab.research.google.com/drive/1HudLLpT9CQdh2k04c06bHUwLubhGTWxA?usp=sharing)
when using tf-nightly==2.4.0-dev20200630, tf.repeat can be converted.

**Comment by abattery** [comment]
The above TensorTTS colab works fine with tf-nightly version, 2.5.0-dev20201029.

Could you create a minimal example for reproducing your problem via Colab?

**Comment by cookingbear** [comment]
I just found that the problem is not caused by tf.repeat and the code can be converted. thanks
