### ISSUE TITLE
ptb_word_lm.py error: unsupported operand type(s) for /: 'Tensor' and 'int'

### ISSUE THREAD

**Issue by mttk** [tensorflow/tensorflow#506]
Hi,

I ran the `ptb_word_lm` example from `models/rnn/ptb`. however I got the `unsupported operand type(s) for /: 'Tensor' and 'int'` for line 139 in `ptb_word_lm.py`.

I also managed to fix it, by changing 
139 `self._cost = cost = tf.reduce_sum(loss) / batch_size`
to
139 `self._cost = cost = tf.div(tf.reduce_sum(loss), tf.constant(batch_size, dtype=tf.types.float32))`

And it works fine so far.

**Comment by mrry** [comment]
Thanks for letting us know about this. Could you tell me whether you're using Python 2 or 3? (Although we're using `from __future__ import division`, this smacks of a Python 3 compatibility issue....)

**Comment by mttk** [comment]
I'm using 2.7, however when I commented out the `from __future__ import division` the original code worked fine. So it is some "v3" trickery.

**Comment by martinwicke** [comment]
This may be a 'feature' -- tensors are intentionally rather strict about
implicit conversions, so I think they don't have __olddiv__. Try casting
the int to a float.

**Comment by mttk** [comment]
Attempt 1:
`from __future__ import division`
`self._cost = cost = tf.reduce_sum(loss) / float(batch_size)`
>>> TypeError: unsupported operand type(s) for /: 'Tensor' and 'float'

Attempt 2. maybe numpy?
`from __future__ import division`
`self._cost = cost = tf.reduce_sum(loss) / np.array(batch_size, dtype=np.float32)`
>>> TypeError: unsupported operand type(s) for /: 'Tensor' and 'float'

With `from __future__ import division` just the way in the original issue I wrote seems to work.

**Comment by vrv** [comment]
@mttk: what do you get when you print
```tf.__version__ ```?

**Comment by mttk** [comment]
@vrv you got it :)

First I got `AttributeError: 'module' object has no attribute '__version__'`

After updating to 0.6.0 , the original code works fine. My bad, sorry for the mistake guys!
