### ISSUE TITLE
print_selective_registration_header: No module named 'tensorflow.python.platform'

### ISSUE THREAD

**Issue by groovemaxRong** [tensorflow/tensorflow#53732]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 20.04
- Tensorflow version: r2.3
- TensorFlow installation (pip package or built from source): source
- TensorFlow library (version, if pip package or github SHA, if built from source): source

### 2. Code

Provide code to help us reproduce your issues using one of the following options:

Hi, i follow the tflite doc and want to reduce the library size, but after i build the print_selective_registration_header tool,  i fail to run the bin because some import error is raised, and i try two way to fix it but both fail.
Can you give me some ideas, Many thanks!

1. try to run print_selective_registration_header **not in tensorflow source dir**.
- i check the pip version has installed and then try to run print_selective_registration_header, but it fails.
```
root@3110c2e48cdb:~# python3
Python 3.8.10 (default, Nov 26 2021, 20:14:08)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2022-01-12 16:57:13.598993: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2022-01-12 16:57:13.599037: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
>>>
root@3110c2e48cdb:~# /root/dev/tensorflow/tensorflow/bazel-bin/tensorflow/python/tools/print_selective_registration_header
Traceback (most recent call last):
  File "/root/dev/tensorflow/tensorflow/bazel-bin/tensorflow/python/tools/print_selective_registration_header.runfiles/org_tensorflow/tensorflow/python/tools/print_selective_registration_header.py", line 41, in <module>
    from tensorflow.python.platform import app
ModuleNotFoundError: No module named 'tensorflow.python.platform'
```

2. try to run print_selective_registration_header **in tensorflow source dir**
```
root@3110c2e48cdb:~/dev/tensorflow/tensorflow# export PYTHONPATH=`pwd`:$PYTHONPATH
root@3110c2e48cdb:~/dev/tensorflow/tensorflow# echo $PYTHONPATH
/root/dev/tensorflow/tensorflow:
root@3110c2e48cdb:~/dev/tensorflow/tensorflow# ./bazel-bin/tensorflow/python/tools/print_selective_registration_header
Traceback (most recent call last):
  File "/root/dev/tensorflow/tensorflow/./bazel-bin/tensorflow/python/tools/print_selective_registration_header.runfiles/org_tensorflow/tensorflow/python/tools/print_selective_registration_header.py", line 41, in <module>
    from tensorflow.python.platform import app
ModuleNotFoundError: No module named 'tensorflow.python.platform'
root@3110c2e48cdb:~/dev/tensorflow/tensorflow# cat .tf_configure.bazelrc
build --action_env ANDROID_NDK_HOME=${ANDROID_NDK_HOME}/android-ndk-r${NDK_VERSION}
build --action_env PYTHON_BIN_PATH="/usr/bin/python3"
build --action_env PYTHON_LIB_PATH="/usr/lib/python3/dist-packages"
build --python_path="/usr/bin/python3"
build --config=xla
build:opt --copt=-march=native
build:opt --copt=-Wno-sign-compare
build:opt --host_copt=-march=native
build:opt --define with_default_optimizations=true
test --flaky_test_attempts=3
test --test_size_filters=small,medium
test:v1 --test_tag_filters=-benchmark-test,-no_oss,-gpu,-oss_serial
test:v1 --build_tag_filters=-benchmark-test,-no_oss,-gpu
test:v2 --test_tag_filters=-benchmark-test,-no_oss,-gpu,-oss_serial,-v1only
test:v2 --build_tag_filters=-benchmark-test,-no_oss,-gpu,-v1only
build --action_env TF_CONFIGURE_IOS="0"
```

**Comment by sushreebarsa** [comment]
@groovemaxRong We could see you are using TF v2.3.0 which is not actively supported ,please refer  this [comment](https://github.com/tensorflow/tensorflow/issues/52915#issuecomment-961288304).Could you please try to upgrade TF version to latest `TF v2.7.0` and let us know the outcome? Thanks!

**Comment by groovemaxRong** [comment]
After upgrade TF version to 2.7.0, it fail with other error.  
```bazel-out/k8-opt/bin/tensorflow/lite/kernels/_objs/builtin_ops_all_linked/register.pic.o: multiple definition of 'tflite::ops::builtin::BuiltinOpResolver::BuiltinOpResolver()```

Build CMD:
```
bazel build --config=monolithic --define=with_select_tf_ops=true \
        --cxxopt="-std=c++${CPP_VERSION}" \
        -c opt \
        --define=no_tensorflow_py_deps=true \
        //tensorflow/lite:libtensorflowlite.so \
        --verbose_failures
```

Here is the detailed log.
```
You have bazel 3.7.2 installed.
Please specify the location of python. [Default is /usr/bin/python3]:

Found possible Python library paths:
  /usr/lib/python3/dist-packages
  /usr/local/lib/python3.8/dist-packages
Please input the desired Python library path to use.  Default is [/usr/lib/python3/dist-packages]
Do you wish to build TensorFlow with ROCm support? [y/N]: No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: No CUDA support will be enabled for TensorFlow.

Do you wish to download a fresh release of clang? (Experimental) [y/N]: Clang will not be downloaded.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -Wno-sign-compare]:

Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: Invalid selection: -march=native -Wno-sign-compare
Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=mkl_aarch64    # Build with oneDNN and Compute Library for the Arm Architecture (ACL).
        --config=monolithic     # Config for mostly static monolithic build.
        --config=numa           # Build with NUMA support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
        --config=v1             # Build with TensorFlow 1 API instead of TF 2 API.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=nogcp          # Disable GCP support.
        --config=nonccl         # Disable NVIDIA NCCL support.
Configuration finished
build --action_env ANDROID_NDK_HOME=${ANDROID_NDK_HOME}/android-ndk-r${NDK_VERSION}
build --action_env PYTHON_BIN_PATH="/usr/bin/python3"
build --action_env PYTHON_LIB_PATH="/usr/lib/python3/dist-packages"
build --python_path="/usr/bin/python3"
build:opt --copt=N
build:opt --host_copt=N
test --flaky_test_attempts=3
test --test_size_filters=small,medium
test:v1 --test_tag_filters=-benchmark-test,-no_oss,-gpu,-oss_serial
test:v1 --build_tag_filters=-benchmark-test,-no_oss,-gpu
test:v2 --test_tag_filters=-benchmark-test,-no_oss,-gpu,-oss_serial,-v1only
test:v2 --build_tag_filters=-benchmark-test,-no_oss,-gpu,-v1only
    deps = [
        ":framework",
        ":tflite_exported_symbols.lds",
        "//tensorflow/lite/delegates/flex:delegate",
        ":tflite_version_script.lds",
        "//tensorflow/lite/kernels:builtin_ops_all_linked",
    ],
)

tflite_portable_test_suite()
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=186
INFO: Reading rc options for 'build' from /root/dev/tensorflow/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /root/dev/tensorflow/tensorflow/.bazelrc:
  'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true
INFO: Reading rc options for 'build' from /root/dev/tensorflow/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env ANDROID_NDK_HOME=${ANDROID_NDK_HOME}/android-ndk-r${NDK_VERSION} --action_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env PYTHON_LIB_PATH=/usr/lib/python3/dist-packages --python_path=/usr/bin/python3
INFO: Reading rc options for 'build' from /root/dev/tensorflow/tensorflow/.bazelrc:
  'build' options: --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/common,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/fallback,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils
INFO: Found applicable config definition build:short_logs in file /root/dev/tensorflow/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /root/dev/tensorflow/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:monolithic in file /root/dev/tensorflow/tensorflow/.bazelrc: --define framework_shared_object=false
INFO: Found applicable config definition build:linux in file /root/dev/tensorflow/tensorflow/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels --distinct_host_configuration=false --experimental_guard_against_concurrent_changes
INFO: Found applicable config definition build:dynamic_kernels in file /root/dev/tensorflow/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
WARNING: Download from http://mirror.tensorflow.org/github.com/tensorflow/runtime/archive/64c92c8013b557087351c91b5423b6046d10f206.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/43d6991c2a4cc2ac374e68c029634f2b59ffdfdf.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1596824487 -0400"
DEBUG: Repository io_bazel_rules_docker instantiated at:
  /root/dev/tensorflow/tensorflow/WORKSPACE:23:14: in <toplevel>
  /root/dev/tensorflow/tensorflow/tensorflow/workspace0.bzl:108:34: in workspace
  /root/.cache/bazel/_bazel_root/2c26c1884d3743801d5d0e3029f61ed7/external/bazel_toolchains/repositories/repositories.bzl:35:23: in repositories
Repository rule git_repository defined at:
  /root/.cache/bazel/_bazel_root/2c26c1884d3743801d5d0e3029f61ed7/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
INFO: Analyzed target //tensorflow/lite:libtensorflowlite.so (238 packages loaded, 15607 targets configured).
INFO: Found 1 target...
ERROR: /root/dev/tensorflow/tensorflow/tensorflow/lite/BUILD:1141:24: Linking of rule '//tensorflow/lite:libtensorflowlite.so' failed (Exit 1): gcc failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/2c26c1884d3743801d5d0e3029f61ed7/execroot/org_tensorflow && \
  exec env - \
    ANDROID_NDK_HOME='${ANDROID_NDK_HOME}/android-ndk-r${NDK_VERSION}' \
    PATH=/root/dev/ndk/android-ndk-r17c:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python3 \
    PYTHON_LIB_PATH=/usr/lib/python3/dist-packages \
    TF2_BEHAVIOR=1 \
  /usr/bin/gcc @bazel-out/k8-opt/bin/tensorflow/lite/libtensorflowlite.so-2.params)
Execution platform: @local_execution_config_platform//:platform
/usr/bin/ld.gold: error: bazel-out/k8-opt/bin/tensorflow/lite/kernels/_objs/builtin_ops_all_linked/register.pic.o: multiple definition of 'tflite::ops::builtin::BuiltinOpResolver::BuiltinOpResolver()'
/usr/bin/ld.gold: bazel-out/k8-opt/bin/tensorflow/lite/kernels/_objs/builtin_ops/register.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/k8-opt/bin/tensorflow/lite/kernels/_objs/builtin_ops_all_linked/register.pic.o: multiple definition of 'tflite::ops::builtin::BuiltinOpResolver::BuiltinOpResolver()'
/usr/bin/ld.gold: bazel-out/k8-opt/bin/tensorflow/lite/kernels/_objs/builtin_ops/register.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/k8-opt/bin/tensorflow/lite/kernels/_objs/builtin_ops_all_linked/register.pic.o: multiple definition of 'tflite::ops::builtin::BuiltinOpResolver::GetDelegateCreators() const'
/usr/bin/ld.gold: bazel-out/k8-opt/bin/tensorflow/lite/kernels/_objs/builtin_ops/register.pic.o: previous definition here
collect2: error: ld returned 1 exit status
Target //tensorflow/lite:libtensorflowlite.so failed to build
INFO: Elapsed time: 1396.340s, Critical Path: 364.69s
INFO: 6245 processes: 354 internal, 5891 local.
FAILED: Build did NOT complete successfully
```
