### ISSUE TITLE
Can't call deprecated functions when embedding Python

### ISSUE THREAD

**Issue by lostmsu** [tensorflow/tensorflow#49225]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5.0
- Python version: 3.8.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
When calling deprecated functions using Python C API, they fail with

> AttributeError: 'NoneType' object has no attribute 'f_back'

Because there's not enough Python stack to be walked

Any deprecated function will fail with this error.

**Describe the expected behavior**

It should be possible to call deprecated functions using Python C APIs.

**[Contributing](https://www.tensorflow.org/community/contribute)**
- Do you want to contribute a PR? (yes/no): yes
- Briefly describe your candidate solution (if contributing): revert [offending commit](https://github.com/tensorflow/tensorflow/commit/42aab9b1f03713757d7c027b23f1113ea80f73ad) or add a check for `f == None` in [this line](https://github.com/tensorflow/tensorflow/blob/704610e1d21288482bf77923b387f9bb6c119318/tensorflow/python/util/deprecation.py#L105)

**Standalone code to reproduce the issue**

```c
Py_Initialize();
PyObject* tf_test = PyImport_ImportModule("tensorflow.test");
PyObject* is_gpu_available = PyObject_GetAttrString(tf_test, "is_gpu_available");
PyObject* haveGpu = PyObject_CallObject(is_gpu_available, NULL); // will return NULL and set Python error state
```

**Comment by mdanatg** [comment]
Looks most likely like a bug in the deprecation API: https://github.com/tensorflow/tensorflow/blob/5fca930c7fb1b302c6d7f1d05a80724028764480/tensorflow/python/util/deprecation.py#L101 

It should be straightforward to add a test an an extra check.

**Comment by bhack** [comment]
@lostmsu Do you want to contribute a PR?

**Comment by AdeshChoudhar** [comment]
I would like to contribute. This might be my first contribution for tensorflow! So, just a check for `f == None` right?

**Comment by AdeshChoudhar** [comment]
I have made a pull request. Can you please review it and let me know if this was the expected thing?

**Comment by AdeshChoudhar** [comment]
I hope we can close this issue.

**Comment by bhack** [comment]
@mdanatg Can you close this?

**Comment by mdanatg** [comment]
Sure. BTW, if you add "Fixed <issue number>" to your PR then it gets closed automatically.

**Comment by bhack** [comment]
> if you add "Fixed " to your PR then it gets closed automatically.
Thanks, It is what I suggest also to the triage and review teams.  To check if the submitted PR is linked or not the issue as they have the permission to link it. Sometimes contributors don't put the auto-connection string in the PR description.

**Comment by AdeshChoudhar** [comment]
@bhack What is an auto-connection string?

**Comment by bhack** [comment]
> @bhack What is an auto-connection string?

You need to use [one of these keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

**Comment by AdeshChoudhar** [comment]
Oh great, I didn't know about that! Thank you for sharing!
