### ISSUE TITLE
An error maybe about protobuf？

### ISSUE THREAD

**Issue by wjc2b** [tensorflow/tensorflow#46631]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Window 10
- TensorFlow installed from (source or binary):
- TensorFlow version: 2.3.0-gpu
- Python version: 3.6.0
- Installed using virtualenv? pip? conda?:  pip
- CUDA/cuDNN version: 10.1 / 7.6.4
- GPU model and memory: 1050Ti ，16G

**Describe the problem**

My tensorflow is installed in the new virtual environment of anaconda.And at first my protobuf version is 3.6.0

Today, I tried to run a tensorflow program, but it reported this error.

``` File "E:\Anaconda3.5\envs\ten2\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1666, in _init_from_args
    graph_mode=self._in_graph_mode)
  File "E:\Anaconda3.5\envs\ten2\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 243, in eager_safe_variable_handle
    shape, dtype, shared_name, name, graph_mode, initial_value)
  File "E:\Anaconda3.5\envs\ten2\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 179, in _variable_handle_from_shape_and_dtype
    handle_data.shape_and_type.append(
AttributeError: 'google.protobuf.pyext._message.RepeatedCompositeCo' object has no attribute 'append'

Process finished with exit code 1
```

Then,i try to search some informations ,some ways suggest to upgrade the version of protobuf to the latest version, the 3.14.0.
But,after upgrading,there is new problems.It show import error.
```
  File "E:\Anaconda3.5\envs\ten2\lib\site-packages\tensorflow\core\framework\function_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "E:\Anaconda3.5\envs\ten2\lib\site-packages\google\protobuf\descriptor.py", line 48, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: 找不到指定的程序。
```

It work well in tensorflow1.14.0 and cuda 10.0.What should i do if i still want to use tensorflow2.3.0？

**Comment by ddbscs** [comment]
have you solve the problem?
I have the same problem as you with the same configuration.
could you show your solution?

**Comment by wjc2b** [comment]
> have you solve the problem?
> I have the same problem as you with the same configuration.
> could you show your solution?

Sorry，I can't solve that problem. I just changed other versions of python and tensorflow-gpu.
Now，I use python-3.7 and tensorflow-gpu-2.1.0.
If it still doesn't work ,you can also try others.
Hope it helps you :)

**Comment by Saduf2019** [comment]
Please create a new issue as this issue is in closed status.

**Comment by wang1wu** [comment]
请问您解决问题了吗，我在这一步卡了好久了

**Comment by wjc2b** [comment]
> 请问您解决问题了吗，我在这一步卡了好久了

看样子当初我是更换了版本来解决这个问题，具体版本在上面。后面使用的是pytorch，没有使用tensorflow了
