### ISSUE TITLE
Can't build libtensorflowlite.so with `--config=elinux_armhf` - external/XNNPACK/src/f32-f16-vcvt/gen/vcvt-neonfp16-x16.c:36:28: error: incompatible types when initializing type 'uint16x8_t' using type 'int'

### ISSUE THREAD

**Issue by reuben** [tensorflow/tensorflow#54268]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): source
- TensorFlow version: r2.8, e994fb9c3ad250d38fd07511aaa445eda728f9af
- Python version: Python 3.8.10
- Bazel version (if compiling from source): 4.2.1
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

**Describe the problem**

```
$ git clone --branch r2.8 https://github.com/tensorflow/tensorflow
$ git checkout e994fb9c3ad250d38fd07511aaa445eda728f9af
$  bazel build --verbose_failures --config=elinux_armhf -c opt //tensorflow/lite:libtensorflowlite.so
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=158
INFO: Reading rc options for 'build' from /root/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /root/tensorflow/.bazelrc:
  'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/analysis,tensorflow/compiler/mlir/tfrt/tests/jit,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_tfrt,tensorflow/compiler/mlir/tfrt/tests/tf_to_corert,tensorflow/compiler/mlir/tfrt/tests/tf_to_tfrt_data,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/common,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/fallback,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils
INFO: Found applicable config definition build:short_logs in file /root/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /root/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:elinux_armhf in file /root/tensorflow/.bazelrc: --config=elinux --cpu=armhf --distinct_host_configuration=true
INFO: Found applicable config definition build:elinux in file /root/tensorflow/.bazelrc: --crosstool_top=@local_config_embedded_arm//:toolchain --host_crosstool_top=@bazel_tools//tools/cpp:toolchain
INFO: Found applicable config definition build:linux in file /root/tensorflow/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels --distinct_host_configuration=false --experimental_guard_against_concurrent_changes
INFO: Found applicable config definition build:dynamic_kernels in file /root/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1596824487 -0400"
DEBUG: Repository io_bazel_rules_docker instantiated at:
  /root/tensorflow/WORKSPACE:23:14: in <toplevel>
  /root/tensorflow/tensorflow/workspace0.bzl:108:34: in workspace
  /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/external/bazel_toolchains/repositories/repositories.bzl:35:23: in repositories
Repository rule git_repository defined at:
  /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
INFO: Analyzed target //tensorflow/lite:libtensorflowlite.so (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/external/XNNPACK/BUILD.bazel:6811:19: Compiling src/f32-f16-vcvt/gen/vcvt-neonfp16-x16.c failed: (Exit 1): arm-linux-gnueabihf-gcc failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow && \
  exec env - \
    PATH=/root/.cache/bazelisk/downloads/bazelbuild/bazel-4.2.1-linux-x86_64/bin:/root/bin:/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
    TF2_BEHAVIOR=1 \
  /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/external/armhf_linux_toolchain/bin/arm-linux-gnueabihf-gcc -fstack-protector -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections -MD -MF bazel-out/armhf-opt/bin/external/XNNPACK/_objs/neonfp16_prod_microkernels/1/vcvt-neonfp16-x16.pic.d '-frandom-seed=bazel-out/armhf-opt/bin/external/XNNPACK/_objs/neonfp16_prod_microkernels/1/vcvt-neonfp16-x16.pic.o' -fPIC -DPTHREADPOOL_NO_DEPRECATED_API -iquote external/XNNPACK -iquote bazel-out/armhf-opt/bin/external/XNNPACK -iquote external/FP16 -iquote bazel-out/armhf-opt/bin/external/FP16 -iquote external/pthreadpool -iquote bazel-out/armhf-opt/bin/external/pthreadpool -iquote external/FXdiv -iquote bazel-out/armhf-opt/bin/external/FXdiv -iquote external/cpuinfo -iquote bazel-out/armhf-opt/bin/external/cpuinfo -iquote external/clog -iquote bazel-out/armhf-opt/bin/external/clog -Ibazel-out/armhf-opt/bin/external/FP16/_virtual_includes/FP16 -Ibazel-out/armhf-opt/bin/external/pthreadpool/_virtual_includes/pthreadpool -Ibazel-out/armhf-opt/bin/external/FXdiv/_virtual_includes/FXdiv -Ibazel-out/armhf-opt/bin/external/cpuinfo/_virtual_includes/cpuinfo -Ibazel-out/armhf-opt/bin/external/clog/_virtual_includes/clog -isystem external/XNNPACK/include -isystem bazel-out/armhf-opt/bin/external/XNNPACK/include -isystem external/XNNPACK/src -isystem bazel-out/armhf-opt/bin/external/XNNPACK/src -isystem external/FP16/include -isystem bazel-out/armhf-opt/bin/external/FP16/include -isystem external/pthreadpool/include -isystem bazel-out/armhf-opt/bin/external/pthreadpool/include -isystem external/FXdiv/include -isystem bazel-out/armhf-opt/bin/external/FXdiv/include -w -DAUTOLOAD_DYNAMIC_KERNELS -Iinclude -Isrc -marm '-march=armv7-a' '-mfpu=neon-fp16' '-std=c99' -O2 -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -no-canonical-prefixes -fno-canonical-system-headers -c external/XNNPACK/src/f32-f16-vcvt/gen/vcvt-neonfp16-x16.c -o bazel-out/armhf-opt/bin/external/XNNPACK/_objs/neonfp16_prod_microkernels/1/vcvt-neonfp16-x16.pic.o)
Execution platform: @local_execution_config_platform//:platform
external/XNNPACK/src/f32-f16-vcvt/gen/vcvt-neonfp16-x16.c: In function 'xnn_f32_f16_vcvt_ukernel__neonfp16_x16':
external/XNNPACK/src/f32-f16-vcvt/gen/vcvt-neonfp16-x16.c:36:28: error: incompatible types when initializing type 'uint16x8_t' using type 'int'
     const uint16x8_t vh0 = vreinterpretq_u16_f16(vcombine_f16(vcvt_f16_f32(vf0), vcvt_f16_f32(vf1)));
                            ^~~~~~~~~~~~~~~~~~~~~
external/XNNPACK/src/f32-f16-vcvt/gen/vcvt-neonfp16-x16.c:37:28: error: incompatible types when initializing type 'uint16x8_t' using type 'int'
     const uint16x8_t vh1 = vreinterpretq_u16_f16(vcombine_f16(vcvt_f16_f32(vf2), vcvt_f16_f32(vf3)));
                            ^~~~~~~~~~~~~~~~~~~~~
external/XNNPACK/src/f32-f16-vcvt/gen/vcvt-neonfp16-x16.c:45:27: error: incompatible types when initializing type 'uint16x4_t' using type 'int'
     const uint16x4_t vh = vreinterpret_u16_f16(vcvt_f16_f32(vf));
                           ^~~~~~~~~~~~~~~~~~~~
external/XNNPACK/src/f32-f16-vcvt/gen/vcvt-neonfp16-x16.c:55:21: error: incompatible types when initializing type 'uint16x4_t' using type 'int'
     uint16x4_t vh = vreinterpret_u16_f16(vcvt_f16_f32(vf));
                     ^~~~~~~~~~~~~~~~~~~~
Target //tensorflow/lite:libtensorflowlite.so failed to build
INFO: Elapsed time: 2.279s, Critical Path: 1.96s
INFO: 293 processes: 236 internal, 57 local.
FAILED: Build did NOT complete successfully
```

**Comment by reuben** [comment]
FWIW the build works fine on the `master` branch.

**Comment by reuben** [comment]
```
4ec84aa99372ca7899fb12715edd2bfe3c947c88 is the first bad commit
commit 4ec84aa99372ca7899fb12715edd2bfe3c947c88
Author: Terry Heo <terryheo@google.com>
Date:   Wed Dec 29 16:31:35 2021 -0800

    lite: Fix XNNPACK build for elinux_armhf

    PiperOrigin-RevId: 418863236
    Change-Id: I066c4c4c10a98975a40a6ea820781e8bcdb75d76

 .bazelrc | 1 +
 1 file changed, 1 insertion(+)
bisect run success
```

**Comment by reuben** [comment]
Hm, but that change is already applied on r2.8... Let me try commenting it out.

**Comment by reuben** [comment]
Oh wait, it isn't! Applying 4ec84aa99372ca7899fb12715edd2bfe3c947c88 on r2.8 fixes the build for me!

**Comment by sachinprasadhs** [comment]
Tensorflow 2.8 branch cut of rc0 and rc1 was made before the above commit on Dec 29th. 
You need to wait for the next branch release for these changes to reflect.
Till then you can build using master branch. Thanks!

**Comment by reuben** [comment]
I understand that it missed the branch, but considering 2.8.0 is already out as a stable release and that target is [documented explicitly](https://www.tensorflow.org/lite/guide/build_arm#step_3_build_arm_binary), you might want to consider uplifting the change.

**Comment by sachinprasadhs** [comment]
Hi, Since the fix will be available in Tensorflow 2.9 and it will be released soon and I'm closing the linked PR, since this issue is not critical for cherrypick. 
You can close this issue. Thanks!

**Comment by reuben** [comment]
I'd say being able to build the project for a supported target is quite critical 😅

**Comment by sachinprasadhs** [comment]
You can build against the master branch and release of Tensorflow 2.9 is around the corner.
