### ISSUE TITLE
Error when building from source Fedora 27 CUDA 9.1

### ISSUE THREAD

**Issue by xd009642** [tensorflow/tensorflow#16165]
### System information
- OS Platform and Distribution: Fedora 27
- TensorFlow installed from (source or binary): binary
- TensorFlow version: r1.4
- Python version: 3.6.3
- Bazel version: 0.8.1
- GCC/Compiler version: 7.2.1
- CUDA/cuDNN version: CUDA 9.1 cuDNN 7.0.5
- **GPU model and memory**: NVidia Geforce GTX 960 4GB
- Exact command to reproduce: bazel build -c opt --config=cuda --verbose_failures //tensorflow/tools/pip_package:build_pip_package

### Describe the problem
So I'm attempting to build tensorflow from source on fedora with the version of CUDA and cuDNN I already had installed to avoid have to also install an older version. The build however errors with the following message:

```
ERROR: .cache/bazel/_bazel_xd009642/f9f5dea1a139b69420e1045d339dda45/external/nccl_archive/BUILD:33:1: error while parsing .d file: /home/xd009642/.cache/bazel/_bazel_xd009642/f9f5dea1a139b69420e1045d339dda45/execroot/org_tensorflow/bazel-out/k8-py3-opt/bin/external/nccl_archive/_objs/nccl/external/nccl_archive/src/all_reduce.cu.pic.d (No such file or directory)
<command-line>:0:15: warning: ISO C++11 requires whitespace after the macro name
<command-line>:0:1: error: macro names must be identifiers
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 0.392s, Critical Path: 0.12s
FAILED: Build did NOT complete successfully
```
I also tried the command `bazel build --config=opt --config=cuda --incompatible_load_argument_is_label=false //tensorflow/tools/pip_package:build_pip_package` from [here](http://www.python36.com/install-tensorflow141-gpu/) with the same end result.

Any guidance is appreciated as this is my first time using bazel (and also trying to compile tensorflow).

**Comment by aselle** [comment]
I suspect you need the 1.5 release candidate or newer to compile with CUDA 9.1, but I'm not sure. I'd try that first. Also, you could try making sure you can compile with CPU only first (that's usually a lot easier and can help you isolate problem.) And typically we only support Ubuntu, so I have no Fedora experience, but others on the forum might.

**Comment by xd009642** [comment]
I tried again on 1.5, the build completed successfully for the CPU but for GPU I got this message (paths cut down to just filenames for brevity):

```
2 errors detected in the compilation of ".../tmpxft_00000ee6_00000000-6_lstm_ops_gpu.cu.cpp1.ii".
ERROR: /home/xd009642/3rdparty/tensorflow/tensorflow/contrib/rnn/BUILD:218:1: output 'tensorflow/contrib/rnn/_objs/python/ops/_lstm_ops_gpu/tensorflow/contrib/rnn/kernels/lstm_ops_gpu.cu.pic.o' was not created
ERROR: tensorflow/tensorflow/contrib/rnn/BUILD:218:1: not all outputs were created or valid
```

I'm going to run again since I forgot --verbose_failures on the GPU build and see if that sheds anymore insight.

**Comment by xd009642** [comment]
I got this message:

```
usr/include/bits/floatn.h(61): error: invalid argument to attribute "__mode__"
usr/include/bits/floatn.h(73): error: identifier "__float128" is undefined
```

Which led me to https://github.com/caffe2/caffe2/issues/1194 I'm currently trying out the added host define recommended in the [arch link in that issue](https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/cuda&id=ae90e4d243510e9565e66e9e8e08c509f5719fe0). If that solves it I'll close the issue and hopefully this will help out other users!

**Comment by xd009642** [comment]
So firstly apologies, this is a large template based error. It got a lot further in the build and failed in list_kernels.cu

Here is the full error it seems to be complaining about misuse of an std::tuple, so I'm guessing this is a glibc/nvcc issue?

```
/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/tuple: In instantiation of 'static constexpr bool std::_TC<<anonymous>, _Elements>::_NonNestedTuple() [with _SrcTuple = const std::tuple<tensorflow::VariantUnaryOp, tensorflow::StringPiece, tensorflow::StringPiece>&; bool <anonymous> = true; _Elements = {tensorflow::VariantUnaryOp, tensorflow::StringPiece, tensorflow::StringPiece}]':
/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/tuple:670:591:   required by substitution of 'template<class ... _UElements, class _Dummy, typename std::enable_if<((std::_TC<((1 == sizeof... (_UElements)) && (! std::is_same<std::tuple<tensorflow::VariantUnaryOp, tensorflow::StringPiece, tensorflow::StringPiece>, std::tuple<_Tps ...> >::value)), tensorflow::VariantUnaryOp, tensorflow::StringPiece, tensorflow::StringPiece>::_ConstructibleTuple<_UElements ...>() && std::_TC<((1 == sizeof... (_UElements)) && (! std::is_same<std::tuple<tensorflow::VariantUnaryOp, tensorflow::StringPiece, tensorflow::StringPiece>, std::tuple<_Tps ...> >::value)), tensorflow::VariantUnaryOp, tensorflow::StringPiece, tensorflow::StringPiece>::_ImplicitlyConvertibleTuple<_UElements ...>()) && std::_TC<(std::is_same<_Dummy, void>::value && (1 == 1)), tensorflow::VariantUnaryOp, tensorflow::StringPiece, tensorflow::StringPiece>::_NonNestedTuple<const tuple<_Tps ...>&>()), bool>::type <anonymous> > constexpr std::tuple<tensorflow::VariantUnaryOp, tensorflow::StringPiece, tensorflow::StringPiece>::tuple(const std::tuple<_Tps ...>&) [with _UElements = {tensorflow::VariantUnaryOp, tensorflow::StringPiece, tensorflow::StringPiece}; _Dummy = void; typename std::enable_if<((std::_TC<((1 == sizeof... (_UElements)) && (! std::is_same<std::tuple<tensorflow::VariantUnaryOp, tensorflow::StringPiece, tensorflow::StringPiece>, std::tuple<_Tps ...> >::value)), tensorflow::VariantUnaryOp, tensorflow::StringPiece, tensorflow::StringPiece>::_ConstructibleTuple<_UElements ...>() && std::_TC<((1 == sizeof... (_UElements)) && (! std::is_same<std::tuple<tensorflow::VariantUnaryOp, tensorflow::StringPiece, tensorflow::StringPiece>, std::tuple<_Tps ...> >::value)), tensorflow::VariantUnaryOp, tensorflow::StringPiece, tensorflow::StringPiece>::_ImplicitlyConvertibleTuple<_UElements ...>()) && std::_TC<(std::is_same<_Dummy, void>::value && (1 == 1)), tensorflow::VariantUnaryOp, tensorflow::StringPiece, tensorflow::StringPiece>::_NonNestedTuple<const tuple<_Tps ...>&>()), bool>::type <anonymous> = <missing>]'
/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/bits/stl_pair.h:198:8:   required from 'struct std::pair<const std::tuple<tensorflow::VariantUnaryOp, tensorflow::StringPiece, tensorflow::StringPiece>, std::function<tensorflow::Status(tensorflow::OpKernelContext*, const tensorflow::Variant&, tensorflow::Variant*)> >'
/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/ext/aligned_buffer.h:84:62:   required from 'struct __gnu_cxx::__aligned_buffer<std::pair<const std::tuple<tensorflow::VariantUnaryOp, tensorflow::StringPiece, tensorflow::StringPiece>, std::function<tensorflow::Status(tensorflow::OpKernelContext*, const tensorflow::Variant&, tensorflow::Variant*)> > >'
/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/bits/hashtable_policy.h:248:39:   required from 'struct std::__detail::_Hash_node_value_base<std::pair<const std::tuple<tensorflow::VariantUnaryOp, tensorflow::StringPiece, tensorflow::StringPiece>, std::function<tensorflow::Status(tensorflow::OpKernelContext*, const tensorflow::Variant&, tensorflow::Variant*)> > >'
/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/bits/hashtable_policy.h:279:8:   required from 'struct std::__detail::_Hash_node<std::pair<const std::tuple<tensorflow::VariantUnaryOp, tensorflow::StringPiece, tensorflow::StringPiece>, std::function<tensorflow::Status(tensorflow::OpKernelContext*, const tensorflow::Variant&, tensorflow::Variant*)> >, true>'
/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/bits/hashtable_policy.h:2007:65:   required from 'struct std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<const std::tuple<tensorflow::VariantUnaryOp, tensorflow::StringPiece, tensorflow::StringPiece>, std::function<tensorflow::Status(tensorflow::OpKernelContext*, const tensorflow::Variant&, tensorflow::Variant*)> >, true> > >'
/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/bits/hashtable.h:173:7:   required from 'class std::_Hashtable<std::tuple<tensorflow::VariantUnaryOp, tensorflow::StringPiece, tensorflow::StringPiece>, std::pair<const std::tuple<tensorflow::VariantUnaryOp, tensorflow::StringPiece, tensorflow::StringPiece>, std::function<tensorflow::Status(tensorflow::OpKernelContext*, const tensorflow::Variant&, tensorflow::Variant*)> >, std::allocator<std::pair<const std::tuple<tensorflow::VariantUnaryOp, tensorflow::StringPiece, tensorflow::StringPiece>, std::function<tensorflow::Status(tensorflow::OpKernelContext*, const tensorflow::Variant&, tensorflow::Variant*)> > >, std::__detail::_Select1st, std::equal_to<std::tuple<tensorflow::VariantUnaryOp, tensorflow::StringPiece, tensorflow::StringPiece> >, tensorflow::UnaryVariantOpRegistry::TupleHash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >'
/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/bits/unordered_map.h:104:12:   required from 'class std::unordered_map<std::tuple<tensorflow::VariantUnaryOp, tensorflow::StringPiece, tensorflow::StringPiece>, std::function<tensorflow::Status(tensorflow::OpKernelContext*, const tensorflow::Variant&, tensorflow::Variant*)>, tensorflow::UnaryVariantOpRegistry::TupleHash>'
./tensorflow/core/framework/variant_op_registry.h:183:162:   required from here
/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/tuple:497:244: error: wrong number of template arguments (4, should be 2)
       return  __and_<__not_<is_same<tuple<_Elements...>,
                                                                                                                                                                                                                                                    ^    
/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/type_traits:1547:8: note: provided for 'template<class _From, class _To> struct std::is_convertible'
     struct is_convertible
        ^~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/tuple:504:1: error: body of constexpr function 'static constexpr bool std::_TC<<anonymous>, _Elements>::_NonNestedTuple() [with _SrcTuple = const std::tuple<tensorflow::VariantUnaryOp, tensorflow::StringPiece, tensorflow::StringPiece>&; bool <anonymous> = true; _Elements = {tensorflow::VariantUnaryOp, tensorflow::StringPiece, tensorflow::StringPiece}]' not a return-statement
     }
 ^
/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/tuple: In instantiation of 'static constexpr bool std::_TC<<anonymous>, _Elements>::_NonNestedTuple() [with _SrcTuple = const std::tuple<tensorflow::VariantBinaryOp, tensorflow::StringPiece, tensorflow::StringPiece>&; bool <anonymous> = true; _Elements = {tensorflow::VariantBinaryOp, tensorflow::StringPiece, tensorflow::StringPiece}]':
/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/tuple:670:591:   required by substitution of 'template<class ... _UElements, class _Dummy, typename std::enable_if<((std::_TC<((1 == sizeof... (_UElements)) && (! std::is_same<std::tuple<tensorflow::VariantBinaryOp, tensorflow::StringPiece, tensorflow::StringPiece>, std::tuple<_Tps ...> >::value)), tensorflow::VariantBinaryOp, tensorflow::StringPiece, tensorflow::StringPiece>::_ConstructibleTuple<_UElements ...>() && std::_TC<((1 == sizeof... (_UElements)) && (! std::is_same<std::tuple<tensorflow::VariantBinaryOp, tensorflow::StringPiece, tensorflow::StringPiece>, std::tuple<_Tps ...> >::value)), tensorflow::VariantBinaryOp, tensorflow::StringPiece, tensorflow::StringPiece>::_ImplicitlyConvertibleTuple<_UElements ...>()) && std::_TC<(std::is_same<_Dummy, void>::value && (1 == 1)), tensorflow::VariantBinaryOp, tensorflow::StringPiece, tensorflow::StringPiece>::_NonNestedTuple<const tuple<_Tps ...>&>()), bool>::type <anonymous> > constexpr std::tuple<tensorflow::VariantBinaryOp, tensorflow::StringPiece, tensorflow::StringPiece>::tuple(const std::tuple<_Tps ...>&) [with _UElements = {tensorflow::VariantBinaryOp, tensorflow::StringPiece, tensorflow::StringPiece}; _Dummy = void; typename std::enable_if<((std::_TC<((1 == sizeof... (_UElements)) && (! std::is_same<std::tuple<tensorflow::VariantBinaryOp, tensorflow::StringPiece, tensorflow::StringPiece>, std::tuple<_Tps ...> >::value)), tensorflow::VariantBinaryOp, tensorflow::StringPiece, tensorflow::StringPiece>::_ConstructibleTuple<_UElements ...>() && std::_TC<((1 == sizeof... (_UElements)) && (! std::is_same<std::tuple<tensorflow::VariantBinaryOp, tensorflow::StringPiece, tensorflow::StringPiece>, std::tuple<_Tps ...> >::value)), tensorflow::VariantBinaryOp, tensorflow::StringPiece, tensorflow::StringPiece>::_ImplicitlyConvertibleTuple<_UElements ...>()) && std::_TC<(std::is_same<_Dummy, void>::value && (1 == 1)), tensorflow::VariantBinaryOp, tensorflow::StringPiece, tensorflow::StringPiece>::_NonNestedTuple<const tuple<_Tps ...>&>()), bool>::type <anonymous> = <missing>]'
/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/bits/stl_pair.h:198:8:   required from 'struct std::pair<const std::tuple<tensorflow::VariantBinaryOp, tensorflow::StringPiece, tensorflow::StringPiece>, std::function<tensorflow::Status(tensorflow::OpKernelContext*, const tensorflow::Variant&, const tensorflow::Variant&, tensorflow::Variant*)> >'
/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/ext/aligned_buffer.h:84:62:   required from 'struct __gnu_cxx::__aligned_buffer<std::pair<const std::tuple<tensorflow::VariantBinaryOp, tensorflow::StringPiece, tensorflow::StringPiece>, std::function<tensorflow::Status(tensorflow::OpKernelContext*, const tensorflow::Variant&, const tensorflow::Variant&, tensorflow::Variant*)> > >'
/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/bits/hashtable_policy.h:248:39:   required from 'struct std::__detail::_Hash_node_value_base<std::pair<const std::tuple<tensorflow::VariantBinaryOp, tensorflow::StringPiece, tensorflow::StringPiece>, std::function<tensorflow::Status(tensorflow::OpKernelContext*, const tensorflow::Variant&, const tensorflow::Variant&, tensorflow::Variant*)> > >'
/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/bits/hashtable_policy.h:279:8:   required from 'struct std::__detail::_Hash_node<std::pair<const std::tuple<tensorflow::VariantBinaryOp, tensorflow::StringPiece, tensorflow::StringPiece>, std::function<tensorflow::Status(tensorflow::OpKernelContext*, const tensorflow::Variant&, const tensorflow::Variant&, tensorflow::Variant*)> >, true>'
/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/bits/hashtable_policy.h:2007:65:   required from 'struct std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<const std::tuple<tensorflow::VariantBinaryOp, tensorflow::StringPiece, tensorflow::StringPiece>, std::function<tensorflow::Status(tensorflow::OpKernelContext*, const tensorflow::Variant&, const tensorflow::Variant&, tensorflow::Variant*)> >, true> > >'
/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/bits/hashtable.h:173:7:   required from 'class std::_Hashtable<std::tuple<tensorflow::VariantBinaryOp, tensorflow::StringPiece, tensorflow::StringPiece>, std::pair<const std::tuple<tensorflow::VariantBinaryOp, tensorflow::StringPiece, tensorflow::StringPiece>, std::function<tensorflow::Status(tensorflow::OpKernelContext*, const tensorflow::Variant&, const tensorflow::Variant&, tensorflow::Variant*)> >, std::allocator<std::pair<const std::tuple<tensorflow::VariantBinaryOp, tensorflow::StringPiece, tensorflow::StringPiece>, std::function<tensorflow::Status(tensorflow::OpKernelContext*, const tensorflow::Variant&, const tensorflow::Variant&, tensorflow::Variant*)> > >, std::__detail::_Select1st, std::equal_to<std::tuple<tensorflow::VariantBinaryOp, tensorflow::StringPiece, tensorflow::StringPiece> >, tensorflow::UnaryVariantOpRegistry::TupleHash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >'
/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/bits/unordered_map.h:104:12:   required from 'class std::unordered_map<std::tuple<tensorflow::VariantBinaryOp, tensorflow::StringPiece, tensorflow::StringPiece>, std::function<tensorflow::Status(tensorflow::OpKernelContext*, const tensorflow::Variant&, const tensorflow::Variant&, tensorflow::Variant*)>, tensorflow::UnaryVariantOpRegistry::TupleHash>'
./tensorflow/core/framework/variant_op_registry.h:186:180:   required from here
/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/tuple:497:244: error: wrong number of template arguments (4, should be 2)
       return  __and_<__not_<is_same<tuple<_Elements...>,
                                                                                                                                                                                                                                                    ^    
/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/type_traits:1547:8: note: provided for 'template<class _From, class _To> struct std::is_convertible'
     struct is_convertible
        ^~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/tuple:504:1: error: body of constexpr function 'static constexpr bool std::_TC<<anonymous>, _Elements>::_NonNestedTuple() [with _SrcTuple = const std::tuple<tensorflow::VariantBinaryOp, tensorflow::StringPiece, tensorflow::StringPiece>&; bool <anonymous> = true; _Elements = {tensorflow::VariantBinaryOp, tensorflow::StringPiece, tensorflow::StringPiece}]' not a return-statement
     }
 ^
ERROR: /home/xd009642/3rdparty/tensorflow/tensorflow/core/kernels/BUILD:1884:1: output 'tensorflow/core/kernels/_objs/list_kernels_gpu/tensorflow/core/kernels/list_kernels.cu.pic.o' was not created
ERROR: /home/xd009642/3rdparty/tensorflow/tensorflow/core/kernels/BUILD:1884:1: not all outputs were created or valid
```

**Comment by arunmandal53** [comment]
I have not tried to build tensorflow on fedora yet. You can try by using latest bazel and linux kernal and gcc version according to https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html . Also have you checked if nvidia driver is loaded properly by running command "nvidia-smi" ?

**Comment by xd009642** [comment]
I'll try when I get home from work, however that page show you can build GCC 6.3, I have GCC 7.2 installed. I saw some stuff yesterday that suggests that cuda is broken with GCC >6.x I'll see if I can dig it out later

**Comment by arunmandal53** [comment]
What is the status? Did you downgrade gcc to version 6 or 5.4?

**Comment by xd009642** [comment]
Status hasn't moved on much. I didn't want to downgrade and installing more than one gcc at once seemed a bit of a pain so I tried the nvidia docker approach. Which when installed via the distros package manager deletes things like the dockerd/daemon.json which took me down another rabbit hole...

I'm going to give it a proper stab today and hopefully will have something to report back (hopefully success).

**Comment by xd009642** [comment]
So I've installed gcc 6.4 under the alias cuda-gcc (thanks to the negativo17 nvidia repo). Set that as the path to gcc in configure but it's still getting jammed on the template code. I think from looking at similar issues in other cuda based projects it's nvcc thinking it can compile it when it should instead forward it to gcc.

With this in mind I've removed the reference to the list_kernels gpu source and I'm going to see if that means it builds. I admit I'm not familiar with bazel so if you know a better way to force the fallback to gcc feel free to chip in :smile:

**Comment by xd009642** [comment]
Right it worked! For other fedora 27 users in the same situation here's a summary of the steps taken:

* Add the [negativo17 nvidia repo ](https://negativo17.org/cuda-9-0-cudnn-7-0-and-wayland-support-in-fedora-27/) 
* Install nvidia drivers, cuda, cdnn, cuda-gcc and cuda-gcc-c++
* Patch cuda/include/host_defines.h and append `#define _BITS_FLOATN_H`
* Run the configure script, point to cuda and cuda-gcc
* Go into tensorflow/core/kernel/BUILD and remove gpu_srcs for `list_kernels` library
* Build

There are naturally some restarts required for driver installs to take effect, but I think that's all the steps.

**Comment by tensorflowbutler** [comment]
The original poster has replied to this issue after the stat:awaiting response label was applied.

**Comment by GrimBShrout** [comment]
I had the same issue with multiple sources. Being a minimalist, Instead of using negativo's repositories (**nothing against them, I think they are great and convenient!**) Here is what I did on Fedora 27 after installing all the normal development packages included in epel-release and so forth:

1. Compiled Video card drivers from source using NVIDIA-Linux-x86_64-390.48.run file provided by NVidia..
2. Compiled the Cuda using cuda_9.1.85_387.26_linux.run. as well as declined to install driver for GPU. patched using the three run files, cuda_9.1.85.1_linux.run cuda_9.1.85.2_linux.run cuda_9.1.85.3_linux.run.

3. Created two files within the /etc/profile.d/
```
touch /etc/profile.d/cuda.sh
echo "PATH=$PATH:/usr/local/cuda/bin" >> /etc/profile.d/cuda.sh
echo "export PATH" >> /etc/profile.d/cuda.sh
touch /etc/profile.d/cuda.csh
echo "set path = ( $path /usr/local/cuda/bin )" >> /etc/profile.d/cuda.csh
```
4. Installed gcc63 from package - More than likely other versions will function as well.
5. Created the following two symbolic links:
```
/usr/local/cuda/bin/gcc -> /usr/bin/gcc63
/usr/local/cuda/bin/g++ -> /usr/bin/g++63
```
6. Took the advice from "xd009642"  Patch cuda/include/host_defines.h
`echo "#define _BITS_FLOATN_H" >> /usr/local/cuda/include/host_defines.h`

This resolved all compiling issues with NVCC for me so far. I understand many gcc versions are not supported but it is likely that many will work as well.
