### ISSUE TITLE
Training loss not decreasing if both mixed-precision and XLA/JIT is enabled (with deep model)

### ISSUE THREAD

**Issue by mlech26l** [tensorflow/tensorflow#46392]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- Linux Ubuntu 18.04:
- TensorFlow installed from binary
- TensorFlow 2.4.0
- Python 3.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA 11/cuDNN 8:
- GPU model and memory Titan RTX/2080Ti:

**Describe the current behavior**

Training a deep model, e.g., ResNet50, with both mixed-precision and XLA/JIT simultaneously enabled results in the training loss not decreasing.
Mixed-precision alone or XLA/JIT with float32 works both fine.

**Describe the expected behavior**

Enabling XLA/JIT and mixed-precision training should behave the same as if only mixed-precision is enabled.

**Standalone code to reproduce the issue**
[Minimal Colab notebook to reproduce issue](https://colab.research.google.com/drive/1FLRd52ZejrD-jSc3fHVYrK4L-QE-73JA?usp=sharing)

**Notes**
Note that this bug does not occur for small models like the ConvNet in the mixed-precision training guide.
Also, the fact that training with mixed-precision alone works fine might point to where there could be an issue here.

**Comment by amahendrakar** [comment]
@mlech26l,
I do not have access to the Colab notebook you have linked. Could you please provide the required permissions to view the files. Thanks!

**Comment by mlech26l** [comment]
Hi, @amahendrakar 
Sorry, the following [link](https://colab.research.google.com/drive/1FLRd52ZejrD-jSc3fHVYrK4L-QE-73JA?usp=sharing) should work.

Thanks

**Comment by Krishna2709** [comment]
Hi @mlech26l, try using a Learning Rate scheduler

**Comment by amahendrakar** [comment]
Facing an error stating `AttributeError: module 'tensorflow.keras.mixed_precision' has no attribute 'Policy'` on running the code with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/cded5ab4b8f8225acc70099fb18ad83f/46392-2-3.ipynb#scrollTo=oQSmky8hrZ4X).

Was able to reproduce the issue with [TF v2.4](https://colab.research.google.com/gist/amahendrakar/299a1ac5dd53648c3ad1b65dbe07a5c5/46392.ipynb).

Whereas with the latest [TF-nightly](https://colab.research.google.com/gist/amahendrakar/8acda2b2bddd514491898af0c2d77a03/46392-tf-nightly.ipynb), `model.fit` runs indefinitely. Please check the linked gist for reference. Thanks!

**Comment by juliangrosshauser** [comment]
Ran into the same problem when training an [EfficientDet](https://github.com/google/automl/tree/master/efficientdet) model after upgrading from TF 2.3.1 to 2.4.1.
After updating to tf-nightly 2.5.0-dev20210127 the loss is decreasing again as expected.

@amahendrakar Code to enable mixed precision is slightly different in TF 2.3:

```python
policy = tf.keras.mixed_precision.experimental.Policy("mixed_float16")
tf.keras.mixed_precision.experimental.set_policy(policy)
```

**Comment by mlech26l** [comment]
Hi @juliangrosshauser and @jvishnuvardhan 

I can confirm that the issue seems to be fixed in the latest tf-nightly.

**Comment by saikumarchalla** [comment]
@mlech26l Thanks for updating us. Closing the issue since the issue was fixed in Nightly version.Thanks!
