### ISSUE TITLE
RuntimeError: No C++ shape function registered for standard op: SingleImageRandomDotStereograms

### ISSUE THREAD

**Issue by mGworkS** [tensorflow/tensorflow#15429]
single_image_random_dot_stereograms (windows bug)
the function works fine on ubuntu 16.04 / tf 1.4.0 (CPU)

I know, that the support for unsupported libraries in tf.contrib on Windows is incomplete, and left up to the individual contributors. I found some sketchy solutions by editing gen_single_image_random_dot_stereograms_ops.py, but i could not figure it out correctly.

**Source code**
```
import tensorflow as tf
from tensorflow.contrib.image import single_image_random_dot_stereograms
img=[[1,2,3,3,2,1],
     [1,2,3,4,5,2],
     [1,2,3,4,5,3],
     [1,2,3,4,5,4],
     [6,5,4,4,5,5]]
session = tf.InteractiveSession()
sirds = single_image_random_dot_stereograms(
    img,
    convergence_dots_size=8,
    number_colors=256,normalize=True)
out = sirds.eval()
png = tf.image.encode_png(out).eval()
with open('picture_out.png', 'wb') as f:
  f.write(png)
```

**Error**
Windows 10 Pro, 1709
conda version : 4.3.30
python version: 3.6.3
tensorflow-gpu 1.4.0

```
File "C:\Users\###\Anaconda3\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 696, in _call_cpp_shape_fn_impl
    "No C++ shape function registered for standard op: %s" % op.type)
RuntimeError: No C++ shape function registered for standard op: SingleImageRandomDotStereograms
```

Windows 10 Pro, 1709
conda version : 4.3.30
python version: 3.5.4
tensorflow 1.3.0/tensorflow 1.2.0

`AttributeError: 'NoneType' object has no attribute 'single_image_random_dot_stereograms`

**Comment by yongtang** [comment]
The `SingleImageRandomDotStereograms` does not have a shape function I think that is the issue.

I added a PR #15431 with the shape function added.

Note`SingleImageRandomDotStereograms` takes an attribute of `output_image_shape` which is in the format of `[X, Y, C]` (`[ImageX, ImageY, Channel]`).

However, the actual data output is in the format of `[ImageY, ImageX, Channel]` (`[h, w, c]`). So by default the output_image_shape has the value of [1024, 768, 1] but the output data will be [768, 1024, 1].

Don't know if we want to change the behavior or not so I leave the behavior alone for now.
