### ISSUE TITLE
Error building custom operator

### ISSUE THREAD

**Issue by eyalhir74** [tensorflow/tensorflow#71568]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

tf 2.16.2

### Custom code

No

### OS platform and distribution

Ubuntu 22.04.4 LTS

### Python version

3.10.12

### GCC/compiler version

g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

### Current behavior?

I'm following the tutorial here: https://www.tensorflow.org/guide/create_op

When trying to compile the cc file as described in the tutorial:
g++  GPUInstrumentOp.cc -fPIC "-I/usr/local/lib/python3.10/dist-packages/tensorflow/include" "-L/usr/local/lib/python3.10/dist-packages/tensorflow" -O2

I'm getting the following error:
----------------------------------------

`GPUInstrumentOp.cc: In lambda function:
GPUInstrumentOp.cc:12:22: error: 'OK' is not a member of 'tsl::Status' {aka 'absl::lts_20230802::Status'}
   12 |       return Status::OK();
      |                      ^~
GPUInstrumentOp.cc: At global scope:
GPUInstrumentOp.cc:10:16: error: cannot convert '<lambda(tensorflow::shape_inference::InferenceContext*)>' to 'tensorflow::OpShapeInferenceFn' {aka 'std::function<absl::lts_20230802::Status(tensorflow::shape_inference::InferenceContext*)>'}
   10 |     .SetShapeFn([](::tensorflow::shape_inference::InferenceContext* c) {
In file included from GPUInstrumentOp.cc:1:
/usr/local/lib/python3.10/dist-packages/tensorflow/include/tensorflow/core/framework/op.h:272:54: note:   initializing argument 1 of 'tensorflow::register_op::OpDefBuilderWrapper& tensorflow::register_op::OpDefBuilderWrapper::SetShapeFn(tensorflow::OpShapeInferenceFn)'
  272 |   OpDefBuilderWrapper& SetShapeFn(OpShapeInferenceFn fn) {
      |                                   ~~~~~~~~~~~~~~~~~~~^~
`

Any assistance is very apperciated

### Standalone code to reproduce the issue

```shell
The code from https://www.tensorflow.org/guide/create_op
```

**Comment by tilakrayal** [comment]
@eyalhir74,
Can you check if your op file is following [this](https://github.com/tensorflow/custom-op#template-overview) folder structure under respective kernels.
Also did you try building the sample custom op zero_out_ops mentioned in the above link.

https://github.com/tensorflow/tensorflow/issues/55148

Thank you!

**Comment by eyalhir74** [comment]
Hi @tilakrayal ,
  So seems like the zero_out_ops is somewhat out of date as far as I can understand..
  I'm working with Python 3.6 and a NVIDIA docker (nvcr.io/nvidia/tritonserver:24.05-py3)

  I had to use "return Status();" instead of "return Status::OK();"
  
  Also if someone stumbles on this and get the same/similar issues, this is the makefile I've used to compile it all

`
TF_CFLAGS=-I/usr/local/lib/python3.10/dist-packages/tensorflow/include
TF_LFLAGS=-L/usr/local/lib/python3.10/dist-packages/tensorflow -l:libtensorflow_framework.so.2
CUDA_FLAGS=--expt-relaxed-constexpr -gencode arch=compute_80,code=sm_80 -gencode arch=compute_86,code=sm_86 -gencode arch=compute_89,code=sm_89 -gencode arch=compute_90,code=sm_90 -gencode arch=compute_90,code=compute_90

CFLAGS=-m64 -D_GLIBCXX_USE_CXX11_ABI=1 --std=c++17 -DEIGEN_MAX_ALIGN_BYTES=64 -O2
NVCC_CFLAGS=--compiler-options "-fPIC -pthread"

all: build

build: GPUInstrumentOp

GPUInstrumentOp.o:GPUInstrumentOp.cc
	nvcc -ccbin g++ ${CFLAGS} ${NVCC_CFLAGS} ${TF_CFLAGS} -o GPUInstrumentOp.o -c GPUInstrumentOp.cc

GPUInstrumentKernels.o: GPUInstrumentKernels.cu
	nvcc -ccbin g++ ${CFLAGS} ${NVCC_CFLAGS} ${TF_CFLAGS} ${CUDA_FLAGS} -o GPUInstrumentKernels.o -c GPUInstrumentKernels.cu

GPUInstrumentOp: GPUInstrumentOp.o GPUInstrumentKernels.o
	g++ ${CFLAGS} -Wl,--no-as-needed ${TF_CFLAGS} ${TF_LFLAGS} --shared  -o GPUInstrument.so GPUInstrumentOp.o GPUInstrumentKernels.o

clean:
	rm -f GPUInstrumentOp.o GPUInstrumentKernels.o GPUInstrumentOp.so
`

**Comment by tilakrayal** [comment]
@eyalhir74,
python 3.6 is not compatible with the latest tensorflow 2.16. Could you please try with the python 3.9-3.12 and the latest stable tensorflow v2.17.0 and update the same. Thank you!

**Comment by Civati** [comment]
i have the same problem. Some solution?
