### ISSUE TITLE
Exploration of cmake on Ubuntu: /tensorflow/stream_executor/gcuda.h

### ISSUE THREAD

**Issue by joshsuihn** [tensorflow/tensorflow#5465]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

### Environment info
Operating System: Ubuntu14.04

Installed version of CUDA and cuDNN: 8.0/5.1.5
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from source, provide 
1. The commit hash (`git rev-parse HEAD`)
f870373756f8017cf89c7a6e3889539aba834265 

I'm exploring TensorFlow build with cmake on Ubuntu14.04

While trying building, I'm stuck with the following error.

It seems to me ..
1. device_functions.h header is not included? 
2. add/remove definitions such as -D__NVCC__? 
3. tf_stream_executor.cmake file looks incomplete. what do I need to add to the file? 

```
> In file included from /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.cc:16:0:
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:234:1: error: ‘__forceinline__’ does not name a type
>  __forceinline__ __device__ clock_t __gcuda_nvcc_clock() { return clock(); }
>  ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:235:1: error: ‘__forceinline__’ does not name a type
>  __forceinline__ __device__ int __gcuda_nvcc__clz(int x) {
>  ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:238:1: error: ‘__forceinline__’ does not name a type
>  __forceinline__ __device__ int __gcuda_nvcc__clzll(long long int x) {
>  ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:241:1: error: ‘__forceinline__’ does not name a type
>  __forceinline__ __device__ float __gcuda_nvcc__fdividef(float a, float b) {
>  ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:244:1: error: ‘__forceinline__’ does not name a type
>  __forceinline__ __device__ int __gcuda_nvcc__ffsll(long long int x) { // NOLINT
>  ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:247:1: error: ‘__forceinline__’ does not name a type
>  __forceinline__ __device__ int __gcuda_nvcc__popc(unsigned int x) {
>  ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:250:1: error: ‘__forceinline__’ does not name a type
>  __forceinline__ __device__ float __gcuda_nvcc__powf(float a, float b) {
>  ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:253:1: error: ‘__forceinline__’ does not name a type
>  __forceinline__ __device__ void __gcuda_nvcc__sincosf(
>  ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:257:1: error: ‘__forceinline__’ does not name a type
>  __forceinline__ __device__ unsigned int __gcuda_nvcc__umulhi(
>  ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:263:1: error: ‘__forceinline__’ does not name a type
>  __forceinline__ __device__ unsigned int __gcuda_nvcc__ballot(int x) {
>  ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:274:9: error: ‘::abs’ has not been declared
>  using ::abs;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:275:9: error: ‘::atomicAdd’ has not been declared
>  using ::atomicAdd;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:276:9: error: ‘::atomicCAS’ has not been declared
>  using ::atomicCAS;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:277:9: error: ‘::ceil’ has not been declared
>  using ::ceil;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:278:9: error: ‘::ceilf’ has not been declared
>  using ::ceilf;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:279:9: error: ‘::cos’ has not been declared
>  using ::cos;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:280:9: error: ‘::cosf’ has not been declared
>  using ::cosf;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:281:9: error: ‘::erfcinv’ has not been declared
>  using ::erfcinv;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:282:9: error: ‘::erfcinvf’ has not been declared
>  using ::erfcinvf;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:283:9: error: ‘::exp’ has not been declared
>  using ::exp;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:284:9: error: ‘::expf’ has not been declared
>  using ::expf;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:285:9: error: ‘::fabs’ has not been declared
>  using ::fabs;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:286:9: error: ‘::fabsf’ has not been declared
>  using ::fabsf;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:287:9: error: ‘::floor’ has not been declared
>  using ::floor;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:288:9: error: ‘::floorf’ has not been declared
>  using ::floorf;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:289:9: error: ‘::fabs’ has not been declared
>  using ::fabs;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:290:9: error: ‘::fabsf’ has not been declared
>  using ::fabsf;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:291:9: error: ‘::fma’ has not been declared
>  using ::fma;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:292:9: error: ‘::fmaf’ has not been declared
>  using ::fmaf;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:293:9: error: ‘::fmax’ has not been declared
>  using ::fmax;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:294:9: error: ‘::fmaxf’ has not been declared
>  using ::fmaxf;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:295:9: error: ‘::fmin’ has not been declared
>  using ::fmin;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:296:9: error: ‘::fminf’ has not been declared
>  using ::fminf;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:297:9: error: ‘::log’ has not been declared
>  using ::log;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:298:9: error: ‘::log1p’ has not been declared
>  using ::log1p;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:299:9: error: ‘::log1pf’ has not been declared
>  using ::log1pf;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:300:9: error: ‘::logf’ has not been declared
>  using ::logf;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:301:9: error: ‘::max’ has not been declared
>  using ::max;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:302:9: error: ‘::min’ has not been declared
>  using ::min;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:303:9: error: ‘::powf’ has not been declared
>  using ::powf;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:305:9: error: ‘::sin’ has not been declared
>  using ::sin;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:306:9: error: ‘::sinf’ has not been declared
>  using ::sinf;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:307:9: error: ‘::sincos’ has not been declared
>  using ::sincos;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:308:9: error: ‘::sincosf’ has not been declared
>  using ::sincosf;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:309:9: error: ‘::sincospi’ has not been declared
>  using ::sincospi;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:310:9: error: ‘::sincospif’ has not been declared
>  using ::sincospif;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:311:9: error: ‘::sqrt’ has not been declared
>  using ::sqrt;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:312:9: error: ‘::sqrtf’ has not been declared
>  using ::sqrtf;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:313:9: error: ‘::tanh’ has not been declared
>  using ::tanh;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:314:9: error: ‘::trunc’ has not been declared
>  using ::trunc;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:315:9: error: ‘::truncf’ has not been declared
>  using ::truncf;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:316:9: error: ‘::trunc’ has not been declared
>  using ::trunc;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:326:1: error: ‘__forceinline__’ does not name a type
>  __forceinline__ __host__ __device__ float rsqrtf(float x) {
>  ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:329:1: error: ‘__forceinline__’ does not name a type
>  __forceinline__ __host__ __device__ double rsqrt(double x) {
>  ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:334:1: error: ‘__forceinline__’ does not name a type
>  __forceinline__ __device__ int clock() { return __gcuda_nvcc_clock(); }
>  ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:336:1: error: ‘__forceinline__’ does not name a type
>  __forceinline__ __device__ int __clz(int x) {
>  ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:340:1: error: ‘__forceinline__’ does not name a type
>  __forceinline__ __device__ int __clz(long long int x) {
>  ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:344:1: error: ‘__forceinline__’ does not name a type
>  __forceinline__ __device__ float __fdividef(float a, float b) {
>  ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:348:1: error: ‘__forceinline__’ does not name a type
>  __forceinline__ __device__ int __ffsll(long long int x) { // NOLINT
>  ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:352:1: error: ‘__forceinline__’ does not name a type
>  __forceinline__ __device__ int __popc(unsigned int x) {
>  ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:356:1: error: ‘__forceinline__’ does not name a type
>  __forceinline__ __device__ float __powf(float a, float b) {
>  ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:360:1: error: ‘__forceinline__’ does not name a type
>  __forceinline__ __device__ void __sincosf(float x, float *sptr, float *cptr) {
>  ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:364:1: error: ‘__forceinline__’ does not name a type
>  __forceinline__ __device__ unsigned int __umulhi(unsigned int x,
>  ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:378:1: error: ‘__forceinline__’ does not name a type
>  __forceinline__ __device__ unsigned int __ballot(int x) {
>  ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:384:9: error: ‘::__shfl’ has not been declared
>  using ::__shfl;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:385:9: error: ‘::__shfl_down’ has not been declared
>  using ::__shfl_down;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:386:9: error: ‘::__shfl_up’ has not been declared
>  using ::__shfl_up;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:387:9: error: ‘::__shfl_xor’ has not been declared
>  using ::__shfl_xor;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:391:9: error: ‘::__ldg’ has not been declared
>  using ::__ldg;
>          ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:402:8: error: ‘__device__’ does not name a type
>  inline __device__ int isfinite(float x) {
>         ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:405:8: error: ‘__device__’ does not name a type
>  inline __device__ int isfinite(double x) {
>         ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.h:408:8: error: ‘__device__’ does not name a type
>  inline __device__ int isfinite(long double x) {
>         ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.cc:23:1: error: ‘map’ in namespace ‘std’ does not name a type
>  std::map<void *, KernelCacheConfig> &GetGcudaccStubToCacheConfigMap() {
>  ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.cc:29:5: error: ‘StreamExecutor’ was not declared in this scope
>      StreamExecutor *stream_exec) {
>      ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.cc:29:21: error: ‘stream_exec’ was not declared in this scope
>      StreamExecutor *stream_exec) {
>                      ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.cc:29:34: error: expected ‘,’ or ‘;’ before ‘{’ token
>      StreamExecutor *stream_exec) {
>                                   ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.cc:102:1: error: expected ‘}’ at end of input
>  }  // namespace perftools
>  ^
> /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.cc:102:1: error: expected ‘}’ at end of input
> make[2]: *** [CMakeFiles/tf_stream_executor.dir/home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.cc.o] Error 1
> make[1]: *** [CMakeFiles/tf_stream_executor.dir/all] Error 2
> make: *** [all] Error 2
```

**Comment by drpngx** [comment]
OK, it looks like you are using cmake. Could you clarify what command you used to build?

@mrry for CC.

**Comment by joshsuihn** [comment]
Yes, using cmake, i am exploring and  trying to build tf.  I had to modify CMakeList such as cuda versions for cuda_config.h and comments on Windows' dependencies or macro because current cmakelist was set up for wondows env. After some edits, commands I entered are pretty much like cmake commands:  cmake .. (with cudnn_home flag and gpu enabled), then sudo make
I figured out serveral build errors previously, but am stuck with this issue as of now.

**Comment by drpngx** [comment]
From what I can tell, the cmake only works on GPU on windows. So if you could get those fixes as PR onc e you're done that would be terrific.

Could you show how the compiler is called? IIRC, it's make VERBOSE=1. Then we can cross-check against the blaze command-line.

**Comment by joshsuihn** [comment]
Hi again, as you mentioned, as of now TF works on GPU + Windows. That's why it's in my experimental stage. In 'CMakeList.txt', there are options such as "(tensorflow_VERBOSE "Enable for verbose output" ON)" which you can pass options with :cmake" (e.g. cmake  ... -Dxxx). The command "cmake ..." generates 'Makefile', then you can put 'sudo make'. As another build option apart from bazel, I think CMake is a cool feature. BTW, tf_stream_executor is blocking my progress with the error above, do you have any insight about this ? 
Thanks!

**Comment by joshsuihn** [comment]
Seemingly, __NVCC__ shouldn't be used  for gcuda.cc? 
[91%] Building CXX object CMakeFiles/tf_stream_executor.dir/home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.cc.o
/usr/bin/c++   
-DEIGEN_AVOID_STL_ARRAY 
-DEIGEN_HAS_C99_MATH 
-DLANG_CXX11 
-DTENSORFLOW_USE_EIGEN_THREADPOOL 
-D__NVCC__ 
-I/home/ubuntu/workspace/tensorflow 
-I/home/ubuntu/workspace/tensorflow/tensorflow/contrib/cmake/build2 
-I/home/ubuntu/workspace/tensorflow/tensorflow/contrib/cmake/build2/external/zlib_archive 
-I/home/ubuntu/workspace/tensorflow/tensorflow/contrib/cmake/build2/external/gif_archive/giflib-5.1.4 
-I/home/ubuntu/workspace/tensorflow/tensorflow/contrib/cmake/build2/external/png_archive 
-I/home/ubuntu/workspace/tensorflow/tensorflow/contrib/cmake/build2/external/jpeg_archive 
-I/home/ubuntu/workspace/tensorflow/tensorflow/contrib/cmake/build2/external/eigen_archive 
-I/home/ubuntu/workspace/tensorflow/third_party/eigen3 
-I/home/ubuntu/workspace/tensorflow/tensorflow/contrib/cmake/build2/gemmlowp/src/gemmlowp 
-I/home/ubuntu/workspace/tensorflow/tensorflow/contrib/cmake/build2/jsoncpp/src/jsoncpp 
-I/home/ubuntu/workspace/tensorflow/tensorflow/contrib/cmake/build2/external/farmhash_archive 
-I/home/ubuntu/workspace/tensorflow/tensorflow/contrib/cmake/build2/external/farmhash_archive/util 
-I/home/ubuntu/workspace/tensorflow/tensorflow/contrib/cmake/build2/external/highwayhash 
-I/home/ubuntu/workspace/tensorflow/tensorflow/contrib/cmake/build2/protobuf/src/protobuf/src 
-I/home/ubuntu/workspace/tensorflow/tensorflow/contrib/cmake/build2/grpc/src/grpc/include 
-I/usr/local/cuda 
-I/usr/local/cuda/extras/CUPTI/include 
-I/usr/local/cuda/include 
-I/home/ubuntu/workspace/tensorflow/third_party/gpus  
-fno-exceptions 
-std=c++11 -fPIC   
-o CMakeFiles/tf_stream_executor.dir/home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.cc.o 
-c /home/ubuntu/workspace/tensorflow/tensorflow/stream_executor/gcuda.cc

**Comment by drpngx** [comment]
The file has ifdefs for CUDA. What error are you getting?

**Comment by joshsuihn** [comment]
While figuring out several issues, I added 'add_definitions(-D__NVCC__) to tf_core_kernel , which caused that error.  Finally, I built tf with cmake and got .so and .a libraries, but I need to test and validate them. 
Plus, I'm also exploring how to build .whl package after cmake build.

**Comment by drpngx** [comment]
Woohoo!

Nice! The CMake should have a rule to build the pip tool:

```
tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
```

**Comment by mrry** [comment]
Note that building the PIP package with CMake is slightly different: you would do `make tf_python_build_pip_package` to generate the wheel file.

**Comment by joshsuihn** [comment]
Thanks for your info, I will try. BTW, Actually, I was looking at 'tf_python.cmake' 

```
add_custom_command(TARGET tf_python_build_pip_package POST_BUILD
  COMMAND ${CMAKE_COMMAND} -E copy ${tensorflow_source_dir}/tensorflow/contrib/cmake/setup.py
                                   ${CMAKE_CURRENT_BINARY_DIR}/tf_python/)
if(WIN32 OR UNIX)
  add_custom_command(TARGET tf_python_build_pip_package POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy ${CMAKE_CURRENT_BINARY_DIR}/${CMAKE_BUILD_TYPE}/pywrap_tensorflow.dll
                                     ${CMAKE_CURRENT_BINARY_DIR}/tf_python/tensorflow/python/_pywrap_tensorflow.pyd)
else()
  add_custom_command(TARGET tf_python_build_pip_package POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy ${CMAKE_CURRENT_BINARY_DIR}/libpywrap_tensorflow.so
                                     ${CMAKE_CURRENT_BINARY_DIR}/tf_python/tensorflow/python/_pywrap_tensorflow.so)
endif()
add_custom_command(TARGET tf_python_build_pip_package POST_BUILD
  COMMAND ${CMAKE_COMMAND} -E copy ${tensorflow_source_dir}/tensorflow/tools/pip_package/README
                                   ${CMAKE_CURRENT_BINARY_DIR}/tf_python/)
add_custom_command(TARGET tf_python_build_pip_package POST_BUILD
  COMMAND ${CMAKE_COMMAND} -E copy ${tensorflow_source_dir}/tensorflow/tools/pip_package/MANIFEST.in
                                   ${CMAKE_CURRENT_BINARY_DIR}/tf_python/)
add_custom_command(TARGET tf_python_build_pip_package POST_BUILD
  COMMAND ${PYTHON_EXECUTABLE} ${CMAKE_CURRENT_BINARY_DIR}/tf_python/setup.py bdist_wheel
  WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/tf_python)
```

**Comment by drpngx** [comment]
Did you get this to work? It would be fabulous if you could make a PR out of it.

**Comment by mrry** [comment]
The line `if(WIN32 OR UNIX)` in the CMake file you quoted looks wrong. That branch should only execute on `WIN32` (and it does [at head](https://github.com/tensorflow/tensorflow/blame/20c3d37ecc9bef0e106002b9d01914efd548e66b/tensorflow/contrib/cmake/tf_python.cmake#L371)) because otherwise when running on Ubuntu it'll look for a `.dll` file that doesn't exist.

**Comment by joshsuihn** [comment]
@mrry, Thans you for your feedback. it was fixed in my CMake file. I could build TF and create whl, it seems working wen I ran ~/workspace/tensorflow$ ls tensorflow/models/image/mnist/convolutional.py, but it's CPU only.  still working on this as of now.

**Comment by joshsuihn** [comment]
I can leave summary here; 
In CMakeList.txt 
1. a wrong version number for cuda_config.h for unix/linux
2. no "add_definitions" are for unix/linux (currently, many -D flags are for Windows)
3.  cuda header path (include_directories) is needed 
4.  cudnn so libs is needed 
let me update this soon again. 
Thanks

**Comment by drpngx** [comment]
Thanks @joshsuihn , very helpful.

**Comment by girving** [comment]
@drpngx What's the status of this bug?

**Comment by drpngx** [comment]
User found a resolution.
