### ISSUE TITLE
AttributeError: 'Sequential' object has no attribute 'target_tensors'

### ISSUE THREAD

**Issue by ssable** [tensorflow/tensorflow#29798]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.14.0-rc0
- Python version: 3.6.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

Example works fine with tensorflow 1.13.1.

import os
import tensorflow as tf
from tensorflow.keras import datasets, layers, models

(train_images, train_labels), (test_images, test_labels) = datasets.mnist.load_data()
train_images = train_images.reshape((60000, 28, 28, 1))
test_images = test_images.reshape((10000, 28, 28, 1))
train_images, test_images = train_images / 255.0, test_images / 255.0
model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

tpu_model = tf.contrib.tpu.keras_to_tpu_model(model,
          strategy=tf.contrib.tpu.TPUDistributionStrategy(
          tf.contrib.cluster_resolver.TPUClusterResolver(tpu='grpc://' + os.environ['COLAB_TPU_ADDR'])
        ))
tpu_model.fit(train_images, train_labels, epochs=5)

When using tensorflow 1.14.0-rc1, I got following error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-73ec4b0d99a3> in <module>()
      1 tpu_model = tf.contrib.tpu.keras_to_tpu_model(model,
      2           strategy=tf.contrib.tpu.TPUDistributionStrategy(
----> 3           tf.contrib.cluster_resolver.TPUClusterResolver(tpu='grpc://' + os.environ['COLAB_TPU_ADDR'])
      4         ))
      5 tpu_model.fit(train_images, train_labels, epochs=5)

2 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py in __init__(self, cpu_model, strategy)
   1426           self._cpu_model.sample_weight_mode,
   1427           self._cpu_model._compile_weighted_metrics,
-> 1428           self._cpu_model.target_tensors,
   1429       )
   1430 

AttributeError: 'Sequential' object has no attribute 'target_tensors'

**Comment by kaushil24** [comment]
Facing the same error while running code on Colab. <br>
Any solution anyone ?

**Comment by ssable** [comment]
I managed to get things running by moving to the new TPU API:

resolver = tf.distribute.cluster_resolver.TPUClusterResolver()
tf.config.experimental_connect_to_host(resolver.master())
tf.tpu.experimental.initialize_tpu_system(resolver)
strategy = tf.distribute.experimental.TPUStrategy(resolver)
with strategy.scope():
    model.compile(...)
    model.fit(...)

I also had to pass directly some tf.data tensor to the fit function rather than a generator function.

However I think it is very unfortunate to break APIs during minor version updates. Also while training an epoch seems to run much faster than before, the accuracy stays much lower as before even after many epochs; so there seem to be some big change in the way it works compared to before.

**Comment by helderdaniel** [comment]
It is also needed to create the model with strategy.scope():

with strategy.scope():
  #Create model, eg.:
  #model=tf.keras.models.Sequential([ .. 
  model.compile(...)
  model.fit(...)

**Comment by kaushil24** [comment]
> It is also needed to create the model with strategy.scope():
> 
> ```
> with strategy.scope():
>   #Create model, eg.:
>   #model=tf.keras.models.Sequential([ .. 
>   model.compile(...)
>   model.fit(...)
> ```

I tried this, but then it gives a new error saying ''Session e9459ae257feda74 is not found.''. 
Here is my code:
```
import tensorflow as tf
resolver = tf.distribute.cluster_resolver.TPUClusterResolver()
tf.config.experimental_connect_to_host(resolver.master())
tf.tpu.experimental.initialize_tpu_system(resolver)
strategy = tf.distribute.experimental.TPUStrategy(resolver)

with strategy.scope():
  base = InceptionV3(weights='imagenet', input_shape=(200,150,3), include_top=False)
  model = Sequential()
  model.add(base)
  model.add(Flatten())
  model.add(Dense(128))#, activation='relu'))
  model.add(Activation('relu'))
  model.add(Dropout(0.5))
  model.add(Dense(128))#, activation='relu'))
  model.add(Dropout(0.5))
  model.add(Activation('relu'))
  model.add(Dense(100))#, activation='relu'))
  model.add(Activation('relu'))
  model.add(Dense(12))#, activation='sigmoid'))
  model.add(Activation('sigmoid'))

  model.summary()
  model.compile(loss='binary_crossentropy', optimizer=sgd, metrics=['acc'])
  model.fit(trainX, trainy, epochs=5, batch_size=32, validation_split=0.08)
```
What should I do ?

**Comment by ssable** [comment]
I managed to run with TPUs and tf 1.14.0-rc1 but the accuracy was really poor compared to tensorflow 1.13.1. Even GPU did not give good results. So I switched back to using CPU for the moment and accuracy is much better (and performance not much degraded actually so I am a bit confused).

**Comment by achandraa** [comment]
Looks like the issue is been resolved , however you are facing low accuracy on 1.14-rc1 as compared to 1.13.1. Will it be possible to give us some information on the same. This will help us to get the root cause. Thanks!

**Comment by ssable** [comment]
Thank you for your feedback.
The issue to me is that tensorflow API compatibility was broken between 1.13 and 1.14 concerning TPU usage. I understand that part is experimental so that may be acceptable to you and you can close the ticket.

Concerning the performance and quality degradation when using TPU with tf 1.14, I will open a separate ticket with full info.
Thanks

**Comment by achandraa** [comment]
@ssable : Thanks for the response. Happy to help.

**Comment by helderdaniel** [comment]
There are imports missing

> import tensorflow as tf
> resolver = tf.distribute.cluster_resolver.TPUClusterResolver()
> tf.config.experimental_connect_to_host(resolver.master())
> tf.tpu.experimental.initialize_tpu_system(resolver)
> strategy = tf.distribute.experimental.TPUStrategy(resolver)
> 
> with strategy.scope():
>   base = InceptionV3(weights='imagenet', input_shape=(200,150,3), include_top=False)
>   model = Sequential()
>   model.add(base)
>   model.add(Flatten())
>   model.add(Dense(128))#, activation='relu'))
>   model.add(Activation('relu'))
>   model.add(Dropout(0.5))
>   model.add(Dense(128))#, activation='relu'))
>   model.add(Dropout(0.5))
>   model.add(Activation('relu'))
>   model.add(Dense(100))#, activation='relu'))
>   model.add(Activation('relu'))
>   model.add(Dense(12))#, activation='sigmoid'))
>   model.add(Activation('sigmoid'))
> 
>   model.summary()
>   model.compile(loss='binary_crossentropy', optimizer=sgd, metrics=['acc'])
>   model.fit(trainX, trainy, epochs=5, batch_size=32, validation_split=0.08)

**Comment by helderdaniel** [comment]
@kaushil24, there are imports missing in your code

**Comment by giovannibaratta** [comment]
> > It is also needed to create the model with strategy.scope():
> > ```
> > with strategy.scope():
> >   #Create model, eg.:
> >   #model=tf.keras.models.Sequential([ .. 
> >   model.compile(...)
> >   model.fit(...)
> > ```
> 
> I tried this, but then it gives a new error saying ''Session e9459ae257feda74 is not found.''.
> Here is my code:
> 
> ```
> import tensorflow as tf
> resolver = tf.distribute.cluster_resolver.TPUClusterResolver()
> tf.config.experimental_connect_to_host(resolver.master())
> tf.tpu.experimental.initialize_tpu_system(resolver)
> strategy = tf.distribute.experimental.TPUStrategy(resolver)
> 
> with strategy.scope():
>   base = InceptionV3(weights='imagenet', input_shape=(200,150,3), include_top=False)
>   model = Sequential()
>   model.add(base)
>   model.add(Flatten())
>   model.add(Dense(128))#, activation='relu'))
>   model.add(Activation('relu'))
>   model.add(Dropout(0.5))
>   model.add(Dense(128))#, activation='relu'))
>   model.add(Dropout(0.5))
>   model.add(Activation('relu'))
>   model.add(Dense(100))#, activation='relu'))
>   model.add(Activation('relu'))
>   model.add(Dense(12))#, activation='sigmoid'))
>   model.add(Activation('sigmoid'))
> 
>   model.summary()
>   model.compile(loss='binary_crossentropy', optimizer=sgd, metrics=['acc'])
>   model.fit(trainX, trainy, epochs=5, batch_size=32, validation_split=0.08)
> ```
> 
> What should I do ?

I have the same problem. @kaushil24 How many samples do you have in `trainX`? I found out that if I increase too much the number of samples or the size of the images, `model.fit` gives this error. 

I tried this is colab (tf = 1.14.0-rc1).

```
import tensorflow as tf
import numpy as np
import os

tpu_address = 'grpc://' + os.environ['COLAB_TPU_ADDR']
batchSize = 64
numImages = 1000 * batchSize
width = 50
height = 50

print("Img", str(numImages))

randomImages = np.random.rand(numImages,width,height,3).astype('float32') 
randomLabels = np.random.randint(2, size=numImages).astype('int32') 

#model
resolver = tf.contrib.cluster_resolver.TPUClusterResolver(tpu_address)
tf.contrib.distribute.initialize_tpu_system(resolver)
strategy = tf.contrib.distribute.TPUStrategy(resolver)

with strategy.scope():
  inputs = tf.keras.layers.Input(shape=(width, height, 3))
  outputLayer = inputs
  for i in range(0,3):
    outputLayer = tf.keras.layers.Conv2D(filters=64, kernel_size = 3, padding = 'valid')(outputLayer)
    outputLayer = tf.keras.layers.BatchNormalization()(outputLayer)
    outputLayer = tf.keras.layers.ReLU()(outputLayer)
  outputLayer = tf.keras.layers.Flatten()(outputLayer)
  outputLayer = tf.keras.layers.Dense(2)(outputLayer)
  outputLayer = tf.keras.layers.BatchNormalization()(outputLayer)
  outputLayer = tf.keras.layers.Softmax()(outputLayer)

  model = tf.keras.Model(inputs = inputs, outputs = outputLayer)
  
  model.compile(
      optimizer=tf.train.AdamOptimizer(learning_rate = 0.0001),
      loss=tf.keras.losses.sparse_categorical_crossentropy,
      metrics=['sparse_categorical_accuracy']
    )
```

With `numImages = 64000`, `width = 50`, `height = 50` the code works fine. If I set `numImages = 80000` or `width = 55` and `height = 55`, I get this error:

<details>
   <summary> Error </summary>

   ```
/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1340       return self._call_tf_sessionrun(
-> 1341           options, feed_dict, fetch_list, target_list, run_metadata)
   1342 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1428         self._session, options, feed_dict, fetch_list, target_list,
-> 1429         run_metadata)
   1430 

AbortedError: Session 290fcb1d6cd9689a is not found.

During handling of the above exception, another exception occurred:

AbortedError                              Traceback (most recent call last)
<ipython-input-3-b914521409eb> in <module>()
     67                 y = randomLabels,
     68                 batch_size = batchSize,
---> 69                 epochs = 10,
     70               )

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    647             steps_per_epoch=steps_per_epoch,
    648             validation_steps=validation_steps,
--> 649             validation_freq=validation_freq)
    650 
    651     batch_size = self._validate_or_infer_batch_size(

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training_distributed.py in fit_distributed(model, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq)
     82       validation_split=validation_split,
     83       shuffle=shuffle,
---> 84       epochs=epochs)
     85   if not distributed_training_utils.is_distributing_by_cloning(model):
     86     with model._distribution_strategy.scope():

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in _distribution_standardize_user_data(self, x, y, sample_weight, class_weight, batch_size, validation_split, shuffle, epochs, allow_partial_batch)
   2380 
   2381         ds = strategy.extended.experimental_make_numpy_dataset(in_tuple,
-> 2382                                                                session=session)
   2383         if shuffle:
   2384           # We want a buffer size that is larger than the batch size provided by

/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py in experimental_make_numpy_dataset(self, numpy_input, session)
   1431     """
   1432     _require_cross_replica_or_default_context_extended(self)
-> 1433     return self._experimental_make_numpy_dataset(numpy_input, session=session)
   1434 
   1435   def _experimental_make_numpy_dataset(self, numpy_input, session):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/tpu_strategy.py in _experimental_make_numpy_dataset(self, numpy_input, session)
    345     return numpy_dataset.one_host_numpy_dataset(
    346         numpy_input, numpy_dataset.SingleDevice(self._host_device),
--> 347         session)
    348 
    349   def _experimental_distribute_dataset(self, dataset):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/numpy_dataset.py in one_host_numpy_dataset(numpy_input, colocate_with, session)
     86                       for i in numpy_flat)
     87   for v, i in zip(vars_flat, numpy_flat):
---> 88     init_var_from_numpy(v, i, session)
     89   vars_nested = nest.pack_sequence_as(numpy_input, vars_flat)
     90   return dataset_ops.Dataset.from_tensor_slices(vars_nested)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/numpy_dataset.py in init_var_from_numpy(input_var, numpy_input, session)
     70           start_placeholder: start,
     71           end_placeholder: end,
---> 72           slice_placeholder: numpy_input[start:end]})
     73       start = end
     74 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    948     try:
    949       result = self._run(None, fetches, feed_dict, options_ptr,
--> 950                          run_metadata_ptr)
    951       if run_metadata:
    952         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1171     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1172       results = self._do_run(handle, final_targets, final_fetches,
-> 1173                              feed_dict_tensor, options, run_metadata)
   1174     else:
   1175       results = []

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1348     if handle is None:
   1349       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1350                            run_metadata)
   1351     else:
   1352       return self._do_call(_prun_fn, handle, feeds, fetches)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1368           pass
   1369       message = error_interpolation.interpolate(message, self._graph)
-> 1370       raise type(e)(node_def, op, message)
   1371 
   1372   def _extend_graph(self):

AbortedError: Session 290fcb1d6cd9689a is not found.
```
</details>

**Comment by capilano** [comment]
model.fit (at least when used with the above distribution strategy) adds nodes to the graph every time it is called, causing about a 100x slowdown. So, is there a workaround?

**Comment by hadaev8** [comment]
fit_generator is not supported for models compiled with tf.distribute.Strategy.
Any ideas how to get around it?

**Comment by capilano** [comment]
@hadaev8 I got around it by using tf estimators.
 I made a feature request a couple of weeks back,let us see if it gets implemented

**Comment by hadaev8** [comment]
@capilano 
But need callbacks.
I cant pass dataset object, right?
I get assert without error message.

**Comment by capilano** [comment]
@hadaev8 you can pass dataset object. Keras callbacks, doubtful but maybe it's possible (not sure) . Do you need callbacks for early stopping and learning rate schedule or for something else?

**Comment by hadaev8** [comment]
Okay get this error, maybe because I have multi output model

```
resolver = tf.distribute.cluster_resolver.TPUClusterResolver()
tf.config.experimental_connect_to_host(resolver.master())
tf.tpu.experimental.initialize_tpu_system(resolver)
strategy = tf.distribute.experimental.TPUStrategy(resolver)
with strategy.scope():
    model = get_model(le.classes_, 4)
    model.compile(loss='sparse_categorical_crossentropy', optimizer=keras.optimizers.Adam(clipnorm=1.), metrics=['accuracy'])
batch_size=128
h = model.fit(X_train, [y_train[:,0], y_train[:,1], y_train[:,2], y_train[:,3]],
                validation_data=(X_test, [y_test[:,0], y_test[:,1], y_test[:,2], y_test[:,3]]),
                steps_per_epoch=len(y_train)//batch_size-1,
                validation_steps=len(y_test)//batch_size-1,
                verbose=1,
                epochs=100,
                batch_size=batch_size,
                callbacks=[
                    keras.callbacks.TerminateOnNaN(),
                    keras.callbacks.EarlyStopping(patience=5, verbose=1),
                    keras.callbacks.ReduceLROnPlateau(factor=0.9, patience=0, verbose=1, min_lr=1e-6),
                    keras.callbacks.ModelCheckpoint('model', period=0),
                ])
```

```
InternalError                             Traceback (most recent call last)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1355     try:
-> 1356       return fn(*args)
   1357     except errors.OpError as e:

11 frames

InternalError: From /job:worker/replica:0/task:0:
Compilation failure: RET_CHECK failure (third_party/tensorflow/compiler/xla/service/dynamic_parameter_binding.cc:130) dynamic_dimension.dimension < ShapeUtil::GetSubshape( entry->parameter_instruction(dynamic_dimension.parameter_num) ->shape(), dynamic_dimension.parameter_index) .rank() 
	TPU compilation failed
	 [[{{node TPUReplicateMetadata_1}}]]


During handling of the above exception, another exception occurred:

InternalError                             Traceback (most recent call last)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1368           pass
   1369       message = error_interpolation.interpolate(message, self._graph)
-> 1370       raise type(e)(node_def, op, message)
   1371 
   1372   def _extend_graph(self):

InternalError: From /job:worker/replica:0/task:0:
Compilation failure: RET_CHECK failure (third_party/tensorflow/compiler/xla/service/dynamic_parameter_binding.cc:130) dynamic_dimension.dimension < ShapeUtil::GetSubshape( entry->parameter_instruction(dynamic_dimension.parameter_num) ->shape(), dynamic_dimension.parameter_index) .rank() 
	TPU compilation failed
	 [[node TPUReplicateMetadata_1 (defined at <ipython-input-8-7930ebedf468>:20) ]]

Original stack trace for 'TPUReplicateMetadata_1':
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/usr/local/lib/python3.6/dist-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/usr/local/lib/python3.6/dist-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/usr/local/lib/python3.6/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 536, in <lambda>
    self.io_loop.add_callback(lambda : self._handle_events(self.socket, 0))
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2718, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2822, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-7930ebedf468>", line 20, in <module>
    keras.callbacks.ModelCheckpoint('model', period=0),
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 649, in fit
    validation_freq=validation_freq)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training_distributed.py", line 128, in fit_distributed
    validation_freq=validation_freq)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training_distributed.py", line 446, in experimental_tpu_fit_loop
    callbacks=callbacks)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training_distributed.py", line 520, in experimental_tpu_test_loop
    _test_step_fn, args=(test_input_data,))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/tpu_strategy.py", line 249, in experimental_run_v2
    return _tpu_run(self, fn, args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/tpu_strategy.py", line 196, in _tpu_run
    maximum_shapes=maximum_shapes)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/tpu/tpu.py", line 592, in replicate
    maximum_shapes=maximum_shapes)[1]
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/tpu/tpu.py", line 854, in split_compile_and_replicate
    num_replicas=num_replicas, use_tpu=use_tpu, **metadata_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_tpu_ops.py", line 6039, in tpu_replicate_metadata
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()
```

**Comment by capilano** [comment]
@hadaev8 
1. Use tensorflow.keras layers and tensorflow.keras.callbacks,do not use any keras layers directly or functions. Even during the import replace all the keras imports with tensorflow .keras. might need to slightly change your code, because there are some subtle differences between tf.keras and keras , but for most cases they have exact same functionality.
2. You cannot pass a dataset object to fit function. I used tensorflow estimators to train my model as a workaround. as far as I can see , you should be able to train yr model using tensorflow estimators,but I do not know if that's what u are doing 
3. If your dataset fits in RAM I.e if X_train is already available to you,and if you are not doing data augmentation, then you can directly pass the data to model .fit. the problem is you cannot call model.fit in a for loop because that causes a 50x slowdown probably dye to distribute strategy, I created a bug issue 2 weeks ago, and I think it's still not resolved.

**Comment by hadaev8** [comment]
@capilano yes, i have everything from tf.keras. I tested it in 2 cases: with data augmentation and not. Second break on test phase. Sad to see keras and tpu api is broken. And why this issue is closed?

**Comment by capilano** [comment]
@hadaev8 the issue that I opened is still open. https://github.com/tensorflow/tensorflow/issues/30162

**Comment by dibyacharya** [comment]
AttributeError: 'Sequential' object has no attribute 'version'

i have this type of error ...please anyone tell me the solution
