### ISSUE TITLE
Impossible to build with Python3.12

### ISSUE THREAD

**Issue by LucasChollet** [tensorflow/tensorflow#73174]
Using latest Ubuntu (24.04 with Python3.12), the following command fails:
```
bazel build ...
```

With this error:
```
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
```

This is because `rules_python` is outdated.

**Comment by LucasChollet** [comment]
Wait, I clicked on the link in the tflite-micro repository, not sure is it supposed to end up in this repo :thinking:.

**Comment by Venkat6871** [comment]
Hi **@LucasChollet** ,
- Please verify your project on the latest build once your [PR](https://github.com/tensorflow/tflite-micro/pull/2654) is getting merged. Please let us know the response.

Thank you!

**Comment by LucasChollet** [comment]
As mentioned in the PR, it still fails to build later on. But it's now clear why you shouldn't build with Python 3.12.
