### ISSUE TITLE
Some wrong code in get_started document

### ISSUE THREAD

**Issue by FangLinHe** [tensorflow/tensorflow#362]
On your get started website http://www.tensorflow.org/get_started/basic_usage.html#basic-usage
I found a small piece of wrong code:
In the sample code of Feeds section:
```
input1 = tf.placeholder(tf.types.float32)
input2 = tf.placeholder(tf.types.float32)
```
I tried them and python gave the AttributeError: 'module' object has no attribute 'types'
After reading the document http://www.tensorflow.org/resources/dims_types.html
I think it should be `tf.float32` instead of `tf.types.float32`.  Probably it's a version issue?

**Comment by mrry** [comment]
Thanks for pointing this out! We have a fix in the pipeline, and it should appear on the website soon.

**Comment by FangLinHe** [comment]
Thanks for the prompt reply!

**Comment by FangLinHe** [comment]
Again I found very minor wrong number in the tutorial: http://www.tensorflow.org/tutorials/mnist/beginners/index.html#mnist-for-ml-beginners
It mentions the shape of training images are [60000, 784], but actually [55000, 784]; also for the labels: [55000, 10] instead of [60000, 10].

**Comment by Careenn** [comment]
Thanks! it does help!!!!
Now I'm studying the newly tensorflow version based on the windows platform, and some demo codes of the guide TENSORFLOW.ORG gave do have some error, probably this guide is for python version 2.x, but the new tensorflow is based on python version 3.5.x.....

**Comment by mrry** [comment]
@Careenn If you have links to the tutorials that don't work in Python 3.5.x, please send them in a new issue (or sending a pull request that fixes them would be even better!).
