### ISSUE TITLE
saved_model_cli broken on 2.2rc

### ISSUE THREAD

**Issue by marcoadurno** [tensorflow/tensorflow#38042]
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): no
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): all platforms (Linux, Win, MacOS)
- TensorFlow installed from binary
- TensorFlow version == 2.2rc[012]
- Python version: 3.6

Hi,

`saved_model_cli` appears to be broken on all platforms and all versions, except for rc0, linux.

Simply trying to use `saved_model_cli` from the command line yields on all versions and all platforms:
```
Traceback (most recent call last):
  File "C:\Users\marco\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\marco\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\marco\repos\tfutils\venv\Scripts\saved_model_cli.exe\__main__.py", line 5, in <module>
  File "c:\users\marco\repos\tfutils\venv\lib\site-packages\tensorflow\python\tools\saved_model_cli.py", line 51, in <module>
    from tensorflow.python.tools import saved_model_aot_compile
ImportError: cannot import name 'saved_model_aot_compile' from 'tensorflow.python.tools' (c:\users\marco\repos\tfutils\venv\lib\site-packages\tensorflow\python\tools\__init__.py)
```
Linux 2.2rc0 appears to be the only exception:
```
usage: saved_model_cli [-h] [-v] {show,run,scan,convert,aot_compile_cpu} ...
saved_model_cli: error: too few arguments
```

Best Regards,

Marco

**Comment by ravikyram** [comment]
In order to expedite the trouble-shooting process, please provide colab link or minimal standalone code to reproduce the issue reported here. Thanks!

**Comment by marcoadurno** [comment]
Hi @ravikyram,

You can reproduce the issue by simply installing tensorflow and calling `saved_model_cli -h` to print its usage.

Using 2.2rc0 on Linux:
```console
virtualenv ./venv_rc0
source ./venv_rc0/bin/activate
pip3 install tensorflow==2.2rc0
saved_model_cli -h
```
yields:
```
usage: saved_model_cli [-h] [-v] {show,run,scan,convert,aot_compile_cpu} ...

saved_model_cli: Command-line interface for SavedModel

optional arguments:
  -h, --help            show this help message and exit
  -v, --version         show program's version number and exit

commands:
  valid commands

  {show,run,scan,convert,aot_compile_cpu}
                        additional help
```

Using 2.2rc1 or rc2 on any platform, or rc0 on MacOS or Windows:
```console
deactivate
virtualenv ./venv_rc1
source ./venv_rc1/bin/activate
pip3 install tensorflow==2.2rc1
saved_model_cli -h
```
yields:
```
Traceback (most recent call last):
  File "/home/ubuntu/venv_rc1/bin/saved_model_cli", line 5, in <module>
    from tensorflow.python.tools.saved_model_cli import main
  File "/home/ubuntu/venv_rc1/lib/python3.6/site-packages/tensorflow/python/tools/saved_model_cli.py", line 51, in <module>
    from tensorflow.python.tools import saved_model_aot_compile
ImportError: cannot import name 'saved_model_aot_compile'
```

**Comment by goldiegadde** [comment]
@marcoadurno thanks for reporting, we are looking into this, and will address it for the next release candidate.

**Comment by ebrevdo** [comment]
(thanks so much for the clean repro!)

**Comment by hennroja** [comment]
Could someone please verify.

The file `saved_model_aot_compile.py` is missing in my `/Python/3.7/lib/python/site-packages/tensorflow/python/tools/` folder. 

It works after I copied `saved_model_aot_compile.py` from the repo directly to `/tools/saved_model_aot_compile.py`.  Somehow it was not there.

```
➜  ~ python3
Python 3.7.7 (default, Mar 10 2020, 15:43:33) 
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.__version__
'2.2.0-rc2'
```

**Comment by ebrevdo** [comment]
We think this will be solved in rc3.

**Comment by tarrade** [comment]
for me this is now working with 2.2.0-rc3. Thanks
