### ISSUE TITLE
`import tf.compat.v2.summary` broken since 88ca0db75e

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorflow#28027]
The following import should work:

```python
import tensorflow.compat.v2.summary as b
b.scalar
```

This worked fine in d4342f77b6, but broke in 88ca0db75e (first bad):

```
$ cat ./repro.py
import tensorflow as tf
print(tf.__git_version__)
import tensorflow.compat.v2.summary as b
print(b)
print(b.scalar)
```

```
$ virtualenv -q -p python2.7 ./ve-old/
$ . ./ve-old/bin/activate
(ve-old) $ pip install ~/tmp/tf-builds/tf-d4342f77b6/* >/dev/null 2>/dev/null
(ve-old) $ python ./repro.py
v1.12.1-143-gd4342f77b6
<module 'tensorflow.compat.v2.summary' from '/tmp/tmp.kn2U5CUdHI/ve-old/local/lib/python2.7/site-packages/tensorboard/summary/_tf/summary/__init__.pyc'>
<function scalar at 0x7f682249aa28>
(ve-old) $ deactivate
```

```
$ virtualenv -q -p python2.7 ./ve-new/
$ . ./ve-new/bin/activate
(ve-new) $ pip install ~/tmp/tf-builds/tf-88ca0db75e/* >/dev/null 2>/dev/null
(ve-new) $ python ./repro.py
v1.12.1-144-g88ca0db75e
<module 'tensorflow.compat.v2.summary' from '/tmp/tmp.kn2U5CUdHI/ve-new/local/lib/python2.7/site-packages/tensorflow/_api/v1/compat/v2/summary/__init__.pyc'>
Traceback (most recent call last):
  File "./repro.py", line 5, in <module>
    print(b.scalar)
AttributeError: 'module' object has no attribute 'scalar'
(ve-new) $ deactivate
```

Note that the imported module path has changed from [TensorBoard’s
component package entry point][tb] to the stub provided by TensorFlow:

```python
# This file is MACHINE GENERATED! Do not edit.
# Generated by: tensorflow/python/tools/api/generator/create_python_api.py script.
"""Operations for writing summary data, for use in analysis and visualization.

See the [Summaries and
TensorBoard](https://www.tensorflow.org/guide/summaries_and_tensorboard) guide.

"""

from __future__ import print_function as _print_function

from tensorflow._api.v1.compat.v2.summary import experimental
from tensorflow.python.ops.summary_ops_v2 import SummaryWriter
from tensorflow.python.ops.summary_ops_v2 import _flush_fn as flush
from tensorflow.python.ops.summary_ops_v2 import create_file_writer_v2 as create_file_writer
from tensorflow.python.ops.summary_ops_v2 import create_noop_writer
from tensorflow.python.ops.summary_ops_v2 import record_if
from tensorflow.python.ops.summary_ops_v2 import trace_export
from tensorflow.python.ops.summary_ops_v2 import trace_off
from tensorflow.python.ops.summary_ops_v2 import trace_on
from tensorflow.python.ops.summary_ops_v2 import write

del _print_function
```

(Note the absence of any imports of `scalar`, etc.)

[tb]: https://github.com/tensorflow/tensorboard/blob/90a386d1da4d9f477cb60b679f07aa98045d8c7e/tensorboard/summary/_tf/summary/__init__.py

This is blocking TensorBoard’s CI.

**Comment by wchargin** [comment]
cc @annarev @nfelt

**Comment by wchargin** [comment]
Reopening due to rollback in f1f5865307d1b162b937dc2e788eaef21713e22b.

**Comment by mihaimaruseac** [comment]
Can you try again? The rollback has been rolled forward

**Comment by wchargin** [comment]
Yep, fixed on latest nightly. Thanks!
