### PR TITLE
Remove property from seekable method of FileIO

### LINKED ISSUE #27276: Crash when opening .npz file with tf.gfile.GFile on Python 3.7
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary (pip)
- TensorFlow version (use command below): v1.13.0-rc2-5-g6612da8 / 1.13.1
- Python version: Python 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1 / 7.5.0
- GPU model and memory: GTX 1080 / 8G

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
A code below works well on Python 3.6 with TF 1.12. On Python 3.7 with TF 1.13, however, the code crashes. 

**Describe the expected behavior**

Do not crash.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```Python
import numpy as np
import tensorflow as tf

information = { "a": 1, "b": 2 }
np.savez_compressed("a.npz", **information)

with tf.gfile.Open("a.npz", "rb") as file_:
  info = np.load(file_)

info_dict = { key: info[key] for key in info.items() }  # crash on Python 3.7 with TF 1.13.1
```

Traceback 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <dictcomp>
  File "/csehome/youhanmir/.virtualenvs/learning-implicit-action/lib/python3.7/_collections_abc.py", line 744, in __iter__
    yield (key, self._mapping[key])
  File "/csehome/youhanmir/.virtualenvs/learning-implicit-action/lib/python3.7/site-packages/numpy/lib/npyio.py", line 251, in __getitem__
    bytes = self.zip.open(key)
  File "/usr/lib64/python3.7/zipfile.py", line 1480, in open
    self._fpclose, self._lock, lambda: self._writing)
  File "/usr/lib64/python3.7/zipfile.py", line 722, in __init__
    self.seekable = file.seekable
AttributeError: 'GFile' object has no attribute 'seekable'
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

### PR DESCRIPTION
**Pull request by yongtang**
This fix is a follow up to address the issue in #27276 where seekable with property causes the following error with Python 3.7.:
```
  File "/usr/lib/python3.7/_collections_abc.py", line 744, in __iter__
    yield (key, self._mapping[key])
  File "/usr/local/lib/python3.7/dist-packages/numpy/lib/npyio.py", line 251, in __getitem__
    bytes = self.zip.open(key)
  File "/usr/lib/python3.7/zipfile.py", line 1540, in open
    return ZipExtFile(zef_file, mode, zinfo, zd, True)
  File "/usr/lib/python3.7/zipfile.py", line 821, in __init__
    if fileobj.seekable():
TypeError: 'bool' object is not callable
```

This fix removed property annotation of the seekable methods.

This fix also adds a test case, though the test case is only exposed in python 3.7+.

This fix fixes #27276.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Review by dynamicwebpaige — DISMISSED** [review]
LGTM! Thanks as always, @yongtang. 🙂

**Comment by yongtang** [comment]
Thanks @dynamicwebpaige 👍 , the sanity ci test was failing because of the pylint format issue. Have fixed the sanity ci test and updated.

**Review by mihaimaruseac — DISMISSED** [review]

**Comment by yongtang** [comment]
@mihaimaruseac Thanks for the review. There were ci failures related to api compatible. I have updated the api goldens file so tests should all pass now.

**Review by mihaimaruseac — APPROVED** [review]

**Comment by alextp** [comment]
This is not a backwards-compatible change.

I think we need to make this change in 2.0 only. This will require having two classes, a V1 with a property and a V2 with a method, and these should have separate tf_export decorator.

**Comment by alextp** [comment]
Nevermind, let's try to merge this as-is.

**Comment by alextp** [comment]
We took a look and found very few to no usages of this, so it's fine to have a backwards-breaking bugfix.
