### ISSUE TITLE
Saver errors in 0.7.0

### ISSUE THREAD

**Issue by aymericdamien** [tensorflow/tensorflow#1135]
In 0.7, there are different errors about Saver, first Warnings in serialization, such as moving averages, or dictionaries:

```
WARNING:tensorflow:Error encountered when serializing moving_average_variables.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
unbound method to_proto() must be called with Variable instance as first argument (got Tensor instance instead)
WARNING:tensorflow:Error encountered when serializing summary_tags.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'dict' object has no attribute 'name'
```

and then, it throws an OS Error:
```
  File "/Users/aymeric/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 970, in save
    self.export_meta_graph(meta_graph_file_name)
  File "/Users/aymeric/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 990, in export_meta_graph
    as_text=as_text)
  File "/Users/aymeric/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1315, in export_meta_graph
    os.path.basename(filename), as_text=as_text)
  File "/Users/aymeric/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/training_util.py", line 70, in write_graph
    gfile.MakeDirs(logdir)
  File "/Users/aymeric/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/default/_gfile.py", line 295, in MakeDirs
    os.makedirs(path, mode)
  File "/Users/aymeric/anaconda2/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 2] No such file or directory: ''
```

But this is working well in 0.6.0, so Saver might have some issues in 0.7.0

**Comment by mrry** [comment]
Thanks for reporting this bug! You can safely ignore the warnings, which are related to the new `MetaGraphDef` support. If you want to be able to serialize your collections and avoid this warning, you can call the [`tf.register_proto_function()` function](https://github.com/tensorflow/tensorflow/blob/03bff43060229357cbe2cc1659e7d129c2799b06/tensorflow/python/framework/ops.py#L3447) for your collection.

The `OSError` is a bigger problem, and is caused by an incompatibility between our internal and external `tf.gfile.MakeDirs()` functions. As a temporary workaround, prepend "./" to the `save_path` argument when calling `Saver.save()`. I have a change in the pipeline that will fix this error.

**Comment by vrv** [comment]
If someone can validate that the above commit fixes the problem with Saver, that would be appreciated!

**Comment by vrv** [comment]
(I was able to run cifar10_train.py with no problems after the above commit).

**Comment by aymericdamien** [comment]
It is working fine now, thanks!
