### ISSUE TITLE
Code from TF2.4.1 does not work in TF2.5

### ISSUE THREAD

**Issue by benjs** [tensorflow/tensorflow#50438]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): v2.5.0-rc3-213-ga4dfb8d1a71 2.5.0
- Python version: 3.9
- CUDA/cuDNN version: 11.2/8
- GPU model and memory: RTX3070

**Describe the current behavior**
Install tensorflow 2.4 through
```
pip install tensorflow==2.4.1
```

Notice that the following code works: 
```python
import tensorflow.experimental.numpy as tnp

arange = tnp.arange(10, dtype=tnp.float32)
pos_vs = tnp.tile(arange, (4, 10, 1))
pos_us = tnp.transpose(pos_vs, [0, 2, 1])
print(pos_us)
```

Install tensorflow 2.5 through
```
pip install tensorflow==2.5.0
```

The code above fails with the following error:
```
AttributeError: 
        'EagerTensor' object has no attribute 'reshape'.
        If you are looking for numpy-related methods, please run the following:
        import tensorflow.python.ops.numpy_ops.np_config
        np_config.enable_numpy_behavior()
```

**Describe the expected behavior**
The code in TF2.5 should work just fine, as no related breaking change has been introduced.

Gist with link to colab: https://gist.github.com/benjs/6955171d577536fdf0df3528ea673674

**Comment by bhack** [comment]
Have you tried with
```python
import tensorflow.python.ops.numpy_ops.np_config as np_config
np_config.enable_numpy_behavior()
```

**Comment by Saduf2019** [comment]
@benjs 
As reported in the error message to use the "enable numpy behavior" and as bhack has highlighted, the error does not appear, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/7c6f1bc38818e7acb2051b965fadc95e/untitled609.ipynb)

**Comment by benjs** [comment]
Wether the bug can be fixed or not, the behavior of the framework should not differ as [no breaking change has been introduced](https://github.com/tensorflow/tensorflow/releases/tag/v2.5.0).

Also, the error message should be adjusted to recommend using [tensorflow.experimental.numpy.experimental_enable_numpy_behavior](https://www.tensorflow.org/api_docs/python/tf/experimental/numpy/experimental_enable_numpy_behavior) which is the same function and can be found in the docs already.

I can submit a PR on that if you like.

**Comment by bhack** [comment]
>tensorflow.experimental.numpy.experimental_enable_numpy_behavior only exists in tf-nightly.

https://www.tensorflow.org/guide/tf_numpy?hl=en

**Comment by benjs** [comment]
This part of the documentation is outdated too.

Please test this yourself:
```
pip install tensorflow
```
```python
import tensorflow as tf
import tensorflow.experimental.numpy as tnp

print(tf.__version__)

tnp.experimental_enable_numpy_behavior()

arange = tnp.arange(3, dtype=tnp.float32)
pos_vs = tnp.tile(arange, (2, 3, 1))
pos_us = tnp.transpose(pos_vs, [0, 2, 1])

print("No error raised until here!")
``` 
```
2.5.0
No error raised until here!
```

**Comment by bhack** [comment]
Ok, so you can submit a PR.
