### ISSUE TITLE
TensorFlow Lite CMake build is broken (label_image & benchmark_model) on TF 2.7

### ISSUE THREAD

**Issue by robert-kalmar** [tensorflow/tensorflow#53083]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Yocto Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.7.0
- Python version: N/A
- Installed using virtualenv? pip? conda?: No
- Bazel version (if compiling from source): N/A
- CMake version: 3.19.5
- GCC/Compiler version (if compiling from source): 10.2.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**
The TensorFlow Lite build using CMake is broken in v2.7.0 for generic Arm device (aarch64). 
The problem is caused by this commit https://github.com/tensorflow/tensorflow/commit/feb49693266f444d5d8ce1a439ffbe7ff6e15e8a . First problem is only the bazel build scripts were updated (the CMake does not support the Hexagon delegate yet at all). Secondly the implementation expects the Qualcomm's Hexagon DSP is available on every aarch64 platform, what is not generally true.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1. Configure the project via CMake: 
```
cmake -DCMAKE_TOOLCHAIN_FILE=${OE_CMAKE_TOOLCHAIN_FILE} ../tensorflow/lite/
```
2. Build the label_image or benchmark_model application: 
```
make -j6 label_image
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
```
[100%] Linking CXX executable label_image
/opt/sdk/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/10.2.0/real-ld: CMakeFiles/label_image.dir/__/__/tools/evaluation/utils.cc.o: in function `tflite::evaluation::CreateHexagonDelegate(TfLiteHexagonDelegateOptions const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::{lambda(TfLiteDelegate*)#1}::_FUN(TfLiteDelegate*)':
/home/robo/tensorflow/tensorflow/lite/tools/evaluation/utils.cc:165: undefined reference to `TfLiteHexagonDelegateDelete'
/opt/sdk/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/10.2.0/real-ld: CMakeFiles/label_image.dir/__/__/tools/evaluation/utils.cc.o: in function `operator()':
/home/robo/tensorflow/tensorflow/lite/tools/evaluation/utils.cc:166: undefined reference to `TfLiteHexagonTearDown'
/opt/sdk/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/10.2.0/real-ld: CMakeFiles/label_image.dir/__/__/tools/evaluation/utils.cc.o: in function `tflite::evaluation::CreateHexagonDelegate(TfLiteHexagonDelegateOptions const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/robo/tensorflow/tensorflow/lite/tools/evaluation/utils.cc:154: undefined reference to `TfLiteHexagonInit'
/opt/sdk/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/10.2.0/real-ld: /home/robo/tensorflow/tensorflow/lite/tools/evaluation/utils.cc:159: undefined reference to `TfLiteHexagonDelegateCreate'
/opt/sdk/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/10.2.0/real-ld: /home/robo/tensorflow/tensorflow/lite/tools/evaluation/utils.cc:156: undefined reference to `TfLiteHexagonInitWithPath'
/opt/sdk/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/10.2.0/real-ld: /home/robo/tensorflow/tensorflow/lite/tools/evaluation/utils.cc:159: undefined reference to `TfLiteHexagonDelegateCreate'
/opt/sdk/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/10.2.0/real-ld: /home/robo/tensorflow/tensorflow/lite/tools/evaluation/utils.cc:161: undefined reference to `TfLiteHexagonTearDown'
/opt/sdk/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/10.2.0/real-ld: /home/robo/tensorflow/tensorflow/lite/tools/evaluation/utils.cc:154: undefined reference to `TfLiteHexagonInit'
/opt/sdk/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/10.2.0/real-ld: /home/robo/tensorflow/tensorflow/lite/tools/evaluation/utils.cc:159: undefined reference to `TfLiteHexagonDelegateCreate'
/opt/sdk/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/10.2.0/real-ld: /home/robo/tensorflow/tensorflow/lite/tools/evaluation/utils.cc:156: undefined reference to `TfLiteHexagonInitWithPath'
/opt/sdk/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/10.2.0/real-ld: /home/robo/tensorflow/tensorflow/lite/tools/evaluation/utils.cc:159: undefined reference to `TfLiteHexagonDelegateCreate'
/opt/sdk/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/10.2.0/real-ld: /home/robo/tensorflow/tensorflow/lite/tools/evaluation/utils.cc:161: undefined reference to `TfLiteHexagonTearDown'
collect2: error: ld returned 1 exit status
examples/label_image/CMakeFiles/label_image.dir/build.make:331: recipe for target 'examples/label_image/label_image' failed
make[3]: *** [examples/label_image/label_image] Error 1
CMakeFiles/Makefile2:4330: recipe for target 'examples/label_image/CMakeFiles/label_image.dir/all' failed
make[2]: *** [examples/label_image/CMakeFiles/label_image.dir/all] Error 2
CMakeFiles/Makefile2:4337: recipe for target 'examples/label_image/CMakeFiles/label_image.dir/rule' failed
make[1]: *** [examples/label_image/CMakeFiles/label_image.dir/rule] Error 2
Makefile:1414: recipe for target 'label_image' failed
make: *** [label_image] Error 2
```

**Comment by karimnosseir** [comment]
Can you please retry from master branch. A fix was pushed.

Thanks

**Comment by karimnosseir** [comment]
Closing, please reopen if issue still happen.

Thanks

**Comment by mihaimaruseac** [comment]
Do we need a cherrypick on 2.7 to fix the build there, @karimnosseir ?

**Comment by karimnosseir** [comment]
@mihaimaruseac Yes, i will send cherrypicks now.

Thanks
