### ISSUE TITLE
Header tensorflow/stream_executor/stream.h not included with tf-nightly pip package

### ISSUE THREAD

**Issue by EnricoMi** [tensorflow/tensorflow#57494]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

binary

### Tensorflow Version

2.11.0.dev20220828

### Custom Code

Yes

### Python version

3.8

### Current Behaviour?

Horovod does not build with tf-nightly anymore, see https://github.com/horovod/horovod/runs/8047013531?check_suite_focus=true#step:10:9615

The code includes tensorflow/stream_executor/stream.h at https://github.com/horovod/horovod/blob/master/horovod/tensorflow/mpi_ops.cc#L65. Header files in tensorflow/core are included with the pip package. That stream.h is part of Tensorflow sources, but is not included in the nightly pip package.

This is similar to #57083, but a different file this time.

### Standalone code to reproduce the issue

```shell
#include "tensorflow/stream_executor/stream.h"
```

### Relevant log output

```shell
/tmp/pip-req-build-5xc4jhus/horovod/tensorflow/mpi_ops.cc:65:10: fatal error: tensorflow/stream_executor/stream.h: No such file or directory
   65 | #include "tensorflow/stream_executor/stream.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
</details>

**Comment by EnricoMi** [comment]
Looks like this has been caused by #57083.

Is `tensorflow/stream_executor/stream.h` meant to be replaced by `tensorflow/compiler/xla/stream_executor/stream.h`?

**Comment by EnricoMi** [comment]
@joker-eph

**Comment by joker-eph** [comment]
I'm not sure how #57083 could cause this: it didn't touch stream executor and TSL does not relate either.

b71fca418dd6b485ed54d4190cac51996c5590c3 moved stream executor code to XLA, but I'm surprised by your error since we left a forwarding header behind: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/stream_executor/stream.h

@rdzhabarov would know maybe?

**Comment by EnricoMi** [comment]
Sorry, I pasted the wrong link. It was caused by 2be83013. It removes `list(find_files('*.h', 'tensorflow/stream_executor')) +` from `tensorflow/tools/pip_package/setup.py`:
https://github.com/tensorflow/tensorflow/commit/2be830137aca09da21d599e04ba7d7ad0059ed05#diff-f526feeafa1000c4773410bdc5417c4022cb2c7b686ae658b629beb541ae9112

**Comment by joker-eph** [comment]
I think I found the issue, let's check if it actually works this time!

**Comment by EnricoMi** [comment]
The `stream.h` is still not in `20220903` (`tf_nightly_gpu-2.11.0.dev20220903-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl`). Was it cut before your fix went into git?

**Comment by EnricoMi** [comment]
It looks like your change in `tensorflow/BUILD` (702e7a4f)
```
"//tensorflow/stream_executor:stream_executor_headers",
```
should read
```
"//tensorflow/stream_executor:stream",
```
See https://github.com/tensorflow/tensorflow/commit/2be830137aca09da21d599e04ba7d7ad0059ed05#diff-679555fdef7c81321743c804a27240b29642a6a04170df06427f14ddf3cdea4eL681

**Comment by joker-eph** [comment]
Still not right apparently...

**Comment by joker-eph** [comment]
At this point I'll need to build the pip package myself and iterate to figure it out, I'll try to get to it later this week. If you have other ideas of diff to try, please suggest :)

**Comment by EnricoMi** [comment]
Nope, that would be my best approach to iterate as well. Can you re-open this issue please for the time being?

Thanks for looking into this.

**Comment by EnricoMi** [comment]
Did you try adding `tensorflow/c/BUILD:681` back in?

```
"//tensorflow/stream_executor:stream",
```

Or is this equivalent to `tensorflow/BUILD:1351`?

```
"//tensorflow/stream_executor:stream_executor_headers",
```

**Comment by joker-eph** [comment]
I didn't, but why would it affect the exported headers? Do you think there is a `transitive_hdrs` collection rule that would be impacted by this?

**Comment by joker-eph** [comment]
Actually they gave me an idea, let me try to add ` "//tensorflow/stream_executor:stream_executor",` here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/pip_package/BUILD#L26

**Comment by joker-eph** [comment]
OK I figured it out, patch coming...

**Comment by joker-eph** [comment]
(Note that I don't think that these headers won't be kept around forever, we will likely clean this up and remove them in the future.)

**Comment by EnricoMi** [comment]
What is the recommended approach to migrate away from those headers?

**Comment by joker-eph** [comment]
It's probably best to wait for the migration to complete, but they will ultimately look like #include "stream_executor/stream_executor.h" I think.

**Comment by rdzhabarov** [comment]
We are about to remove tensorflow/stream_executor completely.
Everything has been moved to the tensorflow/compiler/xla/stream_executor.

Could you include headers from the new location?

**Comment by joker-eph** [comment]
> Could you include headers from the new location?

I don't think that is a good idea: this isn't the final location.

**Comment by EnricoMi** [comment]
As of `20220910`, this is still not fixed.

**Comment by EnricoMi** [comment]
@joker-eph can we re-open this, please? Or shall simply use the new location for the time being until the final location is settled?

**Comment by EnricoMi** [comment]
I will move to the current location and move again once this is moved to the final location.
