### ISSUE TITLE
[TF 2.2] TFLite Android ARM64 benchmark tool fails when compiling XNNPACK

### ISSUE THREAD

**Issue by lgeiger** [tensorflow/tensorflow#37724]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.15.3
- TensorFlow installed from (source or binary): source
- TensorFlow version: v2.2.0-rc1 and master
- Python version: 3.7.7
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source): Apple clang version 11.0.0

**Describe the problem**

Compiling the TFLite benchmarking tool for Android ARM64 following the steps described [here](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark#to-buildinstallrun) fails due to NEON float16 errors in XNNPACK with the error message posted below. This happens for both v2.2.0-rc1 and current master, but worked correctly on 2.1.0.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
bazel build -c opt \
  --config=android_arm64 \
  tensorflow/lite/tools/benchmark:benchmark_model
```
However `--config=android_arm` compiles without issues.

**Any other info / logs**
```
ERROR: /private/var/tmp/_bazel_lukasgeiger/b38acd93c344ce8dbb5b0de713e0e337/external/XNNPACK/BUILD.bazel:1687:1: C++ compilation of rule '@XNNPACK//:neonfp16arith_ukernels' failed (Exit 1)
external/XNNPACK/src/f16-gemm/gen/4x8-neonfp16arith-ld64.c:76:26: error: assigning to 'float16x8_t' (vector of 8 'float16_t' values) from incompatible type 'int'
          vacc0x01234567 = vfmaq_lane_f16(vacc0x01234567, vb01234567c0, va0, 0);
                         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/XNNPACK/src/f16-gemm/gen/4x8-neonfp16arith-ld64.c:77:26: error: assigning to 'float16x8_t' (vector of 8 'float16_t' values) from incompatible type 'int'
          vacc1x01234567 = vfmaq_lane_f16(vacc1x01234567, vb01234567c0, va1, 0);
                         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/XNNPACK/src/f16-gemm/gen/4x8-neonfp16arith-ld64.c:78:26: error: assigning to 'float16x8_t' (vector of 8 'float16_t' values) from incompatible type 'int'
          vacc2x01234567 = vfmaq_lane_f16(vacc2x01234567, vb01234567c0, va2, 0);
                         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/XNNPACK/src/f16-gemm/gen/4x8-neonfp16arith-ld64.c:79:26: error: assigning to 'float16x8_t' (vector of 8 'float16_t' values) from incompatible type 'int'
          vacc3x01234567 = vfmaq_lane_f16(vacc3x01234567, vb01234567c0, va3, 0);
                         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/XNNPACK/src/f16-gemm/gen/4x8-neonfp16arith-ld64.c:94:26: error: assigning to 'float16x8_t' (vector of 8 'float16_t' values) from incompatible type 'int'
          vacc0x01234567 = vfmaq_lane_f16(vacc0x01234567, vb01234567c1, va0, 1);
                         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/XNNPACK/src/f16-gemm/gen/4x8-neonfp16arith-ld64.c:95:26: error: assigning to 'float16x8_t' (vector of 8 'float16_t' values) from incompatible type 'int'
          vacc1x01234567 = vfmaq_lane_f16(vacc1x01234567, vb01234567c1, va1, 1);
                         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/XNNPACK/src/f16-gemm/gen/4x8-neonfp16arith-ld64.c:96:26: error: assigning to 'float16x8_t' (vector of 8 'float16_t' values) from incompatible type 'int'
          vacc2x01234567 = vfmaq_lane_f16(vacc2x01234567, vb01234567c1, va2, 1);
                         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/XNNPACK/src/f16-gemm/gen/4x8-neonfp16arith-ld64.c:97:26: error: assigning to 'float16x8_t' (vector of 8 'float16_t' values) from incompatible type 'int'
          vacc3x01234567 = vfmaq_lane_f16(vacc3x01234567, vb01234567c1, va3, 1);
                         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/XNNPACK/src/f16-gemm/gen/4x8-neonfp16arith-ld64.c:112:26: error: assigning to 'float16x8_t' (vector of 8 'float16_t' values) from incompatible type 'int'
          vacc0x01234567 = vfmaq_lane_f16(vacc0x01234567, vb01234567c2, va0, 2);
                         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/XNNPACK/src/f16-gemm/gen/4x8-neonfp16arith-ld64.c:113:26: error: assigning to 'float16x8_t' (vector of 8 'float16_t' values) from incompatible type 'int'
          vacc1x01234567 = vfmaq_lane_f16(vacc1x01234567, vb01234567c2, va1, 2);
                         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/XNNPACK/src/f16-gemm/gen/4x8-neonfp16arith-ld64.c:114:26: error: assigning to 'float16x8_t' (vector of 8 'float16_t' values) from incompatible type 'int'
          vacc2x01234567 = vfmaq_lane_f16(vacc2x01234567, vb01234567c2, va2, 2);
                         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/XNNPACK/src/f16-gemm/gen/4x8-neonfp16arith-ld64.c:115:26: error: assigning to 'float16x8_t' (vector of 8 'float16_t' values) from incompatible type 'int'
          vacc3x01234567 = vfmaq_lane_f16(vacc3x01234567, vb01234567c2, va3, 2);
                         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/XNNPACK/src/f16-gemm/gen/4x8-neonfp16arith-ld64.c:130:26: error: assigning to 'float16x8_t' (vector of 8 'float16_t' values) from incompatible type 'int'
          vacc0x01234567 = vfmaq_lane_f16(vacc0x01234567, vb01234567c3, va0, 3);
                         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/XNNPACK/src/f16-gemm/gen/4x8-neonfp16arith-ld64.c:131:26: error: assigning to 'float16x8_t' (vector of 8 'float16_t' values) from incompatible type 'int'
          vacc1x01234567 = vfmaq_lane_f16(vacc1x01234567, vb01234567c3, va1, 3);
                         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/XNNPACK/src/f16-gemm/gen/4x8-neonfp16arith-ld64.c:132:26: error: assigning to 'float16x8_t' (vector of 8 'float16_t' values) from incompatible type 'int'
          vacc2x01234567 = vfmaq_lane_f16(vacc2x01234567, vb01234567c3, va2, 3);
                         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/XNNPACK/src/f16-gemm/gen/4x8-neonfp16arith-ld64.c:133:26: error: assigning to 'float16x8_t' (vector of 8 'float16_t' values) from incompatible type 'int'
          vacc3x01234567 = vfmaq_lane_f16(vacc3x01234567, vb01234567c3, va3, 3);
                         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/XNNPACK/src/f16-gemm/gen/4x8-neonfp16arith-ld64.c:157:24: error: assigning to 'float16x8_t' (vector of 8 'float16_t' values) from incompatible type 'int'
        vacc0x01234567 = vfmaq_f16(vacc0x01234567, va0, vb01234567);
                       ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/XNNPACK/src/f16-gemm/gen/4x8-neonfp16arith-ld64.c:158:24: error: assigning to 'float16x8_t' (vector of 8 'float16_t' values) from incompatible type 'int'
        vacc1x01234567 = vfmaq_f16(vacc1x01234567, va1, vb01234567);
                       ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/XNNPACK/src/f16-gemm/gen/4x8-neonfp16arith-ld64.c:159:24: error: assigning to 'float16x8_t' (vector of 8 'float16_t' values) from incompatible type 'int'
        vacc2x01234567 = vfmaq_f16(vacc2x01234567, va2, vb01234567);
                       ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
Target //tensorflow/lite/tools/benchmark:benchmark_model failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 473.607s, Critical Path: 33.08s
INFO: 1229 processes: 1229 local.
FAILED: Build did NOT complete successfully
```

**Comment by lgeiger** [comment]
I was able to compile the model benchmark by upgrading Android NDK to `18.1.5063045`. It would be good if the minimal supported version would be documented somewhere.

**Comment by kvkenyon** [comment]
This worked thanks.

**Comment by dostos** [comment]
Thanks!

**Comment by shervinemami** [comment]
I had this exact same problem, and upgrading to NDK v18 also fixed it for me, thanks Igeiger!
