### ISSUE TITLE
InvalidArgumentError Assign requires shapes of both tensors to match. lhs shape= [5] rhs shape= [1001]

### ISSUE THREAD

**Issue by tranvanhoa533** [tensorflow/tensorflow#7838]
Caused by op u'save/Assign', defined at:
  File "train_image_classifier.py", line 585, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "train_image_classifier.py", line 575, in main
    init_fn=_get_init_fn(),
  File "train_image_classifier.py", line 370, in _get_init_fn
    ignore_missing_vars=FLAGS.ignore_missing_vars)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/framework/python/ops/variables.py", line 579, in assign_from_checkpoint_fn
    saver = tf_saver.Saver(var_list, reshape=reshape_variables)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 986, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1015, in build
    restore_sequentially=self._restore_sequentially)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 620, in build
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 369, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 212, in restore
    self.op.get_shape().is_fully_defined())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 45, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 749, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2380, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1298, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [5] rhs shape= [1001]
         [[Node: save/Assign = Assign[T=DT_FLOAT, _class=["loc:@InceptionV4/AuxLogits/Aux_logits/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/
cpu:0"](InceptionV4/AuxLogits/Aux_logits/biases, save/restore_slice)]]

This error was caused when i pre-train fine-tuning inception-v4. I'm opening this issue.Can you help me?
 Thank you so much !

**Comment by poxvoculi** [comment]
Make sure you're using the current version of tensorflow and any example programs.  If you suspect a bug, please provide the information requested in the issue template.

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by tranvanhoa533** [comment]
Thanks for your response. I tried on version r0.11 and r0.12 . Both raised this error. I suspect checkpoint. Similarly, this error was also raised when i tried to pre-train with inception-v3, vgg-19 model. I see the instruction on model slim page about this error, but i don't know the reason why the differential between the value of lhs shape in my error and in the instruction.
https://github.com/tensorflow/models/tree/master/slim#the-resnet-and-vgg-models-have-1000-classes-but-the-imagenet-dataset-has-1001

**Comment by poxvoculi** [comment]
The current version of TensorFlow is 1.0.  I don't know whether those checkpoints are compatible with older versions.  Have you tried the examples exactly as written?

**Comment by tranvanhoa533** [comment]
I have tried on version 1.0. But i faced another error:

Traceback (most recent call last):
  File "train_image_classifier.py", line 585, in <module>
    tf.app.run()
  File "/home/cloud/.local/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_image_classifier.py", line 448, in main
    image = image_preprocessing_fn(image, train_image_size, train_image_size)
  File "/home/cloud/hoa/workspace/models/slim/preprocessing/preprocessing_factory.py", line 70, in preprocessing_fn
    image, output_height, output_width, is_training=is_training, **kwargs)
  File "/home/cloud/hoa/workspace/models/slim/preprocessing/inception_preprocessing.py", line 302, in preprocess_image
    return preprocess_for_train(image, height, width, bbox, fast_mode)
  File "/home/cloud/hoa/workspace/models/slim/preprocessing/inception_preprocessing.py", line 195, in preprocess_for_train
    tf.image_summary('image_with_bounding_boxes', image_with_box)
AttributeError: module 'tensorflow' has no attribute 'image_summary'

**Comment by prb12** [comment]
Please see this page which gives advice and tools for upgrading your model code to the new TF1.0 API: https://www.tensorflow.org/install/migration

Since the error above is unrelated to the original issue, I'm going to close this thread.  Please open a separate issue if the issue persists after migrating to 1.0.

**Comment by zorancupic** [comment]
I set the `num_classes` in the inception_v3 model to 1001 and now it can restore the variables from the appropriate checkpoint. There seems to be a bug...

**Comment by Praneeth134191t** [comment]
In my case it can be resolved by adding this code before load the model.
 tf.reset_default_graph()

**Comment by FanRockRock** [comment]
11
