### ISSUE TITLE
Compilation failure on OS/X w/ XLA

### ISSUE THREAD

**Issue by DavidNorman** [tensorflow/tensorflow#7920]
OS/X compilation fails with XLA.

Error is:
```
RROR: /Users/davidn/github/tensorflow/tensorflow/compiler/xla/service/BUILD:108:1: C++ compilation of rule '//tensorflow/compiler/xla/service:versioned_computation_handle' failed: cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 93 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
In file included from tensorflow/compiler/xla/service/versioned_computation_handle.cc:16:
./tensorflow/compiler/xla/service/versioned_computation_handle.h:33:19: error: unknown type name 'int64'; did you mean 'tensorflow::int64'?
  using Version = int64;
                  ^~~~~
                  tensorflow::int64
./tensorflow/core/platform/default/integral_types.h:27:19: note: 'tensorflow::int64' declared here
typedef long long int64;
                  ^
In file included from tensorflow/compiler/xla/service/versioned_computation_handle.cc:16:
./tensorflow/compiler/xla/service/versioned_computation_handle.h:38:3: error: unknown type name 'string'; did you mean 'std::string'?
  string ToString() const;
  ^~~~~~
  std::string
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iosfwd:194:65: note: 'std::string' declared here
typedef basic_string<char, char_traits<char>, allocator<char> > string;
                                                                ^
tensorflow/compiler/xla/service/versioned_computation_handle.cc:22:1: error: unknown type name 'string'; did you mean 'std::string'?
string VersionedComputationHandle::ToString() const {
^~~~~~
std::string
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iosfwd:194:65: note: 'std::string' declared here
typedef basic_string<char, char_traits<char>, allocator<char> > string;
                                                                ^
```

issue was probably introduced in 7817ac8055ca328e5bf902677f335502eb0da926.

It is trivial to fix.

**Comment by hawkinsp** [comment]
A fix for this issue has been checked into our internal tree; the issue should be resolved shortly when those changes are pulled to Github.

**Comment by DavidNorman** [comment]
thanks.

**Comment by DavidNorman** [comment]
Hi.  Do you guys think that the fix is in the public repo already?   I notice that the last commit for that file is 'fix opensource build breakage....'.  

however, that fix wasn't the one that is breaking the OS/X build.  The files need proper namespaces on the std:: things, and a namespace on the int64

```
diff --git a/tensorflow/compiler/xla/service/versioned_computation_handle.cc b/tensorflow/compiler/xla/service/versioned_computation_handle.cc
index a693c46..188c4fc 100644
--- a/tensorflow/compiler/xla/service/versioned_computation_handle.cc
+++ b/tensorflow/compiler/xla/service/versioned_computation_handle.cc
@@ -19,7 +19,7 @@ limitations under the License.
 
 namespace xla {
 
-string VersionedComputationHandle::ToString() const {
+std::string VersionedComputationHandle::ToString() const {
   return tensorflow::strings::StrCat(handle.handle(), ":v", version);
 }
 
diff --git a/tensorflow/compiler/xla/service/versioned_computation_handle.h b/tensorflow/compiler/xla/service/versioned_computation_handle.h
index ecedc92..190168e 100644
--- a/tensorflow/compiler/xla/service/versioned_computation_handle.h
+++ b/tensorflow/compiler/xla/service/versioned_computation_handle.h
@@ -30,12 +30,12 @@ struct VersionedComputationHandle {
   // A version value unambiguously specifying the state of the computation at a
   // particular point in time as it is being built. This value is the
   // ComputationDataHandle of the current root instruction.
-  using Version = int64;
+  using Version = tensorflow::int64;
 
   ComputationHandle handle;
   Version version;
 
-  string ToString() const;
+  std::string ToString() const;
   bool operator==(const VersionedComputationHandle& other) const {
     return (handle.handle() == other.handle.handle()) &&
```

**Comment by hawkinsp** [comment]
That change should have fixed it. Does it still actually fail to build?

Note the fix was to `#include "tensorflow/compiler/xla/types.h"`, which defines `xla::int64` and `xla::string`. No namespace qualification should be needed now that header is included.

**Comment by DavidNorman** [comment]
i see.  that is strange.  i will update our repo again and see what happens....

cheers

**Comment by DavidNorman** [comment]
its all ok now.  indeed - we did not have the fix in our central repo.
