### ISSUE TITLE
`TensorContractionThreadPool.h' file not found` when using `--copt=-march=native`

### ISSUE THREAD

**Issue by zafartahirov** [tensorflow/tensorflow#6558]
When trying to run 

```
$ ./configure
........
$ bazel build --copt=-march=native -c opt //tensorflow/tools/pip_package:build_pip_package --verbose_failures
```

it fails with the `./third_party/eigen3/unsupported/Eigen/CXX11/FixedPoint:42:10: fatal error: 'src/Tensor/TensorContractionThreadPool.h' file not found` error.

Similar problem was seen in #4680, #580, 

I am on Mac OS X Sierra 10.12.2 with no CUDA and cuDNN installed. I am using virtual environment on Python 2.7

Here is the checked commit and `bazel` version
```
$ git rev-parse HEAD
ac28ae043df4bc6f112f964f6df22845b8a05390
$ bazel version
Build label: 0.4.3-homebrew
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 22 15:20:15 2016 (1482420015)
Build timestamp: 1482420015
Build timestamp as int: 1482420015
```

This works fine:
```
$ git checkout remotes/origin/r0.12
$ ./configure # With defaults
.........
$ bazel build --copt=-march=native -c opt //tensorflow/tools/pip_package:build_pip_package --verbose_failures
# This finishes correctly
```

Here is the full terminal log when `bazel` is run on the `master` branch:
```
$ git checkout master
$ ./configure # With defaults
.........
$ bazel build --copt=-march=native -c opt //tensorflow/tools/pip_package:build_pip_package --verbose_failures
INFO: Found 1 target...
ERROR: /Users/zafar/GitHub/tensorflow/tensorflow/core/kernels/BUILD:856:1: C++ compilation of rule '//tensorflow/core/kernels:gather_functor' failed: cc_wrapper.sh failed: error executing command
  (cd /private/var/tmp/_bazel_zafar/c40dcca6773e4515fd11c724e0ebae51/execroot/tensorflow && \
  exec env - \
    PATH=/Users/zafar/.virtualenvs/tf-dev-env/bin:/Users/zafar/.rbenv/shims:/Users/zafar/.node/bin:/Users/zafar/bin:/Users/zafar/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/Library/TeX/texbin \
    TMPDIR=/var/folders/yx/nf9nvmpn4_79r7nbzkn8cz8h0000gn/T/ \
  external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-march=native' '-std=c++0x' -MD -MF bazel-out/local-opt/bin/tensorflow/core/kernels/_objs/gather_functor/tensorflow/core/kernels/gather_functor.pic.d '-frandom-seed=bazel-out/local-opt/bin/tensorflow/core/kernels/_objs/gather_functor/tensorflow/core/kernels/gather_functor.pic.o' -fPIC -DEIGEN_MPL2_ONLY -iquote . -iquote bazel-out/local-opt/genfiles -iquote external/bazel_tools -iquote bazel-out/local-opt/genfiles/external/bazel_tools -iquote external/eigen_archive -iquote bazel-out/local-opt/genfiles/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/local-opt/genfiles/external/local_config_sycl -isystem external/bazel_tools/tools/cpp/gcc3 -isystem external/eigen_archive -isystem bazel-out/local-opt/genfiles/external/eigen_archive -DEIGEN_AVOID_STL_ARRAY -Iexternal/gemmlowp -Wno-sign-compare -fno-exceptions -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c tensorflow/core/kernels/gather_functor.cc -o bazel-out/local-opt/bin/tensorflow/core/kernels/_objs/gather_functor/tensorflow/core/kernels/gather_functor.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
In file included from tensorflow/core/kernels/gather_functor.cc:50:
In file included from ./tensorflow/core/kernels/gather_functor.h:22:
In file included from ./tensorflow/core/framework/type_traits.h:22:
In file included from ./tensorflow/core/framework/numeric_types.h:25:
./third_party/eigen3/unsupported/Eigen/CXX11/FixedPoint:42:10: fatal error: 'src/Tensor/TensorContractionThreadPool.h' file not found
#include "src/Tensor/TensorContractionThreadPool.h"
         ^
1 error generated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 34.692s, Critical Path: 25.26s
```

**Comment by zafartahirov** [comment]
I can attach the `pip freeze` of my virtual environment if required, but I think this is an issue with `Eigen` not being downloaded

**Comment by chenmx00** [comment]
2016-12-29 16:04 GMT+08:00 Zafar Takhirov <notifications@github.com>:

**Comment by fnl** [comment]
If it helps, I've "resolved" the issue for me by tinkering around a bit and adding the missing header:

1. Add [`TensorContractionThreadPool.h`](https://bitbucket.org/eigen/eigen/raw/9ba936354ee8b73fb1966dcb2d3506387bb357f1/unsupported/Eigen/CXX11/src/Tensor/TensorContractionThreadPool.h) from [Eigen](https://bitbucket.org/eigen/eigen) "itself" to TF's `third_party/eigen3/unsupported/Eigen/CXX11/src/Tensor` directory (note that the leaf directory `Tensor` has to be created first).
1. Update the `hdrs` parameter of the cc_library function in the Bazel `third_party/eigen3/BUILD` file to include the newly added file by inserting the following line in the list of files there: `"unsupported/Eigen/CXX11/src/Tensor/TensorContractionThreadPool.h",`

After that, my TF builds with AVX2 optimizations again pass and I can nicely use TF (so far, at least...).

But I have exactly zero idea if that's indeed the right fix... YMMV ;-)

**Comment by zafartahirov** [comment]
@fnl I can get it to work by using the `r0.12` branch, so there is no need for tinkering and manually placing the files. Also, `r0.12` has no major differences with the `master` (ac28ae043df4bc6f112f964f6df22845b8a05390). The reason I opened an issue is because it might affect the future releases, and we need to find what caused it.

**Comment by StanislawAntol** [comment]
I have had the same issue (except with --copt=-mavx2 instead of --copt=-march=native).

It seems that removing the two include lines, #include "src/Tensor/TensorContractionThreadPool.h", in [FixedPoint](https://github.com/tensorflow/tensorflow/blob/master/third_party/eigen3/unsupported/Eigen/CXX11/FixedPoint) from this commit (https://github.com/benoitsteiner/tensorflow/commit/8c943af3b139f07aa1f3ba5c976e2f0765e75960) allows bazel to compile, but when I try to use it after installation it fails:

```
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "/home/s.antol/cv/tf/tensorflow/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
ImportError: cannot import name 'pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/s.antol/cv/tf/tensorflow/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/s.antol/cv/tf/tensorflow/tensorflow/python/__init__.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/s.antol/cv/tf/tensorflow/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
ImportError: cannot import name 'pywrap_tensorflow'


Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.
```

Perhaps someone more familiar with the build system would know how to properly remedy this.

**Comment by zafartahirov** [comment]
@StanislawAntol I don't think your error is related -- you are running TF from the same directory where you cloned the repo. Try going to any other directory, the error will be different

**Comment by yaroslavvb** [comment]
So I'm running into same problem when trying to compile with avx/avx2. The following works on "tags/0.12.0-rc1" tag, but doesn't work on today's head. @benoitsteiner -- something in the last 2 weeks broke avx/avx2 compilation, what do you think about @fnl's solution in https://github.com/tensorflow/tensorflow/issues/6558#issuecomment-269643996 ?

```
export flags="-c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both --config=cuda"
bazel build $flags //tensorflow/tools/pip_package:build_pip_package

...
compilation terminated.
ERROR: /local_home/yaroslav/tensorflow_avx2.git/tensorflow/tensorflow/core/kernels/BUILD:582:1: Couldn't build file tensorflow/core/kernels/_objs/mirror_pad_op/tensorflow/core/kernels/mirror_pad_op_cpu_impl_1.pic.o: C++ compilation of rule '//tensorflow/core/kernels:mirror_pad_op' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter ... (remaining 126 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
In file included from ./tensorflow/core/framework/numeric_types.h:25:0,
                 from ./tensorflow/core/framework/register_types.h:20,
                 from ./tensorflow/core/kernels/mirror_pad_op_cpu_impl.h:21,
                 from tensorflow/core/kernels/mirror_pad_op_cpu_impl_1.cc:17:
./third_party/eigen3/unsupported/Eigen/CXX11/FixedPoint:42:52: fatal error: src/Tensor/TensorContractionThreadPool.h: No such file or directory
 #include "src/Tensor/TensorContractionThreadPool.h"
```

**Comment by AndersonJo** [comment]
I have same problem.. when installing Tensorflow from source on Python3.6

```
bazel build --copt=-march=native  -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
```


```
ERROR: /home/anderson/Downloads/tensorflow/tensorflow/core/kernels/BUILD:300:1: C++ compilation of rule '//tensorflow/core/kernels:reader_base' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter ... (remaining 115 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
In file included from ./tensorflow/core/framework/numeric_types.h:25:0,
                 from ./tensorflow/core/framework/allocator.h:23,
                 from ./tensorflow/core/framework/op_kernel.h:22,
                 from ./tensorflow/core/framework/queue_interface.h:22,
                 from ./tensorflow/core/kernels/reader_base.h:21,
                 from tensorflow/core/kernels/reader_base.cc:16:
./third_party/eigen3/unsupported/Eigen/CXX11/FixedPoint:42:52: fatal error: src/Tensor/TensorContractionThreadPool.h: No such file or directory
compilation terminated.
```

**Comment by costad2** [comment]
Same issue, I was able to work around it following @fnl directions in the post above, I do not know enough about the build system used here to know if this is the "correct" way of fixing it.

**Comment by inflation** [comment]
Same here, back to 0.12.1 would work well.

**Comment by gunan** [comment]
Does #6759 Fix this issue?
Are we OK to close this?

**Comment by zafartahirov** [comment]
It looks like it is working for `bazel build --copt=-march=native -c opt //tensorflow/tools/pip_package:build_pip_package --verbose_failures`

The compilation is still going, but it was throwing the error almost immediately before

**Comment by StanislawAntol** [comment]
I was also able to compile the most recent version of master with the following:
`bazel build -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both --config=cuda //tensorflow/tools/pip_package:build_pip_package`

Also, I find it odd that the [nightly build](https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-cpu-mavx/) doesn't seem to be working. I would think it's using similar commands.

**Comment by gunan** [comment]
Nightlies are able to build, but they are having test failures.
We are investigating them, but occasional test failures in nightlies are expected.
@zafartahirov Once (if)your build succeeds, could you close this issue.
If it does not, please share the new failures so we can continue debugging.

**Comment by zafartahirov** [comment]
Complete (with warnings about `-pthread`). Closing
