### PR TITLE
Make keras model load compatible with old version of models

### LINKED ISSUE #38135: Keras Model Errors on Loading - 'list' object has no attribute 'items' with TF 2.1
**System information**

Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ProductName:	Mac OS X, ProductVersion:	10.15.2, BuildVersion:	19C57
TensorFlow installed from (source or binary): pip
TensorFlow version (use command below): 2.1.0
Python version: 3.6.8
CUDA/cuDNN version: None
GPU model and memory: None

**Describe the current behavior**

When trying to load one of my models using tf.keras.models.load_model an error is thrown at the following location:

```
tensorflow_core\python\keras\utils\generic_utils.py", line 254, in class_and_config_for_serialized_keras_object
for key, item in cls_config.items():
**AttributeError: 'list' object has no attribute 'items'**
```
This code expects cls_config to be a dictionary, while for this model it is a list of dictionaries.

I can successfully load and run this model using TensorFlow versions 2.0.0, 1.15.0 and 1.14.0.

This section of code was introduced when adding support for passive serialization in Keras

**Describe the expected behavior**

Can successfully load a model from a hdf5 file.

**Code to reproduce the issue:**

```
import tensorflow as tf

model = tf.keras.models.load_model('cnn_multichannel_dense_f0_b0.h5', compile=False)
```

**Other info / logs:**

**_I am also attaching a dummy hdf5 model below which can be used to test._**

Complete Stacktrace of the error:

```
  File "/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "lib/python3.6/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 168, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "lib/python3.6/site-packages/tensorflow_core/python/keras/saving/model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "lib/python3.6/site-packages/tensorflow_core/python/keras/layers/serialization.py", line 106, in deserialize
    printable_module_name='layer')
  File "lib/python3.6/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 292, in deserialize_keras_object
    config, module_objects, custom_objects, printable_module_name)
  File "lib/python3.6/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 254, in class_and_config_for_serialized_keras_object
    for key, item in cls_config.items():
AttributeError: 'list' object has no attribute 'items'

```

When loaded with tf.keras in v2.0.0 the layers, model config, inputs, outputs, summary etc. are all parsed correctly, as well as being able to run data through the model.

### PR DESCRIPTION
**Pull request by feihugis**
This PR makes `tf.keras.models.load_model(...)` compatible with the old versions of keras models (e.g. `tf-1.2.1`). More details about this issue can be found [here](https://github.com/tensorflow/tensorflow/issues/38135). Note that `tf-2.0` supports the models generated by `tf-1.2.1` but [recent changes](https://github.com/tensorflow/tensorflow/commit/c71c58beb262152d4b486eb92ff29b917584c201#diff-ca2f2579ed6d04b0be9c2bacfa1a4d38L224) in `tf-2.1` break it.

Fix #38135

### CODE REVIEW

**Comment by tanzhenyu** [comment]
Not sure if this is desired. Can't you just update your config?

**Comment by feihugis** [comment]
> Not sure if this is desired. Can't you just update your config?

Thanks for review, @tanzhenyu! 

We can update our model to work with `tf-2.1`. However, I think it will save time for users if Keras API in `tf-2.x` can keep compatible with the old models generated by `tf-1.x`. Otherwise, there may be some other users who met similar issues with ours. 

Note that `tf-2.0` can load the above model file but [some recent changes](https://github.com/tensorflow/tensorflow/commit/c71c58beb262152d4b486eb92ff29b917584c201#diff-ca2f2579ed6d04b0be9c2bacfa1a4d38L224) in `tf-2.1` break it. I'm not sure if it is on purpose, or maybe forgot some edge cases.

**Comment by tanzhenyu** [comment]
> > Not sure if this is desired. Can't you just update your config?
> 
> Thanks for review, @tanzhenyu!
> 
> We can update our model to work with `tf-2.1`. However, I think it will save time for users if Keras API in `tf-2.x` can keep compatible with the old models generated by `tf-1.x`. Otherwise, there may be some other users who met similar issues with ours.
> 
> Note that `tf-2.0` can load the above model file but [some recent changes](https://github.com/tensorflow/tensorflow/commit/c71c58beb262152d4b486eb92ff29b917584c201#diff-ca2f2579ed6d04b0be9c2bacfa1a4d38L224) in `tf-2.1` break it. I'm not sure if it is on purpose, or maybe forgot some edge cases.

Can you be more specific on 1) what was the original config, 2) what error message does it provide, 3) what are alternative solutions towards this? And also a unit test would be desired as well.

**Comment by feihugis** [comment]
@tanzhenyu  The following code can be used to reproduce the issue:

- Step 1: use `tf-1.2.1` to create an old model:
```
def create_model_tf12(model_file):
  from tensorflow.contrib.keras.python.keras.models import Sequential
  from tensorflow.contrib.keras.python.keras.layers import Dense, Embedding
  model = Sequential()
  model.add(Embedding(1000, 64, input_length=10))
  model.save(model_file)
```
- Step 2: use `tf-nightly` to load the model:
```
def load_mode_tf_nightly(model_file):
  model = tf.keras.models.load_model(model_file)
```

> Can you be more specific on 1) what was the original config, 

The original config from `tf-1.2.1` is below:
```
{
  'class_name': 'Sequential', 
  'config': [
    {
      'class_name': 'Embedding', 
      'config': {
        'name': 'embedding_1', 
        'trainable': True, 
        'batch_input_shape': [None, 10], 
        'dtype': 'int32', 
        'input_dim': 1000, 
        'output_dim': 64, 
        'embeddings_initializer': {'class_name': 'RandomUniform', 'config': {'minval': 0, 'maxval': None, 'seed': None, 'dtype': 'float32'}}, 
        'embeddings_regularizer': None, 
        'activity_regularizer': None, 
        'embeddings_constraint': None, 
        'mask_zero': False, 
        'input_length': 10
      }
    }
  ]
}
```

The original config from `tf-nightly` using the python code is below:
```
{
  'class_name': 'Sequential', 
  'config': {
    'name': 'sequential', 
    'layers': [
       {
         'class_name': 'InputLayer', 
         'config': {
           'batch_input_shape': [None, 10], 
           'dtype': 'float32', 
           'sparse': False, 
           'ragged': False, 
           'name': 'embedding_input'}
       },
       {
         'class_name': 'Embedding', 
         'config': {
           'name': 'embedding', 
           'trainable': True, 
           'batch_input_shape': [None, 10], 
           'dtype': 'float32', 
           'input_dim': 1000, 
           'output_dim': 64, 
           'embeddings_initializer': {'class_name': 'RandomUniform', 'config': {'minval': -0.05, 'maxval': 0.05, 'seed': None}}, 
           'embeddings_regularizer': None, 
           'activity_regularizer': None, 
           'embeddings_constraint': None, 
           'mask_zero': False, 
           'input_length': 10}
       }
    ]
  }
}
```

> 2) what error message does it provide, 

The error message is 
```
Traceback (most recent call last):
  File "/home/feihu/miniconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/feihu/miniconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/feihu/.vscode-server/extensions/ms-python.python-2020.3.71659/pythonFiles/lib/python/debugpy/no_wheels/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/feihu/.vscode-server/extensions/ms-python.python-2020.3.71659/pythonFiles/lib/python/debugpy/no_wheels/debugpy/../debugpy/server/cli.py", line 429, in main
    run()
  File "/home/feihu/.vscode-server/extensions/ms-python.python-2020.3.71659/pythonFiles/lib/python/debugpy/no_wheels/debugpy/../debugpy/server/cli.py", line 266, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "/home/feihu/miniconda3/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/feihu/miniconda3/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/feihu/miniconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "tf_explore/keras_load_model.py", line 46, in <module>
    load_mode_tf21(SEQ_MODEL_TF12_FILE)
  File "tf_explore/keras_load_model.py", line 30, in load_mode_tf21
    model = tf.keras.models.load_model(model_file)
  File "/home/feihu/py-virtualenv/tf-nightly/lib/python3.6/site-packages/tensorflow/python/keras/saving/save.py", line 184, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/feihu/py-virtualenv/tf-nightly/lib/python3.6/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 170, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "/home/feihu/py-virtualenv/tf-nightly/lib/python3.6/site-packages/tensorflow/python/keras/saving/model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/feihu/py-virtualenv/tf-nightly/lib/python3.6/site-packages/tensorflow/python/keras/layers/serialization.py", line 173, in deserialize
    printable_module_name='layer')
  File "/home/feihu/py-virtualenv/tf-nightly/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 340, in deserialize_keras_object
    config, module_objects, custom_objects, printable_module_name)
  File "/home/feihu/py-virtualenv/tf-nightly/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 302, in class_and_config_for_serialized_keras_object
    for key, item in cls_config.items():
AttributeError: 'list' object has no attribute 'items'
```

> 3) what are alternative solutions towards this? 

Do you mean if there are any other solution to fix this issue?

> And also a unit test would be desired as well.
Will add a unit test soon.

**Comment by feihugis** [comment]
@tanzhenyu The unit test is added here(https://github.com/tensorflow/tensorflow/pull/38339/commits/49b07e664590f73942bcbaf1c378e59ccab9f04b). Could you please take a look when you have time?

**Comment by feihugis** [comment]
@tanzhenyu kindly remind that the comments have been addressed here (https://github.com/tensorflow/tensorflow/commit/49b07e664590f73942bcbaf1c378e59ccab9f04b). Could you take a look when you get a chance? Hope this PR can be merged before the official release of `TF-2.2`.

**Comment by feihugis** [comment]
@k-w-w Could you please take a look at this PR when you get a chance?

**Review by k-w-w — APPROVED** [review]
Sorry for the late review. Thanks for adding this much needed fix!
