### ISSUE TITLE
Android inference AAR build failure from source code

### ISSUE THREAD

**Issue by guoyinchen** [tensorflow/tensorflow#29344]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04 LTS
- TensorFlow installed from (source or binary): source
- TensorFlow version: master branch with commit e1c98eeb
- Python version: 2.7
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): clang 3.8 from android-ndk-r19c
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the problem**
Android aar build with android-ndk-r19c clang 3.8 will have below build error:
    tensorflow/core/kernels/bias_op.cc:278:13: error: default initialization of an object of const type 'const functor::ReduceMiddleDimensions<float, AccumT,  Eigen::internal::scalar_sum_op<AccumT>, Eigen::internal::SumReducer<float> >'   (aka 'const ReduceMiddleDimensions<float, float, scalar_sum_op<float>,  SumReducer<float> >') without a user-provided default constructor
                redux;
                            ^
    tensorflow/core/kernels/quantized_resize_bilinear_op.cc:52:16: error: default initialization of an object of const type 'const tensorflow::LegacyScaler' without a user-provided default constructor
      const Scaler scaler;
                     ^

**Provide the exact sequence of commands / steps that you executed before running into the problem**
    Build cmds:
    $bazel build --cxxopt='--std=c++11' -c opt --config=android_arm64 \
       --config=monolithic //tensorflow/lite/java:tensorflow-lite-with-select-tf-ops

**Comment by guoyinchen** [comment]
Please review below patch to fix this build issue.
https://github.com/tensorflow/tensorflow/commit/241fe0df4eefaf69d4b349a2502515face810805

**Comment by freedomtan** [comment]
FYR, with android ndk r19c, I can run `bazel build --cxxopt='--std=c++11' -c opt --config=android_arm64 
--config=monolithic //tensorflow/lite/java:tensorflow-lite-with-select-tf-ops` without problem. BTW, the clang in ndk-r19 should be clang 8.0.2.

**Comment by gadagashwini** [comment]
@guoyinchen Can we close this, since the associated PR has been merged. Thanks!
