### ISSUE TITLE
AttributeError: 'module' object has no attribute 'KerasLayer' on Colab script when downloaded to local, non-cuda laptop

### ISSUE THREAD

**Issue by serv-inc** [tensorflow/tensorflow#27538]
The Colab for https://www.tensorflow.org/tutorials/images/hub_with_keras fails to run when downloaded to a local machine.
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): ('v1.13.1-0-g6612da8951', '1.13.1')
- Python version: 2.7.15rc1
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: n.a.
- GPU model and memory:  Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2) 
32 GB max as of https://www.intel.com/content/www/us/en/support/products/88355/graphics-drivers/graphics-for-6th-generation-intel-processors/intel-hd-graphics-520.html

**Describe the current behavior**
Fails at line
```
    hub.KerasLayer(classifier_url, input_shape=IMAGE_SHAPE+(3,))
```
with

> AttributeError: 'module' object has no attribute 'KerasLayer'

**Describe the expected behavior**
Script runs to completion

**Code to reproduce the issue**
1. Open in Browser: https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/images/hub_with_keras.ipynb
2. export as .py file (File -> Download .py)
3. remove pip commands from file, run tf-hub install by hand, avoid tf-gpu-nightly as no CUDA gpu available
```pip install tensorflow tensorflow-hub```
4. execute script: ```python hub_with_keras.py ```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

> $ python hub_with_keras.py 
> WARNING: Logging before flag parsing goes to stderr.
> W0405 12:54:22.202450 140138733332288 __init__.py:56] Some hub symbols are not available because TensorFlow version is less than 1.14
> Traceback (most recent call last):
>   File "hub_with_keras.py", line 28, in <module>
>     hub.KerasLayer(classifier_url, input_shape=IMAGE_SHAPE+(3,))
> AttributeError: 'module' object has no attribute 'KerasLayer'

When upgrading to 2.0.0a (1.14 seems to be unavailable on pip) the script fails with another error, see #27539.

[tf_env.txt](https://github.com/tensorflow/tensorflow/files/3047549/tf_env.txt)

**Comment by serv-inc** [comment]
As @arnoegw [wrote on stackoverflow](https://stackoverflow.com/questions/55682557/valueerror-input-0-of-layer-dense-is-incompatible-with-the-layer-its-rank-is-u?noredirect=1#comment98130637_55682557), this is fixed in `tf-nightly-2.0-preview`.
