### ISSUE TITLE
Compile TFLite wheel file for Raspberry Pi 4. (Tensorflow operators problem)

### ISSUE THREAD

**Issue by CodeMonkey3435** [tensorflow/tensorflow#51657]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Raspbian(Buster) (64 bit version)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Raspberry Pi 4 (1GB RAM, but 2GB Swap memory I think)
- TensorFlow installed from (source or binary): trying to install
- TensorFlow version: 2.5.0, also TFLite 2..5.0
- Python version: 3.7.3
- Installed using virtualenv? pip? conda?: virtualenv, pip3
- Bazel version (if compiling from source): Build label: 4.2.0
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
- CUDA/cuDNN version: 11.2/8.1 on ubuntu 20.04
- GPU model and memory: GTX 1070 8GB

So I started with a well working model on my computer and wanted to transfer it to the Raspberry Pi. My plan is to use TFLite on the RPI with verson 2.5.0(tflite), as the regular Tensorfow is also running on 2.5.0. My first instinct was to install the wheel file that was downloadable from the tensorflow website. (Here https://github.com/google-coral/pycoral/releases/)
I used this:  tflite_runtime-2.5.0.post1-cp37-cp37m-linux_aarch64.whl
It installed fine with pip3 in my venv.

Sadly, I get the following error:

>     interpreter.invoke()
>   File "/home/pi/.local/lib/python3.7/site-packages/tflite_runtime/interpreter.py", line 833, in invoke
>     self._interpreter.Invoke()
> RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.Node number 275 (FlexCropAndResize) failed to prepare.

I understand, that I am using tensorflow operators that are not included in the tflite library. This is unfortunate but I believe there is one other option: To build the wheel file myself.

I found a readme file deep down in tensorflow, located here: tensorflow/tensorflow/lite/tools/pip_package/README.md

I used this part:

> ### Cross build with Flex for armhf Python 3.7
> 
> ```sh
> CI_DOCKER_EXTRA_PARAMS="-e CUSTOM_BAZEL_FLAGS=--define=tflite_pip_with_flex=true" \
>   tensorflow/tools/ci_build/ci_build.sh PI-PYTHON37 \
>   tensorflow/lite/tools/pip_package/build_pip_package_with_bazel.sh armhf
> ```

All I changed was, "armhf" to "aarch64" because of 64 bit OS and I added a flag "--jobs=2" to keep my computer from freezing up during the process.

The process ended with exit 0, so I thought everything should be fine, but then I get this error message when running the same script as with the first error message:

> Traceback (most recent call last):
>   File "tfliteTest.py", line 2, in <module>
>     import tflite_runtime.interpreter as tflite
>   File "/home/pi/.local/lib/python3.7/site-packages/tflite_runtime/interpreter.py", line 42, in <module>
>     from tflite_runtime import metrics_portable as metrics
> ImportError: cannot import name 'metrics_portable' from 'tflite_runtime' (/home/pi/.local/lib/python3.7/site-packages/tflite_runtime/__init__.py)

Please help me, and thank you already for reading this. Also reply if you have another way around this problem, even if I have to take another route.

**Comment by abattery** [comment]
@terryheo could you take a look?

**Comment by CodeMonkey3435** [comment]
Okay, so I have made some progress this morning, but it still does not look very good. I focused on the last error message of my previous post, with the file metrics_portable. I searched through the tensorflow lite directory from github and simply found the missing files (metrics_interface.py and metrics_portable.py) and moved them to the installed tflite_runtime. This stopped the import error.
Nevertheless I am back to the select ops problem. Take a look at this again:

> Traceback (most recent call last):
>   File "tfliteTest.py", line 55, in <module>
>     interpreter.invoke()
>   File "/home/pi/.local/lib/python3.7/site-packages/tflite_runtime/interpreter.py", line 833, in invoke
>     self._interpreter.Invoke()
> RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.Node number 275 (FlexCropAndResize) failed to prepare.

Something to note: I looked at the interpreter.py file and thought this might be important.

```
    """Loads delegate from the shared library.

    Args:
      library: Shared library name.
      options: Dictionary of options that are required to load the delegate. All
        keys and values in the dictionary should be serializable. Consult the
        documentation of the specific delegate for required and legal options.
        (default None)

    Raises:
      RuntimeError: This is raised if the Python implementation is not CPython.
    """
```

I am uncertain what to do now. Hope this shows the problem well.

**Comment by mohantym** [comment]
Hi! @CodeMonkey3435 ,
Could you please try on latest stable version of tf 2.6 or nightly and let us know if this is still an issue. you can also look at the [comment](https://github.com/tensorflow/tensorflow/issues/40157#issuecomment-831019737) of similar issue Thanks!

**Comment by CodeMonkey3435** [comment]
Yes, so I downloaded the version 2.6.0 of tensorflow and rerun this command:

> sudo CI_DOCKER_EXTRA_PARAMS="-e CUSTOM_BAZEL_FLAGS=--define=tflite_pip_with_flex=true--local_ram_resources=2048"   tensorflow/tools/ci_build/ci_build.sh PI-PYTHON37 tensorflow/lite/tools/pip_package/build_pip_package_with_bazel.sh aarch64

When running this with the same old script I still get the same error message:

> Traceback (most recent call last):
>   File "tfliteTest.py", line 59, in <module>
>     interpreter.invoke()
>   File "/home/pi/.local/lib/python3.7/site-packages/tflite_runtime/interpreter.py", line 875, in invoke
>     self._interpreter.Invoke()
> RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.Node number 275 (FlexCropAndResize) failed to prepare.

Also the issue you linked @mohantym does not seem to be a solution because only some of the people chat about the issue being removed in 2020, and the topic has been closed on 5.june.2020. Its about a year later now and there still have been a couple of issues left, like for me. There still seems to be a lot of confusion. 
I do not know how to get a nightly version.

**Comment by mohantym** [comment]
`pip install tf-nightly `, will upgrade to nightly version .

**Comment by CodeMonkey3435** [comment]
Okay, I do not think I could download tf-nightly like this because I was executing the commands to build the wheel file from the tensorflow folder. 
Anyway, I found a way for this to work.

Special thanks to **@PINTO0309** !!!

He managed to find a way to compile wheel files for multiple versions of the raspberry pi and its ditributions. He also provides pre-built wheel files, that actually work. Additionally, he has a little guide for everyone who wants to compile the files themselves.

The **wheel files** are **select ops** enabled for **RASPBERRY PI 3/4**(Many variations)

Link to his repo: **https://github.com/PINTO0309/TensorflowLite-bin**

Also thank you @mohantym and @abattery for replying so quickly.
