### ISSUE TITLE
tf.logging does not exist in tf 2.0, yet is used in example

### ISSUE THREAD

**Issue by serv-inc** [tensorflow/tensorflow#26662]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version: 2.0.0-alpha0
- Doc Link: 
https://github.com/tensorflow/examples/blob/master/courses/udacity_intro_to_tensorflow_for_deep_learning/l02c01_celsius_to_fahrenheit.ipynb
and 
https://classroom.udacity.com/courses/ud187/lessons/e0c70c77-5584-4f83-a47b-a67a6172ae75/concepts/fe91023e-9699-418a-8f4e-58c6acad1169

**Describe the documentation issue**
If you try to execute this code in a python REPL, it fails at

    tf.logging.set_verbosity(tf.logging.ERROR)

with 

    AttributeError: 'module' object has no attribute 'logging'

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

Depends on how you want it. As of https://www.tensorflow.org/versions/r2.0/api_docs/python/tf, it seems the logging API does not exist. Of the methods in https://stackoverflow.com/questions/35911252/disable-tensorflow-debugging-information, only 

    os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' 

worked.

**Comment by jvishnuvardhan** [comment]
@serv-inc Those examples are not related to TF2.0. Those examples user Tensorflow master.
In the example, import tensorflow as tf was used. For 2.0 we need to use, tensorflow==2.0.0-alpha0. Thanks!

**Comment by serv-inc** [comment]
@jvishnuvardhan : thank you for the explanation. This is a course about Tensorflow 2.0. I had only installed the 2.0 version on my system, which is why `import tensorflow as tf` used 2.0. Anyways, it seems to be a non-issue if this is simply not supposed to work in 2.0.

**Comment by jvishnuvardhan** [comment]
I am closing this issue as tf.logging is not there in TF2.0. Thanks!

**Comment by MarkDaoust** [comment]
I fixed this in all the examples I could find:

```
import logging
logger = tf.get_logger()
logger.setLevel(logging.ERROR)
```

**Comment by AfsanaReem** [comment]
If I remove that lines this happens:

"F:\Program Files\Python\Python37\python.exe" F:/PycharmProjects/Sign-Language-master/fun_util.py
2020-04-19 20:44:42.593982: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-04-19 20:44:42.594177: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Using TensorFlow backend.
Traceback (most recent call last):
  File "F:\Program Files\Python\Python37\lib\site-packages\pyttsx3\__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "F:\Program Files\Python\Python37\lib\weakref.py", line 137, in __getitem__
    o = self.data[key]()
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:/PycharmProjects/Sign-Language-master/fun_util.py", line 11, in <module>
    engine = pyttsx3.init()
  File "F:\Program Files\Python\Python37\lib\site-packages\pyttsx3\__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "F:\Program Files\Python\Python37\lib\site-packages\pyttsx3\engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "F:\Program Files\Python\Python37\lib\site-packages\pyttsx3\driver.py", line 50, in __init__
    self._module = importlib.import_module(name)
  File "F:\Program Files\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\Program Files\Python\Python37\lib\site-packages\pyttsx3\drivers\sapi5.py", line 10, in <module>
    import pythoncom
ModuleNotFoundError: No module named 'pythoncom'

Process finished with exit code 1

**Comment by amitport** [comment]
@MarkDaoust is this documented somewhere?
