### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'PluginAssets'

### ISSUE THREAD

**Issue by sjtusmartboy** [tensorflow/tensorflow#50921]
tensorflow 2.5

**This problem occurs when I'm using the tensorboard to do the profiling.**

The code is as follows.

```
import tensorflow as tf
import datetime

# The function to be traced.
@tf.function
def my_func(x, y):
  # A simple hand-rolled layer.
  return tf.nn.relu(tf.matmul(x, y))

# Set up logging.
stamp = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
logdir = 'logs/func/%s' % stamp
writer = tf.summary.create_file_writer(logdir)

# Sample data for your function.
x = tf.random.uniform((3, 3))
y = tf.random.uniform((3, 3))

# Bracket the function call with
# tf.summary.trace_on() and tf.summary.trace_export().
tf.summary.trace_on(graph=True, profiler=True)
# Call only one tf.function when tracing.
z = my_func(x, y)
with writer.as_default():
  tf.summary.trace_export(
      name="my_func_trace",
      step=0,
      profiler_outdir=logdir)
```

**It produces no error when running this code, seeing from the output.**

sjtusmartboy@sjtusmartboy-ThinkPad-X230:~/opt/Projects/RandLA-Net$ python test3.py 
```
2021-07-23 19:41:34.589229: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-07-23 19:41:36.138644: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2021-07-23 19:41:36.170275: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-23 19:41:36.171081: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:03:00.0 name: NVIDIA GeForce GTX 1080 computeCapability: 6.1
coreClock: 1.835GHz coreCount: 20 deviceMemorySize: 7.93GiB deviceMemoryBandwidth: 298.32GiB/s
2021-07-23 19:41:36.171145: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-07-23 19:41:36.176195: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2021-07-23 19:41:36.176262: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11
2021-07-23 19:41:36.178526: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcufft.so.10
2021-07-23 19:41:36.178833: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcurand.so.10
2021-07-23 19:41:36.179436: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusolver.so.11
2021-07-23 19:41:36.180522: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusparse.so.11
2021-07-23 19:41:36.180748: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudnn.so.8
2021-07-23 19:41:36.180909: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-23 19:41:36.181553: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-23 19:41:36.182112: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2021-07-23 19:41:36.183934: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-23 19:41:36.184486: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:03:00.0 name: NVIDIA GeForce GTX 1080 computeCapability: 6.1
coreClock: 1.835GHz coreCount: 20 deviceMemorySize: 7.93GiB deviceMemoryBandwidth: 298.32GiB/s
2021-07-23 19:41:36.184588: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-23 19:41:36.185197: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-23 19:41:36.185693: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2021-07-23 19:41:36.185742: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-07-23 19:41:36.773690: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-07-23 19:41:36.773748: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0 
2021-07-23 19:41:36.773763: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N 
2021-07-23 19:41:36.773975: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-23 19:41:36.774569: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-23 19:41:36.775196: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-23 19:41:36.775721: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6857 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce GTX 1080, pci bus id: 0000:03:00.0, compute capability: 6.1)
WARNING:tensorflow:From /home/sjtusmartboy/.local/lib/python3.6/site-packages/tensorflow/python/ops/summary_ops_v2.py:1263: start (from tensorflow.python.eager.profiler) is deprecated and will be removed after 2020-07-01.
Instructions for updating:
use `tf.profiler.experimental.start` instead.
2021-07-23 19:41:36.884168: I tensorflow/core/profiler/lib/profiler_session.cc:126] Profiler session initializing.
2021-07-23 19:41:36.884221: I tensorflow/core/profiler/lib/profiler_session.cc:141] Profiler session started.
2021-07-23 19:41:36.884273: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1611] Profiler found 1 GPUs
2021-07-23 19:41:36.885256: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcupti.so.11.2
2021-07-23 19:41:37.125954: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2021-07-23 19:41:37.126748: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2793545000 Hz
2021-07-23 19:41:37.141797: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2021-07-23 19:41:37.573205: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11
WARNING:tensorflow:From /home/sjtusmartboy/.local/lib/python3.6/site-packages/tensorflow/python/ops/summary_ops_v2.py:1319: stop (from tensorflow.python.eager.profiler) is deprecated and will be removed after 2020-07-01.
Instructions for updating:
use `tf.profiler.experimental.stop` instead.
2021-07-23 19:41:37.576615: I tensorflow/core/profiler/lib/profiler_session.cc:66] Profiler session collecting data.
2021-07-23 19:41:37.576966: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1743] CUPTI activity buffer flushed
2021-07-23 19:41:37.607794: I tensorflow/core/profiler/internal/gpu/cupti_collector.cc:673]  GpuTracer has collected 11 callback api events and 145 activity events. 
2021-07-23 19:41:37.608909: I tensorflow/core/profiler/lib/profiler_session.cc:159] Profiler session tear down.
WARNING:tensorflow:From /home/sjtusmartboy/.local/lib/python3.6/site-packages/tensorflow/python/ops/summary_ops_v2.py:1319: save (from tensorflow.python.eager.profiler) is deprecated and will be removed after 2020-07-01.
Instructions for updating:
`tf.python.eager.profiler` has deprecated, use `tf.profiler` instead.
WARNING:tensorflow:From /home/sjtusmartboy/.local/lib/python3.6/site-packages/tensorflow/python/eager/profiler.py:151: maybe_create_event_file (from tensorflow.python.eager.profiler) is deprecated and will be removed after 2020-07-01.
Instructions for updating:
`tf.python.eager.profiler` has deprecated, use `tf.profiler` instead.
```

**However, when I type the tensorboard command, `tensorboard --logdir logs/func`, and open the tensorboard webpage, it gives out the following error.**

```
2021-07-23 19:42:10.506328: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0

NOTE: Using experimental fast data loading logic. To disable, pass
    "--load_fast=false" and report issues on GitHub. More details:
    https://github.com/tensorflow/tensorboard/issues/4784

Serving TensorBoard on localhost; to expose to the network, use a proxy or pass --bind_all
TensorBoard 2.5.0 at http://localhost:6006/ (Press CTRL+C to quit)
Exception in thread DynamicProfilePluginIsActiveThread:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sjtusmartboy/.local/lib/python3.6/site-packages/tensorboard_plugin_profile/profile_plugin.py", line 311, in compute_is_active
    self._is_active = any(self.generate_run_to_tools())
  File "/home/sjtusmartboy/.local/lib/python3.6/site-packages/tensorboard_plugin_profile/profile_plugin.py", line 693, in generate_run_to_tools
    plugin_assets = self.multiplexer.PluginAssets(PLUGIN_NAME)
AttributeError: 'NoneType' object has no attribute 'PluginAssets'


```

**Comment by sjtusmartboy** [comment]
Please tell me what's wrong and what I can do to manage this problem so that I can do the profiling work with tensorflow 2.5. Thanks a million.

**Comment by one-two-one-two** [comment]
I am having a similar problem. A keras model is trained with a callback
`tensorboard_callback = TensorBoard(log_dir='logs/{}'.format(log_dir_name))`.
When i run tensorboard and activate the "Profile" menu item, i am getting the error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/FP/interq/ITP/.itp/lib/python3.6/site-packages/tensorboard_plugin_profile/profile_plugin.py", line 311, in compute_is_active
    self._is_active = any(self.generate_run_to_tools())
  File "/home/FP/interq/ITP/.itp/lib/python3.6/site-packages/tensorboard_plugin_profile/profile_plugin.py", line 693, in generate_run_to_tools
    plugin_assets = self.multiplexer.PluginAssets(PLUGIN_NAME)
AttributeError: 'NoneType' object has no attribute 'PluginAssets'
```


tensorboard==2.5.0
tensorboard-data-server==0.6.1
tensorboard-plugin-profile==2.4.0
tensorboard-plugin-wit==1.8.0
tensorflow==2.5.0
tensorflow-estimator==2.5.0

**Comment by sjtusmartboy** [comment]
@rmothukuru Any progress yet?

**Comment by rmothukuru** [comment]
@japie1235813,
This issue has been assigned to the respective Engineer. We will revert soon. Thanks!

**Comment by bmd3k** [comment]
@sjtusmartboy, thanks for the report. @one-two-one-two, thanks for the helpful additional details.

In my case I have no problems with tensorflow==2.5.0, tensorboard==2.5.0 and tensorboard-plugin-profile==2.5.0.

However, if I downgrade to tensorboard-plugin-profile==2.4.0, then I can reproduce the error you are seeing.

It does not surprise me that tensorboard-plugin-profile==2.4.0 is incompatible with newer versions of tensorboard since we have made some changes to plugin management this year.

Could you try upgrading to tensorboard-plugin-profile==2.5.0 and let me know if the problem is resolved?

**Comment by one-two-one-two** [comment]
Yes, problem solved.
thanks a lot

**Comment by sjtusmartboy** [comment]
Yes, problem solved.
thanks a lot
