### ISSUE TITLE
Tensorflow go installation fail (cannot find import)

### ISSUE THREAD

**Issue by nyeinsoe26** [tensorflow/tensorflow#42657]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version: 3.8
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 3.1
- GCC/Compiler version (if compiling from source):9.3
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
I have installed C , following the instructions from https://www.tensorflow.org/install/lang_c and when i ran:                       go get github.com/tensorflow/tensorflow/tensorflow/go
I get the following error:
../github.com/tensorflow/tensorflow/tensorflow/go/saved_model.go:25:2: cannot find package "github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto" in any of:
                     /usr/local/go/src/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto (from $GOROOT)
	            /home/nyein/go/src/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto (from $GOPATH)

I tried following this fix here at https://github.com/tensorflow/tensorflow/issues/14546#issuecomment-347433966 and I checkout from r1.11 and I am getting this error now:
/usr/bin/ld: $WORK/b032/_x007.o: in function `_cgo_d969e426e2e3_Cfunc_TF_DeviceListCount':
/tmp/go-build/cgo-gcc-prolog:115: undefined reference to `TF_DeviceListCount'
/usr/bin/ld: $WORK/b032/_x007.o: in function `_cgo_d969e426e2e3_Cfunc_TF_DeviceListMemoryBytes':
/tmp/go-build/cgo-gcc-prolog:136: undefined reference to `TF_DeviceListMemoryBytes'
/usr/bin/ld: $WORK/b032/_x007.o: in function `_cgo_d969e426e2e3_Cfunc_TF_DeviceListName':
/tmp/go-build/cgo-gcc-prolog:157: undefined reference to `TF_DeviceListName'
/usr/bin/ld: $WORK/b032/_x007.o: in function `_cgo_d969e426e2e3_Cfunc_TF_DeviceListType':
/tmp/go-build/cgo-gcc-prolog:178: undefined reference to `TF_DeviceListType'
/usr/bin/ld: $WORK/b032/_x007.o: in function `_cgo_d969e426e2e3_Cfunc_TF_SessionListDevices':
/tmp/go-build/cgo-gcc-prolog:234: undefined reference to `TF_SessionListDevices'
/usr/bin/ld: $WORK/b032/_x007.o: in function `_cgo_d969e426e2e3_Cfunc_TF_DeleteDeviceList':
/tmp/go-build/cgo-gcc-prolog:62: undefined reference to `TF_DeleteDeviceList'
collect2: error: ld returned 1 exit status

Can someone point me to right right direction on fixing this problem?

**Comment by plyte** [comment]
Try checking out v2.1.0 and run the go get command again. To verify try the go test command with the same endpoint

**Comment by nyeinsoe26** [comment]
I tried checking out v2.1.0 and it does not work either. But then my test successfully build after I changed the tensorflow C **to version 1.15.** Does it mean that tensorflow-go is incompatible with tensorflow-2?

**Comment by rmothukuru** [comment]
@plyte,
Can you please try Building `Tensorflow` with latest version of `Tensorflow`, i.e., `2.3` and let us know how it goes. Thank you!

**Comment by plyte** [comment]
@rmothukuru oh yeah tensorflow c 2.3.0 as of today works with tensorflow v2.1.0

**Comment by plyte** [comment]
@nyeinsoe26 can you run the go get again, but include a -v in your declaration aka:
`go get -v github.com/tensorflow/tensorflow/tensorflow/go`

**Comment by nyeinsoe26** [comment]
nyein@nyein:~/Downloads$ ./hello_tf
Hello from TensorFlow C library version 2.3.0
nyein@nyein:~/Downloads$ go get -v  github.com/tensorflow/tensorflow/tensorflow/go
github.com/tensorflow/tensorflow (download)
cannot find package "github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto" in any of:
	/usr/local/go/src/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto (from $GOROOT)
	/home/nyein/go/src/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto (from $GOPATH)

It seems I am still having this issue with tensorflow C 2.3.0. Its working fine for me with tensorflow C 1.15

**Comment by nyeinsoe26** [comment]
Oh sorry I didnt read the above messages clearly. I checked out from v2.1.0, my test build successfully now.

nyein@nyein:~/go/src/github.com/tensorflow/tensorflow/tensorflow/go$ go test github.com/tensorflow/tensorflow/tensorflow/go
# github.com/tensorflow/tensorflow/tensorflow/go
/usr/bin/ld: /usr/local/lib/libtensorflow.so: .dynsym local symbol at index 851 (>= sh_info of 2)
/usr/bin/ld: /usr/local/lib/libtensorflow.so: .dynsym local symbol at index 1959 (>= sh_info of 2)
/usr/bin/ld: /usr/local/lib/libtensorflow.so: .dynsym local symbol at index 2329 (>= sh_info of 2)
/usr/bin/ld: /usr/local/lib/libtensorflow.so: .dynsym local symbol at index 2517 (>= sh_info of 2)
/usr/bin/ld: /usr/local/lib/libtensorflow.so: .dynsym local symbol at index 2732 (>= sh_info of 2)
/usr/bin/ld: /usr/local/lib/libtensorflow.so: .dynsym local symbol at index 2733 (>= sh_info of 2)
# github.com/tensorflow/tensorflow/tensorflow/go.test
/usr/bin/ld: /usr/local/lib/libtensorflow.so: .dynsym local symbol at index 851 (>= sh_info of 2)
/usr/bin/ld: /usr/local/lib/libtensorflow.so: .dynsym local symbol at index 1959 (>= sh_info of 2)
/usr/bin/ld: /usr/local/lib/libtensorflow.so: .dynsym local symbol at index 2329 (>= sh_info of 2)
/usr/bin/ld: /usr/local/lib/libtensorflow.so: .dynsym local symbol at index 2517 (>= sh_info of 2)
/usr/bin/ld: /usr/local/lib/libtensorflow.so: .dynsym local symbol at index 2732 (>= sh_info of 2)
/usr/bin/ld: /usr/local/lib/libtensorflow.so: .dynsym local symbol at index 2733 (>= sh_info of 2)
ok  	github.com/tensorflow/tensorflow/tensorflow/go	0.152s

This is with tensorflow C 2.3.0. It works fine after checking out from v2.1.0. Thank you for all the help @plyte  @rmothukuru

**Comment by plyte** [comment]
🎉 🎈 🎉 
Glad to help! Good luck with your tensorflow/golang adventures!

**Comment by nyeinsoe26** [comment]
Thanks. Since this is resolved, I will be closing the issue.
