### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Kim-William** [tensorflow/tensorflow#77826]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.17

### Custom code

Yes

### OS platform and distribution

ubuntu 22.04

### Python version

3.9.20

### Current behavior?

TensorFlow version: 2.17.0
Transformers version: 4.46.0.dev0
Keras version: 3.6.0

This problem can be solved by using TensorFlow version 2.11, but it is not solved because i'm trying to use Tensorflow version 2.17. The existing BERT model is implemented in version 2.17, but this also does not work in version 2.11 of Tensorflow... 

Therefore, I would like to solve this problem and make the entire code work in version 2.17.

### Standalone code to reproduce the issue

```shell
from transformers import BertTokenizer, TFBertForSequenceClassification, AdamWeightDecay, TFBertModel
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import classification_report, accuracy_score
from tensorflow.keras.losses import SparseCategoricalCrossentropy
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.layers import Input, Dense, Dropout, GlobalAveragePooling1D

from tensorflow.keras.models import Model
from keras_tuner import HyperParameters, RandomSearch

import numpy as np
import tensorflow as tf

import joblib, os
import pandas as pd
import tensorflow as tf
import numpy as np
import pickle

import numpy as np
import tensorflow as tf
from transformers import TFBertModel
from tensorflow.keras.layers import Input, Dense, GlobalAveragePooling1D
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import SparseCategoricalCrossentropy
from keras_tuner import RandomSearch
from tensorflow.keras.models import Model

gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
    try:
        # Set memory growth
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
    except RuntimeError as e:
        print(e)

INPUT_DIR = "../Output/proto_models_rev2"
# Load data
df_train = pd.read_csv(os.path.join(INPUT_DIR, 'train_cleaned.csv'))
df_test = pd.read_csv(os.path.join(INPUT_DIR, 'test_cleaned.csv'))
# df_test = processor.load_data()
X_train = df_train['review']
X_test = df_test['review']
y_train = df_train['polarity']
y_test = df_test['polarity']

# Initialize the BERT tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

# Tokenizing the datasets
X_train_tokens = tokenizer(
    text=list(X_train),
    add_special_tokens=True,
    max_length=100,
    padding='max_length',
    truncation=True,
    return_tensors='tf',
    return_token_type_ids=False,
    return_attention_mask=True
)

X_test_tokens = tokenizer(
    text=list(X_test),
    add_special_tokens=True,
    max_length=100,
    padding='max_length',
    truncation=True,
    return_tensors='tf',
    return_token_type_ids=False,
    return_attention_mask=True
)


# # Define BERT Model
# bert_model = TFBertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=2)

# # Use Hugging Face's AdamWeightDecay optimizer
# optimizer = AdamWeightDecay(learning_rate=2e-5, weight_decay_rate=0.01)
# # Compile the model using a standard loss function
# loss_fn = SparseCategoricalCrossentropy(from_logits=True)
# bert_model.compile(optimizer=optimizer, loss=loss_fn, metrics=['accuracy'])
# # Model Summary
# bert_model.summary()

# BERT Model Definition
def build_bert_model(hp):
    input_ids = Input(shape=(100,), dtype=tf.int32, name="input_ids")
    attention_mask = Input(shape=(100,), dtype=tf.int32, name="attention_mask")

    bert_model = TFBertModel.from_pretrained("bert-base-uncased")
    bert_output = bert_model(input_ids=input_ids, attention_mask=attention_mask)[0]
    
    pooled_output = GlobalAveragePooling1D()(bert_output)
    dense = Dense(units=hp.Int("units", min_value=32, max_value=128, step=32), activation='relu')(pooled_output)
    output = Dense(2, activation='softmax')(dense)
    
    model = Model(inputs=[input_ids, attention_mask], outputs=output)
    
    learning_rate = hp.Choice("learning_rate", values=[1e-5, 2e-5, 3e-5])
    optimizer = Adam(learning_rate=learning_rate, weight_decay_rate=0.01)
    model.compile(optimizer=optimizer, loss=SparseCategoricalCrossentropy(from_logits=True), metrics=["accuracy"])
    
    return model

# Convert to TensorFlow Tensor
def create_tf_dataset(X, y, batch_size=32):
    input_ids = tf.convert_to_tensor(X["input_ids"])
    attention_mask = tf.convert_to_tensor(X["attention_mask"])
    y = tf.convert_to_tensor(y)
    
    dataset = tf.data.Dataset.from_tensor_slices(({"input_ids": input_ids, "attention_mask": attention_mask}, y))
    dataset = dataset.batch(batch_size).prefetch(tf.data.experimental.AUTOTUNE)
    return dataset

# Convert datasets
train_dataset = create_tf_dataset(X_train_tokens, y_train)
val_dataset = create_tf_dataset(X_test_tokens, y_test)

# Hyperparameter tuner
tuner = RandomSearch(
    build_bert_model,
    objective="val_accuracy",
    max_trials=5,
    executions_per_trial=1,
    directory="bert_tuning",
    project_name="bert_sentiment_analysis"
)


# Perform the hyperparameter tuning search
tuner.search(
    train_dataset,
    validation_data=val_dataset,
    epochs=3
)
```

### Relevant log output

```shell
{
	"name": "RuntimeError",
	"message": "Number of consecutive failures exceeded the limit of 3.
Traceback (most recent call last):
  File \"/home/woong/AI/Dissertation/.venv/lib/python3.9/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial
    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)
  File \"/home/woong/AI/Dissertation/.venv/lib/python3.9/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial
    results = self.run_trial(trial, *fit_args, **fit_kwargs)
  File \"/home/woong/AI/Dissertation/.venv/lib/python3.9/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial
    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)
  File \"/home/woong/AI/Dissertation/.venv/lib/python3.9/site-packages/keras_tuner/src/engine/tuner.py\", line 232, in _build_and_fit_model
    model = self._try_build(hp)
  File \"/home/woong/AI/Dissertation/.venv/lib/python3.9/site-packages/keras_tuner/src/engine/tuner.py\", line 164, in _try_build
    model = self._build_hypermodel(hp)
  File \"/home/woong/AI/Dissertation/.venv/lib/python3.9/site-packages/keras_tuner/src/engine/tuner.py\", line 155, in _build_hypermodel
    model = self.hypermodel.build(hp)
  File \"/tmp/ipykernel_48514/733536575.py\", line 91, in build_bert_model
    bert_model = TFBertModel.from_pretrained(\"bert-base-uncased\")
  File \"/home/woong/AI/Dissertation/.venv/lib/python3.9/site-packages/transformers/modeling_tf_utils.py\", line 1684, in from_pretrained
    model(model.dummy_inputs)  # build the network with dummy inputs
  File \"/home/woong/AI/Dissertation/.venv/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File \"/home/woong/AI/Dissertation/.venv/lib/python3.9/site-packages/transformers/models/bert/modeling_tf_bert.py\", line 1130, in call
    outputs = self.bert(
  File \"/home/woong/AI/Dissertation/.venv/lib/python3.9/site-packages/transformers/models/bert/modeling_tf_bert.py\", line 871, in call
    encoder_outputs = self.encoder(
  File \"/home/woong/AI/Dissertation/.venv/lib/python3.9/site-packages/optree/ops.py\", line 747, in tree_map
    return treespec.unflatten(map(func, *flat_args))
AttributeError: Exception encountered when calling TFBertMainLayer.call().

'NoneType' object has no attribute 'shape'

Arguments received by TFBertMainLayer.call():
  • input_ids=tf.Tensor(shape=(3, 5), dtype=int32)
  • attention_mask=None
  • token_type_ids=None
  • position_ids=None
  • head_mask=None
  • inputs_embeds=None
  • encoder_hidden_states=None
  • encoder_attention_mask=None
  • past_key_values=None
  • use_cache=True
  • output_attentions=False
  • output_hidden_states=False
  • return_dict=True
  • training=False
  • kwargs=<class 'inspect._empty'>
",
	"stack": "---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[19], line 132
    121 tuner = RandomSearch(
    122     build_bert_model,
    123     objective=\"val_accuracy\",
   (...)
    127     project_name=\"bert_sentiment_analysis\"
    128 )
    131 # Perform the hyperparameter tuning search
--> 132 tuner.search(
    133     train_dataset,
    134     validation_data=val_dataset,
    135     epochs=3
    136 )

File ~/AI/Dissertation/.venv/lib/python3.9/site-packages/keras_tuner/src/engine/base_tuner.py:235, in BaseTuner.search(self, *fit_args, **fit_kwargs)
    233     self.on_trial_begin(trial)
    234     self._try_run_and_update_trial(trial, *fit_args, **fit_kwargs)
--> 235     self.on_trial_end(trial)
    236 self.on_search_end()

File ~/AI/Dissertation/.venv/lib/python3.9/site-packages/keras_tuner/src/engine/base_tuner.py:339, in BaseTuner.on_trial_end(self, trial)
    333 def on_trial_end(self, trial):
    334     \"\"\"Called at the end of a trial.
    335 
    336     Args:
    337         trial: A `Trial` instance.
    338     \"\"\"
--> 339     self.oracle.end_trial(trial)
    340     self.save()

File ~/AI/Dissertation/.venv/lib/python3.9/site-packages/keras_tuner/src/engine/oracle.py:108, in synchronized.<locals>.wrapped_func(*args, **kwargs)
    106     LOCKS[oracle].acquire()
    107     THREADS[oracle] = thread_name
--> 108 ret_val = func(*args, **kwargs)
    109 if need_acquire:
    110     THREADS[oracle] = None

File ~/AI/Dissertation/.venv/lib/python3.9/site-packages/keras_tuner/src/engine/oracle.py:588, in Oracle.end_trial(self, trial)
    586 if not self._retry(trial):
    587     self.end_order.append(trial.trial_id)
--> 588     self._check_consecutive_failures()
    590 self._save_trial(trial)
    591 self.save()

File ~/AI/Dissertation/.venv/lib/python3.9/site-packages/keras_tuner/src/engine/oracle.py:545, in Oracle._check_consecutive_failures(self)
    543     consecutive_failures = 0
    544 if consecutive_failures == self.max_consecutive_failed_trials:
--> 545     raise RuntimeError(
    546         \"Number of consecutive failures exceeded the limit \"
    547         f\"of {self.max_consecutive_failed_trials}.\
\"
    548         + (trial.message or \"\")
    549     )

RuntimeError: Number of consecutive failures exceeded the limit of 3.
Traceback (most recent call last):
  File \"/home/woong/AI/Dissertation/.venv/lib/python3.9/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial
    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)
  File \"/home/woong/AI/Dissertation/.venv/lib/python3.9/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial
    results = self.run_trial(trial, *fit_args, **fit_kwargs)
  File \"/home/woong/AI/Dissertation/.venv/lib/python3.9/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial
    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)
  File \"/home/woong/AI/Dissertation/.venv/lib/python3.9/site-packages/keras_tuner/src/engine/tuner.py\", line 232, in _build_and_fit_model
    model = self._try_build(hp)
  File \"/home/woong/AI/Dissertation/.venv/lib/python3.9/site-packages/keras_tuner/src/engine/tuner.py\", line 164, in _try_build
    model = self._build_hypermodel(hp)
  File \"/home/woong/AI/Dissertation/.venv/lib/python3.9/site-packages/keras_tuner/src/engine/tuner.py\", line 155, in _build_hypermodel
    model = self.hypermodel.build(hp)
  File \"/tmp/ipykernel_48514/733536575.py\", line 91, in build_bert_model
    bert_model = TFBertModel.from_pretrained(\"bert-base-uncased\")
  File \"/home/woong/AI/Dissertation/.venv/lib/python3.9/site-packages/transformers/modeling_tf_utils.py\", line 1684, in from_pretrained
    model(model.dummy_inputs)  # build the network with dummy inputs
  File \"/home/woong/AI/Dissertation/.venv/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File \"/home/woong/AI/Dissertation/.venv/lib/python3.9/site-packages/transformers/models/bert/modeling_tf_bert.py\", line 1130, in call
    outputs = self.bert(
  File \"/home/woong/AI/Dissertation/.venv/lib/python3.9/site-packages/transformers/models/bert/modeling_tf_bert.py\", line 871, in call
    encoder_outputs = self.encoder(
  File \"/home/woong/AI/Dissertation/.venv/lib/python3.9/site-packages/optree/ops.py\", line 747, in tree_map
    return treespec.unflatten(map(func, *flat_args))
AttributeError: Exception encountered when calling TFBertMainLayer.call().

'NoneType' object has no attribute 'shape'

Arguments received by TFBertMainLayer.call():
  • input_ids=tf.Tensor(shape=(3, 5), dtype=int32)
  • attention_mask=None
  • token_type_ids=None
  • position_ids=None
  • head_mask=None
  • inputs_embeds=None
  • encoder_hidden_states=None
  • encoder_attention_mask=None
  • past_key_values=None
  • use_cache=True
  • output_attentions=False
  • output_hidden_states=False
  • return_dict=True
  • training=False
  • kwargs=<class 'inspect._empty'>
"
}
```

**Comment by Venkat6871** [comment]
Hi **@Kim-William** ,
Apologies for the delay. I tried to run your code on Colab using TensorFlow 2.17.0, and it is throwing the following error:``` No such file or directory: '../Output/proto_models_rev2/train_cleaned.csv'```. Could you please provide the CSV file associated with your code? This will make it easier for us to replicate and troubleshoot the issue. Please find the [gist](https://colab.sandbox.google.com/gist/Venkat6871/f0c65ee292b0c59cd7330a113d6a7f7f/77826_tf-2-17-0-v.ipynb) here for reference.

Thank you!

**Comment by Kim-William** [comment]
> Hi **@Kim-William** , Apologies for the delay. I tried to run your code on Colab using TensorFlow 2.17.0, and it is throwing the following error:` No such file or directory: '../Output/proto_models_rev2/train_cleaned.csv'`. Could you please provide the CSV file associated with your code? This will make it easier for us to replicate and troubleshoot the issue. Please find the [gist](https://colab.sandbox.google.com/gist/Venkat6871/f0c65ee292b0c59cd7330a113d6a7f7f/77826_tf-2-17-0-v.ipynb) here for reference.
> 
> Thank you!
[test_cleaned.csv](https://github.com/user-attachments/files/17439887/test_cleaned.csv)
[train_cleaned.csv](https://github.com/user-attachments/files/17439888/train_cleaned.csv)


Here i attached the data set.

**Comment by Venkat6871** [comment]
Hi **@Kim-William** ,
Apologies for the delay, and thank you for providing the necessary files. I tried running your code on Colab using TensorFlow v2.17.0 and the nightly version, and I encountered the same issue. Please find the [gist](https://colab.sandbox.google.com/gist/Venkat6871/b134ff955e997f35974092f9a0c6dbe9/77826_tf-2-17-0-v.ipynb) here for reference.
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues) as this issue is more related to keras
Thank you!
