### ISSUE TITLE
tf.contrib.framework.sort failing with <<...has no attribute 'sort'>> in TF windows 

### ISSUE THREAD

**Issue by spripa** [tensorflow/tensorflow#16405]
### [Problem] : Can't use tf.contrib.framework.sort in my tensorflow code as it's failing to find the 'sort' attribute

Source code:
```
import tensorflow as tf

x = tf.placeholder(tf.float32, shape=(10, 10))
y = tf.contrib.framework.sort(x)

with tf.Session() as sess:
    rand_array = np.random.rand(10, 10)
    print(sess.run(y, feed_dict={x: rand_array})) 
```

Error log:
```
 <module>
    y = tf.contrib.framework.sort(x)
AttributeError: module 'tensorflow.contrib.framework' has no attribute 'sort'
```

### System information
- I've been trying to use the tf.contrib.framework.sort  within a custom loss function but issue being reproduced with a simple call to the tf.contrib.framework.sort
- Windows 10 64 bit
- TF installed with native pip3
- TF version: 1.4.0
- Python version: 3.6.2 
- TF with CPU support only

**Comment by mrry** [comment]
According to [the documentation](https://www.tensorflow.org/versions/r1.5/api_docs/python/tf/contrib/framework/sort), `tf.contrib.framework.sort()` was added after TF 1.4, and so you will need to upgrade to TF 1.5 or a nightly build to use it.

**Comment by dimitri320** [comment]
Still doesn't work in TF 1.12.0!
