### ISSUE TITLE
Function tracing fails after upgrading to 2.3.0

### ISSUE THREAD

**Issue by davidia** [tensorflow/tensorflow#41861]
**System information**
- Windows 7
- TensorFlow 2.3.0 from PyPI
- Python version: 3.7.7
- CPU only

After upgrading to 2.3.0 function tracing fails
```

WARNING:tensorflow:AutoGraph could not transform <function _convert_function_call.<locals>.f at 0x0000000015156E58> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Converted call: <function pfor.<locals>.f at 0x00000000138BBD38>
    args: ()
    kwargs: {}

<function pfor.<locals>.f at 0x00000000138BBD38> is not cached for subkey ConversionOptions[{}]
Source code of <function pfor.<locals>.f at 0x00000000138BBD38>:

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
def f():
  return _pfor_impl(loop_fn,
  iters,
  fallback_to_while_loop=fallback_to_while_loop,
  parallel_iterations=parallel_iterations)


Error transforming entity <function pfor.<locals>.f at 0x00000000138BBD38>
WARNING: AutoGraph could not transform <function pfor.<locals>.f at 0x00000000138BBD38> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 584, in converted_call
    converted_f = conversion.convert(target_entity, program_ctx)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\impl\conversion.py", line 119, in convert
    entity, program_ctx.options, program_ctx, custom_vars)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\pyct\transpiler.py", line 412, in transform_function
    extra_locals)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\pyct\transpiler.py", line 373, in _transformed_factory
    nodes, ctx = self._transform_function(fn, user_context)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\pyct\transpiler.py", line 339, in _transform_function
    node = self.transform_ast(node, context)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\impl\conversion.py", line 70, in transform_ast
    node = activity.resolve(node, ctx, None)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\pyct\static_analysis\activity.py", line 705, in resolve
    return ActivityAnalyzer(context, parent_scope).visit(node)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\pyct\transformer.py", line 445, in visit
    result = super(Base, self).visit(node)
  File "C:\ProgramData\Miniconda3.7\lib\ast.py", line 271, in visit
    return visitor(node)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\pyct\static_analysis\activity.py", line 575, in visit_FunctionDef
    node = self._visit_arg_annotations(node)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\pyct\static_analysis\activity.py", line 551, in _visit_arg_annotations
    node = self._visit_arg_declarations(node)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\pyct\static_analysis\activity.py", line 556, in _visit_arg_declarations
    node.args.posonlyargs = self._visit_node_list(node.args.posonlyargs)
AttributeError: 'arguments' object has no attribute 'posonlyargs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 584, in converted_call
    converted_f = conversion.convert(target_entity, program_ctx)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\impl\conversion.py", line 119, in convert
    entity, program_ctx.options, program_ctx, custom_vars)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\pyct\transpiler.py", line 412, in transform_function
    extra_locals)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\pyct\transpiler.py", line 373, in _transformed_factory
    nodes, ctx = self._transform_function(fn, user_context)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\pyct\transpiler.py", line 339, in _transform_function
    node = self.transform_ast(node, context)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\impl\conversion.py", line 70, in transform_ast
    node = activity.resolve(node, ctx, None)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\pyct\static_analysis\activity.py", line 705, in resolve
    return ActivityAnalyzer(context, parent_scope).visit(node)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\pyct\transformer.py", line 445, in visit
    result = super(Base, self).visit(node)
  File "C:\ProgramData\Miniconda3.7\lib\ast.py", line 271, in visit
    return visitor(node)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\pyct\static_analysis\activity.py", line 575, in visit_FunctionDef
    node = self._visit_arg_annotations(node)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\pyct\static_analysis\activity.py", line 551, in _visit_arg_annotations
    node = self._visit_arg_declarations(node)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\pyct\static_analysis\activity.py", line 556, in _visit_arg_declarations
    node.args.posonlyargs = self._visit_node_list(node.args.posonlyargs)
AttributeError: 'arguments' object has no attribute 'posonlyargs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 584, in converted_call
    converted_f = conversion.convert(target_entity, program_ctx)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\impl\conversion.py", line 119, in convert
    entity, program_ctx.options, program_ctx, custom_vars)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\pyct\transpiler.py", line 412, in transform_function
    extra_locals)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\pyct\transpiler.py", line 373, in _transformed_factory
    nodes, ctx = self._transform_function(fn, user_context)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\pyct\transpiler.py", line 339, in _transform_function
    node = self.transform_ast(node, context)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\impl\conversion.py", line 70, in transform_ast
    node = activity.resolve(node, ctx, None)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\pyct\static_analysis\activity.py", line 705, in resolve
    return ActivityAnalyzer(context, parent_scope).visit(node)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\pyct\transformer.py", line 445, in visit
    result = super(Base, self).visit(node)
  File "C:\ProgramData\Miniconda3.7\lib\ast.py", line 271, in visit
    return visitor(node)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\pyct\static_analysis\activity.py", line 575, in visit_FunctionDef
    node = self._visit_arg_annotations(node)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\pyct\static_analysis\activity.py", line 551, in _visit_arg_annotations
    node = self._visit_arg_declarations(node)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\pyct\static_analysis\activity.py", line 556, in _visit_arg_declarations
    node.args.posonlyargs = self._visit_node_list(node.args.posonlyargs)
AttributeError: 'arguments' object has no attribute 'posonlyargs'

```

**Comment by geetachavan1** [comment]
@davidia Can you please provide Standalone code to reproduce the issue?

**Comment by davidia** [comment]
@geetachavan1  this recreates it:

```import tensorflow as tf

@tf.function()
def f(x):
    return x + 1


if __name__ == '__main__':
    tf.autograph.set_verbosity(10, True)
    x = tf.constant(1)
    print(f(x))

```
and the error is:

```Converted call: <function f at 0x0000000002B89828>
    args: (<tf.Tensor 'x:0' shape=() dtype=int32>,)
    kwargs: {}

<function f at 0x0000000002B89828> is not cached for subkey ConversionOptions[{}]
Source code of <function f at 0x0000000002B89828>:

@tf.function()
def f(x):
    return x + 1


Error transforming entity <function f at 0x0000000002B89828>
WARNING: AutoGraph could not transform <function f at 0x0000000002B89828> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 584, in converted_call
    converted_f = conversion.convert(target_entity, program_ctx)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\impl\conversion.py", line 119, in convert
    entity, program_ctx.options, program_ctx, custom_vars)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\pyct\transpiler.py", line 412, in transform_function
    extra_locals)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\pyct\transpiler.py", line 373, in _transformed_factory
    nodes, ctx = self._transform_function(fn, user_context)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\pyct\transpiler.py", line 339, in _transform_function
    node = self.transform_ast(node, context)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\impl\conversion.py", line 70, in transform_ast
    node = activity.resolve(node, ctx, None)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\pyct\static_analysis\activity.py", line 705, in resolve
    return ActivityAnalyzer(context, parent_scope).visit(node)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\pyct\transformer.py", line 445, in visit
    result = super(Base, self).visit(node)
  File "C:\ProgramData\Miniconda3.7\lib\ast.py", line 271, in visit
    return visitor(node)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\pyct\static_analysis\activity.py", line 575, in visit_FunctionDef
    node = self._visit_arg_annotations(node)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\pyct\static_analysis\activity.py", line 551, in _visit_arg_annotations
    node = self._visit_arg_declarations(node)
  File "C:\ProgramData\Miniconda3.7\lib\site-packages\tensorflow\python\autograph\pyct\static_analysis\activity.py", line 556, in _visit_arg_declarations
    node.args.posonlyargs = self._visit_node_list(node.args.posonlyargs)
AttributeError: 'arguments' object has no attribute 'posonlyargs'
WARNING:tensorflow:AutoGraph could not transform <function f at 0x0000000002B89828> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
tf.Tensor(2, shape=(), dtype=int32)

Process finished with exit code 0
```

**Comment by davidia** [comment]
This is windows only, it works as expected with the same versions on linux.

**Comment by amahendrakar** [comment]
@davidia,
>tf.Tensor(2, shape=(), dtype=int32)
>
>Process finished with exit code 0

As we can see from the logs, the code snippet does print the output tensor.

Could you please set `tf.autograph.set_verbosity` to 0 as shown below and let us know what the output is? 


```
@tf.function()
def f(x):
    return x + 1
if __name__ == '__main__':
    tf.autograph.set_verbosity(0, True)
    x = tf.constant(1)
    print(f(x))
```

Thanks!

**Comment by davidia** [comment]
It swallows the error if verbosity is 0 but of course then there will be performance issues.

I tried in a clean python 3.7.7 virtual environment and I wasn't able to reproduce it. I think there is a problem upgrading from 2.2.0 with pip. Going to close it for now, thanks for your help.
