### ISSUE TITLE
Cannot compile with Visual Studio 15

### ISSUE THREAD

**Issue by DrPingy** [tensorflow/tensorflow#16048]
If I build a version of the current tensorflow version 1.5.0RC on Windows with CMAKE and Visual Studio 15 following error is occurred:

1>sparse_column_iterable.cc
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.12.25827\include\algorithm(2417): error C2678: binary '*': no operator found which takes a left-hand operand of type 'const tensorflow::boosted_trees::utils::`anonymous-namespace'::IndicesRowIterator' (or there is no acceptable conversion)
1>D:\....\tensorflow\tensorflow\contrib\boosted_trees\lib\utils\sparse_column_iterable.cc(54): note: could be 'const __int64 &tensorflow::boosted_trees::utils::`anonymous-namespace'::IndicesRowIterator::operator *(void)'
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.12.25827\include\algorithm(2417): note: while trying to match the argument list '(const tensorflow::boosted_trees::utils::`anonymous-namespace'::IndicesRowIterator)'
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.12.25827\include\algorithm(2439): note: see reference to function template instantiation '_FwdIt std::_Lower_bound_unchecked<_Iter,_Ty,_Fn>(_FwdIt,_FwdIt,const _Ty &,_Pr)' being compiled
1>        with
1>        [
1>            _FwdIt=tensorflow::boosted_trees::utils::`anonymous-namespace'::IndicesRowIterator,
1>            _Iter=tensorflow::boosted_trees::utils::`anonymous-namespace'::IndicesRowIterator,
1>            _Ty=tensorflow::int64,
1>            _Fn=std::less<void>,
1>            _Pr=std::less<void>
1>        ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.12.25827\include\algorithm(2447): note: see reference to function template instantiation '_FwdIt std::lower_bound<_FwdIt,_Ty,std::less<void>>(_FwdIt,_FwdIt,const _Ty &,_Pr)' being compiled
1>        with
1>        [
1>            _FwdIt=tensorflow::boosted_trees::utils::`anonymous-namespace'::IndicesRowIterator,
1>            _Ty=tensorflow::int64,
1>            _Pr=std::less<void>
1>        ]
1>D:\....\tensorflow\tensorflow\contrib\boosted_trees\lib\utils\sparse_column_iterable.cc(119): note: see reference to function template instantiation '_FwdIt std::lower_bound<tensorflow::boosted_trees::utils::`anonymous-namespace'::IndicesRowIterator,tensorflow::int64>(_FwdIt,_FwdIt,const _Ty &)' being compiled
1>        with
1>        [
1>            _FwdIt=tensorflow::boosted_trees::utils::`anonymous-namespace'::IndicesRowIterator,
1>            _Ty=tensorflow::int64
1>        ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.12.25827\include\algorithm(2417): error C2100: illegal indirection
1>Done building project "tf_core_kernels.vcxproj" -- FAILED.

This problem is also discussed in #12000 after closing this issue.

###System information
 tensorflow 1.5.0RC
 Windows 10
 VisualStudio Prof. 2017
 CMake 3.10.1

**Comment by arunmandal53** [comment]
For me  Visual Studio 2015 Update 3 is working. I am currently testing for Visual Studio 2017. Will update you on how it goes.

**Comment by DrPingy** [comment]
I'm very confused with the versions numbers of Visual Studio. I use 15.5.3: that is Visual Studio 2017!!

**Comment by arunmandal53** [comment]
You are right and not seem to be confused. I have build tensorflow using cmake and Visual Studio 2015 update 3 release with version 14.x.x. I think you can try to build it using Visual Studio 2015 Update 3 Community Edition.

**Comment by DrPingy** [comment]
I can confirm that Visual Studio 2015 Version 14.1 works!

**Comment by arunmandal53** [comment]
Here is Step by Step instruction to build tensorflow gpu version 1.5.0 on Windows OS. Hope this helps for windows users. Let me know if the tutorial worked. 
Visit my blog here. http://www.python36.com/install-tensorflow-gpu-windows

**Comment by DrPingy** [comment]
in #15925 is a solution
Thanks to boblw for the info!

**Comment by DrPingy** [comment]
gpu version of tensorflow cannot compiled with Visual Studio 2017 and toolset v141. The example of nvcc you must compile with toolset 14.0!
