### ISSUE TITLE
Bazel missing dependency declaration for Eigen

### ISSUE THREAD

**Issue by gustavla** [tensorflow/tensorflow#3743]
Compilation error that suggests Bazel is not recognizing the Eigen header files. Occurs consistently for me on all versions starting from 21716d8f6e175cd6e8cd97a84e48497574268b0c up until the current master (00726750c9f7dedfc57685c5011e21df3b5b3706).

### Environment info
64-bit CentOS / cuda 7.5.18 / cudnn 5.0.5 / bazel 0.2.1 / java 1.8.0_91

### Steps to reproduce
Run `./configure` and set up compilation with CUDA 7.5 and CuDNN 5.0.

    bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

Compiles fine without `--config=cuda`.

### What have you tried?
I ran a `git bisect` and traced it to 21716d8f6e175cd6e8cd97a84e48497574268b0c. More specifically, it is moving Eigen out of the `eigen-eigen-b4fa9622b809` folder that for some reason is causing this. Reverting only these changes from the master makes it compile just fine (see https://github.com/gustavla/tensorflow/commit/058a6517576171bb0c7dcf11ec1aac04bd59aedf). I have so far been unable to fix it while keeping the `strip_prefix` in.

It suspect it might be a quirk in bazel 0.2.1. It would be great if anyone else running that version can confirm.

### Error
The error message (abridged and personal paths removed):
```
ERROR: /.../tensorflow/core/kernels/BUILD:1527:1: undeclared inclusion(s) in rule '//tensorflow/core/kernels:depth_space_ops_gpu':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/kernels/spacetodepth_op_gpu.cu.cc':
  '/.../.cache/external/eigen_archive/Eigen/Core'
  '/.../.cache/external/eigen_archive/Eigen/src/Core/util/DisableStupidWarnings.h'
  '/.../.cache/external/eigen_archive/Eigen/src/Core/util/Macros.h'
  ...
  '/.../.cache/external/eigen_archive/Eigen/src/Core/ArrayWrapper.h'
  '/.../.cache/external/eigen_archive/Eigen/src/Core/GlobalFunctions.h'
  '/.../.cache/external/eigen_archive/Eigen/src/Core/util/ReenableStupidWarnings.h'.
```
Issues with related error messages include #1157 and  #3589.

**Comment by girving** [comment]
Bazel 0.2.1 is quite old.  Could you check if upgrading to recent bazel solves the problem?

**Comment by gustavla** [comment]
I just upgraded to Bazel 0.3.1 and tried to compile again (after fully expunging the cache). The problem still happens.

**Comment by girving** [comment]
@martinwicke Have you seen anything similar?

**Comment by flybirdx101** [comment]
The same happens for me on Ubuntu 16.04.1 with Bazel 0.3.1. Tried reconfiguring with and without GPU support - this doesn't change anything.

**Comment by martinwicke** [comment]
@davidzchen We discussed this change a while ago, and it seemed to be doing ok -- did something change in bazel 0.3.1?

**Comment by gustavla** [comment]
I have tested on all versions of bazel supported by the master branch now (0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.3.0, 0.3.1) and I got the same error every time. I carefully cleaned cache and killed any lingering bazel process between builds.

I also double-checked that building without GPU support is indeed fine, contrary to @flybirdx101's experience.

**Comment by flybirdx101** [comment]
Here is my error message, if this helps (abridged and personal paths removed):
`ERROR: /.../tensorflow/core/BUILD:925:1: undeclared inclusion(s) in rule '//tensorflow/core:framework_internal':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/framework/device_base.cc':
  '/.../third_party/eigen3/unsupported/Eigen/CXX11/CustomOps'
  '/.../third_party/eigen3/unsupported/Eigen/CXX11/src/CustomOps/CTypes.h'
  '/.../third_party/eigen3/unsupported/Eigen/CXX11/src/CustomOps/CMatMatProduct.h'`

**Comment by davidzchen** [comment]
@martinwicke - What is the relationship between `third_party/eigen3` and the `eigen_archive` external repository? `//third_party/eigen3` depends on `@eigen_archive//:eigen`, but I'm not familiar with what the differences between these two packages are.

@flybirdx101's error message seems to be complaining about headers in `//third_party/eigen3` and not `@eigen_archive`:

```
third_party/eigen3/unsupported/Eigen/CXX11/CustomOps
third_party/eigen3/unsupported/Eigen/CXX11/src/CustomOps/CTypes.h
third_party/eigen3/unsupported/Eigen/CXX11/src/CustomOps/CMatMatProduct.h
```

These headers do not seem to be listed in the `hdrs` for the `cc_library` rule in `third_party/eigen3`'s [BUILD file](https://github.com/tensorflow/tensorflow/blob/master/third_party/eigen3/BUILD).

@flybirdx101 - can you try adding the following items to the `hdrs` for the `cc_library` rule in `third_party/eigen3/BUILD`?

```python
        "unsupported/Eigen/CXX11/CustomOps",
        "unsupported/Eigen/CXX11/src/CustomOps/*.h",
```

**Comment by gustavla** [comment]
It looks like @flybirdx101 and my issue are probably not the same. @flybirdx101: Did you add `CustomOps` yourself? I can't find any evidence of that directory ever being in tensorflow.

@davidzchen `@eigen_archive` is the external library that is downloaded and unpacked at build time. `//third_party/eigen3` is a thin wrapper that makes Eigen look like a local bazel package (I imagine for the purpose of the dependency graph, but I'm just guessing).

**Comment by gustavla** [comment]
I have after a lot of debugging understood this error and it is more appropriately filed and fixed as a bazel issue (https://github.com/bazelbuild/bazel/issues/1642).

In the meantime, the dirty fix is to name your cache directory to something really really long:
```
bazel --output_base=/var/tmp/.really-really-long-cache ...
```
If it still doesn't work, try making it even longer.

**Comment by martinwicke** [comment]
That was some impressive sleuthing! Thanks!

**Comment by davidzchen** [comment]
Thanks, @gustavla!

**Comment by gustavla** [comment]
Acually, after further digging (catch up at https://github.com/bazelbuild/bazel/issues/1642), it turns out that this is indeed a Tensorflow bug. Instead of `gcc -M` directly, it is actually the python script `crosstool_wrapper_driver_is_not_gcc` that gets called, which in turn calls gcc (or in the case I am dealing with nvcc, which then invokes gcc). The problem is that this python script is not acknowledging when `-fno-canonical-system-headers` is added, so it does not get included in the actual call.

I tried adding `-fno-canonical-system-headers` inside the `--compiler-options` of the python script if it was part of the python script's arguments. This fixed the problem and I got no build errors. What do you think of this solution? The question is, should *all* arguments (or at least all `-f...` arguments) be propagated into the `--compiler-options` or should a special case be done for `-fno-canonical-system-headers` alone?

**Comment by flybirdx101** [comment]
@davidzchen I have tried this, but it didn't work, the same error.

@gustavla These are my own custom Eigen ops, they used to work just fine before I merged my TensorFlow fork with the upstream repository. 

I have also tried the long cache directory name fix, but it is not working for me as well.

**Comment by flybirdx101** [comment]
Actually my bad, the error has changed. Now it is like this:
```
/tensorflow/contrib/factorization/kernels/BUILD:20:1: undeclared inclusion(s) in rule '//tensorflow/contrib/factorization/kernels:wals_solver_ops':
this rule is missing dependency declarations for the following files included by 'tensorflow/contrib/factorization/kernels/wals_solver_ops.cc':
```
And then the same list of my custom ops.

**Comment by flybirdx101** [comment]
Okey, there was my mistake and it looks like @davidzchen 's advice has fixed everything for me. 

I have updated to TensorFlow [6d57860](https://github.com/tensorflow/tensorflow/commit/6d57860e390f8f44580ae3a05aa350a4b6138b2b) and Bazel [936c2c2](https://github.com/bazelbuild/bazel/commit/936c2c2c815b64525bc6d3c6ac8f049655589370) and everything is working now. Thanks!

**Comment by gustavla** [comment]
I just pushed a PR with a propsed fix to this. Note, this is fixing the issue that I described and not the one @flybirdx101 was having, which turned out to be a separate issue altogether.

**Comment by gustavla** [comment]
PR has been merged. Closing this.
