### ISSUE TITLE
[BUG, iOS] Symbol not found: _clock_gettime 

### ISSUE THREAD

**Issue by rhcpfan** [tensorflow/tensorflow#30304]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **iOS 9.3**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **TESTED on iPhone 6s, iPad Air 2, iPad Mini 4**
- TensorFlow installed from (source or binary): **compiled for iOS using the provided Makefile**
- TensorFlow version (use command below): **1.13**

**Describe the current behavior**

Loading a network using TensorFlow 1.13 compiled for iOS (using the provided Makefile, altered to use `ANDROID_TYPES_FULL` [variable is used in iOS as well, not only on Android!]) in an app running on iOS < 10.0 crashes the application with the following error:

```

dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Users/rhcpfan/Library/Developer/CoreSimulator/Devices/4B733BDB-F1AB-49A4-87D5-3F23C507B599/data/Containers/Bundle/Application/58FB49D0-1330-442A-A46A-8ADADD34EAA2/MyApp.app/MyApp
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 9.3.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Users/slowhand/Library/Developer/CoreSimulator/Devices/4B733BDB-F1AB-49A4-87D5-3F23C507B599/data/Containers/Bundle/Application/58FB49D0-1330-442A-A46A-8ADADD34EAA2/MyApp.app/MyApp
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 9.3.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libSystem.B.dylib

```

**Comment by rhcpfan** [comment]
After more digging, every call to `tensorflow::EnvTime::NowMicros()` causes the app to crash on iOS 9.

The first call that produced a crash was in the logger, so I removed the time-related information from `LogMessage::GenerateLogMessage()` in `tensorflow/core/platform/default/logging.cc` and re-compiled. Now it crashes in `tensorflow::DirectSession::RunInterval(...)`.

Any idea on how to provide a dummy implementation for `tensorflow::EnvTime::NowMicros()`? If I'll always return 0, will this have any side effects?

**Comment by yyoon** [comment]
Is this still an issue for you in more recent versions, such as `1.15.0`, `2.0.0`?

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 30 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
We are closing this issue for now due to lack of activity. Please comment if this is still an issue for you. Thanks!
