### ISSUE TITLE
Bazel compiling source code failed because of highwayhash/sip_hash.cc

### ISSUE THREAD

**Issue by Ralle1998** [tensorflow/tensorflow#68824]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.16.1 

### Custom code

No

### OS platform and distribution

Microsoft Windows 10 Home 10.0.19045 

### Python version

3.12

### Bazel version

6.5.0

### GCC/compiler version

MSVC 14.38.33130

### CUDA/cuDNN version

Not used

### GPU model and memory

Not used

### Current behavior?

I tried to compile the source code of Tensorflow to get access to the C++ API. I followed the instructions on https://www.tensorflow.org/install/source_windows, cloned the repository to C:/tensorflow, set the configurations with configure.py and started to compile. Then I got the first error:

```
.\tensorflow/lite/delegates/xnnpack/weight_cache.h(276): error C7555: use of designated initializers requires at least '/std:c++20'
tensorflow/lite/delegates/xnnpack/weight_cache.cc(206): error C7555: use of designated initializers requires at least '/std:c++20'
tensorflow/lite/delegates/xnnpack/weight_cache.cc(210): error C7555: use of designated initializers requires at least '/std:c++20'
tensorflow/lite/delegates/xnnpack/weight_cache.cc(380): error C7555: use of designated initializers requires at least '/std:c++20'
tensorflow/lite/delegates/xnnpack/weight_cache.cc(383): error C7555: use of designated initializers requires at least '/std:c++20'
tensorflow/lite/delegates/xnnpack/weight_cache.cc(518): error C7555: use of designated initializers requires at least '/std:c++20'
```

This was an easy fix by changing the lines 389 and 390 in .bazelrc from
```
389     build:windows --cxxopt=/std:c++17
390     build:windows --host_cxxopt=/std:c++17
```
to
```
389     build:windows --cxxopt=/std:c++20
390     build:windows --host_cxxopt=/std:c++20
```
Now I came pretty far with the compilation until bazel tried to compile the file "sip_hash.cc". Now it throws this error:

```
ERROR: C:/users/ralle/_bazel_ralle/xv6zejqw/external/highwayhash/BUILD.bazel:111:11: Compiling highwayhash/sip_hash.cc failed: (Exit 2): cl.exe failed: error executing command (from target @highwayhash//:sip_hash)

[...]

# Configuration: 3d8ee62d8d62b08774dc7f4e97d832e9e7d26d50ed850f9d5b41083047ae81d8
# Execution platform: @local_execution_config_platform//:platform
external/highwayhash\highwayhash/state_helpers.h(49): error C2760: syntax error: 'alignas' was unexpected here; expected 'declaration'
external/highwayhash\highwayhash/state_helpers.h(64): error C2065: 'final_packet': undeclared identifier
external/highwayhash\highwayhash/state_helpers.h(65): error C2065: 'final_packet': undeclared identifier
external/highwayhash\highwayhash/state_helpers.h(67): error C2065: 'final_packet': undeclared identifier
Target //tensorflow/tools/pip_package:wheel failed to build
INFO: Elapsed time: 2.067s, Critical Path: 0.55s
INFO: 22 processes: 17 internal, 5 local.
FAILED: Build did NOT complete successfully
```

### Standalone code to reproduce the issue

Changed lines in .bazelrc:
```
389    build:windows --cxxopt=/std:c++20          
390    build:windows --host_cxxopt=/std:c++20     
```

configure.py:
```
You have bazel 6.5.0 installed.
Please specify the location of python. [Default is C:\Python312\python.exe]: Default

Please input the desired Python library path to use.  Default is [C:\Python312\Lib\site-packages]: Default

Do you want to use Clang to build TensorFlow? [Y/n]: N

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]: Default

 Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]: Y

Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: N
```

Start of compilation in console:
```
C:\tensorflow>bazel build --config=opt --repo_env=TF_PYTHON_VERSION=3.12 //tensorflow/tools/pip_package:wheel --repo_env=WHEEL_NAME=tensorflow_cpu
```

### Relevant log output

```
ERROR: C:/users/ralle/_bazel_ralle/xv6zejqw/external/highwayhash/BUILD.bazel:111:11: Compiling highwayhash/sip_hash.cc failed: (Exit 2): cl.exe failed: error executing command (from target @highwayhash//:sip_hash)

[...]

# Configuration: 3d8ee62d8d62b08774dc7f4e97d832e9e7d26d50ed850f9d5b41083047ae81d8
# Execution platform: @local_execution_config_platform//:platform
external/highwayhash\highwayhash/state_helpers.h(49): error C2760: syntax error: 'alignas' was unexpected here; expected 'declaration'
external/highwayhash\highwayhash/state_helpers.h(64): error C2065: 'final_packet': undeclared identifier
external/highwayhash\highwayhash/state_helpers.h(65): error C2065: 'final_packet': undeclared identifier
external/highwayhash\highwayhash/state_helpers.h(67): error C2065: 'final_packet': undeclared identifier
Target //tensorflow/tools/pip_package:wheel failed to build
INFO: Elapsed time: 2.067s, Critical Path: 0.55s
INFO: 22 processes: 17 internal, 5 local.
FAILED: Build did NOT complete successfully
```

**Comment by sushreebarsa** [comment]
@Ralle1998 Could you try cleaning your Bazel build directory and rebuilding the project. Sometimes cached files can cause compilation issues.

**Comment by Ralle1998** [comment]
@sushreebarsa  Thanks for the answer! I cleaned the directory multiple times by using the command "bazel clean" and "bazel clean --expunge" and still have the same error.

**Comment by sushreebarsa** [comment]
@Ralle1998 Thank you for the confirmation. Could you please search for header files included in state_helpers.h or other relevant files that might define final_packet. Also ensure the correct header file is included in the compilation process for `highwayhash/sip_hash.cc` using `#include` directives.
Thank you!

**Comment by DankMemes4President** [comment]
any updates on this? I am facing the exact same issue trying to build it for cpp. Is their a specific version of tensorflow that I can revert back to maybe?

**Comment by Ralle1998** [comment]
@DankMemes4President Sadly no. I guess this thread is dead now. I don't know if there's an earlier version to revert. I honestly just used the Python API in the end and called it in my C++ Programm with the help of python.h. It worked nicely and I didn't had to rewrite too much, but it's still a shame, that there's still no answer.

**Comment by mraunak** [comment]
Hi @Ralle1998, by default, TensorFlow uses Clang Compiler. Please refer to the steps in https://www.tensorflow.org/install/source_windows to build using clang. If it is necessary to use MSVC, try upgrading to 2022 - 14.39.33519
Please let me know if the issue still persists

**Comment by brianGriifin114** [comment]
> Hi @Ralle1998, TensorFlow prefers Clang Compiler. Please refer to the steps in https://www.tensorflow.org/install/source_windows to build using clang. If it is necessary to use MSVC, try upgrading to 2022 - 14.39.33519 Please let us know if the issue still persists.

Hi, We using msvc 14.40.33807,the issue still persists.
```
# Configuration: 158dc7b267f820013108550418444ac6b0ba72f989d1ce87cc413df85a39edd1
# Execution platform: @local_execution_config_platform//:platform
external/highwayhash\highwayhash/state_helpers.h(49): error C2760: syntax error: 'alignas' was unexpected here; expected 'declaration'
external/highwayhash\highwayhash/state_helpers.h(64): error C2065: 'final_packet': undeclared identifier
external/highwayhash\highwayhash/state_helpers.h(65): error C2065: 'final_packet': undeclared identifier
external/highwayhash\highwayhash/state_helpers.h(67): error C2065: 'final_packet': undeclared identifier
```

**Comment by mraunak** [comment]
Hi @brianGriifin114, Could you please test it on the latest TensorFlow commit? I attempted to replicate it using the exact variables and commands mentioned above, and it was successful on my end

**Comment by brianGriifin114** [comment]
> [TensorFlow_build.txt](https://github.com/user-attachments/files/16566980/TensorFlow_build.txt) Hi @brianGriifin114 We've encountered similar issues with the MSVC compilers, which is why we switched to using Clang. Resolving this problem with MSVC would require changes in several files external to TensorFlow. To avoid this, please use the Clang compiler when building TensorFlow which we maintain regularly.

Thanks for your reply, because we are the MSVC test team, we use the build of the open source project to test whether the compiler has any problems. So we stick to the MSVC build. What is the changes in several files external to TensorFlow you mentioned, and how can I apply it?

**Comment by mraunak** [comment]
Hi @brianGriifin114 
**Error 1:**

tensorflow/compiler/mlir/quantization/stablehlo/passes/insert_calibration_statistics_saver.cc(183): error C7555: use of designated initializers requires at least '/std:c++20'

change https://github.com/tensorflow/tensorflow/blob/master/.bazelrc#L391 to fix the above error. Make sure that it works well with Clang as well.

command to build TF using Clang
bazel --output_user_root=c:\ build --config=win_clang --repo_env=TF_PYTHON_VERSION=3.11 --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:wheel

**Fix the error below**

external/highwayhash\highwayhash/state_helpers.h(49): error C2760: syntax error: 'alignas' was unexpected here; expected 'declaration'
external/highwayhash\highwayhash/state_helpers.h(64): error C2065: 'final_packet': undeclared identifier
external/highwayhash\highwayhash/state_helpers.h(65): error C2065: 'final_packet': undeclared identifier
external/highwayhash\highwayhash/state_helpers.h(67): error C2065: 'final_packet': undeclared identifier

highwayhash is external to TensorFlow

Clone highwayhash 

fix the errors in state_helpers.h
create a patch file using command --> git diff > your_patch_name.patch
add this patch file to tensorflow\third_party\highwayhash
add the patch to workspace/bzl in highwayhash folder similar to https://github.com/tensorflow/tensorflow/blob/master/third_party/absl/workspace.bzl#L47

Please let me know if need any further information from my end.

**Comment by brianGriifin114** [comment]
> Hi @brianGriifin114 **Error 1:**
> 
> tensorflow/compiler/mlir/quantization/stablehlo/passes/insert_calibration_statistics_saver.cc(183): error C7555: use of designated initializers requires at least '/std:c++20'
> 
> change https://github.com/tensorflow/tensorflow/blob/master/.bazelrc#L391 to fix the above error. Make sure that it works well with Clang as well.
> 
> command to build TF using Clang bazel --output_user_root=c:\ build --config=win_clang --repo_env=TF_PYTHON_VERSION=3.11 --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:wheel
> 
> **Fix the error below**
> 
> external/highwayhash\highwayhash/state_helpers.h(49): error C2760: syntax error: 'alignas' was unexpected here; expected 'declaration' external/highwayhash\highwayhash/state_helpers.h(64): error C2065: 'final_packet': undeclared identifier external/highwayhash\highwayhash/state_helpers.h(65): error C2065: 'final_packet': undeclared identifier external/highwayhash\highwayhash/state_helpers.h(67): error C2065: 'final_packet': undeclared identifier
> 
> highwayhash is external to TensorFlow
> 
> Clone highwayhash (https://github.com/google/highwayhash)
> 
> fix the errors in state_helpers.h create a patch file using command --> git diff > patch_name_file.patch add this patch file to tensorflow\third_party\highwayhash add the patch to workspace/bzl in highwayhash folder similar to https://github.com/tensorflow/tensorflow/blob/master/third_party/absl/workspace.bzl#L47
> 
> Please let me know if any further information or help is needed from my end.

Thanks, this is very helpful！

**Comment by rishik1001** [comment]
> [TensorFlow_build.txt](https://github.com/user-attachments/files/16566980/TensorFlow_build.txt) Hi @brianGriifin114 We've encountered similar issues with the MSVC compilers, which is why we switched to using Clang. Resolving this problem with MSVC would require changes in several files external to TensorFlow. To avoid this, please use the Clang compiler when building TensorFlow which we maintain regularly.

Why version of clang to be used ?
Because build with clang 17.0.6 is giving errors

**Comment by mraunak** [comment]
Hi @rishik1001 , Please try compiling the code with Clang 18.1.8. If the issue persists, kindly create a separate GitHub issue, providing all relevant details, including error messages and steps to reproduce.

**Comment by rishik1001** [comment]
> Hi @rishik1001 , Please try compiling the code with Clang 18.1.8. If the issue persists, kindly create a separate GitHub issue, providing all relevant details, including error messages and steps to reproduce.

I am actually building flex delegates for tensorflow 2.17.0, as mentioned above I used clang 18.1.8 below errors are shown
ERROR: C:/rishik/tensorflow-2.17.0/tensorflow/core/kernels/BUILD:5616:18: Compiling tensorflow/core/kernels/string_to_hash_bucket_op.cc failed: (Exit 1): clang-cl.exe failed: error executing command (from target //tensorflow/core/kernels:string_to_hash_bucket_op)
  cd /d C:/rishik/bazel/5lnkvv5w/execroot/org_tensorflow
  SET CLANG_COMPILER_PATH=C:Program FilesLLVMbinclang.exe
    SET INCLUDE=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\ATLMFC\include;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include;C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt;C:\Program Files\LLVM\lib\clang\18\include
    SET PATH=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\HostX64\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VC\VCPackages;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\bin\Roslyn;C:\Program Files\Microsoft Visual Studio\2022\Community\Team Tools\DiagnosticsHub\Collector;C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\\x64;C:\Program Files (x86)\Windows Kits\10\bin\\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\\MSBuild\Current\Bin\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\;;C:\WINDOWS\system32;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VC\Linux\bin\ConnectionManagerExe;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\vcpkg
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C:/Python311/python.exe
    SET PYTHON_LIB_PATH=C:/Python311/Lib/site-packages
    SET TEMP=C:\Users\SAIRIS~1\AppData\Local\Temp
    SET TF2_BEHAVIOR=1
    SET TMP=C:\Users\SAIRIS~1\AppData\Local\Temp
    SET VSLANG=1033
  C:\Program Files\LLVM\bin\clang-cl.exe @bazel-out/x64_windows-opt/bin/tensorflow/core/kernels/_objs/string_to_hash_bucket_op/string_to_hash_bucket_op.obj.params
# Configuration: 33ef1b035fadda77415a92f42f21562c50e8db8c1bcccd1e45613733544c9ae3
# Execution platform: //tensorflow/tools/toolchains/win:x64_windows-clang-cl
In file included from tensorflow/core/kernels/string_to_hash_bucket_op.cc:19:
In file included from .\tensorflow/core/platform/strong_hash.h:19:
In file included from external/highwayhash\highwayhash/sip_hash.h:26:
external/highwayhash\highwayhash/state_helpers.h(49,41): error: 'alignas' attribute cannot be applied to types
   49 |   char final_packet[State::kPacketSize] HH_ALIGNAS(32) = {0};
      |                                         ^
external/highwayhash\highwayhash/compiler_specific.h(52,30): note: expanded from macro 'HH_ALIGNAS'
   52 | #define HH_ALIGNAS(multiple) alignas(multiple)  // C++11
      |                              ^
1 error generated.
Target //tensorflow/lite/delegates/flex:tensorflowlite_flex failed to build
[3,025 / 5,333] checking cached actions
INFO: Elapsed time: 2045.524s, Critical Path: 115.42s
INFO: 3025 processes: 1057 internal, 1968 local.
FAILED: Build did NOT complete successfully

The command used is bazel --output_user_root=C:/Rishik/Bazel build --config=win_clang --repo_env=TF_PYTHON_VERSION=3.11 --config=monolithic tensorflow/lite/delegates/flex:tensorflowlite_flex

**Comment by rishik1001** [comment]
I have used tensorflow 2.17.0 for building tensorflow flex delegates. In return, it was a dll file of size 200mb.
Are there any chances of reducing the size of the dll?

**Comment by mraunak** [comment]
Hi @rishik1001, were you able to fix the issue you faced while compiling the Bazel job? is the size of tensorflowlite_flex.dll 200mb?

**Comment by rishik1001** [comment]
> Hi @rishik1001, were you able to fix the issue you faced while compiling the Bazel job? is the size of tensorflowlite_flex.dll 200mb?

Yeah, the issue while compiling is fixed. But the dll size is 200mb.
