### ISSUE TITLE
AttributeError: module 'tensorflow.contrib.cudnn_rnn' has no attribute 'CudnnLSTM'

### ISSUE THREAD

**Issue by boche** [tensorflow/tensorflow#9475]
I am experiencing this when I call tf.contrib.cudnn_rnn.CudnnLSTM:
`AttributeError: module 'tensorflow.contrib.cudnn_rnn' has no attribute 'CudnnLSTM'`

This happens with 1.1.0-rc2, 1.0.1 and probably 1.0.0. Previously, I was using version 0.12.head, and everything is fine. I suspect this is because the model was not exposed in [tensorflow/contrib/cudnn_rnn/\_\_init__.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cudnn_rnn/__init__.py) in an earlier version.

Even though this is fixed in this [commit]( https://github.com/tensorflow/tensorflow/commit/986d337e7da04de627218c12e20be1e3abbf6097), it's somehow not included in 1.1.0-rc2. In 1.1.0-rc2, when I look at the \_\_init__.py, it's still like this:

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

from tensorflow.contrib.cudnn_rnn.python.ops.cudnn_rnn_ops import CudnnGRU
from tensorflow.contrib.cudnn_rnn.python.ops.cudnn_rnn_ops import CudnnLSTM
from tensorflow.contrib.cudnn_rnn.python.ops.cudnn_rnn_ops import CudnnRNNRelu
from tensorflow.contrib.cudnn_rnn.python.ops.cudnn_rnn_ops import CudnnRNNTanh
from tensorflow.contrib.cudnn_rnn.python.ops.cudnn_rnn_ops import RNNParamsSaveable

from tensorflow.python.util.all_util import remove_undocumented
remove_undocumented(__name__)
```

Please fix this in the official release of 1.1 version.

For the reference, my 1.1.0-rc2 is installed from this:
https://pypi.python.org/packages/fd/1a/b6e78223c8e05a8bdee8f9bb20d4926f81db50e583632a1cde6e5b5ec2f0/tensorflow-1.1.0-cp35-cp35m-manylinux1_x86_64.whl#md5=fc5ed08795ef5afa60b48ae916def79c

**Comment by aselle** [comment]
@zhangyaobit, could you take a look? I'm not sure if there is any intentional API changes here.

**Comment by zhangyaobit** [comment]
1.1 has been released: https://github.com/tensorflow/tensorflow/releases/tag/v1.1.0

Looks like the fix is not in.

**Comment by boche** [comment]
okay, but this still needs to be fixed.

**Comment by zhangyaobit** [comment]
Yes, thanks, boche! It turned out release 1.1 was cut just 3 days before the fix. 

The fix will be part of the next release, which will be in the next two months or so and rc0 in about one month.

In the meantime, you may consider using the nightly build here: https://github.com/tensorflow/tensorflow

**Comment by dengyuning** [comment]
I am experiencing this when I call tf.contrib.cudnn_rnn.CudnnLSTM with Python3.5.2 and tensorflow1.2.1:
`AttributeError:module 'tensorflow.contrib.cudnn_rnn' has no attribute 'CudnnLSTM'` 
while the above code works fine with Python3.6 and tensorflow1.2.1.
I checked tensorflow/contrib/cudnn_rnn/__init__.py and found there are some differences.
In `__init__.py` under tensorflow/contrib/cudnn with python3.6, there reads

    from tensorflow.contrib.cudnn_rnn.python.ops.cudnn_rnn_ops import CudnnLSTM
    from tensorflow.contrib.cudnn_rnn.python.ops.cudnn_rnn_ops import CudnnRNNRelu
    from tensorflow.contrib.cudnn_rnn.python.ops.cudnn_rnn_ops import CudnnRNNTanh
    from tensorflow.contrib.cudnn_rnn.python.ops.cudnn_rnn_ops import RNNParamsSaveable
    from tensorflow.python.util.all_util import remove_undocumented
    _allowed_symbols = [
    "CudnnGRU",
    "CudnnLSTM",
    "CudnnRNNRelu",
    "CudnnRNNTanh",
    "RNNParamsSaveable",
    ]

    remove_undocumented(__name__)
while in `__init__.py` under tensorflow/contrib/cudnn with python3.5.2, statement 
 ` _allowed_symbols = [
    "CudnnGRU",
    "CudnnLSTM",
    "CudnnRNNRelu",
    "CudnnRNNTanh",
    "RNNParamsSaveable",
    ]`
is lost.
