### ISSUE TITLE
Bulding Tensorflow Lite on ubuntu 16.04 (GCC 5.4.0)

### ISSUE THREAD

**Issue by HedgeHao** [tensorflow/tensorflow#56817]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

tf 2.8.0

### Custom Code

No

### OS Platform and Distribution

Ubuntu 16.04

### Mobile device

Ubuntu 16.04

### GCC/Compiler version

5.4.0

### Current Behaviour?

I follow the [tutorial](https://www.tensorflow.org/lite/guide/build_cmake) to build tensorflow lite on Ubuntu 16.04. The error shows 

```shell
xnnpack/src/f16-dwconv/gen/up8x25-minmax-neonfp16arith-acc2.c:1:0: error: unknown value 'armv8.2-a+fp16' for -march
```

I know I have a old gcc environment. But I have no choice. Is there any way to build on Ubuntu 16.04 using gcc 5.4.0?

### Standalone code to reproduce the issue

Use Ubuntu 16.04 `apt update` and `apt upgrade -y` then follow [tutorial](https://www.tensorflow.org/lite/guide/build_cmake) to build tensorflow lite

### Relevant log output

```shell
xnnpack/src/f16-dwconv/gen/up8x25-minmax-neonfp16arith-acc2.c:1:0: error: unknown value 'armv8.2-a+fp16' for -march
```
</details>

**Comment by mohantym** [comment]
@HedgeHao !
I am afraid to say that GCC 5.4 is not compatible with TF 2.8 . I guess you have to find a way to upgrade you GCC version to 7.3.1 . Could you post this on TF Forum for further assistance. 
Thank you!
