### ISSUE TITLE
Fail to build on Ubuntu 24.10

### ISSUE THREAD

**Issue by drhaozhong** [tensorflow/tensorflow#90459]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

master

### Custom code

No

### OS platform and distribution

Ubuntu 24.10

### Python version

3.12

### Bazel version

7.4.1

### CUDA/cuDNN version

12.6

### Current behavior?

bazel build //tensorflow/tools/pip_package:wheel --repo_env=WHEEL_NAME=tf_nightly --config=cuda_wheel --copt=-Wno-gnu-offsetof-extensions

The error message is as follows:

clang failed: error executing CppCompile command (from target @@upb//:upb) /usr/lib/llvm-19/bin/clang -MD -MF bazel-out/k8-opt/bin/external/upb/_objs/upb/upb.pic.d '-frandom-seed=bazel-out/k8-opt/bin/external/upb/_objs/upb/upb.pic.o' -iquote external/upb -iquote ... (remaining 43 arguments skipped)
external/upb/upb/upb.c:192:10: error: defining a type within 'offsetof' is a C23 extension [-Werror,-Wc23-extensions]
  192 |   n &= ~(upb_alignof(upb_arena) - 1);
      |          ^~~~~~~~~~~~~~~~~~~~~~
external/upb/upb/upb.c:183:37: note: expanded from macro 'upb_alignof'
  183 | #define upb_alignof(type) offsetof (struct { char c; type member; }, member)
      |                                     ^~~~~~
/usr/lib/llvm-19/lib/clang/19/include/__stddef_offsetof.h:16:43: note: expanded from macro 'offsetof'
   16 | #define offsetof(t, d) __builtin_offsetof(t, d)
      |                                           ^
1 error generated.

### Standalone code to reproduce the issue

```shell
No code
```

### Relevant log output

```shell

```

**Comment by Venkat6871** [comment]
Hi @drhaozhong ,
Apologies for the delay, and thank you for raising your concern here. The main cause of your issue appears to be a version compatibility mismatch. Could you please try using Clang version 18.1.8? If the issue still persists, feel free to let us know we will be happy to assist you further. I am attaching the official [documentation](https://www.tensorflow.org/install/source#cpu) for your reference. Please ensure all compatibility requirements are met to avoid build failures.

Thank you!

**Comment by drhaozhong** [comment]
A update. I change clang to 18.1.8. The previous error disappears. However, I encounter another error:

gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 212 arguments skipped)
In file included from /usr/include/c++/14/memory:78,
                 from tensorflow/compiler/mlir/lite/transforms/default_quant_params.cc:16:
/usr/include/c++/14/bits/unique_ptr.h: In instantiation of 'std::__detail::__unique_ptr_t<_Tp> std::make_unique(_Args&& ...) [with _Tp = mlir::TFL::{anonymous}::DefaultQuantParamsPass; _Args = {const mlir::TFL::DefaultQuantParamsPassOptions&}; __detail::__unique_ptr_t<_Tp> = __detail::__unique_ptr_t<mlir::TFL::{anonymous}::DefaultQuantParamsPass>]':
tensorflow/compiler/mlir/lite/transforms/default_quant_params.cc:249:50:   required from here
  249 |   return std::make_unique<DefaultQuantParamsPass>(options);
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
/usr/include/c++/14/bits/unique_ptr.h:1076:30: error: call of overloaded 'DefaultQuantParamsPass(const mlir::TFL::DefaultQuantParamsPassOptions&)' is ambiguous
 1076 |     { return unique_ptr<_Tp>(new _Tp(std::forward<_Args>(__args)...)); }
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from tensorflow/compiler/mlir/lite/transforms/default_quant_params.cc:52:
bazel-out/k8-opt/bin/tensorflow/compiler/mlir/lite/transforms/passes.h.inc:162:3: note: candidate: 'mlir::TFL::{anonymous}::impl::DefaultQuantParamsPassBase<DerivedT>::DefaultQuantParamsPassBase(mlir::TFL::DefaultQuantParamsPassOptions) [with DerivedT = mlir::TFL::{anonymous}::DefaultQuantParamsPass]'
  162 |   DefaultQuantParamsPassBase(DefaultQuantParamsPassOptions options) : DefaultQuantParamsPassBase() {
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~
tensorflow/compiler/mlir/lite/transforms/default_quant_params.cc:57:37: note:   inherited here
   57 |   using DefaultQuantParamsPassBase::DefaultQuantParamsPassBase;
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~
tensorflow/compiler/mlir/lite/transforms/default_quant_params.cc:66:12: note: candidate: 'mlir::TFL::{anonymous}::DefaultQuantParamsPass::DefaultQuantParamsPass(const mlir::TFL::DefaultQuantParamsPassOptions&)'
   66 |   explicit DefaultQuantParamsPass(
      |            ^~~~~~~~~~~~~~~~~~~~~~
tensorflow/compiler/mlir/lite/transforms/default_quant_params.cc:54:7: note: candidate: 'mlir::TFL::{anonymous}::DefaultQuantParamsPass::DefaultQuantParamsPass(const mlir::TFL::{anonymous}::DefaultQuantParamsPass&)'
   54 | class DefaultQuantParamsPass
      |       ^~~~~~~~~~~~~~~~~~~~~~
tensorflow/compiler/mlir/lite/transforms/default_quant_params.cc:54:7: note: candidate: 'mlir::TFL::{anonymous}::DefaultQuantParamsPass::DefaultQuantParamsPass(mlir::TFL::{anonymous}::DefaultQuantParamsPass&&)' (deleted)
cc1plus: note: unrecognized command-line option '-Wno-gnu-offsetof-extensions' may have been intended to silence earlier diagnostics
Target //tensorflow/tools/pip_package:wheel failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 4275.864s, Critical Path: 432.16s
INFO: 16480 processes: 587 internal, 15893 local.
ERROR: Build did NOT complete successfully

My gcc version  is 14.2.0

**Comment by Kayyuri** [comment]
Hi @drhaozhong,Apologies for the delay, and thank you for your patience.

This issue is likely caused by GCC 14.2.0 being more strict with C++ rules, which leads to ambiguity between two constructors in `default_quant_params.cc`. Could you please try using a different/consistent compiler version to avoid this issue?
Thanks!
