### ISSUE TITLE
module 'tensorflow.python._pywrap_tensorflow_internal' has no attribute 'TFE_NewContextOptions'

### ISSUE THREAD

**Issue by magicmutal** [tensorflow/tensorflow#16981]
I have followed the TensorFlow tutorial, "[Simple Audio Recognition](https://www.tensorflow.org/versions/master/tutorials/audio_recognition)"

When I was running **train.py**, I got this error message:

```
AttributeError                            Traceback (most recent call last)
<ipython-input-4-61266873bc5f> in <module>()
     77 import numpy as np
     78 from six.moves import xrange  # pylint: disable=redefined-builtin
---> 79 import tensorflow as tf
     80 
     81 import input_data

c:\users\jinsu\appdata\local\programs\python\python36\lib\site-packages\tensorflow\__init__.py in <module>()
     22 
     23 # pylint: disable=wildcard-import
---> 24 from tensorflow.python import *
     25 # pylint: enable=wildcard-import
     26 

c:\users\jinsu\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\__init__.py in <module>()
     47 import numpy as np
     48 
---> 49 from tensorflow.python import pywrap_tensorflow
     50 
     51 # Protocol buffers

c:\users\jinsu\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>()
     56     sys.setdlopenflags(_default_dlopen_flags | ctypes.RTLD_LOCAL)
     57 
---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
     59   from tensorflow.python.pywrap_tensorflow_internal import __version__
     60   from tensorflow.python.pywrap_tensorflow_internal import __git_version__

c:\users\jinsu\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in <module>()
    102 def TFE_NewContextOptions():
    103     return _pywrap_tensorflow_internal.TFE_NewContextOptions()
--> 104 TFE_NewContextOptions = _pywrap_tensorflow_internal.TFE_NewContextOptions
    105 
    106 def TFE_ContextOptionsSetConfig(options, proto, proto_len, status):

AttributeError: module 'tensorflow.python._pywrap_tensorflow_internal' has no attribute 'TFE_NewContextOptions'
```
So, I checked out **pywrap_tensorflow_internal.py** in the pyhton directory. 
This is the part of **pywrap_tensorflow_internal.py** that defines TFE_NewContextOptions.

```
def TFE_ContextOptionsSetConfig(options, proto, proto_len, status):
    return _pywrap_tensorflow_internal.TFE_ContextOptionsSetConfig(options, proto, proto_len, status)
TFE_ContextOptionsSetConfig = _pywrap_tensorflow_internal.TFE_ContextOptionsSetConfig
TFE_DEVICE_PLACEMENT_EXPLICIT = _pywrap_tensorflow_internal.TFE_DEVICE_PLACEMENT_EXPLICIT
TFE_DEVICE_PLACEMENT_WARN = _pywrap_tensorflow_internal.TFE_DEVICE_PLACEMENT_WARN
TFE_DEVICE_PLACEMENT_SILENT = _pywrap_tensorflow_internal.TFE_DEVICE_PLACEMENT_SILENT
TFE_DEVICE_PLACEMENT_SILENT_FOR_INT32 = _pywrap_tensorflow_internal.TFE_DEVICE_PLACEMENT_SILENT_FOR_INT32
```

**Comment by magicmutal** [comment]
I have figured out what the problem was!!!
I didn't upgrade the tensorflow version

Thanks a lot.

**Comment by fay0505** [comment]
@magicmutal  I met with the same problem after I upgrade tensorflow from 1.4 to 1.7 .  How to deal with it? Go back to the previous version?

**Comment by sxlprince** [comment]
could you please tell me how to deal with the problem?I upgraded tf to 1.7 and i have the same problem.

**Comment by zwei2007** [comment]
I updated my tensorflow from version 1.4.0 to 1.11.0. After that, when I tried "import tensorflow as tf", I ran into following problem:

File "C:\Users\MyName\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 96, in <module>
    TFE_NewContextOptions = _pywrap_tensorflow_internal.TFE_NewContextOptions
AttributeError: module '_pywrap_tensorflow_internal' has no attribute 'TFE_NewContextOptions'

May I know if you could give me any clue to sort this out? Thanks!

**Comment by manupillai308** [comment]
I also got the same problem after installing tf_nightly using "pip install tf_nightly" with administrator privileges on windows 10. There was another related issue that while installing tf_nightly some WIN ERROR 5 was raised for which the problem stated here occured. I got to know that it was because of an active session running tensorflow. I solved it by shutting down any python programs currently running and reinstalling tensorflow and tf_nightly and it worked like a charm. I hope it helps someone with the same issue.

**Comment by usingare** [comment]
@zwei2007 @manupillai308 

Consider adding the installation directory (usually **"Python36\Scripts"**) to your environment variables. 

It should solve the issue.

**Comment by ritika26** [comment]
I am also facing  the same problem after I upgrade tensorflow   1.12.0. Please suggest how to fix this issue?

**Comment by china-zhangdj** [comment]
谢谢

**Comment by jasonComing** [comment]
I had similar issue.  My problem was that my tensorflow and tensorflow-gpu installation was mixing up.  To solve this, I ran `pip uninstall tensorflow tensorflow-gpu` and removed those tensorflow folders manually in `python36\lib\site-packages`.  Then, reinstall again.

**Comment by Meoooww** [comment]
so how to solved this problem? upgrade seems not useful for others
