### ISSUE TITLE
Problem with Keras sparse_categorical_crossentropy

### ISSUE THREAD

**Issue by Hvass-Labs** [tensorflow/tensorflow#17150]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary (pip install)
- **TensorFlow version (use command below)**: 1.5.0 (Keras 2.1.2-tf)
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: NA
- **GCC/Compiler version (if compiling from source)**: NA
- **CUDA/cuDNN version**: Can't remember.
- **GPU model and memory**: GTX 1070
- **Exact command to reproduce**: See below.

### Background

This issue seems to be specifically about Keras with TensorFlow so I have posted it here.

I have a Keras model for doing Machine Translation of human languages. It has an encoder and decoder each of which use the `Embedding` and `GRU` layers from Keras. The output of the decoder is a one-hot encoded array.

My data-set is from Europarl so it is very large already and converting the target-data from integer-tokens to one-hot-encoded labels would be extremely wasteful and take many GB of memory.

One solution would be to write my own data-generator and only convert integer-tokens to one-hot-labels for a batch at a time. But that's not a very elegant solution.

The correct solution is of course to use a sparse version of the crossentropy-loss which automatically converts the integer-tokens to a one-hot-encoded label for comparison to the model's output. Keras' has a built-in loss-function for doing exactly this called `sparse_categorical_crossentropy`. However, it doesn't seem to work as intended.

### Error

The following shows the essential parts of the code.

    # (Omitted code for building neural network ...)

    # Output of the decoder-part of the neural network.
    decoder_dense = Dense(num_words,
                          activation='softmax',
                          name='decoder_output')
    decoder_output = decoder_dense(decoder_gru_output)

    model = Model(inputs=[encoder_input, decoder_input],
                  outputs=[decoder_output])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy')

    model.fit(x=x_data, y=y_data, batch_size=128, epochs=3)

Everything runs fine except `model.fit()` at the end which gives this error:

    ValueError: Error when checking target: expected decoder_output to have 3 dimensions, but got array with shape (20000, 67)

This is the shape of the model's output:

    >>> decoder_output.get_shape()
    TensorShape([Dimension(None), Dimension(None), Dimension(10000)])

This is the shape of the target-data, which is a 2-dim array of integer-values:

    y_data['decoder_output'].shape
    >>> (20000, 67)

Note that I only allow sequences of length 67 for the decoder's output.

### Working Solution

We can use TensorFlow's implementation of sparse cross-entropy, which seems to work as intended.

First we need to have a linear activation on the output of the decoder:

    decoder_dense = Dense(num_words,
                          activation='linear', # NOTE: changed from 'softmax'
                          name='decoder_output')

Then we need a wrapper-function for the loss that is compatible with Keras:

    def sparse_loss(y_true, y_pred):
        return tf.nn.sparse_softmax_cross_entropy_with_logits(labels=y_true,
                                                              logits=y_pred)

Then we need to create a placeholder variable for the batch of target-values. Once again I only allow sequences of length 67 (this is of course a variable in my own code).

    decoder_target = tf.placeholder(dtype='int32', shape=(None, 67))

    model_train.compile(optimizer='adam,
                        loss=sparse_loss,
                        target_tensors=[decoder_target])

This works fine and we can train it by calling:

    model.fit(x=x_data, y=y_data, batch_size=128, epochs=3)

Maybe Keras should use TensorFlow's sparse-cross-entropy more directly, because it seems to handle higher-dim data better?

### Documentation

Looking at the implementation of `sparse_categorical_crossentropy` in Keras there is actually some reshaping going on there, but the doc-string doesn't make clear what is assumed of the input/output dims and when/how reshaping is supposed to be done, so it's impossible to know whether it is a bug or a feature I am experiencing, and how to deal with it properly.

The doc-string needs to be made more clear by someone who understands the intention of this code.

Furthermore, the doc-string needs to be "exported" somehow to the online docs because it is not shown here: https://keras.io/losses/#sparse_categorical_crossentropy

**Comment by asimshankar** [comment]
Thanks for the report.
CC @fchollet @anj-s for comment.

**Comment by Hvass-Labs** [comment]
Furthermore, I'm not quite sure whether my custom `sparse_loss()` function should reduce the loss-values from a batch-tensor to a single scalar value, e.g. like this:

    def sparse_loss(y_true, y_pred):
        foo = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=y_true,
                                                             logits=y_pred)
        return tf.reduce_mean(foo)

Keras' `fit()` function has a parameter `sample_weight` which should calculate the weighted average of the loss across the batch, but I'm not sure it does that when I provide both a custom loss function and `target_tensors`.

These are generally quite confusing aspects of the Keras API. I've looked in the source-code but it's really hard to understand because it's so dense and has practically no comments.

**Comment by Hvass-Labs** [comment]
I have a working example of my custom loss-function which is a work-around for the bug in Keras. Search for `sparse_cross_entropy`:

https://github.com/Hvass-Labs/TensorFlow-Tutorials/blob/master/21_Machine_Translation.ipynb

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by fchollet** [comment]
@Hvass-Labs : 

your workaround will be compatible with sample weighting, if you use `tf.reduce_mean(foo, axis=-1)` instead of `tf.reduce_mean(foo)`.

Thanks for the bug report. I verified the issue. Here is a reproducible example:

```python
import keras  # also works for tf.keras
import numpy as np

model = keras.Sequential()
model.add(keras.layers.Dense(10, input_shape=(5, 6)))

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy')

x_data = np.random.random((32, 5, 6))
y_data = np.random.randint(0, 9, size=(32,))

model.fit(x=x_data, y=y_data, batch_size=16, epochs=3)
```

I will look into a fix.

**Comment by johntrimble** [comment]
For seq2seq at least, I think the suggested workaround with a custom `sparse_loss` function should not return a scalar (i.e. don't use `reduce_mean`). The `weighted_masked_objective` decorator will take care of that. If the loss function returns a scalar, then masking will not work appropriately. I also don't think using `tf.reduce_mean(foo, axis=-1)` will work either as it will change the shape from (samples, time-steps) to (samples) also breaking masking.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by johntrimble** [comment]
@fchollet I'm not sure if you've actually started on this ticket yet, but I have been reading through the Keras code lately and wouldn't mind taking a stab at addressing this issue if that would be helpful. I'm currently rolling with a similar workaround so I have a vested interest in getting this resolved.

**Comment by Krumpet** [comment]
The Keras objectives documentation says to expand the dimensions of the labels using `y=np.expand_dims(y, -1)`, so I've done this to both my data (X) and my labels and it seems to be running fine. Is this a possible solution or not the same problem?

**Comment by johntrimble** [comment]
@Krumpet you might be on to something here. I think our reproduction example is actually missing a steps dimension for the labels, so `y_data = np.random.randint(0, 9, size=(32,))` should really be `y_data = np.random.randint(0, 9, size=(32,5))`, giving us a reproduction example of:

```
import keras
import numpy as np

model = keras.Sequential()
model.add(keras.layers.Dense(10, input_shape=(5, 6)))

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy')

x_data = np.random.random((32, 5, 6))
y_data = np.random.randint(0, 9, size=(32,5))

model.fit(x=x_data, y=y_data, batch_size=16, epochs=3)
```

That gives the same sort of error about the shape:

```
ValueError: Error when checking target: expected dense_1 to have 3 dimensions, but got array with shape (32, 5)
```

If we expand the labels dimensions to have shape `(32, 5, 1)` like so:

```
import keras
import numpy as np

model = keras.Sequential()
model.add(keras.layers.Dense(10, input_shape=(5, 6)))

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy')

x_data = np.random.random((32, 5, 6))
y_data = np.random.randint(0, 9, size=(32,5,1))

model.fit(x=x_data, y=y_data, batch_size=16, epochs=3)
```

The error does appear to go away (with TensorFlow backend at least, I'm not up and running with Theano presently). I'm going to kick the tires a bit more and make sure this is really working and things like masking still function as we expect. If someone could check the above with Theano, that would be helpful.

**Comment by johntrimble** [comment]
I am convinced this is working. I did a little test to make sure masking is handled correctly, and all looks well:

```python
from tensorflow import keras
import numpy as np

dense_layer = keras.layers.Dense(10, activation='softmax')

model = keras.Sequential()
model.add(keras.layers.Embedding(11, 6, mask_zero=True, embeddings_initializer=keras.initializers.Constant(value=0.1)))
model.add(dense_layer)
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy')

# Set the weights for our dense layer such that each category has the same
# probability except for 1, which will have a lower probability
new_weights = []
for weight in dense_layer.get_weights():
    if weight.shape == (6,10):
        weight = np.full_like(weight, 0.1, dtype='float32')
        weight[:,1] = -2.
    new_weights.append(weight)
dense_layer.set_weights(new_weights)

# Create random dataset where each sample has a different length with 0 padding
# and none of the labels use category 1
x_data = np.zeros((32, 20))
y_data = np.zeros((32, 20, 1))
for i in range(32):
    length = np.random.randint(1, 20)
    x_data[i, 0:length] = np.random.randint(2, 10, size=length)
    y_data[i, 0:length] = np.random.randint(2, 10, size=(length, 1))

# Evaluate to get the cost
cost1 = model.evaluate(x_data, y=y_data)

# Change the 0s to 1s in the labels. If masking is handled correctly, this
# shouldn't matter as these labels will be ignored anyway. If masking is not
# handled correctly, then the cost should go up as the probability of 1 being
# the correct category is lower than any other category
y_data[y_data == 0] = 1

cost2 = model.evaluate(x_data, y=y_data)

assert cost1 == cost2
```

It is possible that there needs to be an update to the documentation to make it clearer as to what the shape of the labels should be. It is perhaps a bit counter intuitive that an extra dimension of size 1 needs to be tacked on. Code-wise though, this appears to be working.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by mobiusinversion** [comment]
@Hvass-Labs @johntrimble @fchollet any word on a fix here?  I am facing this issue currently with:

    File "/home/david/.local/lib/python3.6/site-packages/keras/engine/training.py", line 787, in _standardize_user_data exception_prefix='target')
    File "/home/david/.local/lib/python3.6/site-packages/keras/engine/training_utils.py", line 127, in standardize_input_data 'with shape ' + str(data_shape))
    
    ValueError: Error when checking target: 
    expected decoder_output to have 3 dimensions, but got array with shape (2000, 22)

I plan to one hot encode to finish the work at hand, but this feature is great and would be useful.

**Comment by johntrimble** [comment]
@mobiusinversion so I'm not sure this is actually a bug. Check my [example above](https://github.com/tensorflow/tensorflow/issues/17150#issuecomment-399776510). In particular, notice how when I change the labels from having a dimension of `(32,5)` to a dimension of `(32,5,1)` the problem goes away. You can use `expand_dims` to add that extra dimension. Let me know if that solves your problem.

**Comment by mobiusinversion** [comment]
@johntrimble that works.  This issue should probably be closed in favor of an enhancement, it is a bit of lint that adding the extra dimension is required.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 74 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by nunezpaul** [comment]
So I was having this problem and decided to look at the code for model.fit. This is the section that's giving us problems (lines 1133 - 1149 of tf 1.12.0)

```
        for output_shape, loss_fn in zip(self._feed_output_shapes,
                                         self._feed_loss_fns):
          if loss_fn is losses.sparse_categorical_crossentropy:
            if K.image_data_format() == 'channels_first':
              feed_output_shapes.append(
                  (output_shape[0], 1) + output_shape[2:])
            else:
              feed_output_shapes.append(output_shape[:-1] + (1,))
          elif (not hasattr(loss_fn, '__name__') or
                getattr(losses, loss_fn.__name__, None) is None):
            # If `loss_fn` is not a function (e.g. callable class)
            # or if it not in the `losses` module, then
            # it is a user-defined loss and we make no assumptions
            # about it.
            feed_output_shapes.append(None)
          else:
            feed_output_shapes.append(output_shape)
```


Pretty much if you're using tf.keras.losses.sparse_categorical_crossentropy then it adds an extra dimension to your shapes. This is why if you wrap tf.keras.losses.sparse_categorical_crossentropy with another function then you can bypass this extra dimension.

**Comment by srihari-humbarwadi** [comment]
```
def accuracy_seq2seq(y_true, y_pred):
    y_pred_ = K.cast(K.argmax(y_pred, axis=-1),'int32')
    correct = K.cast(K.equal(y_true, y_pred_), 'int32')
    flattened = K.flatten(correct)
    length = K.shape(flattened)[0]
    acc = tf.reduce_sum(flattened) / length
    return acc
```
i was having problems compiling the model with the default accuracy keras provides, i used this snippet along with the workaround @Hvass-Labs  provided. i can confirm it works on tf 1.12.0

**Comment by chandu8542** [comment]
@Hvass-Labs Which metrics from keras you would recommend for sparse_softmax_... loss function? I tried `sparse_categorical_accuracy` as [here](https://www.dlology.com/blog/how-to-use-keras-sparse_categorical_crossentropy/) but giving data type issue.

**Comment by kumariko** [comment]
@Hvass-Labs We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.6 which is latest stable version of TF and let us know if the issue still persists in newer versions. please check https://github.com/tensorflow/tensorflow/issues/17150#issuecomment-464426225 .Thanks!
