### ISSUE TITLE
pip subprocess to install build dependencies did not run successfully

### ISSUE THREAD

**Issue by lakpa-tamang9** [tensorflow/tensorflow#58982]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

Tf 2.3

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 20.04

### Python version

3.9.7

### Bazel version

3.1.0

### CUDA/cuDNN version

11.4/8

### GPU model and memory

NVIDIA RTX 3060 Ti

### Current Behaviour?

```shell
I am trying to build the and install Tensorflow from source. While I am able to successfully build through bazel, I am encountering issues while installing the build wheel package.

The installation is breaking wit subprocess-exited-with-error after trying to install scipy=1.4.1
```

### Standalone code to reproduce the issue

```shell
$ pip install /tmp/tensorflow_pkg/tensorflow-2.3.0-cp39-cp39-linux_x86_64.whl
```

### Relevant log output

```shell
Processing /tmp/tensorflow_pkg/tf_nightly-2.3.0-cp39-cp39-linux_x86_64.whl
Collecting termcolor>=1.1.0
  Using cached termcolor-2.1.1-py3-none-any.whl (6.2 kB)
Collecting astunparse==1.6.3
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting wrapt>=1.11.1
  Using cached wrapt-1.14.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (77 kB)
Requirement already satisfied: wheel>=0.26 in /home/intelligence/.virtualenvs/tf_dev/lib/python3.9/site-packages (from tf-nightly==2.3.0) (0.38.4)
Requirement already satisfied: six>=1.12.0 in /home/intelligence/.virtualenvs/tf_dev/lib/python3.9/site-packages (from tf-nightly==2.3.0) (1.16.0)
Collecting opt-einsum>=2.3.2
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Collecting scipy==1.4.1
  Using cached scipy-1.4.1.tar.gz (24.6 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [327 lines of output]
      Ignoring numpy: markers 'python_version == "3.5" and platform_system != "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.6" and platform_system != "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.7" and platform_system != "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.5" and platform_system == "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.6" and platform_system == "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.7" and platform_system == "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version >= "3.8" and platform_system == "AIX"' don't match your environment
      Collecting wheel
        Using cached wheel-0.38.4-py3-none-any.whl (36 kB)
      Collecting setuptools
        Using cached setuptools-65.6.3-py3-none-any.whl (1.2 MB)
      Collecting Cython>=0.29.13
        Using cached Cython-0.29.32-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (2.0 MB)
      Collecting numpy==1.17.3
        Using cached numpy-1.17.3.zip (6.4 MB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting pybind11>=2.4.0
        Using cached pybind11-2.10.2-py3-none-any.whl (222 kB)
      Building wheels for collected packages: numpy
        Building wheel for numpy (setup.py): started
        Building wheel for numpy (setup.py): finished with status 'error'
        error: subprocess-exited-with-error
      
        × python setup.py bdist_wheel did not run successfully.
        │ exit code: 1
        ╰─> [124 lines of output]
            Running from numpy source directory.
            blas_opt_info:
            blas_mkl_info:
            customize UnixCCompiler
              libraries mkl_rt not found in ['/home/intelligence/.virtualenvs/tf_dev/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            blis_info:
            customize UnixCCompiler
              libraries blis not found in ['/home/intelligence/.virtualenvs/tf_dev/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            openblas_info:
            customize UnixCCompiler
            customize UnixCCompiler
              libraries openblas not found in ['/home/intelligence/.virtualenvs/tf_dev/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            atlas_3_10_blas_threads_info:
            Setting PTATLAS=ATLAS
            customize UnixCCompiler
              libraries tatlas not found in ['/home/intelligence/.virtualenvs/tf_dev/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu/atlas', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            atlas_3_10_blas_info:
            customize UnixCCompiler
              libraries satlas not found in ['/home/intelligence/.virtualenvs/tf_dev/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu/atlas', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            atlas_blas_threads_info:
            Setting PTATLAS=ATLAS
            customize UnixCCompiler
              libraries ptf77blas,ptcblas,atlas not found in ['/home/intelligence/.virtualenvs/tf_dev/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu/atlas', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            atlas_blas_info:
            customize UnixCCompiler
            get_default_fcompiler: matching types: '['gnu95', 'intel', 'lahey', 'pg', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor']'
            customize Gnu95FCompiler
            Found executable /usr/bin/gfortran
            customize Gnu95FCompiler
            customize Gnu95FCompiler using config
            compiling '_configtest.c':
      
            /* This file is generated from numpy/distutils/system_info.py */
            void ATL_buildinfo(void);
            int main(void) {
              ATL_buildinfo();
              return 0;
            }
      
            C compiler: gcc -pthread -B /home/intelligence/anaconda3/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/intelligence/anaconda3/include -I/home/intelligence/anaconda3/include -fPIC -O2 -isystem /home/intelligence/anaconda3/include -fPIC
      
            compile options: '-c'
            gcc: _configtest.c
            gcc -pthread -B /home/intelligence/anaconda3/compiler_compat _configtest.o -L/usr/lib/x86_64-linux-gnu -lf77blas -lcblas -latlas -o _configtest
            /home/intelligence/anaconda3/compiler_compat/ld: warning: libm.so.6, needed by /usr/lib/x86_64-linux-gnu/libatlas.so, not found (try using -rpath or -rpath-link)
            /home/intelligence/anaconda3/compiler_compat/ld: /usr/lib/x86_64-linux-gnu/libatlas.so: undefined reference to `sqrtl@GLIBC_2.2.5'
            /home/intelligence/anaconda3/compiler_compat/ld: /usr/lib/x86_64-linux-gnu/libatlas.so: undefined reference to `sqrt@GLIBC_2.2.5'
            collect2: error: ld returned 1 exit status
            failure.
            removing: _configtest.c _configtest.o _configtest.o.d
            Status: 255
            Output: compiling '_configtest.c':
      
            /* This file is generated from numpy/distutils/system_info.py */
            void ATL_buildinfo(void);
            int main(void) {
              ATL_buildinfo();
              return 0;
            }
      
            C compiler: gcc -pthread -B /home/intelligence/anaconda3/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/intelligence/anaconda3/include -I/home/intelligence/anaconda3/include -fPIC -O2 -isystem /home/intelligence/anaconda3/include -fPIC
      
            compile options: '-c'
            gcc: _configtest.c
            gcc -pthread -B /home/intelligence/anaconda3/compiler_compat _configtest.o -L/usr/lib/x86_64-linux-gnu -lf77blas -lcblas -latlas -o _configtest
      
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 34, in <module>
              File "/tmp/pip-install-dzf32x9v/numpy_f29f84f3685b47618f1c97bbca81883b/setup.py", line 443, in <module>
                setup_package()
              File "/tmp/pip-install-dzf32x9v/numpy_f29f84f3685b47618f1c97bbca81883b/setup.py", line 435, in setup_package
                setup(**metadata)
              File "/tmp/pip-install-dzf32x9v/numpy_f29f84f3685b47618f1c97bbca81883b/numpy/distutils/core.py", line 137, in setup
                config = configuration()
              File "/tmp/pip-install-dzf32x9v/numpy_f29f84f3685b47618f1c97bbca81883b/setup.py", line 158, in configuration
                config.add_subpackage('numpy')
              File "/tmp/pip-install-dzf32x9v/numpy_f29f84f3685b47618f1c97bbca81883b/numpy/distutils/misc_util.py", line 1033, in add_subpackage
                config_list = self.get_subpackage(subpackage_name, subpackage_path,
              File "/tmp/pip-install-dzf32x9v/numpy_f29f84f3685b47618f1c97bbca81883b/numpy/distutils/misc_util.py", line 999, in get_subpackage
                config = self._get_configuration_from_setup_py(
              File "/tmp/pip-install-dzf32x9v/numpy_f29f84f3685b47618f1c97bbca81883b/numpy/distutils/misc_util.py", line 941, in _get_configuration_from_setup_py
                config = setup_module.configuration(*args)
              File "numpy/setup.py", line 10, in configuration
                config.add_subpackage('core')
              File "/tmp/pip-install-dzf32x9v/numpy_f29f84f3685b47618f1c97bbca81883b/numpy/distutils/misc_util.py", line 1033, in add_subpackage
                config_list = self.get_subpackage(subpackage_name, subpackage_path,
              File "/tmp/pip-install-dzf32x9v/numpy_f29f84f3685b47618f1c97bbca81883b/numpy/distutils/misc_util.py", line 999, in get_subpackage
                config = self._get_configuration_from_setup_py(
              File "/tmp/pip-install-dzf32x9v/numpy_f29f84f3685b47618f1c97bbca81883b/numpy/distutils/misc_util.py", line 941, in _get_configuration_from_setup_py
                config = setup_module.configuration(*args)
              File "numpy/core/setup.py", line 764, in configuration
                blas_info = get_info('blas_opt', 0)
              File "/tmp/pip-install-dzf32x9v/numpy_f29f84f3685b47618f1c97bbca81883b/numpy/distutils/system_info.py", line 444, in get_info
                return cl().get_info(notfound_action)
              File "/tmp/pip-install-dzf32x9v/numpy_f29f84f3685b47618f1c97bbca81883b/numpy/distutils/system_info.py", line 690, in get_info
                self.calc_info()
              File "/tmp/pip-install-dzf32x9v/numpy_f29f84f3685b47618f1c97bbca81883b/numpy/distutils/system_info.py", line 1810, in calc_info
                if getattr(self, '_calc_info_{}'.format(blas))():
              File "/tmp/pip-install-dzf32x9v/numpy_f29f84f3685b47618f1c97bbca81883b/numpy/distutils/system_info.py", line 1756, in _calc_info_atlas
                info = get_info('atlas_blas')
              File "/tmp/pip-install-dzf32x9v/numpy_f29f84f3685b47618f1c97bbca81883b/numpy/distutils/system_info.py", line 444, in get_info
                return cl().get_info(notfound_action)
              File "/tmp/pip-install-dzf32x9v/numpy_f29f84f3685b47618f1c97bbca81883b/numpy/distutils/system_info.py", line 690, in get_info
                self.calc_info()
              File "/tmp/pip-install-dzf32x9v/numpy_f29f84f3685b47618f1c97bbca81883b/numpy/distutils/system_info.py", line 1294, in calc_info
                atlas_version, atlas_extra_info = get_atlas_version(**atlas)
              File "/tmp/pip-install-dzf32x9v/numpy_f29f84f3685b47618f1c97bbca81883b/numpy/distutils/system_info.py", line 1589, in get_atlas_version
                'ATLAS_INFO', _c_string_literal(atlas_version))
              File "/tmp/pip-install-dzf32x9v/numpy_f29f84f3685b47618f1c97bbca81883b/numpy/distutils/system_info.py", line 177, in _c_string_literal
                s = s.replace('\\', r'\\')
            AttributeError: 'NoneType' object has no attribute 'replace'
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
        Running setup.py clean for numpy
        error: subprocess-exited-with-error
      
        × python setup.py clean did not run successfully.
        │ exit code: 1
        ╰─> [10 lines of output]
            Running from numpy source directory.
      
            `setup.py clean` is not supported, use one of the following instead:
      
              - `git clean -xdf` (cleans all files)
              - `git clean -Xdf` (cleans all versioned files, doesn't touch
                                  files that aren't checked into the git repo)
      
            Add `--force` to your command to use it anyway if you must (unsupported).
      
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed cleaning build dir for numpy
      Failed to build numpy
      Installing collected packages: wheel, setuptools, pybind11, numpy, Cython
        Running setup.py install for numpy: started
        Running setup.py install for numpy: finished with status 'error'
        error: subprocess-exited-with-error
      
        × Running setup.py install for numpy did not run successfully.
        │ exit code: 1
        ╰─> [133 lines of output]
            Running from numpy source directory.
      
            Note: if you need reliable uninstall behavior, then install
            with pip instead of using `setup.py install`:
      
              - `pip install .`       (from a git repo or downloaded source
                                       release)
              - `pip install numpy`   (last NumPy release on PyPi)
      
      
            blas_opt_info:
            blas_mkl_info:
            customize UnixCCompiler
              libraries mkl_rt not found in ['/home/intelligence/.virtualenvs/tf_dev/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            blis_info:
            customize UnixCCompiler
              libraries blis not found in ['/home/intelligence/.virtualenvs/tf_dev/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            openblas_info:
            customize UnixCCompiler
            customize UnixCCompiler
              libraries openblas not found in ['/home/intelligence/.virtualenvs/tf_dev/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            atlas_3_10_blas_threads_info:
            Setting PTATLAS=ATLAS
            customize UnixCCompiler
              libraries tatlas not found in ['/home/intelligence/.virtualenvs/tf_dev/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu/atlas', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            atlas_3_10_blas_info:
            customize UnixCCompiler
              libraries satlas not found in ['/home/intelligence/.virtualenvs/tf_dev/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu/atlas', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            atlas_blas_threads_info:
            Setting PTATLAS=ATLAS
            customize UnixCCompiler
              libraries ptf77blas,ptcblas,atlas not found in ['/home/intelligence/.virtualenvs/tf_dev/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu/atlas', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            atlas_blas_info:
            customize UnixCCompiler
            get_default_fcompiler: matching types: '['gnu95', 'intel', 'lahey', 'pg', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor']'
            customize Gnu95FCompiler
            Found executable /usr/bin/gfortran
            customize Gnu95FCompiler
            customize Gnu95FCompiler using config
            compiling '_configtest.c':
      
            /* This file is generated from numpy/distutils/system_info.py */
            void ATL_buildinfo(void);
            int main(void) {
              ATL_buildinfo();
              return 0;
            }
      
            C compiler: gcc -pthread -B /home/intelligence/anaconda3/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/intelligence/anaconda3/include -I/home/intelligence/anaconda3/include -fPIC -O2 -isystem /home/intelligence/anaconda3/include -fPIC
      
            compile options: '-c'
            gcc: _configtest.c
            gcc -pthread -B /home/intelligence/anaconda3/compiler_compat _configtest.o -L/usr/lib/x86_64-linux-gnu -lf77blas -lcblas -latlas -o _configtest
            /home/intelligence/anaconda3/compiler_compat/ld: warning: libm.so.6, needed by /usr/lib/x86_64-linux-gnu/libatlas.so, not found (try using -rpath or -rpath-link)
            /home/intelligence/anaconda3/compiler_compat/ld: /usr/lib/x86_64-linux-gnu/libatlas.so: undefined reference to `sqrtl@GLIBC_2.2.5'
            /home/intelligence/anaconda3/compiler_compat/ld: /usr/lib/x86_64-linux-gnu/libatlas.so: undefined reference to `sqrt@GLIBC_2.2.5'
            collect2: error: ld returned 1 exit status
            failure.
            removing: _configtest.c _configtest.o _configtest.o.d
            Status: 255
            Output: compiling '_configtest.c':
      
            /* This file is generated from numpy/distutils/system_info.py */
            void ATL_buildinfo(void);
            int main(void) {
              ATL_buildinfo();
              return 0;
            }
      
            C compiler: gcc -pthread -B /home/intelligence/anaconda3/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/intelligence/anaconda3/include -I/home/intelligence/anaconda3/include -fPIC -O2 -isystem /home/intelligence/anaconda3/include -fPIC
      
            compile options: '-c'
            gcc: _configtest.c
            gcc -pthread -B /home/intelligence/anaconda3/compiler_compat _configtest.o -L/usr/lib/x86_64-linux-gnu -lf77blas -lcblas -latlas -o _configtest
      
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 34, in <module>
              File "/tmp/pip-install-dzf32x9v/numpy_f29f84f3685b47618f1c97bbca81883b/setup.py", line 443, in <module>
                setup_package()
              File "/tmp/pip-install-dzf32x9v/numpy_f29f84f3685b47618f1c97bbca81883b/setup.py", line 435, in setup_package
                setup(**metadata)
              File "/tmp/pip-install-dzf32x9v/numpy_f29f84f3685b47618f1c97bbca81883b/numpy/distutils/core.py", line 137, in setup
                config = configuration()
              File "/tmp/pip-install-dzf32x9v/numpy_f29f84f3685b47618f1c97bbca81883b/setup.py", line 158, in configuration
                config.add_subpackage('numpy')
              File "/tmp/pip-install-dzf32x9v/numpy_f29f84f3685b47618f1c97bbca81883b/numpy/distutils/misc_util.py", line 1033, in add_subpackage
                config_list = self.get_subpackage(subpackage_name, subpackage_path,
              File "/tmp/pip-install-dzf32x9v/numpy_f29f84f3685b47618f1c97bbca81883b/numpy/distutils/misc_util.py", line 999, in get_subpackage
                config = self._get_configuration_from_setup_py(
              File "/tmp/pip-install-dzf32x9v/numpy_f29f84f3685b47618f1c97bbca81883b/numpy/distutils/misc_util.py", line 941, in _get_configuration_from_setup_py
                config = setup_module.configuration(*args)
              File "numpy/setup.py", line 10, in configuration
                config.add_subpackage('core')
              File "/tmp/pip-install-dzf32x9v/numpy_f29f84f3685b47618f1c97bbca81883b/numpy/distutils/misc_util.py", line 1033, in add_subpackage
                config_list = self.get_subpackage(subpackage_name, subpackage_path,
              File "/tmp/pip-install-dzf32x9v/numpy_f29f84f3685b47618f1c97bbca81883b/numpy/distutils/misc_util.py", line 999, in get_subpackage
                config = self._get_configuration_from_setup_py(
              File "/tmp/pip-install-dzf32x9v/numpy_f29f84f3685b47618f1c97bbca81883b/numpy/distutils/misc_util.py", line 941, in _get_configuration_from_setup_py
                config = setup_module.configuration(*args)
              File "numpy/core/setup.py", line 764, in configuration
                blas_info = get_info('blas_opt', 0)
              File "/tmp/pip-install-dzf32x9v/numpy_f29f84f3685b47618f1c97bbca81883b/numpy/distutils/system_info.py", line 444, in get_info
                return cl().get_info(notfound_action)
              File "/tmp/pip-install-dzf32x9v/numpy_f29f84f3685b47618f1c97bbca81883b/numpy/distutils/system_info.py", line 690, in get_info
                self.calc_info()
              File "/tmp/pip-install-dzf32x9v/numpy_f29f84f3685b47618f1c97bbca81883b/numpy/distutils/system_info.py", line 1810, in calc_info
                if getattr(self, '_calc_info_{}'.format(blas))():
              File "/tmp/pip-install-dzf32x9v/numpy_f29f84f3685b47618f1c97bbca81883b/numpy/distutils/system_info.py", line 1756, in _calc_info_atlas
                info = get_info('atlas_blas')
              File "/tmp/pip-install-dzf32x9v/numpy_f29f84f3685b47618f1c97bbca81883b/numpy/distutils/system_info.py", line 444, in get_info
                return cl().get_info(notfound_action)
              File "/tmp/pip-install-dzf32x9v/numpy_f29f84f3685b47618f1c97bbca81883b/numpy/distutils/system_info.py", line 690, in get_info
                self.calc_info()
              File "/tmp/pip-install-dzf32x9v/numpy_f29f84f3685b47618f1c97bbca81883b/numpy/distutils/system_info.py", line 1294, in calc_info
                atlas_version, atlas_extra_info = get_atlas_version(**atlas)
              File "/tmp/pip-install-dzf32x9v/numpy_f29f84f3685b47618f1c97bbca81883b/numpy/distutils/system_info.py", line 1589, in get_atlas_version
                'ATLAS_INFO', _c_string_literal(atlas_version))
              File "/tmp/pip-install-dzf32x9v/numpy_f29f84f3685b47618f1c97bbca81883b/numpy/distutils/system_info.py", line 177, in _c_string_literal
                s = s.replace('\\', r'\\')
            AttributeError: 'NoneType' object has no attribute 'replace'
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: legacy-install-failure
      
      × Encountered error while trying to install package.
      ╰─> numpy
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for output from the failure.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
</details>

**Comment by tilakrayal** [comment]
@lakpa-tamang9,
 Its unlikely for TF 2.3 version to receive any bug fixes except when we have security patches. There is a high possibility that this was fixed with later TF versions. Perhaps you can use the latest tf versions for your case. Also please take a look at this official doc [link](https://www.tensorflow.org/install/pip#package_location) for the reference. Thank you!

**Comment by mihaimaruseac** [comment]
TF 2.3 was released before Python 3.9. Dependencies it contains are also not able to work with Python 3.9

On the other hand, you are compiling from source and if you look at the error message closely this is what is happening to `scipy` too, pip tries to compile it from source. You could succeed if you ensure you have the needed environment to do that, but this is no longer a TF issue.

Hence, closing.
