### PR TITLE
Updated speech_commands example to work with TensorFlow 2.0+

### PR DESCRIPTION
**Pull request by sungkhum**
I had trouble running the speech_commands example to work, so after some research I updated the script to work with the latest version of TensorFlow using this tool: https://www.tensorflow.org/beta/guide/upgrade as well as modifying the location of audio_ops. I thought I would open a pull request so others don't have the same issues as I was having and are able to run the example out of the box instead of having to debug version issues. This is my first time contributing.

### CODE REVIEW

**Comment by sungkhum** [comment]
I signed it!

**Review by petewarden — DISMISSED** [review]

**Comment by sungkhum** [comment]
Thanks for the approval @petewarden - I noticed that some of the checks were not successful. Is there anything I need to do?

**Comment by gbaned** [comment]
@sungkhum Could you please check build failures and resolve the conflicts? Thanks!

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by sungkhum** [comment]
@gbaned I tried messing around with it a little, but still not exactly sure what is causing the conflict. On my Mac everything works fine.
It looks like some of the imports aren't working in other systems:
`from tensorflow.python.ops import audio_ops as contrib_audio
11
ImportError: cannot import name 'audio_ops'`
Does anyone know what should be imported?

Also this: https://github.com/tensorflow/tensorflow/issues/13031 might be the reason.

**Comment by sungkhum** [comment]
@rthadur I'm still not sure how this can be resolved:
`from tensorflow.python.ops import audio_ops as contrib_audio 11 ImportError: cannot import name 'audio_ops'` Do you know the import name that should be used?

**Comment by MarkDaoust** [comment]
Thanks for all the fixes @sungkhum!

> from tensorflow.python.ops import audio_ops as contrib_audio 11 ImportError: cannot import name 'audio_ops'

`gen_audio_ops` seems to exist. But I think this can use `tf.audio`.

I'll try to merge this and see if I can fix this in the merge commit.

**Review by MarkDaoust — DISMISSED** [review]

**Comment by rthadur** [comment]
@sungkhum can you please resolve conflicts ?

**Comment by MarkDaoust** [comment]
I've resolved the conflicts.

It looks like an auto-formatter caused the conflicts. 

It might be good to merge now.

**Comment by sungkhum** [comment]
Thanks @MarkDaoust !

**Comment by NyllRE** [comment]
Hi there, from 2022. I got confused onto how someone might be able to use the speech recognition library while importing the audio_ops as contrib_audio command. what should be finally imported after all of those changes?

**Comment by MarkDaoust** [comment]
Hi @NyllRE , so me of this has not been kept up to date. 

A better starting point is probably: https://www.tensorflow.org/tutorials/audio/simple_audio
