### ISSUE TITLE
attribute error

### ISSUE THREAD

**Issue by debadityamandal** [tensorflow/tensorflow#30978]
AttributeError: module 'tensorflow' has no attribute 'get_default_graph'

**Comment by pandrey-fr** [comment]
Hi,
Could you please provide more details as to which version of tensorflow you are running, and in which context this error appears? This is most probably an issue with trying to use a behaviour from TF 1.x while running TF 2.0beta

**Comment by debadityamandal** [comment]
Thank you for your response. This error is coming after upgrading tensorflow to 2.0.When i am going to create sequential model,this error is coming.I had to downgrade the version.After that it is working fine.

**Comment by pandrey-fr** [comment]
Great ; you are welcome, and do not forget to close the issue if your problem is solved.

Tensorflow 2.0 changes the API quite a bit. It is up to you to start using it now or not, but if you do you indeed need to update your code :-)

**Comment by debadityamandal** [comment]
OK. Thank you.
