### ISSUE TITLE
Compilation error when building tfcompile on Windows 10 (TF 1.13-rc2)

### ISSUE THREAD

**Issue by GPhilo** [tensorflow/tensorflow#25966]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): source
- TensorFlow version: checkout tag v1.13-rc2
- Python version: 3.5.6
- Installed using virtualenv? pip? conda?: -
- Bazel version (if compiling from source): 0.21
- GCC/Compiler version (if compiling from source): VS 2015 14.0.25431.01 Update 3
- CUDA/cuDNN version: 10.0/7.3.1
- GPU model and memory: GTX 1080, 8GBs

**Describe the problem**
This is a direct clone of issue #24218 as per request of @jvishnuvardhan. Except the code and CUDA version, everything else stated there applies here as well. Below the same information provided in the referenced issue, updated to the current configuration:

Checked out the release 1.13-rc2 branch of the TF repo, configured bazel (configuration is below) and ran 
`bazel build -c opt --config=opt //tensorflow/compiler/aot:tfcompile`

Compilation fails at `.\tensorflow/compiler/tf2xla/cpu_function_runtime.h(71): error C2338`. Full error message:

```
ERROR: C:/tf/tensorflow/compiler/tf2xla/BUILD:98:1: C++ compilation of rule '//tensorflow/compiler/tf2xla:cpu_function_runtime' failed (Exit 2): python.exe failed: error executing command
  cd C:/users/filippo/_bazel_filippo/rbrahckg/execroot/org_tensorflow
  SET CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0
    SET CUDNN_INSTALL_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0
    SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt;
    SET LIB=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64;
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64;C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;;C:\WINDOWS\system32
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C:/Users/Filippo/Anaconda3/envs/tf_build/python.exe
    SET PYTHON_LIB_PATH=C:/Users/Filippo/Anaconda3/envs/tf_build/lib/site-packages
    SET TEMP=C:\Users\Filippo\AppData\Local\Temp
    SET TF_CUDA_CLANG=0
    SET TF_CUDA_COMPUTE_CAPABILITIES=5.0,6.1,7.5
    SET TF_CUDA_VERSION=10.0
    SET TF_CUDNN_VERSION=7
    SET TF_NEED_CUDA=1
    SET TF_NEED_OPENCL_SYCL=0
    SET TF_NEED_ROCM=0
    SET TMP=C:\Users\Filippo\AppData\Local\Temp
  C:/Users/Filippo/Anaconda3/envs/tf_build/python.exe -B external/local_config_cuda/crosstool/windows/msvc_wrapper_for_nvcc.py /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /bigobj /Zm500 /J /Gy /GF /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /I. /Ibazel-out/x64_windows-opt/genfiles /Ibazel-out/x64_windows-opt/bin /Iexternal/nsync /Ibazel-out/x64_windows-opt/genfiles/external/nsync /Ibazel-out/x64_windows-opt/bin/external/nsync /Iexternal/eigen_archive /Ibazel-out/x64_windows-opt/genfiles/external/eigen_archive /Ibazel-out/x64_windows-opt/bin/external/eigen_archive /Iexternal/local_config_sycl /Ibazel-out/x64_windows-opt/genfiles/external/local_config_sycl /Ibazel-out/x64_windows-opt/bin/external/local_config_sycl /Iexternal/nsync/public /Ibazel-out/x64_windows-opt/genfiles/external/nsync/public /Ibazel-out/x64_windows-opt/bin/external/nsync/public /Iexternal/eigen_archive /Ibazel-out/x64_windows-opt/genfiles/external/eigen_archive /Ibazel-out/x64_windows-opt/bin/external/eigen_archive /DEIGEN_MPL2_ONLY /DEIGEN_MAX_ALIGN_BYTES=64 /DEIGEN_HAS_TYPE_TRAITS=0 /showIncludes /MD /O2 /DNDEBUG -w /arch:AVX2 /Fobazel-out/x64_windows-opt/bin/tensorflow/compiler/tf2xla/_objs/cpu_function_runtime/cpu_function_runtime.o /c tensorflow/compiler/tf2xla/cpu_function_runtime.cc
Execution platform: @bazel_tools//platforms:host_platform
.\tensorflow/compiler/tf2xla/cpu_function_runtime.h(71): error C2338:
Target //tensorflow/compiler/aot:tfcompile failed to build
```

It's still the same static assert failing: 
```
std::pair<uint64, uint64> Encode() const {
    static_assert(sizeof(*this) == 16, ""); //<<<<<<<<<<<<<<<<< 
    uint64 upper = Pack(kind(), size_);
    uint64 lower = entry_param_number_;
    return {upper, lower};
  }
```
**Other info / logs**

Bazel config:

```
build --action_env PYTHON_BIN_PATH="C:/Users/Filippo/Anaconda3/envs/tf_build/python.exe"
build --action_env PYTHON_LIB_PATH="C:/Users/Filippo/Anaconda3/envs/tf_build/lib/site-packages"
build --python_path="C:/Users/Filippo/Anaconda3/envs/tf_build/python.exe"
build:xla --define with_xla_support=true
build --config=xla
build --action_env TF_NEED_OPENCL_SYCL="0"
build --action_env TF_NEED_ROCM="0"
build --action_env TF_NEED_CUDA="1"
build --action_env CUDA_TOOLKIT_PATH="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0"
build --action_env TF_CUDA_VERSION="10.0"
build --action_env CUDNN_INSTALL_PATH="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0"
build --action_env TF_CUDNN_VERSION="7"
build --action_env TF_CUDA_COMPUTE_CAPABILITIES="5.0,6.1,7.5"
build --action_env TF_CUDA_CLANG="0"
build --config=cuda
test --config=cuda
build:opt --copt=/arch:AVX2
build:opt --define with_default_optimizations=true
build --config monolithic
build --copt=-w --host_copt=-w
build --verbose_failures
build --distinct_host_configuration=false
build --experimental_shortened_obj_file_path=true
build --define=override_eigen_strong_inline=true
build:v2 --define=tf_api_version=2
```

**Comment by yongtang** [comment]
@GPhilo I could see commit https://github.com/tensorflow/tensorflow/commit/bb479118c9fed7be0186f98a3939ec28b162f2fe might have fixed the issue. It is not part of `rc2` though.

**Comment by GPhilo** [comment]
@yongtang thanks for the update, will the commit be included in 1.13?

**Comment by yongtang** [comment]
@GPhilo Don't know if the commit will be picked up by the final version of 1.13.0. The rc2 is very close to the final release as far as I know.

**Comment by sanatmpa1** [comment]
@GPhilo,

As we see the issue is related to an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to latest stable version of tensorflow `2.6.0`, Can you try to build from source using the [guide](https://www.tensorflow.org/install/source_windows) and let us know if it works fine. Thanks!

**Comment by GPhilo** [comment]
This is definitely a very old issue, I can't really try to build tensorflow on Windows at the moment (nor would I have a reason too), but either way I'm sure the build issues would be different from those I had with version 1.13, so I'll close the issue.
