### ISSUE TITLE
'is_final' is not a member of 'std'

### ISSUE THREAD

**Issue by plopresti** [tensorflow/tensorflow#31900]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux RedHat 7.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: master branch
- Python version: N/A
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): 0.25.2
- GCC/Compiler version (if compiling from source): cc version 8.2.1 20180905 (Red Hat 8.2.1-3)
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**

Compilation of LLVM is failing because '-std=c++0x' is being passed, but current LLVM uses C++14 features.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

bazel build --verbose_failures --config opt --config mkl //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Note "-std=c++0x" option. I could probably fix this myself if I could figure out where it is coming from...
```
  /opt/rh/devtoolset-8/root/usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/host/bin/tensorflow/compiler/mlir/lite/quantization/_objs/op_quant_spec_getters_gen/op_quant_spec_getters_gen.d '-frandom-seed=bazel-out/host/bin/tensorflow/compiler/mlir/lite/quantization/_objs/op_quant_spec_getters_gen/op_quant_spec_getters_gen.o' -DLLVM_ENABLE_STATS -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DLLVM_BUILD_GLOBAL_ISEL -iquote . -iquote bazel-out/host/bin -iquote external/llvm -iquote bazel-out/host/bin/external/llvm -iquote external/zlib_archive -iquote bazel-out/host/bin/external/zlib_archive -iquote external/local_config_mlir -iquote bazel-out/host/bin/external/local_config_mlir -iquote external/bazel_tools -iquote bazel-out/host/bin/external/bazel_tools -isystem external/llvm/include -isystem bazel-out/host/bin/external/llvm/include -isystem external/zlib_archive -isystem bazel-out/host/bin/external/zlib_archive -isystem external/local_config_mlir/include -isystem bazel-out/host/bin/external/local_config_mlir/include -g0 '-march=native' -g0 -DEIGEN_AVOID_STL_ARRAY -Iexternal/gemmlowp -Wno-sign-compare '-ftemplate-depth=900' -fno-exceptions '-DINTEL_MKL=1' -DEIGEN_USE_VML -DENABLE_MKL -fopenmp -msse3 -pthread -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c tensorflow/compiler/mlir/lite/quantization/tools/op_quant_spec_getters_gen.cc -o bazel-out/host/bin/tensorflow/compiler/mlir/lite/quantization/_objs/op_quant_spec_getters_gen/op_quant_spec_getters_gen.o)
Execution platform: @bazel_tools//platforms:host_platform
In file included from external/llvm/include/llvm/TableGen/Record.h:27,
                 from tensorflow/compiler/mlir/lite/quantization/tools/op_quant_spec_getters_gen.cc:21:
external/llvm/include/llvm/Support/TrailingObjects.h: In static member function 'static void llvm::TrailingObjects<BaseTy, TrailingTys>::verifyTrailingObjectsAssertions()':
external/llvm/include/llvm/Support/TrailingObjects.h:252:24: error: 'is_final' is not a member of 'std'
     static_assert(std::is_final<BaseTy>(), "BaseTy must be final.");
                        ^~~~~~~~
```

**Comment by plopresti** [comment]
Reverting 09c588de fixes this for me.

Yes this is a duplicate of issue #31866, which was closed even though the problem remains.

**Comment by plopresti** [comment]
Update: The -std=c++0x flag is coming from inside Bazel.

Setting the environment variable BAZEL_CXXOPTS to "-std=c++14" makes the error go away. (So presumably you can set it to -std=c++0x to reproduce this issue.)

Seems like the LLVM build ought to be setting its build options explicitly?

**Comment by angersson** [comment]
Hmm, I wonder if this is a side effect of our compiler, which is based on devtoolset. We haven't been seeing this issue in our internal builds, so perhaps you're encountering a surprising build configuration error.

Just to double-check, have you tried re-running `./configure`? The setting might have been set in the locally generated .bazelrc.

**Comment by plopresti** [comment]
Perhaps, but I do not think so...

I recursively "grepped" the Tensorflow tree post-configure trying to determine where the "c++0x" was coming from. I even manually edited every instance (although all of them are under "third_party/toolchains", which does not apply), and it did not change anything.

However, when I recursively grep the bazel-0.25.2 source code for "c++0x", I get this:

`./tools/cpp/unix_cc_configure.bzl:    cxx_opts = split_escaped(get_env_var(repository_ctx, "BAZEL_CXXOPTS", "-std=c++0x", False), ":")`

...which in turn is how I decided to try setting BAZEL_CXXOPTS to work around this issue. So I am pretty sure this is coming from inside Bazel.

I do not claim to fully understand Bazel, much less its source code... But I believe a stock Bazel build sets "-std=c++0x" for cxx_opts unless it is overridden. I am pretty sure the LLVM build inside Tensorflow is not doing so.

I am not sure why most people do not see this, but my guess would be it has to do with how their Bazel is compiled.

**Comment by plopresti** [comment]
I am pretty sure you could reproduce this failure by setting the BAZEL_CXXOPTS environment variable to "-std=c++0x" and running a build.

You will find the build still gets pretty far because Tensorflow mostly specifies the cxxopts explicitly. But not when it compiles LLVM, which gets whatever happened to be compiled into Bazel (or set by this environment variable).

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
