### ISSUE TITLE
AttributeError with Protobuf >= 6.30

### ISSUE THREAD

**Issue by sevu** [tensorflow/tensorflow#94030]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

current master   v1.12.1-126604-g3d72b9f063c   2.20.0-dev0+selfbuilt

### Custom code

No

### OS platform and distribution

Ubuntu 25.04 +venv

### Python version

3.13

### Bazel version

7,4.1

### GCC/compiler version

clang 20.1

### CUDA/cuDNN version

-

### GPU model and memory

-

### Current behavior?

Have a version >= 6.30.0 of python-protobuf, such as 6.31.0
When importing tensorflow the error message is displayed.

### Standalone code to reproduce the issue

```shell
python -c "import tensorflow"
```

### Relevant log output

```shell
AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'
```

**Comment by ybaturina** [comment]
FYI - the issue was introduced by https://github.com/tensorflow/tensorflow/pull/91651.

**Comment by Kayyuri** [comment]
Hi,
Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.
Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
