### ISSUE TITLE
Keras Model Errors on Loading - 'list' object has no attribute 'items' with TF 2.1

### ISSUE THREAD

**Issue by tripathysa** [tensorflow/tensorflow#38135]
**System information**

Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ProductName:	Mac OS X, ProductVersion:	10.15.2, BuildVersion:	19C57
TensorFlow installed from (source or binary): pip
TensorFlow version (use command below): 2.1.0
Python version: 3.6.8
CUDA/cuDNN version: None
GPU model and memory: None

**Describe the current behavior**

When trying to load one of my models using tf.keras.models.load_model an error is thrown at the following location:

```
tensorflow_core\python\keras\utils\generic_utils.py", line 254, in class_and_config_for_serialized_keras_object
for key, item in cls_config.items():
**AttributeError: 'list' object has no attribute 'items'**
```
This code expects cls_config to be a dictionary, while for this model it is a list of dictionaries.

I can successfully load and run this model using TensorFlow versions 2.0.0, 1.15.0 and 1.14.0.

This section of code was introduced when adding support for passive serialization in Keras

**Describe the expected behavior**

Can successfully load a model from a hdf5 file.

**Code to reproduce the issue:**

```
import tensorflow as tf

model = tf.keras.models.load_model('cnn_multichannel_dense_f0_b0.h5', compile=False)
```

**Other info / logs:**

**_I am also attaching a dummy hdf5 model below which can be used to test._**

Complete Stacktrace of the error:

```
  File "/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "lib/python3.6/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 168, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "lib/python3.6/site-packages/tensorflow_core/python/keras/saving/model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "lib/python3.6/site-packages/tensorflow_core/python/keras/layers/serialization.py", line 106, in deserialize
    printable_module_name='layer')
  File "lib/python3.6/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 292, in deserialize_keras_object
    config, module_objects, custom_objects, printable_module_name)
  File "lib/python3.6/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 254, in class_and_config_for_serialized_keras_object
    for key, item in cls_config.items():
AttributeError: 'list' object has no attribute 'items'

```

When loaded with tf.keras in v2.0.0 the layers, model config, inputs, outputs, summary etc. are all parsed correctly, as well as being able to run data through the model.

**Comment by tripathysa** [comment]
[cnn_multichannel_dense_f0_b0.h5.zip](https://github.com/tensorflow/tensorflow/files/4416739/cnn_multichannel_dense_f0_b0.h5.zip)

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.1](https://colab.research.google.com/gist/amahendrakar/8ffb93fe9c91670fb8e3e6d21038bbcd/38135-2-1.ipynb), [TF v2.2.0-rc2](https://colab.research.google.com/gist/amahendrakar/78f9cc5cc4fdcebbe9e8e62745af53aa/38135-2-2.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/3f7747e2187f252273d49872d4615c48/38135-tf-nightly.ipynb). Works fine on [TF v2.0](https://colab.research.google.com/gist/amahendrakar/e1c64f58d7da6e77b9a5dae802664dea/38135-2-0.ipynb). Please find the attached gist. Thanks!

**Comment by jvishnuvardhan** [comment]
@tripathysa Can you please share simple standalone code to reproduce the issue? The provided `*.h5` file is not sufficient to find root-cause of the issue. If your code is proprietary code then please try to use public data to create a standalone code. Thanks!

**Comment by tripathysa** [comment]
@jvishnuvardhan : Do you mean sharing train code?

@amahendrakar was already able to reproduce the issue with:
`import tensorflow as tf

model = tf.keras.models.load_model('cnn_multichannel_dense_f0_b0.h5', compile=False)’

**Comment by tripathysa** [comment]
It looks like `config['config']` is expected to be a dictionary here in 2.1 while its a list(https://github.com/tensorflow/tensorflow/blob/r2.1/tensorflow/python/keras/utils/generic_utils.py#L252) but in 2.0. no such assumed deserialization happens as I see it.

**Comment by feihugis** [comment]
@jvishnuvardhan @tripathysa #38339 has been submitted to fix this issue.
