### ISSUE TITLE
[TF 2.0.0-rc0] Keras Model subclassing `dynamic=True` throws Error. Possible Regression bug of rc0

### ISSUE THREAD

**Issue by faizanahemad** [tensorflow/tensorflow#32412]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
    - Mac OSX 10.13.6, intel i7, MacBook Pro (Retina, 13-inch, Early 2015), Intel Iris Graphics 6100 1536 MB, 
    - Google Colab (Both CPU and GPU)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): Binary (pip)
- TensorFlow version (use command below): 2.0.0-rc0
` pip install tensorflow==2.0.0-rc0`
- Python version: 3.7.3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: NA
- GPU model and memory: Intel Iris Graphics 6100 1536 MB (Stock Intel i7 CPU bundled)

**Describe the current behavior**
In 2.0.0-rc0, While using Model Subclassing of tf,keras.Model and passing `dynamic=True`. Then when I call model.fit it throws `AttributeError: 'NoneType' object has no attribute 'dtype'`

**Describe the expected behavior**
model.fit should not throw any error. Note this was working fine in `2.0.0-beta1`

**Code to reproduce the issue**
```python
import numpy as np
import tensorflow as tf
import os

print(tf.__version__)


class ConvBn2D(tf.keras.Model):
    def __init__(self, c_out, kernel_size=3):
        super().__init__()
        self.conv = tf.keras.layers.Conv2D(filters=c_out, kernel_size=kernel_size,
                                           strides=1, padding="SAME",
                                           use_bias=False)
        self.bn = tf.keras.layers.BatchNormalization(momentum=0.9, epsilon=1e-7)

    def call(self, inputs):
        res = tf.nn.relu(self.bn(self.conv(inputs)))
        return res


class FNet(tf.keras.Model):
    def __init__(self, start_kernels=64, weight=0.125, **kwargs):
        super().__init__(**kwargs)
        c = start_kernels
        self.max_pool = tf.keras.layers.MaxPooling2D()
        self.init_conv_bn = ConvBn2D(c, kernel_size=3)
        self.c0 = ConvBn2D(c, kernel_size=3)

        self.c1 = ConvBn2D(c * 2, kernel_size=3)
        self.c2 = ConvBn2D(c * 2, kernel_size=3)

        self.c3 = ConvBn2D(c * 2, kernel_size=3)
        self.c4 = ConvBn2D(c * 2, kernel_size=3)

        self.pool = tf.keras.layers.GlobalMaxPool2D()
        self.linear = tf.keras.layers.Dense(10, use_bias=False)
        self.weight = weight

    def call(self, x):
        h = self.max_pool(self.c0(self.init_conv_bn(x)))
        h = self.max_pool(self.c2(self.c1(h)))
        h = self.max_pool(self.c4(self.c3(h)))
        h = self.pool(h)
        h = self.linear(h) * self.weight
        return h


(x_train, y_train), (x_test, y_test) = tf.keras.datasets.cifar10.load_data()
train = tf.data.Dataset.from_tensor_slices((x_train, y_train))
train = train.map(lambda x,y:(tf.cast(x,tf.float32),tf.cast(y,tf.int64))).map(lambda x,y:(x/255.0,y)).batch(512)

# model = FNet(start_kernels=8)

model = FNet(start_kernels=8,dynamic=True)

loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
model.compile(optimizer=tf.keras.optimizers.RMSprop(0.01),
              loss=loss)

callbacks=[]
model.fit(train, epochs=2, callbacks=callbacks,verbose=1)
```

**Other info / logs**
Run code in `2.0.0-beta1` it works. in rc0 fails.

[Colab Notebook with same issue](https://colab.research.google.com/drive/1dZaIwlgKRk_8FSKkdyQlwXsT3auqV6VX)

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.0.0-rc0 and was able to reproduce the issue.However i am not seeing any issue with TF 2.0.0-beta1 .Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/c1083c26816bb17ae69785f8d5a111cc/untitled174.ipynb). Thanks!

**Comment by bodak** [comment]
This bug is still there for the final version of 2.0.0 and 2.1.0.

The reason is that when passing a tf.dataset as `targets` to Keras.model.fit API `targets` actually contains both `(targets, outputs)`.  Later this means that due to `outputs[0]` being `None` L1382 fails.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/training_utils.py#L1382

Maybe we can update the title accordingly.

Dirty work-around for my case:
```
  if tensor_util.is_tensor(targets):
    if outputs[0] == None:
        return targets
    # There is one target, so output[0] should be the only output
    return cast_single_tensor(targets, dtype=outputs[0].dtype)
```

Blame: https://github.com/tensorflow/tensorflow/commit/4deb12d63f4928340190006549dc96abcf7a2088

**Comment by goldiegadde** [comment]
this issue is no longer seen with 2.2.0-rc0. 
@faizanahemad could you please check and close if the issue if it is resolved.

**Comment by goldiegadde** [comment]
Closing this now, @faizanahemad please feel free to re-open if you still continue to see the issue.
