### ISSUE TITLE
TF 2.0.0a0 doesn't find attributes after fresh installation

### ISSUE THREAD

**Issue by Mardeepus** [tensorflow/tensorflow#26877]
**System information**
- OS Platform and Distribution: **Windows 10 Pro x64**
- TensorFlow installed from (source or binary): **binary (for GPU)** https://files.pythonhosted.org/packages/a3/a1/adff98d96de3d623f53f2e002d6e5b3936857c168a99efa632b7db89da05/tensorflow_gpu-2.0.0a0-cp37-cp37m-win_amd64.whl
- TensorFlow version: **2.0.0a0 for GPU**
- Python version: **3.7.2 64-bit (3.6.8 x64)**
- Installed using: **virtualenv & pip**
- CUDA/cuDNN version: **10.0 | 7.5.0 (7.4.2)**
- GPU model and memory: **Nvidia RTX 2080 Ti (11GB)**
- Others: **Visual Studio 2017 Community | Nvidia-Drivers 419.35**

<details>
  <summary>Package Versions</summary>
- absl-py 0.7.1
- astor 0.7.1
- gast 0.2.2
- google-pasta 0.1.4
- grpcio 1.19.0
- h5py 2.9.0
- Keras-Applications 1.0.7
- Keras-Preprocessing 1.0.9
- Markdown 3.0.1
- numpy 1.16.2
- pip 19.0.3
- protobuf 3.7.0
- setuptools 40.8.0
- six 1.12.0
- tb-nightly 1.14.0a20190301
- tensorflow-gpu 2.0.0a0
- termcolor 1.1.0
- tf-estimator-nightly 1.14.0.dev2019030115
- Werkzeug 0.14.1
- wheel 0.33.1
</details>

**Describe the problem**
Hi you guys! Thanks in advance!
I'm trying to install tensorflow-gpu 2.0.0a0 in an venv using pip as described at https://www.tensorflow.org/install/pip via _'pip install tensorflow-gpu==2.0.0-alpha0'_.
It works fine with TF 1.13.1 (GPU/CPU) but it doesn't for 2.0.0a0 (GPU/CPU)! The GPU and CPU version of 2.0.0a0 has the same error.

First I installed everything according to guides on a fresh system.
After installation I test it with the recommended cmd-line:

_python -c "import tensorflow as tf; tf.enable_eager_execution(); print(tf.reduce_sum(tf.random_normal([1000, 1000])))"_

As for the error, what I get is:

_Traceback (most recent call last):
  File "\<string\>", line 1, in \<module\>
AttributeError: module 'tensorflow' has no attribute 'enable_eager_execution'_

I tried using python 3.6.8 and cuDNN 7.4.2. Also I tried using the newest versions of tf-estimator-nightly and tb-nightly. Tried it outside the venv. Tried it without _'tf.enable_eager_execution();'_ but then it has no attribute _'random_normal'_. Tried using .whl from other sites.

Since TF 1.13.1-gpu works and the error is so strangely unspecific, I have no idea what to try next. I saw issues with similar problems, but those solutions didn't work for me or the issue was similar but not this one. Please help!

**Comment by foobar167** [comment]
It seems that different syntax in TF 2.0 is used.
Try this code (it worked for me):
```
python -c "import tensorflow as tf;     \
    print('Version:', tf.__version__);  \
    print(tf.reduce_sum(tf.random.normal([1000, 1000])));"
```

**Comment by Mardeepus** [comment]
Thank you foobar167, it works!

It seems I have to get used to the new API. You are right, it needs to be _tf.random.normal_ instead of _tf.random_normal_ and also needs to use _tf.executing_eagerly()_ instead of _tf.enable_eager_execution()_ (which is on in 2.0 by default).

The TF-install-Doc needs to be update there, so this confusion would happen again.

Thanks again!

**Comment by starty1314** [comment]
To whoever needs to figure this out. You can use below code to verify the installation of TensorFlow v2.0

python -c "import tensorflow as tf; tf.executing_eagerly(); print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
