### ISSUE TITLE
AttributeError: 'module' object has no attribute 'rnn'

### ISSUE THREAD

**Issue by sharod** [tensorflow/tensorflow#8836]
I had a version of ptb_word_lm.py which worked in 0.11. Now I am trying to use the same code in version 1.0.1. I am facing the following error:

outputs, state = tf.nn.rnn(cell, inputs,initial_state=self._initial_state)
AttributeError: 'module' object has no attribute 'rnn'

Please help soon !!

**Comment by jubjamie** [comment]
That's because tf.nn.rnn doesn't exist anymore! Perhaps you are looking for [tf.nn.dynamic_rnn](https://www.tensorflow.org/api_docs/python/tf/nn/dynamic_rnn) or the more experimental [tf.nn.raw_rnn](https://www.tensorflow.org/api_docs/python/tf/nn/raw_rnn)?

Alternativley there is the contrib repo of RNN function in [tf.contrib.rnn](https://www.tensorflow.org/api_docs/python/tf/contrib/rnn)

**Comment by sharod** [comment]
So where is the rnn function residing presently now?

Doing this gave the following error:

outputs, state = tf.contrib.rnn(cell, inputs,initial_state=self._initial_state)
TypeError: 'module' object is not callable

**Comment by jubjamie** [comment]
You are getting that error because tf.contrib.nn is not a function but a package of modules. Please make sure you _read the documentation_ before trying things in your code. I linked the documentation for you in my first comment for your convenience.

Regarding the original rnn, i'm not sure as I never used it. Perhaps you need dynamic_rnn? I would read the documentation to find which functions satisfy your needs. You may need to alter your function arguments accordingly.

As this isn't a Tensorflow bug but rather a usage problem may I suggest that you open a Stack Overflow question to learn how to use RNN in Tensorflow as this issue may get closed.

**Comment by Ivan-Zhao** [comment]
Did you solve it? I met the problem with you

lstm_cell = tf.contrib.rnn.BasicLSTMCell(dimhidden, forget_bias=1.0)
_LSTM_O, _LSTM_S = tf.contrib.rnn(lstm_cell, _Hsplit,dtype=tf.float32)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-54-a2b2c95b3fbd> in <module>()
      2 x      = tf.placeholder("float", [None, nsteps, diminput])
      3 y      = tf.placeholder("float", [None, dimoutput])
----> 4 myrnn  = _RNN(x, weights, biases, nsteps, 'basic')
      5 pred   = myrnn['O']
      6 cost   = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(pred, y))

<ipython-input-53-6aff4bf02bd1> in _RNN(_X, _W, _b, _nsteps, _name)
     16         scope.reuse_variables()
     17         lstm_cell = tf.contrib.rnn.BasicLSTMCell(dimhidden, forget_bias=1.0)
---> 18         _LSTM_O, _LSTM_S = tf.contrib.rnn(lstm_cell, _Hsplit,dtype=tf.float32)
     19     # 6. Output
     20     _O = tf.matmul(_LSTM_O[-1], _W['out']) + _b['out']

TypeError: 'module' object is not callable

**Comment by jubjamie** [comment]
@Ivan-Zhao tf.contrib.rnn is **NOT** a function. It is a collection of functions. This is why you are receiving that error. Please see it's [documentation here](https://www.tensorflow.org/api_docs/python/tf/contrib/rnn).

**Comment by yogeshg** [comment]
I was looking for the same thing, rnn.rnn -- a function. This thread helped me find rnn.dynamic_rnn which resembles the signature of the function I needed.
