### PR TITLE
Fix symbol duplication for iOS on Xcode/clang

### PR DESCRIPTION
**Pull request by tyfkda**
I tried to use Tensorflow on iPhone.
I successfully created library files for iOS (libtensorflow-core-*.a)
using `tensorflow/contrib/makefile/build_all_ios.sh`.

But when I tried to use the library, following linker error happened on Xcode:

```
duplicate symbol __Z14tf_git_versionv in:
    /Users/admin/tmp/tensorflow/tensorflow/contrib/ios_examples/simple/../../makefile/gen/lib/libtensorflow-core.a(version_info.o)
duplicate symbol __Z19tf_compiler_versionv in:
    /Users/admin/tmp/tensorflow/tensorflow/contrib/ios_examples/simple/../../makefile/gen/lib/libtensorflow-core.a(version_info.o)
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

These functions are defined in `tensorflow/core/util/version_info.cc`.
It seems the object file is added twice in Makefile:
(`$(wildcard tensorflow/core/util/*.cc)` and `tensorflow/core/util/version_info.cc`)

The source file `version_info.cc` is generated from a script
and not included in the repository,
so adding the source file to `CORE_CC_ALL_SRCS` manually on line 431 is necessary.
But once it is generated, it is listed on `$(wildcard tensorflow/core/util/*.cc)` too, and added twice.

Using `$(sort ...)` function removes this duplication and solves the problem.

### CODE REVIEW

**Comment by ic** [comment]
Great. I had a similar fix ready for PR. Yours is better to me.

No problem with missing ops after applying your fix? I give up on my PR, but I also had [to add missing ops](https://github.com/ic/tensorflow/commit/a6a1bfa25860ed9f5f01aaabb72136ce58c6e2be#diff-d251197c17294875e26b96cfff5bb1d8) to get a linkable build on iOS. Please note that the linked diff is valid for `tensorflow/contrib/makefile/tf_op_files.txt` only (my change on the `Makefile` does not cover one case and would err).

**Comment by tyfkda** [comment]
@ic In my environment,
I have succeeded to link and execute iOS examples (simple and camera)
with the library built with this change.
I haven't encountered missing ops, so I'm not sure it is needed.

**Review by aselle — APPROVED** [review]
LGTM. Unfortunately, we can't rely on the glob alone (which is what creates the duplicate) , because in the first compile case the version_info.cc dependency would never be created, preventing version_info from ever being generated. Thanks for the fix.

File: tensorflow/contrib/makefile/Makefile [hunk 1]
```diff
@@ -429,6 +429,8 @@ $(wildcard tensorflow/core/platform/*/*/*.cc) \
 $(wildcard tensorflow/core/util/*.cc) \
 $(wildcard tensorflow/core/util/*/*.cc) \
 tensorflow/core/util/version_info.cc
+# Remove duplicates (for version_info.cc)
+CORE_CC_ALL_SRCS := $(sort $(CORE_CC_ALL_SRCS))
```
Comment (aselle) [inline tensorflow/contrib/makefile/Makefile]: nevermind, see my LGTM above for why this wouldn't work.

**Comment by tyfkda** [comment]
@aselle Thank you for your review!
Could you tap Jenkins?

**Comment by aselle** [comment]
@tensorflow-jenkins test this please

**Comment by arundasan91** [comment]
@tyfkda I hope the Xcode version you are using is Xcode 8 ? I was able to get everything working with Xcode 7.3 without the changes you made in this commit. However, I required to add the change you made in order to get tensor flow properly working and build the app without error in Xcode 8. The app builds fine for an iOS 10 iPhone but crashes.

Are you using using an iOS 10 device ? 
I cannot make it work for iOS 10 with Xcode 8.

Could you please share your versions and all ? That would be really helpful. I can, then, maybe raise a proper question at Stack Overflow.

Thanks !

**Comment by tyfkda** [comment]
@arundasan91 Yes, I have updated Xcode to 8.
Here is my environment:

  * Xcode: Version 8.0 (8A218a)
  * iOS: 10.0.1 (14A403)

I can run an application with this change on iOS simulator, and iPhone 6.

As you said,
I built and ran successfully without this change on Xcode 7.3 in the past (1 month or so).
Recently I updated my device's OS from 9 to 10,
and it requires Xcode 8,
then `duplicate symbol` error happens.

I'm not sure this is causes by some source code change,
or by Xcode 8.

**Comment by arundasan91** [comment]
Thank You ! That clears a lot. 

Did you change or add any build options or similar settings though ? I came across some errors and found that adding `Privacy - Photo Library Usage Description`, `Privacy - Camera Usage Description` to `Info.plist` might help remove the errors. It did build properly. But the app breaks with this error 

```
2016-09-23 23:17:17.086861 CameraExample[2190:405056] 0x16ea0dc0 Copy matching assets reply: XPC_TYPE_DICTIONARY  <dictionary: 0x16ea0dc0> { count = 2, transaction: 0, voucher = 0x0, contents =
	"Result" => <int64: 0x16e9d490>: 0
	"Assets" => <data: 0x16ea0e30>: { length = 1229 bytes, contents = 0x62706c6973743030d401020304050866675424746f705824... }
}
2016-09-23 23:17:17.092728 CameraExample[2190:405056] 0x16d73990 Copy assets attributes reply: XPC_TYPE_DICTIONARY  <dictionary: 0x16d73990> { count = 1, transaction: 0, voucher = 0x0, contents =
	"Result" => <int64: 0x16d73a00>: 1
}
2016-09-23 23:17:17.093023 CameraExample[2190:405056] [MobileAssetError:1] Unable to copy asset attributes
2016-09-23 23:17:17.093369 CameraExample[2190:405056] Could not get attribute 'LocalURL': Error Domain=MobileAssetError Code=1 "Unable to copy asset attributes" UserInfo={NSDescription=Unable to copy asset attributes}
2016-09-23 23:17:17.100138 CameraExample[2190:405056] 0x16d702f0 Copy matching assets reply: XPC_TYPE_DICTIONARY  <dictionary: 0x16d702f0> { count = 2, transaction: 0, voucher = 0x0, contents =
	"Result" => <int64: 0x16d64090>: 0
	"Assets" => <data: 0x16d81380>: { length = 1237 bytes, contents = 0x62706c6973743030d401020304050865665424746f705824... }
}
2016-09-23 23:17:17.104951 CameraExample[2190:405056] 0x16ea3640 Copy assets attributes reply: XPC_TYPE_DICTIONARY  <dictionary: 0x16ea3640> { count = 1, transaction: 0, voucher = 0x0, contents =
	"Result" => <int64: 0x16ea3620>: 1
}
2016-09-23 23:17:17.105176 CameraExample[2190:405056] [MobileAssetError:1] Unable to copy asset attributes
2016-09-23 23:17:17.105510 CameraExample[2190:405056] Could not get attribute 'LocalURL': Error Domain=MobileAssetError Code=1 "Unable to copy asset attributes" UserInfo={NSDescription=Unable to copy asset attributes}
2016-09-23 23:17:18.997743 CameraExample[2190:404997] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2016-09-23 23:17:19.002128 CameraExample[2190:404997] [MC] Reading from public effective user settings.
F /Users/arundas/tensorflow/tensorflow/contrib/ios_examples/camera/../../../../tensorflow/core/lib/core/refcount.h:79] Check failed: ref_.load() == 0 (1 vs. 0)
```

with `Thread 4: signal SIGABRT`

I am sorry if I am not supposed to add more comments here.

I will add a new question in StackOverflow tomorrow.

Thanks a lot for the info about the versions!

**Comment by tyfkda** [comment]
@arundasan91 
I'm sorry for my wrong information,
I didn't test the examples well.

Now I test ios_examples/camera,
I can build it without any modification for bulid settings or `Info.plist` (but set `Team` to run on real device).
But when I try to run the app, it crashes as you said.

I can run ios_example/simple though,
I think the error is not related to Tensorflow library,
and need modification for application code.

It is better to ask in other place about the crash (StackOverflow),
and send a pull request to fix the issue :)

**Comment by arundasan91** [comment]
Thanks a lot !

**Comment by nekot** [comment]
I encountered same issue (duplicate symbol) using Xcode 8.0 and iOS 9.3.5 (iPhone 6 Plus).
And I used @tyfkda patch and fixed the issue.
Now CameraExample is working fine.
JFYI.
