### ISSUE TITLE
SavedModel Loading Issue - '_UserObject' object has no attribute 'add_slot'

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [tensorflow/tensorflow#52370]
Some models that used to be working in TensorFlow 2.5 are now impossible to load with TF 2.6 and onward.

Google Colab to reproduce the issue: https://colab.research.google.com/drive/1n_FY1YNBDaWd43SJI8oxjHPEsA32FPEV?usp=sharing

Script:
```python
import tensorflow as tf
from tensorflow.python.saved_model import tag_constants

print("TF Version:", tf.__version__)

saved_model_loaded = tf.saved_model.load(
    "resnet_v1.5_50_tfv2", tags=[tag_constants.SERVING]
)

print("Success !")
```

Error:
```python
AttributeError                            Traceback (most recent call last)

<ipython-input-2-714dfc7741a0> in <module>()
      5 
      6 saved_model_loaded = tf.saved_model.load(
----> 7     "resnet_v1.5_50_tfv2", tags=[tag_constants.SERVING]
      8 )
      9 

4 frames

/usr/local/lib/python3.7/dist-packages/tensorflow/python/saved_model/load.py in _load_nodes(self)
    446         optimized_variable = nodes[
    447             slot_variable_proto.original_variable_node_id]
--> 448         slot_variable = optimizer_object.add_slot(
    449             var=optimized_variable,
    450             slot_name=slot_variable_proto.slot_name)

AttributeError: '_UserObject' object has no attribute 'add_slot'
```

**Comment by sushreebarsa** [comment]
@DEKHTIARJonathan Was able to reproduce the issue on colab using TF [v2.6](https://colab.research.google.com/gist/sushreebarsa/17029aa9e6effca91060480dfffeccb4/untitled467.ipynb) but the issue is not replicating in [tf-nightly ](https://colab.research.google.com/gist/sushreebarsa/b3c5cd4a4c7922f346cb5307039d9367/untitled468.ipynb#scrollTo=eRSv8cOXzDns)version 2.8.0-dev20211012,Could you please find the attached gists and confirm the same ? This issue seems to be fixed in recent nightly version .Thank you!

**Comment by sushreebarsa** [comment]
@DEKHTIARJonathan Could you please find the latest  [commit](https://github.com/tensorflow/tensorflow/commit/59e882af21831eea9e24d74c9af4242cc1514c6e) reference and let us know if it helps ?
Please move this issue to closed status if it is resolved for you.Thank you!

**Comment by sushreebarsa** [comment]
@DEKHTIARJonathan Could you please find the latest  [commit](https://github.com/tensorflow/tensorflow/commit/59e882af21831eea9e24d74c9af4242cc1514c6e) reference and let us know if it helps ?
Please move this issue to closed status if it is resolved for you.Thank you!

**Comment by Practical-AI** [comment]
@DEKHTIARJonathan 
I had the same issue. I loaded the model in the same notebook that I was trying to load the saved_model and solved the problem. I assume TensorFlow recognizes the used objects in RAM and it prevents further errors.

**Comment by rpytel1** [comment]
I also encounter this issue. 
With all the respect but this issue is not solved as the problem is still there in all of the versions of 2.6 (2.6.0, 2.6.1, 2.6.2), it does indeed work for 2.7, but this version comes with other changes which might not be suitable for everybody. 
I don't think ``nighly`` is the version which you can safely run on production,  which means that basically saving does not work and issue is not solved. 
@pooya-mohammadi loading in the very same notebook is not always possible, for instance when you try to optimize the model for production hardware and methods under the hood actually load graph via ``tf.saved_model.load(..)``. 
After some investigation I found a few things:
- Loading model (``tf.saved_model.load(...)``) works somehow if you add an import ``import tensorflow_io as tfio``, but that's might be specific for my model. 
- It is not always possible to add to runtime ``tensorflow_io`` so I also tried saving the model after training without the optimizer(``tf.keras.models.save_model( ...,include_optimizer=False)``) which also worked. 

This makes me believe that there is some problem with the graph if you add an optimizer while saving it. The issue is solved on TF-2-7. 
I will try to add Colab with a meaningful example soon, but ofc it will need to be restarted between saving the model and loading it, to simulate the behaviour of saving and loading in different notebooks (different kernel/scope).

**Comment by pooya-mohammadi** [comment]
@rpytel1 Tnx for sharing. I had a custom layer in my network, which I knew would cause errors, and indeed it did. How about your optimizer? Is it a custom or one of the pre-defined ones?

**Comment by rpytel1** [comment]
@pooya-mohammadi I use only ``tf.keras.optimizers.Adam`` with ``tf.keras.experimental.CosineDecay`` learning rate. But indeed I do have some custom layers. Also as stated on multiple other similar issues, this used to work earlier (i.e. TF-2.3.4) without adding anything to ``custom_object`` flags.

**Comment by Aida-yy** [comment]
I have same problem, in TF2.6. But, I fix it just need append
`from tensorflow.keras import Model`

hope it's useful for you.
