### PR TITLE
docs: update PJRT plugin README to use kCpuPjrtName

### LINKED ISSUE #119584: [DOCS] One stale README content
### Issue type

Documentation Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

N/A

### Custom code

No

### OS platform and distribution

_No response_

### Mobile device

_No response_

### Python version

_No response_

### Bazel version

_No response_

### GCC/compiler version

_No response_

### CUDA/cuDNN version

_No response_

### GPU model and memory

_No response_

### Current behavior?

 I noticed one stale documentation references.                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
 1. The lib_package README still documents Java/JNI packaging artifacts, but the corresponding lib_package Java/JNI packaging targets are no longer present in the BUILD file (where it was deleted in  https://github.com/tensorflow/tensorflow/commit/0ba4a4f4dcbffbe754278e91b8b512f64503355a)                                                                                                                                                             
 https://github.com/tensorflow/tensorflow/blob/8baaa8cbc5fd22136d8a411d7290b90b32fc897c/tensorflow/tools/lib_package/README.md#L27-L49                                                                                                     
                                                                                                                                                                                                                                           
 Suggested fixes:                                                                                                                                                                                                                          
 - Delete the stale ## Java library section from tensorflow/tools/lib_package/README.md.                                                                                                                                                   
                                                                                                                                                                                                                                           
 I have a fix in my fork if a PR would be helpful:                                                                                                                                                                                         
                                                                                                                                                                                                                                                   
 https://github.com/doehyunbaek/tensorflow/commit/e6dc506c3a9819d4291da83ee44051183fb3b0ec                                                                                                                                                 
                                                                                                                                                                                                                                           
 Happy to split this into two separate issues/PRs if preferred.    

### Standalone code to reproduce the issue

```shell
There is no applicable code as this is a documentation issue.
```

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by akinshaywai**
### What changed

Fixes #119584 (partially — PJRT README part).

The PJRT plugin README example used `PJRT_PLUGIN_NAME_CPU`, which was replaced by `kCpuPjrtName` in `plugin_names.h` (introduced in commit ed770aaa). The old constant no longer exists, making the example misleading for anyone trying to follow the documentation.

**Change:** One line in `third_party/xla/xla/pjrt/plugin/README.md` — replace `PJRT_PLUGIN_NAME_CPU` with `kCpuPjrtName` to match the current definition in `plugin_names.h`.

### Why

Stale constant name in an example confuses contributors and users trying to use the PJRT plugin API. The fix aligns the documentation with the actual source code.

### CODE REVIEW

**Comment by doehyunbaek** [comment]
Hi @akinshaywai thanks for the PR.
I think this PR can be closed as https://github.com/openxla/xla/pull/44805 is already merged :)

**Review by ratgr — COMMENTED** [review]
Thank you for your contribution!
  
  However, this change has already been implemented at HEAD. Additionally, note that `kCpuPjrtName` is defined as `absl::string_view` in `plugin_names.h`, so using `const char*` as shown in the snippet would cause a compilation error.
  
  Closing this as obsolete.

**Comment by ratgr** [comment]
Thank you for your contribution!

However, this change has already been implemented at HEAD. Additionally, note that kCpuPjrtName is defined as absl::string_view in plugin_names.h, so using const char* as shown in the snippet would cause a compilation error.

Closing this as obsolete.
