### PR TITLE
Fix undefined reference to memset

### LINKED ISSUE #61584: Build failure on AARCH64 - undeclared identifier 'memset'
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

git HEAD

### Custom code

No

### OS platform and distribution

Ubuntu 20.04

### Mobile device

n/a

### Python version

3.9.16

### Bazel version

6.1.0

### GCC/compiler version

16.0.6

### CUDA/cuDNN version

n/a

### GPU model and memory

n/a

### Current behavior?

Build fails since commit https://github.com/tensorflow/tensorflow/commit/4993fb9fe4e4dbe26657b3bb88dab152ab397b8c

### Standalone code to reproduce the issue

```shell
bazel build --config=mkl_aarch64_threadpool --copt=-flax-vector-conversions --test_env=TF_ENABLE_ONEDNN_OPTS=1 --test_env=TF2_BEHAVIOR=1 --define=tf_api_version=2 -- //tensorflow/tools/pip_package:build_pip_package
```

### Relevant log output

```shell
ERROR: /workspace/tensorflow/lite/kernels/internal/BUILD:448:11: Compiling tensorflow/lite/kernels/internal/optimized/4bit/neon_fully_connected.cc failed: (Exit 1): clang failed: error executing command (from target //tensorflow/lite/kernels/internal:optimized_4bit) 
  (cd /home/andrew/src/tf_test/tensorflow-git/bazel-ci_build-cache/.cache/bazel/_bazel_andrew/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow && \
  exec env - \
    CACHEBUSTER=20220325 \
    PATH=/home/andrew/src/tf_test/tensorflow-git/bazel-ci_build-cache/.cache/bazelisk/downloads/bazelbuild/bazel-6.1.0-linux-arm64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
    PWD=/proc/self/cwd \
    TF2_BEHAVIOR=1 \
  /usr/lib/llvm-16/bin/clang -MD -MF bazel-out/aarch64-opt/bin/tensorflow/lite/kernels/internal/_objs/optimized_4bit/neon_fully_connected.pic.d '-frandom-seed=bazel-out/aarch64-opt/bin/tensorflow/lite/kernels/internal/_objs/optimized_4bit/neon_fully_connected.pic.o' -DFC_4BIT_NEON '-DBAZEL_CURRENT_REPOSITORY=""' -iquote . -iquote bazel-out/aarch64-opt/bin -iquote external/cpuinfo -iquote bazel-out/aarch64-opt/bin/external/cpuinfo -isystem external/cpuinfo/include -isystem bazel-out/aarch64-opt/bin/external/cpuinfo/include -isystem external/cpuinfo/src -isystem bazel-out/aarch64-opt/bin/external/cpuinfo/src -fmerge-all-constants -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fPIC -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wno-invalid-partial-specialization -fno-omit-frame-pointer -no-canonical-prefixes -DNDEBUG -g0 -O2 -ffunction-sections -fdata-sections -Wno-all -Wno-extra -Wno-deprecated -Wno-deprecated-declarations -Wno-ignored-attributes -Wno-array-bounds -Wunused-result '-Werror=unused-result' -Wswitch '-Werror=switch' '-Wno-error=unused-but-set-variable' -DAUTOLOAD_DYNAMIC_KERNELS -Wno-gnu-offsetof-extensions '-mtune=generic' '-march=armv8-a' -O3 -flax-vector-conversions '-std=c++17' -DFARMHASH_NO_CXX_STRING -Wno-sign-compare -O3 -fno-exceptions -O3 '--sysroot=/dt10' -c tensorflow/lite/kernels/internal/optimized/4bit/neon_fully_connected.cc -o bazel-out/aarch64-opt/bin/tensorflow/lite/kernels/internal/_objs/optimized_4bit/neon_fully_connected.pic.o)
# Configuration: 70a2ceb8c9b79ab96bab8f0b73bbfb70969f7e2a66f605b1d1332a62f7eef342
# Execution platform: @local_execution_config_platform//:platform
tensorflow/lite/kernels/internal/optimized/4bit/neon_fully_connected.cc:284:3: error: use of undeclared identifier 'memset'
  memset(*dest, static_cast<uint8_t>(119), sizeof(uint8_t) * size);
  ^
tensorflow/lite/kernels/internal/optimized/4bit/neon_fully_connected.cc:313:3: error: use of undeclared identifier 'memset'
  memset(data, 0, sizeof(int8_t) * size);
  ^
tensorflow/lite/kernels/internal/optimized/4bit/neon_fully_connected.cc:314:3: error: use of undeclared identifier 'memset'
  memset(input_offsets, 0, sizeof(int32_t) * layout_rows);
  ^
3 errors generated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 23.741s, Critical Path: 7.00s
INFO: 439 processes: 339 internal, 100 local.
FAILED: Build did NOT complete successfully
```

### PR DESCRIPTION
**Pull request by elfringham**
Add include of cstring to resolve symbol

Fixes: https://github.com/tensorflow/tensorflow/issues/61584

### CODE REVIEW

**Comment by elfringham** [comment]
Made moot by https://github.com/tensorflow/tensorflow/commit/57203ff7024239fe6caaf9be54744f2c990a00ef
