### ISSUE TITLE
Tensorflow-2.3.0 build failed

### ISSUE THREAD

**Issue by beew** [tensorflow/tensorflow#41926]
**System information**
- OS Platform and Distribution :Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 2.3.0
- Python version: 3.8.5
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): 5.4.0
- CUDA/cuDNN version:  Cuda10.0, cudnn 7.6.5.32
- GPU model and memory: GTX1070 , 8G

**Describe the problem**
Cannot build tensorflow

Tensorflow configured with cuda and tensorrt enabled

build with

```
bazel build --config=opt --config=cuda --copt=-mavx --copt=-mavx2 --copt=-msse4.1 --copt=-msse4.2 --copt=-mfma --copt=-mfpmath=both //tensorflow/tools/pip_package:build_pip_package 
```

build failed with these output

```
INFO: From ProtoCompile tensorflow/lite/toco/toco_flags.pb.h:
bazel-out/k8-opt/bin/external/com_google_protobuf/src: warning: directory does not exist.
ERROR: /home/bernard/opt/python38/tensorflow-2.3.0/tensorflow/core/kernels/BUILD:5123:1: C++ compilation of rule '//tensorflow/core/kernels:dilation_ops_gpu' failed (Exit 1)
external/com_google_absl/absl/time/internal/cctz/include/cctz/civil_time_detail.h: In function ‘constexpr absl::lts_2020_02_25::time_internal::cctz::detail::civil_day absl::lts_2020_02_25::time_internal::cctz::detail::next_weekday(absl::lts_2020_02_25::time_internal::cctz::detail::civil_day, absl::lts_2020_02_25::time_internal::cctz::detail::weekday)’:
external/com_google_absl/absl/time/internal/cctz/include/cctz/civil_time_detail.h:567:20: error: call to non-constexpr function ‘absl::lts_2020_02_25::time_internal::cctz::detail::civil_time<absl::lts_2020_02_25::time_internal::cctz::detail::day_tag> absl::lts_2020_02_25::time_internal::cctz::detail::operator+(absl::lts_2020_02_25::time_internal::cctz::detail::civil_time<absl::lts_2020_02_25::time_internal::cctz::detail::day_tag>, absl::lts_2020_02_25::time_internal::cctz::diff_t)’
           return cd + (j - i);
                    ^
external/com_google_absl/absl/time/internal/cctz/include/cctz/civil_time_detail.h: In function ‘constexpr absl::lts_2020_02_25::time_internal::cctz::detail::civil_day absl::lts_2020_02_25::time_internal::cctz::detail::prev_weekday(absl::lts_2020_02_25::time_internal::cctz::detail::civil_day, absl::lts_2020_02_25::time_internal::cctz::detail::weekday)’:
external/com_google_absl/absl/time/internal/cctz/include/cctz/civil_time_detail.h:587:20: error: call to non-constexpr function ‘absl::lts_2020_02_25::time_internal::cctz::detail::civil_time<absl::lts_2020_02_25::time_internal::cctz::detail::day_tag> absl::lts_2020_02_25::time_internal::cctz::detail::operator-(absl::lts_2020_02_25::time_internal::cctz::detail::civil_time<absl::lts_2020_02_25::time_internal::cctz::detail::day_tag>, absl::lts_2020_02_25::time_internal::cctz::diff_t)’
           return cd - (j - i);
                    ^
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1001.142s, Critical Path: 93.36s
INFO: 4993 processes: 4993 local.
FAILED: Build did NOT complete successfully
```

**Comment by Saduf2019** [comment]
@beew 
Please refer to [this issue](https://github.com/tensorflow/tensorflow/issues/22082#issuecomment-451908492) with same error and update us. [[link](https://stackoverflow.com/questions/52437344/bazel-build-failed-after-updated-command-line-tool-in-mac)]

**Comment by beew** [comment]
@Saduf2019

Not work, updated setuptools to the latest version, failed again, similar but different error

```
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/bernard/opt/python38/tensorflow-2.3.0/tensorflow/python/tools/BUILD:226:1 C++ compilation of rule '//tensorflow/core/kernels:matrix_diag_op_gpu' failed (Exit 1)
INFO: Elapsed time: 2415.388s, Critical Path: 105.97s
INFO: 7622 processes: 7622 local.
FAILED: Build did NOT complete successfully
```

Should add that I have the same setup with bazel 2.0 and was able to build tf 2.2.0 without a hitch.

**Comment by lissyx** [comment]
Facing the same issue on CI where we also use Ubuntu 16.04 + GCC 5.4.0

**Comment by lissyx** [comment]
>  Please refer to [this issue](https://github.com/tensorflow/tensorflow/issues/22082#issuecomment-451908492) with same error and update us. [[link](https://stackoverflow.com/questions/52437344/bazel-build-failed-after-updated-command-line-tool-in-mac)]

@Saduf2019 Your two links are completely different issues.

**Comment by lissyx** [comment]
According to https://github.com/HowardHinnant/date/issues/477 it might be because of GCC itself.

**Comment by beew** [comment]
@lissyx 

I have tried multiple versions of gcc but still not working.

I tried to compile with gcc-9.3.0 installed in custom location but bazel said
```
ERROR: /home/bernard/opt/python38/tensorflow-2.3.0/tensorflow/core/kernels/BUILD:1232:1: C++ compilation of rule '//tensorflow/core/kernels:quantize_and_dequantize_op_gpu' failed (Exit 1)
In file included from /home/bernard/opt/cuda-10.0/cuda/bin/..//include/cuda_runtime.h:83,
                 from <command-line>:
/home/bernard/opt/cuda-10.0/cuda/bin/..//include/crt/host_config.h:129:2: error: #error -- unsupported GNU version! gcc versions later than 7 are not supported!
```
I then tried gcc-7.5 and it said libstdc++.so.6 is missing GLIBCXX_3.4.26 (which is supported for libstdc++.so.6 in gcc-9.3.0)

**Comment by lissyx** [comment]
> I have tried multiple versions of gcc but still not working.

Using backported gcc-6 from ubuntu toolchain team worked for me: https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test?field.series_filter=xenial

Just install gcc-6, g++-6 and either setup alternatives for gcc/g++ or `CC=gcc-6 CXX=g++-6` should do the trick.

**Comment by lissyx** [comment]
@beew You can also take a look at the header, there is support for disabling `constexpr` in some cases, I might use that and add a hack.

**Comment by beew** [comment]
@lissyx 
Hi,

Compiling with gcc-6.5 works, however, update alternatives is not enough,  I got the error
```
/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found 

```
So I had to make a conf file in /etc/ld.so.conf.d with /path/to/gcc-6.5.0/lib64 followed by sudo ldconfig

Build was successful, but I am wondering if it will have other side effects by leaving this version of libstdc++.so.6 in the ld path? (tensorflow 2.3 won't run without it)

**Comment by Saduf2019** [comment]
@beew 
Please refer to these resolved issues for the above missing file error:
[link](https://github.com/lhelontra/tensorflow-on-arm/issues/13) [link1](https://stackoverflow.com/questions/43070900/version-glibcxx-3-4-22-not-found) [link2](https://github.com/EOSIO/eosio.cdt/issues/285) [link3](https://community.rstudio.com/t/libstdc-so-6-version-glibcxx-3-4-22-not-found/63472/6) and update us.

**Comment by lissyx** [comment]
@Saduf2019 The issue is clearly just that this cannot build with GCC 5.4. I have been able to do so with a little nasty patch: https://github.com/mozilla/tensorflow/commit/6fad14b203093e7a19301c4ef51a87fce71e38cb#diff-18a66e25fbcbd72730332a799ddee2ec

This does had a define `NO_CONSTEXPR_FOR_YOU` that I can set at build time and leverage the ability to build this part without `constexpr` at all.

**Comment by lissyx** [comment]
> Build was successful, but I am wondering if it will have other side effects by leaving this version of libstdc++.so.6 in the ld path? (tensorflow 2.3 won't run without it)

That depends on your needs.

**Comment by beew** [comment]
@lissyx
> > Build was successful, but I am wondering if it will have other side effects by leaving this version of libstdc++.so.6 in the ld path? (tensorflow 2.3 won't run without it)
> 
> That depends on your needs.

Hi, My question is really whether the presence of a higher  libstdc++so.6 in the library path would interfere with projects compiled with a lower version. All the links you provide involves upgrading libstdc++so.6 in one way or the other basically like what I have done, by making a config file in /etc/ld.so.conf.d, except I keep the older system version as well.

I could set LD_LIBRARY_PATH at runtime but it is kind of cumbersome (or by adding it to LD_LIBRARY_PATH but it has the same concern) BTW setting LD_LIBRARY_PATH doesn't work for compile time since bazel couldn't find it, only adding to /etc/ld.so.conf.d works.

**Comment by npanpaliya** [comment]
> @Saduf2019 The issue is clearly just that this cannot build with GCC 5.4. I have been able to do so with a little nasty patch: [mozilla@6fad14b#diff-18a66e25fbcbd72730332a799ddee2ec](https://github.com/mozilla/tensorflow/commit/6fad14b203093e7a19301c4ef51a87fce71e38cb#diff-18a66e25fbcbd72730332a799ddee2ec)
> 
> This does had a define `NO_CONSTEXPR_FOR_YOU` that I can set at build time and leverage the ability to build this part without `constexpr` at all.

I've been facing the same error with gcc 5.4 but I can't update my gcc as anaconda doesn't have 6.x packages for gcc/gxx. I tried above mentioned patch as well as defined the macro `NO_CONSTEXPR_FOR_YOU` in bazelrc as below, still same error -
```
build:opt --copt=-DNO_CONSTEXPR_FOR_YOU=1
build --define=NO_CONSTEXPR_FOR_YOU=1
```
It looks the way it is to be defined isn't right. Could someone please help me define this macro?

**Comment by lissyx** [comment]
> > @Saduf2019 The issue is clearly just that this cannot build with GCC 5.4. I have been able to do so with a little nasty patch: [mozilla@6fad14b#diff-18a66e25fbcbd72730332a799ddee2ec](https://github.com/mozilla/tensorflow/commit/6fad14b203093e7a19301c4ef51a87fce71e38cb#diff-18a66e25fbcbd72730332a799ddee2ec)
> > This does had a define `NO_CONSTEXPR_FOR_YOU` that I can set at build time and leverage the ability to build this part without `constexpr` at all.
> 
> I've been facing the same error with gcc 5.4 but I can't update my gcc as anaconda doesn't have 6.x packages for gcc/gxx. I tried above mentioned patch as well as defined the macro `NO_CONSTEXPR_FOR_YOU` in bazelrc as below, still same error -
> 
> ```
> build:opt --copt=-DNO_CONSTEXPR_FOR_YOU=1
> build --define=NO_CONSTEXPR_FOR_YOU=1
> ```
> 
> It looks like the way I've defined it isn't right. Could someone please help me define this macro?

Have you applied the linked patch?

Once that's the case, `--copt=-DNO_CONSTEXPR_FOR_YOU=1` should be enough.

**Comment by npanpaliya** [comment]
Yes, I've it applied -
```
diff --git a/third_party/com_google_absl_fix_mac_and_nvcc_build.patch b/third_party/com_google_absl_fix_mac_and_nvcc_build.patch
index 271e941..81c8e5d 100644
--- a/third_party/com_google_absl_fix_mac_and_nvcc_build.patch
+++ b/third_party/com_google_absl_fix_mac_and_nvcc_build.patch
@@ -1,3 +1,14 @@
+--- ./absl/time/internal/cctz/include/cctz/civil_time_detail.h 2020-08-06 01:33:56.005757145 +0200
++++ ./absl/time/internal/cctz/include/cctz/civil_time_detail.h 2020-08-06 01:33:35.460579387 +0200
+@@ -23,7 +23,7 @@
+ #include "absl/base/config.h"
+
+ // Disable constexpr support unless we are in C++14 mode.
+-#if __cpp_constexpr >= 201304 || (defined(_MSC_VER) && _MSC_VER >= 1910)
++#if (!defined(NO_CONSTEXPR_FOR_YOU) && __cpp_constexpr >= 201304) || (defined(_MSC_VER) && _MSC_VER >= 1910)
+ #define CONSTEXPR_D constexpr  // data
+ #define CONSTEXPR_F constexpr  // function
+ #define CONSTEXPR_M constexpr  // member
 --- ./absl/time/internal/cctz/BUILD.bazel      2019-09-23 13:20:52.000000000 -0700
 +++ ./absl/time/internal/cctz/BUILD.bazel.fixed        2019-09-23 13:20:48.000000000 -0700
 @@ -74,15 +74,6 @@
@@ -301,4 +312,3 @@
 +        .internal_compressed_tuple::template Storage<CompressedTuple, I>::get();
    }
  };
```

**Comment by lissyx** [comment]
Well, it's working for us, I can't do more.

**Comment by npanpaliya** [comment]
With same gcc 5.4?

**Comment by lissyx** [comment]
> With same gcc 5.4?

Yes.

**Comment by npanpaliya** [comment]
Okay. Thanks.

**Comment by npanpaliya** [comment]
@lissyx - The macro setting mentioned in bazelrc worked for cpu builds but not for gpu build. It looks like the same macro has to be defined for nvcc too. I've tried this `build:cuda --define=-DNO_CONSTEXPR_FOR_YOU=1` and waiting for the build to get finished.

**Comment by lissyx** [comment]
> @lissyx - The macro setting mentioned in bazelrc worked for cpu builds but not for gpu build. It looks like the same macro has to be defined for nvcc too. I've tried this `build:cuda --define=-DNO_CONSTEXPR_FOR_YOU=1` but it didn't work. Could you please help me set the same macro for cu.cc files?

no, I can't help you. again, what I shared is what we use and it works everywhere.

**Comment by gunan** [comment]
The build is also working fine for us. I cannot reproduce the issue.
I would recommend reaching out to absl team for support.

Since we cannot reproduce the problem, one way we can help is if you can create a docker container where we can reproduce the problem, we may be able to debug and help.

**Comment by lissyx** [comment]
> The build is also working fine for us. I cannot reproduce the issue.

@gunan Have you tried on a distro using GCC 5.4 ?

**Comment by npanpaliya** [comment]
Thanks a lot everyone. I was able to fix the problem using GCC 5.4 by adding another line in bazelrc for setting --host_copt too as below.
```
build:opt --copt=-DNO_CONSTEXPR_FOR_YOU=1
build:opt --host_copt=-DNO_CONSTEXPR_FOR_YOU=1
```

**Comment by Yuze-HE** [comment]
> Thanks a lot everyone. I was able to fix the problem using GCC 5.4 by adding another line in bazelrc for setting --host_copt too as below.
> 
> ```
> build:opt --copt=-DNO_CONSTEXPR_FOR_YOU=1
> build:opt --host_copt=-DNO_CONSTEXPR_FOR_YOU=1
> ```

Hi, I'm really confused about how to use the patch and where to set these two lines you mentioned. Could you please explain more details? Thanks a lot!

**Comment by npanpaliya** [comment]
The patch being talked here is `third_party/com_google_absl_fix_mac_and_nvcc_build.patch`. This patch is already being used by TF here https://github.com/tensorflow/tensorflow/blob/v2.3.0/tensorflow/workspace.bzl#L227. But we need to update it by adding the additional stuff mentioned https://github.com/mozilla/tensorflow/commit/6fad14b203093e7a19301c4ef51a87fce71e38cb#diff-18a66e25fbcbd72730332a799ddee2ec.  And then add following two lines in .bazelrc file which is in tensorflow source code.
```
build:opt --copt=-DNO_CONSTEXPR_FOR_YOU=1
build:opt --host_copt=-DNO_CONSTEXPR_FOR_YOU=1
```

**Comment by Yuze-HE** [comment]
> The patch being talked here is `third_party/com_google_absl_fix_mac_and_nvcc_build.patch`. This patch is already being used by TF here https://github.com/tensorflow/tensorflow/blob/v2.3.0/tensorflow/workspace.bzl#L227. But we need to update it by adding the additional stuff mentioned [mozilla@6fad14b#diff-18a66e25fbcbd72730332a799ddee2ec](https://github.com/mozilla/tensorflow/commit/6fad14b203093e7a19301c4ef51a87fce71e38cb#diff-18a66e25fbcbd72730332a799ddee2ec). And then add following two lines in .bazelrc file which is in tensorflow source code.
> 
> ```
> build:opt --copt=-DNO_CONSTEXPR_FOR_YOU=1
> build:opt --host_copt=-DNO_CONSTEXPR_FOR_YOU=1
> ```

Thanks for your reply. What's the specific command line to add the additional stuff? Could you please tell me the detailed steps? I'm not familiar with the operations of patches. Thanks again!

**Comment by npanpaliya** [comment]
@Yuze-HE 
To update the existing patch, I did following -
1. Download the abseil code mentioned in tensorflow/workspace.bzl at here https://github.com/tensorflow/tensorflow/blob/v2.3.0/tensorflow/workspace.bzl#L232. 
`wget https://github.com/abseil/abseil-cpp/archive/df3ea785d8c30a9503321a3d35ee7d35808f190d.tar.gz`
2. Extract the downloaded tar 
`tar -xvf df3ea785d8c30a9503321a3d35ee7d35808f190d.tar.gz`
3. Create a copy of this extracted tar as abseil_orig
4. Go to the extracted directory and apply the original patch which is https://github.com/tensorflow/tensorflow/blob/v2.3.0/third_party/com_google_absl_fix_mac_and_nvcc_build.patch using below command -
`patch -p1 < <path_to_tensorflow>/third_party/com_google_absl_fix_mac_and_nvcc_build.patch`
5. Hand edit the files mentioned here https://github.com/mozilla/tensorflow/commit/6fad14b203093e7a19301c4ef51a87fce71e38cb#diff-18a66e25fbcbd72730332a799ddee2ec.
6. Take the diff of abseil_org with this abseil directory which has got modified files because of above two steps, using below command -
`diff -Naur abseil_org abseil > <path_to_tensorflow>/third_party/com_google_absl_fix_mac_and_nvcc_build.patch`
7. Now, restart the TF build.

**Comment by Yuze-HE** [comment]
> @Yuze-HE
> To update the existing patch, I did following -
> 
> 1. Download the abseil code mentioned in tensorflow/workspace.bzl at here https://github.com/tensorflow/tensorflow/blob/v2.3.0/tensorflow/workspace.bzl#L232.
>    `wget https://github.com/abseil/abseil-cpp/archive/df3ea785d8c30a9503321a3d35ee7d35808f190d.tar.gz`
> 2. Extract the downloaded tar
>    `tar -xvf df3ea785d8c30a9503321a3d35ee7d35808f190d.tar.gz`
> 3. Create a copy of this extracted tar as abseil_orig
> 4. Go to the extracted directory and apply the original patch which is https://github.com/tensorflow/tensorflow/blob/v2.3.0/third_party/com_google_absl_fix_mac_and_nvcc_build.patch using below command -
>    `patch -p1 < <path_to_tensorflow>/third_party/com_google_absl_fix_mac_and_nvcc_build.patch`
> 5. Hand edit the files mentioned here [mozilla@6fad14b#diff-18a66e25fbcbd72730332a799ddee2ec](https://github.com/mozilla/tensorflow/commit/6fad14b203093e7a19301c4ef51a87fce71e38cb#diff-18a66e25fbcbd72730332a799ddee2ec).
> 6. Take the diff of abseil_org with this abseil directory which has got modified files because of above two steps, using below command -
>    `diff -Naur abseil_org abseil > <path_to_tensorflow>/third_party/com_google_absl_fix_mac_and_nvcc_build.patch`
> 7. Now, restart the TF build after updating .bazelrc with the two lines mentioned in my previous comment.

Thank you very much!

**Comment by AndreyPlotkinOr** [comment]
Is it something that will be integrated into TF build is some reasonable time period?

**Comment by AndreyPlotkinOr** [comment]
@npanpaliya "edit the files mentioned here mozilla@6fad14b#diff-18a66e25fbcbd72730332a799ddee2ec."
What files do you mean? Or do I have to apply this patch as well?

**Comment by npanpaliya** [comment]
Editing the files in absl as per the changes mentioned at mozilla/tensorflow@6fad14b#diff-18a66e25fbcbd72730332a799ddee2ec.
Then create a single patch of existing content of https://github.com/tensorflow/tensorflow/blob/v2.3.0/third_party/com_google_absl_fix_mac_and_nvcc_build.patch and changes in mozilla/tensorflow in that commit.

Regarding TF including these changes - I think it will probably not included by TF as these changes are needed to get TF built with older gcc 5.4. But TF community can comment more on this.

**Comment by AndreyPlotkinOr** [comment]
Same issue with
TF 2.4.0-rc3
Python 3.6.9
GPU: Tesla T4 | NVIDIA driver: 455.45.01 | CUDA: 10.1.243 | CUDNN: 7.6.4
Bazel 3.1.0

**Comment by AndreyPlotkinOr** [comment]
@npanpaliya Are you talking about this patch? https://github.com/mozilla/tensorflow/commit/6fad14b203093e7a19301c4ef51a87fce71e38cb#diff-8757a02eb58c1cd11dda17ad77b09ded795db562ed05acd02248b00d141356e6

**Comment by AndreyPlotkinOr** [comment]
> Editing the files in absl as per the changes mentioned at [mozilla/tensorflow@6fad14b](https://github.com/mozilla/tensorflow/commit/6fad14b)#diff-18a66e25fbcbd72730332a799ddee2ec.
> Then create a single patch of existing content of https://github.com/tensorflow/tensorflow/blob/v2.3.0/third_party/com_google_absl_fix_mac_and_nvcc_build.patch and changes in mozilla/tensorflow in that commit.
> 
> Regarding TF including these changes - I think it will probably not included by TF as these changes are needed to get TF built with older gcc 5.4. But TF community can comment more on this.

I have 3 folder:
1) Original absl in TF folder
2) abseil-cpp-df3ea785d8c30a9503321a3d35ee7d35808f190d (extracted from tar.gz)
3) abseil_orig (copied abseil-cpp-df3ea785d8c30a9503321a3d35ee7d35808f190d folder)

I applied <path_to_tensorflow>/third_party/com_google_absl_fix_mac_and_nvcc_build.patch on 2nd folder.

Now you say to hand edit files from mozilla patch.
I understand that there are 2 files to be edited:
1)./absl/time/internal/cctz/include/cctz/civil_time_detail.h - it will add NO_CONSTEXPR_FOR_YOU flag
2) ./absl/time/internal/cctz/BUILD.bazel.fixed - I don't see it in any folder. What should I do here?

**Comment by AndreyPlotkinOr** [comment]
I ended up adding 

```
--- ./absl/time/internal/cctz/include/cctz/civil_time_detail.h	2020-08-06 01:33:56.005757145 +0200
+++ ./absl/time/internal/cctz/include/cctz/civil_time_detail.h	2020-08-06 01:33:35.460579387 +0200
@@ -23,7 +23,7 @@
 #include "absl/base/config.h"
 
 // Disable constexpr support unless we are in C++14 mode.
-#if __cpp_constexpr >= 201304 || (defined(_MSC_VER) && _MSC_VER >= 1910)
+#if (!defined(NO_CONSTEXPR_FOR_YOU) && __cpp_constexpr >= 201304) || (defined(_MSC_VER) && _MSC_VER >= 1910)
 #define CONSTEXPR_D constexpr  // data
 #define CONSTEXPR_F constexpr  // function
 #define CONSTEXPR_M constexpr  // member
```

at the beginning of <path_to_tensorflow>/third_party/com_google_absl_fix_mac_and_nvcc_build.patch

+

adding 

```
build:opt --copt=-DNO_CONSTEXPR_FOR_YOU=1
build:opt --host_copt=-DNO_CONSTEXPR_FOR_YOU=1
```

in .bazelrc

Build completed successfully with 
bazel build --config=cuda --config=opt --config=v2 //tensorflow/tools/pip_package:build_pip_package

**Comment by gmt710** [comment]
Hello, I followed your steps to compile tensorflow2.3.0, but it got this error:
```
./tensorflow/stream_executor/lib/statusor_internals.h:165:76: error: invalid static_cast from type 'const Status {aka const tensorflow::Status}' to type 'stream_executor::port::Status& {aka tensorflow::Status&}'
./tensorflow/stream_executor/lib/statusor_internals.h: In instantiation of 'bool stream_executor::port::internal_statusor::StatusOrData<T>::ok() const [with T = std::unique_ptr<stream_executor::dnn::RnnDescriptor>]':

```

My enviroment:
```
ubuntu16.04
cuda9.0
gcc5.4.0
tensorflow2.3.0
```
It's so wired. I have no idea about how to correct this ?
would you mind giving me some suggestion ? 
Thanks !

**Comment by AndreyPlotkinOr** [comment]
@gmt710 I think your exception is not related to this issue.
Probably: https://github.com/tensorflow/tensorflow/issues/20764

**Comment by gmt710** [comment]
Yes, but [#20764](https://github.com/tensorflow/tensorflow/issues/20764) is not solved.

**Comment by ssrokyz** [comment]
> I ended up adding
> 
> ```
> --- ./absl/time/internal/cctz/include/cctz/civil_time_detail.h	2020-08-06 01:33:56.005757145 +0200
> +++ ./absl/time/internal/cctz/include/cctz/civil_time_detail.h	2020-08-06 01:33:35.460579387 +0200
> @@ -23,7 +23,7 @@
>  #include "absl/base/config.h"
>  
>  // Disable constexpr support unless we are in C++14 mode.
> -#if __cpp_constexpr >= 201304 || (defined(_MSC_VER) && _MSC_VER >= 1910)
> +#if (!defined(NO_CONSTEXPR_FOR_YOU) && __cpp_constexpr >= 201304) || (defined(_MSC_VER) && _MSC_VER >= 1910)
>  #define CONSTEXPR_D constexpr  // data
>  #define CONSTEXPR_F constexpr  // function
>  #define CONSTEXPR_M constexpr  // member
> ```
> 
> at the beginning of <path_to_tensorflow>/third_party/com_google_absl_fix_mac_and_nvcc_build.patch
> 
> 
> adding
> 
> ```
> build:opt --copt=-DNO_CONSTEXPR_FOR_YOU=1
> build:opt --host_copt=-DNO_CONSTEXPR_FOR_YOU=1
> ```
> 
> in .bazelrc
> 
> Build completed successfully with
> bazel build --config=cuda --config=opt --config=v2 //tensorflow/tools/pip_package:build_pip_package

worked for me
cuda 10.2, tensorflow 2.4.1, centos 7

**Comment by gmt710** [comment]
wow, it's a good idea.
But I only can use cuda9.0.

**Comment by gmt710** [comment]
cuda10.2
I've installed tensorflow yet and do not need build tensorflow.

**Comment by njzjz** [comment]
> at the beginning of <path_to_tensorflow>/third_party/com_google_absl_fix_mac_and_nvcc_build.patch

In v2.5, `com_google_absl_fix_mac_and_nvcc_build.patch` has been moved to `tensorflow/third_party/absl`
