### ISSUE TITLE
 Can't use multiple tensorboard callbacks in TF2.8

### ISSUE THREAD

**Issue by anth2o** [tensorflow/tensorflow#55224]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.8.0-rc1-32-g3f878cff5b6 2.8.0
- Python version: 3.8.12
- Bazel version (if compiling from source):
- GPU model and memory: None
- Exact command to reproduce:

**Describe the problem.**

I am using multiple tensoboard callbacks with the same Model. Since I upgraded Tensorflow from 2.5 to 2.8, I have an error at the end of the training when closing the Tensorboard writers.  
I opened an issue on the Keras repo https://github.com/keras-team/keras/issues/16235, but after diving a little bit more into the source code, I think the issue directly comes from Tensorflow and not from keras. This [commit](https://github.com/tensorflow/tensorflow/commit/6edaa9105a2cd91369ae69da0dd10993f77557b3) might have introduced the bug.

**Describe the current behavior.**

The training doesn't end correctly because of a Tensrboard callback error.

**Describe the expected behavior.**

It used to work in TF2.5 and it should still do.

**Standalone code to reproduce the issue**.

```python
import tensorflow as tf
import tempfile

with tempfile.TemporaryDirectory() as tmpdir:
    batch_size = 3
    nb_samples = 10
    update_freq = 2
    inputs = tf.random.normal((nb_samples, 2))
    outputs = tf.random.normal((nb_samples, 10))
    dataset = tf.data.Dataset.from_tensor_slices((inputs, outputs)).batch(batch_size)
    dataset_val = tf.data.Dataset.from_tensor_slices((inputs, outputs)).batch(batch_size)
    nb_epochs = 5

    model = tf.keras.Sequential([tf.keras.layers.Dense(10)])
    optimizer = tf.keras.optimizers.SGD()

    tensorboard_kwargs = dict(profile_batch=0, update_freq=update_freq, write_graph=False)

    tensorboard_callbacks = [
        tf.keras.callbacks.TensorBoard(tmpdir.join("tensorboard_1"), **tensorboard_kwargs),
        tf.keras.callbacks.TensorBoard(tmpdir.join("tensorboard_2"), **tensorboard_kwargs)
    ]
    model.compile(optimizer, "mse")
    model.fit(
        dataset,
        batch_size=batch_size,
        callbacks=tensorboard_callbacks,
        epochs=nb_epochs,
        validation_data=dataset_val
    )
```

**Stacktrace**

```bash
2022-03-14 13:24:44.758272: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Epoch 1/5
4/4 [==============================] - 1s 43ms/step - loss: 1.3517 - val_loss: 1.3417
Epoch 2/5
4/4 [==============================] - 0s 5ms/step - loss: 1.3396 - val_loss: 1.3297
Epoch 3/5
4/4 [==============================] - 0s 8ms/step - loss: 1.3276 - val_loss: 1.3178
Epoch 4/5
4/4 [==============================] - 0s 5ms/step - loss: 1.3158 - val_loss: 1.3062
Epoch 5/5
4/4 [==============================] - 0s 10ms/step - loss: 1.3042 - val_loss: 1.2947
Traceback (most recent call last):
  File "poulet.py", line 26, in <module>
    model.fit(
  File "/Users/antoinehoorelbeke/vision/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/antoinehoorelbeke/vision/venv/lib/python3.8/site-packages/tensorflow/python/ops/summary_ops_v2.py", line 93, in __exit__
    _summary_state.writer.flush()
AttributeError: 'NoneType' object has no attribute 'flush'
```

**Comment by tilakrayal** [comment]
@chunduriv ,
I was able to reproduce the issue in tf v2.8 and nightly, where in v2.5 the code is executing without any errors.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/9209e0a369285b5a909f320771608a7b/55224.ipynb).

**Comment by chunduriv** [comment]
@anth2o,

Can you please close this issue, since it is tracked [there](https://github.com/tensorflow/tensorboard/issues/5639). Thanks!

**Comment by japie1235813** [comment]
So for TB we need to have a global write created for summary api to work. I think somewhere in keras it trigged the api but since the write is not created, it cause errors.

Could you try add the two lines before calling keras?
```    
    writer = tf.summary.create_file_writer(tmpdir)
    with writer.as_default():
      model = tf.keras.Sequential([tf.keras.layers.Dense(10)])
      optimizer = tf.keras.optimizers.SGD()
```

As for why the version works in 2.5 but not in 2.8, I think it goes back to see how tf.keras is implemented and use summary api v2 under the hood.

**Comment by anth2o** [comment]
Hi @japie1235813 , thanks for your answer. It doesn't seem to work:
```python
import tensorflow as tf
def test(tmpdir):
    batch_size = 3
    nb_samples = 10
    update_freq = 2
    inputs = tf.random.normal((nb_samples, 2))
    outputs = tf.random.normal((nb_samples, 10))
    dataset = tf.data.Dataset.from_tensor_slices((inputs, outputs)).batch(batch_size)
    dataset_val = tf.data.Dataset.from_tensor_slices((inputs, outputs)).batch(batch_size)
    nb_epochs = 5

    writer = tf.summary.create_file_writer(str(tmpdir))

    with writer.as_default():
        model = tf.keras.Sequential([tf.keras.layers.Dense(10)])
        optimizer = tf.keras.optimizers.SGD()

        tensorboard_kwargs = dict(profile_batch=0, update_freq=update_freq, write_graph=False)
        tensorboard_callbacks = [
            tf.keras.callbacks.TensorBoard(tmpdir.join("tensorboard_1"), **tensorboard_kwargs),
            tf.keras.callbacks.TensorBoard(tmpdir.join("tensorboard_2"), **tensorboard_kwargs)
        ]

    model.compile(optimizer, "mse")
    model.fit(
        dataset,
        batch_size=batch_size,
        callbacks=tensorboard_callbacks,
        epochs=nb_epochs,
        validation_data=dataset_val
    )
```
still raises the same issue

**Comment by anth2o** [comment]
Hi @yatbear , indeed it works. Thanks for your answer !
I tried putting only `model.fit` under the `with writer.as_default():` and it also works
