### ISSUE TITLE
Keras' predict method should be compatible with TensorFlow Probability

### ISSUE THREAD

**Issue by nbro** [tensorflow/tensorflow#34765]
**System information**
- TensorFlow version (you are using): 2.
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**

Currently, I cannot call the [`predict`](https://keras.io/models/model/) method to perform predictions, when using a [`DistributionLambda`](https://www.tensorflow.org/probability/api_docs/python/tfp/layers/DistributionLambda) as the output layer of a Keras model. See, for example, the issues https://github.com/tensorflow/probability/issues/427, https://github.com/tensorflow/probability/issues/538 and https://github.com/tensorflow/tensorflow/issues/31695. So, currently, the apparent alternative is to use  `my_model(input)`, which is a syntax that is not even documented anywhere (AFAIK), to get the predictions.

**Will this change the current api? How?**

I don't know exactly because I am not very familiar with the Keras APIs.

**Who will benefit with this feature?**

Everyone interested in Bayesian deep learning.

**Comment by nbro** [comment]
@jvishnuvardhan, @fchollet Actually, it seems that, at least in one case, you can call `model.predict`, when the output of your model is a distribution. See, for example, the comment https://github.com/tensorflow/probability/issues/538#issuecomment-561113039, where the following code is provided

```
import tensorflow as tf
import tensorflow_probability as tfp
import math

def game(action):
    return math.sin(action)

def make_distribution_fn(t):
    return tfp.distributions.Normal(loc=t, scale=t, validate_args=True)

action_model = tf.keras.Sequential([
  tf.keras.layers.Dense(2, input_dim=2),
  tf.keras.layers.Lambda(tf.abs),
  tfp.layers.DistributionLambda(
    make_distribution_fn=make_distribution_fn
  )
])

tensor = tf.constant([
  [1.0, 2.0]
], dtype='float32')

out = action_model.predict(tensor)

print(out)
```

which can be executed with TF 2.1 and TFP 0.9 without getting any errors. However, I remember I had an example where I couldn't use `predict`.

**Comment by nbro** [comment]
The issue still persists if I set the `compile`'s parameter `experimental_run_tf_function` to `False`, which is necessary in order to train TensorFlow Probability models with Keras' `fit` (see this comment https://github.com/tensorflow/tensorflow/issues/33729#issuecomment-562656807, the issues https://github.com/tensorflow/tensorflow/issues/33729 and https://github.com/tensorflow/probability/issues/620 and [this Stack Overflow question](https://stackoverflow.com/q/58565913/3924118)). For example, if you execute the following code, you will get the error `AttributeError: 'Normal' object has no attribute 'type'`.

```
import tensorflow as tf
import tensorflow_probability as tfp

def make_distribution_fn(t):
    return tfp.distributions.Normal(loc=t, scale=t, validate_args=True)

model = tf.keras.Sequential([
    tf.keras.layers.Dense(2, input_dim=2),
    tf.keras.layers.Lambda(tf.abs),
    tfp.layers.DistributionLambda(
        make_distribution_fn=make_distribution_fn
    )
])

# If you use experimental_run_tf_function=False (as a parameter), you will get the error
# AttributeError: 'Normal' object has no attribute 'type'
model.compile(experimental_run_tf_function=False, loss="mse")

tensor = tf.constant([
    [1.0, 2.0]
], dtype='float32')

out = model.predict(tensor)

print(out)
```

**Comment by evanatyourservice** [comment]
It would be nice to be able to use .fit with tfp, but for now I found I had to use custom training talked about [here](https://www.tensorflow.org/probability/api_docs/python/tfp/layers/DenseFlipout)  in the tfp documentation and [here](https://www.tensorflow.org/tutorials/customization/custom_training_walkthrough) for the custom training.

**Comment by Bitsy-Chuck** [comment]
I have the same issue. 
```
TypeError: An op outside of the function building code is being passed
    a "Graph" tensor. It is possible to have Graph tensors
    leak out of the function building context by including a
    tf.init_scope in your function building code.
    For example, the following function will fail:
      @tf.function
      def has_init_scope():
        my_constant = tf.constant(1.)
        with tf.init_scope():
          added = my_constant * 2
    The graph tensor has name: model/pconv2d_enc_1/Shape:0
```
did try experimental_run_tf_function=False but not working still

Help....

**Comment by DraXus** [comment]
I had the same issue and it seems to be solved in tensorflow-probability 0.11.1.

**Comment by rmothukuru** [comment]
@nbro,
The code mentioned in [this comment](https://github.com/tensorflow/tensorflow/issues/34765#issuecomment-580359337) works fine in **`Tensorflow Version 2.4.1`** and in **`TFP Version 0.12.1`**. Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/50e8bebffe57a05d725f13e01a111f50/gh_34765.ipynb) of the working code. Thanks!
