### ISSUE TITLE
parameterized_docker_build.sh fails to build

### ISSUE THREAD

**Issue by OleRoel** [tensorflow/tensorflow#18552]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
*NO*
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Dockerfile: nvidia/cuda:9.0-base-ubuntu16.04
My System: Fedora 27
- **TensorFlow installed from (source or binary)**:
Source
- **TensorFlow version (use command below)**:
v1.8.0-rc0
- **Python version**:
3.6
- **Bazel version**
N/A
- **CUDA/cuDNN version**
N/A
- **GPU model and memory**
N/A
- **Exact command to reproduce**
`./parameterized_docker_build.sh`

### Describe the problem
Build the Docker image from a fresh clone of Tensorflow:

``` shell
git clone https://github.com/tensorflow/tensorflow.git
git fetch --all --tags --prune
git checkout -b v.1.8.0 v1.8.0-rc0
cd tensorflow/tensorflow/tools/docker
export TF_DOCKER_BUILD_IS_DEVEL=NO
export TF_DOCKER_BUILD_TYPE=GPU
export TF_DOCKER_BUILD_PYTHON_VERSION=PYTHON3
./parameterized_docker_build.sh
```

After some time the build fails with:

```shell
AttributeError: '_NamespacePath' object has no attribute 'sort'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```

### Source code / logs
```shell
ERROR: /workspace/tensorflow/tools/api/generator/BUILD:27:1: Executing genrule //tensorflow/tools/api/generator:python_api_gen failed (Exit 1): bash failed: error executing command 
  (cd /home/oroel/projects/Picsure/tensorflow/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_oroel/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow && \
  exec env - \
    CUDA_TOOLKIT_PATH=/usr/local/cuda \
    CUDNN_INSTALL_PATH=/usr/local/cuda-9.0 \
    GCC_HOST_COMPILER_PATH=/usr/bin/gcc \
    LD_LIBRARY_PATH=/usr/local/cuda/extras/CUPTI/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64 \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin \
    PYTHON_BIN_PATH=/usr/bin/python3 \
    PYTHON_LIB_PATH=/usr/local/lib/python3.5/dist-packages \
    TF_CUDA_CLANG=0 \
    TF_CUDA_COMPUTE_CAPABILITIES=3.0 \
    TF_CUDA_VERSION=9.0 \
    TF_CUDNN_VERSION=7 \
    TF_NCCL_VERSION=1 \
    TF_NEED_CUDA=1 \
    TF_NEED_OPENCL_SYCL=0 \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/k8-py3-opt/bin/tensorflow/tools/api/generator/create_python_api bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/app/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/bitwise/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/compat/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/contrib/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/contrib/stat_summarizer/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/data/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/distributions/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/distributions/bijectors/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/errors/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/estimator/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/estimator/export/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/estimator/inputs/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/feature_column/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/gfile/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/graph_util/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/image/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/initializers/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/keras/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/keras/activations/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/keras/applications/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/keras/applications/densenet/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/keras/applications/inception_resnet_v2/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/keras/applications/inception_v3/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/keras/applications/mobilenet/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/keras/applications/nasnet/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/keras/applications/resnet50/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/keras/applications/vgg16/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/keras/applications/vgg19/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/keras/applications/xception/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/keras/backend/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/keras/callbacks/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/keras/constraints/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/keras/datasets/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/keras/datasets/boston_housing/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/keras/datasets/cifar10/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/keras/datasets/cifar100/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/keras/datasets/fashion_mnist/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/keras/datasets/imdb/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/keras/datasets/mnist/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/keras/datasets/reuters/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/keras/estimator/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/keras/initializers/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/keras/layers/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/keras/losses/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/keras/metrics/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/keras/models/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/keras/optimizers/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/keras/preprocessing/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/keras/preprocessing/image/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/keras/preprocessing/sequence/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/keras/preprocessing/text/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/keras/regularizers/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/keras/utils/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/keras/wrappers/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/keras/wrappers/scikit_learn/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/layers/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/linalg/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/logging/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/losses/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/manip/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/math/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/metrics/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/nn/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/nn/rnn_cell/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/profiler/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/python_io/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/resource_loader/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/saved_model/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/saved_model/builder/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/saved_model/constants/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/saved_model/loader/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/saved_model/main_op/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/saved_model/signature_constants/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/saved_model/signature_def_utils/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/saved_model/tag_constants/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/saved_model/utils/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/sets/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/spectral/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/summary/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/sysconfig/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/test/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/train/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/train/queue_runner/__init__.py bazel-out/k8-py3-opt/genfiles/tensorflow/tools/api/generator/api/user_ops/__init__.py')
Traceback (most recent call last):
  File "/home/oroel/projects/Picsure/tensorflow/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_oroel/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/k8-py3-opt/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/tools/api/generator/create_python_api.py", line 26, in <module>
    from tensorflow.python.util import tf_decorator
  File "/home/oroel/projects/Picsure/tensorflow/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_oroel/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/k8-py3-opt/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/home/oroel/projects/Picsure/tensorflow/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_oroel/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/k8-py3-opt/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/__init__.py", line 37, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2952, in _initialize_master_working_set
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 956, in subscribe
    callback(dist)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2952, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2515, in activate
    declare_namespace(pkg)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2097, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2047, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2066, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 2047.653s, Critical Path: 176.85s
FAILED: Build did NOT complete successfully
Build failed.

```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by cyberwillis** [comment]
Hi @OleRoel, guys
 
I was stuck on this problem too, then I rolledback protobuf to version 3.5.1 and it worked for me.

**Comment by simpeng** [comment]
ya! I got exactly the same error & stacks when build on linux gpu version as @OleRoel . I was using v1.80 to build, hope to get some insights here.

**Comment by simpeng** [comment]
Thanks @cyberwillis , tried the workaround, it does fix the problem. just curious how the 3.5.2.post1 introduced the issue.

**Comment by OleRoel** [comment]
@cyberwillis and @simpeng Can you please elaborate in mode detail, what you did? I'd appreciate it very much. Makes me feel quite stupid that I don't see at the first glance, where to downgrade the protobuf package :-)

**Comment by cyberwillis** [comment]
I didn't make nothing either just thiking

I just saw the error tracing back to protofub and I thought two things:
1. I had compiled right after the release of tf 1.7 successfully and now I was compiling the  tf 1.8 and nothing appear to be right. 
2.I could not blabe the entire repository of tf for this they won't let everybody down like this. Then may be that package or another that is causing the problem.

Then I tought... "protobuf" what was the time of my previous tensorflow build that actually get success and investigated at [pypi](https://pypi.org/search/?q=protobuf) what was the protobuf on that time I get everything successfull?

I just find out that the release date of the package was days after my last build on Tf 1.7. Then I relealised that could be it.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @bignamehyp: It has been 22 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @bignamehyp: It has been 37 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by whatdhack** [comment]
Had the same issue  ( AttributeError: '_NamespacePath' object has no attribute 'sort' ) with  Tensorflow  1.9  Ubuntu 16.04, and Python 3.,5.2.   Seems to be gone after moving to Python 3.6.6 .

**Comment by mdangschat** [comment]
I had the same issue `( AttributeError: '_NamespacePath' object has no attribute 'sort' )` with TF v1.9.0-rc2 and v1.8.0; on Ubuntu 16.04, Python 3.5.2, protobuf 3.6.

Fixed it by downgrading protobuff to 3.5.1.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by pramenku** [comment]
I am seeing seeing the issue. :(
$ pip3 list | grep -i  protobuf
protobuf                      3.5.1
Bazel version is 0.15.2
tf1.8
OS: Ubuntu16.04.4
Python : 3.5.2

INFO: Found 1 target...
ERROR: /home/taccuser/.cache/bazel/_bazel_taccuser/cbc64142ddf66660b02ff669605f4d7f/external/protobuf_archive/BUILD:265:1: Executing genrule @protobuf_archive//:generate_js_well_known_types_embed failed (Aborted): bash failed: error executing command
  (cd /home/taccuser/.cache/bazel/_bazel_taccuser/cbc64142ddf66660b02ff669605f4d7f/execroot/org_tensorflow && \
  exec env - \
    LD_LIBRARY_PATH=/usr/local/lib:/usr/local/mpi/lib:/usr/local/lib:/usr/local/mpi/lib: \
    PATH=/opt/rocm/hcc/bin:/opt/rocm/hip/bin:/opt/rocm/hcc/bin:/opt/rocm/hip/bin:/home/taccuser/bin:/home/taccuser/.local/bin:/usr/local/mpi/bin:/home/taccuser/bin:/home/taccuser/.local/bin:/usr/local/mpi/bin:/home/taccuser/bin:/home/taccuser/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/external/protobuf_archive/js_embed external/protobuf_archive/src/google/protobuf/compiler/js/well_known_types/any.js external/protobuf_archive/src/google/protobuf/compiler/js/well_known_types/struct.js external/protobuf_archive/src/google/protobuf/compiler/js/well_known_types/timestamp.js > bazel-out/host/genfiles/external/protobuf_archive/src/google/protobuf/compiler/js/well_known_types_embed.cc'): bash failed: error executing command
  (cd /home/taccuser/.cache/bazel/_bazel_taccuser/cbc64142ddf66660b02ff669605f4d7f/execroot/org_tensorflow && \
  exec env - \
    LD_LIBRARY_PATH=/usr/local/lib:/usr/local/mpi/lib:/usr/local/lib:/usr/local/mpi/lib: \
    PATH=/opt/rocm/hcc/bin:/opt/rocm/hip/bin:/opt/rocm/hcc/bin:/opt/rocm/hip/bin:/home/taccuser/bin:/home/taccuser/.local/bin:/usr/local/mpi/bin:/home/taccuser/bin:/home/taccuser/.local/bin:/usr/local/mpi/bin:/home/taccuser/bin:/home/taccuser/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/external/protobuf_archive/js_embed external/protobuf_archive/src/google/protobuf/compiler/js/well_known_types/any.js external/protobuf_archive/src/google/protobuf/compiler/js/well_known_types/struct.js external/protobuf_archive/src/google/protobuf/compiler/js/well_known_types/timestamp.js > bazel-out/host/genfiles/external/protobuf_archive/src/google/protobuf/compiler/js/well_known_types_embed.cc')
/bin/bash: line 1: 15045 Aborted                 (core dumped) bazel-out/host/bin/external/protobuf_archive/js_embed external/protobuf_archive/src/google/protobuf/compiler/js/well_known_types/any.js external/protobuf_archive/src/google/protobuf/compiler/js/well_known_types/struct.js external/protobuf_archive/src/google/protobuf/compiler/js/well_known_types/timestamp.js > bazel-out/host/genfiles/external/protobuf_archive/src/google/protobuf/compiler/js/well_known_types_embed.cc
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 1.329s, Critical Path: 0.65s
INFO: 12 processes: 12 local.
FAILED: Build did NOT complete successfully

**Comment by angersson** [comment]
I've recently proposed a change to TensorFlow that obsoletes parameterized_docker_build.sh, which may help alleviate this issue. If anyone following this thread is interested in making TensorFlow's Dockerfile story better for everyone, [please take a look at the RFC](https://github.com/tensorflow/community/pull/8).

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 44 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
