### PR TITLE
Fix build failures for python 3.8

### LINKED ISSUE #33543: [tf2.0.0] Fails to build on Python 3.8 - suggested fix (change nullptr to 0 in source)
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.0.0 with cuda and TensorRT
- Python version: 3.8
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): 7.4.0
- CUDA/cuDNN version: CUDA 10.0, CUDNN 7.6.4
- GPU model and memory: NVidia RTX 2080 Ti

**Describe the problem**

While building from source:
ERROR: /home/daniel/tensorflow/tensorflow/python/BUILD:341:1: C++ compilation of rule '//tensorflow/python:ndarray_tensor_bridge' failed (Exit 1) tensorflow/python/lib/core/ndarray_tensor_bridge.cc:108:1: error: cannot convert ‘std::nullptr_t’ to ‘Py_ssize_t {aka long int}’ in initialization

**Provide the exact sequence of commands / steps that you executed before running into the problem**

git checkout r2.0

bazel build --config=opt --config=cuda --config=v2 --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" //tensorflow/tools/pip_package:build_pip_package

Fix:

In Python 3.8, the reserved "tp_print" slot was changed from a function pointer to a number, `Py_ssize_t tp_vectorcall_offset`.
In C, there is no "nullptr"; either a 0 or NULL casts automatically to both pointers and numbers.
Use 0 instead of "nullptr" in the slot to be source-compatible both with Python 3.8 and previous versions.

Search for "tp_print" in the files listed below.  Change nullptr to 0 where tp_print is in the comment:
i.e. 
change:
`    nullptr,                                      /* tp_print */     `
to:
`    0,                                      /* tp_print */     `
List of files that need this change:
/tensorflow/tensorflow/python/lib/core/ndarray_tensor_bridge.cc     ----> 1 change
/tensorflow/tensorflow/python/lib/core/bfloat16.cc                -----> 1 change
/tensorflow/tensorflow/python/eager/pywrap_tfe_src.cc      -------> 2 changes ( /* tp_print */ occurs twice)

### PR DESCRIPTION
**Pull request by yongtang**
This fix tries to address the issue raised in #33543 where tensorflow build on python 3.8 failed.

This fix fixed the issue as was suggested in #33543 and pip builds finished successfully.

**NOTE: tensorflow depends on h5py which does not have python 3.8
support yet, as such a release version of tensorflow for python 3.8
may have to wait for h5py first.**

This fix fixes #33543.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Review by mihaimaruseac — APPROVED** [review]

**Comment by Mosely** [comment]
Very cool!  Since the blocking factor in providing Tensorflow wheel files for python 3.8 has been other dependencies not having 3.8 support, and since those dependencies now have support, can we have Tensorflow wheel files with Python 3.8 support, please?  Thank you in advance!

Here's some PyPi links showing Python 3.8 support for some dependencies:
https://pypi.org/project/grpcio/#files
https://pypi.org/project/h5py/#files
https://pypi.org/project/scipy/#files
https://pypi.org/project/numpy/#files

**Comment by mihaimaruseac** [comment]
@Mosely https://github.com/tensorflow/tensorflow/issues/33374#issuecomment-571074915

**Comment by byronyi** [comment]
I see a regression on https://github.com/tensorflow/tensorflow/commit/9ec6997dfbb08c978d31f236c1347db8de6fdf5a.
