### ISSUE TITLE
Can't build tf-lite benchmark_model

### ISSUE THREAD

**Issue by abhi-rf** [tensorflow/tensorflow#20313]
Hi all. I am trying to run tflite models on my desktop and for that trying to build benchmark models as given in the benchmark tools github page https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/lite/tools/benchmark . However when I run the command

`bazel build -c opt tensorflow/contrib/lite/tools/benchmark:benchmark_model`

Please help me with this :) Thanks in advance.
I encounter the following error -
System information

    OS Platform and Distribution (Linux Ubuntu):
    TensorFlow installed from (source): Yes
    **TensorFlow version **: 1.9.0rc1
    Python version: 2.7
    Bazel version (if compiling from source):
    GCC/Compiler version (if compiling from source):
    CUDA/cuDNN version: No CUDA
    GPU model and memory:
    Exact command to reproduce:

Describe the problem

The command I ran

bazel build -c opt tensorflow/contrib/lite/tools/benchmark:benchmark_model

**Source code / logs**

**tensorflow/contrib/lite/profiling/profile_summarizer.cc: In function 'tflite::profiling::{anonymous}::OperatorDetails tflite::profiling::{anonymous}::GetOperatorDetails(const tflite::Interpreter&, int)':
tensorflow/contrib/lite/profiling/profile_summarizer.cc:86:27: error: 'string' was not declared in this scope
details.name += ":" + string(profiling_string);
^~~~~~
tensorflow/contrib/lite/profiling/profile_summarizer.cc:86:27: note: suggested alternatives:
In file included from /usr/include/c++/7/iosfwd:39:0,
from /usr/include/c++/7/memory:72,
from ./tensorflow/contrib/lite/simple_memory_arena.h:19,
from ./tensorflow/contrib/lite/allocation.h:25,
from ./tensorflow/contrib/lite/interpreter.h:24,
from ./tensorflow/contrib/lite/profiling/profile_summarizer.h:21,
from tensorflow/contrib/lite/profiling/profile_summarizer.cc:16:
/usr/include/c++/7/bits/stringfwd.h:74:33: note: 'std::__cxx11::string'
typedef basic_string string;
^~~~~~
/usr/include/c++/7/bits/stringfwd.h:74:33: note: 'std::__cxx11::string'
Target //tensorflow/contrib/lite/tools/benchmark:benchmark_model failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.069s, Critical Path: 1.77s
INFO: 0 processes.
FAILED: Build did NOT complete successfully**

**Comment by mikeliao97** [comment]
I'm having the same issues

**Comment by freedomtan** [comment]
I created a patch to fix this and sent a PR https://github.com/tensorflow/tensorflow/pull/20330

**Comment by abhi-rf** [comment]
@freedomtan @achowdhery any ETA as to when it will be fixed and updated finally?

**Comment by freedomtan** [comment]
@abhi-rf  no idea. You can apply the patch yourself.

**Comment by shashishekhar** [comment]
PR #20330 looks good to me, I am going to approve it. Thanks @freedomtan  for the quick patch.

**Comment by shashishekhar** [comment]
PR #20330 is merged.

**Comment by abhi-rf** [comment]
Hi guys. I seem to be hitting a new issue now.

C++ compilation of rule '//tensorflow/contrib/lite/kernels:eigen_support' failed (Exit 1)
tensorflow/contrib/lite/kernels/eigen_support.cc:32:1: error: static assertion failed: kDefaultArenaAlignment doesn't comply with Eigen alignment requirement.
 static_assert(
 ^~~~~~~~~~~~~
Target //tensorflow/contrib/lite/tools/benchmark:benchmark_model failed to build
Use --verbose_failures to see the command lines of failed build steps.


I am getting this in a few builds such as the lite/toco also. Kindly help.

**Comment by freedomtan** [comment]
@abhi-rf it seems you had bad luck. You must be somewhere between ff4945f86e04d403cdf46c19392b2041bc75c2ad and 37cf4e0783ad06e6cfc94c98a77a48734190ed48. The problematic code introduced in ff4945f was reverted already.
