### ISSUE TITLE
can't use keras function, 'CategoryCrossing' in tensorflow version 2.8

### ISSUE THREAD

**Issue by TarunBilluri** [tensorflow/tensorflow#55711]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

tf 2.8

### Custom Code

Yes

### OS Platform and Distribution

Google Cloud Vertex AI TensorFlow:2.6 notebook

### Python version

3.7.12

### GPU model and memory

4 vCPUs, 15 GB RAM & NVIDIA Tesla T4 x 1 	

### Current Behaviour?

```shell
The keras function 'CategoryCrossing()' was working fine in tf version 2.6.2 but throws AttributeError when used in tf version 2.8.

Is this a version issue ? or was the 'Cross Category' function branched under a different library in the 2.8 version?
```

### Standalone code to reproduce the issue

```shell
day_hour_cross = tf.keras.layers.experimental.preprocessing.CategoryCrossing()([day_category, hour_category])
```

### Relevant log output

```shell
AttributeError: module 'keras.api._v2.keras.layers.experimental.preprocessing' has no attribute 'CategoryCrossing'
```
</details>

**Comment by chunduriv** [comment]
@TarunBilluri,

Removed `keras.layers.experimental.preprocessing.CategoryCrossing` in `Tensorflow 2.8`. Users should migrate to the `HashedCrossing` layer or use `tf.sparse.cross`/`tf.ragged.cross` directly. 

For more details please refer [TF 2.8 Release notes](https://github.com/tensorflow/tensorflow/blob/v2.8.0/RELEASE.md), [HashedCrossing](https://www.tensorflow.org/api_docs/python/tf/keras/layers/experimental/preprocessing/HashedCrossing), [tf.sparse.cross](https://www.tensorflow.org/api_docs/python/tf/sparse/cross) and [tf.ragged.cross](https://www.tensorflow.org/api_docs/python/tf/ragged/cross). Thanks!
