### ISSUE TITLE
Error when loading h5 model inside strategy scope

### ISSUE THREAD

**Issue by ismael-elatifi** [tensorflow/tensorflow#38423]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): **No**
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): **Windows 10 and Ubuntu 16.04.6 LTS**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: 
- TensorFlow installed from (source or
binary): **binary**
- TensorFlow version (use command below): **2.1.0**
- Python version: **Python 3.7.5**
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: **CUDA 10.1.243, CuDNN 7.6.4**
- GPU model and memory: **error with CPU and GPU**

**Describe the current behavior**
Cannot load a model from a h5 file inside a strategy context (either CPU, GPU or mirrored) whereas load_model works without strategy context.
Inside a strategy context, it gives error :  

> c:\program files\python37\lib\site-packages\tensorflow_core\python\keras\optimizer_v2\optimizer_v2.py in apply_gradients(self, grads_and_vars, name)
>     439         return control_flow_ops.no_op()
>     440       apply_state = self._prepare(var_list)
> --> 441       return distribute_ctx.get_replica_context().merge_call(
>     442           functools.partial(self._distributed_apply, apply_state=apply_state),
>     443           args=(grads_and_vars,),
> 
> AttributeError: 'NoneType' object has no attribute 'merge_call'

This issue is linked to https://github.com/tensorflow/tensorflow/issues/32359 

**Describe the expected behavior**
load_model call should work in both cases : with or without the use of a strategy context.

**Standalone code to reproduce the issue** 
The zip archive containing the h5 file of the model is attached : 
[dummy_model.zip](https://github.com/tensorflow/tensorflow/files/4460828/dummy_model.zip)

  
Here is the code to reproduce the issue : 
```python
import tensorflow as tf

model_path = "dummy_model.h5"

##### WORKING CASE #####
model = tf.keras.models.load_model(model_path)
model.summary()
########################

##### NON WORKING CASE #####
strategy_context = tf.distribute.OneDeviceStrategy(device="/cpu:0")  # not working also with "/gpu:0" and MirroredStrategy
with strategy_context.scope():
    model = tf.keras.models.load_model(model_path)
    model.summary()
############################
```

**Comment by jvishnuvardhan** [comment]
@ismael-elatifi I agree with you that it is not working with `TF2.1`. However, when I tried with recent `tf-nightly`, it is working as expected. [Here](https://colab.research.google.com/gist/jvishnuvardhan/b93d61013733e421467e1180e3576f82/loading_model_in_scope.ipynb) is a gist for your reference. Based on the gist, I guess this was resolved in recent `tf-nightly`. If you like stable version, In the near future there will be stable `TF2.0` release.

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by Saduf2019** [comment]
@ismael-elatifi 
please update as per above comment

**Comment by ismael-elatifi** [comment]
@jvishnuvardhan Thanks for your reply. However the model you tried in your gist is not the same as in my issue. Can you try with the same h5 file I provided ?

**Comment by jvishnuvardhan** [comment]
@ismael-elatifi [Here](https://colab.research.google.com/gist/jvishnuvardhan/ba1b415602fb89381256a1fb21fde977/loading_model_in_scope.ipynb) is the gist with your model. Thanks!

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by ismael-elatifi** [comment]
@jvishnuvardhan ok thanks, then I will wait for the TF2.2 stable version and in the meantime I won't use any context with the 2.1.
Since it works with the latest nightly, I close this issue.
