### ISSUE TITLE
tensorflow.python.eager.core._FallbackException: This function does not handle the case of the path where all inputs are not already EagerTensors.

### ISSUE THREAD

**Issue by brunorigal** [tensorflow/tensorflow#28924]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Custom code
- Ubuntu 18

- TensorFlow installed from source:
- TensorFlow version :2.0
- Python version: 3.6
- CUDA/cuDNN version:10.0/
- GPU model and memory: 1080Ti/11Go

Contrary to the docs, tf.print do not handle printing tensors in a session run (for example when building a keras model with the model API)
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/print

**Describe the expected behavior**
I expect the example shown in the docs to run smoothly

**Code to reproduce the issue**
```pytho
import os
import tensorflow as tf
from tensorflow.keras.layers import BatchNormalization
import numpy as np
input = np.random.uniform(size=(6, 40, 40, 1)).astype(np.float32)

ds = tf.data.Dataset.from_tensor_slices(input).batch(2)

iterator = iter(ds)
inp = tf.keras.Input((None, None, 1))
print_op = tf.print(inp)
with tf.control_dependencies([print_op]):
    out = tf.keras.layers.Conv2D(5, 3)(inp)
model = tf.keras.Model(inputs=inp, outputs=out)
model(next(iterator))
```

Which raises:
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_string_ops.py", line 807, in string_format
    summarize)
tensorflow.python.eager.core._FallbackException: This function does not handle the case of the path where all inputs are not already EagerTensors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "log_test.py", line 13, in <module>
    print_op = tf.print(inp)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/logging_ops.py", line 339, in print_v2
    name=format_name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/string_ops.py", line 192, in string_format
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_string_ops.py", line 813, in string_format
    summarize=summarize, name=name, ctx=_ctx)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_string_ops.py", line 867, in string_format_eager_fallback
    _attr_T, inputs = _execute.convert_to_mixed_eager_tensors(inputs, _ctx)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py", line 210, in convert_to_mixed_eager_tensors
    types = [t._datatype_enum() for t in v]  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py", line 210, in <listcomp>
    types = [t._datatype_enum() for t in v]  # pylint: disable=protected-access
AttributeError: 'Tensor' object has no attribute '_datatype_enum'
```

**Comment by gadagashwini** [comment]
Thanks for finding the issue. I could reproduce the issue with TF2.0.

**Comment by prannayk** [comment]
Any updates on this?

**Comment by aaronlyt** [comment]
Any solution here?

**Comment by aaronlyt** [comment]
Any solution here?

**Comment by slaweks17** [comment]
I am getting the same error when mixing an LSTM with some additional preprocessing formulas (that have their own parameters to be fitted)

**Comment by aaronlyt** [comment]
Any updates?

**Comment by Inferentialion** [comment]
I´m having this issue as well. Could someone help with why is happening? Thanks.

**Comment by samelsamel** [comment]
I'm having the same issue while converting code from Pytorch to tensorflow2.0, did anyone find a solution?

**Comment by Collonville** [comment]
I have the same issue when I updated TensorFlow version 1.13 to 1.14.

**Comment by sgillen** [comment]
I had this issue with Tensorflow 2.0.0. Downgrading to 1.13.2 resolved the issue, which for me was an acceptable solution.

**Comment by squidszyd** [comment]
I´m having this issue as well

**Comment by Elbek1997** [comment]
Is there any update on this issue with Tensorflow v2.0?

**Comment by astal-veo** [comment]
Any update with TF2.0 ?

**Comment by AntSYau** [comment]
Same issue here

**Comment by oceallc** [comment]
Same issue on version 2

**Comment by omalleyt12** [comment]
`control_dependencies` should not be used in TF2.x.

The way to do this is:

```python
import os
import tensorflow as tf
from tensorflow.keras.layers import BatchNormalization
import numpy as np
input = np.random.uniform(size=(6, 40, 40, 1)).astype(np.float32)

ds = tf.data.Dataset.from_tensor_slices(input).batch(2)

def _print(t):
  tf.print(t)
  return t

iterator = iter(ds)
inp = tf.keras.Input((None, None, 1))
out = tf.keras.layers.Lambda(_print)(inp)
out = tf.keras.layers.Conv2D(5, 3)(out)
model = tf.keras.Model(inputs=inp, outputs=out)
model(next(iterator))
```

**Comment by Kaju-Bubanja** [comment]
I am still getting this error and I am not using control_dependencies

**Comment by Crispy13** [comment]
I am still getting this error also. Tensorflow 2.1.0

**Comment by dmus** [comment]
Same error here: Tensorflow 2.2.0

**Comment by YiZeng623** [comment]
Found an easy solution for this problem in Tensorfolw v 2.xx.xx:

import tensorflow.compat.v1 as tf
tf.disable_eager_execution()

**Comment by antoinehabis** [comment]
Had the same problem when using a generator. Turns out that on_epoch_end and on_epoch_begins where not called. I added 
LambdaCallback(on_epoch_end=train_gen.on_epoch_end,on_epoch_begin=train_gen.on_epoch_begin) to callbacks and this solved the issue.
