### ISSUE TITLE
Failed to compile with CUDA 10.1 on Windows

### ISSUE THREAD

**Issue by LiyuCode** [tensorflow/tensorflow#32831]
Trying to build TF with CUDA 10.1 support with following env:

**Enviroment**
``` 
OS: Winwdows Pro 64 bits, 1903, 18362.356
bazel : 0.26.1
msys64 : MYSIS2 64 Bit, 20190524
Visual Studio: Community 2019,  Version 16.3.1
CUDA: 10.1, cuda_10.1.243_426.00_win10
  - cuDNN : cudnn-10.1-windows10-x64-v7.6.3.30
  - TensorRT : TensorRT-6.0.1.5.Windows10.x86_64.cuda-10.1.cudnn7.6
Conda : 4.7.10, 64 bits
  - Python : 3.6.9
CPU: E5-2678 v3
GPU: RTX 2080

**Target** TF version: v2.0.0-rc1
```

**Steps to reproduce the issue**
Basically, following https://www.tensorflow.org/install/source_windows on a fresh installed Windows OS.

A detailed note: 
https://github.com/LiyuCode/blue_notes/blob/master/Windows/Tensorflow/tensorflow_with_latest_cuda_on_windows.md .

**Problem**
Failed to compile when executing the following command: 

```
bazel build --config=opt --config=cuda --config=v2 --define=no_tensorflow_py_deps=true --copt=-nvcc_options=disable-warnings //tensorflow/tools/pip_package:build_pip_package
```

The error message:
```
C:\users\lcode\_bazel_lcode\hagsv6rp\execroot\org_tensorflow\external\eigen_archive\unsupported\Eigen\CXX11\src/Tensor/TensorExecutor.h(381): error: calling a __host__ function("std::operator -<float> ") from a __device__ function("Eigen::internal::EigenMetaKernelEval< ::Eigen::TensorEvaluator<const  ::Eigen::TensorAssignOp< ::Eigen::TensorMap< ::Eigen::Tensor<    ::std::complex<float> , (int)1, (int)1, int> , (int)16,  ::Eigen::MakePointer> , const  ::Eigen::TensorCwiseUnaryOp< ::Eigen::internal::scalar_opposite_op<    ::std::complex<float> > , const  ::Eigen::TensorMap< ::Eigen::Tensor<const     ::std::complex<float> , (int)1, (int)1, int> , (int)16,  ::Eigen::MakePointer> > > ,  ::Eigen::GpuDevice> , int, (bool)0> ::run") is not allowed

C:\users\lcode\_bazel_lcode\hagsv6rp\execroot\org_tensorflow\external\eigen_archive\unsupported\Eigen\CXX11\src/Tensor/TensorExecutor.h(381): error: identifier "std::operator -<float> " is undefined in device code

C:\users\lcode\_bazel_lcode\hagsv6rp\execroot\org_tensorflow\external\eigen_archive\unsupported\Eigen\CXX11\src/Tensor/TensorExecutor.h(381): error: calling a __host__ function("std::operator -<double> ") from a __device__ function("Eigen::internal::EigenMetaKernelEval< ::Eigen::TensorEvaluator<const  ::Eigen::TensorAssignOp< ::Eigen::TensorMap< ::Eigen::Tensor<    ::std::complex<double> , (int)1, (int)1, int> , (int)16,  ::Eigen::MakePointer> , const  ::Eigen::TensorCwiseUnaryOp< ::Eigen::internal::scalar_opposite_op<    ::std::complex<double> > , const  ::Eigen::TensorMap< ::Eigen::Tensor<const     ::std::complex<double> , (int)1, (int)1, int> , (int)16,  ::Eigen::MakePointer> > > ,  ::Eigen::GpuDevice> , int, (bool)0> ::run") is not allowed

C:\users\lcode\_bazel_lcode\hagsv6rp\execroot\org_tensorflow\external\eigen_archive\unsupported\Eigen\CXX11\src/Tensor/TensorExecutor.h(381): error: identifier "std::operator -<double> " is undefined in device code

4 errors detected in the compilation of "C:/Users/lcode/AppData/Local/Temp/nvcc_inter_files_tmp_dir/tmp_5sdgd1b/cwise_op_gpu_neg.cu.compute_75.cpp1.ii".
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 1023.611s, Critical Path: 353.85s
INFO: 3709 processes: 3709 local.
FAILED: Build did NOT complete successfully
```

**Other info**
1. Compillation was ok about two days ago with same steps on a different computer
2. if checkout `v2.0.0-rc2` instead of `v2.0.0-rc1`, same error will occure.

**Comment by gadagashwini** [comment]
@LiyuCode, Thanks for reporting this issue.
Could you try compiling with CUDA 10.0. 
Please take a look at [software requirements](https://www.tensorflow.org/install/gpu#software_requirements). Thanks!

**Comment by gadagashwini** [comment]
@LiyuCode, Were you able resolve this issue. Thanks

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
