### PR TITLE
Add the corresponding --action_env to .bazelrc from ./configure

### LINKED ISSUE #8619: compilation error on latest master
Seems to have been caused by ede5ebe54f0689a53eeaf0fb1c9a25f136ab3a69
```
$ bazel build -c opt //tensorflow/examples/android:tensorflow_demo
ERROR: /Users/yonits/dev/joytunes/tensorflow/third_party/gpus/cuda_configure.bzl:828:18: unexpected keyword 'environ' in call to repository_rule(implementation: function, *, attrs: dict or NoneType = None, local: bool = False).
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Extension file 'third_party/gpus/cuda_configure.bzl' has errors.
```

### PR DESCRIPTION
**Pull request by damienmg**
This will make the fetch phase reproducible so the refetch does
not happens unless people re-run configure (the environment variable
are stored in the .bazelrc file).

Fixes #8619.

### CODE REVIEW

**Comment by damienmg** [comment]
Only one failure on the GPU build, is it a flake?

**Comment by gunan** [comment]
That is indeed a flake. I will send a change to disable it for now.

**Review by gunan — APPROVED** [review]

**Comment by meteorcloudy** [comment]
@gunan This change is missing from HEAD, can you check what happened? A merge mistake?

**Comment by gunan** [comment]
@wicke @yifeif FYI It is almost like this change never got merged to master at all.
All gone from history, too. Not sure what happened.

Could you resend the change, if you have it handy?
