### ISSUE TITLE
lib/python3.6/site-packages/tensorflow_probability/python/experimental/auto_batching/frontend.py", line 44, in <module>     from tensorflow.python.autograph.core import naming ImportError: cannot import name 'naming'

### ISSUE THREAD

**Issue by anjugopinath** [tensorflow/tensorflow#44718]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: 
- TensorFlow installed from (source or binary): conda install
- TensorFlow version: 1.15
- Python version: 3.6.1
- Installed using virtualenv? pip? conda?: conda 
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): 9.3.0
- CUDA/cuDNN version: 10
- GPU model and memory:

Getting error:
lib/python3.6/site-packages/tensorflow_probability/python/experimental/auto_batching/frontend.py", line 44, in <module>
    from tensorflow.python.autograph.core import naming
ImportError: cannot import name 'naming'

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Ran a .py file with "python <file.py>" command

**Comment by anjugopinath** [comment]
How can I get it working with tensorflow version 1.15?

**Comment by anjugopinath** [comment]
Complete log:
python handObjectTrackingSingleFrame.py --seq 'test' --showFig --doPyRender
2020-11-09 22:41:54.700734: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64
2020-11-09 22:41:54.700770: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "handObjectTrackingSingleFrame.py", line 6, in <module>
    from ghope.common import *
  File "/s/red/a/nobackup/vision/anju/honnotate/HOnnotate-master/optimization/ghope/__init__.py", line 4, in <module>
    from ghope.optimization import Optimizer
  File "/s/red/a/nobackup/vision/anju/honnotate/HOnnotate-master/optimization/ghope/optimization.py", line 5, in <module>
    import tensorflow_probability as tfp
  File "/s/red/a/nobackup/vision/anju/anaconda3/envs/honnotate/lib/python3.6/site-packages/tensorflow_probability/__init__.py", line 75, in <module>
    from tensorflow_probability.python import *  # pylint: disable=wildcard-import
  File "/s/red/a/nobackup/vision/anju/anaconda3/envs/honnotate/lib/python3.6/site-packages/tensorflow_probability/python/__init__.py", line 24, in <module>
    from tensorflow_probability.python import experimental
  File "/s/red/a/nobackup/vision/anju/anaconda3/envs/honnotate/lib/python3.6/site-packages/tensorflow_probability/python/experimental/__init__.py", line 34, in <module>
    from tensorflow_probability.python.experimental import auto_batching
  File "/s/red/a/nobackup/vision/anju/anaconda3/envs/honnotate/lib/python3.6/site-packages/tensorflow_probability/python/experimental/auto_batching/__init__.py", line 24, in <module>
    from tensorflow_probability.python.experimental.auto_batching import frontend
  File "/s/red/a/nobackup/vision/anju/anaconda3/envs/honnotate/lib/python3.6/site-packages/tensorflow_probability/python/experimental/auto_batching/frontend.py", line 44, in <module>
    from tensorflow.python.autograph.core import naming
ImportError: cannot import name 'naming'

**Comment by ravikyram** [comment]
@anjugopinath 

I have tried in colab  with TF version 1.15 and i am not seeing any issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/d0a8523a9563bfee371ef212780a2b5c/untitled505.ipynb).

Please, refer similar issues #40584, #40385 and see if it helps you. Thanks!

**Comment by anjugopinath** [comment]
@ravikyram  Thank You ... Can I try this command: " pip install tfp-nightly 0.11.0.dev20200708" ?

**Comment by anjugopinath** [comment]
I had tensorflow-probability version 0.8.0 ... I installed version 0.7 with the command "pip install tensorflow-probability==0.7" inside the conda virtual environment and I am not getting that error now...

Thank You very much!!
