### PR TITLE
Replay of #8637: Add the corresponding --action_env to .bazelrc from …

### LINKED ISSUE #8619: compilation error on latest master
Seems to have been caused by ede5ebe54f0689a53eeaf0fb1c9a25f136ab3a69
```
$ bazel build -c opt //tensorflow/examples/android:tensorflow_demo
ERROR: /Users/yonits/dev/joytunes/tensorflow/third_party/gpus/cuda_configure.bzl:828:18: unexpected keyword 'environ' in call to repository_rule(implementation: function, *, attrs: dict or NoneType = None, local: bool = False).
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Extension file 'third_party/gpus/cuda_configure.bzl' has errors.
```

### PR DESCRIPTION
**Pull request by damienmg**
…./configure

The original PR got overriden by bc456e361d49d1d89a74b80060c70efb51fd7d87

This will make the fetch phase reproducible so the refetch does
not happens unless people re-run configure (the environment variable
are stored in the .bazelrc file).

Fixes #8619.

### CODE REVIEW

**Review by martinwicke — APPROVED** [review]

**Comment by martinwicke** [comment]
What I don't see how bc456e3 overwrite the original -- bc456e3's diff doesn't have any deleted lines in configure which `echo >> bazel.rc`

**Comment by damienmg** [comment]
Humm maybe I got the commit wrong...

**Comment by martinwicke** [comment]
Anyway, we're looking into this squashing problem. There's probably bad UX
in the merging process which encourages this type of problem.​
