### ISSUE TITLE
Build from source issue (CUDA 7.5)

### ISSUE THREAD

**Issue by mtngld** [tensorflow/tensorflow#13926]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 14.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.4 RC0
- **Python version**: 3.4.3
- **Bazel version (if compiling from source)**: 0.7
- **CUDA/cuDNN version**: CUDA7.5 , cudnn v5.1
- **GPU model and memory**: GeForce GTX TITAN 
- **Exact command to reproduce**: `bazel build --config opt --config=cuda //tensorflow/tools/pip_package:build_pip_package`

### Describe the problem
I am trying to build tensorflow 1.4 RC0 from source, getting compilation error that 'cusolverEigMode_t' has not been declared.

Looks like this is the commit where this code was added:
https://github.com/tensorflow/tensorflow/commit/e3413de529c3f762885efd62932f76445ed22653#diff-e4b1fa736000720d06dab76006540ec4R467

I tried grepping for `cusolverEigMode_t`in my `/usr/local/cuda/` but could not find any reference, is it possible that `cusolverEigMode_t` is not supported in CUDA 7.5? 
In that case, it should be noted that 1.4 is only supported for CUDA 8.0 and above

### Source code / logs
```
ERROR: /home/xxxxx/downloads/tensorflow/tensorflow/core/kernels/BUILD:839:1: C++ compilation of rule '//tensorflow/core/kernels:where_op' failed (Exit 1).
In file included from tensorflow/core/kernels/where_op.cc:42:0:
./tensorflow/core/kernels/cuda_solvers.h:299:16: error: 'cusolverEigMode_t' has not been declared
   Status Heevd(cusolverEigMode_t jobz, cublasFillMode_t uplo, int n,
                ^
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```

**Comment by skye** [comment]
@tfboyd do you know if we expect CUDA 7.5 to work with 1.4?

**Comment by tfboyd** [comment]
Older versions of Cuda are handled as a if it works that is nice but not supported.  Not to pass this around but I think Amit might have a table he was going to publish to show compatibility.  @av8ramit And agreed, we should post something if we have not and if we could make it clear in the release notes that would be useful.

**Comment by av8ramit** [comment]
https://www.tensorflow.org/versions/r1.4/install/install_sources#tested_source_configurations
This will be in master docs soon as well.

**Comment by av8ramit** [comment]
@case540 can we make the release notes for 1.4 more clear with regards to cuda compatibility?

**Comment by case540** [comment]
Not super familiar with CUDA compatibility. Any suggestions for text to add to the release notes about this issue?

**Comment by gunan** [comment]
I do not think we should point this out in our release notes, as they mostly include which cuda/cudnn versions we support. but maybe we can make this clear in our install from sources page in our website?

**Comment by eLvErDe** [comment]
Hi,

I can confirm TF 1.4.0 (stable release) fails to build with the following error on CUDA 7.5.

**Comment by alquraishi** [comment]
I'm getting build errors as well with TF 1.4.0 and CUDA 7.5, but it works with CUDA 8. Unfortunately I can't use CUDA 8 because of outdated Nvidia drivers that I can't upgrade, so it would be great if CUDA 7.5 were supported.

**Comment by gunan** [comment]
Officially we will  only support the latest CUDA version. So we are currently actively working to upgrade to CUDA 9 and drop support for CUDA 8.
However, we will be happy to accept any contributions that fix the build issues on CUDA 7.5.

**Comment by alquraishi** [comment]
Just a heads up that CUDA 9 does not appear to be supported on Ubuntu 14.04, which has a large installed base in ML.

**Comment by alumae** [comment]
From the documentation here https://www.tensorflow.org/install/install_linux I understand that CUDA 7.0 is also officially supported by Tensorflow (given that I compile it myself).

**Comment by camaclean** [comment]
This policy of only supporting the most bleeding edge dependencies is very problematic for HPC centers. Kernel module updates required for the latest Cuda versions are a much bigger deal on a supercomputer than they are on a workstation. At Blue Waters, we are still on Cuda 7.5, although we hope to get 8 at some point. We won't be getting 9. Please understand that "just run the most bleeding edge version of everything" doesn't work for everyone and makes your software "alpha" in terms of reliability.

**Comment by eLvErDe** [comment]
I couldn't agree more.

This is why I build my own Debian/Ubuntu packages against provided CUDA framework.

I don't see installing latest bleeding edge CUDA toolkit by hands on production servers as a good practise...

**Comment by gunan** [comment]
Supporting only one version of CUDA officially just means we have limited resources and other priorities unfortunately preempted older CUDA versions. But I definitely understand your side of the problem.
I will escalate the issue, and see what we can do, but as always, we are happy to accept any contributions that will keep TF working for older CUDA versions. If you have any fixes, I can try to get patch releases of 1.4 our with these fixes to ensure TF 1.4 works with older CUDA versions.

**Comment by mtngld** [comment]
I was able to succesfully build TF 1.4.1 for CUDA 7.5 with a few modifications as in https://github.com/mtngld/tensorflow/commit/a6b7a05331670870a635a1da30c5e7ad0754e526

I think it is a fairly small amount of changes required in order to support old CUDA versions, however I haven't fully tested this and there is probably more work required.

**Comment by mohantym** [comment]
Hi @mtngld!
It seems you are using older versions(1.x versions) of Tensorflow. Have you tried latest versions (TF 2.6/2.7 ) yet? Thanks!

**Comment by mtngld** [comment]
Well that was back in 2017 when we only had tf 1.4.x...

I guess you we can close this ticket as I don't think it is needed anymore with newer versions of both TF and CUDA.

**Comment by mohantym** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
