### ISSUE TITLE
Can not find strtod_l function on Android device

### ISSUE THREAD

**Issue by yen-dang-ts** [tensorflow/tensorflow#61951]
### 1. System information

- OS Platform and Distribution: Android 5.1, OPPO device
- TensorFlow library : Tensorflow lite 2.13.0

When I try to load model and get error:

`E/art: dlopen("/data/app/com.app.demo-1/lib/arm64/libtensorflowlite_jni.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "strtod_l" referenced by "/data/app/com.app.demo-1/lib/arm64/libtensorflowlite_jni.so"...`

**Comment by sushreebarsa** [comment]
@yen-dang-ts 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thank you!

**Comment by yen-dang-ts** [comment]
Hi @sushreebarsa ,

- Load model part:

```
val options = Interpreter.Options()
            val tfLite = Interpreter(
                TFLiteUtils.loadModelFile(context.assets, modelFileName),
                options
            )
```

- `loadModelFile` function
```
fun loadModelFile(assets: AssetManager, modelFilename: String?): MappedByteBuffer {
        val fileDescriptor = assets.openFd(modelFilename!!)
        val inputStream = FileInputStream(fileDescriptor.fileDescriptor)
        val fileChannel = inputStream.channel
        val startOffset = fileDescriptor.startOffset
        val declaredLength = fileDescriptor.declaredLength
        return fileChannel.map(FileChannel.MapMode.READ_ONLY, startOffset, declaredLength)
    }
```

Please have a look on that

**Comment by pjpratik** [comment]
Hi @yen-dang-ts 

What is the SDK and NDK version that are being used? 

As per the documentation,

```
NDK_API_LEVEL="26"
ANDROID_BUILD_TOOLS_VERSION="30.0.3"
ANDROID_SDK_API_LEVEL="30"
```
are recommended for the latest versions.

Thanks.

**Comment by yen-dang-ts** [comment]
Here is my config:

```
  ndkVersion "26.0.10792818"
  compileSdkVersion 33
  buildToolsVersion "30.0.3"
```
And issue still happen

**Comment by pjpratik** [comment]
Hi @yen-dang-ts 

Thanks for the information. I believe there is a Android version compatibility issue with latest TF versions. 

Are you using tflite-flutter for the task?

Have you tried compiling the `libtensorflowlite_jni.so` for amr64 with the the latest TF 2.13 and nightly pull and still observe the same error?

Thanks.

**Comment by andynewman10** [comment]
This problem has been reported in May for `tflite-flutter`: https://github.com/tensorflow/flutter-tflite/issues/73

The problem happens with Android 7.1.1 too. Not sure if Android 8.x/9.x are impacted (Android 13 is not impacted).

Where are the instructions to build `libtensorflowlite_jni.so`?

**Comment by andynewman10** [comment]
> Hi @yen-dang-ts
> 
> Thanks for the information. I believe there is a Android version compatibility issue with latest TF versions.
> 
> Are you using tflite-flutter for the task?
> 
> Have you tried compiling the `libtensorflowlite_jni.so` for amr64 with the the latest TF 2.13 and nightly pull and still observe the same error?
> 
> Thanks.

@pjpratik The problem was introduced in Tensorflow Lite 2.12.0. All versions >= 2.12.0 seem to be [affected](https://github.com/tensorflow/flutter-tflite/issues/73#issuecomment-1754696187). Version 2.11.0 is not affected by this issue. I also tested version 2.10.0, not affected either.

**Comment by pkgoogle** [comment]
Hi @andynewman10, can you give me more context to help reproduce your issue. Do you have a toy version of your model that reproduces this issue on load? Does it run into this on any model? If you can export/share a toy project that'll be easiest, or at least tell me your imports that contextualizes your code snippets:

```
val options = Interpreter.Options()
            val tfLite = Interpreter(
                TFLiteUtils.loadModelFile(context.assets, modelFileName),
                options
            )
```
```
fun loadModelFile(assets: AssetManager, modelFilename: String?): MappedByteBuffer {
        val fileDescriptor = assets.openFd(modelFilename!!)
        val inputStream = FileInputStream(fileDescriptor.fileDescriptor)
        val fileChannel = inputStream.channel
        val startOffset = fileDescriptor.startOffset
        val declaredLength = fileDescriptor.declaredLength
        return fileChannel.map(FileChannel.MapMode.READ_ONLY, startOffset, declaredLength)
    }
```
I should note that currently we only support NDK up to 25b and not 26, you might want to see if that resolves your issues.

**Comment by fiberflow** [comment]
https://github.com/tensorflow/tensorflow/blob/1bd1b7f4b0311575ead19f14e74488a97b524555/tensorflow/lite/g3doc/android/lite_build.md?plain=1#L126
Apparently , the minimum supported version of the official build is Android 8.0

**Comment by andynewman10** [comment]
> Hi @yen-dang-ts, @andynewman10, can you give me more context to help reproduce your issue. Do you have a toy version of your model that reproduces this issue on load? Does it run into this on any model? If you can export/share a toy project that'll be easiest, or at least tell me your imports that contextualizes your code snippets:

@pkgoogle You can use any model, for instance, this one (that I confirm works flawlessly):

https://tfhub.dev/tensorflow/lite-model/efficientnet/lite4/uint8/2

Click on the Download link on the right (download size: 14.34MB), and load this model in your code.

Your code does not have to do anything meaningful. Just import the TF Lite dependencies (>= 2.12.0) in your Gradle file, and make sure that in your program, you execute the lines of code you mentionned in your post above

Then run your the code on Android 7.1.1 (real device or emulator) and this will clearly replicate the issue (libtensorflowlite_jni.so issue with 'strtod_l')

Now switch to Tensorflow Lite 2.11.0 dependencies in your Gradle file : the issue will not show up.

**Comment by andynewman10** [comment]
> https://github.com/tensorflow/tensorflow/blob/1bd1b7f4b0311575ead19f14e74488a97b524555/tensorflow/lite/g3doc/android/lite_build.md?plain=1#L126
> 
> 
> Apparently , the minimum supported version of the official build is Android 8.0

Nice find. Apparently, this commit (dated August, 7) is the culprit:

https://github.com/tensorflow/tensorflow/commit/6d53a5aefdecaba99e93c0933d6cc32050c108d7

As I am writing these lines, this is the latest commit affecting this file.

**Comment by pkgoogle** [comment]
@fiberflow, my bad I thought the previous comment referred to the line above that

https://github.com/tensorflow/tensorflow/blob/1bd1b7f4b0311575ead19f14e74488a97b524555/tensorflow/lite/g3doc/android/lite_build.md?plain=1#L125C1-L125C74
```
build --action_env ANDROID_NDK_HOME="/usr/local/android/android-ndk-r21e"
```
which is the NDK version not the NDK_API_LEVEL.

**Comment by pkgoogle** [comment]
Hi @yen-dang-ts, @andynewman10 I was able to replicate here (with SDK API level = 22, i.e. Android 5.1): [Test61951_min22.zip](https://github.com/tensorflow/tensorflow/files/12875033/Test61951_min22.zip). I was able to get around the error by using a higher SDK level, I tried with SDK API 34. If you can update your Android version and thus SDK API level you can possibly get around this.

Hi @miaout17, can you please take a look? Thanks.

**Comment by andynewman10** [comment]
@pkgoogle Here is what I did:

- I reinstalled Android Studio Giraffe from scratch using latest version
- imported your project (Test61951_min22.zip) that has `minSdkVersion 22` specified in build.gradle, as well as `org.tensorflow:tensorflow-lite:2.13.0`
- ran the program on my Android 7.1.1 (API level 25) device

As expected, I am getting the exception:

```
Process: com.example.test61951_min22, PID: 17748
java.lang.UnsatisfiedLinkError: Failed to load native TensorFlow Lite methods. Check that the correct native libraries are present, and, if using a custom native library, have been properly loaded via System.loadLibrary():
  java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "strtod_l" referenced by "/data/app/com.example.test61951_min22-1/lib/arm64/libtensorflowlite_jni.so"...
	at org.tensorflow.lite.TensorFlowLite.init(TensorFlowLite.java:137)
	at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:62)
	at org.tensorflow.lite.NativeInterpreterWrapperExperimental.<init>(NativeInterpreterWrapperExperimental.java:36)
	at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:232)
```
After that, I switched to `org.tensorflow:tensorflow-lite:2.11.0`: the exception disappears.

**Conclusion**: Android < 8 compatibility was suddenly lost with Tensorflow Lite >= 2.12.0.

Is that expected?

**Comment by nijat-ahmadli** [comment]
@andynewman10 Your conclusion statement doesn't seem to match your test outcome. Based on what you shared, it seems you are still having the issue. Do you mind revising your reply?

Context: I am also having exactly the same issue and opened a separate issue [here](https://github.com/tensorflow/tensorflow/issues/62173). I am interested in resolution of this issue asap.

**Comment by nijat-ahmadli** [comment]
Hi @pkgoogle I have tried [Test61951_min22.zip](https://github.com/tensorflow/tensorflow/files/12875033/Test61951_min22.zip) as per your instructions and updated following versions to 34. I can confirm that I am still getting the same crash on Android Emulators using Android 7 (API level 25) and below.
```
compileSdk 34
targetSdk 34
```

**Comment by fergushenderson** [comment]
> Conclusion: Android < 8 compatibility was suddenly lost with Tensorflow Lite >= 2.12.0.
> Is that expected?

The minimum API level was increased to API 26 in order to provide guaranteed support for AHardwareBuffer,
which is used by the GPU delegate for the asynchronous API.

However, I don't think the consequences of this were fully anticipated, understood, and weighed off
when that change was made.  Breaking compatibility with ~6% of existing devices (based on the numbers on https://apilevels.com/) seems undesirable.  I think TF Lite should strive to support ~99% of existing devices.

**Comment by andynewman10** [comment]
@fergushenderson IMHO, it always feels really good when you know a piece of software works on a "best endavor" basis, targeting the widest possible audience. (on a side note, I would point out the fact that Android OS versions may sometimes be upgraded for just a few years only, but it should be noted that many apps can target Android 5 - Android 5 has plenty to offer already).

The dealbreaker for me is that the Gpu delegate is extremely restrictive. Very few models work with it. None of my models do actually.

**Comment by nijat-ahmadli** [comment]
Hi @pkgoogle Is there an update on this?

Please also note that the official [documentation](https://www.tensorflow.org/lite/android/development#minimum_android_sdk_versions_for_libraries) still indicates that the supported `minSdkVersion` is 19.

**Comment by fergushenderson** [comment]
We are going to fix this.

I have been discussing this with the TF Lite team, and we have consensus that this is a problem that should be fixed.
I have analyzed the cause and possible solutions, and produced a prototype solution that allows use of AHardwareBuffer on versions of Android that support it while still remaining compatible with earlier versions of Android back to Android API level 21.  A TF Lite team member (@[turbotoribio](https://github.com/tensorflow/tensorflow/commits?author=turbotoribio)) has taken on the remaining tasks to get this fix landed.

The main part of the fix has landed:
https://github.com/tensorflow/tensorflow/commit/c7c3135b2802f3b8886f2ecefc39de49799b1e9b

The remaining parts are to change ANDROID_NDK_API_LEVEL from 26 back to 21.

The fix will be included in TF Lite 2.16.

**Comment by nijat-ahmadli** [comment]
Thanks for the reply @fergushenderson. That is a great news!
Are you also considering patching the previous versions, namely 2.12.0, 2.13.0, 2.14.0?

**Comment by fergushenderson** [comment]
We are _considering_ patching 2.15, since that could be shipped a lot sooner than 2.16.

There doesn't seem to be much benefit from patching 2.12-2.14, since users who are affected by this issue could just use 2.15 instead.  (But please correct me if I am wrong about that.)

**Comment by mamahd12** [comment]
@fergushenderson Do we know when the version 2.15 can be released on Maven central?

**Comment by mamahd12** [comment]
@fergushenderson Our project needs version 2.15 please help me to answer the release date

**Comment by nijat-ahmadli** [comment]
@fergushenderson I have just tried tensorflow-lite version 2.15.0. Now I am getting the following compilation error:

```
> Failed to transform guice-5.1.0.jar (com.google.inject:guice:5.1.0) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: /Users/nijatahmadli/.gradle/caches/modules-2/files-2.1/com.google.inject/guice/5.1.0/da25056c694c54ba16e78e4fc35f17fc60f0d1b4/guice-5.1.0.jar.
         > Error while dexing.
           Increase the minSdkVersion to 26 or above.
```
Looks like `guice` was introduced in 2.15.0 and requires minSdkVersion 26 which I guess stems from the use of Java 8 language features. Unfortunately, upgrading to 26 is not an option for our project.

**Comment by mamahd12** [comment]
@fergushenderson I have the same issue with @nijat-ahmadli. Please support us

**Comment by bennyhuo** [comment]
> @fergushenderson I have just tried tensorflow-lite version 2.15.0. Now I am getting the following compilation error:
> 
> ```
> > Failed to transform guice-5.1.0.jar (com.google.inject:guice:5.1.0) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
>       > Execution failed for DexingWithClasspathTransform: /Users/nijatahmadli/.gradle/caches/modules-2/files-2.1/com.google.inject/guice/5.1.0/da25056c694c54ba16e78e4fc35f17fc60f0d1b4/guice-5.1.0.jar.
>          > Error while dexing.
>            Increase the minSdkVersion to 26 or above.
> ```
> 
> Looks like `guice` was introduced in 2.15.0 and requires minSdkVersion 26 which I guess stems from the use of Java 8 language features. Unfortunately, upgrading to 26 is not an option for our project.

Same problem here.

**Comment by fergushenderson** [comment]
Thanks for raising that issue with the guice dependency.  I have alerted the TensorFlow Lite team of this new issue.

The tensorflow 2.16.0 preview release is out.  Is the issue still reproducible in 2.16.0?

In general it is possible to use (most) Java 8 language features while depending only on API level 21, rather than 26.
See <https://developer.android.com/studio/write/java8-support> for details.
So if guice is using Java 8 language features, that doesn't necessarily mean that it needs to be incompatible with API level 21.

**Comment by Ahmed82232** [comment]
I have a problem too, I think it's the same problem
ERROR:C:\Users\hp\.gradle\caches\transforms-3\0e1dbadb4b8b682380e0f29f2a20be93\transformed\jetified-guice-5.1.0.jar: D8: com.android.tools.r8.internal.a2: MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeExtDexDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform guice-5.1.0.jar (com.google.inject:guice:5.1.0) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: C:\Users\hp\.gradle\caches\transforms-3\0e1dbadb4b8b682380e0f29f2a20be93\transformed\jetified-guice-5.1.0.jar.
         > Error while dexing.

**Comment by bennyhuo** [comment]
According to the error messages, guice-5.1.0.jar is not compatible with Android 21. The Java support 8 of Android by desugaring seems not working with guice-5.1.0.jar, could you please consider removing it from the dependency list of tensorflow-lite?

> @fergushenderson I have just tried tensorflow-lite version 2.15.0. Now I am getting the following compilation error:
> 
> ```
> > Failed to transform guice-5.1.0.jar (com.google.inject:guice:5.1.0) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
>       > Execution failed for DexingWithClasspathTransform: /Users/nijatahmadli/.gradle/caches/modules-2/files-2.1/com.google.inject/guice/5.1.0/da25056c694c54ba16e78e4fc35f17fc60f0d1b4/guice-5.1.0.jar.
>          > Error while dexing.
>            Increase the minSdkVersion to 26 or above.
> ```
> 
> Looks like `guice` was introduced in 2.15.0 and requires minSdkVersion 26 which I guess stems from the use of Java 8 language features. Unfortunately, upgrading to 26 is not an option for our project.

**Comment by shawn-lin-013** [comment]
Hi @fergushenderson, we would like to inquire about the release date of version 2.16.0 on Maven Central, as it has been released for two weeks. Additionally, do you have any further information regarding the incompatibility of Guice on Android 7 or below?

**Comment by fergushenderson** [comment]
It looks like the dependency on guice is probably not needed.  So a possible work-around is to simply exclude that in your Gradle config file (e.g. `build.gradle`):

```
implementation ("org.tensorflow:tensorflow-lite:2.15.0") {
  exclude group: 'com.google.inject', module: 'guice'
}
```

[Credit to Khan LeViet for this suggestion.]

We have not tested this work-around yet, but I wanted to share it as soon as possible. Please let us know if this work-around works for you.

**Comment by Abhiek187** [comment]
> It looks like the dependency on guice is probably not needed. So a possible work-around is to simply exclude that in your Gradle config file (e.g. `build.gradle`):
> 
> ```
> implementation ("org.tensorflow:tensorflow-lite:2.15.0") {
>   exclude group: 'com.google.inject', module: 'guice'
> }
> ```
> 
> [Credit to Khan LeViet for this suggestion.]
> 
> We have not tested this work-around yet, but I wanted to share it as soon as possible. Please let us know if this work-around works for you.

I tried this, but I get the following exception when initializing the `Interpreter` on SDK 23:
```kotlin
val assetManager = context.assets
val model = loadModelFile(assetManager, "mnist.tflite")
val options = Interpreter.Options()
val interpreter = Interpreter(model, options)
```

```
java.lang.UnsatisfiedLinkError: Failed to load native TensorFlow Lite methods. Check that the correct native libraries are present, and, if using a custom native library, have been properly loaded via System.loadLibrary():
	java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "strtod_l" referenced by "/data/app/com.abhi.minibrainage-2/base.apk"...
	at org.tensorflow.lite.TensorFlowLite.init(TensorFlowLite.java:137)
	at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:62)
	at org.tensorflow.lite.NativeInterpreterWrapperExperimental.<init>(NativeInterpreterWrapperExperimental.java:36)
	at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:232)
	at com.abhi.minibrainage.DigitClassifier.initializeInterpreter(DigitClassifier.kt:59)
	at com.abhi.minibrainage.DigitClassifier.initialize$lambda$0(DigitClassifier.kt:36)
	at com.abhi.minibrainage.DigitClassifier.$r8$lambda$YB-smHSmZMC0H3c5D98bqcY-rb8(DigitClassifier.kt)
	at com.abhi.minibrainage.DigitClassifier$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.UnsatisfiedLinkError: No implementation found for void org.tensorflow.lite.TensorFlowLite.nativeDoNothing() (tried Java_org_tensorflow_lite_TensorFlowLite_nativeDoNothing and Java_org_tensorflow_lite_TensorFlowLite_nativeDoNothing__)
	at org.tensorflow.lite.TensorFlowLite.nativeDoNothing(Native Method)
	at org.tensorflow.lite.TensorFlowLite.init(TensorFlowLite.java:132)
	at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:62) 
	at org.tensorflow.lite.NativeInterpreterWrapperExperimental.<init>(NativeInterpreterWrapperExperimental.java:36) 
	at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:232) 
	at com.abhi.minibrainage.DigitClassifier.initializeInterpreter(DigitClassifier.kt:59) 
	at com.abhi.minibrainage.DigitClassifier.initialize$lambda$0(DigitClassifier.kt:36) 
	at com.abhi.minibrainage.DigitClassifier.$r8$lambda$YB-smHSmZMC0H3c5D98bqcY-rb8(DigitClassifier.kt) 
	at com.abhi.minibrainage.DigitClassifier$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0) 
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
	at java.lang.Thread.run(Thread.java:818) 
```

**Comment by fergushenderson** [comment]
The symptom that you observe (`cannot locate symbol "strtod_l"`) indicates that the code has been built with the Android NDK (minimum) API level set to a value that is higher than the API level of the system that the code is run on.

I have sent https://github.com/tensorflow/tensorflow/pull/64451 which I suspect will fix this.  But that will require an updated build of TF Lite, if you are using a binary distribution of TF Lite.

If you are building TF Lite from source, I think it may be enough to just make sure you configure with `ANDROID_NDK_API_LEVEL=21` rather than `ANDROID_NDK_API_LEVEL=26` (see <https://www.tensorflow.org/lite/android/lite_build#configure_workspace_and_bazelrc>.)

**Comment by nijat-ahmadli** [comment]
Hi @fergushenderson Thanks for you reply. Just wanted to share that I was also able to compile and run the project after excluding `guice` as instructed. However, I am also getting `cannot locate symbol "strtod_l"` for Android SDK versions 21-25. Will look forward to the next release for the fix mentioned above.
 If `guice` is not needed, are you also planning to remove it from the project for the next release?

**Comment by khanhlvg** [comment]
@nijat-ahmadli @Abhiek187 @shawn-lin-013 @Ahmed82232 @mamahd12 @andynewman10 
Fergus's change has made it to the TFLite nightly build. Could you test it out if it works in your app by change the TFLite dependency in your Gradle file to use the nightly build?

```
implementation ("org.tensorflow:tensorflow-lite:0.0.0-nightly-SNAPSHOT")
```

If everything is fine, we'll work on releasing a stable TFLite release with this fix.

**Comment by fergushenderson** [comment]
> Hi @fergushenderson Thanks for you reply. Just wanted to share that I was also able to compile and run the project after excluding guice as instructed. However, I am also getting cannot locate symbol "strtod_l" for Android SDK versions 21-25.

Try using the nightly build, as Khanh suggested.
For more detailed instructions on how to do that, see
<https://www.tensorflow.org/lite/android/lite_build#use_nightly_snapshots>.

Or alternatively, build from source, and make sure to configure with `ANDROID_NDK_API_LEVEL=21` rather than `ANDROID_NDK_API_LEVEL=26` (see <https://www.tensorflow.org/lite/android/lite_build#configure_workspace_and_bazelrc>).

> If guice is not needed, are you also planning to remove it from the project for the next release?

Yes, the dependency on guice has been removed in the latest nightly builds, and should no longer be present in the next release.

**Comment by Abhiek187** [comment]
The nightly build works for me!

**Comment by shawn-lin-013** [comment]
> > Hi @fergushenderson Thanks for you reply. Just wanted to share that I was also able to compile and run the project after excluding guice as instructed. However, I am also getting cannot locate symbol "strtod_l" for Android SDK versions 21-25.
> 
> Try using the nightly build, as Khanh suggested. For more detailed instructions on how to do that, see https://www.tensorflow.org/lite/android/lite_build#use_nightly_snapshots.
> 
> Or alternatively, build from source, and make sure to configure with `ANDROID_NDK_API_LEVEL=21` rather than `ANDROID_NDK_API_LEVEL=26` (see https://www.tensorflow.org/lite/android/lite_build#configure_workspace_and_bazelrc).
> 
> > If guice is not needed, are you also planning to remove it from the project for the next release?
> 
> Yes, the dependency on guice has been removed in the latest nightly builds, and should no longer be present in the next release.

Hi @fergushenderson, unfortunately, this nightly build does not work for me on Android 5.

```
java.lang.UnsatisfiedLinkError: Failed to load native TensorFlow Lite methods. Check that the correct native libraries are present, and, if using a custom native library, have been properly loaded via System.loadLibrary():
	java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__register_atfork" referenced by "libtensorflowlite_jni.so"...
	at org.tensorflow.lite.TensorFlowLite.init(TensorFlowLite.java:137)
	at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:62)
	at org.tensorflow.lite.NativeInterpreterWrapperExperimental.<init>(NativeInterpreterWrapperExperimental.java:36)
	at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:232)
Caused by: java.lang.UnsatisfiedLinkError: No implementation found for void org.tensorflow.lite.TensorFlowLite.nativeDoNothing() (tried Java_org_tensorflow_lite_TensorFlowLite_nativeDoNothing and Java_org_tensorflow_lite_TensorFlowLite_nativeDoNothing__)
	at org.tensorflow.lite.TensorFlowLite.nativeDoNothing(Native Method)
	at org.tensorflow.lite.TensorFlowLite.init(TensorFlowLite.java:132)
	at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:62) 
	at org.tensorflow.lite.NativeInterpreterWrapperExperimental.<init>(NativeInterpreterWrapperExperimental.java:36) 
	at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:232) 
```

**Comment by shawn-lin-013** [comment]
Hi @fergushenderson, @khanhlvg, We have reconfirmed that the nightly build performs well on Android 5 and above. Could you kindly assist us in releasing the new SDK version to Maven Central? Additionally, we would like to know about the schedule for the next release. Thank you once again for all your assistance.

**Comment by nijat-ahmadli** [comment]
Hi @fergushenderson @khanhlvg the nightly build also works for me. I have tried on Android 5 with the following dependencies. Thanks!

```
    implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly-SNAPSHOT'
    implementation 'org.tensorflow:tensorflow-lite-support:0.0.0-nightly-SNAPSHOT'
```

**Comment by shawn-lin-013** [comment]
Hi @fergushenderson, @khanhlvg, any updates for the next release? 🙏

**Comment by fergushenderson** [comment]
The fix has been cherry picked onto the r2.16 release branch,
and TF Lite 2.16.1 has been released on Maven Central now.
I have verified that the `libtensorflowlite_jni.so` files from TF Lite 2.16.1 do not contain any references to `strtod_l`.
So this issue is fixed now.

**Comment by pkgoogle** [comment]
Hi @yen-dang-ts, this issue should be fixed now, do you agree? Thanks.
