### ISSUE TITLE
Crash when calling TFSMLayer object during TF_lite conversion

### ISSUE THREAD

**Issue by feranick** [tensorflow/tensorflow#76675]
### 1. System information

- Linux Ubuntu 24.04
- TF 2.17.0 (pip) and Keras 3.5.0

### 2. Code

A TF model is first exported using Keras 3.5.0:

```model.export(model_name)```

Then when the following method is called below, the conversion crashes in TF 2.17.0 (log below). It works fine with TF 2.16.2.

```
def makeQuantizedTFmodel(A, dP):
    import tensorflow as tf    
    A2 = tf.cast(A, tf.float32)
    A = tf.data.Dataset.from_tensor_slices((A2)).batch(1)
    
    def representative_dataset_gen():
        for input_value in A.take(100):
            yield[input_value]
  
            import keras
            model = keras.layers.TFSMLayer(model_name), call_endpoint='serve')    
            converter = tf.lite.TFLiteConverter.from_keras_model(model)    

            converter.optimizations = [tf.lite.Optimize.DEFAULT]
            converter.representative_dataset = representative_dataset_gen
            converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
            converter.inference_input_type = tf.uint8
            converter.inference_output_type = tf.uint8
            tflite_quant_model = converter.convert()

            with open(model_name+'.tflite', 'wb') as o:
                   o.write(tflite_quant_model)
```

The error with TF 2.17.0:

```
Traceback (most recent call last):
  File "/home/nicola/test/DML/DataML.py", line 1008, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/nicola/test/DML/DataML.py", line 160, in main
    train(sys.argv[2], None, None)
  File "/home/nicola/test/DML/DataML.py", line 398, in train
    makeQuantizedTFmodel(A, dP)
  File "/home/nicola/test/DML/libDataML.py", line 231, in makeQuantizedTFmodel
    tflite_quant_model = converter.convert()
                         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tensorflow/lite/python/lite.py", line 1231, in wrapper
    return self._convert_and_export_metrics(convert_func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tensorflow/lite/python/lite.py", line 1183, in _convert_and_export_metrics
    result = convert_func(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tensorflow/lite/python/lite.py", line 1749, in convert
    self._freeze_keras_model()
  File "/usr/local/lib/python3.12/dist-packages/tensorflow/lite/python/convert_phase.py", line 215, in wrapper
    raise error from None  # Re-throws the exception.
    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tensorflow/lite/python/convert_phase.py", line 205, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tensorflow/lite/python/lite.py", line 1690, in _freeze_keras_model
    input_signature = _model_input_signature(
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tensorflow/lite/python/tflite_keras_util.py", line 119, in model_input_signature
    input_specs = model._get_save_spec(  # pylint: disable=protected-access
                  ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TFSMLayer' object has no attribute '_get_save_spec'. Did you mean: '_set_save_spec'?
```

**Comment by gaikwadrahul8** [comment]
Hi, @feranick

Thank you for bringing this issue to our attention, I was trying to replicate the same behavior from my end with `TensorFlow version 2.17.0 ` and I did not encounter error which is mentioned in the issue template for your reference I have attached [gist-file](https://colab.sandbox.google.com/gist/gaikwadrahul8/ca6167e8c96be86276f498c364d096d6/test-76675.ipynb)

Please let me know if I have missed something here.

Thank you for your cooperation and patience.

**Comment by feranick** [comment]
Thanks for the quick reply. Please find the [gist-file](https://colab.research.google.com/drive/1jLqjeYl03UmWTWG5NJj5uSEr1ygNO0rF#scrollTo=xITwjDtpOOPV) with the code to convert a TF model to a tflite. It works on TF2.16.2, not on TF 2.17.0. (The same script in github is available [here](https://github.com/feranick/DataML/blob/master/src/utilities/ConvertToTFLiteK3.py
)). 

Attached here are the zipped modelscreated with tf2.16.2 and tf2.17.0. After unzipping, you can try to convert them using the script above. Again, it works on 2.16.2 but not with TF 2.17.0. 

[k3_tf_2.16.2_model_regressor.zip](https://github.com/user-attachments/files/17191135/k3_tf_2.16.2_model_regressor.zip)
[k3_tf_2.17.0_model_regressor.zip](https://github.com/user-attachments/files/17191136/k3_tf_2.17.0_model_regressor.zip)

Please let me know if you need anything else.

**Comment by feranick** [comment]
The issue is still present in TF nightly (2024/10/01) provisional v. 2.19.0

**Comment by gaikwadrahul8** [comment]
Hi, @feranick 

I apologize for the delayed response, I was trying to replicate the same behavior from my end with your this [script](https://github.com/feranick/DataML/blob/master/src/utilities/ConvertToTFLiteK3.py) but I'm getting different error so if possible could you please give me access to your [gist-file](https://colab.research.google.com/drive/1jLqjeYl03UmWTWG5NJj5uSEr1ygNO0rF#scrollTo=xITwjDtpOOPV) to replicate same behavior from my end ? 

Thank you for your cooperation and patience.

**Comment by feranick** [comment]
Thanks and no worries. You should be able to access the gist-file. Just run it, and the error should appear. 

I used the colab AI feature that suggested a completely different way to do the conversion, that does not run on Keras but it is built in TF. Anyway, I added both version of the method *BROKEN" and "SUGGESTED" and you can comment/uncomment the last line to run either one. The Broken one is the one that triggers the issue.

Please note that there is nothing special about the code in the broken call, I am using code that used to work fine in TF 2.16.2 and it is the one suggested.

**Comment by gaikwadrahul8** [comment]
Hi, @feranick 

Thank you for providing the access to your [gist-file](https://colab.research.google.com/drive/1jLqjeYl03UmWTWG5NJj5uSEr1ygNO0rF#scrollTo=xITwjDtpOOPV) and I'm able to replicate the similar behavior from my end so we'll have to dig more into this issue and will update you, thank you for bringing this issue to our attention. 

Thank you for your cooperation and patience.

**Comment by gaikwadrahul8** [comment]
Hi, @pkgoogle
Please take look into this issue. Thank you

**Comment by pkgoogle** [comment]
I was able to replicate as above, this issue did happen before in more general cases (partially caused by Keras 2 to 3). Hi @sirakiin, can you please take a look?

**Comment by jmarrietar** [comment]
Hi @pkgoogle @sirakiin 👋 , do you have a chance to look into this issue? I also have the `'_get_save_spec'.`  problem. 

Thanks!

**Comment by pkgoogle** [comment]
Hi @feranick, @jmarrietar, what's the whole workflow expected here? Reason I ask is the preferred workflow now would be to save in PyTorch (or perhaps pytorch-backed Keras), reload the model in PyTorch, then convert using [ai-edge-torch](https://github.com/google-ai-edge/ai-edge-torch). Can you guys switch to that workflow or is there a reason you guys can't?

**Comment by feranick** [comment]
> Hi [@feranick](https://github.com/feranick), [@jmarrietar](https://github.com/jmarrietar), what's the whole workflow expected here? Reason I ask is the preferred workflow now would be to save in PyTorch (or perhaps pytorch-backed Keras), reload the model in PyTorch, then convert using [ai-edge-torch](https://github.com/google-ai-edge/ai-edge-torch). Can you guys switch to that workflow or is there a reason you guys can't?

I have my whole coding infrastructure based on a tensorflow-backend with keras front-end. You are suggesting to move to PyTorch completely, which isn't feasible on our end at the moment as our non-quantized models are all TF based. Furthermore, as we still rely on edgeTPUs it is also not clear whether ai-edge-torch would be any helpful, and as far as I know it still requires TF-lite. 

As an aside: there is a lot of uncertainty on the fate of EdgeTPU future. Google seems to implying that support is dead. And yet ASUS is happy to still sell it for business customers, with no support whatsoever. Grassroot attempts to keep it alive (including myself) are compensating for this, but clearly it's becoming increasingly difficult to understand the status of the device support, or in general, how much one should rely in tensorflow for TFlite-like quantized modeling.

**Comment by aravindmurali22** [comment]
@suleshahid , could you please take a look into this? thanks

**Comment by aravindmurali22** [comment]
@feranick , Thank you for filing the issue. Since this issue was opened, many updates have been released that may already address your concern; please test the latest version to see if the problem is resolved. We also recommend trying LiteRT, as active development has transitioned there to include the latest features and fixes. If the issue persists, please open a new report in the LiteRT repository so we can investigate it within our current development workflow.
