### PR TITLE
[tflite] make build_rpi_lib.sh work again

### PR DESCRIPTION
**Pull request by freedomtan**
fix undefined referneces introduced by 1a25a8e6. Functions
defined and implemented in `neon_tensor_utils.h`, but not
included anywhere so that there are undefined references.

error messages:
```
....
layer_norm_lstm.cc:(.text+0x20f6): undefined reference to `tflite::tensor_utils::MeanStddevNormalization(float const*, float*, int, int, float)'
layer_norm_lstm.cc:(.text+0x2104): undefined reference to `tflite::tensor_utils::VectorBatchVectorCwiseProduct(float const*, int, float const*, int, float*)'
layer_norm_lstm.cc:(.text+0x2110): undefined reference to `tflite::tensor_utils::VectorBatchVectorAdd(float const*, int, int, float*)'
layer_norm_lstm.cc:(.text+0x2138): undefined reference to `tflite::tensor_utils::MeanStddevNormalization(float const*, float*, int, int, float)'
layer_norm_lstm.cc:(.text+0x2146): undefined reference to `tflite::tensor_utils::VectorBatchVectorCwiseProduct(float const*, int, float const*, int, float*)'
layer_norm_lstm.cc:(.text+0x2152): undefined reference to `tflite::tensor_utils::VectorBatchVectorAdd(float const*, int, int, float*)'
layer_norm_lstm.cc:(.text+0x216c): undefined reference to `tflite::tensor_utils::MeanStddevNormalization(float const*, float*, int, int, float)'
layer_norm_lstm.cc:(.text+0x217c): undefined reference to `tflite::tensor_utils::VectorBatchVectorCwiseProduct(float const*, int, float const*, int, float*)'
layer_norm_lstm.cc:(.text+0x2188): undefined reference to `tflite::tensor_utils::VectorBatchVectorAdd(float const*, int, int, float*)'
layer_norm_lstm.cc:(.text+0x21ea): undefined reference to `tflite::tensor_utils::MeanStddevNormalization(float const*, float*, int, int, float)'
layer_norm_lstm.cc:(.text+0x21fa): undefined reference to `tflite::tensor_utils::VectorBatchVectorCwiseProduct(float const*, int, float const*, int, float*)'
layer_norm_lstm.cc:(.text+0x2206): undefined reference to `tflite::tensor_utils::VectorBatchVectorAdd(float const*, int, int, float*)'
layer_norm_lstm.cc:(.text+0x229e): undefined reference to `tflite::tensor_utils::MeanStddevNormalization(float const*, float*, int, int, float)'
layer_norm_lstm.cc:(.text+0x22ac): undefined reference to `tflite::tensor_utils::VectorBatchVectorCwiseProduct(float const*, int, float const*, int, float*)'
layer_norm_lstm.cc:(.text+0x22b8): undefined reference to `tflite::tensor_utils::VectorBatchVectorAdd(float const*, int, int, float*)'
layer_norm_lstm.cc:(.text+0x22d2): undefined reference to `tflite::tensor_utils::MeanStddevNormalization(float const*, float*, int, int, float)'
layer_norm_lstm.cc:(.text+0x22e0): undefined reference to `tflite::tensor_utils::VectorBatchVectorCwiseProduct(float const*, int, float const*, int, float*)'
layer_norm_lstm.cc:(.text+0x22ec): undefined reference to `tflite::tensor_utils::VectorBatchVectorAdd(float const*, int, int, float*)'
layer_norm_lstm.cc:(.text+0x2306): undefined reference to `tflite::tensor_utils::MeanStddevNormalization(float const*, float*, int, int, float)'
layer_norm_lstm.cc:(.text+0x2316): undefined reference to `tflite::tensor_utils::VectorBatchVectorCwiseProduct(float const*, int, float const*, int, float*)'
layer_norm_lstm.cc:(.text+0x2322): undefined reference to `tflite::tensor_utils::VectorBatchVectorAdd(float const*, int, int, float*)'
layer_norm_lstm.cc:(.text+0x23f4): undefined reference to `tflite::tensor_utils::MeanStddevNormalization(float const*, float*, int, int, float)'
layer_norm_lstm.cc:(.text+0x2402): undefined reference to `tflite::tensor_utils::VectorBatchVectorCwiseProduct(float const*, int, float const*, int, float*)'
layer_norm_lstm.cc:(.text+0x240e): undefined reference to `tflite::tensor_utils::VectorBatchVectorAdd(float const*, int, int, float*)'
layer_norm_lstm.cc:(.text+0x2428): undefined reference to `tflite::tensor_utils::MeanStddevNormalization(float const*, float*, int, int, float)'
layer_norm_lstm.cc:(.text+0x2438): undefined reference to `tflite::tensor_utils::VectorBatchVectorCwiseProduct(float const*, int, float const*, int, float*)'
layer_norm_lstm.cc:(.text+0x2444): undefined reference to `tflite::tensor_utils::VectorBatchVectorAdd(float const*, int, int, float*)'
/hack/freedom/tensorflow/tensorflow/tensorflow/contrib/lite/tools/make/gen/rpi_armv7l/lib/libtensorflow-lite.a(layer_norm_lstm.o): In function `tflite::ops::custom::layer_norm_lstm::LayerNormLstmStep(float const*, signed char const*, float, signed char const*, float, signed char const*, float, signed char const*, float, signed char const*, float, signed char const*, float, signed char const*, float, signed char const*, float, signed char const*, float, signed char const*, float, signed char const*, float, float const*, float const*, float const*, float const*, float const*, float const*, float const*, float const*, signed char const*, float, float const*, float, float, TfLiteFusedActivation const&, int, int, int, int, float*, float*, float*, float*, float*, float*, float*, signed char*, signed char*, signed char*, float*, float*, float*)':
layer_norm_lstm.cc:(.text+0x2f06): undefined reference to `tflite::tensor_utils::MeanStddevNormalization(float const*, float*, int, int, float)'
layer_norm_lstm.cc:(.text+0x2f14): undefined reference to `tflite::tensor_utils::VectorBatchVectorCwiseProduct(float const*, int, float const*, int, float*)'
layer_norm_lstm.cc:(.text+0x2f20): undefined reference to `tflite::tensor_utils::VectorBatchVectorAdd(float const*, int, int, float*)'
layer_norm_lstm.cc:(.text+0x2f40): undefined reference to `tflite::tensor_utils::MeanStddevNormalization(float const*, float*, int, int, float)'
layer_norm_lstm.cc:(.text+0x2f4e): undefined reference to `tflite::tensor_utils::VectorBatchVectorCwiseProduct(float const*, int, float const*, int, float*)'
layer_norm_lstm.cc:(.text+0x2f5a): undefined reference to `tflite::tensor_utils::VectorBatchVectorAdd(float const*, int, int, float*)'
layer_norm_lstm.cc:(.text+0x2f76): undefined reference to `tflite::tensor_utils::MeanStddevNormalization(float const*, float*, int, int, float)'
layer_norm_lstm.cc:(.text+0x2f84): undefined reference to `tflite::tensor_utils::VectorBatchVectorCwiseProduct(float const*, int, float const*, int, float*)'
layer_norm_lstm.cc:(.text+0x2f90): undefined reference to `tflite::tensor_utils::VectorBatchVectorAdd(float const*, int, int, float*)'
layer_norm_lstm.cc:(.text+0x2ff0): undefined reference to `tflite::tensor_utils::MeanStddevNormalization(float const*, float*, int, int, float)'
layer_norm_lstm.cc:(.text+0x2ffe): undefined reference to `tflite::tensor_utils::VectorBatchVectorCwiseProduct(float const*, int, float const*, int, float*)'
layer_norm_lstm.cc:(.text+0x300a): undefined reference to `tflite::tensor_utils::VectorBatchVectorAdd(float const*, int, int, float*)'
layer_norm_lstm.cc:(.text+0x326a): undefined reference to `tflite::tensor_utils::MeanStddevNormalization(float const*, float*, int, int, float)'
layer_norm_lstm.cc:(.text+0x3278): undefined reference to `tflite::tensor_utils::VectorBatchVectorCwiseProduct(float const*, int, float const*, int, float*)'
layer_norm_lstm.cc:(.text+0x3284): undefined reference to `tflite::tensor_utils::VectorBatchVectorAdd(float const*, int, int, float*)'
layer_norm_lstm.cc:(.text+0x32c0): undefined reference to `tflite::tensor_utils::MeanStddevNormalization(float const*, float*, int, int, float)'
layer_norm_lstm.cc:(.text+0x32ce): undefined reference to `tflite::tensor_utils::VectorBatchVectorCwiseProduct(float const*, int, float const*, int, float*)'
layer_norm_lstm.cc:(.text+0x32da): undefined reference to `tflite::tensor_utils::VectorBatchVectorAdd(float const*, int, int, float*)'
layer_norm_lstm.cc:(.text+0x32f6): undefined reference to `tflite::tensor_utils::MeanStddevNormalization(float const*, float*, int, int, float)'
layer_norm_lstm.cc:(.text+0x3304): undefined reference to `tflite::tensor_utils::VectorBatchVectorCwiseProduct(float const*, int, float const*, int, float*)'
layer_norm_lstm.cc:(.text+0x3310): undefined reference to `tflite::tensor_utils::VectorBatchVectorAdd(float const*, int, int, float*)'
layer_norm_lstm.cc:(.text+0x337c): undefined reference to `tflite::tensor_utils::MeanStddevNormalization(float const*, float*, int, int, float)'
layer_norm_lstm.cc:(.text+0x338a): undefined reference to `tflite::tensor_utils::VectorBatchVectorCwiseProduct(float const*, int, float const*, int, float*)'
layer_norm_lstm.cc:(.text+0x3396): undefined reference to `tflite::tensor_utils::VectorBatchVectorAdd(float const*, int, int, float*)'
layer_norm_lstm.cc:(.text+0x33b6): undefined reference to `tflite::tensor_utils::MeanStddevNormalization(float const*, float*, int, int, float)'
layer_norm_lstm.cc:(.text+0x33c4): undefined reference to `tflite::tensor_utils::VectorBatchVectorCwiseProduct(float const*, int, float const*, int, float*)'
layer_norm_lstm.cc:(.text+0x33d0): undefined reference to `tflite::tensor_utils::VectorBatchVectorAdd(float const*, int, int, float*)'
layer_norm_lstm.cc:(.text+0x35d6): undefined reference to `tflite::tensor_utils::MeanStddevNormalization(float const*, float*, int, int, float)'
layer_norm_lstm.cc:(.text+0x35e4): undefined reference to `tflite::tensor_utils::VectorBatchVectorCwiseProduct(float const*, int, float const*, int, float*)'
layer_norm_lstm.cc:(.text+0x35f0): undefined reference to `tflite::tensor_utils::VectorBatchVectorAdd(float const*, int, int, float*)'
layer_norm_lstm.cc:(.text+0x3610): undefined reference to `tflite::tensor_utils::MeanStddevNormalization(float const*, float*, int, int, float)'
layer_norm_lstm.cc:(.text+0x361e): undefined reference to `tflite::tensor_utils::VectorBatchVectorCwiseProduct(float const*, int, float const*, int, float*)'
layer_norm_lstm.cc:(.text+0x362a): undefined reference to `tflite::tensor_utils::VectorBatchVectorAdd(float const*, int, int, float*)'
collect2: error: ld returned 1 exit status
tensorflow/contrib/lite/tools/make/Makefile:191: recipe for target '/hack/freedom/tensorflow/tensorflow/tensorflow/contrib/lite/tools/make/gen/rpi_armv7l/bin/minimal' failed
make: *** [/hack/freedom/tensorflow/tensorflow/tensorflow/contrib/lite/tools/make/gen/rpi_armv7l/bin/minimal] Error 1
make: *** Waiting for unfinished jobs....

```

### CODE REVIEW

**Comment by freedomtan** [comment]
Well, actually, there was no problem. It's my own fault. I didn't clean up old dependency.
