### ISSUE TITLE
cuDNN 7.2 linker errors

### ISSUE THREAD

**Issue by Henje** [tensorflow/tensorflow#32350]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS Linux release 7.6.1810 (Core)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.14.0
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 0.25.2
- GCC/Compiler version (if compiling from source): 7.3.1
- CUDA/cuDNN version: 9.2.148 / 7.2.1
- GPU model and memory: GeForce GTX 1080

**Describe the problem**

When compiling tensorflow 1.14 from source with cuDNN version 7.2 linker errors occur:

```
ERROR: /nfs/freenas/tuph/e18/project/e18sat/poeschl_neuron/tensorinstall/shredderPy3/tensorflow/tf_test/tensorflow-1.14.0/tensorflow/python/BUILD:2189:1: Linking of rule '//tensorflow/python:gen_tpu_ops_py_wrappers_cc' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /tmp/ga58pas/bazel/_bazel_ga58pas/afa3e28b79d056ac590a6714d65f8145/execroot/org_tensorflow && \
  exec env - \
    LD_LIBRARY_PATH=/nfs/mnemosyne/sys/cc7/sw/root/x86-64/6.14.06/devtoolset-7/root/lib:/opt/rh/python27/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib:/opt/rh/devtoolset-7/root/usr/lib64/dyninst:/opt/rh/devtoolset-7/root/usr/lib/dyninst:/opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib:/nfs/freenas/globalSoftware/CC7/geant4/install/lib64:/nfs/freenas/globalSoftware/CC7/CADMesh/build/lib:/nfs/freenas/globalSoftware/CC7/CGAL/build/lib::/nfs/freenas/geant4.10.2/geant4.10.2-install/lib64 \
    PATH=/nfs/mnemosyne/user/ga58pas/private/bazel/bazel-0.25.2/bin:/nfs/mnemosyne/sys/cc7/sw/root/x86-64/6.14.06/devtoolset-7/root/bin:/opt/rh/python27/root/usr/bin:/opt/rh/devtoolset-7/root/usr/bin:/nfs/freenas/globalSoftware/CC7/geant4/install/bin:/nfs/freenas/globalSoftware/CC7/cmake/build/bin:/nfs/mnemosyne/user/ga58pas/private/scripts:/usr/sue/bin:/usr/lib64/qt-3.3/bin:/usr/lib64/ccache:/opt/sge/bin/lx-amd64:/usr/local/bin:/usr/bin:/bin:/usr/games:/opt/puppetlabs/bin/ \
    PWD=/proc/self/cwd \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -o bazel-out/host/bin/tensorflow/python/gen_tpu_ops_py_wrappers_cc '-Wl,-rpath,$ORIGIN/../../_solib_local/_U_S_Stensorflow_Spython_Cgen_Utpu_Uops_Upy_Uwrappers_Ucc___Utensorflow' -Lbazel-out/host/bin/_solib_local/_U_S_Stensorflow_Spython_Cgen_Utpu_Uops_Upy_Uwrappers_Ucc___Utensorflow -Wl,-ldl '-Wl,-rpath,$ORIGIN/,-rpath,$ORIGIN/..' -pthread -pthread -pthread -pthread -Wl,-S -Wl,-no-as-needed -pie -Wl,-z,relro,-z,now '-Wl,--build-id=md5' '-Wl,--hash-style=gnu' -no-canonical-prefixes -fno-canonical-system-headers -B/usr/bin -Wl,--gc-sections -Wl,@bazel-out/host/bin/tensorflow/python/gen_tpu_ops_py_wrappers_cc-2.params)
Execution platform: @bazel_tools//platforms:host_platform
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Spython_Cgen_Utpu_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so.1: undefined reference to `cudnnSetRNNPaddingMode'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Spython_Cgen_Utpu_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so.1: undefined reference to `cudnnRNNForwardInferenceEx'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Spython_Cgen_Utpu_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so.1: undefined reference to `cudnnCreateRNNDataDescriptor'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Spython_Cgen_Utpu_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so.1: undefined reference to `cudnnRNNForwardTrainingEx'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Spython_Cgen_Utpu_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so.1: undefined reference to `cudnnSetRNNDataDescriptor'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Spython_Cgen_Utpu_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so.1: undefined reference to `cudnnRNNBackwardDataEx'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Spython_Cgen_Utpu_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so.1: undefined reference to `cudnnRNNBackwardWeightsEx'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Spython_Cgen_Utpu_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so.1: undefined reference to `cudnnDestroyRNNDataDescriptor'
collect2: error: ld returned 1 exit status
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 1529.552s, Critical Path: 187.94s
INFO: 5504 processes: 5504 local.
FAILED: Build did NOT complete successfully
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

I configured tensorflow to compile with CUDA 9.2 and cuDNN 7.2 and started the build:
```
./configure
bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package --verbose_failures
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

My .tf_configure.bazelrc looks like this
```
build --action_env PYTHON_BIN_PATH="/nfs/freenas/virtenv/TensorPy3/bin/python"
build --action_env PYTHON_LIB_PATH="/nfs/freenas/virtenv/TensorPy3/lib/python3.6/site-packages"
build --python_path="/nfs/freenas/virtenv/TensorPy3/bin/python"
build:xla --define with_xla_support=true
build --action_env TF_NEED_OPENCL_SYCL="0"
build --action_env TF_NEED_ROCM="0"
build --action_env TF_NEED_CUDA="1"
build --action_env TF_NEED_TENSORRT="0"
build --action_env TF_CUDA_VERSION="9"
build --action_env TF_CUDNN_VERSION="7"
build --action_env TF_NCCL_VERSION=""
build --action_env TF_CUDA_PATHS="/usr/local/cuda-9.2,/usr/local/cuda-9.2/targets/x86_64-linux"
build --action_env CUDA_TOOLKIT_PATH="/usr/local/cuda-9.2"
build --action_env TF_CUDA_COMPUTE_CAPABILITIES="6.1"
build --action_env LD_LIBRARY_PATH="/nfs/mnemosyne/sys/cc7/sw/root/x86-64/6.14.06/devtoolset-7/root/lib:/opt/rh/python27/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib:/opt/rh/devtoolset-7/root/usr/lib64/dyninst:/opt/rh/devtoolset-7/root/usr/lib/dyninst:/opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib:/nfs/freenas/globalSoftware/CC7/geant4/install/lib64:/nfs/freenas/globalSoftware/CC7/CADMesh/build/lib:/nfs/freenas/globalSoftware/CC7/CGAL/build/lib::/nfs/freenas/geant4.10.2/geant4.10.2-install/lib64"
build --action_env TF_CUDA_CLANG="0"
build --action_env GCC_HOST_COMPILER_PATH="/opt/rh/devtoolset-7/root/usr/bin/gcc"
build --config=cuda
build:opt --copt=-march=native
build:opt --copt=-Wno-sign-compare
build:opt --host_copt=-march=native
build:opt --define with_default_optimizations=true
build:v2 --define=tf_api_version=2
test --flaky_test_attempts=3
test --test_size_filters=small,medium
test --test_tag_filters=-benchmark-test,-no_oss,-oss_serial
test --build_tag_filters=-benchmark-test,-no_oss
test --test_tag_filters=-gpu
test --build_tag_filters=-gpu
build --action_env TF_CONFIGURE_IOS="0"
```

**Comment by Henje** [comment]
As far as I can tell this happens because in tensorflow/stream_executor/cuda/cuda_dnn.cc the cuDNN version checks for `CUDNN_VERSION >= 7201` whereas the wrapper  tensorflow/stream_executor/cuda/cudnn_stub.cc checks `CUDNN_MINOR < 1` and then `CUDNN_MINOR < 3`. So there is no special handling for cuDNN 7.2, even though it is used elsewhere.

**Comment by zhanghaocol** [comment]
I faced the same error and simply installing cuDNN > 7.2 does not resolve the issue.

**Comment by chsigg** [comment]
Thanks Henje, your analysis is correct. The cudnn_stub code doesn't match the cuda_dnn code. I think the simpler approach would be to bump the version number in cuda_dnn, but if you want to have RNN support maybe you could try changing the version number in cudnn_stub, using the 7.3 .inc file for your cuDNN 7.2. Let me know if that works for you.

**Comment by Henje** [comment]
To make it work I just replaced the check in cudnn_stub:

```diff
--- cudnn_stub.cc.orig  2019-11-12 11:13:18.337247976 +0100
+++ cudnn_stub.cc       2019-09-06 17:06:33.000000000 +0200
@@ -53,11 +53,10 @@
 #include "tensorflow/stream_executor/cuda/cudnn_6_0.inc"
 #elif CUDNN_MINOR < 1
 #include "tensorflow/stream_executor/cuda/cudnn_7_0.inc"
-#elif CUDNN_MINOR < 3
+#elif CUDNN_MINOR < 2
 #include "tensorflow/stream_executor/cuda/cudnn_7_1.inc"
 #elif CUDNN_MINOR < 4
 #include "tensorflow/stream_executor/cuda/cudnn_7_3.inc"
 #else
 #include "tensorflow/stream_executor/cuda/cudnn_7_4.inc"
 #endif
```

This works for me. I hoped you could implement a proper fix, because this seems like a hack.

**Comment by chsigg** [comment]
Hi Henje, given that cuDNN 7.2 is quite old already and it seems to work, let's just go ahead with the hack.
