### ISSUE TITLE
ImportError: cannot import name 'lite'

### ISSUE THREAD

**Issue by jeet4690** [tensorflow/tensorflow#30693]
on ubuntu 18.4

using this input 

`from tensorflow.contrib import lite
converter = lite.TFLiteConverter.from_keras_model_file( 'model.h5')
tfmodel = converter.convert()
open ("model.tflite" , "wb") .write(tfmodel)`

i got this error

`Traceback (most recent call last):
  File "h5totflite.py", line 1, in <module>
    from tensorflow.contrib import lite
ImportError: cannot import name 'lite'`

**Comment by anush-o** [comment]
@jeet4690 ,
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by jeet4690** [comment]
ubuntu 18.4

working on google COLAB

tensorflow version 1.14

**Comment by anush-o** [comment]
@jeet4690 ,
You can use the below code which has been executed in google colab and is working with TF version 1.14

```
#from tensorflow.contrib import lite 
import tensorflow as tf
converter = tf.lite.TFLiteConverter.from_keras_model_file('my_model.h5') 
tfmodel = converter.convert() 
open ("model.tflite" , "wb") .write(tfmodel)
```

**Comment by jeet4690** [comment]
@anush-o after trying that it gave me this error

`ValueError: No model found in config file.

![Screenshot from 2019-07-19 20-23-04](https://user-images.githubusercontent.com/32290207/61544538-51100780-aa63-11e9-895c-ce9408c96c10.png)

`

**Comment by jeet4690** [comment]
@haozha111 can you plz help me find the problem, P.S. i am trying to convert `model.h5` it only have "weights" into `model.tflite`

**Comment by haozha111** [comment]
The error comes from keras code when loading the h5 file:
https://github.com/tensorflow/tensorflow/blob/3f89bc5175caf279ae232088c88891b804a6b51f/tensorflow/python/keras/saving/hdf5_format.py#L158

Please make sure that the h5 file contains the model itself, not only the weights.

**Comment by akinpelu746** [comment]
hello
my code is
import tensorflow as tf
converter = tf.lite.TFLiteConverter.from_keras_model_file( r'/content/drive/My Drive/inceptionv3-transfer-learning__fine_tune.h5') # Your model's name
model = converter.convert()
file = open( 'model.tflite' , 'wb' ) 
file.write( model )

ValueError: None is only supported in the 1st dimension. Tensor 'input_1' has invalid shape '[None, None, None, 3]'.

what can ido?

**Comment by haozha111** [comment]
Please post your question in a new issue and we will triage it. Thanks.
