### ISSUE TITLE
Tensorflow-2.20 build-failure

### ISSUE THREAD

**Issue by tamama-plb** [tensorflow/tensorflow#104297]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tensorflow-2.20.0

### Custom code

No

### OS platform and distribution

RockyLinux 9.6

### Mobile device

N/A

### Python version

3.13

### Bazel version

8.4.2

### GCC/compiler version

15.1.1-2

### CUDA/cuDNN version

N/A

### GPU model and memory

N/A

### Current behavior?

Versions:
- Bazel: Release 8.4.2
- Tensorflow: Release 2.20.0

First, here are the custom bazelrc

```
(tamama) [tamama@admin--cde tensorflow-2.20.0]$ cat .tf_configure.bazelrc
build --action_env PYTHON_BIN_PATH="/home/tamama/.tamama/opt/github.com/conda-forge/miniforge/Miniforge3-25.3.1-0/envs/tamama/bin/python3"
build --action_env PYTHON_LIB_PATH="/home/tamama/.tamama/opt/github.com/conda-forge/miniforge/Miniforge3-25.3.1-0/envs/tamama/lib/python3.13/site-packages"
build --python_path="/home/tamama/.tamama/opt/github.com/conda-forge/miniforge/Miniforge3-25.3.1-0/envs/tamama/bin/python3"
build:opt --copt=-O3
build:opt --host_copt=-O3
build:opt --copt=-s
build:opt --host_copt=-s
test --test_size_filters=small,medium
test:v1 --test_tag_filters=-benchmark-test,-no_oss,-oss_excluded,-gpu,-oss_serial
test:v1 --build_tag_filters=-benchmark-test,-no_oss,-oss_excluded,-gpu
test:v2 --test_tag_filters=-benchmark-test,-no_oss,-oss_excluded,-gpu,-oss_serial,-v1only
test:v2 --build_tag_filters=-benchmark-test,-no_oss,-oss_excluded,-gpu,-v1only

### Added this following line manually
common --repo_env=HERMETIC_PYTHON_VERSION=3.13
```

Second, here is the bazel build command:

```
bazel build   \
    --enable_workspace \
    --config=opt  \
    --copt="-march=native"  \
    //tensorflow:libtensorflow_cc.so
```

Error logs:
```
... ...
DEBUG: /home/tamama/.cache/bazel/_bazel_tamama/45e422347f6fcb66ffad31cd40ecc1db/external/local_xla/third_party/py/python_repo.bzl:82:14: !!!Using pywrap rules instead of directly creating .so objects!!!
DEBUG: /home/tamama/.cache/bazel/_bazel_tamama/45e422347f6fcb66ffad31cd40ecc1db/external/local_xla/third_party/py/python_repo.bzl:87:10: 
=============================
Hermetic Python configuration:
Version: "3.13"    
Kind: ""                
Interpreter: "default" (provided by rules_python)
Requirements_lock label: "@python_version_repo//:requirements_lock_3_13.txt"     
=====================================                                                                                              
ERROR: Traceback (most recent call last):                                                                                          
        File "/home/tamama/.cache/bazel/_bazel_tamama/45e422347f6fcb66ffad31cd40ecc1db/external/rules_python/python/private/py_runtime_pair_rule.bzl", line 80, column 34, in <toplevel>
                "py2_runtime": attr.label(
Error in label: Illegal argument: element in 'providers' is of unexpected type. Either all elements should be providers, or all elements should be lists of providers, but got list with an element of type NoneType.
ERROR: Error computing the main repository mapping: at /home/tamama/.cache/bazel/_bazel_tamama/45e422347f6fcb66ffad31cd40ecc1db/external/local_xla/third_party/py/python_init_pip.bzl:5:6: at /home/tamama/.cache/bazel/_bazel_tamama/45e422347f6fcb66ffad31cd40ecc1db
/external/rules_python/python/pip.bzl:29:6: at /home/tamama/.cache/bazel/_bazel_tamama/45e422347f6fcb66ffad31cd40ecc1db/external/rules_python/python/private/pypi/pip_compile.bzl:22:6: at /home/tamama/.cache/bazel/_bazel_tamama/45e422347f6fcb66ffad31cd40ecc1db/ex
ternal/rules_python/python/defs.bzl:22:6: at /home/tamama/.cache/bazel/_bazel_tamama/45e422347f6fcb66ffad31cd40ecc1db/external/rules_python/python/py_runtime_pair.bzl:18:6: at /home/tamama/.cache/bazel/_bazel_tamama/45e422347f6fcb66ffad31cd40ecc1db/external/rule
s_python/python/private/py_runtime_pair_macro.bzl:17:6: initialization of module 'python/private/py_runtime_pair_rule.bzl' failed                                                                                                                                     
Computing main repo mapping: 
    Fetching repository @@python; Running GetUname
    Fetching repository @@rules_cc; starting
    Fetching /home/tamama/.cache/bazel/_bazel_tamama/45e422347f6fcb66ffad31cd40ecc1db/external/rules_cc; Extracting rules_cc-0.0.13.tar.gz
(tamama) [tamama@admin--cde tensorflow-2.20.0]$ 
```

Please kindly advise how I could patch / workaround this issue.

Thank you!

Kind regards,
Tama MA

### Standalone code to reproduce the issue

```shell
bazel build  \
    --enable_workspace \
    --config=opt  \
    --copt="-march=native"  \
    //tensorflow:libtensorflow_cc.so
```

### Relevant log output

```shell
DEBUG: /home/tamama/.cache/bazel/_bazel_tamama/45e422347f6fcb66ffad31cd40ecc1db/external/local_xla/third_party/py/python_repo.bzl:82:14: !!!Using pywrap rules instead of directly creating .so objects!!!
DEBUG: /home/tamama/.cache/bazel/_bazel_tamama/45e422347f6fcb66ffad31cd40ecc1db/external/local_xla/third_party/py/python_repo.bzl:87:10: 
=============================
Hermetic Python configuration:
Version: "3.13"    
Kind: ""                
Interpreter: "default" (provided by rules_python)
Requirements_lock label: "@python_version_repo//:requirements_lock_3_13.txt"     
=====================================                                                                                              
ERROR: Traceback (most recent call last):                                                                                          
        File "/home/tamama/.cache/bazel/_bazel_tamama/45e422347f6fcb66ffad31cd40ecc1db/external/rules_python/python/private/py_runtime_pair_rule.bzl", line 80, column 34, in <toplevel>
                "py2_runtime": attr.label(
Error in label: Illegal argument: element in 'providers' is of unexpected type. Either all elements should be providers, or all elements should be lists of providers, but got list with an element of type NoneType.
ERROR: Error computing the main repository mapping: at /home/tamama/.cache/bazel/_bazel_tamama/45e422347f6fcb66ffad31cd40ecc1db/external/local_xla/third_party/py/python_init_pip.bzl:5:6: at /home/tamama/.cache/bazel/_bazel_tamama/45e422347f6fcb66ffad31cd40ecc1db
/external/rules_python/python/pip.bzl:29:6: at /home/tamama/.cache/bazel/_bazel_tamama/45e422347f6fcb66ffad31cd40ecc1db/external/rules_python/python/private/pypi/pip_compile.bzl:22:6: at /home/tamama/.cache/bazel/_bazel_tamama/45e422347f6fcb66ffad31cd40ecc1db/ex
ternal/rules_python/python/defs.bzl:22:6: at /home/tamama/.cache/bazel/_bazel_tamama/45e422347f6fcb66ffad31cd40ecc1db/external/rules_python/python/py_runtime_pair.bzl:18:6: at /home/tamama/.cache/bazel/_bazel_tamama/45e422347f6fcb66ffad31cd40ecc1db/external/rule
s_python/python/private/py_runtime_pair_macro.bzl:17:6: initialization of module 'python/private/py_runtime_pair_rule.bzl' failed                                                                                                                                     
Computing main repo mapping: 
    Fetching repository @@python; Running GetUname
    Fetching repository @@rules_cc; starting
    Fetching /home/tamama/.cache/bazel/_bazel_tamama/45e422347f6fcb66ffad31cd40ecc1db/external/rules_cc; Extracting rules_cc-0.0.13.tar.gz
(tamama) [tamama@admin--cde tensorflow-2.20.0]$
```

**Comment by tamama-plb** [comment]
The issue seems to go away after I fallback Bazel to Bazel-7.4.1, as advised by your compatibility matrix.

Let me double confirm on this in a bit.

**Comment by tamama-plb** [comment]
The build still fails. Here it goes.   

(Please advise me whether I should rollback to TF v2.19.0. Thank you.)

Bazel: Release - v7.4.1
Tensorflow: Release - v2.20.0
GCC: gcc-toolset-15

(Later on, I further checked that neither gcc-toolset-14 and gcc-toolset-13 worked as well.) 

Command:
```
bazel build \
  -j 12 \
  --local_resources=memory=16384  \
  --config=opt \
  //tensorflow:all
```

Custom Bazel config: - `.tf_configure.bazelrc`
```
build --action_env PYTHON_BIN_PATH="/home/tamama/.tamama/opt/github.com/conda-forge/miniforge/current/envs/tamama/bin/python3"
build --action_env PYTHON_LIB_PATH="/home/tamama/.tamama/opt/github.com/conda-forge/miniforge/current/envs/tamama/lib/python3.13/site-packages"
build --python_path="/home/tamama/.tamama/opt/github.com/conda-forge/miniforge/current/envs/tamama/bin/python3"
build:opt --copt=-s
build:opt --host_copt=-s
build:opt --copt=-O3
build:opt --host_copt=-O3
build:opt --copt=-march=native
build:opt --host_copt=-march=native
test --test_size_filters=small,medium
test:v1 --test_tag_filters=-benchmark-test,-no_oss,-oss_excluded,-gpu,-oss_serial
test:v1 --build_tag_filters=-benchmark-test,-no_oss,-oss_excluded,-gpu
test:v2 --test_tag_filters=-benchmark-test,-no_oss,-oss_excluded,-gpu,-oss_serial,-v1only
test:v2 --build_tag_filters=-benchmark-test,-no_oss,-oss_excluded,-gpu,-v1only

### Note: The following flags are added by Tama MA
common --repo_env=HERMETIC_PYTHON_VERSION=3.13
```

Log:
```
ERROR: /home/tamama/.cache/bazel/_bazel_tamama/45e422347f6fcb66ffad31cd40ecc1db/external/ducc/BUILD.bazel:72:11: Compiling google/fft.cc failed: (Exit 1): gcc failed: error executing CppCompile command (from target @@ducc//:fft_wrapper) /opt/rh/gcc-toolset-15/ro
ot/usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 82 arguments skipped)                                                      
In file included from external/ducc/google/fft.cc:28:                                                                                                                                                                                                                 bazel-out/k8-opt/bin/external/ducc/_virtual_includes/fft/ducc/src/ducc0/fft/fftnd_impl.h: In instantiation of 'void ducc0::detail_fft::c2c(const ducc0::detail_mav::cfmav<std::complex<_Tp> >&, const ducc0::detail_mav::vfmav<std::complex<_Tp> >&, const shape_t&, b
ool, T, size_t) [with T = float; shape_t = std::vector<long unsigned int>; size_t = long unsigned int]':                           
external/ducc/google/fft.cc:56:17:   required from 'void ducc0::google::c2c(const std::complex<_Tp>*, const Shape&, const Stride&, std::complex<_Tp>*, const Shape&, const Stride&, const Shape&, bool, RealScalar, Eigen::ThreadPoolInterface*) [with RealScalar = fl
oat; Shape = std::vector<long unsigned int>; Stride = std::vector<long int>]'                                                      
   56 |       ducc0::c2c(m_in, m_out, axes, forward, scale, 1);                                                                    
      |       ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                     
external/ducc/google/fft.cc:143:1:   required from here                                                                                                                                                                                                               
  132 |       Eigen::ThreadPoolInterface* thread_pool);                                \                                           
      |                                              ^
bazel-out/k8-opt/bin/external/ducc/_virtual_includes/fft/ducc/src/ducc0/fft/fftnd_impl.h:1393:20: error: call of '(ducc0::detail_mav::vmav<std::complex<float>, 2>) (long unsigned int&, size_t&)' is ambiguous                                                       
 1393 |                 tmp(i,j) *= conj(roots[i*j]);                                                                                                                                                                                                                 
      |                 ~~~^~~~~                        
In file included from bazel-out/k8-opt/bin/external/ducc/_virtual_includes/fft/ducc/src/ducc0/fft/fft.h:65,                        
                 from external/ducc/google/fft.cc:26:                                                                                                                                                                                                                 
external/ducc/src/ducc0/infra/mav.h:803:41: note: there are 2 candidates                                                           
  803 | template<typename T, size_t ndim> class vmav: public cmav<T, ndim>                                                         
      |                                         ^~~~                                                                                                                                                                                                                  
external/ducc/src/ducc0/infra/mav.h:765:39: note: candidate 1: 'const T& ducc0::detail_mav::cmav<T, ndim>::operator()(Ns ...) const [with Ns = {long unsigned int, long unsigned int}; T = std::complex<float>; long unsigned int ndim = 2]'                            765 |     template<typename... Ns> const T &operator()(Ns... ns) const                                                           
      |                                       ^~~~~~~~
external/ducc/src/ducc0/infra/mav.h:856:33: note: candidate 2: 'T& ducc0::detail_mav::vmav<T, ndim>::operator()(Ns ...) const [with Ns = {long unsigned int, long unsigned int}; T = std::complex<float>; long unsigned int ndim = 2]'                                
  856 |     template<typename... Ns> T &operator()(Ns... ns) const                                                                                                                                                                                                          |                                 ^~~~~~~~
bazel-out/k8-opt/bin/external/ducc/_virtual_includes/fft/ducc/src/ducc0/fft/fftnd_impl.h:1400:20: error: call of '(ducc0::detail_mav::vmav<std::complex<float>, 2>) (long unsigned int&, size_t&)' is ambiguous                                                       
 1400 |                 tmp(i,j) *= roots[i*j];              
      |                 ~~~^~~~~                                                                                                                                                                                                                                      external/ducc/src/ducc0/infra/mav.h:803:41: note: there are 2 candidates                   
  803 | template<typename T, size_t ndim> class vmav: public cmav<T, ndim>
      |                                         ^~~~            
external/ducc/src/ducc0/infra/mav.h:765:39: note: candidate 1: 'const T& ducc0::detail_mav::cmav<T, ndim>::operator()(Ns ...) const [with Ns = {long unsigned int, long unsigned int}; T = std::complex<float>; long unsigned int ndim = 2]'                            765 |     template<typename... Ns> const T &operator()(Ns... ns) const
      |                                       ^~~~~~~~         
external/ducc/src/ducc0/infra/mav.h:856:33: note: candidate 2: 'T& ducc0::detail_mav::vmav<T, ndim>::operator()(Ns ...) const [with Ns = {long unsigned int, long unsigned int}; T = std::complex<float>; long unsigned int ndim = 2]'                                
  856 |     template<typename... Ns> T &operator()(Ns... ns) const                                                                 
      |                                 ^~~~~~~~                                                                                   
bazel-out/k8-opt/bin/external/ducc/_virtual_includes/fft/ducc/src/ducc0/fft/fftnd_impl.h: In instantiation of 'void ducc0::detail_fft::c2c(const ducc0::detail_mav::cfmav<std::complex<_Tp> >&, const ducc0::detail_mav::vfmav<std::complex<_Tp> >&, const shape_t&, b
ool, T, size_t) [with T = double; shape_t = std::vector<long unsigned int>; size_t = long unsigned int]':                                                                                                                                                             
external/ducc/google/fft.cc:56:17:   required from 'void ducc0::google::c2c(const std::complex<_Tp>*, const Shape&, const Stride&, std::complex<_Tp>*, const Shape&, const Stride&, const Shape&, bool, RealScalar, Eigen::ThreadPoolInterface*) [with RealScalar = do
uble; Shape = std::vector<long unsigned int>; Stride = std::vector<long int>]'                                                     
   56 |       ducc0::c2c(m_in, m_out, axes, forward, scale, 1);                                                                    
      |       ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                                                        
external/ducc/google/fft.cc:144:1:   required from here 
  132 |       Eigen::ThreadPoolInterface* thread_pool);                                \                                           
      |                                              ^                                                                                                                                                                                                                
bazel-out/k8-opt/bin/external/ducc/_virtual_includes/fft/ducc/src/ducc0/fft/fftnd_impl.h:1393:20: error: call of '(ducc0::detail_mav::vmav<std::complex<double>, 2>) (long unsigned int&, size_t&)' is ambiguous                                                      
 1393 |                 tmp(i,j) *= conj(roots[i*j]);
      |                 ~~~^~~~~                                                                                                   
external/ducc/src/ducc0/infra/mav.h:803:41: note: there are 2 candidates                                                           
  803 | template<typename T, size_t ndim> class vmav: public cmav<T, ndim>                                                         
      |                                         ^~~~
external/ducc/src/ducc0/infra/mav.h:765:39: note: candidate 1: 'const T& ducc0::detail_mav::cmav<T, ndim>::operator()(Ns ...) const [with Ns = {long unsigned int, long unsigned int}; T = std::complex<double>; long unsigned int ndim = 2]'                         
  765 |     template<typename... Ns> const T &operator()(Ns... ns) const                                                           
      |                                       ^~~~~~~~           
external/ducc/src/ducc0/infra/mav.h:856:33: note: candidate 2: 'T& ducc0::detail_mav::vmav<T, ndim>::operator()(Ns ...) const [with Ns = {long unsigned int, long unsigned int}; T = std::complex<double>; long unsigned int ndim = 2]'                               
  856 |     template<typename... Ns> T &operator()(Ns... ns) const                                                                 
      |                                 ^~~~~~~~                 
bazel-out/k8-opt/bin/external/ducc/_virtual_includes/fft/ducc/src/ducc0/fft/fftnd_impl.h:1400:20: error: call of '(ducc0::detail_mav::vmav<std::complex<double>, 2>) (long unsigned int&, size_t&)' is ambiguous
 1400 |                 tmp(i,j) *= roots[i*j];
      |                 ~~~^~~~~
external/ducc/src/ducc0/infra/mav.h:803:41: note: there are 2 candidates
  803 | template<typename T, size_t ndim> class vmav: public cmav<T, ndim>
      |                                         ^~~~
external/ducc/src/ducc0/infra/mav.h:765:39: note: candidate 1: 'const T& ducc0::detail_mav::cmav<T, ndim>::operator()(Ns ...) const [with Ns = {long unsigned int, long unsigned int}; T = std::complex<double>; long unsigned int ndim = 2]'
  765 |     template<typename... Ns> const T &operator()(Ns... ns) const
      |                                       ^~~~~~~~
external/ducc/src/ducc0/infra/mav.h:856:33: note: candidate 2: 'T& ducc0::detail_mav::vmav<T, ndim>::operator()(Ns ...) const [with Ns = {long unsigned int, long unsigned int}; T = std::complex<double>; long unsigned int ndim = 2]'
  856 |     template<typename... Ns> T &operator()(Ns... ns) const
      |                                 ^~~~~~~~
bazel-out/k8-opt/bin/external/ducc/_virtual_includes/fft/ducc/src/ducc0/fft/fftnd_impl.h: In instantiation of 'void ducc0::detail_fft::copy_output(const Titer&, const T*, const ducc0::detail_mav::vfmav<T>&) [with T = float; Titer = multi_iter<8>]':
bazel-out/k8-opt/bin/external/ducc/_virtual_includes/fft/ducc/src/ducc0/fft/fftnd_impl.h:1270:20:   required from 'void ducc0::detail_fft::general_c2r(const ducc0::detail_mav::cfmav<ducc0::Cmplx<T> >&, const ducc0::detail_mav::vfmav<T>&, size_t, bool, T, size_t)
 [with T = float; size_t = long unsigned int]'
 1270 |         copy_output(it, res, out);
      |         ~~~~~~~~~~~^~~~~~~~~~~~~~
bazel-out/k8-opt/bin/external/ducc/_virtual_includes/fft/ducc/src/ducc0/fft/fftnd_impl.h:1489:14:   required from 'void ducc0::detail_fft::c2r(const ducc0::detail_mav::cfmav<std::complex<_Tp> >&, const ducc0::detail_mav::vfmav<T>&, size_t, bool, T, size_t) [with
 T = float; size_t = long unsigned int]'
 1489 |   general_c2r(in2, out, axis, forward, fct, nthreads);
      |   ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bazel-out/k8-opt/bin/external/ducc/_virtual_includes/fft/ducc/src/ducc0/fft/fftnd_impl.h:1497:15:   required from 'void ducc0::detail_fft::c2r(const ducc0::detail_mav::cfmav<std::complex<_Tp> >&, const ducc0::detail_mav::vfmav<T>&, const shape_t&, bool, T, size_
t) [with T = float; shape_t = std::vector<long unsigned int>; size_t = long unsigned int]'
 1497 |     return c2r(in, out, axes[0], forward, fct, nthreads); 
      |            ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/ducc/google/fft.cc:112:17:   required from 'void ducc0::google::c2r(const std::complex<_Tp>*, const Shape&, const Stride&, RealScalar*, const Shape&, const Stride&, const Shape&, bool, RealScalar, Eigen::ThreadPoolInterface*) [with RealScalar = float; S
hape = std::vector<long unsigned int>; Stride = std::vector<long int>]'
  112 |       ducc0::c2r(m_in, m_out, axes, forward, scale, 1);
      |       ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/ducc/google/fft.cc:143:1:   required from here
  142 |                     Eigen::ThreadPoolInterface* thread_pool)
      |                                                            ^
bazel-out/k8-opt/bin/external/ducc/_virtual_includes/fft/ducc/src/ducc0/fft/fftnd_impl.h:486:22: error: call of overloaded 'raw(ptrdiff_t)' is ambiguous
  486 |   if (src == &dst.raw(it.oofs(0))) return;  // in-place
      |               ~~~~~~~^~~~~~~~~~~~
bazel-out/k8-opt/bin/external/ducc/_virtual_includes/fft/ducc/src/ducc0/fft/fftnd_impl.h:486:22: note: there are 2 candidates
external/ducc/src/ducc0/infra/mav.h:118:35: note: candidate 1: 'const T& ducc0::detail_mav::cmembuf<T>::raw(I) const [with I = long int; T = float]'
  118 |     template<typename I> const T &raw(I i) const
      |                                   ^~~
external/ducc/src/ducc0/infra/mav.h:643:29: note: candidate 2: 'T& ducc0::detail_mav::vfmav<T>::raw(I) const [with I = long int; T = float]'
  643 |     template<typename I> T &raw(I i) const
      |                             ^~~
bazel-out/k8-opt/bin/external/ducc/_virtual_includes/fft/ducc/src/ducc0/fft/fftnd_impl.h: In instantiation of 'void ducc0::detail_fft::copy_output(const Titer&, const T*, const ducc0::detail_mav::vfmav<T>&) [with T = double; Titer = multi_iter<4>]':
bazel-out/k8-opt/bin/external/ducc/_virtual_includes/fft/ducc/src/ducc0/fft/fftnd_impl.h:1270:20:   required from 'void ducc0::detail_fft::general_c2r(const ducc0::detail_mav::cfmav<ducc0::Cmplx<T> >&, const ducc0::detail_mav::vfmav<T>&, size_t, bool, T, size_t)
 [with T = double; size_t = long unsigned int]'
 1270 |         copy_output(it, res, out);
      |         ~~~~~~~~~~~^~~~~~~~~~~~~~
bazel-out/k8-opt/bin/external/ducc/_virtual_includes/fft/ducc/src/ducc0/fft/fftnd_impl.h:1489:14:   required from 'void ducc0::detail_fft::c2r(const ducc0::detail_mav::cfmav<std::complex<_Tp> >&, const ducc0::detail_mav::vfmav<T>&, size_t, bool, T, size_t) [with
 T = double; size_t = long unsigned int]'
 1489 |   general_c2r(in2, out, axis, forward, fct, nthreads);
      |   ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bazel-out/k8-opt/bin/external/ducc/_virtual_includes/fft/ducc/src/ducc0/fft/fftnd_impl.h:1497:15:   required from 'void ducc0::detail_fft::c2r(const ducc0::detail_mav::cfmav<std::complex<_Tp> >&, const ducc0::detail_mav::vfmav<T>&, const shape_t&, bool, T, size_
t) [with T = double; shape_t = std::vector<long unsigned int>; size_t = long unsigned int]'
 1497 |     return c2r(in, out, axes[0], forward, fct, nthreads); 
      |            ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/ducc/google/fft.cc:112:17:   required from 'void ducc0::google::c2r(const std::complex<_Tp>*, const Shape&, const Stride&, RealScalar*, const Shape&, const Stride&, const Shape&, bool, RealScalar, Eigen::ThreadPoolInterface*) [with RealScalar = double; 
Shape = std::vector<long unsigned int>; Stride = std::vector<long int>]'
  112 |       ducc0::c2r(m_in, m_out, axes, forward, scale, 1);
      |       ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/ducc/google/fft.cc:144:1:   required from here
  142 |                     Eigen::ThreadPoolInterface* thread_pool)
      |                                                            ^
bazel-out/k8-opt/bin/external/ducc/_virtual_includes/fft/ducc/src/ducc0/fft/fftnd_impl.h:486:22: error: call of overloaded 'raw(ptrdiff_t)' is ambiguous
  486 |   if (src == &dst.raw(it.oofs(0))) return;  // in-place
      |               ~~~~~~~^~~~~~~~~~~~
bazel-out/k8-opt/bin/external/ducc/_virtual_includes/fft/ducc/src/ducc0/fft/fftnd_impl.h:486:22: note: there are 2 candidates
external/ducc/src/ducc0/infra/mav.h:118:35: note: candidate 1: 'const T& ducc0::detail_mav::cmembuf<T>::raw(I) const [with I = long int; T = double]'
  118 |     template<typename I> const T &raw(I i) const
      |                                   ^~~
external/ducc/src/ducc0/infra/mav.h:643:29: note: candidate 2: 'T& ducc0::detail_mav::vfmav<T>::raw(I) const [with I = long int; T = double]'
  643 |     template<typename I> T &raw(I i) const
      |                             ^~~
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 842.253s, Critical Path: 71.29s
INFO: 6244 processes: 2505 internal, 3739 local.
ERROR: Build did NOT complete successfully
(tamama) [tamama@admin--cde tensorflow-2.20.0]$ 
```

**Comment by tamama-plb** [comment]
- Confirmed that Tensorflow release-2.20.0 does not build on RockyLinux 9.6 under GCC-toolset-13, 14, 15.  
- Decide to fallback to v2.18, due to a whole lot of bug issues regarding TF-2.19.

Thanks.

**Comment by tamama-plb** [comment]
Fall back to

Bazel version: release 7.4.1
Tensorflow version: release v2.18.1
GCC: gcc-toolset-13
Python: Python 3.12 (via Conda/Mamba)

Error:
```
DEBUG: /home/tamama/.cache/bazel/_bazel_tamama/58b7608ca73a11d140fa1e0461b289ac/external/local_xla/third_party/py/python_repo.bzl:107:10: Using hermetic Python 3.12
ERROR: /mnt/volume/.vendor/cxx/github.com/tensorflow/tensorflow/tensorflow-2.18.1/tensorflow/python/BUILD:467:27: //tensorflow/python:_pywrap_tfcompile.so: no such attribute 'licenses' in 'cc_shared_library' rule
ERROR: /mnt/volume/.vendor/cxx/github.com/tensorflow/tensorflow/tensorflow-2.18.1/tensorflow/python/BUILD:515:27: //tensorflow/python:_pywrap_py_exception_registry.so: no such attribute 'licenses' in 'cc_shared_library' rule
ERROR: /mnt/volume/.vendor/cxx/github.com/tensorflow/tensorflow/tensorflow-2.18.1/tensorflow/python/BUILD:1194:27: //tensorflow/python:_pywrap_tfe.so: no such attribute 'licenses' in 'cc_shared_library' rule
ERROR: /mnt/volume/.vendor/cxx/github.com/tensorflow/tensorflow/tensorflow-2.18.1/tensorflow/BUILD:1689:14: Target '//tensorflow/python:no_contrib' contains an error and its package is in error and referenced by '//tensorflow:tf_python_api_gen_v2.extract-tensorflow'
Target //tensorflow:virtual_root_init_gen failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: Analysis of target '//tensorflow:tf_python_api_gen_v2.extract-tensorflow' failed; build aborted: Analysis failed
INFO: Elapsed time: 38.322s, Critical Path: 0.22s
INFO: 2 processes: 1 internal, 1 local.
ERROR: Build did NOT complete successfully
FAILED: 
    Fetching repository @@go_sdk; Finding Go SHA-256 sums
    Fetching repository @@bazel_features~; Patching repository
    Fetching repository @@flatbuffers; starting
    Fetching repository @@pypi_keras; starting
    Fetching repository @@python_x86_64-unknown-linux-gnu; starting
    Fetching /home/tamama/.cache/bazel/_bazel_tamama/58b7608ca73a11d140fa1e0461b289ac/external/flatbuffers; Extracting e6463926479bd6b330cbcf673f7e917803fd5831.tar.gz
    Fetching repository @@pypi_tensorboard; starting
    Fetching repository @@rules_cc~; Patching repository
(zz-tamama-1) [tamama@admin--cde current]$ 
```

Version check:
```
(zz-tamama-1) [tamama@admin--cde current]$ python --version
Python 3.12.12
(zz-tamama-1) [tamama@admin--cde current]$ 
(zz-tamama-1) [tamama@admin--cde current]$ gcc --version
gcc (GCC) 13.3.1 20240611 (Red Hat 13.3.1-2)
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(zz-tamama-1) [tamama@admin--cde current]$ 
(zz-tamama-1) [tamama@admin--cde current]$ bazel --version
bazel 7.4.1- (@non-git)
(zz-tamama-1) [tamama@admin--cde current]$ 
```

OK - Compatibility matrix indicates that I should fall back to Bazel-6.5.0
However, Bazel-6.5.0 installation does not support Java-21 - so I think I will stop here...

As of current, I use TF-2.18 shared libraries from python site-packages directly - so no pressure here tbh.

However, I would still want to compile TF from source, because I would like to compile with  _-s -O3 -march=native_ (providing machine optimzation such as AVX etc...)

Would the TF team kindly provide some guide of version compability matrix which actually work? 

Thank you in advance.

Kind regards,
Tama MA

**Comment by tamama-plb** [comment]
OK - I get it compiled with the following spec:

- Tensorflow - release 2.20.0
- Bazel - release 7.4.1
- CC - clang-19.1.7 (via redhat llvm-toolset).   - WARNING: **Not working with neither of the recent GCCs** - GCC-13, 14, 15.
- Python 3.13 via Conda/Mamba

Close Issue.
