### ISSUE TITLE
contrib.layers.avg_pool2d raises warnings when serializing metagraph

### ISSUE THREAD

**Issue by nryant** [tensorflow/tensorflow#9939]
### System information

- **OS Platform and Distribution**: Ubuntu 14.04 LTS
- **TensorFlow installed from**: source
- **TensorFlow version**:  ('v1.1.0-rc2-1015-gf2047a3', '1.1.0-rc2')
- **Bazel version**: 0.4.5
- **CUDA/cuDNN version**: 8.0/5.1.5
- **GPU model and memory**: Maxwell Titan X (12 GiB)

### Overview of problem
Since updating to the most recent version (as of yesterday) of TensorFlow, I've started seeing the following ominous warning when serializing a wide resnet variant that I've been using for acoustic modeling:

    WARNING:tensorflow:Error encountered when serializing LAYER_NAME_UIDS.
    Type is unsupported, or the types of the items don't match field type in CollectionDef.
    'dict' object has no attribute 'name'

However, a metagraphdef does export and I am able to successfully use it to recreate the trained model. After playing around with simpler architectures, it looks like the problem comes from the average pooling I do at the end, which involves a call to ``tf.contrib.layers.avg_pool2d``. For a trivial example that elicits this warning, please see the script at 

    https://gist.github.com/nryant/1f69cda71fd6a468fa5641855199f843

**Comment by ali01** [comment]
Hi @sherrym, are you able to take a look? Thanks!

**Comment by JeremyCCHsu** [comment]
I also frequently encounter this issue since I started to use the `tf.layers` module in TF 1.1.
It seems that something related to naming went wrong in some of the modules.

For example, the following code triggered the issue:
```python
import tensorflow as tf

x = tf.zeros([10, 3])
y = tf.layers.dense(x, 5)  # the issue is originated from this line

sv = tf.train.Supervisor()
sess = sv.prepare_or_wait_for_session()
sv.saver.save(sess, '.')
```
Return:
```
WARNING:tensorflow:Error encountered when serializing LAYER_NAME_UIDS.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'dict' object has no attribute 'name'
```

However, the issue can be easily avoided (in this simple case) by specifying the `name` argument:
In contrast, using `slim`, `keras`, or `tf.Variable` doesn't trigger such an issue.
Here are some examples that work smoothly without triggering the warning above.
```python
# The Tensorflow infrastructure
w = tf.Variable(tf.zeros([3, 5]))
y = tf.matmul(x, w)
```

```python
# The `layers` module with the `name` arg specified
y = tf.layers.dense(x, 5, name='y')
```

```python
# Slim
from tensorflow.contrib import slim
y = slim.fully_connected(x, 5)
```

```python
# Keras
y = tf.contrib.keras.layers.Dense(units=5)(x)
```

**Comment by lsqpku** [comment]
@JeremyCCHsu, I use slim but am yet encountered by this issue AFTER I upgrade from tf 1.0.1 to 1.1. 
environment info:
python 2.7
gpu: k40c with cudn 8.0
rhel: 6.5
tf: binary installation

**Comment by neighthan** [comment]
Also getting this error on tf 1.1 even though I've passed names to all tf.layers commands (at least, I think so. If it's useful, I can try to find a minimal example of this where it doesn't come from an unnamed tf.layers).

**Comment by EdeMeijer** [comment]
I'm getting the exact same error, but I'm not using any `tf.layers`. I'll see if I can create a minimal example.

**Comment by EdeMeijer** [comment]
I did a quick debugging session, and it seems the issue was introduced in https://github.com/tensorflow/tensorflow/commit/1e3e5d424eaa6332314f8ad1d54089eb0f9e02e7 by adding a dictionary named `LAYER_NAME_UIDS` as a graph collection. I'm not sure on the internals, but my feeling is that collections are not meant for dictionaries, only for ops, as the serialization code apparently expects to be able to access a `name` property on all collection entries.

The dictionary serves as a global (or technically graph-local) store for tracking counters per base name to make unique names. As a proof of concept I defined `layer_name_uids` globally as a struct and just used that without using collections, and this fixed the graph serialization issue.

I hope someone with more in-depth knowledge on this code could take a look. Maybe @fchollet who authored the commit in question?

**Comment by EdeMeijer** [comment]
As a temporary workaround, running `del tf.get_collection_ref('LAYER_NAME_UIDS')[0]` before exporting the graph seems to work.

**Comment by amygdala** [comment]
FWIW, I get the same warning when running [this](https://github.com/GoogleCloudPlatform/training-data-analyst/tree/master/blogs/timeseries/simplernn) rnn example using TF 1.2 rc0.
Don't see it in TF 1.1.
```
WARNING:tensorflow:Error encountered when serializing LAYER_NAME_UIDS.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'dict' object has no attribute 'name'
```

**Comment by jart** [comment]
@ebrevdo has done some work on contrib.layers recently. Mind taking a look at why this warning message is being printed?

**Comment by ebrevdo** [comment]
This is a harmless warning.  Layers perform bookkeeping inside a specially
named graph collection. The bookkeeping doesn't need to be serialized
across meta graph save/reload, so we haven't added the appropriate
serialization classes.

**Comment by thinxer** [comment]
It is a harmless warning. It is still a warning, and users keep asking what is the meaning of this warning.

It seems that originally the bookkeeping is done within each package (slim, layers, etc). Then the bookkeeping  dict gets moved into a special collection, so that the packages can share the bookkeeping code.

It seems that TensorFlow collections are used for collecting Tensors only. I suggest that we do not re-use the collections, and use some other means to share the bookkeeping dict.

Or, at least we can set a flag so that MetaGraph Savers don't try to serialize that.

**Comment by neighthan** [comment]
I find that *harmless warnings* are a little silly. I don't want to be warned about harmless things. Then it becomes very difficult for me to find the real warnings. Or I just turn warnings off because it's bothersome to have so much text output with no meaning. I'll just add the fix by @EdeMeijer to my code for now, but it is a bit hacky to have to do. As I save models while I'm still training them, though (which is why the number of warnings is enough to be troublesome), I wonder if I ought to make a copy of the dictionary, then delete it when I export the model to avoid the warning, then restore it so that it's there if something in the layers expects it later? By the time the workaround is that long (admittedly only a few lines of code), I'd be glad to have something incorporated that took care of it for me.

**Comment by jart** [comment]
Thanks @ebrevdo for helping us know that there's no cause for alarm. How do you think this issue should be triaged? I agree with our friends that, ideally speaking, warnings should be as helpful as possible. So maybe contributions welcome?

**Comment by domschl** [comment]
Still present in 1.2rc1:
`WARNING:tensorflow:Error encountered when serializing LAYER_NAME_UIDS.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'dict' object has no attribute 'name'`
@ali01 : please reclassify, this isn't a feature-request, but a bug: This worked fine until 1.1, then models that were working without error-messages suddenly produce the error-message above.
That causes people first to assume a breaking API-change, then to look for problems in their own model definition, when finding out that model-saves cause this, and finally to start digging in tf's code for the reason of this message, which by it self sounds like the model-save did _not_ work.

**Comment by ebrevdo** [comment]
Francois and Sherry should probably come to a decision. Either keras keeps
an internal dictionary or we find a way to signal to saver to mark some
collections as local.

**Comment by tfboyd** [comment]
Fix is checked in internally and should get synced today.  I am attempting to make sure it is in the next 1.2 RC as a final cherry pick.

**Comment by tfboyd** [comment]
This is in with this https://github.com/tensorflow/tensorflow/pull/10359   and I have it on the list to get cherry-picked into 1.2 RC2.  I will double check as long as I do not forget.

**Comment by HectorSVC** [comment]
@tfboyd

I still get this error when I tried to use tf.add_to_collection to add a dictionary/list to the collection. Is it the same issue? I tested with latest 1.2.1 build for windows.

WARNING:tensorflow:Error encountered when serializing exporter_interface.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'xxxx' object has no attribute 'name'
