### PR TITLE
Expose tf.keras.preprocessing.text.tokenizer_from_json to match Keras API

### LINKED ISSUE #30061: Method mentioned in documentation is missing: tf.keras.preprocessing.text.tokenizer_from_json
**System information**
- TensorFlow version: v2.0.0-beta0-16-g1d91213fe7 2.0.0-beta1

**Describe the current behavior**
Error raised when attempting to call `tf.keras.preprocessing.text.tokenizer_from_json`:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
----> 1 tf.keras.preprocessing.text.tokenizer_from_json

AttributeError: module 'tensorflow.python.keras.api._v2.keras.preprocessing.text' has no attribute 'tokenizer_from_json'
```

**Describe the expected behavior**
I expect this method to be callable per the documentation of `tf.keras.preprocessing.text.Tokenizer.to_json` (below), which says we can use `keras.preprocessing.text.tokenizer_from_json(json_string)` to load a tokenizer.

Otherwise, there's no obvious way to use the output of `Tokenizer.to_json` to restore a tokenizer.

```
Signature: tf.keras.preprocessing.text.Tokenizer.to_json(self, **kwargs)
Docstring:
Returns a JSON string containing the tokenizer configuration.
To load a tokenizer from a JSON string, use
`keras.preprocessing.text.tokenizer_from_json(json_string)`.

# Arguments
    **kwargs: Additional keyword arguments
        to be passed to `json.dumps()`.

# Returns
    A JSON string containing the tokenizer configuration.
```
**Code to reproduce the issue**
```python3
json_string = tf.keras.preprocessing.text.Tokenizer().to_json()
tf.keras.preprocessing.text.tokenizer_from_json(json_string)
```

### PR DESCRIPTION
**Pull request by yongtang**
This fix tries to address the issue raised in #30061 where `tf.keras.preprocessing.text.tokenizer_from_json` is not available, while in keras, `keras.preprocessing.text.tokenizer_from_json` is available.

This fix expose `tf.keras.preprocessing.text.tokenizer_from_json` and alias to `keras.preprocessing.text.tokenizer_from_json`, like all other similar APIs in the same keras_proprocessing/text.py

This fix fixes #30061.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Review by pavithrasv — APPROVED** [review]
Thank you for the PR!

**Comment by mihaimaruseac** [comment]
This broke a lot of builds and is now rolled back in c205be168295893f7f49be3ed8c9d5d14e0307a4

```python
  File ".../tensorflow/python/keras/preprocessing/text.py", line 30, in <module>
    tokenizer_from_json = text.tokenizer_from_json
AttributeError: 'module' object has no attribute 'tokenizer_from_json'
```

**Comment by HubberDev** [comment]
Any update on this issue?

**Comment by mihaimaruseac** [comment]
It has never been rolled forward :(

I'll attempt something later today

**Comment by mihaimaruseac** [comment]
This cannot be done before we update the keras-preprocessing dependency to a newer version. As of now, `text` module doesn't contain `tokenizer_from_json`

I think we might try this next week, please ping me if this gets delayed more.

**Comment by mike-edmonds** [comment]
is there an ETA for this fix?  If not, is there a temporary workaround (besides going back to tf1)?

**Comment by mihaimaruseac** [comment]
Please ping me after TF2.0-RC0 is released to check.

**Comment by yongtang** [comment]
@mihaimaruseac @mike-edmonds Since 2.0.0RC0 has been released, I created a PR #31946 to re-apply the changes.

**Comment by oldmonkABA** [comment]
> Please ping me after TF2.0-RC0 is released to check.

Could you tell when this will be fixed.

**Comment by HubberDev** [comment]
Ping， the fix is not part of rc1 yet.

**Comment by mihaimaruseac** [comment]
We cannot release it in 2.0 as it depends on us changing some setup on our release infrastructure (as it requires newer keras-preprocessing). So we have to wait until 2.0 is released and then the fix will land in master in 1-2 days. Sorry about this.

**Comment by nlpds** [comment]
@mihaimaruseac Is there any update on this issue?

**Comment by mihaimaruseac** [comment]
Blocked on a 1.15 release pending. We cannot update the release infrastructure while a release is pending. Sorry about this

**Comment by mihaimaruseac** [comment]
This is fixed now
