### ISSUE TITLE
AttributeError: 'KerasTPUModel' object has no attribute '_distribution_strategy'

### ISSUE THREAD

**Issue by ValentinMezev** [tensorflow/tensorflow#27290]
I load inceptionV3 with:

```
from keras.applications import InceptionV3

model= InceptionV3(weights='imagenet',
                             include_top=False,
                             pooling='max',
                             input_shape=(229, 229, 3))
```

Then I convert it to TPU model with:

```
TPU_WORKER = 'grpc://10.x.x.x:8470'
model = tf.contrib.tpu.keras_to_tpu_model(
            model,
            strategy=tf.contrib.tpu.TPUDistributionStrategy(
                tf.contrib.cluster_resolver.TPUClusterResolver(TPU_WORKER)))
```

And I try to extract feature vector of an image with:

`model.predict`

The error I receive is

>  AttributeError: 'KerasTPUModel' object has no attribute '_distribution_strategy'

My code works fine without the TPU part, however its very slow and I want to do the predict part on TPU for better performance.

**Comment by jvishnuvardhan** [comment]
@ValentinMezev Please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. Thanks!

**Comment by ValentinMezev** [comment]
Hi @jvishnuvardhan 
Thank you for your reply and guidance. Apologies for the poor description. Here is the filled template:

**System information**
- OS Platform and Distribution: Ubuntu 18.10 cosmic
- Mobile device: N/A
- TensorFlow installed from (source or binary): installed with pip install tensorflow
- TensorFlow version:
- Python version: tensorflow (1.13.1); tensorflow-estimator (1.13.0)
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): not sure
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 8.2.0-7ubuntu1) 8.2.0
- CUDA/cuDNN version: N/A
- GPU model and memory: Using GCP TPU



**Describe the problem**
I use InceptionV3 from tf.keras.applications for feature extraction.
When I obtain the model I call predict on it in order to extract the features.
This works but slow and I want to use TPU. I saw keras_to_tpu_model function I can use to transform Keras model into KerasTPUModel which should run on TPU.

Here is my code:
`from keras.applications import InceptionV3

model= InceptionV3(weights='imagenet',
                             include_top=False,
                             pooling='max',
                             input_shape=(229, 229, 3))

TPU_WORKER = 'grpc://10.x.x.x:8470'
model = tf.contrib.tpu.keras_to_tpu_model(
            model,
            strategy=tf.contrib.tpu.TPUDistributionStrategy(
                tf.contrib.cluster_resolver.TPUClusterResolver(TPU_WORKER)))

model.predict(source)`

The error thrown is:

> AttributeError: 'KerasTPUModel' object has no attribute '_distribution_strategy'

**Comment by jhseu** [comment]
That particular implementation was a placeholder.

Sourabh might know if TPUStrategy works with predict in TF 1.13:
https://www.tensorflow.org/versions/r1.13/api_docs/python/tf/contrib/distribute/TPUStrategy?hl=en

**Comment by ymodak** [comment]
`tf.contrib.tpu.keras_to_tpu_model` is deprecated use [tf.distribute.TPUStrategy](https://www.tensorflow.org/api_docs/python/tf/distribute/TPUStrategy) instead.
See https://www.tensorflow.org/guide/tpu for usage details
