### ISSUE TITLE
Compile tensorflow with compile option "-xMIC-AVX512" does not work

### ISSUE THREAD

**Issue by sjlee7748** [tensorflow/tensorflow#4775]
Hi, All

I want to use AVX512 with tensorflow because vectorization can increase performance.
In addition, building any program with icpc(Intel compiler) and compile option "-xMIC-AVX512" can vectorize automatically in state-of-art Intel machine.
So, I use the command as below:

`CC=icpc bazel build -c opt --copt=-xMIC-AVX512 //tensorflow/tools/pip_package:build_pip_package`

But when I type the command, build does not work.
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
- Nothing exist related my issue in GitHub or StackOverflow
### Environment info
- Operating System: Centos 7.2.1511 
- Tensorflow version: r0.10.0 source code version
- Only use CPU
### What other attempted solutions have you tried?

As far as I know, linear algebra library for Tensorflow is "Eigen library" and SIMD vectorizations(like SSE, AVX, etc.) are applied to the Eigen library.
So, I changed Eigen source code to apply the AVX512 and gcc compile option "-mavx512f" referring two links([eigen bug report](http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1306), [Benoit Steiner's Bitbucket](https://bitbucket.org/benoitsteiner/eigen-avx512)), but I didn't apply AVX512 because there was little information about that.

If someone know the method about applying AVX512 or the date to release Eigen version with AVX512,  please tell me about that.

Thank you very much.

**Comment by tripiana** [comment]
Few months ago I was able to compile tf for knl with gcc 6.1.0 and some gcc patches. But in the end I was unable to get good performance. I used good flags but seems like poor vectorization.

Somebody can add more info on this?

**Comment by yaroslavvb** [comment]
BTW, I ran all the tf tests under avx2 about 12 months ago, and there were several ops which gave incorrect answers or failed (alignment problems). At that point @benoitsteiner has fixed them in Eigen, but I'm not sure anyone tried testing advanced flags since then (it's not part of CI pipeline for sure), so there's a chance you get unexpected/incorrect results

**Comment by benoitsteiner** [comment]
Support for AVX512 in TensorFlow is still a work in progress. I'll link to the relevant code changes as we make them to keep everyone updated.

**Comment by sjlee7748** [comment]
@tripiana @yaroslavvb thank you for attention of my question :) 
@benoitsteiner I'm really happy to hear that. If you don't mind, would you tell me  approximate date(e.g. about a month) to link the relevant code? Thank you so much!

**Comment by sjlee7748** [comment]
@benoitsteiner Is it still going on? I waited until a month but  I don't have any information about that. I am very appreciated if you tell me the progress, Thank you!

**Comment by benoitsteiner** [comment]
The code that adds support for AVX512 to Eigen is pending a review before I can merge it (https://bitbucket.org/eigen/eigen/pull-requests/235). Once it's in I'll update TensorFlow to make use of the new capability.

**Comment by sjlee7748** [comment]
I think It's almost finished. Thank you for your support.

**Comment by alquraishi** [comment]
Just to confirm, is it safe to compile with avx2 or not? @yaroslavvb was mentioning possible bugs / numerical errors.

**Comment by mccajm** [comment]
@benoitsteiner I'm keen to test this. Are you planning to update TensorFlow soon? Thanks.

**Comment by dave-andersen** [comment]
@alquraishi  - it should be safe to run with avx2, yes.  (Run the tests to be sure, of course, but it gets routinely used.)

Note that in general, -mavx will probably get you a lot of the performance boosts, since what avx2 adds over avx is primarily integer support, and -mavx already has the wider vector float support.  I haven't surveyed it, but -mavx is used widely.  But you're safe using -mavx2 if you have it.

**Comment by craftlk** [comment]
Does Eigen support AVX512 in tf now ?

**Comment by craftlk** [comment]
@benoitsteiner  Hi, this command "CC=icpc bazel build -c opt --copt=-xMIC-AVX512 //tensorflow/tools/pip_package:build_pip_package" still can't be applied on KNL server. Is the new tensorflow merged?

**Comment by craftlk** [comment]
@yaroslavvb Hi,I can't even build with icpc as:"CC=icpc bazel build -c opt  //tensorflow/tools/pip_package:build_pip_package".  Can you give some help?

**Comment by c0710204** [comment]
@craftlk I overwrite the CROSSTOOL under subdir in `bazel-tensorflow` and that worked.
By the way  eigen said that they support AVX-512 now(Eigen3.3.0/Tensorflow0.11+/require `--copt='-DEIGEN_ENABLE_AVX512`)
On the other hand @benoitsteiner implemented the AVX-512 support for Fixedpoint last week. However, due to the use of AVX-512 DQ in that part, that implement cannot compiling on KNL.

**Comment by sjlee7748** [comment]
@c0710204 Hi, I want to know detailed information about how you compile tensorflow with AVX 512.
When I used option '--copt=-DEIGEN_ENABLE_AVX512', compiling the source code is okay, but there was no speedup. (I think the option was not applied)
So, I want to know what is your version of tensorflow and compiling command.
Additionally, If you use further action, please tell me about that.

Thank you.

**Comment by c0710204** [comment]
@sjlee7748 Do you also add the  the avx512 compile flag like ‘--copt=“-mavx512f”'?  You can add macro to Eigen code to check it worked or not. The version I used is before the avx-512 Fixedpoint function add into the tensorflow(because I used the Xeon-phi when i build) 
The command I used is 
```bash
bazel build --ignore_unsupported_sandboxing -c opt //tensorflow/tools/pip_package:build_pip_package  --copt "-mavx512f" --copt "-mavx512cd" --copt "-mavx512er" --copt "-mavx512pf" --copt "-mavx2" --copt "-fopt-info-vec-all" --copt "-DEIGEN_ENABLE_AVX512" --copt "-DEIGEN_ENABLE_AVX2"  --verbose_failures   -j 64
```

**Comment by sjlee7748** [comment]
@c0710204 When I used your command, I had below errors.
`gcc: error: unrecognized command line option '-mavx512f'`
`gcc: error: unrecognized command line option '-mavx512cd'`
`gcc: error: unrecognized command line option '-mavx512er'`
`gcc: error: unrecognized command line option '-mavx512pf'`

I think this error related with Tensorflow , OS and GCC version, but I don't know what is the best combination. Please tell me about that.
( I have executed tensorflow 0.12.0 version with CentOS 7.2 and GCC 4.8.5)

Thank you.

**Comment by c0710204** [comment]
Oh ,sorry.I forgot the gcc version.To use avx-512, you must use gcc 4.9+ (I suggest use latest version like gcc 6.x)
To set the gcc you can change the bazel cache file (path looks like  `*****/external/local_config_cc/CROSSTOOL`). It will generated by bazel after 1 build (bazel clean will delete it)

**Comment by jiazhentim** [comment]
Hi @c0710204, I tried your command to build TF on Xeon Phi, but failded. Like describe in [https://github.com/tensorflow/tensorflow/issues/7116](url), Could you help to figure out what is wrong?

**Comment by drpngx** [comment]
Just to put the links in github form: #7116, #6349

**Comment by aselle** [comment]
@benoitsteiner , it looks the eigen change was merged. Could you post an update and close this if relevant?

**Comment by craftlk** [comment]
@benoitsteiner ,  How to confirm that it's eigen that caused this problem?

**Comment by DaejinJung** [comment]
@drpngx @benoitsteiner 
Hello, is there any update on this issue? I am waiting your comments.

**Comment by drpngx** [comment]
Reading the thread, it looks like Eigen was updated. @DaejinJung , @craftlk did you try?

**Comment by jiazhentim** [comment]
Hi just pull the master branch. I use the command "bazel build -c opt --copt "-mavx512pf" //tensorflow/tools/pip_package:build_pip_package". The error is as fellows:

 ./third_party/eigen3/unsupported/Eigen/CXX11/src/FixedPoint/PacketMathAVX512.h:84:11: error: 'Packet16q16i' does not name a type
   typedef Packet16q16i half;
           ^
./third_party/eigen3/unsupported/Eigen/CXX11/src/FixedPoint/PacketMathAVX512.h:135:11: error: 'Packet16q16i' does not name a type
   typedef Packet16q16i half;
The message is same as I got before.

**Comment by drpngx** [comment]
Did you run configure again? It needs to bazel fetch

**Comment by jiazhentim** [comment]
Yes, I run configure @drpngx

**Comment by drpngx** [comment]
Looking at @benoitsteiner 's [link](https://bitbucket.org/eigen/eigen/pull-requests/235/added-support-for-avx512-to-eigen/diff), we merged Half support from `unsupported` to `Core`, in `arch/AVX512` and some in `arch/CUDA`. It looks like what needs to happen is that we update our internal code to include the right headers and use the right definition if necessary, away from `unsupported` and using the new `arch/` headers.

**Comment by drpngx** [comment]
What happens when you go to the `unsupported/FixedPoint` [header](https://github.com/tensorflow/tensorflow/blob/master/third_party/eigen3/unsupported/Eigen/CXX11/FixedPoint#L35) and replace the includes with the new ones?

```
#include "src/Core/arch/AVX512/PacketMath.h"
#include "src/Core/arch/CUDA/TypeCasting.h"
```

**Comment by benoitsteiner** [comment]
I've added the missing definition for Packet16q16i in https://github.com/tensorflow/tensorflow/pull/7820. That should solve the immediate compilation error. I think there are a few more primitives missing though.

**Comment by jiazhentim** [comment]
Hi @benoitsteiner , there is still an error:
tensorflow/core/kernels/split_lib_cpu.cc:43:1:   required from here
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/GenericPacketMath.h:467:16: error: 'alignment' is not a member of 'Eigen::internal::unpacket_traits<Eigen::internal::Packet64q8u>'
   if(Alignment >= unpacket_traits<Packet>::alignment)
                ^
Target //tensorflow/tools/pip_package:build_pip_package failed to build

**Comment by jiazhentim** [comment]
Hi @drpngx, I tried and the came across a fatal error:
In file included from ./tensorflow/core/framework/numeric_types.h:25:0,
                 from ./tensorflow/core/framework/allocator.h:23,
                 from ./tensorflow/core/framework/op_kernel.h:22,
                 from tensorflow/contrib/input_pipeline/kernels/input_pipeline_kernels.cc:16:
./third_party/eigen3/unsupported/Eigen/CXX11/FixedPoint:36:45: fatal error: src/Core/arch/AVX512/PacketMath.h: No such file or directory

**Comment by drpngx** [comment]
@jiazhentim we have to wait for #7820 to be merged. If you want to check if that would solve your problem, you could try it locally:

```
git fetch origin pull/7820/head:pr7820
git checkout pr7820
```

**Comment by drpngx** [comment]
#7820 was merged, please try now.

**Comment by benoitsteiner** [comment]
I've just checked that bazel build --copt=-march=skylake //tensorflow/tools/pip_package:build_pip_package now works with gcc 6.2 with the latest version of the codebase.

**Comment by drpngx** [comment]
Woohoo!

**Comment by jiazhentim** [comment]
Thanks, it works now.

**Comment by jiazhentim** [comment]
And is there a way to compile Tensorflow with ICC on KNL? I can compile it with gcc.

**Comment by TaoLv** [comment]
@jiazhentim Try export CC=/yout/path/of/icpc, and then call bazel to build tensorflow.

**Comment by Nayana-ibm** [comment]
Could you please let me know the exact command to build TensorFlow on Intel x86 platform (Ubuntu 16.04/18.04) with avx/avx2 and avx512 support?  And which gcc is required?
