### PR TITLE
Fix some symbols error for cmake.

### PR DESCRIPTION
**Pull request by flyinskyin2013**
### Patch 
Fix about "undefined reference to __android_log_vprint" and "multiple definition of tflite::logging_internal::MinimalLogger::LogFormatted"

### Note
When I compile libtensorflow-lite.so for android by cmake, I get those problems.

### How to recurrence
```shell
mkdir build_tflite
cd build_tflite
cmake -DCMAKE_INSTALL_PREFIX=/xxxxx/install -DBUILD_SHARED_LIBS=True -DCMAKE_TOOLCHAIN_FILE=/xxxxx/ndk/21.4.7075529/build/cmake/android.toolchain.cmake -DANDROID_ARM_NEON=ON -DANDROID_PLATFORM=android-21  -DTFLITE_ENABLE_GPU=ON -DANDROID_ABI=arm64-v8a ../tensorflow/lite
make -j16
```
By the way, this patch will work well on tag-v2.8.2. if you want to test it on master,  there are some error about "tensorflow_profiler_logger", maybe someone should fix it.

### CODE REVIEW

**Comment by MeghnaNatraj** [comment]
The changes look good, but could you elaborate "if you want to test it on master, there are some error about "tensorflow_profiler_logger", maybe someone should fix it."

**Comment by flyinskyin2013** [comment]
> The changes look good, but could you elaborate "if you want to test it on master, there are some error about "tensorflow_profiler_logger", maybe someone should fix it."

On master, it will also report 'undefined reference to tensorflow::profiler::ScopedMemoryDebugAnnotation::ThreadMemoryDebugAnnotation()', becuase we don't include the file (tensorflow\core\profiler\lib\scoped_memory_debug_annotation.cc) in cmakelists.txt. I can solve it by importing this file from tensorflow to tflite, but I don't think it' a good solution.

How do you think that? @MeghnaNatraj

**Comment by gbaned** [comment]
Hi @MeghnaNatraj Can you please review this PR ? Thank you!

**Review by JunyoungLim — APPROVED** [review]

**Comment by JunyoungLim** [comment]
Hi @flyinskyin2013 , 

I gave an approval for this change, but I'm not sure if we should merge this before confirming that the master branch is not breaking with this.

Regarding the `undefined reference to tensorflow::profiler::ScopedMemoryDebugAnnotation::ThreadMemoryDebugAnnotation()` issue you mentioned earlier, could you check if that error still exists in master? And is that error being introduced by this change?

**Comment by gbaned** [comment]
Hi @flyinskyin2013 Any update on this PR? Please. Thank you!

**Comment by flyinskyin2013** [comment]
### Test(master: 4abdd895ea3d266988ee3405b96dac459e2128ad)
There are build-error-msg:
```
CMakeFiles/tensorflow-lite.dir/minimal_logging_default.cc.o: In function `tflite::logging_internal::MinimalLogger::LogFormatted(tflite::LogSeverity, char const*, std::__va_list)':
tensorflow/lite/minimal_logging_default.cc:34: multiple definition of `tflite::logging_internal::MinimalLogger::LogFormatted(tflite::LogSeverity, char const*, std::__va_list)'
CMakeFiles/tensorflow-lite.dir/minimal_logging_android.cc.o:tensorflow/lite/minimal_logging_android.cc:45: first defined here
CMakeFiles/tensorflow-lite.dir/minimal_logging_default.cc.o: In function `tflite::logging_internal::MinimalLogger::LogFormatted(tflite::LogSeverity, char const*, std::__va_list)':
tensorflow/lite/minimal_logging_default.cc:34: multiple definition of `tflite::logging_internal::MinimalLogger::minimum_log_severity_'
CMakeFiles/tensorflow-lite.dir/minimal_logging_android.cc.o:tensorflow/lite/minimal_logging_android.cc:45: first defined here
CMakeFiles/tensorflow-lite.dir/nnapi/nnapi_handler.cc.o: In function `NnApiHandler':
tensorflow/lite/nnapi/nnapi_handler.h:306: undefined reference to `tsl::internal::LogMessageFatal::LogMessageFatal(char const*, int)'
tensorflow/lite/nnapi/nnapi_handler.h:306: undefined reference to `tsl::internal::LogMessageFatal::~LogMessageFatal()'
tensorflow/lite/nnapi/nnapi_handler.h:306: undefined reference to `tsl::internal::LogMessageFatal::~LogMessageFatal()'
CMakeFiles/tensorflow-lite.dir/delegates/gpu/delegate.cc.o: In function `DelegateAsyncKernel':
tensorflow/lite/delegates/gpu/delegate.cc:824: undefined reference to `kTfLiteSyncTypeNoSyncObj'
tensorflow/lite/delegates/gpu/delegate.cc:824: undefined reference to `kTfLiteSyncTypeNoSyncObj'
CMakeFiles/tensorflow-lite.dir/delegates/gpu/delegate.cc.o: In function `tflite::gpu::(anonymous namespace)::DelegateAsyncKernel::ReconcileRestrictions(TfLiteOpaqueContext*, TfLiteOpaqueNode*, int, TfLiteAttributeMap const*, TfLiteAttributeMap*, TfLiteAttributeMap*) const':
tensorflow/lite/delegates/gpu/delegate.cc:911: undefined reference to `TfLiteAttributeMapIsBufferAttributeMap'
tensorflow/lite/delegates/gpu/delegate.cc:912: undefined reference to `TfLiteAttributeMapIsBufferAttributeMap'
tensorflow/lite/delegates/gpu/delegate.cc:919: undefined reference to `TfLiteAttributeMapIsBufferAttributeMap'
tensorflow/lite/delegates/gpu/delegate.cc:928: undefined reference to `tflite::delegates::utils::ReadBufferAttrs(TfLiteAttributeMap const*)'
tensorflow/lite/delegates/gpu/delegate.cc:930: undefined reference to `tflite::delegates::utils::WriteBufferAttrs(tflite::delegates::utils::BufferAttributes const&, TfLiteAttributeMap*)'
tensorflow/lite/delegates/gpu/delegate.cc:932: undefined reference to `tflite::delegates::utils::WriteBufferAttrs(tflite::delegates::utils::BufferAttributes const&, TfLiteAttributeMap*)'
tensorflow/lite/delegates/gpu/delegate.cc:936: undefined reference to `TfLiteAttributeMapIsSyncAttributeMap'
tensorflow/lite/delegates/gpu/delegate.cc:937: undefined reference to `TfLiteAttributeMapIsSyncAttributeMap'
tensorflow/lite/delegates/gpu/delegate.cc:944: undefined reference to `TfLiteAttributeMapIsSyncAttributeMap'
tensorflow/lite/delegates/gpu/delegate.cc:953: undefined reference to `tflite::delegates::utils::ReadSyncAttrs(TfLiteAttributeMap const*)'
tensorflow/lite/delegates/gpu/delegate.cc:955: undefined reference to `tflite::delegates::utils::WriteSyncAttrs(tflite::delegates::utils::SyncAttributes const&, TfLiteAttributeMap*)'
tensorflow/lite/delegates/gpu/delegate.cc:957: undefined reference to `tflite::delegates::utils::WriteSyncAttrs(tflite::delegates::utils::SyncAttributes const&, TfLiteAttributeMap*)'
CMakeFiles/tensorflow-lite.dir/delegates/gpu/delegate.cc.o: In function `tflite::gpu::(anonymous namespace)::DelegateAsyncKernel::RegisterBufferImpl(TfLiteContext*, TfLiteIoType, TfLiteBackendBuffer const*, TfLiteAttributeMap const*, int)':
tensorflow/lite/delegates/gpu/delegate.cc:1049: undefined reference to `TfLiteAttributeMapIsBufferAttributeMap'
tensorflow/lite/delegates/gpu/delegate.cc:1052: undefined reference to `tflite::delegates::utils::ReadBufferAttrs(TfLiteAttributeMap const*)'
tensorflow/lite/delegates/gpu/delegate.cc:1078: undefined reference to `TfLiteBackendBufferGetPtr'
CMakeFiles/tensorflow-lite.dir/delegates/gpu/delegate.cc.o: In function `tflite::gpu::(anonymous namespace)::DelegateAsyncKernel::Acquire(AHardwareBuffer*)':
tensorflow/lite/delegates/gpu/delegate.cc:796: undefined reference to `AHardwareBuffer_acquire'
CMakeFiles/tensorflow-lite.dir/delegates/gpu/delegate.cc.o: In function `tflite::gpu::(anonymous namespace)::DelegateAsyncKernel::Describe(std::__ndk1::unique_ptr<AHardwareBuffer, void (*)(AHardwareBuffer*)> const&)':
tensorflow/lite/delegates/gpu/delegate.cc:812: undefined reference to `AHardwareBuffer_describe'
CMakeFiles/tensorflow-lite.dir/delegates/gpu/delegate.cc.o: In function `operator()':
tensorflow/lite/delegates/gpu/delegate.cc:804: undefined reference to `AHardwareBuffer_release'
CMakeFiles/tensorflow-lite.dir/delegates/gpu/delegate.cc.o: In function `tflite::gpu::(anonymous namespace)::DelegateAsyncKernel::SetAttributesImpl(TfLiteContext*, TfLiteNode*, int, TfLiteAttributeMap const*)':
tensorflow/lite/delegates/gpu/delegate.cc:977: undefined reference to `TfLiteAttributeMapIsSyncAttributeMap'
tensorflow/lite/delegates/gpu/delegate.cc:982: undefined reference to `tflite::delegates::utils::ReadSyncAttrs(TfLiteAttributeMap const*)'
CMakeFiles/tensorflow-lite.dir/delegates/gpu/delegate.cc.o: In function `tflite::gpu::(anonymous namespace)::DelegateAsyncKernel::EvalImpl(TfLiteContext*, TfLiteNode*, TfLiteExecutionTask*)':
tensorflow/lite/delegates/gpu/delegate.cc:1237: undefined reference to `TfLiteExecutionTaskGetSyncByIndex'
tensorflow/lite/delegates/gpu/delegate.cc:1239: undefined reference to `TfLiteSynchronizationGetPtr'
tensorflow/lite/delegates/gpu/delegate.cc:1251: undefined reference to `tflite::delegates::utils::WaitForAllFds(absl::lts_20220623::Span<int const>)'
tensorflow/lite/delegates/gpu/delegate.cc:1291: undefined reference to `tflite::delegates::utils::ConvertToTfLiteStatus(absl::lts_20220623::Status)'
tensorflow/lite/delegates/gpu/delegate.cc:1309: undefined reference to `TfLiteExecutionTaskGetSyncByIndex'
tensorflow/lite/delegates/gpu/delegate.cc:1311: undefined reference to `TfLiteSynchronizationSetPtr'
CMakeFiles/tensorflow-lite.dir/delegates/gpu/delegate.cc.o: In function `operator()':
tensorflow/lite/delegates/gpu/delegate.cc:1266: undefined reference to `TfLiteExecutionTaskGetBufferByIndex'
tensorflow/lite/delegates/gpu/delegate.cc:1272: undefined reference to `tflite::delegates::utils::ConvertToTfLiteStatus(absl::lts_20220623::Status)'
tensorflow/lite/delegates/gpu/delegate.cc:1168: undefined reference to `AHardwareBuffer_lock'
tensorflow/lite/delegates/gpu/delegate.cc:1195: undefined reference to `AHardwareBuffer_unlock'
CMakeFiles/tensorflow-lite.dir/minimal_logging_android.cc.o: In function `tflite::logging_internal::MinimalLogger::LogFormatted(tflite::LogSeverity, char const*, std::__va_list)':
tensorflow/lite/minimal_logging_android.cc:49: undefined reference to `__android_log_vprint'
```

### Analyze
When I analyze it, I find error(`"undefined reference to __android_log_vprint" and "multiple definition of tflite::logging_internal::MinimalLogger::LogFormatted"`) is still here.

By the way, the error about `undefined reference to tensorflow::profiler::ScopedMemoryDebugAnnotation::ThreadMemoryDebugAnnotation()` is not exsit now, I'm sure the error 
is not introduced by this pr.

The other error about 'delegate.cc', I think it's receptive, because it's changing now(lastest change: 268a6a577df35f2782cceecb0658ef31d25a993c).

### Summary
The pr is still effective for  "undefined reference to __android_log_vprint" and "multiple definition of tflite::logging_internal::MinimalLogger::LogFormatted".

@JunyoungLim That's all notes about it, thanks.
@gbaned I don't have updates for this pr, thanks.

**Comment by gbaned** [comment]
Hi @JunyoungLim Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @JunyoungLim Can you please review this PR ? Thank you!

**Comment by terryheo** [comment]
Thanks for the contribution. I've merged a similar patch. Plz let me know if you still have an issue.
