### ISSUE TITLE
Tensorflow crashes on build on Ubuntu 16.04 when building for skylake (avx512)

### ISSUE THREAD

**Issue by Randl** [tensorflow/tensorflow#10220]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: building from source
- **TensorFlow version (use command below)**:  5ae244e
- **Bazel version (if compiling from source)**:  0.4.5
- **CUDA/cuDNN version**: CUDA 8.0.61, cudnn 6.0.21 (tried also 5.1)
- **GPU model and memory**: 2x Tesla P100-PCIE-12GB
- **Exact command to reproduce**: building
- **Additional information**: Intel(R) Xeon(R) CPU E7-4860 v2 @ 2.60GHz, gcc version 5.4.1 20170519 (Ubuntu 5.4.1-11ubuntu2~16.04)

### Describe the problem
On the regular rebuild of Tensorflow, the build crashes with bunch of `error: argument of type "const void *" is incompatible with parameter of type "const something *"`

### Source code / logs
Crash log:
```
INFO: From Compiling tensorflow/core/kernels/scatter_functor_gpu.cu.cc:
/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9218): error: argument of type "const void *" is incompatible with parameter of type "const float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9229): error: argument of type "const void *" is incompatible with parameter of type "const float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9242): error: argument of type "const void *" is incompatible with parameter of type "const double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9253): error: argument of type "const void *" is incompatible with parameter of type "const double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9266): error: argument of type "const void *" is incompatible with parameter of type "const float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9277): error: argument of type "const void *" is incompatible with parameter of type "const float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9290): error: argument of type "const void *" is incompatible with parameter of type "const double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9301): error: argument of type "const void *" is incompatible with parameter of type "const double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9314): error: argument of type "const void *" is incompatible with parameter of type "const int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9325): error: argument of type "const void *" is incompatible with parameter of type "const int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9338): error: argument of type "const void *" is incompatible with parameter of type "const long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9350): error: argument of type "const void *" is incompatible with parameter of type "const long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9363): error: argument of type "const void *" is incompatible with parameter of type "const int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9374): error: argument of type "const void *" is incompatible with parameter of type "const int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9387): error: argument of type "const void *" is incompatible with parameter of type "const long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9399): error: argument of type "const void *" is incompatible with parameter of type "const long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9408): error: argument of type "void *" is incompatible with parameter of type "float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9417): error: argument of type "void *" is incompatible with parameter of type "float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9426): error: argument of type "void *" is incompatible with parameter of type "double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9435): error: argument of type "void *" is incompatible with parameter of type "double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9443): error: argument of type "void *" is incompatible with parameter of type "float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9452): error: argument of type "void *" is incompatible with parameter of type "float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9461): error: argument of type "void *" is incompatible with parameter of type "double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9470): error: argument of type "void *" is incompatible with parameter of type "double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9479): error: argument of type "void *" is incompatible with parameter of type "int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9488): error: argument of type "void *" is incompatible with parameter of type "int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9497): error: argument of type "void *" is incompatible with parameter of type "long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9506): error: argument of type "void *" is incompatible with parameter of type "long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9515): error: argument of type "void *" is incompatible with parameter of type "int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9524): error: argument of type "void *" is incompatible with parameter of type "int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9533): error: argument of type "void *" is incompatible with parameter of type "long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9542): error: argument of type "void *" is incompatible with parameter of type "long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512pfintrin.h(54): error: argument of type "const void *" is incompatible with parameter of type "const long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512pfintrin.h(62): error: argument of type "const void *" is incompatible with parameter of type "const int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512pfintrin.h(70): error: argument of type "const void *" is incompatible with parameter of type "const long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512pfintrin.h(78): error: argument of type "const void *" is incompatible with parameter of type "const int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512pfintrin.h(86): error: argument of type "void *" is incompatible with parameter of type "const long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512pfintrin.h(95): error: argument of type "void *" is incompatible with parameter of type "const int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512pfintrin.h(104): error: argument of type "void *" is incompatible with parameter of type "const long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512pfintrin.h(112): error: argument of type "void *" is incompatible with parameter of type "const int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512pfintrin.h(120): error: argument of type "void *" is incompatible with parameter of type "const long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512pfintrin.h(129): error: argument of type "void *" is incompatible with parameter of type "const int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512pfintrin.h(138): error: argument of type "void *" is incompatible with parameter of type "const long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512pfintrin.h(146): error: argument of type "void *" is incompatible with parameter of type "const int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10223): error: argument of type "const void *" is incompatible with parameter of type "const float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10235): error: argument of type "const void *" is incompatible with parameter of type "const float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10247): error: argument of type "const void *" is incompatible with parameter of type "const double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10259): error: argument of type "const void *" is incompatible with parameter of type "const double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10271): error: argument of type "const void *" is incompatible with parameter of type "const float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10283): error: argument of type "const void *" is incompatible with parameter of type "const float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10295): error: argument of type "const void *" is incompatible with parameter of type "const double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10307): error: argument of type "const void *" is incompatible with parameter of type "const double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10319): error: argument of type "const void *" is incompatible with parameter of type "const int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10331): error: argument of type "const void *" is incompatible with parameter of type "const int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10343): error: argument of type "const void *" is incompatible with parameter of type "const long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10355): error: argument of type "const void *" is incompatible with parameter of type "const long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10367): error: argument of type "const void *" is incompatible with parameter of type "const int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10379): error: argument of type "const void *" is incompatible with parameter of type "const int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10391): error: argument of type "const void *" is incompatible with parameter of type "const long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10403): error: argument of type "const void *" is incompatible with parameter of type "const long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10413): error: argument of type "void *" is incompatible with parameter of type "float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10424): error: argument of type "void *" is incompatible with parameter of type "float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10433): error: argument of type "void *" is incompatible with parameter of type "float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10444): error: argument of type "void *" is incompatible with parameter of type "float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10453): error: argument of type "void *" is incompatible with parameter of type "double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10464): error: argument of type "void *" is incompatible with parameter of type "double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10473): error: argument of type "void *" is incompatible with parameter of type "double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10484): error: argument of type "void *" is incompatible with parameter of type "double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10493): error: argument of type "void *" is incompatible with parameter of type "float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10504): error: argument of type "void *" is incompatible with parameter of type "float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10513): error: argument of type "void *" is incompatible with parameter of type "float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10524): error: argument of type "void *" is incompatible with parameter of type "float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10533): error: argument of type "void *" is incompatible with parameter of type "double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10544): error: argument of type "void *" is incompatible with parameter of type "double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10553): error: argument of type "void *" is incompatible with parameter of type "double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10564): error: argument of type "void *" is incompatible with parameter of type "double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10573): error: argument of type "void *" is incompatible with parameter of type "int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10584): error: argument of type "void *" is incompatible with parameter of type "int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10593): error: argument of type "void *" is incompatible with parameter of type "int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10604): error: argument of type "void *" is incompatible with parameter of type "int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10613): error: argument of type "void *" is incompatible with parameter of type "long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10624): error: argument of type "void *" is incompatible with parameter of type "long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10633): error: argument of type "void *" is incompatible with parameter of type "long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10644): error: argument of type "void *" is incompatible with parameter of type "long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10653): error: argument of type "void *" is incompatible with parameter of type "int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10664): error: argument of type "void *" is incompatible with parameter of type "int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10673): error: argument of type "void *" is incompatible with parameter of type "int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10684): error: argument of type "void *" is incompatible with parameter of type "int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10693): error: argument of type "void *" is incompatible with parameter of type "long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10704): error: argument of type "void *" is incompatible with parameter of type "long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10713): error: argument of type "void *" is incompatible with parameter of type "long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10724): error: argument of type "void *" is incompatible with parameter of type "long long *"

92 errors detected in the compilation of "/tmp/tmpxft_00008f12_00000000-7_scatter_functor_gpu.cu.cpp1.ii".
ERROR: /scratch/chaimb/tensorflow/tensorflow/core/kernels/BUILD:1140:1: output 'tensorflow/core/kernels/_objs/scatter_functor_gpu/tensorflow/core/kernels/scatter_functor_gpu.cu.pic.o' was not created.
ERROR: /scratch/chaimb/tensorflow/tensorflow/core/kernels/BUILD:1140:1: not all outputs were created or valid.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 147.888s, Critical Path: 69.54s
```

I've tried disabling most of the options (MKL, architecture optimizations, computability) but the crash happens even with full-default (except CUDA and XLA) configuration.

**Comment by csoehnel** [comment]
I had a similar problem and my workaround was to downgrade to gcc/g++ 4.8, see this page for [how2](https://ask.fedoraproject.org/en/question/95016/fedora-24-how-do-i-install-and-change-the-default-gcc-compiler-version/).

ubuntu 17.04 64 bit, CUDA 8.0.61, cudnn 6.0.21, tensorflow tag v1.1.0, bazel configured to use -msse4.1, -msse4.2, -mavx, -mavx2, -mfma, cuda compute capabilities 6.1, gpu is nvidia geforce gtx 1080 ti, cpu is amd ryzen 1700x

**Comment by gunan** [comment]
From what I can see, you are trying to build with avx 512 instruction set?
I am not sure if we tested with avx512 yet. Could you try rebuilding without avx512?

**Comment by Randl** [comment]
@gunan No, I'm not, at least not explicitly. The processor is Ivy Bridge, and I was building with default settings.

**Comment by gunan** [comment]
@Randl Your build failure seems to be in `avx512fintrin.h`. 
I think it is included through `immintrin.h`, but looking at the files, most of the header should be skipped.
What is the exact build command you are running before you saw this failure?

**Comment by Randl** [comment]
@gunan That's what I run (different options set were tried):
```

chaimb@hpc1:/scratch/chaimb/tensorflow$ ./configure
Please specify the location of python. [Default is /usr/bin/python]: /usr/bin/python3
Found possible Python library paths:
  /usr/lib/python3/dist-packages
  /usr/local/lib/python3.5/dist-packages
  /usr/local/lib/python2.7/site-packages
Please input the desired Python library path to use.  Default is [/usr/lib/python3/dist-packages]

Using python library path: /usr/lib/python3/dist-packages
Do you wish to build TensorFlow with MKL support? [y/N] y
MKL support will be enabled for TensorFlow
Do you wish to download MKL LIB from the web? [Y/n] y
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]:
Do you wish to use jemalloc as the malloc implementation? [Y/n]
jemalloc enabled
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N]
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N]
No Hadoop File System support will be enabled for TensorFlow
Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N] y
XLA JIT support will be enabled for TensorFlow
Do you wish to build TensorFlow with VERBS support? [y/N]
No VERBS support will be enabled for TensorFlow
Do you wish to build TensorFlow with OpenCL support? [y/N]
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N] y
CUDA support will be enabled for TensorFlow
Do you want to use clang as CUDA compiler? [y/N]
nvcc will be used as CUDA compiler
Please specify the CUDA SDK version you want to use, e.g. 7.0. [Leave empty to use system default]:
Please specify the location where CUDA  toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]:
Please specify the cuDNN version you want to use. [Leave empty to use system default]:
Please specify the location where cuDNN  library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: "6.0"
Do you wish to build TensorFlow with MPI support? [y/N]
MPI support will not be enabled for TensorFlow
WARNING: Output base '/home/chaimb/.cache/bazel/_bazel_chaimb/7e5d2835edc3e2079ed27c4c385315e6' is on NFS. This may lead to surprising failures and undetermined behavior.
.....................................
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
Configuration finished
chaimb@hpc1:/scratch/chaimb/tensorflow$ bazel build --verbose_failures --jobs 96 --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
```

@csoehnel  Confirmed, using `/usr/bin/gcc-4.9` is a valid workaround.

**Comment by gunan** [comment]
Looks like you enabled MKL support. I think that is why the build is failing.

**Comment by Randl** [comment]
@gunan disabling it gives same result

**Comment by byronyi** [comment]
Same thing happens using ``gcc-5.4.1`` on Debian 9.  This is my build command:

```
bazel build -c opt --config=cuda --copt=-msse4.1 --copt=-msse4.2 --copt=-mavx --copt=-mavx2 --copt=-mfma //tensorflow/tools/pip_package:build_pip_package
```

**Comment by byronyi** [comment]
I believe #9296 is the same issue, and switching back to `gcc-4.9` seems to solve the problem.

[Here](http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#system-requirements) seems to be a combination supported by Nvidia.

```
Distribution	Kernel	GCC	GLIBC
Ubuntu 16.04	4.4.0	5.3.1	2.23
```

**Comment by gdahlm** [comment]
Switching back to `gcc-4.9` only fixes the issue because it doesn't have the intrinsic for avx512 yet.

Something in the GPU code is including `immintrin.h` which now includes the new avx512 instructions for hardware enablement. 

gcc-5  5.4.1-11ubuntu2  is the version on my machine, and it doesn't matter if I add/remove MKL, XLA or any other options it will compile fine.  And yes I can compile with gcc-4.9 but it doesn't even natively support skylake let alone AVX512 instructions.

My C++ is rusty and bazel is new to me, but it seems like some work on includes in  `tensorflow/core/platform/platform.h` 

Nvidia technically supports GCC 5.4 which would should this problem, and it is a problem with llvm 3.8.1 too as it also includes these intrinsic types with an include of immintrin.h.

I wish I wasn't so rusty or I would help to get access to these instructions but from looking around the  real options seem to be either pull out the inclusion of the gcc intrinsics from cudacc code or adding explicit casts for the new types.

**Comment by marijnfs** [comment]
I have this problem as well, made any progress?

**Comment by tfboyd** [comment]
Stress before saying something that is likely not useful.  I do not recall building from head in the past few weeks.  Sharing what I have done recently, which I doubt is helpful but it is the only info I have that has a remote chance of being helpful.  

I built 1.3.0rc2  multiple times on a stock 16.04 setup (on AWS) with AVX2,  CUDA 8 and cuDNN 6 .  I did not use the CUDA 8 Patch 2 (which I can say performs poorly for inception3 and Resnet and possibly others on K80s even more so as I scaled from 1 to 8 GPUs. No idea why (maybe I did something wrong) and I did not try other GPUs for 1 GPU is seemed the same).

The version of Bazel I use is 0.5.1.  I do not think that matters just sharing exactly what I was using.  I would NOT use 0.5.3 although I think the problem was fixed.

I normally build with this command and the only option I add during the `./configure` that is not default is CUDA.
`bazel build -c opt --copt=-march="haswell" --config=cuda //tensorflow/tools/pip_package:build_pip_package`

**Comment by jplu** [comment]
I have the exact same issue on Debian. Any update on this issue?

**Comment by tfboyd** [comment]
@jplu 
I do not know if someone will look at this, but with out knowing the hash you are building from, gcc, debian version and bazel version as well as the full build command and ./configure options it is looking for a needle in a haystack.  I do custom TensorFlow builds weekly on 16.04 and I 100% understand there are many combinations of builds that could trigger a problem that I would never see.  If I know exactly what you are doing I can give it a try in my environment or possibly someone else can take a look.  Our build environment here is Ubuntu 14.04 and I mostly build ion 16.04 and sometimes amazon linux I do not remember the version.

**Comment by jplu** [comment]
Sorry. Here is my setup:

### System information
- **OS Platform and Distribution**: Debian Buster
- **TensorFlow installed from**: source
- **TensorFlow version**: commit https://github.com/tensorflow/tensorflow/commit/12a628a623a5dae81b8fc699792eaf414e6ace41
- **Python version**: 3.5.4
- **Bazel version**: 0.5.4
- **CUDA/cuDNN version**: CUDA 8/CuDNN 6
- **GPU model and memory**: 2xTesla K80 with 12GB each
- **CPU model**: Intel Xeon E5-2683 v4
- **Exact command to reproduce**:

```
bazel build -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both --copt=-msse4.2 --copt=-msse4.1 --config=mkl --config=cuda --verbose_failures -k //tensorflow/tools/pip_package:build_pip_package
```

Or

```
bazel build -c opt --copt=-march=native --copt=-mfpmath=both --config=mkl --config=cuda --verbose_failures -k //tensorflow/tools/pip_package:build_pip_package
```
### Describe the problem
I'm trying to compile a Tensorflow package specifically optimized for my machine. When I run the compilation with one of the command lines described above, I get some compilation errors. Doesn't matter if I let GCC deciding which optimization to make or if I force them. The kind of errors are always the same as described in the first post and finish by:

```
92 errors detected in the compilation of "/tmp/tmpxft_00007482_00000000-7_zero_initializer_op_gpu.cu.cpp1.ii".
ERROR: /opt/tensorflow/tensorflow/contrib/framework/BUILD:88:1: output 'tensorflow/contrib/framework/_objs/python/ops/_variable_ops_gpu/tensorflow/contrib/framework/kernels/zero_initializer_op_gpu.cu.pic.o' was not created
ERROR: /opt/tensorflow/tensorflow/contrib/framework/BUILD:88:1: not all outputs were created or valid
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 331.599s, Critical Path: 63.79s
FAILED: Build did NOT complete successfully
```

Am I using a wrong command line or is it a bug in the compilation process?

Thanks in advance for any help.

**Comment by juanecito** [comment]
Hello, I have found the same error when I add <random> include in a .cu file (compiled by nvcc CUDA 8). This file random (/usr/include/c++/5/random in GNU/Debian 9) include opt_random.h -> x86intrin.h -> immintrin.h -> avx512vlintrin.h. I don't have this problem when I compile with debug flags in nvcc (-g -O0). Finally I solved this problem changing include dependences in my application.

**Comment by jplu** [comment]
Sorry @juanecito but I don't get your post. I don't see the relation between the compilation of Tensorflow and the compilation of your application. Can you give more details please.

**Comment by fischman** [comment]
I think the problem here is that gcc-5.5 shipped with avx512\*intrin.h headers that switched to using `void*` and `const void*` (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=76731) but without switching the builtins to do the same.  This is why 5.4 works but 5.5 breaks.  The tensorflow r1.4 build at least can be unbroken for 5.5 by locally rolling back the above change with e.g.:
```shell
for f in avx512fintrin.h avx512pfintrin.h avx512vlintrin.h; do
   curl -H "User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36" -o $f "https://gcc.gnu.org/viewcvs/gcc/branches/gcc-5-branch/gcc/config/i386/${f}?view=co&revision=245536&content-type=text%2Fplain&pathrev=245536"
done && mv avx512*intrin.h  /usr/lib/gcc/x86_64-linux-gnu/5/include/
```
This is a terrible idea (who knows what else it's rolling back? are you really cherrypicking 3 random files out of an entire release? and so on) and nobody should do it, of course.

But maybe, if you're trying to build tensorflow for GPU (so require nvcc, so require GCC < 6) inside an ubuntu:17.10 docker image (so don't have an apt-get'able gcc-5.4 option), this might be useful.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by daisylab** [comment]
I met same situation described above. It happened when my system (slackware linux) updated gcc from 5.3 to 5.5, as @fischman said.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tfboyd: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tfboyd: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tfboyd: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tfboyd: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by amq** [comment]
Similar problem here. It's odd that it happened with GCC 5.4

```
C++ compilation of rule '@fft2d//:fft2d' failed (Exit 1)
external/fft2d/fft/fftsg.c: In function 'cftf162':
external/fft2d/fft/fftsg.c:3028:1: error: insn does not satisfy its constraints:
 }
 ^
(insn 486 485 130 2 (set (reg:DF 50 xmm13 [orig:218 D.7773 ] [218])
        (plus:DF (reg:DF 50 xmm13 [orig:218 D.7773 ] [218])
            (reg:DF 56 xmm19 [orig:218 D.7773 ] [218]))) external/fft2d/fft/fftsg.c:2933 796 {*fop
_df_comm_mixed}
     (nil))
external/fft2d/fft/fftsg.c:3028:1: internal compiler error: in extract_constrain_insn, at recog.c:
2246
```

### System information
- **OS Platform and Distribution**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: https://github.com/tensorflow/tensorflow/commit/92e6c3e4f5c1cabfda1e61547a6a1b268ef95fa5
- **Python version**: 3.5.2
- **Bazel version (if compiling from source)**: 0.11.0
- **GCC/Compiler version (if compiling from source)**: 5.4.0
- **CUDA/cuDNN version**: CUDA 9.1. cuDNN 7.1
- **GPU model and memory**: NVIDIA K80
- **CPU model**: 2.0 GHz Intel Xeon (Skylake) on GCP
- **Exact command to reproduce**:
```
bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
```

Optimizations set with `./configure`:
```
-mavx -mavx2 -mavx512f -mfma -mfpmath=both -msse4.2 -Ofast
```

**Comment by amq** [comment]
Interestingly though, compiling without `-mavx512f` works just fine.

**Comment by hamiGH** [comment]
i have same error with System information:
    OS Platform and Distribution: Ubuntu 16.04
    TensorFlow installed from: source
    TensorFlow version: 1.8
    Python version: 3.6.4
    GCC version: 5.4.1
    CUDA/cuDNN version: CUDA 9.1/CuDNN 7.1.3
    GPU model and memory: 1080 Ti

I solved this problem by switching to **gcc-4.9**:
_**$ sudo apt-get install gcc-4.9 g++-4.9
$ sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 50 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9**_ 
Now you can switch to gcc-4.9 by using:
_**$ sudo update-alternatives --config gcc**_

then run the following command:
_**$ bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package**_

**Comment by MCMcCallum** [comment]
Same issue as hamiGH above

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tfboyd: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tfboyd: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by szm2015** [comment]
Hi, has this issue been resolved? I am using Ubuntu 18.04 and the lowest version of gcc I could get there is 5.5 which gives the errors as asked in the question. On this same system, I had Ubuntu 16.04 with gcc 5.4 and TensorFlow compiled without a problem. I am really stuck and would appreciate any help! I have tested with TF version 1.9.0 and 1.8.0 both give the same error (the Cuda version I'm using is 9.0).

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tfboyd: It has been 16 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tfboyd: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tfboyd: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tfboyd: It has been 60 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tfboyd: It has been 75 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by sclarkson** [comment]
I believe this was an nvcc issue.

I can now compile 1.11.0-rc1 with CUDA 10.0 and gcc 5.5. (But CUDA 10.0 also supports gcc 7.3, so it's kind of moot)

**Comment by hannahzhangapp** [comment]
If I compile with Debug, the problem is gone.
 xxx/xxx/build$ cmake -DCMAKE_BUILD_TYPE=Debug  /path/to/source/code

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tfboyd: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tfboyd: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tfboyd: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by wt-huang** [comment]
Closing as this is resolved

**Comment by rahul003** [comment]
@wt-huang Could you share the fix that resolves this issue? I see the same error even with gcc-4.9. Compiling with debug isn't practical for performance reasons.
