### ISSUE TITLE
gcc: error: unrecognized command line option '-fcolor-diagnostics'

### ISSUE THREAD

**Issue by ScottHCL** [tensorflow/tensorflow#1192]
I had counted such problem when compiling tensorflow from source in mac system:
gcc: error: unrecognized command line option '-fcolor-diagnostics'
gcc: error: unrecognized command line option '-Wthread-safety'
gcc: error: unrecognized command line option '-Wself-assign'
ERROR: /Users/clhuang/Downloads/tensorflow/google/protobuf/BUILD:29:1: C++ compilation of rule '//google/protobuf:protobuf_lite' failed: osx_gcc_wrapper.sh failed: error executing command external/bazel_tools/tools/cpp/osx_gcc_wrapper.sh '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 -DNDEBUG ... (remaining 37 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException

And my gcc version is 4.9,when I just run the command /my/path/gcc-4.9 -Wthread-safety example.cc,
it also shows gcc: error: unrecognized command line option '-Wthread-safety'.could anyone give me some advise ,thanks in advance.

**Comment by petewarden** [comment]
We generally use the default of clang for OS X compilation, which explains your error. When I run `gcc --version` I get `Apple LLVM version 7.0.2 (clang-700.1.81)`. You should try switching to clang instead of gcc, since that's the supported approach.

**Comment by ScottHCL** [comment]
yeh,after I switch to clang there is no such problems above.When I run gcc -v I get Apple LLVM version 6.0 (clang-600.0.57) .While some others occour:

tensorflow/core/kernels/fifo_queue.cc:164:46: error: expected body of lambda expression
          [callback, this](Attempt* attempt) EXCLUSIVE_LOCKS_REQUIRED(mu_) {
                                             ^
./tensorflow/core/platform/default/thread_annotations.h:89:3: note: expanded from macro 'EXCLUSIVE_LOCKS_REQUIRED'
  THREAD_ANNOTATION_ATTRIBUTE__(exclusive_locks_required(__VA_ARGS__))
  ^
./tensorflow/core/platform/default/thread_annotations.h:42:42: note: expanded from macro 'THREAD_ANNOTATION_ATTRIBUTE__'
#define THREAD_ANNOTATION_ATTRIBUTE__(x) __attribute__((x))
                                         ^
tensorflow/core/kernels/fifo_queue.cc:248:46: error: expected body of lambda expression
          [callback, this](Attempt* attempt) EXCLUSIVE_LOCKS_REQUIRED(mu_) {
                                             ^
./tensorflow/core/platform/default/thread_annotations.h:89:3: note: expanded from macro 'EXCLUSIVE_LOCKS_REQUIRED'
  THREAD_ANNOTATION_ATTRIBUTE__(exclusive_locks_required(__VA_ARGS__))
  ^
./tensorflow/core/platform/default/thread_annotations.h:42:42: note: expanded from macro 'THREAD_ANNOTATION_ATTRIBUTE__'
#define THREAD_ANNOTATION_ATTRIBUTE__(x) __attribute__((x))
                                         ^
8 warnings and 4 errors generated.
ERROR: /Users/clhuang/Downloads/tensorflow/tensorflow/core/BUILD:359:1: C++ compilation of rule '//tensorflow/core:kernel_lib' failed: osx_gcc_wrapper.sh failed: error executing command external/bazel_tools/tools/cpp/osx_gcc_wrapper.sh '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 -DNDEBUG ... (remaining 77 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.

I should update xcode and get the same gcc version  as you?I have searched from internet and I find someone with linux occoured the same problem when using gcc 4.7,but after update to 4.9 everything is fine.Is the matter suportting c++11?And I think my version can also support c++ compiling.Thx very much!

**Comment by izeye** [comment]
@ScottHCL I've got the same errors with you. I fixed it by upgrading `gcc` via upgrading Xcode.

See http://izeye.blogspot.kr/2016/03/error-expected-body-of-lambda-expression.html

**Comment by vincentvanhoucke** [comment]
Assuming issue has been addressed. Please reopen if not.
