### ISSUE TITLE
'tensorflow._api.v2.compat.v2.compat' has no attribute 'v1'

### ISSUE THREAD

**Issue by rambail** [tensorflow/tensorflow#38122]
I am working on Ubuntu 19.10.
I have installed tensorflow version '2.0.0-beta1'
I have installed tensorflow-dataset version '2.1.0'
When I try to load mnist dataset, I get the following error:
 >>> dataset =tfds.load(name="mnist")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/umesh/.local/lib/python3.7/site-packages/tensorflow_datasets/core/api_utils.py", line 52, in disallow_positional_args_dec
    return fn(*args, **kwargs)
  File "/home/umesh/.local/lib/python3.7/site-packages/tensorflow_datasets/core/registered.py", line 318, in load
    ds = dbuilder.as_dataset(**as_dataset_kwargs)
  File "/home/umesh/.local/lib/python3.7/site-packages/tensorflow_datasets/core/api_utils.py", line 52, in disallow_positional_args_dec
    return fn(*args, **kwargs)
  File "/home/umesh/.local/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py", line 482, in as_dataset
    datasets = utils.map_nested(build_single_dataset, split, map_tuple=True)
  File "/home/umesh/.local/lib/python3.7/site-packages/tensorflow_datasets/core/utils/py_utils.py", line 145, in map_nested
    for k, v in data_struct.items()
  File "/home/umesh/.local/lib/python3.7/site-packages/tensorflow_datasets/core/utils/py_utils.py", line 145, in <dictcomp>
    for k, v in data_struct.items()
  File "/home/umesh/.local/lib/python3.7/site-packages/tensorflow_datasets/core/utils/py_utils.py", line 159, in map_nested
    return function(data_struct)
  File "/home/umesh/.local/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py", line 541, in _build_single_dataset
    read_config=read_config,
  File "/home/umesh/.local/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py", line 949, in _as_dataset
    shuffle_files=shuffle_files,
  File "/home/umesh/.local/lib/python3.7/site-packages/tensorflow_datasets/core/tfrecords_reader.py", line 290, in read
    return tf.nest.map_structure(_read_instruction_to_ds, instructions)
  File "/home/umesh/.local/lib/python3.7/site-packages/tensorflow/python/util/nest.py", line 515, in map_structure
    structure[0], [func(*x) for x in entries],
  File "/home/umesh/.local/lib/python3.7/site-packages/tensorflow/python/util/nest.py", line 515, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "/home/umesh/.local/lib/python3.7/site-packages/tensorflow_datasets/core/tfrecords_reader.py", line 287, in _read_instruction_to_ds
    num_examples=file_instructions.num_examples,
  File "/home/umesh/.local/lib/python3.7/site-packages/tensorflow_datasets/core/tfrecords_reader.py", line 322, in read_files
    num_examples=num_examples,
  File "/home/umesh/.local/lib/python3.7/site-packages/tensorflow_datasets/core/tfrecords_reader.py", line 201, in _read_files
    instruction_ds = tf.compat.v1.data.Dataset.from_tensor_slices(tensor_inputs)
AttributeError: module 'tensorflow._api.v2.compat.v2.compat' has no attribute 'v1'

**Comment by gadagashwini** [comment]
@rambail, Can you share the standalone code to replicate the issue and also try with the latest stable Tensorflow 2.1 version. Thanks!

**Comment by rambail** [comment]
`import tensorflow as tf
import tensorflow_datasets as tfds

print("\u2022 Using TensorFlow Version:", tf.__version__)
print("\u2022 Using TensorFlow Dataset Version:", tfds.__version__)`

• Using TensorFlow Version: 2.0.0-beta0
• Using TensorFlow Dataset Version: 2.1.0

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-6940136dcaab> in <module>
----> 1 dataset =tfds.load(name="mnist")

/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/core/api_utils.py in disallow_positional_args_dec(fn, instance, args, kwargs)
     50     _check_no_positional(fn, args, ismethod, allowed=allowed)
     51     _check_required(fn, kwargs)
---> 52     return fn(*args, **kwargs)
     53 
     54   return disallow_positional_args_dec(wrapped)  # pylint: disable=no-value-for-parameter

/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/core/registered.py in load(name, split, data_dir, batch_size, in_memory, shuffle_files, download, as_supervised, decoders, read_config, with_info, builder_kwargs, download_and_prepare_kwargs, as_dataset_kwargs, try_gcs)
    316   as_dataset_kwargs.setdefault("read_config", read_config)
    317 
--> 318   ds = dbuilder.as_dataset(**as_dataset_kwargs)
    319   if with_info:
    320     return ds, dbuilder.info

/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/core/api_utils.py in disallow_positional_args_dec(fn, instance, args, kwargs)
     50     _check_no_positional(fn, args, ismethod, allowed=allowed)
     51     _check_required(fn, kwargs)
---> 52     return fn(*args, **kwargs)
     53 
     54   return disallow_positional_args_dec(wrapped)  # pylint: disable=no-value-for-parameter

/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/core/dataset_builder.py in as_dataset(self, split, batch_size, shuffle_files, decoders, read_config, as_supervised, in_memory)
    480         in_memory=in_memory,
    481     )
--> 482     datasets = utils.map_nested(build_single_dataset, split, map_tuple=True)
    483     return datasets
    484 

/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/core/utils/py_utils.py in map_nested(function, data_struct, dict_only, map_tuple)
    143     return {
    144         k: map_nested(function, v, dict_only, map_tuple)
--> 145         for k, v in data_struct.items()
    146     }
    147   elif not dict_only:

/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/core/utils/py_utils.py in <dictcomp>(.0)
    143     return {
    144         k: map_nested(function, v, dict_only, map_tuple)
--> 145         for k, v in data_struct.items()
    146     }
    147   elif not dict_only:

/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/core/utils/py_utils.py in map_nested(function, data_struct, dict_only, map_tuple)
    157         return tuple(mapped)
    158   # Singleton
--> 159   return function(data_struct)
    160 
    161 

/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/core/dataset_builder.py in _build_single_dataset(self, split, shuffle_files, batch_size, decoders, read_config, as_supervised, in_memory)
    539           shuffle_files=shuffle_files,
    540           decoders=decoders,
--> 541           read_config=read_config,
    542       )
    543       # Auto-cache small datasets which are small enough to fit in memory.

/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/core/dataset_builder.py in _as_dataset(self, split, decoders, read_config, shuffle_files)
    947           split_infos=self.info.splits.values(),
    948           read_config=read_config,
--> 949           shuffle_files=shuffle_files,
    950       )
    951     else:

/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/core/tfrecords_reader.py in read(self, name, instructions, split_infos, read_config, shuffle_files)
    288       )
    289 
--> 290     return tf.nest.map_structure(_read_instruction_to_ds, instructions)
    291 
    292   def read_files(

~/.local/lib/python3.7/site-packages/tensorflow/python/util/nest.py in map_structure(func, *structure, **kwargs)
    513 
    514   return pack_sequence_as(
--> 515       structure[0], [func(*x) for x in entries],
    516       expand_composites=expand_composites)
    517 

~/.local/lib/python3.7/site-packages/tensorflow/python/util/nest.py in <listcomp>(.0)
    513 
    514   return pack_sequence_as(
--> 515       structure[0], [func(*x) for x in entries],
    516       expand_composites=expand_composites)
    517 

/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/core/tfrecords_reader.py in _read_instruction_to_ds(instruction)
    285           read_config=read_config,
    286           shuffle_files=shuffle_files,
--> 287           num_examples=file_instructions.num_examples,
    288       )
    289 

/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/core/tfrecords_reader.py in read_files(self, files, read_config, shuffle_files, num_examples)
    320         parse_fn=self._parser.parse_example,
    321         shuffle_files=shuffle_files,
--> 322         num_examples=num_examples,
    323     )
    324     return dataset

/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/core/tfrecords_reader.py in _read_files(files, parse_fn, read_config, shuffle_files, num_examples)
    199   block_length = read_config.interleave_block_length
    200 
--> 201   instruction_ds = tf.compat.v1.data.Dataset.from_tensor_slices(tensor_inputs)
    202 
    203   # If shuffle is True, we shuffle the instructions/shards

AttributeError: module 'tensorflow._api.v2.compat.v2.compat' has no attribute 'v1'
`

**Comment by rambail** [comment]
<import tensorflow as tf
import tensorflow_datasets as tfds

print("\u2022 Using TensorFlow Version:", tf.__version__)
print("\u2022 Using TensorFlow Dataset Version:", tfds.__version__)>

**• Using TensorFlow Version: 2.0.0-beta0
• Using TensorFlow Dataset Version: 2.1.0**

'---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-6940136dcaab> in <module>
----> 1 dataset =tfds.load(name="mnist")

/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/core/api_utils.py in disallow_positional_args_dec(fn, instance, args, kwargs)
     50     _check_no_positional(fn, args, ismethod, allowed=allowed)
     51     _check_required(fn, kwargs)
---> 52     return fn(*args, **kwargs)
     53 
     54   return disallow_positional_args_dec(wrapped)  # pylint: disable=no-value-for-parameter

/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/core/registered.py in load(name, split, data_dir, batch_size, in_memory, shuffle_files, download, as_supervised, decoders, read_config, with_info, builder_kwargs, download_and_prepare_kwargs, as_dataset_kwargs, try_gcs)
    316   as_dataset_kwargs.setdefault("read_config", read_config)
    317 
--> 318   ds = dbuilder.as_dataset(**as_dataset_kwargs)
    319   if with_info:
    320     return ds, dbuilder.info

/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/core/api_utils.py in disallow_positional_args_dec(fn, instance, args, kwargs)
     50     _check_no_positional(fn, args, ismethod, allowed=allowed)
     51     _check_required(fn, kwargs)
---> 52     return fn(*args, **kwargs)
     53 
     54   return disallow_positional_args_dec(wrapped)  # pylint: disable=no-value-for-parameter

/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/core/dataset_builder.py in as_dataset(self, split, batch_size, shuffle_files, decoders, read_config, as_supervised, in_memory)
    480         in_memory=in_memory,
    481     )
--> 482     datasets = utils.map_nested(build_single_dataset, split, map_tuple=True)
    483     return datasets
    484 

/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/core/utils/py_utils.py in map_nested(function, data_struct, dict_only, map_tuple)
    143     return {
    144         k: map_nested(function, v, dict_only, map_tuple)
--> 145         for k, v in data_struct.items()
    146     }
    147   elif not dict_only:

/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/core/utils/py_utils.py in <dictcomp>(.0)
    143     return {
    144         k: map_nested(function, v, dict_only, map_tuple)
--> 145         for k, v in data_struct.items()
    146     }
    147   elif not dict_only:

/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/core/utils/py_utils.py in map_nested(function, data_struct, dict_only, map_tuple)
    157         return tuple(mapped)
    158   # Singleton
--> 159   return function(data_struct)
    160 
    161 

/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/core/dataset_builder.py in _build_single_dataset(self, split, shuffle_files, batch_size, decoders, read_config, as_supervised, in_memory)
    539           shuffle_files=shuffle_files,
    540           decoders=decoders,
--> 541           read_config=read_config,
    542       )
    543       # Auto-cache small datasets which are small enough to fit in memory.

/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/core/dataset_builder.py in _as_dataset(self, split, decoders, read_config, shuffle_files)
    947           split_infos=self.info.splits.values(),
    948           read_config=read_config,
--> 949           shuffle_files=shuffle_files,
    950       )
    951     else:

/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/core/tfrecords_reader.py in read(self, name, instructions, split_infos, read_config, shuffle_files)
    288       )
    289 
--> 290     return tf.nest.map_structure(_read_instruction_to_ds, instructions)
    291 
    292   def read_files(

~/.local/lib/python3.7/site-packages/tensorflow/python/util/nest.py in map_structure(func, *structure, **kwargs)
    513 
    514   return pack_sequence_as(
--> 515       structure[0], [func(*x) for x in entries],
    516       expand_composites=expand_composites)
    517 

~/.local/lib/python3.7/site-packages/tensorflow/python/util/nest.py in <listcomp>(.0)
    513 
    514   return pack_sequence_as(
--> 515       structure[0], [func(*x) for x in entries],
    516       expand_composites=expand_composites)
    517 

/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/core/tfrecords_reader.py in _read_instruction_to_ds(instruction)
    285           read_config=read_config,
    286           shuffle_files=shuffle_files,
--> 287           num_examples=file_instructions.num_examples,
    288       )
    289 

/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/core/tfrecords_reader.py in read_files(self, files, read_config, shuffle_files, num_examples)
    320         parse_fn=self._parser.parse_example,
    321         shuffle_files=shuffle_files,
--> 322         num_examples=num_examples,
    323     )
    324     return dataset

/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/core/tfrecords_reader.py in _read_files(files, parse_fn, read_config, shuffle_files, num_examples)
    199   block_length = read_config.interleave_block_length
    200 
--> 201   instruction_ds = tf.compat.v1.data.Dataset.from_tensor_slices(tensor_inputs)
    202 
    203   # If shuffle is True, we shuffle the instructions/shards

AttributeError: module 'tensorflow._api.v2.compat.v2.compat' has no attribute 'v1'
'

I have the latest stable version of the TensorFlow dataset i.e 2.1. I tried changing the tensorflow version to 2.0.0a0 and 2.0.0b1, but getting the same result.
​

**Comment by rambail** [comment]
In colab too when I code:
```
!pip install --upgrade tensorflow==2.0.0b0
```
I get the same error. But when I change the version to 
```
!pip install --upgrade tensorflow==2.0.0
```
`It works!!

But unfortunately, Ubuntu 19.10 has only upto 2.0.0b1 in its pip3 repository, And I am not equal to the task of compiling from source.

**Comment by mihaimaruseac** [comment]
`pip install --upgrade pip` and then when you do `pip install` you should see the other versions

**Comment by rambail** [comment]
I was not using pip but pip3 as I didn't want python2.7 files in my system.  ```pip install --upgrade pip``` and ```pip install --upgrade tensorflow``` installs tensorflow.2.1 in the site-packages folder of python2.7. But ```pip3 install --upgrade pip``` and followed by ```pip3 install --upgrade tensorflow``` upgrades the package in python3.7 folders. Thanks for the hint

**Comment by mihaimaruseac** [comment]
You can always create a virtualenv where python3 tools are default `virtualenv <dir> -p python3` and then `<dir>/bin/activate`.

Or you can do `python3 -m pip install` instead of `pip install`.

Both are alternatives to using `pip3`.

But more important, now that the issue seems solved, can we close it?
