### ISSUE TITLE
 AttributeError: 'tuple' object has no attribute 'shape' error while using Google colab

### ISSUE THREAD

**Issue by mkpisk** [tensorflow/tensorflow#38503]
Based on research and understanding of the issue its looks to me as a bug as i tried different things suggested by other users for similar issues. but it doesn't resolve.

------------------------

### System information
Using google colab
access to the notebook: https://colab.research.google.com/drive/1sDg-5lDnUKYLQUbSkBiZsYK4ZBof3ZQZ#scrollTo=mopYecQ-eIJk&uniqifier=1

You can obtain the TensorFlow version with:
Using goolge colab

### Describe the problem
I am able to run the same code on a normal jupyter notebook on my uni server. but it throws me an error while trying to run it on google colab.
I checked if there are any references to keras instaed of tensoflw.keras and corrected them. I also converted the datagenerator output to a tuple instead of list

### Source code / logs
WARNING:tensorflow:From <ipython-input-10-1ae13c8462de>:9: Model.fit_generator (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
Please use Model.fit, which supports generators.
Epoch 1/5
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-1ae13c8462de> in <module>()
      7                   epochs=nb_epoch,
      8                   steps_per_epoch=nb_train_samples,
----> 9                   validation_data=gen_valid)

12 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
    966           except Exception as e:  # pylint:disable=broad-except
    967             if hasattr(e, "ag_error_metadata"):
--> 968               raise e.ag_error_metadata.to_exception(e)
    969             else:
    970               raise

AttributeError: in user code:

    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:505 train_function  *
        outputs = self.distribute_strategy.run(
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:951 run  **
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:2290 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:2649 _call_for_each_replica
        return fn(*args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:477 train_step  **
        self.compiled_metrics.update_state(y, y_pred, sample_weight)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/compile_utils.py:386 update_state
        self._build(y_pred, y_true)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/compile_utils.py:317 _build
        self._metrics, y_true, y_pred)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/util/nest.py:1118 map_structure_up_to
        **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/util/nest.py:1214 map_structure_with_tuple_paths_up_to
        *flat_value_lists)]
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/util/nest.py:1213 <listcomp>
        results = [func(*args, **kwargs) for args in zip(flat_path_list,
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/util/nest.py:1116 <lambda>
        lambda _, *values: func(*values),  # Discards the path arg.
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/compile_utils.py:416 _get_metric_objects
        return [self._get_metric_object(m, y_t, y_p) for m in metrics]
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/compile_utils.py:416 <listcomp>
        return [self._get_metric_object(m, y_t, y_p) for m in metrics]
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/compile_utils.py:437 _get_metric_object
        y_t_rank = len(y_t.shape.as_list())

    AttributeError: 'tuple' object has no attribute 'shape'

**Comment by khimraj** [comment]
@mkpisk, can you please share full code to reproduce issue as i have not access to your colab file.

**Comment by mkpisk** [comment]
# -*- coding: utf-8 -*-
"""Lab2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sDg-5lDnUKYLQUbSkBiZsYK4ZBof3ZQZ
"""

USE_G_COLAB = False
if USE_G_COLAB:
    from google.colab import drive
    drive.mount('/content/drive')

if USE_G_COLAB:
    root_dir = "/content/drive/My Drive/CNN/"
    root_dir_to_test = "/content/drive/My\ Drive/CNN/"
    !ls $root_dir_to_test

from google.colab import drive
drive.mount('/content/drive')

# Import necessary packages for loading the dataset

import numpy as np  # Package for matrix operations, handling data
np.random.seed(2020)
import os
# import cv2
import matplotlib.pyplot as plt  # Package for plotting
#from PIL import Image
# from tensorflow.keras.preprocessing.image import img_to_array
# from tensorflow.keras.preprocessing.image import load_img
# from tensorflow.keras.utils import to_categorical
import tensorflow as tf
from tensorflow.python.keras.utils.data_utils import Sequence


class DataGenerator(tf.keras.utils.Sequence):

    def __init__(self,
                 data_path,
                 inputs,
                 outputs,
                 batch_size=32):

        self.data_path = data_path
        self.inputs = inputs
        self.outputs = outputs
        self.batch_size = batch_size

        if data_path is None:
            raise ValueError('The data path is not defined.')

        if not os.path.isdir(data_path):
            raise ValueError('The data path is incorrectly defined.')

        self.file_idx = 0
        self.file_list = [self.data_path + '/' + s
                          for s in os.listdir(self.data_path)]

        self.on_epoch_end()
        with np.load(self.file_list[0]) as npzfile:
            self.out_dims = []
            self.in_dims = []
            self.n_channels = 1

            for i in range(len(self.inputs)):
                im = npzfile[self.inputs[i]]
                self.in_dims.append((self.batch_size,
                                     *np.shape(im),
                                     self.n_channels))

            for i in range(len(self.outputs)):
                im = npzfile[self.outputs[i]]
                self.out_dims.append((self.batch_size,
                                      *np.shape(im),
                                      self.n_channels))

    def __len__(self):
        'Denotes the number of batches per epoch'
        return int(np.floor((len(self.file_list)) / self.batch_size))

    def __getitem__(self, index):
        'Generate one batch of data'
        # Generate indexes of the batch
        indexes = self.indexes[index * self.batch_size:(index + 1) *
                               self.batch_size]

        # Find list of IDs
        list_IDs_temp = [self.file_list[k] for k in indexes]

        # Generate data
        i, o = self.__data_generation(list_IDs_temp)

        return i, o

    def on_epoch_end(self):
        'Updates indexes after each epoch'
        self.indexes = np.arange(len(self.file_list))
        np.random.shuffle(self.indexes)

    #@threadsafe_generator
    def __data_generation(self, temp_list):
        'Generates data containing batch_size samples'
        # X : (n_samples, *dim, n_channels)
        # Initialization
        inputs = []
        outputs = []

        for i in range(len(self.inputs)):
            inputs.append(np.empty(self.in_dims[i]).astype(np.float32))

        for i in range(self.outputs.__len__()):
            outputs.append(np.empty(self.out_dims[i]).astype(np.float32))

        for i, ID in enumerate(temp_list):
            with np.load(ID) as npzfile:

                for idx in range(len(self.inputs)):
                    x = npzfile[self.inputs[idx]].astype(np.float32)
                    x = x[..., np.newaxis]
                    inputs[idx][i, ...] = x

                for idx in range(len(self.outputs)):
                    x = npzfile[self.outputs[idx]].astype(np.float32)
                    x = x[..., np.newaxis]
                    outputs[idx][i, ...] = x

        return tuple(inputs), tuple(outputs)


gen_dir = "/content/drive/My Drive/CNN/data/"
# gen_dir = "/import/software/3ra023vt20/brats/data/"

# Available arrays in data: 'flair', 't1', 't2', 't1ce', 'mask'
# See the lab instructions for more info about the arrays
input_arrays = ['flair', 't1', 't1ce']
output_arrays = ['mask']
batch_size = 48
gen_train = DataGenerator(data_path=gen_dir + 'training',
                          inputs=input_arrays,
                          outputs=output_arrays,
                          batch_size=batch_size)

# Look at some sample images
img_in, img_out = gen_train[np.random.randint(0, len(gen_train))]
for inp in range(np.shape(img_in)[0]):
    plt.figure(figsize=(12, 5))
    for i in range(4):
        plt.subplot(1, 4, i + 1)
        plt.imshow(img_in[inp][i, :, :, 0])
        plt.title('Image size: ' + str(np.shape(img_in[inp][i, :, :, 0])))
        plt.tight_layout()
    plt.suptitle('Input for array: ' + gen_train.inputs[inp])
    plt.show()

plt.figure(figsize=(12, 4))
for outp in range(np.shape(img_out)[0]):
    for i in range(4):
        plt.subplot(1, 4, i + 1)
        plt.imshow(img_out[outp][i, :, :, 0])
        plt.title('Image size: ' + str(np.shape(img_out[outp][i, :, :, 0])))
        plt.tight_layout()

    plt.suptitle('Output for array: ' + gen_train.outputs[outp])
# import cv2
import matplotlib.pyplot as plt  # Package for plotting
#from PIL import Image
# from tensorflow.keras.preprocessing.image import img_to_array
# from tensorflow.keras.preprocessing.image import load_img
# from tensorflow.keras.utils import to_categorical    plt.show()

gen_dir = "/content/drive/My Drive/CNN/data/"
input_arrays = ['flair']
output_arrays = ['mask']
batch_size = 48
gen_train = DataGenerator(data_path=gen_dir + 'training',
                          inputs=input_arrays,
                          outputs=output_arrays,
                          batch_size=batch_size)

gen_valid = DataGenerator(data_path=gen_dir + 'validating',
                          inputs=input_arrays,
                          outputs=output_arrays,
                          batch_size=batch_size)

print("#ofFileSamples:", len(gen_train))
print("#ofFileSamples:", len(gen_valid))

import cv2
import matplotlib.pyplot as plt  # Package for plotting
from PIL import Image
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.preprocessing.image import load_img
from tensorflow.keras.utils import to_categorical

import tensorflow.keras as keras

IMG_WIDTH = 128
IMG_HEIGHT = 128
IMG_CHANNELS = 1

#Building the CNN model

inputs = keras.layers.Input((IMG_WIDTH,IMG_HEIGHT,IMG_CHANNELS))

s = keras.layers.Lambda(lambda x:x / 255)(inputs)
c1 = keras.layers.Conv2D(16, (3,3), activation='relu', kernel_initializer='he_normal', padding='same')(s)
c1 = keras.layers.Dropout(0.1)(c1)
c1 = keras.layers.Conv2D(16, (3,3), activation='relu', kernel_initializer='he_normal', padding='same')(c1)
p1 = keras.layers.MaxPool2D((2,2))(c1)

c2 = keras.layers.Conv2D(32, (3,3), activation='relu', kernel_initializer='he_normal', padding='same')(p1)
c2 = keras.layers.Dropout(0.1)(c2)
c2 = keras.layers.Conv2D(32, (3,3), activation='relu', kernel_initializer='he_normal', padding='same')(c2)
p2 = keras.layers.MaxPool2D((2,2))(c2)

c3 = keras.layers.Conv2D(64, (3,3), activation='relu', kernel_initializer='he_normal', padding='same')(p2)
c3 = keras.layers.Dropout(0.1)(c3)
c3 = keras.layers.Conv2D(64, (3,3), activation='relu', kernel_initializer='he_normal', padding='same')(c3)
p3 = keras.layers.MaxPool2D((2,2))(c3)

c4 = keras.layers.Conv2D(128, (3,3), activation='relu', kernel_initializer='he_normal', padding='same')(p3)
c4 = keras.layers.Dropout(0.1)(c4)
c4 = keras.layers.Conv2D(128, (3,3), activation='relu', kernel_initializer='he_normal', padding='same')(c4)
p4 = keras.layers.MaxPool2D((2,2))(c4)

c5 = keras.layers.Conv2D(128, (3,3), activation='relu', kernel_initializer='he_normal', padding='same')(p4)
c5 = keras.layers.Dropout(0.1)(c5)
c5 = keras.layers.Conv2D(128, (3,3), activation='relu', kernel_initializer='he_normal', padding='same')(c5)

u6 = keras.layers.Conv2DTranspose(128, (2,2), strides=(2,2), padding='same')(c5)
u6 = keras.layers.concatenate([u6, c4])
c6 = keras.layers.Conv2D(128, (3,3), activation='relu', kernel_initializer='he_normal', padding='same')(u6)
c6 = keras.layers.Dropout(0.2)(c6)
c6 = keras.layers.Conv2D(128, (3,3), activation='relu', kernel_initializer='he_normal', padding='same')(c6)

u7 = keras.layers.Conv2DTranspose(64, (2,2), strides=(2,2), padding='same')(c6)
u7 = keras.layers.concatenate([u7, c3])
c7 = keras.layers.Conv2D(64, (3,3), activation='relu', kernel_initializer='he_normal', padding='same')(u7)
c7 = keras.layers.Dropout(0.2)(c7)
c7 = keras.layers.Conv2D(64, (3,3), activation='relu', kernel_initializer='he_normal', padding='same')(c7)

u8 = keras.layers.Conv2DTranspose(32, (2,2), strides=(2,2), padding='same')(c7)
u8 = keras.layers.concatenate([u8, c2])
c8 = keras.layers.Conv2D(32, (3,3), activation='relu', kernel_initializer='he_normal', padding='same')(u8)
c8 = keras.layers.Dropout(0.2)(c8)
c8 = keras.layers.Conv2D(32, (3,3), activation='relu', kernel_initializer='he_normal', padding='same')(c8)

u9 = keras.layers.Conv2DTranspose(16, (2,2), strides=(2,2), padding='same')(c8)
u9 = keras.layers.concatenate([u9, c1])
c9 = keras.layers.Conv2D(16, (3,3), activation='relu', kernel_initializer='he_normal', padding='same')(u9)
c9 = keras.layers.Dropout(0.2)(c9)
c9 = keras.layers.Conv2D(16, (3,3), activation='relu', kernel_initializer='he_normal', padding='same')(c9)

outputs = keras.layers.Conv2D(1, (1,1), activation='sigmoid')(c9)

model = keras.Model(inputs=[inputs], outputs=[outputs])
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.summary()

#checkpointer = tf.keras.callbacks.ModelCheckpoint('Model_Img_seg.h5', verbose=1, save_best_only=True)

callbacks = [keras.callbacks.EarlyStopping(patience=2, monitor='val_loss'),
            keras.callbacks.TensorBoard(log_dir='logs')]

nb_train_samples = len(gen_train)
nb_validation_samples = len(gen_train)
nb_validation_samples

nb_epoch = 5
nb_train_samples = len(gen_train)
nb_validation_samples = len(gen_train)


results=model.fit_generator(generator=gen_train,
                  epochs=nb_epoch,
                  steps_per_epoch=nb_train_samples,
                  validation_data=gen_valid)

idx = random.randint(0, len(X_train))

preds_train = model.predict(X_train[:int(X_train.shape)])

**Comment by ravikyram** [comment]
@mkpisk 

I am not able to access colab link you have provided. Request you to share the colab link or standalone code with proper indentation to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by ravikyram** [comment]
@mkpisk 

Any update on this issue please. Thanks!

**Comment by Akshaykoushik06** [comment]
I am also facing the same issue. I am using autokeras in Google Colab.

This is the error:
AttributeError: 'tuple' object has no attribute 'shape'

@mkpisk was your issue resolved? If yes, how?

**Comment by mkpisk** [comment]
no. its not resolved yet.

**Comment by mkpisk** [comment]
I believe it is version issue on google colab. Same code worked for me on other notebook formats. Kaggle and Zure.

**Comment by Akshaykoushik06** [comment]
Thanks for the fast reply.

My issue is still not resolved as :
   1. In Azure Notebook, the version of Tensorflow being installed is 2.0.0-beta1 which is not needed.
   
   2. Kaggle Notebook installs the version 2.1.0 for Tensorflow and gives the following error when I 
   try to install autokeras:
   ```
   ERROR: Could not find a version that satisfies the requirement autokeras (from versions: none)
   ERROR: No matching distribution found for autokeras
   ```

**Comment by anugrahasinha** [comment]
I dont know whether this would really solve the problem and/or if you are using something specific to `eager` execution, but the following things helped me solve the issue.

Before you build you model (preferably when you are import(ing) libraries)
```
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
```

also when you are compiling your model, use the following argument
`experimental_run_tf_function=False`

**Comment by ks93** [comment]
Same issue here. Google Colab. Tried default 2.x and 2.2.0rc2

**Comment by vizsatiz** [comment]
I faced the same issue, was fixed by switching to tensorflow=2.1.0 and keras=2.3.1, also it did work fine with tensorflow=2.0.0

Issue is in tensorflow=2.0.0.

**Comment by ks93** [comment]
> I faced the same issue, was fixed by switching to `tensorflow=2.1.0` and `keras=2.3.1`, also it did work fine with `tensorflow=2.0.0`
> 
> Issue is in `tensorflow=2.2.0`

`!pip install tensorflow=2.1.0` fixed it for me on colab! Thanks.

**Comment by TeaTimeChimp** [comment]
Changing from metrics=['accuracy'] to metrics=[tf.keras.metrics.Accuracy()] fixed it for me.

**Comment by luchspeter** [comment]
> I dont know whether this would really solve the problem and/or if you are using something specific to `eager` execution, but the following things helped me solve the issue.
> 
> Before you build you model (preferably when you are import(ing) libraries)
> 
> ```
> import tensorflow as tf
> tf.compat.v1.disable_eager_execution()
> ```
> 
> also when you are compiling your model, use the following argument
> `experimental_run_tf_function=False`

That solved the issue for me! Thank you.

**Comment by leimao** [comment]
This bug exists in TensorFlow 2.2.0. Is there any fix going on if the user does not want to switch back to TensorFlow 2.1.0?

**Comment by luchspeter** [comment]
I am running on 2.2.0 and the fix with disabling the eager execution worked without switching back to 2.1.0

**Comment by ZJaume** [comment]
I found the same error on my Keras code when I switched to a generator `keras.util.Sequence`. Disabling eager execution solves the problem but the network trains too slow with the generator. Data is pre-loaded on ram and every `__getitem__` step only grabs a slice from the numpy dataset, so I assume the generator is not the bottleneck.

**Comment by jorgeveamurguia** [comment]
With version transformers==4.10.3 it works but transformers==4.12.5 does not work
