### PR TITLE
Fix linking errors of lmdb on Windows

### PR DESCRIPTION
**Pull request by meteorcloudy**
http://ci.tensorflow.org/job/tf-master-win-bzl/1041/console
The error was introduced in https://github.com/tensorflow/tensorflow/commit/e6f58186363279496c46563e6f065ce7ea16c501

```
23:09:48 liblmdb.a(mdb.o) : error LNK2019: unresolved external symbol __imp_InitializeSecurityDescriptor referenced in function mdb_env_setup_locks
23:09:48 liblmdb.a(mdb.o) : error LNK2019: unresolved external symbol __imp_SetSecurityDescriptorDacl referenced in function mdb_env_setup_locks
```
@gunan

### CODE REVIEW

File: third_party/lmdb.BUILD [hunk 1]
```diff
@@ -18,8 +18,20 @@ cc_library(
...
+        ":windows": ["-Wl,advapi32.lib"], # InitializeSecurityDescriptor, SetSecurityDescriptorDacl
+        ":windows_msvc": ["-Wl,advapi32.lib"],
+        "//conditions:default": ["-lpthread"],
+    }),
     visibility = ["//visibility:public"],
 )
+
+config_setting(
+    name = "windows",
+    values = {"cpu": "x64_windows"},
```
Comment (meteorcloudy) [inline third_party/lmdb.BUILD]: I'm soon going to send a change to make TF build on Windows without `--cpu=x64_windows_msvc`. So here also adding config_setting for cpu value x64_windows to be compatible.

**Comment by meteorcloudy** [comment]
http://ci.tensorflow.org/job/tensorflow-pr-win-bazel/22/console
The build succeeded, but has some test failures.

**Review by gunan — APPROVED** [review]

**Comment by gunan** [comment]
Ill take care of the test failures
