### ISSUE TITLE
'cannot import name string_int_label_map_pb2' 

### ISSUE THREAD

**Issue by yash486gadhavi** [tensorflow/tensorflow#17922]
Hello there;

I am using tensorflow 1.6 cpu in windows 8.1 anaconda jupyter notebook

I want to use tensorflow object detection api and I follow the installation instruction provided in the  models tensorflow github repository

according to that instructions 

1. First I installed tensorflow and the other dependencies 
2. I did the protobuf compilation
3. The pythonpath is also being set
and the setup.py file is being run
but when I try to use the object_detection_tutorial.ipynb it still shows the "import error cannot import name string_int_label_map_pb2" 
please help me if I am doing something wrong, I know this issue is old but still, it causes a lot of problems. help me 

Thanking you in anticipation

**Comment by jatinmandav** [comment]
Hey, I myself am getting error with 
`py train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v1_pets.config`
command in cmd. I am using windows 10 OS. I am getting the error

`ImportError: cannot import name 'preprocessor_pb2'`
Even though I have compiled all the proto files and preprocessor_pb2.py file exists in object-detection/protos directory.
Let me too know if you find any solution to it!

**Comment by yash486gadhavi** [comment]
I have checked the proto files  from the "models/research/object_detefction/proto " , and  i found that there is proto file named 'string_int_label_map.proto',  I changed the import 'string_int_label_map_pb2'in label.map.util to 'string_int_label_map' but it still shows the error.

**Comment by yash486gadhavi** [comment]
Hey i found the solution  i follow the steps given in this[https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10](url)

**Comment by drpngx** [comment]
Nice to see you figured it out!

**Comment by huseynlilkin** [comment]
I am getting same error and ling provided by @yash486gadhavi  is broken

**Comment by yash486gadhavi** [comment]
https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10

This is the link i checked it again

**Comment by aruna09** [comment]
> Hey I found the solution I follow the steps given in this link in case you are not able to understand I will explain it to you
> [https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10](link)

I am facing this error when I am running the jupyter notebook:


ImportError                               Traceback (most recent call last)
<ipython-input-3-aa270cd948af> in <module>()
----> 1 from utils import label_map_util
      2 
      3 from utils import visualization_utils as vis_util

/home/icts/models/research/object_detection/utils/label_map_util.py in <module>()
     19 import tensorflow as tf
     20 from google.protobuf import text_format
---> 21 from object_detection.protos import string_int_label_map_pb2
     22 
     23 

ImportError: cannot import name string_int_label_map_pb2

When I run:
protoc object_detection/protos/*.proto --python_out=
I am getting the following error:

object_detection/protos/ssd.proto:104:3: Expected "required", "optional", or "repeated".
object_detection/protos/ssd.proto:104:12: Expected field name.
object_detection/protos/model.proto: Import "object_detection/protos/ssd.proto" was not found or had errors.
object_detection/protos/model.proto:12:5: "Ssd" is not defined.

I am working on machine with ubuntu version 16.04

**Comment by pranka02** [comment]
> 
> 
> I am getting same error and ling provided by @yash486gadhavi is broken

If your issue is the following error

> ImportError                               Traceback (most recent call last)
> <ipython-input-3-aa270cd948af> in <module>()
> ----> 1 from utils import label_map_util
>       2 
>       3 from utils import visualization_utils as vis_util
> 
> ~\models\research\object_detection\utils\label_map_util.py in <module>()
>      19 import tensorflow as tf
>      20 from google.protobuf import text_format
> ---> 21 from object_detection.protos import string_int_label_map_pb2
>      22 
>      23 
> 
> ImportError: cannot import name 'string_int_label_map_pb2'   

and if your protoc file is in the models/research/  folder, 

1. go to the utils folder in the object_detection folder
2. open the label_map_util.py file in an editor and edit the line 'from object_detection.protos import string_int_label_map_pb2' to 'from protos import string_int_label_map_pb2

**Comment by pranka02** [comment]
> 
> 
> > Hey I found the solution I follow the steps given in this link in case you are not able to understand I will explain it to you
> > [https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10](link)
> 
> I am facing this error when I am running the jupyter notebook:
> 
> ImportError Traceback (most recent call last)
> in ()
> ----> 1 from utils import label_map_util
> 2
> 3 from utils import visualization_utils as vis_util
> 
> /home/icts/models/research/object_detection/utils/label_map_util.py in ()
> 19 import tensorflow as tf
> 20 from google.protobuf import text_format
> ---> 21 from object_detection.protos import string_int_label_map_pb2
> 22
> 23
> 
> ImportError: cannot import name string_int_label_map_pb2
> 
> When I run:
> protoc object_detection/protos/*.proto --python_out=
> I am getting the following error:
> 
> object_detection/protos/ssd.proto:104:3: Expected "required", "optional", or "repeated".
> object_detection/protos/ssd.proto:104:12: Expected field name.
> object_detection/protos/model.proto: Import "object_detection/protos/ssd.proto" was not found or had errors.
> object_detection/protos/model.proto:12:5: "Ssd" is not defined.
> 
> I am working on machine with ubuntu version 16.04

The new protoc version does not allow you to do **protoc object_detection/protos/*.proto --python_out=**. I hope you understand that *.proto means do the above command for all files with extension .proto in the object_detection/protos/ folder. In the new version, you will need to compile each file in protos folder individually as, for example,  **protoc object_detection/protos/anchor_generator.proto --python_out=**.

As for the import error, I have mentioned a few steps above, that you can follow to solve it.

**Comment by Mehran970** [comment]
Simply, go to **protos** dirctory in object detection folder in your pc and put this python file into the it:
[https://github.com/datitran/object_detector_app/blob/master/object_detection/protos/string_int_label_map_pb2.py](url)

**Comment by contractorwolf** [comment]
this is the fix in @pranka02's solution above:

> and if your protoc file is in the models/research/ folder,

go to the utils folder in the object_detection folder
open the label_map_util.py file in an editor and edit the line 'from object_detection.protos import string_int_label_map_pb2' to 'from protos import string_int_label_map_pb2
