### PR TITLE
Adapt commit 5467ee9 from XLA to TensorFlow

### LINKED ISSUE #90562: gpu_prim.h: no instance of overloaded function "cub::ThreadLoadVolatilePointer" matches the specified type
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

r2.19

### Custom code

No

### OS platform and distribution

Alma Linux 9.5

### Mobile device

_No response_

### Python version

3.12

### Bazel version

6.5.0

### GCC/compiler version

_No response_

### CUDA/cuDNN version

12.8.0

### GPU model and memory

_No response_

### Current behavior?

Compiling against CUDA 12.8.0 gives an error:

```
./tensorflow/core/kernels/gpu_prim.h(48): error: no instance of overloaded function "cub::ThreadLoadVolatilePointer" matches the specified type
                            Eigen::half ThreadLoadVolatilePointer<Eigen::half>(
```

[Commit 5467ee9](https://github.com/tensorflow/tensorflow/commit/5467ee993e1d3e4709c1e99f3a15a978325ae536) for XLA needs to be adapted and applied to tensorflow/core/kernels/gpu_prim.h.

### Standalone code to reproduce the issue

```shell
`env HERMETIC_CUDA_VERSION=1.8.0 ./configure`
`bazel build`
```

### Relevant log output

```shell
./tensorflow/core/kernels/gpu_prim.h(48): error: no instance of overloaded function "cub::ThreadLoadVolatilePointer" matches the specified type
                            Eigen::half ThreadLoadVolatilePointer<Eigen::half>(
```

### PR DESCRIPTION
**Pull request by plopresti**
TensorFlow has a build failure with newer CUDA. The problem has been fixed in XLA (openxla/xla#16095 and TensorFlow commit https://github.com/tensorflow/tensorflow/commit/5467ee993e1d3e4709c1e99f3a15a978325ae536). This change adapts that commit to tensorflow/core/kernels/gpu_prim.h.

Fixes #90562.

### CODE REVIEW

**Comment by plopresti** [comment]
I would also recommend this as a cherry-pick for r2.19, which does not currently work with CUDA 12.8.0.

**Review by mihaimaruseac — APPROVED** [review]

**Comment by keerthanakadiri** [comment]
Hi @plopresti, Can you please resolve the conflicts. Many Thanks!

**Comment by keerthanakadiri** [comment]
I'm going  ahead and closing this PR, because there seems to be no response for a long time. If you're still interested in pursuing this , please feel free to reopen!
