### ISSUE TITLE
Module 'gast' has no attribute 'Num'

### ISSUE THREAD

**Issue by mgreenbe** [tensorflow/tensorflow#32319]
I got an error message including a request that I report a bug.

Here's the code:
```python
import numpy as np
import tensorflow as tf
import platform

print()
print(f"PLATFORM:\n---------\n{platform.platform()}")
print("\nTENSORFLOW:\n----------")
for a in tf.version.__all__:
    print(f"{a}: {getattr(tf.version, a)}")

print(f"\nNUMPY:\n-----\n{np.version.version}")

print(f"\nPYTHON:\n-------\n{sys.version}\n")

np.random.seed(0)
tf.random.set_seed(0)


model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(1, activation="linear")
])
model.compile(optimizer="sgd", loss="mse")

x = np.random.uniform(size=(1,1))
y = np.random.uniform(size=(1,))
model.fit(x, y, epochs=1)
```

And here's the output, including system info, module versions, etc.
```

PLATFORM:
---------
Darwin-18.7.0-x86_64-i386-64bit

TENSORFLOW:
----------
COMPILER_VERSION: 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)
GIT_VERSION: v2.0.0-beta1-5101-gc75bb66a99
GRAPH_DEF_VERSION: 119
GRAPH_DEF_VERSION_MIN_CONSUMER: 0
GRAPH_DEF_VERSION_MIN_PRODUCER: 0
VERSION: 2.0.0-rc0

NUMPY:
-----
1.17.1

PYTHON:
-------
3.7.4 (default, Jul  9 2019, 18:13:23) 
[Clang 10.0.1 (clang-1001.0.46.4)]

Train on 1 samples
WARNING:tensorflow:Entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x1492748c0> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'
WARNING: Entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x1492748c0> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'
1/1 [==============================] - 0s 157ms/sample - loss: 1.2336

<tensorflow.python.keras.callbacks.History at 0x14927b5d0>
```

**Comment by tocosastalo** [comment]
Hello,

3 hours ago  was `gast` library updated from 0.2.2 to 0.3.0 and `Num` constant was removed (check commit https://github.com/serge-sans-paille/gast/commit/231ee7a1b599b68354acbbf8b8d19acc8a2ce60a#diff-88b99bb28683bd5b7e3a204826ead112R99).  

TF requires `gast>=0.2.0`, so updated version of `gast` module is automatically installed on your machine and that's probably why it fails with error `AttributeError: module 'gast' has no attribute 'Num'`.

This happens on the line 236 in `tensorflow/python/autograph/pyct/qual_names.py` (https://github.com/tensorflow/tensorflow/blob/r1.14/tensorflow/python/autograph/pyct/qual_names.py#L236):
```
if isinstance(s.value, gast.Num):
```

**Comment by jlebar** [comment]
@mgreenbe thank you for filing the bug, and @tocosastalo thanks for the info.

Workaround that worked for me: `$ pip3 install 'gast==0.2.2'`.

**Comment by ai-nikolai** [comment]
@jlebar & @tocosastalo & @mgreenbe thank you:
> @mgreenbe thank you for filing the bug, and @tocosastalo thanks for the info.
> 
> Workaround that worked for me: `$ pip3 install 'gast==0.2.2'`.

This worked for me too: $ `pip3 install gast==0.2.2.`

**Comment by FeynmanDNA** [comment]
I encountered the same warning with tensorflow-gpu2.0beta1, and the above fix works for me too:
```
$ pip install gast==0.2.2
Collecting gast==0.2.2
Installing collected packages: gast
  Found existing installation: gast 0.3.1
    Uninstalling gast-0.3.1:
      Successfully uninstalled gast-0.3.1
Successfully installed gast-0.2.2
```

**Comment by mgreenbe** [comment]
Using the older version of `gast` worked for me too. I'll leave it to @jlebar or someone else on the tensorflow team to close this issue at their discretion, presumably once `tensorflow` and `gast=0.3.x` are interacting nicely.

**Comment by mihaimaruseac** [comment]
#32332 fixes this for 1.15, there's a similar PR for 2.0 and a commit on master. Adding @goldiegadde as she is fixing this

**Comment by wchargin** [comment]
I don’t understand what the status of this is. The [corresponding commit
on master][1] hasn’t fixed this in nightlies:

```
$ cat test.py
import tensorflow as tf

print(tf.__version__)

@tf.function
def foo():
  return 1

foo()
$ AUTOGRAPH_VERBOSITY=10 python test.py
2.0.0-dev20190910
WARNING:tensorflow:Entity <function foo at 0x7f71ac1990d0> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: Bad argument number for Name: 3, expecting 4
```

Running `pip install gast==0.2.2` fixes the above issue.

I’m not sure what those changes in `pip_new.sh` do, but is there a plan
to update the [actual Pip dependencies][2] so that people who simply run
`pip install tf-nightly-2.0-preview` get a working install?

[1]: https://github.com/tensorflow/tensorflow/commit/cc2e03a1384f80035f9fbe1949dd46004a62b41f
[2]:
https://github.com/tensorflow/tensorflow/blob/a25803e6ee8f90e3604651ad813e64fccd1e408e/tensorflow/tools/pip_package/setup.py#L57

**Comment by mihaimaruseac** [comment]
Classical error of having same dependency specified in two places. I'll send a fix, sorry for this

**Comment by wchargin** [comment]
thanks! :-)

**Comment by mihaimaruseac** [comment]
Should be fixed by c72125bd59858ec82a9238b232bbd77c45889c5a, #32390 and #32391 (the last two need merging before fixing on corresponding branches)

**Comment by mihaimaruseac** [comment]
Should be fixed now, keeping issue open until verified

**Comment by wchargin** [comment]
Confirmed fixed for me on `tf-nightly-2.0-preview==2.0.0.dev20190911`. Thank you!

Feel free to close at your discretion.

**Comment by mihaimaruseac** [comment]
In that case, closing.

Thank you for verifying.

@arainboldt the fix should get released in all pips we are releasing.

**Comment by cuongth95** [comment]
`gast-0.3.2` on `Tensorflow 2.0.0rc` still get that issue, but for 'Str'. 
My solution is downgrading to `gast-0.2.2`

WARNING:tensorflow:Entity <function <lambda> at 0x000002567C2DB950> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Str'

**Comment by wchargin** [comment]
@cuongth95: Right; downgrading is the official solution at this time.

**Comment by mihaimaruseac** [comment]
`gast` has been pinned in the meantime, pending new release

**Comment by mihaimaruseac** [comment]
New update:

`gast` has been pinned to 0.2.2 for 1.15 and 2.0 and later releases as well as nightly.
TF 1.14 or earlier don't have `gast` pinned and won't get it as we are not doing more releases there (except for security vulnerabilities).

If you encounter this issue on 1.14 or earlier, please install gast==0.2.2 using pip before installing tensorflow.

**Comment by bestwayyy** [comment]
I'm still getting the error even with gast 0.2.2.
I really need help to get this fixed.

**Comment by mihaimaruseac** [comment]
We are currently working on getting `gast==0.3.2`. Apologies for the delay.

**Comment by wookayin** [comment]
Starting from TensorFlow 2.2.0, it will work with gast 0.3.x but NOT gast 0.2.x any more. For TF <= 2.1, gast 0.2.2 is needed.
