### PR TITLE
Pass the Android aar build with android-ndk-r19c clang 3.8

### PR DESCRIPTION
**Pull request by guoyinchen**
Add user-provided default constructor and remove "const" statement
for "reducer".

Build cmds:
$bazel build --cxxopt='--std=c++11' -c opt --config=android_arm64 \
   --config=monolithic //tensorflow/lite/java:tensorflow-lite-with-select-tf-ops

Build error:
tensorflow/core/kernels/bias_op.cc:278:13: error: default initialization of an object
of const type 'const functor::ReduceMiddleDimensions<float, AccumT,
Eigen::internal::scalar_sum_op<AccumT>, Eigen::internal::SumReducer<float> >'
(aka 'const ReduceMiddleDimensions<float, float, scalar_sum_op<float>,
 SumReducer<float> >') without a user-provided default constructor
            redux;
                        ^
tensorflow/core/kernels/quantized_resize_bilinear_op.cc:52:16: error: default
initialization of an object of const type 'const tensorflow::LegacyScaler'
without a user-provided default constructor
  const Scaler scaler;
                 ^

Signed-off-by: Chen Guoyin <guoyin.chen@gmail.com>

### CODE REVIEW

**Comment by freedomtan** [comment]
FYR, with android ndk r19c, I can run bazel build --cxxopt='--std=c++11' -c opt --config=android_arm64 --config=monolithic //tensorflow/lite/java:tensorflow-lite-with-select-tf-ops without problem. BTW, the clang in ndk-r19 should be clang 8.0.2.

**Review by ezhulenev — APPROVED** [review]

**Comment by guoyinchen** [comment]
> FYR, with android ndk r19c, I can run bazel build --cxxopt='--std=c++11' -c opt --config=android_arm64 --config=monolithic //tensorflow/lite/java:tensorflow-lite-with-select-tf-ops without problem. BTW, the clang in ndk-r19 should be clang 8.0.2.

I thought i was using r19 ndk. But it actually use the r12 ndk which has the clang 3.8.
android-ndk-r12-beta2/toolchains/llvm/prebuilt/linux-x86_64/bin$ ./clang --version
Android clang version 3.8.256229  (based on LLVM 3.8.256229)
Target: x86_64-unknown-linux
Thread model: posix
InstalledDir: /home/myname/android-studio/android-ndk-r12-beta2/toolchains/llvm/prebuilt/linux-x86_64/bin/.
