### ISSUE TITLE
"Cache iterator is in an invalid state" error

### ISSUE THREAD

**Issue by apls777** [tensorflow/tensorflow#29060]
**System information**
- OS Platform and Distribution: macOS High Sierra 10.13.6
- TensorFlow for CPU installed from PyPI
- TensorFlow version: v1.13.0-rc2-5-g6612da8951, 1.13.1
- Python version: 3.6.6

**Describe the current behavior**

Minimal not working example:
```python
import tensorflow as tf
from tensorflow.python.framework.errors_impl import OutOfRangeError


dataset = tf.data.Dataset.range(10)
dataset = dataset.cache('cache1')
dataset = dataset.map(lambda a: a)
dataset = dataset.batch(4)

batch = dataset.make_one_shot_iterator().get_next()

with tf.Session() as sess:
    while True:
        try:
            res = sess.run(batch)
            print(res)
        except OutOfRangeError:
            print('out-of-range')
            break
```

The code above properly iterates through the dataset only the first run when a cache doesn't exist. But when it loads the dataset from the cache file it crashes with an error:
```
tensorflow.python.framework.errors_impl.InternalError: Cache iterator is in an invalid state. (Perhaps GetNext called after end_of_sequence?)
	 [[{{node IteratorGetNext}}]
```

**A workaround**

It happens because the `map` operation follows right after the `cache`. It starts working as expected if some other dataset operation is added between `cache` and `map` steps. For example:
```python
...

dataset = tf.data.Dataset.range(10)
dataset = dataset.cache('cache1')
dataset = dataset.filter(lambda x: True)  # a fake filter is added
dataset = dataset.map(lambda a: a)
dataset = dataset.batch(4)

...
```

**Comment by muddham** [comment]
@apls777 I have executed the first part of the code in TF 1.12.0, did not receive any error. Please try and let us know how it progresses. Thanks!

**Comment by apls777** [comment]
@muddham It works in TF 1.12.0. Just changed the filename to `./cache1` instead of `cache1`, otherwise, it throws an error for the first run:
```
tensorflow.python.framework.errors_impl.NotFoundError: ; No such file or directory
	 [[{{node IteratorGetNext}} = IteratorGetNext[output_shapes=[[?]], output_types=[DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]
```

**Comment by muddham** [comment]
@apls777 As it is working now, are you happy for this issue to be closed?

**Comment by apls777** [comment]
@muddham No, clearly it’s a bug that should be fixed in the latest stable version.

**Comment by muddham** [comment]
@apls777 I ran the code in TF 1.13 GPU the output I got was below.
[0 1 2 3]
[4 5 6 7]
[8 9]
out-of-range

In TF 1.13 CPU I got the below error.
AttributeError: 'BatchDataset' object has no attribute 'make_one_shot_iterator'

**Comment by apls777** [comment]
@muddham Did you run the code twice to load the dataset from a cache? Are you sure you're running it on TF 1.13 **.1**? What version of Python do you use?

**Comment by gadagashwini** [comment]
> @muddham Did you run the code twice to load the dataset from a cache? Are you sure you're running it on TF 1.13 **.1**? What version of Python do you use?

I am able to reproduce the issue with TF 1.13.1 and Python 3.6.7.

**Comment by jsimsa** [comment]
@apls777 thank you for reporting the issue and providing a minimal reproducible example.

I can confirm this is an issue. The problem is that the existing cache transformation produces an error if the dataset transformation that consumes its input asks for an input after the cache transformations has reached the end of its input. This happens in your repro because `.map(fn).batch(batch_size)` will get fused into `.map_and_batch(fn, batch_size)` which will ask for `batch_size` worth of elements at once. Because the input cardinality (10) is not divisible evenly by the batch size (4), the invalid cache op kernel behavior is triggered. Inserting a transformation between `map` and `batch` will prevent the fusion from happening (and so does disabling the fusion through tf.data [options](https://www.tensorflow.org/api_docs/python/tf/data/experimental/OptimizationOptions#map_and_batch_fusion).

I have a fix for this and expect it to merged to master by the end of this week.

**Comment by devstein** [comment]
@apls777 

I'm running into this issue when caching before `interleave`

`tf 2.0.0-beta1` and `python 3.6.8`
```python
    filenames_dataset = filenames_dataset.cache("./some_path")

    return filenames_dataset.interleave(
        lambda f: map_file_to_xy_dataset(f, predict_task_fn, params),
        cycle_length=params[CYCLE_LENGTH_KEY],
        block_length=params[BLOCK_LENGTH_KEY],
        num_parallel_calls=tf.data.experimental.AUTOTUNE)
```

```
Iterator "Iterator::Model::Prefetch::Batch::Shuffle::ParallelInterleaveV2" returned OutOfRange without setting `*end_of_sequence`. This indicates that an error may have occurred. Original message: Attempting to call get_next after iteration should have finished. [Op:IteratorGetNextSync]
```

**Comment by jsimsa** [comment]
@alextp could you please take a look, the ResourceMgr change is not specific to tf.data

**Comment by jsimsa** [comment]
@devstein thank you for reporting the problem. This is a different issue, so please create a new issue for it and reference it here. Thank you.

**Comment by devstein** [comment]
@jsimsa Will do!
