### ISSUE TITLE
DistributedDataset does not work on Python 3.8

### ISSUE THREAD

**Issue by ornew** [tensorflow/tensorflow#50436]
**System information**

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): `no`
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): `docker ubuntu:focal`
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: `no`
- TensorFlow installed from (source or binary): `binary`
- TensorFlow version (use command below): `v2.5.0-rc3-213-ga4dfb8d1a71 2.5.0`
- Python version: `3.8.5`
- Bazel version (if compiling from source): `n/a`
- GCC/Compiler version (if compiling from source): `n/a`
- CUDA/cuDNN version: `n/a`
- GPU model and memory: `n/a`

**Describe the current behavior**

When I use Python 3.8.5,

MirroredStrategy:

```
Exception ignored in: <function Pool.__del__ at 0x7fbd5c04d280>
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 268, in __del__
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 362, in put
AttributeError: 'NoneType' object has no attribute 'dumps'
```

MultiWorkerMirroredStrategy:

```
terminate called without an active exception
```

Nothing happens in Python 3.6.9.

**Describe the expected behavior**

The process exits with code 0.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```python
import sys
import tensorflow as tf


print(sys.version_info)
print(tf.version.GIT_VERSION, tf.version.VERSION)


def distribute_dataset_fn(input_context: tf.distribute.InputContext):
  return tf.data.Dataset.from_tensors(([1.0])).repeat(64).batch(2)


@tf.function
def step(x):
  return x


if __name__ == '__main__':
  strategy = tf.distribute.MultiWorkerMirroredStrategy()
  #strategy = tf.distribute.MirroredStrategy()
  with strategy.scope():
    dist_ds = strategy.distribute_datasets_from_function(distribute_dataset_fn)

  for x in dist_ds:
    strategy.run(step, args=[x])
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
2021-06-24 04:46:17.224210: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:tensorflow:There are non-GPU devices in `tf.distribute.Strategy`, not using nccl allreduce.
WARNING:tensorflow:Collective ops is not configured at program startup. Some performance features may not be enabled.
2021-06-24 04:46:17.280529: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2021-06-24 04:46:17.281658: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2199970000 Hz
sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)
v2.5.0-rc3-213-ga4dfb8d1a71 2.5.0
Exception ignored in: <function Pool.__del__ at 0x7fbd5c04d280>
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 268, in __del__
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 362, in put
AttributeError: 'NoneType' object has no attribute 'dumps'
```

```
2021-06-24 04:52:19.023657: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-06-24 04:52:19.031611: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job worker -> {0 -> tf-multi-worker-v5xfh-worker-0.pipelines.svc:2222, 1 -> tf-multi-worker-v5xfh-worker-1.pipelines.svc:2222}
2021-06-24 04:52:19.033039: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:411] Started server with target: grpc://tf-multi-worker-v5xfh-worker-0.pipelines.svc:2222
2021-06-24 04:52:20.069924: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2021-06-24 04:52:20.071033: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2199970000 Hz
sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)
v2.5.0-rc3-213-ga4dfb8d1a71 2.5.0
terminate called without an active exception
```

**Comment by jvishnuvardhan** [comment]
@ornew Can you please explain details about your setup like how many workers? GPUs? CPUs? I tried on a system with single GPU and don't face that error. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/996daf2a6ddf9f813c16bb7519845893/untitled.ipynb). Thanks!

**Comment by ornew** [comment]
Please see attached logs. now I'm using tensorflow-cpu binary, on two workers with grpc ring communications.

I'm using kubeflow for running:

```yaml
apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  generateName: tf-multi-worker-example-
spec:
  backoffLimit: 0
  tfReplicaSpecs:
    Worker:
      replicas: 2
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: tensorflow
              image: <python 3.8 base image>
              command: ["/bin/bash"]
              args:
                - -exc
                - python3 /example.py
```

**Comment by gadagashwini** [comment]
Hi @ornew, Seems issue is resolved on latest Tensorflow version 2.9
```
>>> import sys
>>> import tensorflow as tf
>>> print(sys.version_info)
sys.version_info(major=3, minor=9, micro=12, releaselevel='final', serial=0)
>>> print(tf.version.GIT_VERSION, tf.version.VERSION)
v2.9.0-18-gd8ce9f9c301 2.9.1
>>> def distribute_dataset_fn(input_context: tf.distribute.InputContext):
...     return tf.data.Dataset.from_tensors(([1.0])).repeat(64).batch(2)
... 
>>> @tf.function
... def step(x):
...     return x
... 
>>> if __name__ == '__main__':
...     strategy = tf.distribute.MultiWorkerMirroredStrategy()
...     with strategy.scope():
...       dist_ds = strategy.distribute_datasets_from_function(distribute_dataset_fn)
...     for x in dist_ds:
...       strategy.run(step, args=[x])
... 
WARNING:tensorflow:Collective ops is not configured at program startup. Some performance features may not be enabled.
INFO:tensorflow:Single-worker MultiWorkerMirroredStrategy with local_devices = ('/device:GPU:0', '/device:GPU:1'), communication = CommunicationImplementation.AUTO
WARNING:tensorflow:AutoGraph could not transform <function step at 0x7fb115832700> and will run it as-is.
Cause: Unable to locate the source code of <function step at 0x7fb115832700>. Note that functions defined in certain environments, like the interactive Python shell, do not expose their source code. If that is the case, you should define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.experimental.do_not_convert. Original error: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING: AutoGraph could not transform <function step at 0x7fb115832700> and will run it as-is.
Cause: Unable to locate the source code of <function step at 0x7fb115832700>. Note that functions defined in certain environments, like the interactive Python shell, do not expose their source code. If that is the case, you should define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.experimental.do_not_convert. Original error: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
PerReplica:{
  0: <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>,
  1: <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>
}
PerReplica:{
  0: <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>,
  1: <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>
}
PerReplica:{
  0: <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>,
  1: <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>
}
PerReplica:{
  0: <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>,
  1: <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>
}
PerReplica:{
  0: <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>,
  1: <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>
}
PerReplica:{
  0: <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>,
  1: <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>
}
PerReplica:{
  0: <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>,
  1: <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>
}
PerReplica:{
  0: <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>,
  1: <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>
}
PerReplica:{
  0: <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>,
  1: <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>
}
PerReplica:{
  0: <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>,
  1: <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>
}
PerReplica:{
  0: <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>,
  1: <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>
}
PerReplica:{
  0: <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>,
  1: <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>
}
PerReplica:{
  0: <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>,
  1: <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>
}
PerReplica:{
  0: <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>,
  1: <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>
}
PerReplica:{
  0: <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>,
  1: <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>
}
PerReplica:{
  0: <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>,
  1: <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>
}
```

**Comment by ornew** [comment]
@gadagashwini Thank you!
