### ISSUE TITLE
TensorBoard charts blank on Firefox

### ISSUE THREAD

**Issue by stepseazy** [tensorflow/tensorflow#4856]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

I have not found any related issues
### Environment info

Operating System:

Ubuntu 16.04

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

```

rik@rik-MS-7971:~$ ls -l /usr/local/cuda/lib64/libcud*
-rw-r--r-- 1 root root   560184 Sep 23 09:09 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 Sep 23 09:09 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 root root       19 Sep 23 09:09 /usr/local/cuda/lib64/libcudart.so.8.0 -> libcudart.so.8.0.27
-rwxr-xr-x 1 root root   394472 Sep 23 09:09 /usr/local/cuda/lib64/libcudart.so.8.0.27
-rw-r--r-- 1 root root   737516 Sep 23 09:09 /usr/local/cuda/lib64/libcudart_static.a
lrwxrwxrwx 1 rik  rik        13 Jul 27 01:55 /usr/local/cuda/lib64/libcudnn.so -> libcudnn.so.5
lrwxrwxrwx 1 rik  rik        17 Jul 27 01:55 /usr/local/cuda/lib64/libcudnn.so.5 -> libcudnn.so.5.1.5
-rwxrwxr-x 1 rik  rik  79337624 Sep 26 21:55 /usr/local/cuda/lib64/libcudnn.so.5.1.5
-rw-rw-r-- 1 rik  rik  69756172 Sep 26 21:55 /usr/local/cuda/lib64/libcudnn_static.a
```

If installed from binary pip package, provide:
1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

```
rik@rik-MS-7971:~$ python -c "import tensorflow; print(tensorflow.__version__)"
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
0.11.0rc0
```

If installed from source, provide 
1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`
### What other attempted solutions have you tried?

Tried erasing files from logdir and re-running. Tried running mnist with summaries tutorial, this is also blank charts
### Logs or other output that would be helpful

(If logs are large, please upload as attachment or provide link).

---

All, when running [MNIST with Summaries example](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/mnist/mnist_with_summaries.py) charts exist on events and distribution tabs, they are blank. Histograms and appear correct. Also, code is running slow compated to non-tensorboard version. Please help, Thanks. Below is output.

```
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Extracting /tmp/data/train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting /tmp/data/train-labels-idx1-ubyte.gz
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting /tmp/data/t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting /tmp/data/t10k-labels-idx1-ubyte.gz
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:925] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:951] Found device 0 with properties: 
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.797
pciBusID 0000:01:00.0
Total memory: 7.92GiB
Free memory: 7.36GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:972] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0)
Accuracy at step 0: 0.0802
Accuracy at step 10: 0.6788
Accuracy at step 20: 0.8217
Accuracy at step 30: 0.8495
Accuracy at step 40: 0.8734
Accuracy at step 50: 0.8794
Accuracy at step 60: 0.8847
Accuracy at step 70: 0.8863
Accuracy at step 80: 0.8898
Accuracy at step 90: 0.8939
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcupti.so locally
Adding run metadata for 99
Accuracy at step 100: 0.9015
Accuracy at step 110: 0.9132
Accuracy at step 120: 0.9163
Accuracy at step 130: 0.9197
Accuracy at step 140: 0.9252
Accuracy at step 150: 0.9182
Accuracy at step 160: 0.9283
Accuracy at step 170: 0.9243
Accuracy at step 180: 0.9231
Accuracy at step 190: 0.9266
Adding run metadata for 199
Accuracy at step 200: 0.9327
Accuracy at step 210: 0.9336
Accuracy at step 220: 0.9329
Accuracy at step 230: 0.9311
Accuracy at step 240: 0.9308
Accuracy at step 250: 0.9214
Accuracy at step 260: 0.9324
Accuracy at step 270: 0.9393
Accuracy at step 280: 0.9327
Accuracy at step 290: 0.9401
Adding run metadata for 299
Accuracy at step 300: 0.9442
Accuracy at step 310: 0.9405
Accuracy at step 320: 0.9424
Accuracy at step 330: 0.9425
Accuracy at step 340: 0.9468
Accuracy at step 350: 0.9461
Accuracy at step 360: 0.9427
Accuracy at step 370: 0.9434
Accuracy at step 380: 0.9474
Accuracy at step 390: 0.9449
Adding run metadata for 399
Accuracy at step 400: 0.9443
Accuracy at step 410: 0.9449
Accuracy at step 420: 0.9474
Accuracy at step 430: 0.9455
Accuracy at step 440: 0.952
Accuracy at step 450: 0.9505
Accuracy at step 460: 0.9525
Accuracy at step 470: 0.9493
Accuracy at step 480: 0.9489
Accuracy at step 490: 0.9515
Adding run metadata for 499
Accuracy at step 500: 0.9517
Accuracy at step 510: 0.9515
Accuracy at step 520: 0.9499
Accuracy at step 530: 0.9539
Accuracy at step 540: 0.9548
Accuracy at step 550: 0.9573
Accuracy at step 560: 0.9548
Accuracy at step 570: 0.9569
Accuracy at step 580: 0.9552
Accuracy at step 590: 0.9548
Adding run metadata for 599
Accuracy at step 600: 0.9551
Accuracy at step 610: 0.9535
Accuracy at step 620: 0.96
Accuracy at step 630: 0.9599
Accuracy at step 640: 0.9603
Accuracy at step 650: 0.9616
Accuracy at step 660: 0.9617
Accuracy at step 670: 0.9623
Accuracy at step 680: 0.9613
Accuracy at step 690: 0.9614
Adding run metadata for 699
Accuracy at step 700: 0.9592
Accuracy at step 710: 0.9614
Accuracy at step 720: 0.9595
Accuracy at step 730: 0.9646
Accuracy at step 740: 0.9636
Accuracy at step 750: 0.964
Accuracy at step 760: 0.9656
Accuracy at step 770: 0.9616
Accuracy at step 780: 0.9631
Accuracy at step 790: 0.964
Adding run metadata for 799
Accuracy at step 800: 0.9637
Accuracy at step 810: 0.9637
Accuracy at step 820: 0.9653
Accuracy at step 830: 0.9636
Accuracy at step 840: 0.9615
Accuracy at step 850: 0.9654
Accuracy at step 860: 0.9668
Accuracy at step 870: 0.9653
Accuracy at step 880: 0.965
Accuracy at step 890: 0.9645
Adding run metadata for 899
Accuracy at step 900: 0.9664
Accuracy at step 910: 0.967
Accuracy at step 920: 0.9658
Accuracy at step 930: 0.9664
Accuracy at step 940: 0.9671
Accuracy at step 950: 0.967
Accuracy at step 960: 0.9663
Accuracy at step 970: 0.968
Accuracy at step 980: 0.9679
Accuracy at step 990: 0.9666
Adding run metadata for 999
```

---

**Comment by alexbeloi** [comment]
I'm not sure if this is the same issue, but I had blank (black images) in place of the events and distribution plots. This occurred with Firefox version 49.0, when I tried in chrome version 54.0.2840.59 (64-bit), the events and distributions plots would display correctly. 

The 3d histogram plots displayed correctly in both firefox and chrome. Did not test in other browsers.

Images from firefox 49.0 below:
![screenshot from 2016-10-12 13-56-25](https://cloud.githubusercontent.com/assets/9807648/19327449/f3e7915a-9083-11e6-83d5-47a4caafd66b.png)
![screenshot from 2016-10-12 13-56-53](https://cloud.githubusercontent.com/assets/9807648/19327450/f4095542-9083-11e6-99bc-0898bbc36398.png)

**Comment by jart** [comment]
Thank you both for reporting. @stepseazy Are you using Firefox? Where did you get TensorBoard? Bazel at HEAD? Or pip install? I'd also be interested in knowing the same from @alexbeloi. 

CC: @danmane

**Comment by alexbeloi** [comment]
@jart : I have installed with pip install

tensorflow version 0.11.0rc0
not sure how to get tensorboard version if it is independent from tensorflow

**Comment by stepseazy** [comment]
Yes, I was indeed using Firefox. It's the only browser I have installed in ubuntu right now so while I saw alex's response (thanks alex) I haven't tried another browser yet but I'll report back shortly...

**Comment by stepseazy** [comment]
I ssem to be having another issue now and I can't use tensorboard on either browser. Tensorboard can't seem to find these files that exist but in a different location. For example the first file exists in /home/rik/anaconda3/lib/python3.5/site-packages/external/webcomponentsjs but not in /home/rik/anaconda3/lib/python3.5/site-packages/tensorflow/tensorboard/webcomponentsjs/

```
Starting TensorBoard b'29' on port 6006
(You can navigate to http://127.0.1.1:6006)
127.0.0.1 - - [14/Oct/2016 09:03:41] "GET / HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/rik/anaconda3/lib/python3.5/site-packages/tensorflow/tensorboard/webcomponentsjs/webcomponents-lite.min.js' on path /home/rik/anaconda3/lib/python3.5/site-packages/tensorflow/tensorboard/webcomponentsjs/webcomponents-lite.min.js
127.0.0.1 - - [14/Oct/2016 09:03:41] "GET /webcomponentsjs/webcomponents-lite.min.js HTTP/1.1" 200 -
127.0.0.1 - - [14/Oct/2016 09:03:41] "GET /lib/css/global.css HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/rik/anaconda3/lib/python3.5/site-packages/tensorflow/tensorboard/dist/bazel-html-imports.html' on path /home/rik/anaconda3/lib/python3.5/site-packages/tensorflow/tensorboard/dist/bazel-html-imports.html
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/rik/anaconda3/lib/python3.5/site-packages/external/dist/bazel-html-imports.html' on path /home/rik/anaconda3/lib/python3.5/site-packages/external/dist/bazel-html-imports.html

```

**Comment by jart** [comment]
TensorBoard is written to support Chrome and Firefox. So we're definitely going to make it a priority to fix the Firefox support. As for the IOErrors, you probably ran into the same issue as #4830. This was just fixed internally and will be pushed to GitHub soon, if it hasn't been already.

**Comment by stepseazy** [comment]
I used this to install:

```
export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.11.0rc0-cp35-cp35m-linux_x86_64.whl
sudo pip3 install --upgrade $TF_BINARY_URL
```

from [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md). I'm assuming this is what will be updated?

**Comment by jart** [comment]
Yes it will be updated in time. But it would help us if you could test out the repository and HEAD and let us know if it works.

**Comment by vladfi1** [comment]
I'm having the same issue with tensorflow r0.11 bazel install. I get the black charts only when connecting from a different computer than the one running tensorboard (both local and remote are running firefox 49).

**Comment by danmane** [comment]
Looks like Plottable CSS rules aren't getting applied for some reason. 
I'm surprised that it happens only when connected remotely. I would expect it to either always be missing or always be present. This is quite weird :<

**Comment by fdasilva59** [comment]
I met the same issue with r0.11rc1 (and  previously with r0.11rc0) 

Details : 
- using  Ubuntu 14.04 with Nvidia GTX1080 (latest drivers, latest version of Cuda 8 and cuDnn5)
- Install and build  from sources
- testing with mnist_with_summaries.py

`~/develop/tensorflow/tutorials/mnist$ python mnist_with_summaries.py 
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
Extracting /tmp/data/train-images-idx3-ubyte.gz
Extracting /tmp/data/train-labels-idx1-ubyte.gz
Extracting /tmp/data/t10k-images-idx3-ubyte.gz
Extracting /tmp/data/t10k-labels-idx1-ubyte.gz
I tensorflow/core/common_runtime/gpu/gpu_device.cc:951] Found device 0 with properties: 
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.7335
pciBusID 0000:04:00.0
Total memory: 7.92GiB
Free memory: 7.81GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:972] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:04:00.0)
Accuracy at step 0: 0.118
Accuracy at step 10: 0.6865
Accuracy at step 20: 0.81
[...]
Accuracy at step 980: 0.9673
Accuracy at step 990: 0.967
Adding run metadata for 999
`  

- then launch tensorboard : 
`
~/develop/tensorflow/tutorials/mnist$ tensorboard --logdir=/tmp/mnist_logs/
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
Starting TensorBoard 29 on port 6006
`

- With Mac OS X 10.11.6 Le Capitan and Safari Version 10.0 (11602.1.50.0.10), I can display tensorborad. HIstohrams, images are well displayed. However if I try do display Events, like accuracy, cross entropy, ... just a blanck/black iamge is displayed instead of the graphs

- also an error in the console used to launch tensorboard
`127.0.0.1 - - [23/Oct/2016 12:07:27] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [23/Oct/2016 12:07:28] "GET /webcomponentsjs/webcomponents-lite.min.js HTTP/1.1" 200 -
127.0.0.1 - - [23/Oct/2016 12:07:28] code 404, message Not Found
127.0.0.1 - - [23/Oct/2016 12:07:28] "GET /dist/bazel-html-imports.html HTTP/1.1" 404 -
127.0.0.1 - - [23/Oct/2016 12:07:28] "GET /lib/css/global.css HTTP/1.1" 200 -
127.0.0.1 - - [23/Oct/2016 12:07:28] "GET /dist/tf-tensorboard.html HTTP/1.1" 200 -
127.0.0.1 - - [23/Oct/2016 12:07:28] "GET /polymer/polymer.html HTTP/1.1" 200 -
`

and if I try to display Events/accuracy  and cross entropy there does not seem to have some errors 
`
127.0.0.1 - - [23/Oct/2016 12:08:45] "GET /data/scalars?run=test&tag=accuracy HTTP/1.1" 200 -
127.0.0.1 - - [23/Oct/2016 12:08:45] "GET /data/scalars?run=train&tag=accuracy HTTP/1.1" 200 -

127.0.0.1 - - [23/Oct/2016 12:09:11] "GET /data/scalars?run=test&tag=cross%20entropy HTTP/1.1" 200 -
127.0.0.1 - - [23/Oct/2016 12:09:11] "GET /data/scalars?run=train&tag=cross%20entropy HTTP/1.1" 200 -
`

Note when testing **with previous release candidate r0.11rc0 , I met lots of IOError** (a few examples below). **I do NOT have this errors with r0.11rc1** : this must have been corrected.

`WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/polymer/polymer.html' on path /usr/local/lib/python2.7/dis
t-packages/tensorflow/tensorboard/polymer/polymer.html
127.0.0.1 - - [20/Oct/2016 16:49:01] "GET /polymer/polymer.html HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/iron-icons/iron-icons.html' on path /usr/local/lib/python2
.7/dist-packages/tensorflow/tensorboard/iron-icons/iron-icons.html
127.0.0.1 - - [20/Oct/2016 16:49:01] "GET /iron-icons/iron-icons.html HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/paper-tabs/paper-tabs.html' on path /usr/local/lib/python2
.7/dist-packages/tensorflow/tensorboard/paper-tabs/paper-tabs.html
`

**Comment by fdasilva59** [comment]
More info : 
- problem occurs in Firefox 49.0.2 (Mac OS X El Capitan), Firefox 47.0.1 (Windows 7)
- problem occurs in Safari Version 10.0 (11602.1.50.0.10) (Mac OS X El Capitan)
- Events graphs are well displayed with Google Chrome 54.0.2840.71 (Window 7) 

Now looking in the Safari console, a javascript error occurs when trying to display the accuracy graphs : 
[Warning] Warning: Problem parsing viewBox="" (d3.js, line 662)

```
    function attrConstant() {
      this.setAttribute(name, value);          # <---- Problem parsing viewBox=""
    }
```

In fact the same error occurs in Google Chrome but it seems more fault tolerant as the graph is well displayed in the end

```
d3.js:662 Error: <svg> attribute viewBox: Unexpected end of attribute. Expected number, "".
attrConstant                   @ d3.js:662
(anonymous function)   @ d3.js:961
d3_selection_each         @ d3.js:967
d3_selectionPrototype.each     @ d3.js:960
d3_selectionPrototype.attr       @ d3.js:651
LineChart.setViewBox  @ tf-tensorboard.html:3852
LineChart.renderTo       @ tf-tensorboard.html:3841
(anonymous function)   @ tf-tensorboard.html:4195
(anonymous function)   @ polymer.html:1307
```

**Comment by MadWombat** [comment]
Same problem. 

Tensorflow 0.11.0rc2 installed via pip
Firefox 49.0.2
OSX 10.12.1

Works fine on Chrome 54.0.2840.71

**Comment by pannous** [comment]
see #5341 for workaround

**Comment by Samurais** [comment]
Same problem.

Tensorflow 0.11.0rc1 installed via pip
Firefox 49.0.2
Ubuntu 16.04

work fine on Chrome 54.0.x

**Comment by jendelel** [comment]
@Samurais Either upgrade to new version of tensorflow, or link the css file to the html i.e. apply the fix (https://github.com/tensorflow/tensorflow/pull/5755/files) yourself.
