### ISSUE TITLE
static_assert failure with gcc

### ISSUE THREAD

**Issue by elfringham** [tensorflow/tensorflow#62125]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

git HEAD

### Custom code

No

### OS platform and distribution

Ubuntu 20.04

### Mobile device

n/a

### Python version

3.9.17

### Bazel version

6.1.0

### GCC/compiler version

10.2.1

### CUDA/cuDNN version

n/a

### GPU model and memory

n/a

### Current behavior?

Build failure

### Standalone code to reproduce the issue

```shell
bazel build --config=mkl_aarch64_threadpool --copt=-flax-vector-conversions --define=tf_api_version=2 --verbose_failures --jobs=75 -- //tensorflow/tools/pip_package:build_pip_package
```

### Relevant log output

```shell
tensorflow/compiler/mlir/lite/stablehlo/transforms/legalize_hlo.cc: In member function 'mlir::LogicalResult mlir::odml::{anonymous}::ConvertReduceOpToTfArgMinMax<TfReduce, TfArgReduce>::matchAndRewrite(mlir::mhlo::ReduceOp, mlir::OpConversionPattern<mlir::mhlo::ReduceOp>::OpAdaptor, mlir::ConversionPatternRewriter&) const':
tensorflow/compiler/mlir/lite/stablehlo/transforms/legalize_hlo.cc:2186: error: static assertion failed: Only TF::MaxOp and TF::MinOp are supported.
 2186 |         static_assert(false, "Only TF::MaxOp and TF::MinOp are supported.");
      | 
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 502.712s, Critical Path: 197.25s
INFO: 1603 processes: 79 internal, 1524 local.
FAILED: Build did NOT complete successfully
```

**Comment by elfringham** [comment]
Introduced by https://github.com/tensorflow/tensorflow/commit/e7aa1cadef44349d57019401e54d4fb390bf48f1

**Comment by elfringham** [comment]
Fixed by https://github.com/tensorflow/tensorflow/commit/5a39244519e46bfba66e377e5ee533bc2ab3969b
