### ISSUE TITLE
Error building Custom Op with TF2.0 Nightly

### ISSUE THREAD

**Issue by oracle3001** [tensorflow/tensorflow#31477]
**System information**
- OS Platform and Distribution: Windows 10
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): TF 2.0 Nightly
- Python version: 3.6
- GCC/Compiler version (if compiling from source): VS2017

I have a number of custom ops which I am able to build / operate fine using TF v1.14. I have just tried to recompile them using 2.0 Nightly version of tensorflow and run into the following set of build errors relating to op_kernehl.h

1>d:\data\documents\github\tensorflow\tensorflow\core\framework\op_kernel.h(690): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>d:\data\documents\github\tensorflow\tensorflow\core\framework\op_kernel.h(690): error C2143: syntax error: missing ';' before '*'
1>d:\data\documents\github\tensorflow\tensorflow\core\framework\op_kernel.h(690): error C2238: unexpected token(s) preceding ';'
1>d:\data\documents\github\tensorflow\tensorflow\core\framework\op_kernel.h(1134): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>d:\data\documents\github\tensorflow\tensorflow\core\framework\op_kernel.h(1134): error C2143: syntax error: missing ';' before '*'
1>d:\data\documents\github\tensorflow\tensorflow\core\framework\op_kernel.h(1134): error C2334: unexpected token(s) preceding '{'; skipping apparent function body

**Comment by jvishnuvardhan** [comment]
@oracle3001 There are couple of resources [1](https://www.tensorflow.org/guide/extend/op#build_a_pip_package_for_your_custom_op), and [2](https://github.com/tensorflow/docs/blob/master/site/en/guide/extend/op.md) for building custom ops.  Thanks!

**Comment by mihaimaruseac** [comment]
Unfortunately I won't have cycles to look into this, especially given that it's a Windows issue. Assigning to @gunan, possibly for future triage

**Comment by oracle3001** [comment]
@jvishnuvardhan - I have read those resources, and have a range of custom ops, which all build / work fine with TF v1.14. 

It is only when I try and compile against TF v2.0 nightly preview do I run into compiler errors.

**Comment by gunan** [comment]
@goldiegadde did anyone else report issues with custom ops with 2.0?
