### ISSUE TITLE
Example MNIST_RNN not working

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [tensorflow/tensorflow#4930]
Hello everyone,

I use the very last docker container, GPU Enabled (nvidia-docker). 
Everything works fine for what I could have tested so far.

Host : Ubuntu 14.04 Server with CUDA and NVIDIA drivers up to date

Except, this example is not working anymore :
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/skflow/mnist_rnn.py

**AttributeError: 'LSTMStateTuple' object has no attribute 'get_shape'**

![screen shot 2016-10-13 at 01 41 19](https://cloud.githubusercontent.com/assets/10923599/19331714/2fac0baa-90e6-11e6-8027-5f68dd10b160.png)

**Comment by jart** [comment]
Is it possible that this issue is related to #3056?

**Comment by DEKHTIARJonathan** [comment]
It seems like I am able to run the failing code :

![capture_](https://cloud.githubusercontent.com/assets/10923599/19341349/5ba6d3ce-912d-11e6-8724-f0e620045106.PNG)

So I would say, not related. If you need me to run any code. Do not hesitate. You will find my running configuration in this Issue : #4929 

Thanks for the help !

**Comment by jart** [comment]
We're happy to be of service.

**Comment by jart** [comment]
Just to clarify your recent comment, this is still broken for you, correct? I think the root cause with this issue and #4929 might be that there doesn't appear to be any tests for these examples. @baoblackcoal contributed this example, so maybe he/she can help.

**Comment by DEKHTIARJonathan** [comment]
Hello, yes it is still broken. I was just referencing that I can't reproduce the bug you referenced in the issue #3056.

**Comment by jart** [comment]
Assigning to @ilblackdragon who is the skflow czar.

**Comment by baoblackcoal** [comment]
@DEKHTIARJonathan Honestly, I had not tested mnist_rnn.py with GPU(I have not GPU environment :(). mnist_rnn.py work fine on my CPU version of Ubuntu14.4 and TF version is V0.10.0.  the following is log of python mnist_rnn.py

>`Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Extracting MNIST-data/train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting MNIST-data/train-labels-idx1-ubyte.gz
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting MNIST-data/t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting MNIST-data/t10k-labels-idx1-ubyte.gz
WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmpbmrvcx
WARNING:tensorflow:Using default config.
WARNING:tensorflow:Setting feature info to TensorSignature(dtype=tf.float32, shape=TensorShape([Dimension(None), Dimension(784)]), is_sparse=False)
WARNING:tensorflow:Setting targets info to TensorSignature(dtype=tf.float32, shape=TensorShape([Dimension(None), Dimension(10)]), is_sparse=False)
WARNING:tensorflow:<tensorflow.python.ops.rnn_cell.BasicLSTMCell object at 0x7f3bc48e1e90>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.
WARNING:tensorflow:<tensorflow.python.ops.rnn_cell.BasicLSTMCell object at 0x7f3b7e8d52d0>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.
Accuracy: 0.984300

Process finished with exit code 0`

**Comment by DEKHTIARJonathan** [comment]
@baoblackcoal is thereanything I can change to switch the script to CPU only and not using the GPU ?

**Comment by baoblackcoal** [comment]
AttributeError: 'LSTMStateTuple' object has no attribute 'get_shape' .

The issue above that may need the help of @ilblackdragon .

**Comment by ilblackdragon** [comment]
Sorry for late reply. We actually deleted this examples, as they are deprecated and untested. New examples will be `examples/learn`.
Now in this case, what happen is that `rnn` function call now returns `StateTuple` instead of jsut value. If you want to fix this in your version of example, feel free to change this lines:
```
   # Define a GRU cell with tensorflow		
   lstm_cell = tf.nn.rnn_cell.BasicLSTMCell(n_hidden)		
   # Get lstm cell output		
   _, encoding = tf.nn.rnn(lstm_cell, X, dtype=tf.float32)		
 		
   return learn.models.logistic_regression(encoding, y)
```
to
```
   # Define a GRU cell with tensorflow		
   lstm_cell = tf.nn.rnn_cell.BasicLSTMCell(n_hidden)		
   # Get lstm cell output		
   _, state_tuple = tf.nn.rnn(lstm_cell, X, dtype=tf.float32)
   encoding = tf.concat(1, [state_tuple.c, state_tuple.h])

   return learn.models.logistic_regression(encoding, y)
```

Hope this helps!
