### ISSUE TITLE
tf.nn has no attribute rnn_cell in version 1.0.1

### ISSUE THREAD

**Issue by xiatian122** [tensorflow/tensorflow#7664]
### Environment info
Operating System: Ubuntu 16.04

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1.0.0

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

`<ipython-input-66-e322aca5289e> in makeGRUCells()
      7 
      8         def makeGRUCells():
----> 9             base_cell = tf.nn.rnn_cell.GRUCell(num_units=RNN_HIDDEN_SIZE,)
     10             layered_cell = tf.nn.rnn_cell.MultiRNNCell([base_cell] * NUM_LAYERS,state_is_tuple=False)
     11             attn_cell =tf.contrib.rnn.AttentionCellWrapper(cell=layered_cell,attn_length=ATTN_LENGTH,state_is_tuple=False)

AttributeError: 'module' object has no attribute 'rnn_cell'`

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by standy66** [comment]
It was moved to contrib. Take a look [here](https://www.tensorflow.org/api_docs/python/tf/contrib/rnn)

**Comment by gaika** [comment]
The change is not mentioned in release notes, conversion script doesn't notice it too.

**Comment by aselle** [comment]
@gaika, sorry about that. Unfortunately it appears a few things slipped through. I'll update the conversion script. @yifeif, can you update the release notes, and @ebrevdo are there any rnn things that need to be added to the release notes?

**Comment by aselle** [comment]
##TODO

- [ ] fix converter script (aselle)
- [ ] fix release notes (yifeif)
- [ ] document anything else that is needed on release notes (ebrevdo)

**Comment by gaika** [comment]
Why did you close it? A lot of people will run into this issue when migrating to 1.0.

**Comment by ebrevdo** [comment]
Andrew, it does indeed seem that the move of many of the ops and cells to
tf.contrib.rnn was not mentioned in release.md.  mea culpa; i was hoping to
get them all back into core by 1.0.  Unfortunately looks like it won't
happen until TF 1.0.

So in the meantime, we should update the release notes to say that
tf.nn.rnn_cell.* and most functions in tf.nn.rnn.* (with the exception of
dynamic_rnn and raw_rnn) are temporarily in tf.contrib.rnn.  They will move
back into core (presumably) for TF 1.1.

**Comment by jihopark** [comment]
i also ran into this issue. I realized `tf.nn.rnn_cell.DropoutWrapper` is moved to `Module: tf.contrib.rnn.core_rnn_cell`. What is this? Why isn't all this included in the upgrade script??

I think i need to migrate back to 0.12 for now...

**Comment by szmgithub** [comment]
I also encountered such problems in Tensorflow 1.0:
lstm_cell = tf.nn.rnn_cell.BasicLSTMCell(size, forget_bias=0.0, state_is_tuple=True)
AttributeError: 'module' object has no attribute 'rnn_cell'
It can not find 'rnn_cell'. When I use tf.contrib.rnn.BasicLSTMCell, it worked. So i suggest you change the  nn.rnn_cell to contrib.rnn.

**Comment by aselle** [comment]
@yifeif, could you update the release notes?

**Comment by yifeif** [comment]
Release note was updated in #7745 to indicate that RNN is temporarily moved to contrib. But it also says it will be back in core in r1.1. We should update that part to 1.2, @ebrevdo?  Also cc @av8ramit for release.

**Comment by ebrevdo** [comment]
Yes; we should definitely update that to document the  move back in TF 1.2;
not 1.1.

**Comment by davtalab** [comment]
I am using tensorflow-1.1.0rc2, when I use the code for:
scell = tf.nn.rnn_cell.GRUCell(embedding_size)

I get the following error:
AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'rnn_cell'

what should I use instead  of  `tf.nn.rnn_cell.GRUCell` for 1.1.0rc2 version?

**Comment by ebrevdo** [comment]
tf.contrib.rnn.GRUCell

**Comment by nealwu** [comment]
Added a PR to fix the release notes to indicate TF 1.2 rather than TF 1.1.

Looks like the only remaining thing to fix this now is to update the conversion script?

**Comment by yifeif** [comment]
FYI now the release note should be updated in 1.0, 1.1 and master branches. Thanks @nealwu!

**Comment by physicso** [comment]
One more question here. I saved a RNN model in TF 0.12, how can I restore it in TF1.0?

**Comment by athuldevin** [comment]
i got this error what i do 

  File "C:\Users\win-7\Downloads\Compressed\tensorflow_chatbot-master\seq2seq_model.py", line 98, in __init__
    single_cell = tf.nn.rnn_cell.GRUCell(size)
AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'rnn_cell'

**Comment by nealwu** [comment]
Hi @athuldevin, as mentioned above, `tf.nn.rnn_cell` has moved to `tf.contrib.rnn`.

What you should actually do to solve the problem however is to pull your repository / grab the latest version of the code at https://github.com/tensorflow/models/blob/master/tutorials/rnn/translate/seq2seq_model.py. Your current version is out of date, and there have been a few other bugs fixed since then.

**Comment by physicso** [comment]
The RNN definition for TF 0.12 is different from 1.0: tf.nn. * -> tf.contrib.rnn. *

The model is not compatible, in other words, once we trained a model on TF 0.12, it is hard to restore it on TF 1.0.

I wrote an adapter, using which you can transfer TF 0.12 RNN model into TF 1.0.

Sample code ({k} indicates the k_th RNN layer):
replace_vars = {
'rnn/rnn/MultiRNNCell/Cell{k}/BasicLSTMCell/Linear/Matrix': 'rnn/rnn/multi_rnn_cell/cell_{k}/basic_lstm_cell/weights',
'rnn/rnn/MultiRNNCell/Cell{k}/BasicLSTMCell/Linear/Bias': 'rnn/rnn/multi_rnn_cell/cell_{k}/basic_lstm_cell/biases'}
saver.restore(sess, "old.ckpt")
names_to_vars = {v.op.name: v for v in tf.all_variables()}
for key in replace_vars.keys():
    bias_var = names_to_vars[key]
    names_to_vars[replace_vars[key]] = bias_var
    del names_to_vars[key]
saver = tf.train.Saver(var_list=names_to_vars)
saver.save(sess, 'new.ckpt')

You may refer to this repo for a complete solution:

https://github.com/physicso/TensorFlow_RNN_Adaptor

**Comment by ebrevdo** [comment]
FYI we'll try to bring the tf.nn.rnn_cell namespace back in TF 1.2.

**Comment by physicso** [comment]
@ebrevdo Great news, thanks!

**Comment by SNCI** [comment]
upgraded to 1.2.0rc0 
was rnn NOT moved back to core?
still getting:
AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'rnn_cell'

**Comment by ebrevdo** [comment]
I have a PR in place undergoing internal testing, should go out next week
in the nighties and then be in the final 1.2 release.

**Comment by ebrevdo** [comment]
And it'll be tf.nn.rnn_cell as before.

**Comment by SNCI** [comment]
Is there a wheel for 1.2-rc1 gpu for windows? Can't seem to find it.

**Comment by michal-kierzynka** [comment]
Hi,
I'm trying to move my LSTM network from TF v0.12 to v1.1, but its learning capabilities are very different:
in v0.12 I had:
`    cell = tf.nn.rnn_cell.BasicLSTMCell(num_units=n_hidden, state_is_tuple=True)
    cell = tf.nn.rnn_cell.MultiRNNCell([cell] * num_layers)
    cell = tf.nn.rnn_cell.DropoutWrapper(cell, output_keep_prob=dropout)`

in my TFv1.1 code I have now:
`    cell = []
    for _ in range(num_layers):
        cell.append(tf.contrib.rnn.BasicLSTMCell(num_units=n_hidden, state_is_tuple=True) )
        
    multicell = tf.contrib.rnn.MultiRNNCell([cell[i] for i in range(num_layers)])
    multicell = tf.contrib.rnn.DropoutWrapper(multicell, output_keep_prob=dropout)`

And these are not equivalent. The 0.12 version was learning much better than the one in 1.1. What is the reason? Did I move my code to 1.1 correctly?

**Comment by taiwotman** [comment]
This works: 
cell = tf.contrib.rnn.BasicRNNCell(num_units = rnn_size) in current Tensorflow version

**Comment by sleighsoft** [comment]
There seems to be a discrepancy between `tensorflow-gpu` v1.2.0 from pip and `tensorflow` v1.2.0 from pip.
I run the following within a `model_fn` for `Estimator`:
```
import tensorflow.contrib.rnn as rnn
def single_cell():
        return rnn.BasicLSTMCell(cell_size)
cell = rnn.core_rnn_cell.MultiRNNCell(
            [single_cell() for _ in range(layers)])
```
It throws the following error for `tensorflow-gpu` but works for `tensorflow`:
```
  File "/home/user/miniconda3/envs/pvalearning-gpu/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 289, in new_func
    return func(*args, **kwargs)
  File "/home/user/miniconda3/envs/pvalearning-gpu/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 455, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "/home/user/miniconda3/envs/pvalearning-gpu/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 955, in _train_model
    model_fn_ops = self._get_train_ops(features, labels)
  File "/home/user/miniconda3/envs/pvalearning-gpu/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1162, in _get_train_ops
    return self._call_model_fn(features, labels, model_fn_lib.ModeKeys.TRAIN)
  File "/home/user/miniconda3/envs/pvalearning-gpu/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1133, in _call_model_fn
    model_fn_results = self._model_fn(features, labels, **kwargs)
  File "/home/user/pva/learning/packages/model/my_model.py", line 67, in __model__
    cell = rnn.core_rnn_cell.MultiRNNCell(
AttributeError: module 'tensorflow.contrib.rnn' has no attribute 'core_rnn_cell'
```

**Comment by ebrevdo** [comment]
Use tf.nn.rnn_cell.MultiRNNCell.

**Comment by Halfish** [comment]
my tensorflow version is 1.2.1, and I find these three things are the same thing.
- tf.nn.rnn_cell.*
- tf.contrib.rnn.*
- tensorflow.python.ops.rnn_cell_impl.*

Proof it in ipython:
```python
In [78]: tf.nn.rnn_cell.LSTMCell
Out[78]: tensorflow.python.ops.rnn_cell_impl.LSTMCell

In [79]: tf.contrib.rnn.LSTMCell
Out[79]: tensorflow.python.ops.rnn_cell_impl.LSTMCell
```

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by nealwu** [comment]
[`tf.nn.rnn_cell`](https://www.tensorflow.org/api_docs/python/tf/nn/rnn_cell) is available as of TensorFlow 1.2, so I think we can close this issue.
