### ISSUE TITLE
tensorflow.lib missing some symbols on linking in a application

### ISSUE THREAD

**Issue by springile** [tensorflow/tensorflow#39407]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (Woindows 10):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (r2.1):
- TensorFlow version:
- Python version:3.7
- Installed using virtualenv? pip? conda?:venv
- Bazel version (if compiling from source):0.29.1
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.1, 7.6
- GPU model and memory: GTX1080

**Describe the problem**

I want use to tensotflow in windows 10. I have built r2.1 from source finally.
Another problem stop me again, there are some missing symbols on linking tensorflow.lib in my application.

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "class tensorflow::Session * __cdecl tensorflow::NewSession(struct tensorflow::SessionOptions const &)" (?NewSession@tensorflow@@YAPEAVSession@1@AEBUSessionOptions@1@@Z) 

It works in Linux. The same application does not work in windows.

Please help.
Thanks.

**Comment by ravikyram** [comment]
@heyufei2008 

Just to verify did you follow the instructions mentioned in [Tensorflow website.](https://www.tensorflow.org/install/source_windows) .You can check your cpu is avx2 instruction sets supported or not.Also, go through [link](https://github.com/tensorflow/tensorflow/issues/30647) and see if it helps you.Thanks!

**Comment by heyufei2008** [comment]
Yes， I followed the instructions from the website.
The link you provided is for 1.14 mostly.

Can you tell what I should do for r2.1?

Thanks.
John

**Comment by ymodak** [comment]
Can you try this hack https://github.com/tensorflow/tensorflow/issues/34159#issuecomment-565805682 ?

**Comment by heyufei2008** [comment]
Hi ymodak

I tried the answer from conradjones@ffdbaa2, which is at the end of  #34159 (comment) 
I got this error on compiling:

tensorflow/core/common_runtime/session_options.cc(22): error C2600: 'tensorflow::SessionOptions::SessionOptions': cannot define a compiler-generated special member function (must be declared in the class first)
Target //tensorflow:tensorflow.lib failed to build
INFO: Elapsed time: 31.668s, Critical Path: 20.50s
INFO: 116 processes: 116 local.
FAILED: Build did NOT complete successfully

**Comment by heyufei2008** [comment]
Hi Yasir
I will try your answer. Thanks.

**Comment by richaolas** [comment]
I get the same issue, it works ok in ubuntu18.04, but can't run in windows10.

**Comment by richaolas** [comment]
Thanks for https://github.com/conradjones/tensorflow/commit/ffdbaa25411340cf49b2eba8e180733340af61cd
I solve the problem with:
add 
#include "tensorflow/core/platform/macros.h" 
add TF_EXPORT:
**TF_EXPORT** Status Reset(const SessionOptions& options,
             const std::vector<string>& containers);
**TF_EXPORT** Session*  NewSession(const SessionOptions& options);

**Comment by heyufei2008** [comment]
Thanks

**Comment by ymodak** [comment]
Can we close this issue if it solved your problem? Thanks!

**Comment by richaolas** [comment]
TF2.0 & windows10 & VS2019 & /arch:AVX2
I am sorry, I don not think we can close the issue. Although I compile the .dll and .lib success, and have linked them without any error, but when I run the program which I just build, it crashed.
Anybody get the similar issue like this?...

**Comment by heyufei2008** [comment]
No, can  not close it yet.

**Comment by heyufei2008** [comment]
Hi Yasir
I think this is in a dangerous direction by adding TF_EXPORT to some functions.
What's your official solution to fix this issue completely?
Thanks

John

**Comment by heyufei2008** [comment]
I still have 2 unresolved external symbols:

unresolved external symbol "public: __cdecl tensorflow::ops::Placeholder::Placeholder(class tensorflow::Scope const &,enum

unresolved external symbol "public: __cdecl tensorflow::ops::Cast::Cast(class tensorflow::Scope const &,class tensorflow::Input,enum tensorflow::DataType

Where can I find the 2 functions ?

**Comment by heyufei2008** [comment]
@ymodak Hi Yasir 
Can you give me more help on this issue? I need tensorflow in windows. it's super urgent
John

**Comment by jgasperlin** [comment]
I have same issue:
- TensorFlow (v2.2) compiled using VS2019 and Bazel

Build with command:
`bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/lib_package:libtensorflow`

Output is then located on
- DLL => {PROEJCT_DIR}\tensorflow\bazel-bin\tensorflow\tensorflow.dll
- LIB =>{PROEJCT_DIR}\tensorflow\bazel-bin\tensorflow\libtensorflow.dll.ifso (renamed in project to tensorflow.lib)

It can link some symbols like:
`tensorflow::port::InitMain(argv[0], &argc, &argv);`
But can't link 
`tensorflow::NewSession(tensorflow::SessionOptions())`

**Comment by heyufei2008** [comment]
@ymodak we really need a good fix for this from Google.

**Comment by jgasperlin** [comment]
Any ETA on potential fix ?

**Comment by jgasperlin** [comment]
I found some instruction how to make it work on Windows 
https://github.com/sitting-duck/stuff/tree/master/ai/tensorflow/build_tensorflow_1.14_source_for_Windows

Problem is .dll is limited to 64k exported symbols.
As suggested by comment above is to use TF_EXPORT.
Other solution could be to exclude more non essential symbols in 
`tensorflow\tools\def_file_filter\def_file_filter.py.tpl`

**Comment by heyufei2008** [comment]
I need 2.0, my code in linux is based on 2.0

**Comment by heyufei2008** [comment]
Adding TF_EXPORT manually is risky.

**Comment by jgasperlin** [comment]
@heyufei2008 how so ?

**Comment by heyufei2008** [comment]
@jgasperlin 
Can you tell me how you made it work?
Thanks.

**Comment by jgasperlin** [comment]
@heyufei2008  
Just [follow](https://github.com/sitting-duck/stuff/tree/master/ai/tensorflow/build_tensorflow_1.14_source_for_Windows) and add necessary TF_EXPORT
i rebuild both dll and lib and used 
`bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/lib_package:libtensorflow`
And then checked they both exported `NewSession` and `SessionOptions`
`dumbbin /EXPORTS tensorflow.dll > dll-export.txt`
>23630 5C4D 06CCB8E0 ?NewSession@tensorflow@@YA?AVStatus@1@AEBUSessionOptions@1@PEAPEAVSession@1@@Z = ?NewSession@tensorflow@@YA?AVStatus@1@AEBUSessionOptions@1@PEAPEAVSession@1@@Z (class tensorflow::Status __cdecl tensorflow::NewSession(struct tensorflow::SessionOptions const &,class tensorflow::Session * *))

`dumbbin /EXPORTS tensorflow.lib > lib-export.txt`
>?NewSession@tensorflow@@YA?AVStatus@1@AEBUSessionOptions@1@PEAPEAVSession@1@@Z (class tensorflow::Status __cdecl tensorflow::NewSession(struct tensorflow::SessionOptions const &,class tensorflow::Session * *))

**Comment by heyufei2008** [comment]
@jgasperlin 
I did the same TF_EXPORT for NewSession and SessionOptions.

I still have 2 unresolved external symbols:

unresolved external symbol "public: __cdecl tensorflow::ops::Placeholder::Placeholder(class tensorflow::Scope const &,enum

unresolved external symbol "public: __cdecl tensorflow::ops::Cast::Cast(class tensorflow::Scope const &,class tensorflow::Input,enum tensorflow::DataType

I don't know where they are.

**Comment by jgasperlin** [comment]
@heyufei2008 most IDS if you click + ctrl on class it show you file that contains it or follow your includes or use docs https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/placeholder.
=> tensorflow\cc\ops\array_ops.h

**Comment by richaolas** [comment]
Although I compile the .dll and .lib success with the TF_EXPORT declaration, and have linked them without any error, but when I run the program which I just build, it crashed. Can you test it whether this method can work ok?
Thanks a lot.

**Comment by jgasperlin** [comment]
@richaolas 
https://github.com/tensorflow/tensorflow/issues/17778

**Comment by heyufei2008** [comment]
Hi Gens
I use the Cast class like this:
auto uint8Caster = Cast(root.WithOpName("uint8_Cast"), outTensor, tensorflow::DT_UINT8);

But Cast class is defined in math_ops.h, which is "// This file is MACHINE GENERATED! Do not edit."

How to add TF_EXPORT to class Cast ?

Thanks

**Comment by jeffhwang02** [comment]
TF_EXPORT can not solve this issue clearly, manual adding is painful and also could miss some other symbols. Bazel script for link needs to solve it.

**Comment by heyufei2008** [comment]
@jeffhwang02 Yes. it's still not fixed for me.
Do you know how to change Bazel script for this issue?

Thanks.

**Comment by jeffhwang02** [comment]
> @jeffhwang02 Yes. it's still not fixed for me.
> Do you know how to change Bazel script for this issue?
> 
> Thanks.

I have managed to make a tensorflow.dll which has no symbol error by using link again with some exported symbols def file.
But when it runs with my code, it still shows some another running time error.
So it still has not been solved clearly.

**Comment by starkovr** [comment]
> > @jeffhwang02 Yes. it's still not fixed for me.
> > Do you know how to change Bazel script for this issue?
> > Thanks.
> 
> I have managed to make a tensorflow.dll which has no symbol error by using link again with some exported symbols def file.
> But when it runs with my code, it still shows some another running time error.
> So it still has not been solved clearly.

hi @jeffhwang02 
Do you think you could please elaborate what exactly did you do to fix the issue with unresolved exported symbols? As you pointed out, manually adding `TF_EXPORT` is a bit tedious, but at least it's a viable workaround. Unfortunately, it does not appear to be working for certain symbols residing in machine-generated files, as mentioned here https://github.com/tensorflow/tensorflow/issues/35178, simply because rebuilding the `*.lib` file will regenerate the said files, removing any introduced modifications. An example of such symbol is `GraphDef` in `graph.pb.h`, which has the following statement at the top:
```
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/graph.proto
```

**Comment by jeffhwang02** [comment]
I solved the problem by using tf_exported_symbols_msvc.ids file in TF1.13 version now.
But newer tf1.15 does not work by the same method.
Anyway I am using the TF1.13 DLL in Windows10 which could be enough currently.
I hope some one could find more root solution for every version later.

**Comment by mabc666** [comment]
> TF2.0 & windows10 & VS2019 & /arch:AVX2 I am sorry, I don not think we can close the issue. Although I compile the .dll and .lib success, and have linked them without any error, but when I run the program which I just build, it crashed. Anybody get the similar issue like this?...
> 
> ```
>         tensorflow::SessionOptions session_options;
>         tensorflow::RunOptions run_options;
>         tensorflow::SavedModelBundle bundle;
>         tensorflow::Status status;
>         constexpr char kSavedModelTagServe[] = "serve";
> 
>         status = tensorflow::LoadSavedModel(session_options, run_options, model_path, { kSavedModelTagServe }, &bundle);
> ```
> 
> I got a exception: Unhandled exception at 0x00007FFC5DE93E49 in TensorflowTest.exe: Microsoft C++ exception: std::length_error at memory location 0x0000009852D5DF20.



> TF2.0 & windows10 & VS2019 & /arch:AVX2 I am sorry, I don not think we can close the issue. Although I compile the .dll and .lib success, and have linked them without any error, but when I run the program which I just build, it crashed. Anybody get the similar issue like this?...
> 
> ```
>         tensorflow::SessionOptions session_options;
>         tensorflow::RunOptions run_options;
>         tensorflow::SavedModelBundle bundle;
>         tensorflow::Status status;
>         constexpr char kSavedModelTagServe[] = "serve";
> 
>         status = tensorflow::LoadSavedModel(session_options, run_options, model_path, { kSavedModelTagServe }, &bundle);
> ```
> 
> I got a exception: Unhandled exception at 0x00007FFC5DE93E49 in TensorflowTest.exe: Microsoft C++ exception: std::length_error at memory location 0x0000009852D5DF20.

I got the same issue,did u slove it?
