### ISSUE TITLE
protobuf error from build

### ISSUE THREAD

**Issue by alanpurple** [tensorflow/tensorflow#26155]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04.2 x64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.13.1
- Python version: 3.7.2
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 0.21.0
- GCC/Compiler version (if compiling from source): 7.3.0
- CUDA/cuDNN version: 10.1 / 7.5
- GPU model and memory: RTX2080Ti GDDR6 11GB

**Describe the problem**

error during build

**Provide the exact sequence of commands / steps that you executed before running into the problem**

see log below

**Any other info / logs**

./tensorflow/core/framework/node_def_util.h:167:177:   required from here
external/protobuf_archive/src/google/protobuf/map.h:422:29: error: cannot call member function 'bool google::protobuf::Map<Key, T>::InnerMap::TableEntryIsNonEmptyList(google::protobuf::Map<Key, T>::size_type) const [with Key = std::__cxx11::basic_string<char>; T = tensorflow::AttrValue; google::protobuf::Map<Key, T>::size_type = long unsigned int]' without object
           if (m_->TableEntryIsNonEmptyList(bucket_index_)) {
           ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
external/protobuf_archive/src/google/protobuf/map.h:425:30: error: cannot call member function 'bool google::protobuf::Map<Key, T>::InnerMap::TableEntryIsTree(google::protobuf::Map<Key, T>::size_type) const [with Key = std::__cxx11::basic_string<char>; T = tensorflow::AttrValue; google::protobuf::Map<Key, T>::size_type = long unsigned int]' without object
           } else if (m_->TableEntryIsTree(bucket_index_)) {
              ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
external/protobuf_archive/src/google/protobuf/map.h: In instantiation of 'bool google::protobuf::Map<Key, T>::InnerMap::iterator_base<KeyValueType>::revalidate_if_necessary(google::protobuf::Map<Key, T>::InnerMap::TreeIterator*) [with KeyValueType = google::protobuf::Map<std::__cxx11::basic_string<char>, tensorflow::AttrValue>::KeyValuePair; Key = std::__cxx11::basic_string<char>; T = tensorflow::AttrValue; google::protobuf::Map<Key, T>::InnerMap::TreeIterator = std::_Rb_tree_const_iterator<std::__cxx11::basic_string<char>*>]':
external/protobuf_archive/src/google/protobuf/map.h:603:12:   required from 'void google::protobuf::Map<Key, T>::InnerMap::erase(google::protobuf::Map<Key, T>::InnerMap::iterator) [with Key = std::__cxx11::basic_string<char>; T = tensorflow::AttrValue; google::protobuf::Map<Key, T>::InnerMap::iterator = google::protobuf::Map<std::__cxx11::basic_string<char>, tensorflow::AttrValue>::InnerMap::iterator_base<google::protobuf::Map<std::__cxx11::basic_string<char>, tensorflow::AttrValue>::KeyValuePair>]'
external/protobuf_archive/src/google/protobuf/map.h:1132:1:   required from 'google::protobuf::Map<Key, T>::iterator google::protobuf::Map<Key, T>::erase(google::protobuf::Map<Key, T>::iterator) [with Key = std::__cxx11::basic_string<char>; T = tensorflow::AttrValue]'
external/protobuf_archive/src/google/protobuf/map.h:1137:14:   required from 'void google::protobuf::Map<Key, T>::erase(google::protobuf::Map<Key, T>::iterator, google::protobuf::Map<Key, T>::iterator) [with Key = std::__cxx11::basic_string<char>; T = tensorflow::AttrValue]'
external/protobuf_archive/src/google/protobuf/map.h:1140:21:   required from 'void google::protobuf::Map<Key, T>::clear() [with Key = std::__cxx11::basic_string<char>; T = tensorflow::AttrValue]'
external/protobuf_archive/src/google/protobuf/map_field_inl.h:178:1:   required from 'void google::protobuf::internal::MapField<Derived, Key, T, key_wire_type, value_wire_type, default_enum_value>::Clear() [with Derived = tensorflow::NameAttrList_AttrEntry_DoNotUse; Key = std::__cxx11::basic_string<char>; T = tensorflow::AttrValue; google::protobuf::internal::WireFormatLite::FieldType kKeyFieldType = (google::protobuf::internal::WireFormatLite::FieldType)9; google::protobuf::internal::WireFormatLite::FieldType kValueFieldType = (google::protobuf::internal::WireFormatLite::FieldType)11; int default_enum_value = 0]'
bazel-out/k8-opt/genfiles/tensorflow/core/framework/attr_value.pb.h:1785:15:   required from here
external/protobuf_archive/src/google/protobuf/map.h:484:29: error: cannot call member function 'bool google::protobuf::Map<Key, T>::InnerMap::TableEntryIsNonEmptyList(google::protobuf::Map<Key, T>::size_type) const [with Key = std::__cxx11::basic_string<char>; T = tensorflow::AttrValue; google::protobuf::Map<Key, T>::size_type = long unsigned int]' without object
         if (m_->TableEntryIsNonEmptyList(bucket_index_)) {
         ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
external/protobuf_archive/src/google/protobuf/map.h:498:24: error: cannot call member function 'bool google::protobuf::Map<Key, T>::InnerMap::TableEntryIsList(google::protobuf::Map<Key, T>::size_type) const [with Key = std::__cxx11::basic_string<char>; T = tensorflow::AttrValue; google::protobuf::Map<Key, T>::size_type = long unsigned int]' without object
         return m_->TableEntryIsList(bucket_index_);
         ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
external/protobuf_archive/src/google/protobuf/map.h: In instantiation of 'void google::protobuf::Map<Key, T>::InnerMap::iterator_base<KeyValueType>::SearchFrom(google::protobuf::Map<Key, T>::size_type) [with KeyValueType = google::protobuf::Map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >::KeyValuePair; Key = std::__cxx11::basic_string<char>; T = std::__cxx11::basic_string<char>; google::protobuf::Map<Key, T>::size_type = long unsigned int]':
external/protobuf_archive/src/google/protobuf/map.h:394:11:   required from 'google::protobuf::Map<Key, T>::InnerMap::iterator_base<KeyValueType>::iterator_base(const google::protobuf::Map<Key, T>::InnerMap*) [with KeyValueType = google::protobuf::Map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >::KeyValuePair; Key = std::__cxx11::basic_string<char>; T = std::__cxx11::basic_string<char>]'
external/protobuf_archive/src/google/protobuf/map.h:510:28:   required from 'google::protobuf::Map<Key, T>::InnerMap::iterator google::protobuf::Map<Key, T>::InnerMap::begin() [with Key = std::__cxx11::basic_string<char>; T = std::__cxx11::basic_string<char>; google::protobuf::Map<Key, T>::InnerMap::iterator = google::protobuf::Map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >::InnerMap::iterator_base<google::protobuf::Map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >::KeyValuePair>]'
external/protobuf_archive/src/google/protobuf/map.h:1030:27:   required from 'google::protobuf::Map<Key, T>::iterator google::protobuf::Map<Key, T>::begin() [with Key = std::__cxx11::basic_string<char>; T = std::__cxx11::basic_string<char>]'
external/protobuf_archive/src/google/protobuf/map.h:1140:27:   required from 'void google::protobuf::Map<Key, T>::clear() [with Key = std::__cxx11::basic_string<char>; T = std::__cxx11::basic_string<char>]'
external/protobuf_archive/src/google/protobuf/map_field_inl.h:178:1:   required from 'void google::protobuf::internal::MapField<Derived, Key, T, key_wire_type, value_wire_type, default_enum_value>::Clear() [with Derived = tensorflow::FunctionDef_RetEntry_DoNotUse; Key = std::__cxx11::basic_string<char>; T = std::__cxx11::basic_string<char>; google::protobuf::internal::WireFormatLite::FieldType kKeyFieldType = (google::protobuf::internal::WireFormatLite::FieldType)9; google::protobuf::internal::WireFormatLite::FieldType kValueFieldType = (google::protobuf::internal::WireFormatLite::FieldType)9; int default_enum_value = 0]'
bazel-out/k8-opt/genfiles/tensorflow/core/framework/function.pb.h:776:14:   required from here
external/protobuf_archive/src/google/protobuf/map.h:422:29: error: cannot call member function 'bool google::protobuf::Map<Key, T>::InnerMap::TableEntryIsNonEmptyList(google::protobuf::Map<Key, T>::size_type) const [with Key = std::__cxx11::basic_string<char>; T = std::__cxx11::basic_string<char>; google::protobuf::Map<Key, T>::size_type = long unsigned int]' without object
           if (m_->TableEntryIsNonEmptyList(bucket_index_)) {
           ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
external/protobuf_archive/src/google/protobuf/map.h:425:30: error: cannot call member function 'bool google::protobuf::Map<Key, T>::InnerMap::TableEntryIsTree(google::protobuf::Map<Key, T>::size_type) const [with Key = std::__cxx11::basic_string<char>; T = std::__cxx11::basic_string<char>; google::protobuf::Map<Key, T>::size_type = long unsigned int]' without object
           } else if (m_->TableEntryIsTree(bucket_index_)) {
              ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
external/protobuf_archive/src/google/protobuf/map.h: In instantiation of 'bool google::protobuf::Map<Key, T>::InnerMap::iterator_base<KeyValueType>::revalidate_if_necessary(google::protobuf::Map<Key, T>::InnerMap::TreeIterator*) [with KeyValueType = google::protobuf::Map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >::KeyValuePair; Key = std::__cxx11::basic_string<char>; T = std::__cxx11::basic_string<char>; google::protobuf::Map<Key, T>::InnerMap::TreeIterator = std::_Rb_tree_const_iterator<std::__cxx11::basic_string<char>*>]':
external/protobuf_archive/src/google/protobuf/map.h:603:12:   required from 'void google::protobuf::Map<Key, T>::InnerMap::erase(google::protobuf::Map<Key, T>::InnerMap::iterator) [with Key = std::__cxx11::basic_string<char>; T = std::__cxx11::basic_string<char>; google::protobuf::Map<Key, T>::InnerMap::iterator = google::protobuf::Map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >::InnerMap::iterator_base<google::protobuf::Map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >::KeyValuePair>]'
external/protobuf_archive/src/google/protobuf/map.h:1132:1:   required from 'google::protobuf::Map<Key, T>::iterator google::protobuf::Map<Key, T>::erase(google::protobuf::Map<Key, T>::iterator) [with Key = std::__cxx11::basic_string<char>; T = std::__cxx11::basic_string<char>]'
external/protobuf_archive/src/google/protobuf/map.h:1137:14:   required from 'void google::protobuf::Map<Key, T>::erase(google::protobuf::Map<Key, T>::iterator, google::protobuf::Map<Key, T>::iterator) [with Key = std::__cxx11::basic_string<char>; T = std::__cxx11::basic_string<char>]'
external/protobuf_archive/src/google/protobuf/map.h:1140:21:   required from 'void google::protobuf::Map<Key, T>::clear() [with Key = std::__cxx11::basic_string<char>; T = std::__cxx11::basic_string<char>]'
external/protobuf_archive/src/google/protobuf/map_field_inl.h:178:1:   required from 'void google::protobuf::internal::MapField<Derived, Key, T, key_wire_type, value_wire_type, default_enum_value>::Clear() [with Derived = tensorflow::FunctionDef_RetEntry_DoNotUse; Key = std::__cxx11::basic_string<char>; T = std::__cxx11::basic_string<char>; google::protobuf::internal::WireFormatLite::FieldType kKeyFieldType = (google::protobuf::internal::WireFormatLite::FieldType)9; google::protobuf::internal::WireFormatLite::FieldType kValueFieldType = (google::protobuf::internal::WireFormatLite::FieldType)9; int default_enum_value = 0]'
bazel-out/k8-opt/genfiles/tensorflow/core/framework/function.pb.h:776:14:   required from here
external/protobuf_archive/src/google/protobuf/map.h:484:29: error: cannot call member function 'bool google::protobuf::Map<Key, T>::InnerMap::TableEntryIsNonEmptyList(google::protobuf::Map<Key, T>::size_type) const [with Key = std::__cxx11::basic_string<char>; T = std::__cxx11::basic_string<char>; google::protobuf::Map<Key, T>::size_type = long unsigned int]' without object
         if (m_->TableEntryIsNonEmptyList(bucket_index_)) {
         ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
external/protobuf_archive/src/google/protobuf/map.h:498:24: error: cannot call member function 'bool google::protobuf::Map<Key, T>::InnerMap::TableEntryIsList(google::protobuf::Map<Key, T>::size_type) const [with Key = std::__cxx11::basic_string<char>; T = std::__cxx11::basic_string<char>; google::protobuf::Map<Key, T>::size_type = long unsigned int]' without object
         return m_->TableEntryIsList(bucket_index_);
         ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
ERROR: /home/wproject/repo/tensorflow/tensorflow/core/kernels/BUILD:3795:1: output 'tensorflow/core/kernels/_objs/topk_op_gpu/topk_op_gpu.cu.pic.o' was not created
ERROR: /home/wproject/repo/tensorflow/tensorflow/core/kernels/BUILD:3795:1: not all outputs were created or valid

**Comment by ymodak** [comment]
What version of protobuf are you using?
> pip show protobuf
Can you please switch to protobuf 3.6.0 if its other than that?

**Comment by alanpurple** [comment]
@ymodak 

3.6.1 of course and this has been worked with CUDA 10.0 and tf 1.13.0
https://anaconda.org/anaconda/protobuf

**Comment by leandro-gracia-gil** [comment]
I'm having this problem too. Same versions for protobuf, tf, cuda, cudnn, gcc, bazel and ubuntu. My python version is 3.7.0 instead of 3.7.2.

**Comment by leandro-gracia-gil** [comment]
Tried doing pip install protobuf==3.6.0 and building again, but the error is still there. It seems that the files raising the error are cuda kernels.

**Comment by wdirons** [comment]
Can you try the build with gcc 7.2.0 ? I also observed this issue in gcc 7.3.0 and not 7.2.0.

**Comment by leandro-gracia-gil** [comment]
Using gcc 7.2.0 seems to fix this specific problem, but getting that version might be not be very straightforward for Ubuntu 18.04 users. Furthermore, after the problem is fixed you get a linker error that can force you to disable XLA  (#24373).

Considering up-to-date Ubuntu 18.04 + CUDA 10.1 is likely to become a popular build environment, perhaps something should be done to avoid both this and #24373?


Full details:
I tried looking for a Ubuntu 18.04 package for gcc 7.2.0 but couldn't find any. The earliest I could find were all 7.3 versions. So, in an attempt to get that version while avoiding to screw up my current gcc environment, I gave a try to build the [source code](https://ftp.gnu.org/gnu/gcc/gcc-7.2.0/gcc-7.2.0.tar.gz) directly and make a separate install.

./configure --disable-multilib
make -j (num_cpus)
make DESTDIR=/tmp/gcc_7.2.0 install

Then I set /tmp/gcc_7.2.0/usr/local/bin/gcc as the gcc compiler to use with nvcc in TensorFlow's configure. With this I was able to compile the CUDA kernels that were failing, but then I hit the linker error of #24373 at the very end of the build. After disabling XLA I was able to get a working build.

**Comment by wdirons** [comment]
@leandro-gracia-gil , thank you for confirming you saw the same issue as me and my co-worker. When I first saw this the only thing that had changed in my environment was cuDNN 7.5. My co-worker opened a bug against NVIDIA for this problem. That bug is not publicly viewable, but last I knew NVIDIA has not commented on it yet. If the problem is in cuDNN, I would hope NVIDIA provides a fix for it.

**Comment by leandro-gracia-gil** [comment]
@wdirons I'm not that sure that this problem is on the NVIDIA side. It could also be a gcc or a protobuf issue, considering it fails depending on the gcc version and on protobuf headers. I also tried using clang to build the CUDA kernels, but hit other problems.

**Comment by gunan** [comment]
To me this looks to be a protobuf bug. Could you file an issue on protobuf repository too, and link this issue?
They may have a better idea about what we are running into.

**Comment by alanpurple** [comment]
@gunan 
I did

**Comment by rongou** [comment]
I fixed a similar problem by using gcc 6. You can follow the instructions here (https://askubuntu.com/questions/26498/how-to-choose-the-default-gcc-and-g-version), so it shouldn't be too hard to try on ubuntu 18.04.

**Comment by alanpurple** [comment]
@rongou maybe it's not too hard, but I don't think it is a good idea to downgrade which is even below the system-default version

**Comment by rongou** [comment]
I'm not saying it's a long term solution, just a temporary workaround.

**Comment by placidchat** [comment]
i have the same problem as well. Using python 3.6.7. For some reason, the compiler thinks m_ InnerMap is  called by a non object. But protobuf compiles fine by itself, just not the protobuf_archive together with the tensorflow bazel build system.

**Comment by rongou** [comment]
This is a known bug in CUDA 10.1 (together with gcc 7.3+). You can either downgrade to CUDA 10.0 or gcc 6/7.2, whichever is easier.

**Comment by artur-braga** [comment]
Hello, 
i have the same problem and given the current setup and dependencies I cannot downgrade neither of both softwares. 
Does anyone have another suggestion?

**Comment by rongou** [comment]
Another option is to patch the protobuf code to derefence the pointer first:
```cpp
if ((*m_).TableEntryIsNonEmptyList(bucket_index)) {
```
like what we did [here](https://github.com/dmlc/xgboost/pull/4223#issuecomment-470476672), but if you can't change your CUDA/gcc versions, I'm not sure if this is easier. :)

**Comment by edrozenberg** [comment]
Thanks to @rongou for inspiring a temporary workaround. The actual steps involved were quite a bit more work to figure out. First I tried patching and installing the latest protobuf 3.7.0. Turns out Tensorflow does not use the protobuf package installed on the system - instead, it downloads its own protobuf from a URL listed in the tensorflow source code under `tensorflow/workspace.bzl`.

Steps:
- Download protobuf source listed in `tensorflow/workspace.bzl` (current value is `https://mirror.bazel.build/github.com/protocolbuffers/protobuf/archive/v3.6.1.2.tar.gz`)
- Untar the protobuf source and patch `src/google/protobuf/map.h as follows`:

```
--- map.h	2019-03-25 19:50:24.000000000 -0700
+++ map.h.orig	2019-03-25 19:47:03.000000000 -0700
@@ -419,10 +419,10 @@
         node_ = NULL;
         for (bucket_index_ = start_bucket; bucket_index_ < m_->num_buckets_;
              bucket_index_++) {
-          if ((*m_).TableEntryIsNonEmptyList(bucket_index_)) {
+          if (m_->TableEntryIsNonEmptyList(bucket_index_)) {
             node_ = static_cast<Node*>(m_->table_[bucket_index_]);
             break;
-          } else if ((*m_).TableEntryIsTree(bucket_index_)) {
+          } else if (m_->TableEntryIsTree(bucket_index_)) {
             Tree* tree = static_cast<Tree*>(m_->table_[bucket_index_]);
             GOOGLE_DCHECK(!tree->empty());
             node_ = NodePtrFromKeyPtr(*tree->begin());
@@ -481,7 +481,7 @@
           return true;
         // Less common: the bucket is a linked list with node_ somewhere in it,
         // but not at the head.
-        if ((*m_).TableEntryIsNonEmptyList(bucket_index_)) {
+        if (m_->TableEntryIsNonEmptyList(bucket_index_)) {
           Node* l = static_cast<Node*>(m_->table_[bucket_index_]);
           while ((l = l->next) != NULL) {
             if (l == node_) {
@@ -495,7 +495,7 @@
         // find-like method that compares Node* instead of const Key&.
         iterator_base i(m_->find(*KeyPtrFromNodePtr(node_), it));
         bucket_index_ = i.bucket_index_;
-        return (*m_).TableEntryIsList(bucket_index_);
+        return m_->TableEntryIsList(bucket_index_);
       }
 
       Node* node_;
```
- Re-tar the protobuf source to a name such as v3.6.1.2_patched.tar.gz
- Place the patched protobuf source on an https server you control
- Back to the Tensorflow source, modify `tensorflow/workspace.bzl` to point to your own server and patched protobuf source. Modify both protobuf URL's and the sha256 value as appropriate for your patched source:

```
PROTOBUF_URLS = [
        "https://myserver.something/software/linux/development/protobuf/v3.6.1.2_patched.tar.gz",
        "https://myserver.something/software/linux/development/protobuf/v3.6.1.2_patched.tar.gz",
    ]
    PROTOBUF_SHA256 = "11111222233333value-for-your-patched-source-tarball"
```

Before restarting the Tensorflow build, you may need to do a `bazel clean` and a `bazel shutdown`. To be extra sure old stuff won't be left around, also consider cleaning ~/.cache/bazel where all the bazel cached downloads (such as the protobuf source) are stored.

**Comment by edrozenberg** [comment]
This was not easy but it was better than having to downgrade CUDA or gcc, neither of which are easy to do either:
- Tried to use CUDA 10.0 but its installer failed because it doesn't support gcc 8
- Trying to downgrade the OS-shipped gcc 8.3 to something else causes many other issues
- Building and installing an additional gcc 7 in a location such as /opt/gcc works but requires passing a bunch of compile flags as env variables when building various software packages that use CUDA libraries (tensorflow, caffe2, etc). Otherwise the CUDA 10.0(<) stuff will still use the default gcc8 and crap out.

**Comment by wdirons** [comment]
@edrozenberg , you should be able to simplify the above steps by just adding a patch file to the existing protobuf entry in workspace.bzl. 

See this example:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/workspace.bzl#L612

**Comment by edrozenberg** [comment]
@wdirons thanks! Sounds like a good way to go once I figure out where to put the patch file for it to be found. bazel/tensorflow leave a lot of things as exercises for the reader ("just read the source code to figure it out") :sweat_smile:

**Comment by wdirons** [comment]
@edrozenberg, here is how:
```
git clone -b v3.6.1.2 https://github.com/protocolbuffers/protobuf
cd protobuf/
vi src/google/protobuf/map.h
git diff > 26155.patch
```
and copy the file to third_party/protobuf

I'm wondering if your patch should be submitted a PR to resolve this issue ?

**Comment by kgizdov** [comment]
All that is needed is the following:
```patch
# protobuf_temp_fix_cuda10.1_apply.patch
diff --git a/tensorflow/workspace.bzl b/tensorflow/workspace.bzl
index dff151246a..d3fe95ec04 100755
--- a/tensorflow/workspace.bzl
+++ b/tensorflow/workspace.bzl
@@ -349,11 +349,11 @@ def tf_workspace(path_prefix = "", tf_repo_name = ""):
     )
 
     PROTOBUF_URLS = [
-        "https://mirror.bazel.build/github.com/protocolbuffers/protobuf/archive/v3.6.1.2.tar.gz",
-        "https://github.com/protocolbuffers/protobuf/archive/v3.6.1.2.tar.gz",
+        "https://mirror.bazel.build/github.com/protocolbuffers/protobuf/archive/v3.6.1.3.tar.gz",
+        "https://github.com/protocolbuffers/protobuf/archive/v3.6.1.3.tar.gz",
     ]
-    PROTOBUF_SHA256 = "2244b0308846bb22b4ff0bcc675e99290ff9f1115553ae9671eba1030af31bc0"
-    PROTOBUF_STRIP_PREFIX = "protobuf-3.6.1.2"
+    PROTOBUF_SHA256 = "73fdad358857e120fd0fa19e071a96e15c0f23bb25f85d3f7009abfd4f264a2a"
+    PROTOBUF_STRIP_PREFIX = "protobuf-3.6.1.3"
 
     tf_http_archive(
         name = "protobuf_archive",
@@ -364,6 +364,7 @@ def tf_workspace(path_prefix = "", tf_repo_name = ""):
             "//third_party/systemlibs:protobuf.bzl": "protobuf.bzl",
         },
         urls = PROTOBUF_URLS,
+        patch_file = clean_dep("//third_party:protobuf_temp_fix_cuda10.1.patch"),
     )
 
     # We need to import the protobuf library under the names com_google_protobuf
@@ -378,6 +379,7 @@ def tf_workspace(path_prefix = "", tf_repo_name = ""):
             "//third_party/systemlibs:protobuf.bzl": "protobuf.bzl",
         },
         urls = PROTOBUF_URLS,
+        patch_file = clean_dep("//third_party:protobuf_temp_fix_cuda10.1.patch"),
     )
 
     tf_http_archive(
@@ -389,6 +391,7 @@ def tf_workspace(path_prefix = "", tf_repo_name = ""):
             "//third_party/systemlibs:protobuf.bzl": "protobuf.bzl",
         },
         urls = PROTOBUF_URLS,
+        patch_file = clean_dep("//third_party:protobuf_temp_fix_cuda10.1.patch"),
     )
 
     tf_http_archive(
```
```patch
# protobuf_temp_fix_cuda10.1.patch
diff --git a/src/google/protobuf/map.h b/src/google/protobuf/map.h
index 40f35e92..1af91f9c 100644
--- a/src/google/protobuf/map.h
+++ b/src/google/protobuf/map.h
@@ -425,10 +425,10 @@ class Map {
         node_ = NULL;
         for (bucket_index_ = start_bucket; bucket_index_ < m_->num_buckets_;
              bucket_index_++) {
-          if (m_->TableEntryIsNonEmptyList(bucket_index_)) {
+          if ((*m_).TableEntryIsNonEmptyList(bucket_index_)) {
             node_ = static_cast<Node*>(m_->table_[bucket_index_]);
             break;
-          } else if (m_->TableEntryIsTree(bucket_index_)) {
+          } else if ((*m_).TableEntryIsTree(bucket_index_)) {
             Tree* tree = static_cast<Tree*>(m_->table_[bucket_index_]);
             GOOGLE_DCHECK(!tree->empty());
             node_ = NodePtrFromKeyPtr(*tree->begin());
@@ -487,7 +487,7 @@ class Map {
           return true;
         // Less common: the bucket is a linked list with node_ somewhere in it,
         // but not at the head.
-        if (m_->TableEntryIsNonEmptyList(bucket_index_)) {
+        if ((*m_).TableEntryIsNonEmptyList(bucket_index_)) {
           Node* l = static_cast<Node*>(m_->table_[bucket_index_]);
           while ((l = l->next) != NULL) {
             if (l == node_) {
@@ -501,7 +501,7 @@ class Map {
         // find-like method that compares Node* instead of const Key&.
         iterator_base i(m_->find(*KeyPtrFromNodePtr(node_), it));
         bucket_index_ = i.bucket_index_;
-        return m_->TableEntryIsList(bucket_index_);
+        return (*m_).TableEntryIsList(bucket_index_);
       }
 
       Node* node_;
```
```bash
$ patch -d tensorflow-1.13.1 -Np1 -i tensorflow/protobuf_temp_fix_cuda10.1_apply.patch
$ cp protobuf_temp_fix_cuda10.1.patch tensorflow-1.13.1/third_party/
$ cd tensorflow-1.13.1
$ bazel build ...
```
To upgrade to `protobuf 3.7.x` one needs a bigger change to build environment as `skylib` build options have significantly changed.

**Comment by edrozenberg** [comment]
@kgizdov Thanks for your excellent step-by-step guide! I will try it soon. Having done the builds already the hard way, it will be nice to do them again the easy way.

**Comment by kgizdov** [comment]
I can confirm successful build with this workaround for GCC 7.4.1, with and without CUDA 10.1.

**Comment by kgizdov** [comment]
Also, builds fine with GCC 8.2.1, with and without CUDA 10.1

**Comment by objectiveinteraction** [comment]
Isn't m_->func equivalent to (*m).func ? Or did some standard change somewhere?

**Comment by svenstaro** [comment]
> Isn't m_->func equivalent to (*m).func ? Or did some standard change somewhere?

It is, but nvcc doesn't think so.

**Comment by artur-braga** [comment]
All builds fine here as well, cuda 10.1 and GCC7.3.0 on aarch64. Thank you for your help!

**Comment by cya410** [comment]
@kgizdov just tried the work around. It seems that the link "https://mirror.bazel.build/github.com/protocolbuffers/protobuf/archive/v3.6.1.3.tar.gz" isn't working?

**Comment by kgizdov** [comment]
@objectiveinteraction it's not equivalent under the hood:
```
class A {
  int const foo(int b) {return b;}
  int const bar(int b) {c+=b; return c;}
  // foo. bar have hidden parameter 'this', the class instance
private:
  int c{1};
}
A *a = nullptr;
int b{2};
a->foo(b);    // == A::foo( a, b) == return 2;
(*a).foo(b);  // == A::foo(*a, b) == undefined behavior
a->bar(b);   // == type(*nullptr)::foo(a, b) == *this.c+b == seg fault
/// this is simplified of course, but explains the difference
```
The root problem seems to be somewhere in CUDA the vtable is malformed (probably broken inheritance) and that lead to GCC not being able to find `A::foo()`. So we need to derefence `*a` to find the function and call it. That invites undefined behaviour in some cases, but is the only working patch at the moment. I am, however, seeing a lot of warnings from CUDA that tensorflow/protobuf includes internal CUDA headers instead of `cuda.h` and that could be it, in terms of broken inheritance.

@cya410 if you applied the whole patch, then bazel will automatically use the GitHub link when the other is unavailable. You may be suffering from bad connection to GitHub or something. It's a known issue and @svenstaro has a year-long standing issue to allow tensorflow/bazel to link to locally installed libraries, but no one from the devs seems to be working on it. Until then, all builds depend on stable network connection.

**Comment by objectiveinteraction** [comment]
Strange, looking through map.h, it seemed like m was an innermap that would've have been just a pointer. I was expecting it to be eventually pointing to an valid innermap, which was why i never considered (*m).func to be a possibility. Compiling protobuf by itself didn't generate any issues. So i'd assumed the problem was with the linking step of tensorflow and cuda.  Great find and explanation @kgizdov 
bazel itself is very noisy on the network.

**Comment by wdirons** [comment]
This problem with the nvcc compiler should be fixed with the nvidia gpu driver version 418.67

**Comment by rongou** [comment]
This problem is not tied to the gpu driver. It's the cuda compiler version. Should be fixed if you are on 10.1.168.
```shell
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Apr_24_19:10:27_PDT_2019
Cuda compilation tools, release 10.1, V10.1.168
```

**Comment by alanpurple** [comment]
yeap, as @rongou  said, this has been fixed, closing

**Comment by lwind18** [comment]
Dose anyone have the same issue with Mac system? I run into the same problem when using Mac, and don't know how to solve this. I know it is the tensorflow (1.13.1) and protobuf (3.8) problems. But how to fix it in Mac system?
