### PR TITLE
Fix crash of GFile in python 3.7

### LINKED ISSUE #27276: Crash when opening .npz file with tf.gfile.GFile on Python 3.7
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary (pip)
- TensorFlow version (use command below): v1.13.0-rc2-5-g6612da8 / 1.13.1
- Python version: Python 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1 / 7.5.0
- GPU model and memory: GTX 1080 / 8G

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
A code below works well on Python 3.6 with TF 1.12. On Python 3.7 with TF 1.13, however, the code crashes. 

**Describe the expected behavior**

Do not crash.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```Python
import numpy as np
import tensorflow as tf

information = { "a": 1, "b": 2 }
np.savez_compressed("a.npz", **information)

with tf.gfile.Open("a.npz", "rb") as file_:
  info = np.load(file_)

info_dict = { key: info[key] for key in info.items() }  # crash on Python 3.7 with TF 1.13.1
```

Traceback 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <dictcomp>
  File "/csehome/youhanmir/.virtualenvs/learning-implicit-action/lib/python3.7/_collections_abc.py", line 744, in __iter__
    yield (key, self._mapping[key])
  File "/csehome/youhanmir/.virtualenvs/learning-implicit-action/lib/python3.7/site-packages/numpy/lib/npyio.py", line 251, in __getitem__
    bytes = self.zip.open(key)
  File "/usr/lib64/python3.7/zipfile.py", line 1480, in open
    self._fpclose, self._lock, lambda: self._writing)
  File "/usr/lib64/python3.7/zipfile.py", line 722, in __init__
    self.seekable = file.seekable
AttributeError: 'GFile' object has no attribute 'seekable'
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

### PR DESCRIPTION
**Pull request by yongtang**
This fix tries to address the issue raised in #27276 where in Python 3.7, opening a zip file (of GFile) will results in the error of
```
    bytes = self.zip.open(key)
  File "/usr/lib64/python3.7/zipfile.py", line 1480, in open
    self._fpclose, self._lock, lambda: self._writing)
  File "/usr/lib64/python3.7/zipfile.py", line 722, in __init__
    self.seekable = file.seekable
AttributeError: 'GFile' object has no attribute 'seekable'
```

The issue is that Python 3.7 adds seekable check:
https://github.com/python/cpython/commit/066df4fd454d6ff9be66e80b2a65995b10af174f

This fix adds `seekable()` and returns True, as GFile is indeed seekable.

This fix fixes #27276

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Review by annarev — DISMISSED** [review]
Thank you for the fix!

**Comment by annarev** [comment]
Can you update api_compatibility_test goldens as well? That test is failing now because 'seekable' is a new method added in the API.
See instructions here to update goldens: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/api/tests

**Comment by yongtang** [comment]
Thanks @annarev for the review. The api goldens has been updated.

**Review by annarev — DISMISSED** [review]

File: tensorflow/python/lib/io/file_io.py [hunk 1]
```diff
@@ -246,6 +246,10 @@ def close(self):
         pywrap_tensorflow.Set_TF_Status_from_Status(status, ret_status)
     self._writable_file = None
 
+  def seekable(self):
```
Comment (alextp) [inline tensorflow/python/lib/io/file_io.py]: This should be a @property

**Review by alextp — APPROVED** [review]

File: tensorflow/python/lib/io/file_io.py (hunk 1 above)
Comment (Corea) [reply tensorflow/python/lib/io/file_io.py]: Actually it should not be a property, because [`zipfile` calls `fileobj.seekable()`](https://github.com/python/cpython/commit/066df4fd454d6ff9be66e80b2a65995b10af174f#diff-30e3ce7dc73ea0f34b323c729c652a08R798). This code still doesn't work. :sob:

Could you fix this problem with other PR again? @yongtang
