### ISSUE TITLE
ImportError: No module named nn.rnn

### ISSUE THREAD

**Issue by kevinashaw** [tensorflow/tensorflow#6973]
I'm having trouble accessing the rnn models.  The following commands:
```
import tensorflow as tf
from tensorflow.nn.rnn import rnn, rnn_cell
```
yield the following error:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-f6712a17b199> in <module>()
----> 1 from tensorflow.nn.rnn import rnn, rnn_cell

ImportError: No module named nn.rnn
```
And the line:
```
lstm_cell_1 = tf.nn.rnn_cell.BasicLSTMCell(n_hidden)
```
yields:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-f0f106c78703> in <module>()
----> 1 lstm_cell_1 = tf.nn.rnn_cell.BasicLSTMCell(n_hidden)

AttributeError: 'module' object has no attribute 'rnn_cell'

```
The version is  `'0.12.head'` and I'm working on MacOS 10.12.2.  I'm working off git hash #7c16e2e23.
I have been following the commentary in [#2685](https://github.com/tensorflow/tensorflow/issues/2685) and others.
First, I installed setuptools:
```
pip install --upgrade -I setuptools
```
and then the latest python:
```
pip install --ignore-installed --upgrade tensorflow-0.12.1-py2-none-any.whl 
```
Is this a real issue, or a problem with my setup?

**Comment by kevinashaw** [comment]
Thanks again!  -K
