### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'Session'

### ISSUE THREAD

**Issue by oroojlooy** [tensorflow/tensorflow#18538]
When I call any function in python3.6, I get the error below; however, it works fine in python3.4. Any idea? 
import tensorflow as tf 
tf.Session()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'Session'
>>> 
Here is my  System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian 8.7 
- **TensorFlow installed from (source or binary)**: by pip3
- **TensorFlow version (use command below)**: 1.7.0
- **Python version**: 3.6.5
- **CUDA/cuDNN version**: cuda 9.0 and cudnn 7.0
- **GPU model and memory**: K80, 12 GB 
- **Exact command to reproduce**:
import tensorflow as tf 
tf.Session()

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
Bazel version

**Comment by oroojlooy** [comment]
Have I written custom code: Yes. But I get the error in either of the codes in tensorflow models. 
Bazel version: I did not install tensorflow from source, so I did not install Bazel.

**Comment by 43061b4a** [comment]
Try reinstalling or upgrading tensorflow-gpu.

`pip install --upgrade tensorflow-gpu`

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yifeif: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yifeif: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yifeif: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by aznshodan** [comment]
`pip3 install --upgrade --force-reinstall tensorflow-gpu` worked for me

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yifeif: It has been 16 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yifeif: It has been 31 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by yifeif** [comment]
@oroojlooy is this still an issue for you? Could you check if there is tensorflow folder or tensorflow.py from where you were seeing the error?

**Comment by oroojlooy** [comment]
@yifeif No, I installed a newer version of Python3.6, then installed tensorflow and it works.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yifeif: It has been 20 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yifeif: It has been 36 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yifeif: It has been 51 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yifeif: It has been 66 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by oroojlooy** [comment]
I close the issue.

**Comment by Him010** [comment]
Can someone help me? I am getting the same issue.
I have already tried both ways as told by 43061b4a and aznshodan but the problem still persists.

**Comment by mihaimaruseac** [comment]
Please open a new issue, filling in the template.

Note that 1.7 is very old and outside of support window. You should consider using 2.0 in which case Session is no longer needed.

**Comment by Him010** [comment]
thanks @mihaimaruseac 
I was encountering this on Tensorflow 2.0 only.

As i am enrolled in a bootcamp so they are teaching us using previous version but in my PC i was getting error as I didn't know that 2.0 don't support Session.

Note:Sorry for grammatical mistakes.

**Comment by NyaaGitty** [comment]
I solved this problem by unistall the tensorflow，and install tensorflow by this "conda create -n tensorflow_env tensorflow"

**Comment by ChanasitGithub** [comment]
I'm also encountering this problem on Tensorflow 2.0 . I have no Anaconda install, tensorflow 2 installed in local env of Windows10.

**Comment by Smsmadly** [comment]
If tf.Session() is deprecated, Please use **tf.compat.v1.Session()** instead

**Comment by rj1346** [comment]
> If tf.Session() is deprecated, Please use **tf.compat.v1.Session()** instead

sess.run() is not working. is there any alternative?

**Comment by shikharmay7** [comment]
> sess= tf.compat.v1.Session()
> sess.run() is not working. its saying, "The Session graph is empty. Add operations to the graph before calling run()"

@rj1346 try the following it worked for me

import tensorflow as tf
with tf.compat.v1.Session() as sess:
    a = tf.constant(3.0)
    b = tf.constant(4.0)
    c = a+b
    print(sess.run(c))
    sess.close()

**Comment by prakhar28sharma** [comment]
> > If tf.Session() is deprecated, Please use **tf.compat.v1.Session()** instead
> 
> sess= tf.compat.v1.Session()
> sess.run() is not working. its saying, "The Session graph is empty. Add operations to the graph before calling run()"

you are getting this error because of the indentation

**Comment by eduamf** [comment]
Same error using ELMo. It seems solved using tensorflow==1.15, that includes CPU and GPU packages.

**Comment by mihaimaruseac** [comment]
Guys, this issue is solved and for a very old version of TF. Please open new issue, no one is really watching the closed issues

**Comment by andrei1887** [comment]
Good thread for noobies like me. Was following some old doccos on how to use Tf and stumbled into this issue. Mihai, you helped a lot. Merci si sanatate!

**Comment by chiweii** [comment]
tensorflow 2.x 

import tensorflow as tf
hello = tf.constant('Hello, TensorFlow!')
sess = tf.Session()
print(sess.run(hello))

**Comment by mihaimaruseac** [comment]
There is no session in TF 2.x.

Locking conversation as this has been already answered multiple times.
