### ISSUE TITLE
CMAKE+CPU on Ubuntu 18.04 build failure

### ISSUE THREAD

**Issue by yongtang** [tensorflow/tensorflow#19353]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: N/A
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: master 51ef16057b4625e0a3e2943a9f1bbf856cf098ca
- **Python version**: 3.6.5
- **Bazel version (if compiling from source)**: 0.13.0 (Irrelevant)
- **GCC/Compiler version (if compiling from source)**: 7.3.0
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**:
```
$ mkdir build && cd build
$ cmake -DCMAKE_BUILD_TYPE=Release ../tensorflow/contrib/cmake
$ make -j 4

```

### Describe the problem

While trying to build tensorflow with cmake (CPU only) it looks like build is broken. From the log it seems that there are some eager dependency issues. 

### Source code / logs

```
# mkdir build && cd build
# cmake -DCMAKE_BUILD_TYPE=Release ../tensorflow/contrib/cmake
# make -j 4

[ 99%] Building CXX object CMakeFiles/summarize_graph.dir/home/ubuntu/tensorflow/tensorflow/tools/graph_transforms/summarize_graph_main.cc.o
[ 99%] Linking CXX executable summarize_graph
CMakeFiles/tf_core_cpu.dir/home/ubuntu/tensorflow/tensorflow/core/common_runtime/eager/eager_operation.cc.o: In function `tensorflow::EagerOperation::AddInput(tensorflow::TensorHandle*)':
eager_operation.cc:(.text+0x23b): undefined reference to `tensorflow::AttrBuilder::NumInputs(int)'
CMakeFiles/tf_core_cpu.dir/home/ubuntu/tensorflow/tensorflow/core/common_runtime/eager/execute.cc.o: In function `tensorflow::EagerExecute(tensorflow::EagerOperation*, tensorflow::gtl::InlinedVector<tensorflow::TensorHandle*, 2>*, int*)':
execute.cc:(.text+0x2bf4): undefined reference to `tensorflow::AttrBuilder::CacheKey(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
execute.cc:(.text+0x32f4): undefined reference to `tensorflow::AttrBuilder::BuildNodeDef()'
execute.cc:(.text+0x4e3a): undefined reference to `tensorflow::OpDefForOp(char const*, tensorflow::OpDef const**)'
collect2: error: ld returned 1 exit status
CMakeFiles/summarize_graph.dir/build.make:2164: recipe for target 'summarize_graph' failed
make[2]: *** [summarize_graph] Error 1
CMakeFiles/Makefile2:2214: recipe for target 'CMakeFiles/summarize_graph.dir/all' failed
make[1]: *** [CMakeFiles/summarize_graph.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by tensorflowbutler** [comment]
Nagging Assignee @skye: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by yongtang** [comment]
I tried to build with CMAKE again on Ubuntu 18.04 and now it works. Thanks!
