### ISSUE TITLE
Build of tensorflow==1.12.0 on broadwell fails

### ISSUE THREAD

**Issue by ziky90** [tensorflow/tensorflow#23554]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.12.0
- Python version: 3.6.5
- Installed using virtualenv? pip? conda?: no
- Bazel version (if compiling from source): 0.19.0
- GCC/Compiler version (if compiling from source): 7.3
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**
I'm unable to build tensorflow for CPU from source.
I'm using command `bazel build --verbose_failures -c opt --copt=-march=native --copt=-mfpmath=both -k //tensorflow/tools/pip_package:build_pip_package`
For tensorflow==1.12.0 I'm getting:
```
INFO: From Compiling tensorflow/contrib/lite/toco/import_tensorflow.cc:
In file included from external/gemmlowp/fixedpoint/fixedpoint.h:874:0,
                 from ./tensorflow/contrib/lite/kernels/internal/common.h:48,
                 from ./tensorflow/contrib/lite/toco/runtime/types.h:18,
                 from ./tensorflow/contrib/lite/toco/model.h:28,
                 from ./tensorflow/contrib/lite/toco/import_tensorflow.h:20,
                 from tensorflow/contrib/lite/toco/import_tensorflow.cc:15:
external/gemmlowp/fixedpoint/./fixedpoint_sse.h:43:39: warning: ignoring attributes on template argument '__m128i {aka __vector(2) long long int}' [-Wignored-attributes]
 struct FixedPointRawTypeTraits<__m128i> {
                                       ^
INFO: From Compiling tensorflow/python/framework/fast_tensor_util.cpp:
In file included from bazel-out/k8-fastbuild/genfiles/external/local_config_python/numpy_include/numpy/ndarraytypes.h:1821:0,
                 from bazel-out/k8-fastbuild/genfiles/external/local_config_python/numpy_include/numpy/ndarrayobject.h:18,
                 from bazel-out/k8-fastbuild/genfiles/external/local_config_python/numpy_include/numpy/arrayobject.h:4,
                 from bazel-out/k8-fastbuild/genfiles/tensorflow/python/framework/fast_tensor_util.cpp:581:
bazel-out/k8-fastbuild/genfiles/external/local_config_python/numpy_include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^~~~~~~
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 4582.121s, Critical Path: 791.83s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 7555 processes: 4 local, 7551 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
export CC_OPT_FLAGS="-march=native"
./configure
bazel build -c opt --copt=-march=native --copt=-mfpmath=both -k //tensorflow/tools/pip_package:build_pip_package
```

I'm trying this on the GCE, 32 core broadwell machine in the `us-central1-f` zone.

**Any other info / logs**
I've also tried to build the package by:
```
export CC_OPT_FLAGS="-march=native"
./configure
bazel build --verbose_failures --config=opt -k //tensorflow/tools/pip_package:build_pip_package
```
Getting exactly the sameproblem.

**EDIT:**
I've tried exactly the same bazel build command with tensorflow==1.11.0 and everything works well. Unfortunately I'd like to use tensorflow==1.12.0 this way. Are there some specific things I've to change for building tensorflow==1.12.0?

**EDIT2:**
After a bit of searching and trying different stuff, such as installing `libc-ares-dev`. I was able to find in the stack trace following error:
```
ERROR: /tensorflow/tensorflow/python/BUILD:3865:1: Linking of rule '//tensorflow/python:_pywrap_tensorflow_internal.so' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -shared -o bazel-out/host/bin/tensorflow/python/_pywrap_tensorflow_internal.so -Wl,--version-script bazel-out/host/bin/tensorflow/python/pywrap_tensorflow_internal_versionscript.lds ... (remaining 66 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
/usr/bin/ld.gold: error: bazel-out/host/bin/external/grpc/_objs/grpc_nanopb/pb_common.pic.o: multiple definition of 'pb_field_iter_begin'
/usr/bin/ld.gold: bazel-out/host/bin/external/grpc/third_party/nanopb/_objs/nanopb/pb_common.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/grpc/_objs/grpc_nanopb/pb_common.pic.o: multiple definition of 'pb_field_iter_next'
/usr/bin/ld.gold: bazel-out/host/bin/external/grpc/third_party/nanopb/_objs/nanopb/pb_common.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/grpc/_objs/grpc_nanopb/pb_common.pic.o: multiple definition of 'pb_field_iter_find'
/usr/bin/ld.gold: bazel-out/host/bin/external/grpc/third_party/nanopb/_objs/nanopb/pb_common.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/grpc/_objs/grpc_nanopb/pb_decode.pic.o: multiple definition of 'pb_read'
/usr/bin/ld.gold: bazel-out/host/bin/external/grpc/third_party/nanopb/_objs/nanopb/pb_decode.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/grpc/_objs/grpc_nanopb/pb_decode.pic.o: multiple definition of 'pb_istream_from_buffer'
/usr/bin/ld.gold: bazel-out/host/bin/external/grpc/third_party/nanopb/_objs/nanopb/pb_decode.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/grpc/_objs/grpc_nanopb/pb_decode.pic.o: multiple definition of 'pb_decode_varint'
/usr/bin/ld.gold: bazel-out/host/bin/external/grpc/third_party/nanopb/_objs/nanopb/pb_decode.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/grpc/_objs/grpc_nanopb/pb_decode.pic.o: multiple definition of 'pb_decode_tag'
/usr/bin/ld.gold: bazel-out/host/bin/external/grpc/third_party/nanopb/_objs/nanopb/pb_decode.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/grpc/_objs/grpc_nanopb/pb_decode.pic.o: multiple definition of 'pb_skip_field'
/usr/bin/ld.gold: bazel-out/host/bin/external/grpc/third_party/nanopb/_objs/nanopb/pb_decode.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/grpc/_objs/grpc_nanopb/pb_decode.pic.o: multiple definition of 'pb_make_string_substream'
/usr/bin/ld.gold: bazel-out/host/bin/external/grpc/third_party/nanopb/_objs/nanopb/pb_decode.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/grpc/_objs/grpc_nanopb/pb_decode.pic.o: multiple definition of 'pb_close_string_substream'
/usr/bin/ld.gold: bazel-out/host/bin/external/grpc/third_party/nanopb/_objs/nanopb/pb_decode.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/grpc/_objs/grpc_nanopb/pb_decode.pic.o: multiple definition of 'pb_decode_noinit'
/usr/bin/ld.gold: bazel-out/host/bin/external/grpc/third_party/nanopb/_objs/nanopb/pb_decode.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/grpc/_objs/grpc_nanopb/pb_decode.pic.o: multiple definition of 'pb_decode'
/usr/bin/ld.gold: bazel-out/host/bin/external/grpc/third_party/nanopb/_objs/nanopb/pb_decode.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/grpc/_objs/grpc_nanopb/pb_decode.pic.o: multiple definition of 'pb_decode_delimited'
/usr/bin/ld.gold: bazel-out/host/bin/external/grpc/third_party/nanopb/_objs/nanopb/pb_decode.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/grpc/_objs/grpc_nanopb/pb_decode.pic.o: multiple definition of 'pb_decode_svarint'
/usr/bin/ld.gold: bazel-out/host/bin/external/grpc/third_party/nanopb/_objs/nanopb/pb_decode.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/grpc/_objs/grpc_nanopb/pb_decode.pic.o: multiple definition of 'pb_decode_fixed32'
/usr/bin/ld.gold: bazel-out/host/bin/external/grpc/third_party/nanopb/_objs/nanopb/pb_decode.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/grpc/_objs/grpc_nanopb/pb_decode.pic.o: multiple definition of 'pb_decode_fixed64'
/usr/bin/ld.gold: bazel-out/host/bin/external/grpc/third_party/nanopb/_objs/nanopb/pb_decode.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/grpc/_objs/grpc_nanopb/pb_encode.pic.o: multiple definition of 'pb_ostream_from_buffer'
/usr/bin/ld.gold: bazel-out/host/bin/external/grpc/third_party/nanopb/_objs/nanopb/pb_encode.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/grpc/_objs/grpc_nanopb/pb_encode.pic.o: multiple definition of 'pb_write'
/usr/bin/ld.gold: bazel-out/host/bin/external/grpc/third_party/nanopb/_objs/nanopb/pb_encode.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/grpc/_objs/grpc_nanopb/pb_encode.pic.o: multiple definition of 'pb_encode_varint'
/usr/bin/ld.gold: bazel-out/host/bin/external/grpc/third_party/nanopb/_objs/nanopb/pb_encode.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/grpc/_objs/grpc_nanopb/pb_encode.pic.o: multiple definition of 'pb_encode_svarint'
/usr/bin/ld.gold: bazel-out/host/bin/external/grpc/third_party/nanopb/_objs/nanopb/pb_encode.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/grpc/_objs/grpc_nanopb/pb_encode.pic.o: multiple definition of 'pb_encode_fixed32'
/usr/bin/ld.gold: bazel-out/host/bin/external/grpc/third_party/nanopb/_objs/nanopb/pb_encode.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/grpc/_objs/grpc_nanopb/pb_encode.pic.o: multiple definition of 'pb_encode_fixed64'
/usr/bin/ld.gold: bazel-out/host/bin/external/grpc/third_party/nanopb/_objs/nanopb/pb_encode.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/grpc/_objs/grpc_nanopb/pb_encode.pic.o: multiple definition of 'pb_encode_tag'
/usr/bin/ld.gold: bazel-out/host/bin/external/grpc/third_party/nanopb/_objs/nanopb/pb_encode.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/grpc/_objs/grpc_nanopb/pb_encode.pic.o: multiple definition of 'pb_encode_tag_for_field'
/usr/bin/ld.gold: bazel-out/host/bin/external/grpc/third_party/nanopb/_objs/nanopb/pb_encode.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/grpc/_objs/grpc_nanopb/pb_encode.pic.o: multiple definition of 'pb_encode'
/usr/bin/ld.gold: bazel-out/host/bin/external/grpc/third_party/nanopb/_objs/nanopb/pb_encode.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/grpc/_objs/grpc_nanopb/pb_encode.pic.o: multiple definition of 'pb_get_encoded_size'
/usr/bin/ld.gold: bazel-out/host/bin/external/grpc/third_party/nanopb/_objs/nanopb/pb_encode.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/grpc/_objs/grpc_nanopb/pb_encode.pic.o: multiple definition of 'pb_encode_string'
/usr/bin/ld.gold: bazel-out/host/bin/external/grpc/third_party/nanopb/_objs/nanopb/pb_encode.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/grpc/_objs/grpc_nanopb/pb_encode.pic.o: multiple definition of 'pb_encode_submessage'
/usr/bin/ld.gold: bazel-out/host/bin/external/grpc/third_party/nanopb/_objs/nanopb/pb_encode.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/grpc/_objs/grpc_nanopb/pb_encode.pic.o: multiple definition of 'pb_encode_delimited'
/usr/bin/ld.gold: bazel-out/host/bin/external/grpc/third_party/nanopb/_objs/nanopb/pb_encode.pic.o: previous definition here
collect2: error: ld returned 1 exit status
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```

**Comment by ziky90** [comment]
Resolved I'm able to build tensorflow==1.12.0 using bazet 0.18.1. It does not work with bazel 0.19.0 (tensorflow==1.11.0 works also with bazel 0.19.0)

**Comment by sekarpdkt** [comment]
I was able to build using bazel 0.18.1, python3.6.

**Comment by ExtremeGTX** [comment]
Able to get successful compilation using the following setup:
Google App Engine n1-standard-4 (4 vCPUs, 15 GB memory)
Ubuntu 18.04.2 LTS
Bazel: 0.18.1
Python: 3.6
tf: r1.12

different python version or bazel version didn't work for me
