### ISSUE TITLE
What (tf) happened to and in release 1.15.1?

### ISSUE THREAD

**Issue by sebastianschramm** [tensorflow/tensorflow#36282]
There was a release of tensorflow-1.15.1 available for a very short time (on Jan 24 2020) that caused a `TypeError: gradients_v2() got an unexpected keyword argument 'colocate_gradients_with_ops'`.

Exact same code that failed with above error on v1.15.1 works with v1.15.0 and v1.15.2.

Now, the release tag 1.15.1 (https://github.com/tensorflow/tensorflow/tags) is not even available anymore on github! To me that seems very fishy to say the least! So of course I am wondering what happened here?

**Comment by wdirons** [comment]
My speculation - 1.15.1 was tagged with something major wrong and they had to delete the tag so that no one tried to build it. The same thing happen with 1.13.0 when the master branch was tagged instead of the r1.13 branch. Once a tag is used and picked up in forks, you can't reuse it.

So 1.15.1 is history. Looking at the commit history for the r1.15 branch I see this: https://github.com/tensorflow/tensorflow/commit/a6d897351e483dfd0418e5cad2900ad9ef24188c

That makes me think that 1.15.1 was built using the TensorFlow 2.X build rules, hence the runtime error.

**Comment by mihaimaruseac** [comment]
1.15.1 was build using v2 behavior by mistake. So we removed all the pips and tags to make sure it won't get installed and we won't get issues to debug in the future for something we already know we caused as an error.

Apologies for the confusion.

Closing issue.
