### ISSUE TITLE
TensorFlowLiteC and TensorFlowLiteSelectTfOps expose duplicate symbols on iOS

### ISSUE THREAD

**Issue by psobot** [tensorflow/tensorflow#41876]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.15.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: iPhone 11 Pro Max
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.3.0

**Describe the problem**

When attempting to use TensorFlow Lite on iOS [with `TensorFlowLiteSelectTfOps` as per the documentation](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/ios/TensorFlowLiteSelectTfOps.md), the linker raises an error that it found `17 duplicate symbols for architecture arm64`:

```
duplicate symbol '_TfLiteDelegateCreate' in:
    [...snip...]/Pods/TensorFlowLiteSelectTfOps/Frameworks/TensorFlowLiteSelectTfOps.framework/TensorFlowLiteSelectTfOps(common_1fe599348340cdd31b92895a3a36b237.o)
    [...snip...]/Pods/TensorFlowLiteC/Frameworks/TensorFlowLiteC.framework/TensorFlowLiteC
duplicate symbol '_TfLiteFloatArrayCreate' in:
    [...snip...]/Pods/TensorFlowLiteSelectTfOps/Frameworks/TensorFlowLiteSelectTfOps.framework/TensorFlowLiteSelectTfOps(common_1fe599348340cdd31b92895a3a36b237.o)
    [...snip...]/Pods/TensorFlowLiteC/Frameworks/TensorFlowLiteC.framework/TensorFlowLiteC
duplicate symbol '_TfLiteFloatArrayFree' in:
    [...snip...]/Pods/TensorFlowLiteSelectTfOps/Frameworks/TensorFlowLiteSelectTfOps.framework/TensorFlowLiteSelectTfOps(common_1fe599348340cdd31b92895a3a36b237.o)
    [...snip...]/Pods/TensorFlowLiteC/Frameworks/TensorFlowLiteC.framework/TensorFlowLiteC
duplicate symbol '_TfLiteFloatArrayGetSizeInBytes' in:
    [...snip...]/Pods/TensorFlowLiteSelectTfOps/Frameworks/TensorFlowLiteSelectTfOps.framework/TensorFlowLiteSelectTfOps(common_1fe599348340cdd31b92895a3a36b237.o)
    [...snip...]/Pods/TensorFlowLiteC/Frameworks/TensorFlowLiteC.framework/TensorFlowLiteC
duplicate symbol '_TfLiteIntArrayCopy' in:
    [...snip...]/Pods/TensorFlowLiteSelectTfOps/Frameworks/TensorFlowLiteSelectTfOps.framework/TensorFlowLiteSelectTfOps(common_1fe599348340cdd31b92895a3a36b237.o)
    [...snip...]/Pods/TensorFlowLiteC/Frameworks/TensorFlowLiteC.framework/TensorFlowLiteC
duplicate symbol '_TfLiteIntArrayCreate' in:
    [...snip...]/Pods/TensorFlowLiteSelectTfOps/Frameworks/TensorFlowLiteSelectTfOps.framework/TensorFlowLiteSelectTfOps(common_1fe599348340cdd31b92895a3a36b237.o)
    [...snip...]/Pods/TensorFlowLiteC/Frameworks/TensorFlowLiteC.framework/TensorFlowLiteC
duplicate symbol '_TfLiteIntArrayEqual' in:
    [...snip...]/Pods/TensorFlowLiteSelectTfOps/Frameworks/TensorFlowLiteSelectTfOps.framework/TensorFlowLiteSelectTfOps(common_1fe599348340cdd31b92895a3a36b237.o)
    [...snip...]/Pods/TensorFlowLiteC/Frameworks/TensorFlowLiteC.framework/TensorFlowLiteC
duplicate symbol '_TfLiteIntArrayEqualsArray' in:
    [...snip...]/Pods/TensorFlowLiteSelectTfOps/Frameworks/TensorFlowLiteSelectTfOps.framework/TensorFlowLiteSelectTfOps(common_1fe599348340cdd31b92895a3a36b237.o)
    [...snip...]/Pods/TensorFlowLiteC/Frameworks/TensorFlowLiteC.framework/TensorFlowLiteC
duplicate symbol '_TfLiteIntArrayFree' in:
    [...snip...]/Pods/TensorFlowLiteSelectTfOps/Frameworks/TensorFlowLiteSelectTfOps.framework/TensorFlowLiteSelectTfOps(common_1fe599348340cdd31b92895a3a36b237.o)
    [...snip...]/Pods/TensorFlowLiteC/Frameworks/TensorFlowLiteC.framework/TensorFlowLiteC
duplicate symbol '_TfLiteIntArrayGetSizeInBytes' in:
    [...snip...]/Pods/TensorFlowLiteSelectTfOps/Frameworks/TensorFlowLiteSelectTfOps.framework/TensorFlowLiteSelectTfOps(common_1fe599348340cdd31b92895a3a36b237.o)
    [...snip...]/Pods/TensorFlowLiteC/Frameworks/TensorFlowLiteC.framework/TensorFlowLiteC
duplicate symbol '_TfLiteQuantizationFree' in:
    [...snip...]/Pods/TensorFlowLiteSelectTfOps/Frameworks/TensorFlowLiteSelectTfOps.framework/TensorFlowLiteSelectTfOps(common_1fe599348340cdd31b92895a3a36b237.o)
    [...snip...]/Pods/TensorFlowLiteC/Frameworks/TensorFlowLiteC.framework/TensorFlowLiteC
duplicate symbol '_TfLiteSparsityFree' in:
    [...snip...]/Pods/TensorFlowLiteSelectTfOps/Frameworks/TensorFlowLiteSelectTfOps.framework/TensorFlowLiteSelectTfOps(common_1fe599348340cdd31b92895a3a36b237.o)
    [...snip...]/Pods/TensorFlowLiteC/Frameworks/TensorFlowLiteC.framework/TensorFlowLiteC
duplicate symbol '_TfLiteTensorDataFree' in:
    [...snip...]/Pods/TensorFlowLiteSelectTfOps/Frameworks/TensorFlowLiteSelectTfOps.framework/TensorFlowLiteSelectTfOps(common_1fe599348340cdd31b92895a3a36b237.o)
    [...snip...]/Pods/TensorFlowLiteC/Frameworks/TensorFlowLiteC.framework/TensorFlowLiteC
duplicate symbol '_TfLiteTensorFree' in:
    [...snip...]/Pods/TensorFlowLiteSelectTfOps/Frameworks/TensorFlowLiteSelectTfOps.framework/TensorFlowLiteSelectTfOps(common_1fe599348340cdd31b92895a3a36b237.o)
    [...snip...]/Pods/TensorFlowLiteC/Frameworks/TensorFlowLiteC.framework/TensorFlowLiteC
duplicate symbol '_TfLiteTensorRealloc' in:
    [...snip...]/Pods/TensorFlowLiteSelectTfOps/Frameworks/TensorFlowLiteSelectTfOps.framework/TensorFlowLiteSelectTfOps(common_1fe599348340cdd31b92895a3a36b237.o)
    [...snip...]/Pods/TensorFlowLiteC/Frameworks/TensorFlowLiteC.framework/TensorFlowLiteC
duplicate symbol '_TfLiteTensorReset' in:
    [...snip...]/Pods/TensorFlowLiteSelectTfOps/Frameworks/TensorFlowLiteSelectTfOps.framework/TensorFlowLiteSelectTfOps(common_1fe599348340cdd31b92895a3a36b237.o)
    [...snip...]/Pods/TensorFlowLiteC/Frameworks/TensorFlowLiteC.framework/TensorFlowLiteC
duplicate symbol '_TfLiteTypeGetName' in:
    [...snip...]/Pods/TensorFlowLiteSelectTfOps/Frameworks/TensorFlowLiteSelectTfOps.framework/TensorFlowLiteSelectTfOps(common_1fe599348340cdd31b92895a3a36b237.o)
    [...snip...]/Pods/TensorFlowLiteC/Frameworks/TensorFlowLiteC.framework/TensorFlowLiteC
ld: 17 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Ran `pod install` with the following lines in my `Podfile`, as per documentation:
```
pod 'TensorFlowLiteObjC'
pod 'TensorFlowLiteSelectTfOps', '~> 0.0.1-nightly.20200729'
use_frameworks!
```

Attempted to build the app in Xcode.

`grep Tensor Podfile.lock` returns:
```
  - TensorFlowLiteC (2.3.0):
    - TensorFlowLiteC/Core (= 2.3.0)
  - TensorFlowLiteC/Core (2.3.0)
  - TensorFlowLiteObjC (2.3.0):
    - TensorFlowLiteC (= 2.3.0)
  - TensorFlowLiteSelectTfOps (0.0.1-nightly.20200729)
  - TensorFlowLiteObjC
  - TensorFlowLiteSelectTfOps (~> 0.0.1-nightly.20200729)
    - TensorFlowLiteC
    - TensorFlowLiteObjC
    - TensorFlowLiteSelectTfOps
  TensorFlowLiteC: 51f50caf5777f740a70e2c1a5dbdc149e7aeb50b
  TensorFlowLiteObjC: 5b358503636cffcbbafd8b0ac9badb577fd72800
  TensorFlowLiteSelectTfOps: eb44f3855f87b50470c70a379777c98aaf13a943
```

Friendly ping to @yyoon - I see you've been active in this code recently and may have some insight. 🙂

**Comment by yyoon** [comment]
Thanks for flagging! Let me try reproducing the issue and see what we can do about it.
Between 2.2.0 and 2.3.0, we had modified the way we expose symbols in iOS prebuilt frameworks, and that might have caused this issue.

**Comment by tinoucas** [comment]
I have the same issue.
Until it gets fixed, is there a workaround?

**Comment by kkadakia** [comment]
I have the same issue. 

` - TensorFlowLiteC (2.3.0):
    - TensorFlowLiteC/Core (= 2.3.0)
  - TensorFlowLiteC/Core (2.3.0)
  - TensorFlowLiteSelectTfOps (0.0.1-nightly.20200819)
  - TensorFlowLiteSwift (2.3.0):
    - TensorFlowLiteSwift/Core (= 2.3.0)
  - TensorFlowLiteSwift/Core (2.3.0):
    - TensorFlowLiteC (= 2.3.0)
  - TensorFlowLiteSelectTfOps (~> 0.0.1-nightly)
  - TensorFlowLiteSwift (= 2.3.0)
    - TensorFlowLiteC
    - TensorFlowLiteSelectTfOps
    - TensorFlowLiteSwift
  TensorFlowLiteC: 51f50caf5777f740a70e2c1a5dbdc149e7aeb50b
  TensorFlowLiteSelectTfOps: 003d038ccf014b39b65b7d02627e1b2856c0a340
  TensorFlowLiteSwift: fb152cc1eec36b25b03a23c07f5d58113170af58`

`Undefined symbols for architecture arm64:
  "_uprv_getICUData_conversion", referenced from:
      openCommonData(char const*, int, UErrorCode*) in TensorFlowLiteSelectTfOps(udata_2985644a25bfa5ed30c4cd35b64b13bb.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`


Is there a workaround

**Comment by vikalpsharma-kiwi** [comment]
Hi 

I am also getting same error.
Undefined symbols for architecture arm64:
  "_uprv_getICUData_conversion", referenced from:
      openCommonData(char const*, int, UErrorCode*) in TensorFlowLiteSelectTfOps(udata_2985644a25bfa5ed30c4cd35b64b13bb.o)
ld: symbol(s) not found for architecture arm64

Any solution for this.

**Comment by Vivekkiwitech** [comment]
> > > > @kkadakia : if you compile the frameworks from tip, it links without any issue. It's a bit time consuming, but in the mean time, it works.
> > > 
> > > 
> > > @tinoucas can you explain?
> > 
> > 
> > You need bazel version 3.1 installed, and run:
> > `/path/to/bazel build -c opt --config=ios --ios_multi_cpus=armv7,arm64,x86_64 "//tensorflow/lite/experimental/ios:TensorFlowLiteC_framework"`
> > and
> > `/path/to/bazel build -c opt --config=ios --ios_multi_cpus=armv7,arm64,x86_64 "//tensorflow/lite/experimental/ios:TensorFlowLiteSelectTfOps_framework"`
> > To quickly find the frameworks built you can run `find -L . -name \*.framework`
> 
> @tinoucas how do I integrate within an existing Swift project, without installing Bazel and starting a new project?

I have implemented Bazel as well but same error is still coming.

**Comment by Vivekkiwitech** [comment]
Hi TF Team,

We have integrated the below framework from the pod and also try to compile the project from Bazel as well but we are facing the same error during compile time.

We have also added force load from the Other linker sections in Xcode. 

Framework Used -
TensorFlowLiteSwift
TensorFlowLiteSelectTfOps

Xcode Configuration -

Xcode 11.3
Min Deployment Target - 13.0

Error - 

Undefined symbols for architecture x86_64:

  "_uprv_getICUData_conversion", referenced from:

      openCommonData(char const*, int, UErrorCode*) in TensorFlowLiteSelectTfOps(udata_6946572031b696892300e9a29f96be3f.o)

ld: symbol(s) not found for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

Kindly let me know the resolution for this It will be a great help for us.

**Comment by thaink** [comment]
Hi all,
The duplicated error does not appear in the current nightly anymore so please use that.
However, there is an current error: undefined symbol _uprv_getICUData_conversion which is described in b/41948

**Comment by thaink** [comment]
My current configs that this error does not happen:
PODS:
  - TensorFlowLiteC (0.0.1-nightly.20201005):
    - TensorFlowLiteC/Core (= 0.0.1-nightly.20201005)
  - TensorFlowLiteC/Core (0.0.1-nightly.20201005)
  - TensorFlowLiteSelectTfOps (0.0.1-nightly.20201005)
  - TensorFlowLiteSwift (0.0.1-nightly.20201005):
    - TensorFlowLiteSwift/Core (= 0.0.1-nightly.20201005)
  - TensorFlowLiteSwift/Core (0.0.1-nightly.20201005):
    - TensorFlowLiteC (= 0.0.1-nightly.20201005)

DEPENDENCIES:
  - TensorFlowLiteSelectTfOps (~> 0.0.1-nightly)
  - TensorFlowLiteSwift (~> 0.0.1-nightly)

**Comment by thaink** [comment]
Please feel free to reopen this bug if you still got this error.

**Comment by Koushik-Ogma** [comment]
@thaink 
I specified the versions as you have posted here. 

PODS:
  - TensorFlowLiteC (0.0.1-nightly.20200818):
    - TensorFlowLiteC/Core (= 0.0.1-nightly.20200818)
  - TensorFlowLiteC/Core (0.0.1-nightly.20200818)
  - TensorFlowLiteSelectTfOps (0.0.1-nightly.20200819)
  - TensorFlowLiteSwift (0.0.1-nightly.20200818):
    - TensorFlowLiteSwift/Core (= 0.0.1-nightly.20200818)
  - TensorFlowLiteSwift/Core (0.0.1-nightly.20200818):
    - TensorFlowLiteC (= 0.0.1-nightly.20200818)

DEPENDENCIES:
  - TensorFlowLiteSelectTfOps (~> 0.0.1-nightly)
  - TensorFlowLiteSwift (~> 0.0.1-nightly)

But I'm still getting this error.
Note: Not using Bazel or something else.

**Comment by thaink** [comment]
> @thaink
> I specified the versions as you have posted here.
> 
> PODS:
> 
> * TensorFlowLiteC (0.0.1-nightly.20200818):
>   
>   * TensorFlowLiteC/Core (= 0.0.1-nightly.20200818)
> * TensorFlowLiteC/Core (0.0.1-nightly.20200818)
> * TensorFlowLiteSelectTfOps (0.0.1-nightly.20200819)
> * TensorFlowLiteSwift (0.0.1-nightly.20200818):
>   
>   * TensorFlowLiteSwift/Core (= 0.0.1-nightly.20200818)
> * TensorFlowLiteSwift/Core (0.0.1-nightly.20200818):
>   
>   * TensorFlowLiteC (= 0.0.1-nightly.20200818)
> 
> DEPENDENCIES:
> 
> * TensorFlowLiteSelectTfOps (~> 0.0.1-nightly)
> * TensorFlowLiteSwift (~> 0.0.1-nightly)
> 
> But I'm still getting this error.
> Note: Not using Bazel or something else.

The nightly you are using is almost 2-month old. Could you run "pod update" and try the latest nightly.

**Comment by Koushik-Ogma** [comment]
> > @thaink
> > I specified the versions as you have posted here.
> > PODS:
> > 
> > * TensorFlowLiteC (0.0.1-nightly.20200818):
> >   
> >   * TensorFlowLiteC/Core (= 0.0.1-nightly.20200818)
> > * TensorFlowLiteC/Core (0.0.1-nightly.20200818)
> > * TensorFlowLiteSelectTfOps (0.0.1-nightly.20200819)
> > * TensorFlowLiteSwift (0.0.1-nightly.20200818):
> >   
> >   * TensorFlowLiteSwift/Core (= 0.0.1-nightly.20200818)
> > * TensorFlowLiteSwift/Core (0.0.1-nightly.20200818):
> >   
> >   * TensorFlowLiteC (= 0.0.1-nightly.20200818)
> > 
> > DEPENDENCIES:
> > 
> > * TensorFlowLiteSelectTfOps (~> 0.0.1-nightly)
> > * TensorFlowLiteSwift (~> 0.0.1-nightly)
> > 
> > But I'm still getting this error.
> > Note: Not using Bazel or something else.
> 
> The nightly you are using is almost 2-month old. Could you run "pod update" and try the latest nightly.

I had this done already. I even reinstalled Cocoapods. But it still downloads the same thing. 
Is there any other way around to download the latest version?

**Comment by Koushik-Ogma** [comment]
@thaink I just tried pod update again and ran into errors, twice.
Screenshot is attached.
![Screen Shot 2020-10-07 at 18 43 43](https://user-images.githubusercontent.com/60460266/95335574-32e33100-08cd-11eb-967d-3210eb6bb9c6.png)

**Comment by thaink** [comment]
@Koushik-Ogma I realized I still sometime faces this error too.
Will investigate more.

**Comment by Jesssullivan** [comment]
Any workarounds?  Still hitting `Undefined symbol: _uprv_getICUData_conversion` with nightly builds.

```
TensorFlowLiteC (0.0.1-nightly.20201010)
TensorFlowLiteSelectTfOps (0.0.1-nightly.20201010)
TensorFlowLiteSwift (0.0.1-nightly.20201010)
```

**Comment by magorik** [comment]
Same issue here.

**Comment by Jesssullivan** [comment]
> Same issue here.



> Same issue here.

Continuing thread over on Duplicate of #41948

**Comment by vvalouch** [comment]
The issue is still there:
Dependencies:
```
TensorFlowLiteC 0.0.1-nightly.20201019
TensorFlowLiteSwift 0.0.1-nightly.20201019
TensorFlowLiteSelectTfOps 0.0.1-nightly.20201021
```

Error:
```
Undefined symbols for architecture arm64:
  "_uprv_getICUData_conversion", referenced from:
      openCommonData(char const*, int, UErrorCode*) in TensorFlowLiteSelectTfOps(udata_2985644a25bfa5ed30c4cd35b64b13bb.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by thaink** [comment]
A fix is under review internally. Please wait a bit, I'll notify when it is merged to the master.

**Comment by vvalouch** [comment]
Thanks very much. I can confirm that it is working with 2.2.0 but as I am experimenting with Metal and CoreML on iOS (https://blog.concurlabs.com/mobile-machine-learning-model-benchmarking-tool-ef005cb60eb7?source=friends_link&sk=22ab42c053fd59cf1c2436739187d526) delegates I need it at least version 2.3.0 or nightly working. I am looking forward to fix. Thanks @thaink

**Comment by thaink** [comment]
Hi all,
Commit https://github.com/tensorflow/tensorflow/commit/4b6c15218b690c5c75b28c423991096e4f0ea51b contains the fix for this error.
You can try to build the master branch or waiting for it to be included in the nightly build tomorrow.

**Comment by swittk** [comment]
Hi, I'm experiencing this with the current nightly builds

Current podfile
```
'TensorFlowLiteObjC', '~> 0.0.1-nightly'
'TensorFlowLiteObjC/Metal', '~> 0.0.1-nightly'
'TensorFlowLiteSelectTfOps', '~> 0.0.1-nightly'
```
Resolves to lockfile
```
  - TensorFlowLiteC (0.0.1-nightly.20210915):
    - TensorFlowLiteC/Core (= 0.0.1-nightly.20210915)
  - TensorFlowLiteC/Core (0.0.1-nightly.20210915)
  - TensorFlowLiteC/Metal (0.0.1-nightly.20210915):
    - TensorFlowLiteC/Core
  - TensorFlowLiteObjC (0.0.1-nightly.20210915):
    - TensorFlowLiteObjC/Core (= 0.0.1-nightly.20210915)
  - TensorFlowLiteObjC/Core (0.0.1-nightly.20210915):
    - TensorFlowLiteC (= 0.0.1-nightly.20210915)
  - TensorFlowLiteObjC/Metal (0.0.1-nightly.20210915):
    - TensorFlowLiteC/Metal (= 0.0.1-nightly.20210915)
    - TensorFlowLiteObjC/Core (= 0.0.1-nightly.20210915)
  - TensorFlowLiteSelectTfOps (0.0.1-nightly.20210915)
```

The duplicate symbols are `_TfLiteXNNPackDelegateCreate `, `_TfLiteXNNPackDelegateDelete `, `_TfLiteXNNPackDelegateGetThreadPool `, and `_TfLiteXNNPackDelegateOptionsDefault`. 

They're duplicated between `/Pods/TensorFlowLiteSelectTfOps/Frameworks/TensorFlowLiteSelectTfOps.framework/TensorFlowLiteSelectTfOps(xnnpack_delegate.o)` and `Pods/TensorFlowLiteC/Frameworks/TensorFlowLiteC.framework/TensorFlowLiteC`.

**Comment by yyoon** [comment]
@swittk Can you instead file a new issue about this? This thread is closed long ago, and the cause of the issue seems different.

**Comment by swittk** [comment]
Sure thing!

**Comment by normano** [comment]
@yyoon Can you reopen this and possibly reassign to someone else. The issue may be stale, but the problem is still exists.

**Comment by w3sip** [comment]
Was this ever fixed? Trying 2.14.1, still seeing libz symbols exported by TensorFlowLiteSelectTfOps, resulting in linker failure when linking a project with TFLite.
