### ISSUE TITLE
what is gen_rnn_ops in tensorflow/python/ops

### ISSUE THREAD

**Issue by Vampsj** [tensorflow/tensorflow#33850]
Hi, I am trying to create my own linear tanh&sigmoid activation functions for lstmblockfusedcell (in lstm_ops.py), thus I directly create my own activation functions in rnn_cell_impl.py file and import this file in my own lstm_ops.py file. 
Then I got an error msg as follows:
`File "/home/git/DeepSpeech/lstm_ops_dpsp.py", line 29, in <module>
    from tensorflow.python.ops import gen_rnn_ops
ImportError: cannot import name 'gen_rnn_ops'`

But there is no much useful information about this _gen_rnn_ops_, and also I want to know whether my way to change the activation function is okay. 

By the way, I'm using 
Ubuntu 16.04
python 3.5
tensorflow-estimator 1.13.0
tensorflow-gpu       1.13.1

Thank you

**Comment by ravikyram** [comment]
@Vampsj 
In order to expedite the trouble-shooting process, please provide a minimal standalone code to reproduce the issue reported here. Thanks!

**Comment by Vampsj** [comment]
@ravikyram Sorry for the lack of codes! 
I am working on Deepspeech(Mozilla) but trying to replace the activation functions with linear approximated functions in the LSTM. Here is a piece of the code, they used *LSTMBlockFusedCell* here. Thus I copied the _lstm\_ops.py, rnn.py, rnn\_cell\_impl.py_ files and changed activation functions in _rnn\_cell\_impl.py_, and import my changed _rnn\_cell\_impl.py_ into the rest two files. 

Code in Deepspeech: 
```python
import Tensorflow as tf  
import rnn_dpsp as td_rnn # a copy of Tensorflow/python/ops/rnn.py
import lstm_ops_dpsp as td_lstm_ops # Tensorflow/python/ops/lstm_ops.py
import rnn_cell_impl_dpsp as td_rnn_cell # which is a copy of Tensorflow/python/ops/rnn_cell_impl.py  
def rnn_impl_lstmblockfusedcell(x, seq_length, previous_state, reuse):   
     # Forward direction cell:  
     # Original code: fw_cell = tf.contrib.rnn.LSTMBlockFusedCell(Config.n_cell_dim, reuse=reuse)  
    fw_cell = td_lstm_ops.LSTMBlockFusedCell(Config.n_cell_dim, reuse=reuse)  
    output, output_state = fw_cell(inputs=x,  
                                   dtype=tf.float32,  
                                   sequence_length=seq_length,  
                                   initial_state=previous_state)  
    return output, output_state
```
where, in my own _rnn_cell_impl_dpsp.py_ file, I added two linear approximated sigmoid&tanh functions:
```python
def tf_tanh_poly(x, name=None):
    with tf.name_scope(name, "tanh_poly", [x]) as name:
        y = py_func(np_tanh_poly_32,
                    [x],
                    [tf.float32],
                    name=name,
                    grad=tanhpgrad)  # <-- here's the call to the gradient
        return y[0]

def tf_sigmoid_poly(x, name=None):
    with tf.name_scope(name, "sigmoid_poly", [x]) as name:
        y = py_func(np_sigmoid_poly_32,
                    [x],
                    [tf.float32],
                    name=name,
                    grad=sigmoidgrad)  # <-- here's the call to the gradient
        return y[0]

....

@tf_export(v1=["nn.rnn_cell.BasicLSTMCell"])
class BasicLSTMCell(LayerRNNCell):
  @deprecated(None, "This class is equivalent as tf.keras.layers.LSTMCell,"
              " and will be replaced by that in Tensorflow 2.0.")
  def __init__(self, num_units, forget_bias=1.0,  state_is_tuple=True, activation=None, reuse=None,        name=None,  dtype=None,  **kwargs):

    self._num_units = num_units
    self._forget_bias = forget_bias
    self._state_is_tuple = state_is_tuple

    if activation:
      self._activation = math_ops.tanh
    else:
      self._activation = tf_tanh_poly     # HERE
```
and in the rest of two files, I only comment out the original import and changed to my own file :
```python
"""LSTM Block Cell ops."""
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import abc

import six

from tensorflow.python.framework import dtypes
from tensorflow.python.framework import ops
from tensorflow.python.keras.engine import input_spec
from tensorflow.python.layers import base as base_layer
from tensorflow.python.ops import array_ops
from tensorflow.python.ops import gen_rnn_ops
from tensorflow.python.ops import init_ops
from tensorflow.python.ops import math_ops
from tensorflow.python.ops import nn_ops
# from tensorflow.python.ops import rnn_cell_impl
import rnn_cell_impl_dpsp as rnn_cell_impl


LayerRNNCell = rnn_cell_impl.LayerRNNCell  # pylint: disable=invalid-name

```

Then I put these files in one folder, but I faced the 
`ImportError:in <module> from tensorflow.python.ops import gen_rnn_ops ImportError: cannot import name 'gen_rnn_ops'. 
`
For more detail, I used pip3 to install TensorFlow-gpu 1.13 rather than build from the source.

I am new to Tensorflow, if there is a better way to change the activation function, please tell me! Thank you!

**Comment by gadagashwini** [comment]
@Vampsj, It is working with Tf 1.15.0.
Please see the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/8326e49854e8d1fbf1c644a51ee01e59/untitled261.ipynb). Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ravikyram** [comment]
I  am closing the issue as it was resolved with TF 1.15. Please, feel free to reopen the issue if you feel issue still persists. Thanks!
