### ISSUE TITLE
Keras Model Errors on Loading - 'list' object has no attribute 'items'

### ISSUE THREAD

**Issue by Robbie-Palmer** [tensorflow/tensorflow#35934]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
**No**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Windows 10**
- TensorFlow installed from (source or binary): **pip**
- TensorFlow version (use command below): **2.1.0**
- Python version: **3.5.2**
- CUDA/cuDNN version: **CUDA 10.1 cuDNN 7.6**
- GPU model and memory: **Quadro M2000M 4.00GiB**

**Describe the current behavior**

When trying to load one of my sequential models using `tf.keras.models.load_model` an error is thrown at the following location:
```
tensorflow_core\python\keras\utils\generic_utils.py", line 254, in class_and_config_for_serialized_keras_object
for key, item in cls_config.items():
```

This code expects `cls_config` to be a dictionary, while for this model it is a list of dictionaries.
I can successfully load and run this model using TensorFlow versions `2.0.0`, `1.14.0` and `1.4.0` (the version is was trained with)

This section of code was introduced when adding support for [passive serialization in Keras](https://github.com/tensorflow/tensorflow/commit/a4fe7d8b6919281e26e2970e530cbff886a778ae#diff-ca2f2579ed6d04b0be9c2bacfa1a4d38)

**Describe the expected behavior**

Can successfully load a model from a hdf5 file when its config is in the list format

**Code to reproduce the issue**

Execute the `class_and_config_for_serialized_keras_object` function with a config of the following form:

```JSON
{
    "config": [
        {
            "config": 
            {
                ...
            },
            "class_name": "Conv2D"
        },
        ...
    ],
    "class_name": "Sequential"
}
```

Which is different from the form when I create a new model using TF v2.1.0 or 2.0.0 (I haven't verified the form of the config with the other versions):

```JSON
{
    "config": {
        "name": "sequential",
        "layers": [
            {
                "config": 
                {
                    ...
                },
                "class_name": "Conv2D"
            },
            ...
        ]
    },
    "class_name": "Sequential"
}
```

**Other info / logs**

When loaded with tf.keras in v2.0.0 the layers, model config, inputs, outputs, summary etc. are all parsed correctly, as well as being able to run data through the model.

**Comment by ymodak** [comment]
Please minimal reproducible code snippet. Thanks!

**Comment by Robbie-Palmer** [comment]
**Minimal reproducible code snippets**

Using TensorFlow v1.4.0, Keras v2.1.1, CUDA v8.0.1 and cuDNN v6.0

```Python
from keras.models import Sequential
from keras.layers import Conv2D

model = Sequential()
model.add(Conv2D(32, (3, 3), input_shape=(96, 96, 3)))
model.save('model.hdf5')
```


Using TensorFlow v2.1.0, CUDA v10.1.105 and cuDNN v7.6

```Python
from tensorflow.keras.models import load_model

model = load_model('model.hdf5', compile=False)
```

**Comment by Hyperclaw79** [comment]
@ymodak 
Any updates on this? I've encountered the same bug as well.
Would really appreciate a fix for this.

**Comment by hangyao** [comment]
I had the same issue and I downgrade tensorflow to 2.0.0 and it works fine.

**Comment by Hyperclaw79** [comment]
> I had the same issue and I downgrade tensorflow to 2.0.0 and it works fine.

Same here but a rollback should be a last resort imo.

**Comment by ymodak** [comment]
I was not able to reproduce the behavior. Can you change your imports from `keras` to `tensorflow.keras` in all snippets and confirm if issue persists?
I saved the model using TensorFlow 1.14 and loaded the same `h5` successfully using tf-nightly version and TF 2.1.

**Comment by xquyvu** [comment]
I'm having the same problem here.

Using `from tensorflow.keras.models` throws an error, but `from keras.models ... ` doesn't

`
# Doesnt work
from tensorflow.keras.models import model_from_config
model = model_from_config(event['parameters']['model_json'])

# Work
from keras.models import model_from_config
model = model_from_config(event['parameters']['model_json'])
`

`{"class_name": "Sequential", "config": [{"class_name": "Dense", "config": {"name": "dense_1", "trainable": true, "batch_input_shape": [null, 52], "dtype": "float32", "units": 128, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "VarianceScaling", "config": {"scale": 1.0, "mode": "fan_avg", "distribution": "uniform", "seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": {"class_name": "L1L2", "config": {"l1": 0.0, "l2": 0.009999999776482582}}, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}}, {"class_name": "BatchNormalization", "config": {"name": "batch_normalization_1", "trainable": true, "axis": -1, "momentum": 0.99, "epsilon": 0.001, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}}, "gamma_initializer": {"class_name": "Ones", "config": {}}, "moving_mean_initializer": {"class_name": "Zeros", "config": {}}, "moving_variance_initializer": {"class_name": "Ones", "config": {}}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}}, {"class_name": "Dropout", "config": {"name": "dropout_1", "trainable": true, "rate": 0.2, "noise_shape": null, "seed": null}}, {"class_name": "Dense", "config": {"name": "dense_2", "trainable": true, "units": 128, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "VarianceScaling", "config": {"scale": 1.0, "mode": "fan_avg", "distribution": "uniform", "seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}}, {"class_name": "BatchNormalization", "config": {"name": "batch_normalization_2", "trainable": true, "axis": -1, "momentum": 0.99, "epsilon": 0.001, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}}, "gamma_initializer": {"class_name": "Ones", "config": {}}, "moving_mean_initializer": {"class_name": "Zeros", "config": {}}, "moving_variance_initializer": {"class_name": "Ones", "config": {}}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}}, {"class_name": "Dropout", "config": {"name": "dropout_2", "trainable": true, "rate": 0.2, "noise_shape": null, "seed": null}}, {"class_name": "Dense", "config": {"name": "dense_3", "trainable": true, "units": 64, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "VarianceScaling", "config": {"scale": 1.0, "mode": "fan_avg", "distribution": "uniform", "seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}}, {"class_name": "BatchNormalization", "config": {"name": "batch_normalization_3", "trainable": true, "axis": -1, "momentum": 0.99, "epsilon": 0.001, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}}, "gamma_initializer": {"class_name": "Ones", "config": {}}, "moving_mean_initializer": {"class_name": "Zeros", "config": {}}, "moving_variance_initializer": {"class_name": "Ones", "config": {}}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}}, {"class_name": "Dropout", "config": {"name": "dropout_3", "trainable": true, "rate": 0.2, "noise_shape": null, "seed": null}}, {"class_name": "Dense", "config": {"name": "dense_4", "trainable": true, "units": 32, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "VarianceScaling", "config": {"scale": 1.0, "mode": "fan_avg", "distribution": "uniform", "seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}}, {"class_name": "BatchNormalization", "config": {"name": "batch_normalization_4", "trainable": true, "axis": -1, "momentum": 0.99, "epsilon": 0.001, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}}, "gamma_initializer": {"class_name": "Ones", "config": {}}, "moving_mean_initializer": {"class_name": "Zeros", "config": {}}, "moving_variance_initializer": {"class_name": "Ones", "config": {}}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}}, {"class_name": "Dropout", "config": {"name": "dropout_4", "trainable": true, "rate": 0.2, "noise_shape": null, "seed": null}}, {"class_name": "Dense", "config": {"name": "dense_5", "trainable": true, "units": 1, "activation": "linear", "use_bias": true, "kernel_initializer": {"class_name": "VarianceScaling", "config": {"scale": 1.0, "mode": "fan_avg", "distribution": "uniform", "seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}}], "keras_version": "2.2.2", "backend": "tensorflow"}`

**Comment by ymodak** [comment]
Closing this issue since it cannot be reproduced. Feel free to reopen a new issue with a repro example. Thanks!

**Comment by Robbie-Palmer** [comment]
@ymodak Will `tf.keras` only be kept backwards compatible with `tf.keras` and not the original `keras` package?
As given Keras officially says `tf.keras` is its successor, this could cause difficulties for people

**Comment by robfreund** [comment]
@ymodak What is recommended path forward on this. I have similar issue when using >2.0 tensorflow.
```
from tensorflow.keras.models import load_model
model = load_model()
AttributeError: 'list' object has no attribute 'items
```
When I downgrade to 2.0 this works fine.

**Comment by tripathysa** [comment]
@ymodak : Same issue I am facing. Please suggest a resolution.

**Comment by ymodak** [comment]
@robfreund @tripathysa Please open a new issue with a minimal reproducible example and I will be happy to take a look.
At this moment I cannot reproduce the reported behavior. Thanks!

**Comment by strohmann** [comment]
I'm able to reproduce this issue when converting an h5 model from this package:
https://zenodo.org/record/3466980
(This is the model data for this system: https://github.com/mahehu/TUT-live-age-estimator)

Input model for tflite_convert: recognizers\alignment\model-056-0.716316-0.967865.h5
(File from the package mentioned above)

Command line: 
tflite_convert --output_file=model.tflite --keras_model_file=model-056-0.716316-0.967865.h5

Output:
  File "c:\users\matthias\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 325, in class_and_config_for_serialized_keras_object
    for key, item in cls_config.items():
AttributeError: 'list' object has no attribute 'items'

Python: 3.7.7
TF version: 2.1.0 and 2.2.0-rc2, installed via pip
OS: Windows 8.1
No CUDA or configured GPU

**Comment by danbricedatascience** [comment]
@ymodak I have the same issue, it's easy to reproduce because it's happened when I have old models created and saved with Keras (with TF 1.14 as backend) I try to import in TF 2.1 with tf.keras. 

The tf.keras import works with TF 2.0.

To reproduce, train and save anything with Keras (not tf.keras) with TF 1.14 as backend, and try to import with tf.keras under TF 2.1

**Comment by midhuniitm** [comment]
Any resolution on this ?

**Comment by mhsmith** [comment]
It looks like this will be fixed in TensorFlow 2.3: see #38135.

**Comment by KuldeepSangwan** [comment]
this problem can be due to, while saving the file you used a different version of tensorflow(or maybe you used someone else's .h5 file that was using some different version of tensorflow).

**Comment by johncalvowtg** [comment]
Hello! I have the same issue here... 
invoice_candidate_model = tf.keras.models.load_model('../model/Invoice_Extraction_Model_AU')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-1d8766d6d9d0> in <module>
----> 1 invoice_candidate_model = tf.keras.models.load_model('../model/Invoice_Extraction_Model_AU')

C:\Program Files\Python38\lib\site-packages\tensorflow\python\keras\saving\save.py in load_model(filepath, custom_objects, compile, options)
    210       if isinstance(filepath, six.string_types):
    211         loader_impl.parse_saved_model(filepath)
--> 212         return saved_model_load.load(filepath, compile, options)
    213 
    214   raise IOError(

C:\Program Files\Python38\lib\site-packages\tensorflow\python\keras\saving\saved_model\load.py in load(path, compile, options)
    136   # Recreate layers and metrics using the info stored in the metadata.
    137   keras_loader = KerasObjectLoader(metadata, object_graph_def)
--> 138   keras_loader.load_layers()
    139 
    140   # Generate a dictionary of all loaded nodes.

C:\Program Files\Python38\lib\site-packages\tensorflow\python\keras\saving\saved_model\load.py in load_layers(self)
    372         continue
    373 
--> 374       self.loaded_nodes[node_metadata.node_id] = self._load_layer(
    375           node_metadata.node_id, node_metadata.identifier,
    376           node_metadata.metadata)

C:\Program Files\Python38\lib\site-packages\tensorflow\python\keras\saving\saved_model\load.py in _load_layer(self, node_id, identifier, metadata)
    403     # Detect whether this object can be revived from the config. If not, then
    404     # revive from the SavedModel instead.
--> 405     obj, setter = self._revive_from_config(identifier, metadata, node_id)
    406     if obj is None:
    407       obj, setter = revive_custom_object(identifier, metadata)

C:\Program Files\Python38\lib\site-packages\tensorflow\python\keras\saving\saved_model\load.py in _revive_from_config(self, identifier, metadata, node_id)
    421       obj = (
    422           self._revive_graph_network(metadata, node_id) or
--> 423           self._revive_layer_from_config(metadata, node_id))
    424 
    425     if obj is None:

C:\Program Files\Python38\lib\site-packages\tensorflow\python\keras\saving\saved_model\load.py in _revive_layer_from_config(self, metadata, node_id)
    480 
    481     try:
--> 482       obj = layers_module.deserialize(
    483           generic_utils.serialize_keras_class_and_config(class_name, config))
    484     except ValueError:

C:\Program Files\Python38\lib\site-packages\tensorflow\python\keras\layers\serialization.py in deserialize(config, custom_objects)
    171   """
    172   populate_deserializable_objects()
--> 173   return generic_utils.deserialize_keras_object(
    174       config,
    175       module_objects=LOCAL.ALL_OBJECTS,

C:\Program Files\Python38\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    352 
    353       if 'custom_objects' in arg_spec.args:
--> 354         return cls.from_config(
    355             cls_config,
    356             custom_objects=dict(

C:\Program Files\Python38\lib\site-packages\tensorflow\python\keras\layers\core.py in from_config(cls, config, custom_objects)
   1017   def from_config(cls, config, custom_objects=None):
   1018     config = config.copy()
-> 1019     function = cls._parse_function_from_config(
   1020         config, custom_objects, 'function', 'module', 'function_type')
   1021 

C:\Program Files\Python38\lib\site-packages\tensorflow\python\keras\layers\core.py in _parse_function_from_config(cls, config, custom_objects, func_attr_name, module_attr_name, func_type_attr_name)
   1063     if function_type == 'function':
   1064       # Simple lookup in custom objects
-> 1065       function = generic_utils.deserialize_keras_object(
   1066           config[func_attr_name],
   1067           custom_objects=custom_objects,

C:\Program Files\Python38\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    373       obj = _GLOBAL_CUSTOM_OBJECTS[object_name]
    374     else:
--> 375       obj = module_objects.get(object_name)
    376       if obj is None:
    377         raise ValueError(

AttributeError: 'NoneType' object has no attribute 'get'

My tensorflow version is 2.4.0 .... So annoying!

**Comment by tami64** [comment]
Saving without model.fit?
