### ISSUE TITLE
plot_model() got an unexpected keyword argument 'show_layer_activations'

### ISSUE THREAD

**Issue by kaushalkrishna2000** [tensorflow/tensorflow#59166]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

2.6.4

### Custom Code

No

### OS Platform and Distribution

Linux

### Python version

3.7.12

### Current Behaviour?

```shell
plot_model not working according to the documentation mentioned. In Jupyer Notebook of Kaggle.
```

### Standalone code to reproduce the issue

```shell
n=3
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout,Input
from tensorflow.keras.callbacks import EarlyStopping

e=EarlyStopping(patience=9,restore_best_weights=True,verbose=1)

model=Sequential()

#Input Layer
model.add(Input(shape=(X_train.shape[1],)))

#Hidden Layer
for counter in range(1,n+1):
    model.add(Dense(n*X_train.shape[1],activation='relu'))
#     if(counter%4==0):
#         model.add(Dropout(0.75))

#Output Layer
model.add(Dense(1))

model.compile(loss='mean_squared_error',
              optimizer='adam',
              metrics = ['mean_absolute_error',tf.keras.metrics.RootMeanSquaredError()])

model. Summary()

# from tensorflow.keras.utils import plot_model
tf.keras.utils.plot_model(model, to_file='model.png',show_shapes=True,show_dtype=True,show_layer_activations=True,show_layer_names=True,rankdir='LR')
```

### Relevant log output

```shell
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_23/976071416.py in <module>
      1 # from tensorflow.keras.utils import plot_model
----> 2 tf.keras.utils.plot_model(model, to_file='model.png',show_shapes=True,show_dtype=True,show_layer_activations=True,show_layer_names=True,rankdir='LR')

TypeError: plot_model() got an unexpected keyword argument 'show_layer_activations'
```
</details>

**Comment by mohantym** [comment]
Hi @kaushalkrishna2000 !

Thanks for sharing your observation of plot_model w.r.to 2.6 version. 
Could you check against [2.9](https://colab.sandbox.google.com/gist/mohantym/e3e6ad691bc5c3f1f10406176f5a010d/git_59166.ipynb)/[2.11](https://colab.sandbox.google.com/gist/mohantym/2463a86d808f90db818d65be4cf15447/git_59166.ipynb#scrollTo=0OMk51yk-wl3) and let us know.

Thank you!

**Comment by kaushalkrishna2000** [comment]
Its working in 2.9 ( will check 2.11 in sometime ).
There is a difference in which the image is presented.

2.9
![image](https://user-images.githubusercontent.com/67849172/211206451-f2bc8e56-40d8-49d1-a4b1-a44a022cec9d.png)



2.6
![image](https://user-images.githubusercontent.com/67849172/211206470-b45bbe07-952f-42d8-89ec-a342f7e80301.png)


Is it possible to make it the same size of 2.6 ?

**Comment by kaushalkrishna2000** [comment]
2.11

![image](https://user-images.githubusercontent.com/67849172/211207661-743718b5-599f-441d-a183-d1c0c82789d6.png)

**Comment by kaushalkrishna2000** [comment]
n=3
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout,Input
from tensorflow.keras.callbacks import EarlyStopping

e=EarlyStopping(patience=9,restore_best_weights=True,verbose=1)

model=Sequential()

#Input Layer
model.add(Input(shape=(24,)))

#Hidden Layer
for counter in range(1,n+1):
    model.add(Dense(n*24,activation='relu'))
#     if(counter%4==0):
#         model.add(Dropout(0.75))

#Output Layer
model.add(Dense(1))

model.compile(loss='mean_squared_error',
              optimizer='adam',
              metrics = ['mean_absolute_error',tf.keras.metrics.RootMeanSquaredError()])

model. summary()


tf.keras.utils.plot_model(model, to_file='model.png',rankdir='TB',show_layer_activations=True,
                          show_shapes=True,show_layer_names=True,show_dtype=True)



You can try above code to reproduce the above pics.

**Comment by kaushalkrishna2000** [comment]
`tf.keras.utils.plot_model(model, to_file='model.png',rankdir='TB',show_layer_activations=True,
                          show_shapes=True,show_layer_names=True,show_dtype=True)`

**Comment by mohantym** [comment]
Hi @kaushalkrishna2000 !

I am getting type error mentioned in template for [2.6.3](https://colab.sandbox.google.com/gist/mohantym/b2af1b8f4ce40d9638acc89ec3d54a28/git_59166_2-6-3_keras.ipynb#scrollTo=wFtwFGE5XjHz). 
Shapes seems to be same for 2.9 and 2.11. 

Could you consider this resolved in 2.11 (as a lot of bugs has been fixed in version after 2.9)


Please post this issue on [keras-team/keras repo](https://github.com/keras-team/keras/issues) for further assistance.
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999) . 

Thank you!
