### ISSUE TITLE
Direct access to Tensor Buffers in C++ interface

### ISSUE THREAD

**Issue by pdrews** [tensorflow/tensorflow#8033]
I would like to request direct access to the tensorflow buffers through the C++ interface.  I have commented previously about this on [StackOverflow](http://stackoverflow.com/questions/39379747/import-opencv-mat-into-c-tensorflow-without-copying), and have gotten it to work by exposing the `TensorCApi` class.  This required some fiddling around with the source code.

My specific use case is using tensorflow from a [ROS](http://www.ros.org/) (robot operating system) node.  ROS has its own build system, so I have to link to the tensorflow library (libtensorflow.so) externally.  The C++ interface is much more convenient than the C interface, as I only load and do forward inference on static graphs.

Because I get an OpenCV array as input, my only other option is to iterate the entire array and copy it to a newly allocated tensor buffer as suggested in [this post](http://stackoverflow.com/questions/36044197/how-do-i-pass-an-opencv-mat-into-a-c-tensorflow-graph).  In my case, copying the buffer by iterating it can take 25-75ms, whereas simply pointing to the memory already allocated by OpenCV incurs almost no overhead.  I am doing all of this in real time as part of a tight control loop, so this extra time is absolutely critical.

I realize this patch is probably not the right way to expose the interface, and my example code provides no memory checking or safeguards, but it is an example (diff against the r1.0 tensorflow tag):

```
diff --git a/tensorflow/c/c_api.cc b/tensorflow/c/c_api.cc
index 83ce3e2..34ae2b4 100644
--- a/tensorflow/c/c_api.cc
+++ b/tensorflow/c/c_api.cc
@@ -464,14 +464,11 @@ TF_Tensor* TF_Tensor_EncodeStrings(const Tensor& src) {
                       dimvec.size(), base, size, DeleteArray, base);
 }
 
-class TensorCApi {
- public:
-  static TensorBuffer* Buffer(const Tensor& tensor) { return tensor.buf_; }
-  static Tensor MakeTensor(TF_DataType type, const TensorShape& shape,
-                           TensorBuffer* buf) {
-    return Tensor(static_cast<DataType>(type), shape, buf);
-  }
-};
+TensorBuffer* TensorCApi::Buffer(const Tensor& tensor) { return tensor.buf_; }
+Tensor TensorCApi::MakeTensor(TF_DataType type, const TensorShape& shape,
+                         TensorBuffer* buf) {
+  return Tensor(static_cast<DataType>(type), shape, buf);
+}
 
 // Create an empty tensor of type 'dtype'. 'shape' can be arbitrary, but has to
 // result in a zero-sized tensor.
diff --git a/tensorflow/c/c_api.h b/tensorflow/c/c_api.h
index e625d65..7479a1f 100644
--- a/tensorflow/c/c_api.h
+++ b/tensorflow/c/c_api.h
@@ -18,6 +18,7 @@ limitations under the License.
 
 #include <stddef.h>
 #include <stdint.h>
+#include "tensorflow/core/framework/tensor.h"
 
 // --------------------------------------------------------------------------
 // C API for TensorFlow.
@@ -64,6 +65,10 @@ limitations under the License.
 //   and the API just provides high level controls over the number of
 //   devices of each type.
 
+using tensorflow::Tensor;
+using tensorflow::TensorBuffer;
+using tensorflow::TensorShape;
+
 #ifdef __cplusplus
 extern "C" {
 #endif
@@ -1030,6 +1035,15 @@ extern void TF_DeleteLibraryHandle(TF_Library* lib_handle);
 // in this address space.
 extern TF_Buffer* TF_GetAllOpList();
 
+namespace tensorflow{
+class TensorCApi {
+public:
+ static TensorBuffer* Buffer(const Tensor& tensor);
+ static Tensor MakeTensor(TF_DataType type, const TensorShape& shape,
+                          TensorBuffer* buf);
+};
+};
+
 #ifdef __cplusplus
 } /* end extern "C" */
 #endif
diff --git a/tensorflow/core/framework/tensor.h b/tensorflow/core/framework/tensor.h
index c2a1c3d..14e9881 100644
--- a/tensorflow/core/framework/tensor.h
+++ b/tensorflow/core/framework/tensor.h
@@ -36,7 +36,7 @@ limitations under the License.
 namespace tensorflow {
 
 class TensorBuffer;  // Forward declaration.
-class TensorCApi;
+// class TensorCApi;
 
 /// @ingroup core
 /// Represents an n-dimensional array of values.
```

and a small snippet of code to use it:
```
// Put an image in the cameraImg mat
cv::resize(image->image, cameraImg, cv::Size(inputwidth, inputheight), 0, 0, cv::INTER_AREA);
// Create a new tensor pointing to that memory:
const int64_t tensorDims[4] = {1,inputheight,inputwidth,3};
int *imNumPt = new int(1);
TF_Tensor* tftensor = TF_NewTensor(TF_DataType::TF_UINT8, tensorDims, 4,
                           cameraImg.data, inputheight * inputwidth * 3,
                           NULL, imNumPt);
Tensor inputImg = tensorflow::TensorCApi::MakeTensor(tftensor->dtype, tftensor->shape, tftensor->buffer);
```

**Comment by pdrews** [comment]
The C++ interface seems much more concise for this application, but it may be better to use the C interface.  The c interface header doesn't depend on any other headers, so building outside of the tensorflow source tree becomes much easier (a requirement for my project).  However, I cannot find any examples of loading and running a graph using the C api.  

If there are concise resources for the C api, I can investigate this pathway.

**Comment by tatatodd** [comment]
@josh11b Can you share your thoughts here?

**Comment by HossamAmer12** [comment]
@pdrews I tried your approach, but I get the following error: "undefined reference to `TF_NewTensor'" -- Any pointers?

**Comment by pdrews** [comment]
@HossamAmer12 This should be in the c_api.h header in tensorflow.  That code snippet is not complete, so won't compile on its own. I had to add several headers from the c++ interface as well.  I added a line at the bottom of the code snippet that is required to use this new C tensor from the C++ interface.

**Comment by HossamAmer12** [comment]
@pdrews Is there any chance that you can provide the steps anywhere (here, tutorial or anything)? 

Would be highly appreciated!

**Comment by skye** [comment]
@pdrews I would recommend using the C API for now. As you mentioned, it's more verbose but might make your project build simpler, and most importantly it already exposes the functionality you need :) Unfortunately we lack documentation on it so here's some info to get you started:

_Building:_ https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-1.0.0.tar.gz is a pre-built Linux binary (CPU-only, I'm assuming your robot doesn't have a GPU). I believe this should work if ROS is built on top of a standard Linux distro. Otherwise it sounds like you have already figured out how to build from source.

_Usage_: Here's an example on how to load and run a graph:
```c++
TF_Status* s = TF_NewStatus();
TF_Graph* graph = TF_NewGraph();

const char* graph_def_data; // <-- your serialized GraphDef here
TF_Buffer graph_def = {graph_def_data, strlen(graph_def_data), nullptr};

// Import `graph_def` into `graph`
TF_ImportGraphDefOptions* import_opts = TF_NewImportGraphDefOptions();
TF_ImportGraphDefOptionsSetPrefix(import_opts, "import");
TF_GraphImportGraphDef(graph, &graph_def, import_opts, s);
assert(TF_GetCode(s) == TF_OK);

// Setup graph inputs
std::vector<TF_Output> inputs;
std::vector<TF_Tensor*> input_values;
// Add the placeholders you would like to feed, e.g.:
TF_Operation* placeholder = TF_GraphOperationByName(graph, "import/my_placeholder");
inputs.push_back({placeholder, 0});
TF_Tensor* tensor = TF_NewTensor(/*...*/);
input_values.push_back(tensor);

// Setup graph outputs
std::vector<TF_Output> outputs;
// Add the node outputs you would like to fetch, e.g.:
TF_Operation* output_op = TF_GraphOperationByName(graph, "import/my_output");
outputs.push_back({output_op, 0});
std::vector<TF_Tensor*> output_values(outputs.size(), nullptr);

// Run `graph`
TF_SessionOptions* sess_opts = TF_NewSessionOptions();
TF_Session* session = TF_NewSession(graph, sess_opts, s);
assert(TF_GetCode(s) == TF_OK);
TF_SessionRun(session, nullptr,
              &inputs[0], &input_values[0], inputs.size(),
              &outputs[0], &output_values[0], outputs.size(),
              nullptr, 0, nullptr, s);

void* output_data = TF_TensorData(output_values[0]);
assert(TF_GetCode(s) == TF_OK);

// If you have a more complicated workflow, I suggest making scoped wrapper
// classes that call these in their destructors
for (int i = 0; i < inputs.size(); ++i) TF_DeleteTensor(input_values[i]);
for (int i = 0; i < outputs.size(); ++i) TF_DeleteTensor(output_values[i]);
TF_CloseSession(session, s);
TF_DeleteSession(session, s);
TF_DeleteSessionOptions(sess_opts);
TF_DeleteImportGraphDefOptions(import_opts);
TF_DeleteGraph(graph);
TF_DeleteStatus(s);
```
Full disclosure, I didn't actually run this code, so please let me know if you run into problems. For details please refer to the [C API header](https://github.com/tensorflow/tensorflow/blob/r1.0/tensorflow/c/c_api.h). The [C API test](https://github.com/tensorflow/tensorflow/blob/r1.0/tensorflow/c/c_api_test.cc) has more examples for how to use the code.

If using the C API doesn't work for you, using the C++ API is still an option. I'm currently working on making the C++ API more user-friendly (e.g. distributing binaries so you don't have to build from source), and I'll be sure to include this feature request, but it might not be available for a while.

**Comment by skye** [comment]
@HossamAmer12 I suggest using the instructions I provided above to use the C API. If you'd like to try modifying the C++ API, please refer to [Installing TensorFlow from Source](https://www.tensorflow.org/install/install_sources). Once you get that working, you can use `bazel build -c opt //tensorflow:libtensorflow.so`, which will build the libtensorflow.so in bazel-bin/tensorflow (relative to your TF checkout root). I'd like to keep this issue focused on direct access to Tensor data, so if you have any further build problems please report them on [Stack Overflow](https://stackoverflow.com/questions/tagged/tensorflow) (we try to reserve GitHub issues for bugs, feature requests, etc.).

**Comment by HossamAmer12** [comment]
@skye Thank you for your reply!

I have already built TF from source and it is all set up, yet I do have the same issue where I use the TF's C++ API in a project that requires manually feeding data (char*) into tensors; to avoid this, I tried @pdrews's approach and I got the compile error that I've mentioned. 

Because I still use the C++ API, it seems to me that I should still keep copying the data in order to run my NN -- Correct?

**Comment by skye** [comment]
Yes, if you have it working acceptably with copying, I'd say you should continue using that. Premature optimization is the root of all evil ;)

That said, I realize you probably need to build with `bazel build -c opt //tensorflow/tools/lib_package:libtensorflow` and look at bazel-bin/tensorflow/tools/lib_package/libtensorflow.tar.gz (which includes the header and .so you need). Linking that should expose the C API.

**Comment by HossamAmer12** [comment]
@skye I understand :)  I'm working on a project where optimising execution time is a big deal and copying data is expensive, so I'd appreciate it if you can come up with the C++ feature as soon as you can. I'm actually thinking of excluding this copy time for my calculated total time.

As for your C API suggestion, would it work normally with C++ code? (I guess yes)

**Comment by pdrews** [comment]
@skye That looks great!  An example of the C interface is exactly what I have been missing.  I will look into transitioning to that over the next week.  I am already able to compile libtensorflow.so from source (we do have a GPU on our robot, so we need GPU acceleration).  I assume the graphdef char array can just be read in from a .pb file created from the freeze_graph.py script?

**Comment by skye** [comment]
@HossamAmer12 Yup, you can use the C API in a C++ application (I usually end up writing little C++ wrappers to make it easier to use, like scoped wrapper classes).

@pdrews I'm not super familiar with freeze_graph.py but it looks like that should work (the input to TF_ImportGraphDef is a serialized GraphDef proto, which it looks like freeze_graph.py emits).

Also, here's the link to the GPU-enabled version: https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-linux-x86_64-1.0.0.tar.gz

For future reference, these links and some more instructions are inconveniently located here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/go/README.md. I'll look into creating some more documentation for the C API.

**Comment by byronyi** [comment]
Might be a little be too hacky, but one way not to changing TF C/C++ API is to allocate an empty `Tensor` before you do any other computation, and use the buffer (a direct pointer could be obtained from `StringPiece`) of that `Tensor` as the underlaying storage for data structure to, say, OpenCV. 

Lifetime issue could be tricky though.

**Comment by ioannisnousias** [comment]
@skye with your help I have an 'almost' working program using the C API libtensorflow.so. 

I run into the following problem. I get this error message:
W tensorflow/core/common_runtime/device_mgr.cc:94] Unknown device: /job:localhost/replica:0/task:0/cpu:0 all devices: 
/job:localhost/replica:0/task:0/cpu:0 unknown device.

I've compiled the library like so:
bazel build -c opt //tensorflow/tools/lib_package:libtensorflow -c dbg --strip=never --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both --copt=-msse4.2 --copt=-Wno-error=stringop-overflow

I've also tried without any of the optimization or debug symbols.  I've followed your example above for loading a graph definition and running the session. I can iterate through the operations and print their names, so I know that part is working. I get the above error with a != TF_OK status, when trying to run the session.

Any ideas what I'm doing wrong?

thanks

**Comment by guillaume-michel** [comment]
@pdrews In your case you can allocate a Tensor with the C++ API then use flat to get a pointer to the memory for that particular tensor.
With that pointer you can use cv::Mat(rows, cols, type, pointer) constructor to fake a cv::Mat with the memory from the Tensor.

Then just use your cv::Mat.

Untested code:
// allocate a Tensor
Tensor inputImg(DT_FLOAT, TensorShape({1,inputheight,inputwidth,3}));
// get pointer to memory for that Tensor
float *p = inputImg.flat<float>().data();
// create a "fake" cv::Mat from it 
cv::Mat cameraImg(inputheight, inputwidth, CV_32FC3, p);

// use it here as a destination
cv::Mat imagePixels = ...; // get data from your video pipeline
imagePixels.convertTo(cameraImg, CV_32FC3);

Hope this helps

**Comment by moorage** [comment]
@guillaume-michel how would you use the (converted) `cameraImg` in the C++ API's run function which accepts a Tensor?  In other words, once `cameraImg` has the image data, how do you get it back to a Tensor?

**Comment by jimdsouza** [comment]
@guillaume-michel Any way to do this for a tensor which has a batch of images? 
Eg.
`Tensor inputImg(DT_FLOAT, TensorShape({4,inputHeight,inputWidth,3}));`

Since tensors aren't subscriptable, I'd imagine you would create tensors for each image and combine them somehow to forrn `inputImg`. If so, is there a way to combine tensors?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by skye** [comment]
I'm gonna close this as we're no longer actively working on the C++ API. Feel free to continue this discussion though.

**Comment by jimdsouza** [comment]
@skye Does "no longer actively working on the C++ API" also mean that the C++ API would eventually be deprecated/abandoned? 

The TF1.4 doc gives no indication to that.

 https://www.tensorflow.org/api_guides/cc/guide

**Comment by skye** [comment]
No, I should have been more specific. I meant that I'm no longer working on improving C++ API usability, in particular the Tensor interface, meaning there's nothing to do for this issue anymore (this functionality is currently possible in both the C API and using the Tensor C++ interface directly).

**Comment by ibadami** [comment]
> @guillaume-michel Any way to do this for a tensor which has a batch of images?
> Eg.
> `Tensor inputImg(DT_FLOAT, TensorShape({4,inputHeight,inputWidth,3}));`
> 
> Since tensors aren't subscriptable, I'd imagine you would create tensors for each image, load the `cv::Mat` into it, and combine them somehow to forrn `inputImg`. If so, is there a way to combine tensors?

@jimaldon Did you find any solution for this?

**Comment by jimaldon** [comment]
@ibadami  Yes! memcpy to the rescue

```
  float*   imgTensorFlat = inputImg.flat<float>().data();
  int      arrSize       = imageWidth * imageHeight * imageChannels;

  cv::Mat temp;
  for (int z = 0; z < imagesInBatch; ++z)
  {   
    cv::Mat inputImg = cv::imread(aInputBatch[z], CV_32F);
    inputImg.convertTo(temp, CV_32F);
    float* p = temp.ptr<float>();
    std::copy(p, p + arrSize, imgTensorFlat + z * arrSize);
  }   
```

**Comment by dviettu134** [comment]
I'm following @guillaume-michel method to convert my image to tensor as input for my Object detection model (SSD).

However, if I keep the original size of the image (1280x720), it takes long time to finish the conversion (~0.3s per image).

So I would resize the image to 300x300 before converting, it can help significantly decrease the conversion time.
But does it affect to the object detection result? (When I train the SSD model, I used the config:
fixed_shape_resizer {
        height: 300
        width: 300
      }
)

**Comment by zkxvb** [comment]
> No, I should have been more specific. I meant that I'm no longer working on improving C++ API usability, in particular the Tensor interface, meaning there's nothing to do for this issue anymore (this functionality is currently possible in both the C API and using the Tensor C++ interface directly).

have examples about how to use  this functionality?
