### ISSUE TITLE
Immediately build `tf.keras.layers.Layer` if `input_dim` or `input_shape` are specified

### ISSUE THREAD

**Issue by zakizhou** [tensorflow/tensorflow#27050]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.0alpha0
- Are you willing to contribute it (Yes/No): Y

**Describe the feature and the current behavior/state.**
Currently `tf.keras.layers.Layer`(and its subclasses like `tf.keras.layers.Dense`) is lazily built when the first time it sees input tensors since it needs to know the input shape or input dim, but after `input_dim` or `input_shape`  are specified in the constructor, there is no need for that, it should get immediately built because users expect to see variables attached to this layer right after they provide `input_dim` or `input_shape` 

**Will this change the current api? How?**
No, no need to change the current api.

**Who will benefit with this feature?**
I believe lots of users benefit with this feature

**Any Other info.**
```python
import tensorflow as tf
from tensorflow.python import keras

d = keras.layers.Dense(2, input_dim=3)
# this line should raise errors since the input_dim is 3 not 4, but it works in TF 2.0alpha0
# if `tf.keras.layers.Dense` will be immediately built if `input_dim` is specified, then
# errors that (1, 4) can't do matmul with (2, 3) will be rasied, much more clear right?
o = d(tf.random.normal(shape=(1, 4)))
```

**Comment by gshashank84** [comment]
#25780

**Comment by tanzhenyu** [comment]
@zakizhou Can you list your use cases here? eager variable creation will have many side effects. Currently this is the behavior in model level, but not layer level. Having different behavior between 1) input_shape is specified, 2) input_shape is not specified is dangerous and we need to have a strongly consistent semantics in the future.

**Comment by zakizhou** [comment]
@tanzhenyu 

```
import tensorflow as tf
import numpy as np


preloaded_weights = [np.random.normal(size=(3, 2))]
d = tf.keras.layers.Dense(2, input_dim=3, use_bias=False)
d.set_weights(preloaded_weights)
# ValueError: You called `set_weights(weights)` on layer "dense_2" with a
# weight list of length 1, but the layer was expecting 0 weights. Provided weights: ...

d.kernel.assign(preloaded_weights)
# AttributeError: 'Dense' object has no attribute 'kernel'

# So I just simply want to assign a specific weight to `d` before I pass any input to it
# but I can not do it because of lazy building  of `tf.keras.layers.Layer`.
# The only thing I can do is to call `d.build((None, 3))` before assign weights which I
# think not necessary because I already pass `input_dim=3` in the constructor
```

**Comment by tanzhenyu** [comment]
@zakizhou sounds reasonable. This can be achieved by `build` and I haven't received many requests for it. If you'd like to contribute for it, I'd be happy to review!

**Comment by zakizhou** [comment]
@tanzhenyu one way to implement eager building of `tf.keras.layers.Layer`(and its subclasses) is quite straightforward, just add a check in the constructor whether an `input_dim` is explicitly passed by user or not, if yes, build a `input_shape` from `input_dim`, and add one line `self.build(input_shape)` at the end of constructor, otherwise, still perform lazy building.

**Comment by zakizhou** [comment]
closed
