### ISSUE TITLE
compilation error on latest master

### ISSUE THREAD

**Issue by theyonibomber** [tensorflow/tensorflow#8619]
Seems to have been caused by ede5ebe54f0689a53eeaf0fb1c9a25f136ab3a69
```
$ bazel build -c opt //tensorflow/examples/android:tensorflow_demo
ERROR: /Users/yonits/dev/joytunes/tensorflow/third_party/gpus/cuda_configure.bzl:828:18: unexpected keyword 'environ' in call to repository_rule(implementation: function, *, attrs: dict or NoneType = None, local: bool = False).
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Extension file 'third_party/gpus/cuda_configure.bzl' has errors.
```

**Comment by damienmg** [comment]
Which version of Bazel are you using?

**Comment by theyonibomber** [comment]
Was using 0.4.4, upgrading to 0.4.5 seems to have solved it.
Thanks.

**Comment by jasonbunk** [comment]
Having a similar issue, build fails for me on bazel version 0.4.5.

Build fails using "git checkout ede5ebe54f0689a53eeaf0fb1c9a25f136ab3a69"
http://pastebin.com/FHt0r5kS

Build succeeds using "git checkout 450386c513a4c68d6b77f9b475dc39b442775a86" which is the commit prior to the above failing one.
http://pastebin.com/3vGHik0G

CUDA Version 8.0.61
CUDNN version 5.1.10

bazel version info:

jbunk@desktop:~/libraries$ bazel version
Build label: 0.4.5
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Mar 16 12:19:38 2017 (1489666778)
Build timestamp: 1489666778
Build timestamp as int: 1489666778

**Comment by damienmg** [comment]
Can you give the output of `export` after the failing build?

**Comment by jasonbunk** [comment]
The output of export is the same between the two commits except for ssh details I omitted.

```
jbunk@desktop:~/libraries/Tensorflow-Github$ export
declare -x DERBY_HOME="/usr/lib/jvm/java-8-oracle/db"
declare -x DISPLAY="localhost:11.0"
declare -x DYLD_LIBRARY_PATH="/home/jbunk/torch/install/lib:/home/jbunk/torch/install/lib:"
declare -x HISTFILE="/home/jbunk/.bash_eternal_history"
declare -x HISTFILESIZE=""
declare -x HISTSIZE=""
declare -x HISTTIMEFORMAT="[%F %T] "
declare -x HOME="/home/jbunk"
declare -x J2REDIR="/usr/lib/jvm/java-8-oracle/jre"
declare -x J2SDKDIR="/usr/lib/jvm/java-8-oracle"
declare -x JAVA_HOME="/usr/lib/jvm/java-8-oracle"
declare -x LANG="en_US.UTF-8"
declare -x LD_LIBRARY_PATH="/home/jbunk/torch/install/lib:/home/jbunk/torch/install/lib::/usr/local/cuda/lib64"
declare -x LESSCLOSE="/usr/bin/lesspipe %s %s"
declare -x LESSOPEN="| /usr/bin/lesspipe %s"
declare -x LOGNAME="jbunk"
declare -x LS_COLORS="rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:"
declare -x LUA_CPATH="/home/jbunk/torch/install/lib/?.so;/home/jbunk/.luarocks/lib/lua/5.1/?.so;/home/jbunk/torch/install/lib/lua/5.1/?.so;./?.so;/usr/local/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/loadall.so"
declare -x LUA_PATH="/home/jbunk/.luarocks/share/lua/5.1/?.lua;/home/jbunk/.luarocks/share/lua/5.1/?/init.lua;/home/jbunk/torch/install/share/lua/5.1/?.lua;/home/jbunk/torch/install/share/lua/5.1/?/init.lua;./?.lua;/home/jbunk/torch/install/share/luajit-2.1.0-beta1/?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua"
declare -x MAIL="/var/mail/jbunk"
declare -x OLDPWD="/home/jbunk/libraries"
declare -x PATH="/home/jbunk/torch/install/bin:/home/jbunk/bin:/home/jbunk/.local/bin:/home/jbunk/torch/install/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin"
declare -x PWD="/home/jbunk/libraries/Tensorflow-Github"
declare -x QT_QPA_PLATFORMTHEME="appmenu-qt5"
declare -x SHELL="/bin/bash"
declare -x SHLVL="1"
declare -x TERM="xterm-256color"
declare -x USER="jbunk"
declare -x XDG_RUNTIME_DIR="/run/user/1001"
declare -x XDG_SESSION_ID="52"
```

**Comment by damienmg** [comment]
`cat .bazelrc` from the tensorflow workspace?

**Comment by jasonbunk** [comment]
It appears to be empty (zero bytes) in ede5ebe54f0689a53eeaf0fb1c9a25f136ab3a69 after ./configure, while there is no ".bazelrc" at all in 450386c513a4c68d6b77f9b475dc39b442775a86. If I simply delete the empty ".bazelrc" in ede5ebe54f0689a53eeaf0fb1c9a25f136ab3a69 before `bazel build --config=opt --config=cuda ...` it still fails.

**Comment by jasonbunk** [comment]
In the latest commit 4e18625c55afdbe50e922a70a12df05320e387e0, if I revert the lines in "third_party/gpus/cuda_configure.bzl" to what they were in 450386c513a4c68d6b77f9b475dc39b442775a86, the compiliation succeeds.

**Comment by damienmg** [comment]
Ok the problem is the missing TF_* environment variable in the environment. We should check them in the .bazelrc files, let me prepare a PR for that.

**Comment by sampathchanda** [comment]
Am still seeing this issue. Can anyone help by letting me know how to fix this.

**Comment by gunan** [comment]
You need to upgrade the version of  bazel you are using.

**Comment by annakhaimovich-babylon** [comment]
have the same problem with basel version 0.26.1  

/4a5a8dc24223cbce1398873ead9ee5e3/external/org_tensorflow/third_party/gpus/cuda_configure.bzl:115:1: load() statements must be called before any other statement. First non-load() statement appears at /private/var/tmp/_bazel_anna.khaimovich/4a5a8dc24223cbce1398873ead9ee5e3/external/org_tensorflow/third_party/gpus/cuda_configure.bzl:26:1. Use --incompatible_bzl_disallow_load_after_statement=false to temporarily disable this check.
ERROR: error loading package '': in /private/var/tmp/_bazel_anna.khaimovich/4a5a8dc24223cbce1398873ead9ee5e3/external/org_tensorflow/tensorflow/workspace.bzl: Extension 'third_party/gpus/cuda_configure.bzl' has errors
