### ISSUE TITLE
tensorflow import error(tf.estimator package not installed)

### ISSUE THREAD

**Issue by 07freedom** [tensorflow/tensorflow#22342]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Centos 7
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**:1.10.0
- **Python version**:anaconda python 3.6.5
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: None
- **GPU model and memory**: None
- **Exact command to reproduce**: import tensorflow

I have installed anaconda 3 on Centos 7 and instlall tensorflow with pip.
Just import tensorflow and the error says "tf.estimator package not installed." I am not able to import tensorflow.estimator().
I have figured out one way to avoid this is to import msgpack or distributed before import tensorflow and it works just fine. But I am still looking for the right fix.

**Comment by 07freedom** [comment]
I have tried uninstall and install tensorflow & tensorflow-hub. But it doesn't work.

**Comment by harshini-gadige** [comment]
#21478

**Comment by bjvanov** [comment]
I was experiencing this error as well. It was preventing me from using some of the contrib rnn packages. I was also getting 

> cannot import name hashtable

which led me to this [SO post](https://stackoverflow.com/questions/14422976/importing-pandas-shows-importerror-cannot-import-name-hashtable).

Apparently there is some dependency on pandas that was out-of-date for me. I fixed it accordingly and now these warning are gone

`pip3 install --upgrade pandas`

**Comment by harshini-gadige** [comment]
@07freedom Can you please try to check if any of the dependencies are out-of-date and try reinstalling those.

**Comment by 07freedom** [comment]
@harshini-gadige @bjvanov thanks for the quick reply. I have already fixed the problem by upgrade pandas. I have to install Tensorflow offline from scratch so I am so glad to find the exact needed dependency.
The pandas comes with my Anaconda3-5.2.0-Linux-x86_64 is 0.23.0
After upgrade pandas with pip to 0.23.4 and it works for me.

**Comment by VadimShevchuk** [comment]
pip install pandas and **reconfigure** tensorflow, fixed the my problem.

**Comment by 07freedom** [comment]
I have run some tests and found that the version of pandas and pytz matters, when:
pandas 0.23.4--pytz 2018.5 or
pandas 0.23.0--pytz 2018.4
then tensorflow runs perfectly

**Comment by antdlc** [comment]
I have the same problem as well. I have tried (as suggested in this and other posts):
- downgrading pytz from 2018.7 to 2018.5 (with pandas already being version 0.23.4)
- downgrading pytz to 2018.4 and pandas to 0.23.0
-importing pandas before importing tensorflow
- uninstalling pandas : this got rid of the error message but surely pandas is needed to run tensorflow? (I am very new to this)

Please advise

**Comment by Abudhagir** [comment]
Requirement already up-to-date: pandas in c:\users\anaconda3\lib\site-packages (0.23.4)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.5.0 in c:\users\anaconda3\lib\site-packages (from pandas) (2.7.5)
Requirement already satisfied, skipping upgrade: pytz>=2011k in c:\users\anaconda3\lib\site-packages (from pandas) (2018.7)
Requirement already satisfied, skipping upgrade: numpy>=1.9.0 in c:\users\anaconda3\lib\site-packages (from pandas) (1.15.4)
Requirement already satisfied, skipping upgrade: six>=1.5 in c:\users\anaconda3\lib\site-packages (from python-dateutil>=2.5.0->pandas) (1.11.0)

I am also getting same error. 
tf.estimator package not installed.

Please help out

**Comment by macny** [comment]
Faced the same problem with Anaconda5.3, python3.6, and tensorflow 1.12.0: 

- pip install -U pandas (0.23.4 installed)
- pip install -U matplotlib (3.0.2 installed)

Worked for me

**Comment by antdlc** [comment]
updating to tensorflow 1.12.0 worked for me in the end

**Comment by oxhagolli** [comment]
Updating pandas alone did not help. Updating matplotlib fixed the issue for me.

**Comment by Abudhagir** [comment]
Thanks all. I resolved it

**Comment by l3lackcurtains** [comment]
Updating matplotlib helped. Thanks,

**Comment by l3lackcurtains** [comment]
Updating matplotlib helped. Thanks.

**Comment by agilebean** [comment]
> Faced the same problem with Anaconda5.3, python3.6, and tensorflow 1.12.0:
> 
> * pip install -U pandas (0.23.4 installed)
> * pip install -U matplotlib (3.0.2 installed)
> 
> Worked for me

it also works with conda:
* conda upgrade matplotlib

**Comment by PeterMitrano** [comment]
For me this had nothing to do with pandas or matplotlib. The issue was that I had installed a newer version of TF then downgraded. Uninstalling `tensorflow-estimator` and `tensorflow-gpu`, then reinstalling `tensorflow-gpu` fixed it.

**Comment by carrieeeeewithfivee** [comment]
faced the same problem, and 
tensorflow==1.13.1, 
pandas==0.23.0, 
matplotlib==1.5.1 
worked for me : )

**Comment by iiapache** [comment]
downgrading tensorflow-estimator works for me.
