### ISSUE TITLE
AARCH64 builds broken

### ISSUE THREAD

**Issue by elfringham** [tensorflow/tensorflow#56887]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

git HEAD

### Custom Code

No

### OS Platform and Distribution

CentOS 7

### Mobile device

n/a

### Python version

3.8.10

### Bazel version

5.1.1

### GCC/Compiler version

10.2.1

### CUDA/cuDNN version

n/a

### GPU model and memory

n/a

### Current Behaviour?

```shell
Build fails to complete with
"./tensorflow/compiler/xla/service/cpu/runtime_fp16.h:23:23: error: '_Float16' does not name a type"
```

### Standalone code to reproduce the issue

```shell
bazel build --config=nonccl --config=mkl_aarch64 --copt="-mtune=generic" --copt="-march=armv8-a" --copt="-O3" --copt="-fopenmp" --linkopt="-lgomp" --jobs=100 -- //tensorflow/tools/pip_package:build_pip_package
```

### Relevant log output

```shell
In file included from tensorflow/compiler/xla/service/cpu/runtime_fp16.cc:16:
./tensorflow/compiler/xla/service/cpu/runtime_fp16.h:23:23: error: '_Float16' does not name a type
   23 | using XlaF16ABIType = _Float16;
      |                       ^~~~~~~~
./tensorflow/compiler/xla/service/cpu/runtime_fp16.h:36:12: error: 'XlaF16ABIType' does not name a type
   36 | extern "C" XlaF16ABIType __gnu_f2h_ieee(float);
      |            ^~~~~~~~~~~~~
./tensorflow/compiler/xla/service/cpu/runtime_fp16.h:39:33: error: 'XlaF16ABIType' was not declared in this scope
   39 | extern "C" float __gnu_h2f_ieee(XlaF16ABIType);
      |                                 ^~~~~~~~~~~~~
./tensorflow/compiler/xla/service/cpu/runtime_fp16.h:42:12: error: 'XlaF16ABIType' does not name a type
   42 | extern "C" XlaF16ABIType __truncdfhf2(double);
      |            ^~~~~~~~~~~~~
tensorflow/compiler/xla/service/cpu/runtime_fp16.cc:63:1: error: 'XlaF16ABIType' does not name a type
   63 | XlaF16ABIType ABSL_ATTRIBUTE_WEAK __gnu_f2h_ieee(float float_value) {
      | ^~~~~~~~~~~~~
tensorflow/compiler/xla/service/cpu/runtime_fp16.cc:117:27: error: redefinition of 'float __gnu_h2f_ieee'
  117 | float ABSL_ATTRIBUTE_WEAK __gnu_h2f_ieee(XlaF16ABIType hf) {
      |                           ^~~~~~~~~~~~~~
In file included from tensorflow/compiler/xla/service/cpu/runtime_fp16.cc:16:
./tensorflow/compiler/xla/service/cpu/runtime_fp16.h:39:18: note: 'float __gnu_h2f_ieee' previously defined here
   39 | extern "C" float __gnu_h2f_ieee(XlaF16ABIType);
      |                  ^~~~~~~~~~~~~~
tensorflow/compiler/xla/service/cpu/runtime_fp16.cc:117:42: error: 'XlaF16ABIType' was not declared in this scope
  117 | float ABSL_ATTRIBUTE_WEAK __gnu_h2f_ieee(XlaF16ABIType hf) {
      |                                          ^~~~~~~~~~~~~
tensorflow/compiler/xla/service/cpu/runtime_fp16.cc:141:1: error: 'XlaF16ABIType' does not name a type
  141 | XlaF16ABIType ABSL_ATTRIBUTE_WEAK __truncdfhf2(double d) {
      | ^~~~~~~~~~~~~
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```
</details>

**Comment by elfringham** [comment]
@cfRod @nSircombe @penpornk

**Comment by elfringham** [comment]
Introduced by https://github.com/tensorflow/tensorflow/commit/579c67bd60220fe66a29318191f0850ff0aa825f

**Comment by elfringham** [comment]
@d0k

**Comment by elfringham** [comment]
@d0k on AARCH64 the availability of _Float16 depends on if the target CPU includes the support or not. The documentation is sadly lacking in explaining this. So the default compile settings of '--copt=-march=armv8-a' result in the above failure. But if targetting a CPU with the needed support by '--copt=-march=armv8-a+fp16' then _Float16 is available and the code would compile, but then generate an illegal instruction trap if run on a CPU without the support.

**Comment by d0k** [comment]
The purpose of this code is providing the proper ABI for fp16 function calls when the hardware doesn't support fp16 natively. On x86 fp16 used to be passed in GPR but now moved to floating point registers. I think on aarch64 it's always an fp register, but I don't know that architecture well.

The main problem here is that GCC is essentially lying about the type, which also contradicts the documentation. I'll put
in a hack to not use _Float16 on ARM64 GCC. Everything seems to be working fine with ARM64 Clang, which doesn't define `__FLT16_MANT_DIG__` when the type isn't actually there.

Note that there is no _Float16 arithmetic done here, XLA just needs to match the ABI between JIT-compiled code and runtime functions. Compilers making type availability dependent on hardware features and then providing no macros
for detecting those features is really awful.
