### ISSUE TITLE
module 'tensorflow.python.keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'

### ISSUE THREAD

**Issue by flydragon2018** [tensorflow/tensorflow#38012]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),

the function populate_dict_with_module_objects() is missed in the 2.2.0rc2

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): 
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: 
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): 
- Python version: - Bazel
version (if compiling from source):
- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version: - GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@flydragon2018 
please update the template for us to help you resolve the issue, we will not be able to help with out the version, simple stand alone code before which the error was faced.

**Comment by Saduf2019** [comment]
on basis of error shared, please refer to [this link](https://github.com/tensorflow/probability/issues/255) and let us know if it helps

**Comment by flydragon2018** [comment]
the code is simply not there compared with the code on github.

**Comment by Saduf2019** [comment]
@flydragon2018 
 
could you please share exact sequence of steps before this issue occurred

**Comment by Saduf2019** [comment]
@flydragon2018

could you please update as per above comment

**Comment by Saduf2019** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by oilst-source** [comment]
I have the same problem:

AttributeError: module 'tensorflow.python.keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'

Any fix for this error?

**Comment by anndr01d** [comment]
I am also experiencing this issue. I am still very new to tf. I was running throught some tutorials. VS Code stops at the 'import tensorflow' line and returns the error:

module 'tensorflow.python.keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'

This exact script was working BEFORE I installed CUDA drivers, but sent a warning saying it could not find the 'cuart64_101.dll'. After installing the drivers, it states that the dll was found, then immediately errors at the import. 

All software is the most recent versions:

tensorflow 2.2.0rc4
cuda 10.2.89

**Comment by sibyjackgrove** [comment]
I am also experiencing the same error when importing tensorflow after installing tensorflow 2.2.0rc4.
` AttributeError: module 'tensorflow.python.keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'`

**Comment by diegostaPy** [comment]
I have the same problem with tensorflow 2.2.0rc4
cuda 10.2.89
cudnn-10.2-linux-x64-v7.6.5.32
TensorRT-7.0.0.11

**Comment by PiyushDatta** [comment]
running:
 `python tensorflow\tensorflow\python\keras\engine\sequential.py`

will get the error:

>   File "tensorflow\python\keras\engine\sequential.py", line 350, in Sequential
>     @generic_utils.default
> AttributeError: module 'tensorflow.python.keras.utils.generic_utils' has no attribute 'default'

this is from the build method in sequential.py
```
  @generic_utils.default
  def build(self, input_shape=None):
```

**Issue:** Seems sequential.py not picking up the `def default(method): ` function in generic_utils.py on line 777.

**Comment by nvs-abhilash** [comment]
It worked for me after uninstalling the `tf-nightly` packages.

```
pip list | grep tf
```

Then reinstall tensorflow
```python
pip install tensorflow --upgrade --force-reinstall
```

**Comment by anndr01d** [comment]
> 
> 
> It worked for me after uninstalling the `tf-nightly` packages.
> 
> ```shell
> pip list | grep tf
> ```
> 
> Then reinstall tensorflow
> 
> ```shell
> pip install tensorflow --upgrade --force-reinstall
> ```

This worked for me!! Thank you! Not sure what tf-nightly is or if I will want it later, but for now 'weeee'

**Comment by leqnam** [comment]
I have the same issue since try the NMT which is require ft_nightly, so it mays conflict with tf. First uninstall tf_nightly and then force reinstall tf.
```
pip uninstall tf-nightly
pip install tensorflow --upgrade --force-reinstall
```

**Comment by joe983** [comment]
I'm having this issue and uninstalling tf-nightly
and forcing reinstall of tensorflow is not helping.

Any other ideas please folks?

**Comment by viswanath27** [comment]
I have tried to force upgrade **tensorflow 2.2.0** and I am landing in same issue. 
**Keras version 2.3.1** 

Any help here is appreciated to help fix this issue.
 

Traceback (most recent call last):
  File "image_classification.py", line 2, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/__init__.py", line 84, in <module>
    from tensorflow.python import keras
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/__init__.py", line 27, in <module>
    from tensorflow.python.keras import models
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/models.py", line 24, in <module>
    from tensorflow.python.keras import metrics as metrics_module
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/metrics.py", line 37, in <module>
    from tensorflow.python.keras.engine import base_layer
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 51, in <module>
    from tensorflow.python.keras import initializers
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/initializers/__init__.py", line 127, in <module>
    populate_deserializable_objects()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/initializers/__init__.py", line 85, in populate_deserializable_objects
    generic_utils.populate_dict_with_module_objects(
AttributeError: module 'tensorflow.python.keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'

**Comment by esozmen** [comment]
Thanks!

**Comment by danial880** [comment]
Please copy "populate_dict_with_module_objects" function from this [link](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/utils/generic_utils.py) and add it your "generic_utils.py"

**Comment by MaxHeuillet** [comment]
I am having the same problem.

It worked fine, then I downloaded CUDA, CuDNN and tensorflow gpu and now i get this error.
I do not have tf-nightly installed.

**Comment by celowsky** [comment]
The solution above from @danial880 worked for me

**Comment by Honghe** [comment]
@danial880 it worked on Tensorflow 2.3.1.

**Comment by 8sukanya8** [comment]
> Please copy "populate_dict_with_module_objects" function from this [link](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/utils/generic_utils.py) (line 827 to 832) and add it to "generic_utils.py"

The solution by @danial880 worked for me on Tensorflow 2.3.1

**Comment by clime** [comment]
Still an issue: https://github.com/keras-team/keras/issues/14632

**Comment by yuanshancheng** [comment]
You simply need to reinstall tensorflow as shown by @lequan above. Works for me.

**Comment by AndreyStille** [comment]
> Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

go fuck yourself

**Comment by statco19** [comment]
@danial880 it worked for me. Tensorflow 2.5.0. actually after I copied and pasted "populate_dict_with_module_objects" function, another error message popped up which said I need "to_snake_case" function. So, I copied and pasted "to_snake_case" from the same page.
Then another error popped up and said it needs "re" package. So, I wrote the code "import re" at the top of "generic_utils.py." And finally, it works.
Python version 3.7.7, tensorflow version 2.5.0

**Comment by harshbangad** [comment]
> @danial880 it worked for me. Tensorflow 2.5.0. actually after I copied and pasted "populate_dict_with_module_objects" function, another error message popped up which said I need "to_snake_case" function. So, I copied and pasted "to_snake_case" from the same page.
> Then another error popped up and said it needs "re" package. So, I wrote the code "import re" at the top of "generic_utils.py." And finally, it works.
> Python version 3.7.7, tensorflow version 2.5.0

That worked for me. Thanks

**Comment by hojnicki307** [comment]
> @danial880 it worked for me. Tensorflow 2.5.0. actually after I copied and pasted "populate_dict_with_module_objects" function, another error message popped up which said I need "to_snake_case" function. So, I copied and pasted "to_snake_case" from the same page.
> Then another error popped up and said it needs "re" package. So, I wrote the code "import re" at the top of "generic_utils.py." And finally, it works.
> Python version 3.7.7, tensorflow version 2.5.0

This also worked for me, Python 3.8.10. Thanks!

**Comment by lamtougui** [comment]
%tensorflow_version 1.x

**Comment by sanpy2910** [comment]
> @danial880 it worked for me. Tensorflow 2.5.0. actually after I copied and pasted "populate_dict_with_module_objects" function, another error message popped up which said I need "to_snake_case" function. So, I copied and pasted "to_snake_case" from the same page.
> Then another error popped up and said it needs "re" package. So, I wrote the code "import re" at the top of "generic_utils.py." And finally, it works.
> Python version 3.7.7, tensorflow version 2.5.0

thanx a lot it worked for me

**Comment by Namangarg110** [comment]
> Please copy "populate_dict_with_module_objects" function from this [link](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/utils/generic_utils.py) (line 827 to 832) and add it to "generic_utils.py"

it is already there in my case still facing the same issue

**Comment by EverestLi** [comment]
> @danial880 it worked for me. Tensorflow 2.5.0. actually after I copied and pasted "populate_dict_with_module_objects" function, another error message popped up which said I need "to_snake_case" function. So, I copied and pasted "to_snake_case" from the same page.
> Then another error popped up and said it needs "re" package. So, I wrote the code "import re" at the top of "generic_utils.py." And finally, it works.
> Python version 3.7.7, tensorflow version 2.5.0

it worked for me,Python version 3.8.10,tensorflow version 2.5.0,thanks!

**Comment by stacklikemind** [comment]
The issue is **not occuring** in tensorflow==2.6.0rc0 and python 3.9.6 for me.

**Comment by execptionerror** [comment]
[[Already Solved] AttributeError: module ‘keras.utils.generic_utils’ has no attribute ‘populate_dict_with_module_objects’
](https://exerror.com/attributeerror-module-keras-utils-generic_utils-has-no-attribute-populate_dict_with_module_objects/)
