### PR TITLE
Fix tf.signal.inverse_stft AttributeError in tf 2.0

### LINKED ISSUE #28444: tf.signal.inverse_stft AttributeError: 'int' object has no attribute 'value' in 2.0.0-alpha0
There appears to be a bug in tf.signal.inverse_stft, when testing for `real_frames.shape[-1].value is None`, where `real_frames.shape[-1]` is an integer, and does not have a `value`. 

Reproducible code:
```
print(tf.__version__)
frame_length = 512
frame_step = 256
signal = tf.random.uniform(shape=(1000,))
x = tf.signal.stft(signal, frame_length, frame_step)
y = tf.signal.inverse_stft(x, frame_length, frame_step)
```

```
2.0.0-alpha0
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-261-d4526d62007f> in <module>
----> 1 tf.signal.inverse_stft(x, frame_length, frame_step)

/mnt/cube/tsainbur/conda_envs/tpy3/lib/python3.6/site-packages/tensorflow/python/ops/signal/spectral_ops.py in inverse_stft(stfts, frame_length, frame_step, fft_length, window_fn, name)
    242     if (frame_length_static is None or
    243         real_frames.shape.ndims is None or
--> 244         real_frames.shape[-1].value is None):
    245       real_frames = real_frames[..., :frame_length]
    246       real_frames_rank = array_ops.rank(real_frames)

AttributeError: 'int' object has no attribute 'value'
```

### PR DESCRIPTION
**Pull request by yongtang**
This fix tries to address the issue raised in #28444 where tf.signal.inverse_stft causes AttributeError with:
```
frame_length = 512
frame_step = 256
signal = tf.random.uniform(shape=(1000,))
x = tf.signal.stft(signal, frame_length, frame_step)
y = tf.signal.inverse_stft(x, frame_length, frame_step)

AttributeError: 'int' object has no attribute 'value'
```

The issue is that, in `inverse_stft`, `real_frames.shape[-1].value` has been used to get the value of the dim -1 for shape. However, the `real_frames.shape[-1].value` only works in non-eager mode where shape gives list of `Dimension` (value works). It does not work in eager mode (2.0) where shape gives list of ints.

This fix replaces with `real_frames.shape.as_list()[-1]` which should work in eager and non-eager mode.

This fix fixes #28444.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Review by rryan — APPROVED** [review]
Thank you!
