### ISSUE TITLE
Float 16 quantization error

### ISSUE THREAD

**Issue by raghavgurbaxani** [tensorflow/tensorflow#39066]
Hi 

I get the following error - 

`"tflite.py", line 5, in <module>
    converter.target_spec.supported_types = [tf.lite.constants.FLOAT16]
AttributeError: module 'tensorflow_core._api.v2.lite' has no attribute 'constants'`

while trying the following code to quantize my .pb file to float 16 

```
import tensorflow as tf
converter = tf.lite.TFLiteConverter.from_saved_model('out/')
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_types = [tf.lite.constants.FLOAT16]
tflite_quant_model = converter.convert()
```

Tensorflow version 2.1.0, OS - Mac

**Comment by gargn** [comment]
There are details on compatibility between `tf.lite.constants` in 1.X to 2.0 available [here](https://www.tensorflow.org/lite/convert/1x_compatibility#liteconstants).

Something like the following should work:
```
import tensorflow as tf
converter = tf.lite.TFLiteConverter.from_saved_model('out/')
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_types = [tf.float16]
tflite_quant_model = converter.convert()
```

**Comment by raghavgurbaxani** [comment]
Thank you for your response @gargn . I tried the following code above and get the following error - 

```
 File "tflite.py", line 13, in <module>
    tflite_quanit_model = converter.convert()
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/lite/python/lite.py", line 418, in convert
    raise ValueError("This converter can only convert a single "
ValueError: This converter can only convert a single ConcreteFunction. Converting multiple functions is under development.
$ python3 tflite.py 
2020-05-01 14:30:08.503886: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-05-01 14:30:08.522133: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fa891dc1140 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-05-01 14:30:08.522153: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "tflite.py", line 5, in <module>
    tflite_quant_model = converter.convert()
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/lite/python/lite.py", line 418, in convert
    raise ValueError("This converter can only convert a single "
ValueError: This converter can only convert a single ConcreteFunction.
```

**Comment by raghavgurbaxani** [comment]
@gargn  any update ?

**Comment by yefengjie** [comment]
same bug to me
`
Traceback (most recent call last):
  File "int_optimize_convert.py", line 7, in <module>
    converter.inference_type = tf.lite.constants.QUANTIZED_UINT8
AttributeError: module 'tensorflow._api.v2.lite' has no attribute 'constants'
`

**Comment by Saduf2019** [comment]
@raghavgurbaxani 
Is this still an issue

**Comment by stefano555** [comment]
Hi,

at first I had the same issue than I tried 

converter = tf.lite.TFLiteConverter.from_saved_model('/path/to/saved/model')
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_types = [tf.float16]
tflite_model = converter.convert()

and it worked perfectly. TF version: 2.3.0-dev20200608

**Comment by Saduf2019** [comment]
@raghavgurbaxani
Please update if this is still an issue.

**Comment by Saduf2019** [comment]
Moving this to closed status as it works in 2.3-dev as informed.

**Comment by raghavgurbaxani** [comment]
@Saduf2019 @stefano555  it does not work for me . I tried with tf-nightly==2.3.0-dev20200608

But I still get the error - 
```
File "try_fp16.py", line 2, in <module>
    converter = tf.lite.TFLiteConverter.from_keras_model('out/')
  File "/home/ahi/.local/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 980, in from_saved_model
    raise ValueError("Only support a single signature key.")
ValueError: Only support a single signature key.
```

@Saduf2019  can you help ?

**Comment by raghavgurbaxani** [comment]
@Saduf2019  could you reopen the issue , I am still unable to get it to work

**Comment by jvishnuvardhan** [comment]
@raghavgurbaxani May be something not right with the shared model. When I tried to load the model, code is throwing the following error. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/ab88f7074ef586b0b496f9b0f4e0f4a9/untitled953.ipynb). 

Can you please share model building code? Thanks!

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-ee9580594b88> in <module>()
      1 import tensorflow as tf
----> 2 model = tf.keras.models.load_model('/content/EAST_IC15_13_model.h5')
      3 converter = tf.lite.TFLiteConverter.from_keras_model(model)
      4 converter.optimizations = [tf.lite.Optimize.DEFAULT]
      5 converter.target_spec.supported_types = [tf.float16]

1 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/hdf5_format.py in load_model_from_hdf5(filepath, custom_objects, compile)
    173     model_config = f.attrs.get('model_config')
    174     if model_config is None:
--> 175       raise ValueError('No model found in config file.')
    176     model_config = json.loads(model_config.decode('utf-8'))
    177     model = model_config_lib.model_from_config(model_config,

ValueError: No model found in config file.
```
