### PR TITLE
micro: fix null-dereference build warning/error on g++ 10.2

### LINKED ISSUE #45381: micro: null-dereference warning breaks Makefile build on g++ 10.2
@tensorflow/micro

### Description

Changes merged yesterday in 17130a8f trigger a warning treated as an error that breaks a Makefile build on g++10.2:
```
% git describe --all --long
heads/master-0-g34f2adacdbe

% make -f tensorflow/lite/micro/tools/make/Makefile test
tensorflow/lite/micro/tools/make/downloads/flatbuffers already exists, skipping the download.
tensorflow/lite/micro/tools/make/Makefile:478: warning: overriding recipe for target 'tensorflow/lite/micro/tools/make/downloads/person_model_int8'
tensorflow/lite/micro/tools/make/Makefile:478: warning: ignoring old recipe for target 'tensorflow/lite/micro/tools/make/downloads/person_model_int8'
g++ -std=c++11 -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-unwind-tables -ffunction-sections -fdata-sections -fmessage-length=0 -DTF_LITE_STATIC_MEMORY -DTF_LITE_DISABLE_X86_NEON -O3 -Werror -Wsign-compare -Wdouble-promotion -Wshadow -Wunused-variable -Wmissing-field-initializers -Wunused-function -Wswitch -Wvla -Wall -Wextra -Wstrict-aliasing -Wno-unused-parameter   -DTF_LITE_USE_CTIME -I. -Itensorflow/lite/micro/tools/make/downloads/gemmlowp -Itensorflow/lite/micro/tools/make/downloads/flatbuffers/include -Itensorflow/lite/micro/tools/make/downloads/ruy -Itensorflow/lite/micro/tools/make/downloads/kissfft -c tensorflow/lite/micro/kernels/detection_postprocess.cc -o tensorflow/lite/micro/tools/make/gen/linux_x86_64/obj/tensorflow/lite/micro/kernels/detection_postprocess.o
tensorflow/lite/micro/kernels/detection_postprocess.cc: In function ‘TfLiteStatus tflite::{anonymous}::Eval(TfLiteContext*, TfLiteNode*)’:
tensorflow/lite/micro/kernels/detection_postprocess.cc:590:58: error: potential null pointer dereference [-Werror=null-dereference]
  590 |   tflite::micro::GetTensorData<float>(num_detections)[0] =
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
  591 |       size_of_sorted_indices;
      |       ~~~~~~~~~~~~~~~~~~~~~~
tensorflow/lite/micro/kernels/detection_postprocess.cc:686:58: error: potential null pointer dereference [-Werror=null-dereference]
  686 |   tflite::micro::GetTensorData<float>(num_detections)[0] = output_box_index;
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make: *** [tensorflow/lite/micro/tools/make/Makefile:490: tensorflow/lite/micro/tools/make/gen/linux_x86_64/obj/tensorflow/lite/micro/kernels/detection_postprocess.o] Error 1
```

This does not trigger a build error on tests run via `bazel test tensorflow/lite/micro/kernels:all:`. Perhaps that uses a different compiler than the `make`-initiated build.

### System information

This is with the native g++ in Debian bullseye:
```
% g++ --version
g++ (Debian 10.2.0-19) 10.2.0
[....]
```

### PR DESCRIPTION
**Pull request by rkuester**
Without the added ENSURE, g++ flags an:

    error: potential null pointer dereference [-Werror=null-dereference]

in both of these locations while building from the Makefile a la:

    % g++ --version
    g++ (Debian 10.2.0-19) 10.2.0

    % make -f tensorflow/lite/micro/tools/make/Makefile test

which breaks the build.

Fixes #45381.

----
Not sure if this is the best way to fix this. The warning-as-error is annoying considering this is a pretty straightforward uses of GetEvalOutput and GetTensorData. Not certain why it isn't triggered on other uses of the return from GetTensorData, perhaps being within control-flow constructs causes g++ to assume the nullptr case is already handled.

### CODE REVIEW

**Comment by rkuester** [comment]
The underlying issue was fixed by a different means. See #45381.
