### ISSUE TITLE
no attribute 'ConfigProto' & no attribute '_MTCNN__session'

### ISSUE THREAD

**Issue by kyimin11** [tensorflow/tensorflow#33317]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Window 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pycharm addons
- TensorFlow version: 2.0.0
- Python version:3.7.2
- Installed using virtualenv? pip? conda?:pip

Rookie from China, not a native speaker. Working on tutorials at 'https://machinelearningmastery.com/how-to-perform-face-recognition-with-vggface2-convolutional-neural-network-in-keras/'. 
Problem is that I couldn't install the previous tensorflow version in >Project Interpreter>package of Pycharm no matter how I tried to install the other packages related with tensorflow. So that I installed version 2.0.0 which I've known that version 2.0.0 will not work as expected as is mentioned in that tutorial. 
Keyed those first part '**How to Detect Faces for Face Recognition**' codes. Here are the Erorrs:
AttributeError: module 'tensorflow' has no attribute 'ConfigProto'
Exception ignored in: <function MTCNN.__del__ at 0x00000199DEC60B70>
Traceback (most recent call last):
  File "C:\PycharmProjects\VGG\venv\lib\site-packages\mtcnn\mtcnn.py", line 616, in __del__
    self.__session.close()
AttributeError: 'MTCNN' object has no attribute '_MTCNN__session'

Then I found ways to solve this problem but couldn't quite understand which push me to post this issue of course the first time posting things.

Any suggestions and help are warmly welcomed. Thanks a lot.

Kym

**Comment by ravikyram** [comment]
@kyimin11 

As per my understanding you have installed TF 2.0.0. But you want to install previous TF versions.Please, let us know where exactly you are facing the issue with tensorflow. It will be great if you share  simple standalone code, then it is easy for localizing the issue faster. Thanks again.!

**Comment by fisakhan** [comment]
I could successfully run mtcnn (https://github.com/ipazc/mtcnn) with TF 2.0.0. Please check the version of mtcnn. The latest version of mtcnn is 0.0.9 that can work with TF 2.0.0.
