### ISSUE TITLE
Unable to build Tensorflow 2.3 on OSX with LLVM

### ISSUE THREAD

**Issue by ianlokh** [tensorflow/tensorflow#43421]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution: OSX 10.15.6
- TensorFlow installed from: source
- TensorFlow version: 2.3
- Python version: 3.7
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): clang version 10.0.1 
- CUDA/cuDNN version: No
- GPU model and memory: No GPU

**Describe the problem**

I am unable to build from source and I keep getting errors around:
> bazel-out/darwin-opt-exec-50AE0418/bin/tensorflow/core/protobuf/saved_object_graph.pb.h:131:3: error: expected identifier TRUE = 1,
> In file included from bazel-out/darwin-opt-exec-50AE0418/bin/tensorflow/core/protobuf/meta_graph.pb.h:43:
bazel-out/darwin-opt-exec-50AE0418/bin/tensorflow/core/protobuf/saved_object_graph.pb.h:132:3: error: expected identifier
  FALSE = 2,
  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/mach/boolean.h:85:17: note: expanded from macro 'FALSE'
#define FALSE   0

I tried with different compilers from brew but this error keeps appearing.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

% export BAZEL_USE_CPP_ONLY_TOOLCHAIN=1
% export CC=/usr/local/opt/llvm/bin/clang
% bazel build --action_env CC=/usr/local/opt/llvm/bin/clang  --config=noaws --config=nogcp --config=mkl -c opt --copt=-O2 --cxxopt=-D_GLIBCXX_USE_CXX11_ABI=0 --copt=-mfma --copt=-mavx2 //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**

Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=174
INFO: Reading rc options for 'build' from /Users/stb/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /Users/stb/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=0 --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=short_logs --config=v2
INFO: Reading rc options for 'build' from /Users/stb/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/Users/stb/opt/anaconda3/envs/tfmkl_py37/bin/python3 --action_env PYTHON_LIB_PATH=/Users/stb/opt/anaconda3/envs/tfmkl_py37/lib/python3.7/site-packages --python_path=/Users/stb/opt/anaconda3/envs/tfmkl_py37/bin/python3 --config=xla --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:short_logs in file /Users/stb/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /Users/stb/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file /Users/stb/tensorflow/.bazelrc: --define=with_xla_support=true
INFO: Found applicable config definition build:noaws in file /Users/stb/tensorflow/.bazelrc: --define=no_aws_support=true
INFO: Found applicable config definition build:nogcp in file /Users/stb/tensorflow/.bazelrc: --define=no_gcp_support=true
INFO: Found applicable config definition build:mkl in file /Users/stb/tensorflow/.bazelrc: --define=build_with_mkl=true --define=enable_mkl=true --define=tensorflow_mkldnn_contraction_kernel=0 -c opt
INFO: Found applicable config definition build:macos in file /Users/stb/tensorflow/.bazelrc: --copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -0400"
DEBUG: Repository io_bazel_rules_docker instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule git_repository defined at:
  /private/var/tmp/_bazel_stb/c17790719609824de969482a41b5bf78/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18: in <toplevel>
INFO: Analyzed target //tensorflow/tools/pip_package:build_pip_package (390 packages loaded, 30618 targets configured).
INFO: Found 1 target...
ERROR: /Users/stb/tensorflow/tensorflow/compiler/mlir/tensorflow/BUILD:1620:1: C++ compilation of rule '//tensorflow/compiler/mlir/tensorflow:compile_mlir_util_no_tf_dialect_passes' failed (Exit 1)
In file included from tensorflow/compiler/mlir/tensorflow/utils/compile_mlir_util.cc:16:
In file included from ./tensorflow/compiler/mlir/tensorflow/utils/compile_mlir_util.h:29:
In file included from ./tensorflow/core/common_runtime/device.h:42:
In file included from ./tensorflow/core/framework/resource_mgr.h:32:
./tensorflow/core/framework/type_index.h:61:17: warning: unused variable 'hash_bit' [-Wunused-variable]
    static bool hash_bit[1];
                ^
In file included from tensorflow/compiler/mlir/tensorflow/utils/compile_mlir_util.cc:45:
In file included from ./tensorflow/compiler/mlir/tensorflow/translate/import_model.h:25:
In file included from ./tensorflow/cc/saved_model/bundle_v2.h:28:
In file included from bazel-out/darwin-opt-exec-50AE0418/bin/tensorflow/core/protobuf/meta_graph.pb.h:43:
bazel-out/darwin-opt-exec-50AE0418/bin/tensorflow/core/protobuf/saved_object_graph.pb.h:131:3: error: expected identifier
  TRUE = 1,
  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/mach/boolean.h:81:17: note: expanded from macro 'TRUE'
#define TRUE    1
                ^
In file included from tensorflow/compiler/mlir/tensorflow/utils/compile_mlir_util.cc:45:
In file included from ./tensorflow/compiler/mlir/tensorflow/translate/import_model.h:25:
In file included from ./tensorflow/cc/saved_model/bundle_v2.h:28:
In file included from bazel-out/darwin-opt-exec-50AE0418/bin/tensorflow/core/protobuf/meta_graph.pb.h:43:
bazel-out/darwin-opt-exec-50AE0418/bin/tensorflow/core/protobuf/saved_object_graph.pb.h:132:3: error: expected identifier
  FALSE = 2,
  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/mach/boolean.h:85:17: note: expanded from macro 'FALSE'
#define FALSE   0
                ^
In file included from tensorflow/compiler/mlir/tensorflow/utils/compile_mlir_util.cc:45:
In file included from ./tensorflow/compiler/mlir/tensorflow/translate/import_model.h:25:
In file included from ./tensorflow/cc/saved_model/bundle_v2.h:28:
In file included from bazel-out/darwin-opt-exec-50AE0418/bin/tensorflow/core/protobuf/meta_graph.pb.h:43:
bazel-out/darwin-opt-exec-50AE0418/bin/tensorflow/core/protobuf/saved_object_graph.pb.h:138:31: error: cannot initialize a variable of type 'const tensorflow::ExperimentalCompile' with an rvalue of type 'int'
constexpr ExperimentalCompile ExperimentalCompile_MAX = FALSE;
                              ^                         ~~~~~
1 warning and 3 errors generated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /Users/stb/tensorflow/tensorflow/python/tools/BUILD:82:1 C++ compilation of rule '//tensorflow/compiler/mlir/tensorflow:compile_mlir_util_no_tf_dialect_passes' failed (Exit 1)
INFO: Elapsed time: 4667.715s, Critical Path: 318.82s
INFO: 5927 processes: 5927 local.
FAILED: Build did NOT complete successfully

**Comment by ravikyram** [comment]
@ianlokh 

Just to verify did you follow the instructions mentioned [here.](https://www.tensorflow.org/install/source#macos_1).
Plese, see tested build configurations from [here](https://www.tensorflow.org/install/source#cpu_2).Thanks!

**Comment by ianlokh** [comment]
Hi Ravikyram, thanks for the follow up. Yes I followed the instructions but as my Xcode version is 12, I downloaded llvm 10.0.1 from brew and tried to compile using the llvm 10.0.1 as per build configuration. However I keep getting into the same issue

**Comment by ianlokh** [comment]
Hi as a correction, I used bazel 3.1 and llvm 10.0.1

**Comment by ianlokh** [comment]
> @ianlokh
> 
> Just to verify did you follow the instructions mentioned [here.](https://www.tensorflow.org/install/source#macos_1).
> Please, see tested build configurations from [here](https://www.tensorflow.org/install/source#cpu_2).Thanks!

Hi Ravikyram, thanks for the follow up. Yes I followed the instructions but as my Xcode version is 12, I downloaded llvm 10.0.1 from brew and tried to compile using the llvm 10.0.1 as per build configuration. However I keep getting into the same issue.

As a correction to the issue posted, I used bazel 3.1 and llvm 10.0.1. This is as per tested build configuration listed on the Tensorflow webpage

**Comment by lgeiger** [comment]
I am running into the same problem with XCode 12.

@ravikyram it seems like the problem has been introduced by 57f0a5e0b67720f0bc94e4decefc09fbff2f2416. Reverting the commit fixes the build issue for me.

**Comment by ianlokh** [comment]
> I am running into the same problem with XCode 12.
> 
> @ravikyram it seems like the problem has been introduced by [57f0a5e](https://github.com/tensorflow/tensorflow/commit/57f0a5e0b67720f0bc94e4decefc09fbff2f2416). Reverting the commit fixes the build issue for me.

Hi Lukas, thanks for your inputs. How do I go about getting the previous commit? I ran "git clone https://github.com/tensorflow/tensorflow.git" and assumed that it was the latest stable version.

**Comment by freedomtan** [comment]
use ON/OFF instead of TRUE/FALSE should work.

```diff
diff --git a/tensorflow/core/protobuf/saved_object_graph.proto b/tensorflow/core/protobuf/saved_object_graph.proto
index e4293bcddf..c915d0224c 100644
--- a/tensorflow/core/protobuf/saved_object_graph.proto
+++ b/tensorflow/core/protobuf/saved_object_graph.proto
@@ -153,8 +153,8 @@ message SavedVariable {
 // See `tf.function` for details.
 enum ExperimentalCompile {
   NONE = 0;
-  TRUE = 1;
-  FALSE = 2;
+  ON = 1;
+  OFF = 2;
 }
 
 // Represents `FunctionSpec` used in `Function`. This represents a
diff --git a/tensorflow/python/saved_model/function_serialization.py b/tensorflow/python/saved_model/function_serialization.py
index 777af9bd5b..9660710c9d 100644
--- a/tensorflow/python/saved_model/function_serialization.py
+++ b/tensorflow/python/saved_model/function_serialization.py
@@ -50,8 +50,8 @@ def _serialize_function_spec(function_spec, coder):
   # See `tf.function` and the ExperimentalCompile proto for details.
   proto.experimental_compile = {
       None: saved_object_graph_pb2.ExperimentalCompile.NONE,
-      True: saved_object_graph_pb2.ExperimentalCompile.TRUE,
-      False: saved_object_graph_pb2.ExperimentalCompile.FALSE,
+      True: saved_object_graph_pb2.ExperimentalCompile.ON,
+      False: saved_object_graph_pb2.ExperimentalCompile.OFF,
   }.get(function_spec.experimental_compile)
 
   return proto

```

**Comment by ianlokh** [comment]
Hi Lukas and Koan-sin, thank you for your help!

I eventually managed to compile it as suggested by Lukas - to revert to the previous commit.

git checkout b95f88a5e759367ae80bad988fdd35cbd0f604b4

Thanks again!
