### ISSUE TITLE
make_adv_reg_config not found

### ISSUE THREAD

**Issue by fbadine** [tensorflow/tensorflow#32208]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

While trying to run the code given on https://www.tensorflow.org/neural_structured_learning/ I ran into the following error:
AttributeError: module 'neural_structured_learning.lib' has no attribute 'make_adv_reg_config'
I have already installed neural_structured_learning using !pip install neural_structured_learning and I am working on TF 2.0.0-rc0 on Colab (also tried it on 1.14)
I have also check the code on github and couldn't find make_adv_reg_config in neural_structured_learning/lib/*

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by AmalVijayan** [comment]
Seems like the method make_adv_reg_config() was moved to the configs module. The below code works:
`adv_config = nsl.configs.make_adv_reg_config(multiplier=0.2, adv_step_size=0.05)`

**Comment by fbadine** [comment]
Thank you for your response.
It's working now

**Comment by ymodak** [comment]
Closing this issue since it's resolved. Thanks!
https://www.tensorflow.org/neural_structured_learning/api_docs/python/nsl/configs/make_adv_reg_config
