### ISSUE TITLE
Unit test //tensorflow/tsl/framework/convolution:spatial_convolutions_test fails to build

### ISSUE THREAD

**Issue by elfringham** [tensorflow/tensorflow#59680]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

git HEAD

### Custom Code

No

### OS Platform and Distribution

RHEL 8.7

### Mobile device

n/a

### Python version

3.9.13

### Bazel version

5.3.0

### GCC/Compiler version

10.3.0

### CUDA/cuDNN version

n/a

### GPU model and memory

n/a

### Current Behaviour?

```shell
When building for AARCH64 the unit test //tensorflow/tsl/framework/convolution:spatial_convolutions_test fails to build with

./tensorflow/tsl/framework/convolution/eigen_spatial_convolutions-inl.h:1490:27: error: static assertion failed: YOU_MADE_A_PROGRAMMING_MISTAKE
```

### Standalone code to reproduce the issue

```shell
bazel test --test_timeout=300,500,-1,-1 --flaky_test_attempts=3 --test_output=all --cache_test_results=no --noremote_accept_cached --config=mkl_aarch64_threadpool --copt="-mtune=generic" --copt="-march=armv8-a" --copt="-O3" --build_tag_filters=-no_oss,-oss_serial,-gpu,-tpu,-benchmark-test,-v1only,-no_aarch64,-requires-gpu --test_tag_filters=-no_oss,-oss_serial,-gpu,-tpu,-benchmark-test,-v1only,-no_aarch64,-requires-gpu --verbose_failures --build_tests_only -- //tensorflow/tsl/framework/convolution:spatial_convolutions_test
```

### Relevant log output

```shell
ERROR: /home/andrew/src/tensorflow/tensorflow/tsl/framework/convolution/BUILD:99:12: Compiling tensorflow/tsl/framework/convolution/eigen_spatial_convolutions_test.cc failed: (Exit 1): gcc failed: error executing command 
  (cd /home/andrew/.cache/bazel/_bazel_andrew/c61c5f84d239689cb19a72cfde16be9f/execroot/org_tensorflow && \
  exec env - \
    LD_LIBRARY_PATH=/opt/rh/gcc-toolset-10/root/usr/lib64:/opt/rh/gcc-toolset-10/root/usr/lib:/opt/rh/gcc-toolset-10/root/usr/lib64/dyninst:/opt/rh/gcc-toolset-10/root/usr/lib/dyninst:/opt/rh/gcc-toolset-10/root/usr/lib64:/opt/rh/gcc-toolset-10/root/usr/lib \
    PATH=/home/andrew/.cache/bazelisk/downloads/bazelbuild/bazel-5.3.0-linux-arm64/bin:/home/andrew/.local/bin:/home/andrew/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/home/andrew/src/venv38/bin/python3 \
    PYTHON_LIB_PATH=/home/andrew/src/venv38/lib/python3.8/site-packages \
    TF2_BEHAVIOR=1 \
  /opt/rh/gcc-toolset-10/root/usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/aarch64-opt/bin/tensorflow/tsl/framework/convolution/_objs/spatial_convolutions_test/eigen_spatial_convolutions_test.d '-frandom-seed=bazel-out/aarch64-opt/bin/tensorflow/tsl/framework/convolution/_objs/spatial_convolutions_test/eigen_spatial_convolutions_test.o' -DEIGEN_MPL2_ONLY '-DEIGEN_MAX_ALIGN_BYTES=64' -DTENSORFLOW_USE_CUSTOM_CONTRACTION_KERNEL -DGEMM_KERNEL_H '-DEIGEN_ALTIVEC_USE_CUSTOM_PACK=0' '-DEIGEN_NEON_GEBP_NR=4' -iquote . -iquote bazel-out/aarch64-opt/bin -iquote external/com_google_absl -iquote bazel-out/aarch64-opt/bin/external/com_google_absl -iquote external/eigen_archive -iquote bazel-out/aarch64-opt/bin/external/eigen_archive -iquote external/nsync -iquote bazel-out/aarch64-opt/bin/external/nsync -iquote external/double_conversion -iquote bazel-out/aarch64-opt/bin/external/double_conversion -iquote external/com_google_googletest -iquote bazel-out/aarch64-opt/bin/external/com_google_googletest -iquote external/com_google_benchmark -iquote bazel-out/aarch64-opt/bin/external/com_google_benchmark -iquote external/com_google_protobuf -iquote bazel-out/aarch64-opt/bin/external/com_google_protobuf -iquote external/zlib -iquote bazel-out/aarch64-opt/bin/external/zlib -iquote external/bazel_tools -iquote bazel-out/aarch64-opt/bin/external/bazel_tools -Ibazel-out/aarch64-opt/bin/external/com_google_benchmark/_virtual_includes/benchmark -isystem third_party/eigen3/mkl_include -isystem bazel-out/aarch64-opt/bin/third_party/eigen3/mkl_include -isystem external/eigen_archive -isystem bazel-out/aarch64-opt/bin/external/eigen_archive -isystem external/nsync/public -isystem bazel-out/aarch64-opt/bin/external/nsync/public -isystem external/com_google_googletest/googlemock -isystem bazel-out/aarch64-opt/bin/external/com_google_googletest/googlemock -isystem external/com_google_googletest/googlemock/include -isystem bazel-out/aarch64-opt/bin/external/com_google_googletest/googlemock/include -isystem external/com_google_googletest/googletest -isystem bazel-out/aarch64-opt/bin/external/com_google_googletest/googletest -isystem external/com_google_googletest/googletest/include -isystem bazel-out/aarch64-opt/bin/external/com_google_googletest/googletest/include -isystem external/com_google_protobuf/src -isystem bazel-out/aarch64-opt/bin/external/com_google_protobuf/src -isystem external/zlib -isystem bazel-out/aarch64-opt/bin/external/zlib -Wno-all -Wno-extra -Wno-deprecated -Wno-deprecated-declarations -Wno-ignored-attributes -Wno-array-bounds -Wunused-result '-Werror=unused-result' -Wswitch '-Werror=switch' '-Wno-error=unused-but-set-variable' -DAUTOLOAD_DYNAMIC_KERNELS '-mtune=generic' '-march=armv8-a' -O3 '-std=c++17' -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c tensorflow/tsl/framework/convolution/eigen_spatial_convolutions_test.cc -o bazel-out/aarch64-opt/bin/tensorflow/tsl/framework/convolution/_objs/spatial_convolutions_test/eigen_spatial_convolutions_test.o)
# Configuration: 67e3477bbfd3aa6df692c90e4aaaf7a6ee0f55b121a5556fe852592ce2c633e2
# Execution platform: @local_execution_config_platform//:platform
In file included from external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/Core:162,
                 from external/eigen_archive/unsupported/Eigen/CXX11/Tensor:14,
                 from ./third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1,
                 from ./tensorflow/tsl/framework/convolution/eigen_spatial_convolutions.h:19,
                 from tensorflow/tsl/framework/convolution/eigen_spatial_convolutions_test.cc:16:
./tensorflow/tsl/framework/convolution/eigen_spatial_convolutions-inl.h: In instantiation of 'struct Eigen::internal::gemm_pack_rhs<Eigen::QInt8, long int, Eigen::internal::TensorContractionSubMapper<Eigen::QInt8, long int, 0, Eigen::TensorEvaluator<const Eigen::TensorReshapingOp<Eigen::DSizes<long int, 2>, const Eigen::TensorImagePatchOp<-1, -1, Eigen::TensorMap<Eigen::Tensor<Eigen::QInt8, 4, 0, long int>, 16, Eigen::MakePointer> > >, Eigen::DefaultDevice>, std::array<long int, 1>, std::array<long int, 1>, 1, true, false, 0, Eigen::MakePointer>, 1, 0, false, false>':
tensorflow/tsl/framework/convolution/eigen_spatial_convolutions_test.cc:924:15:   required from 'void Eigen::PackRhsHelper(benchmark::State&, int, int, int, int, int, int, int, Eigen::PaddingType, int, int, int, int, Eigen::Index, Eigen::Index) [with T = Eigen::QInt8; Eigen::Index = long int]'
tensorflow/tsl/framework/convolution/eigen_spatial_convolutions_test.cc:1375:1:   required from here
./tensorflow/tsl/framework/convolution/eigen_spatial_convolutions-inl.h:1490:27: error: static assertion failed: YOU_MADE_A_PROGRAMMING_MISTAKE
 1490 |   EIGEN_STATIC_ASSERT((nr == 4), YOU_MADE_A_PROGRAMMING_MISTAKE)
      |                       ~~~~^~~~~
Target //tensorflow/tsl/framework/convolution:spatial_convolutions_test failed to build
INFO: Elapsed time: 9.629s, Critical Path: 9.11s
INFO: 3 processes: 2 internal, 1 local.
FAILED: Build did NOT complete successfully
//tensorflow/tsl/framework/convolution:spatial_convolutions_test FAILED TO BUILD

FAILED: Build did NOT complete successfully
```
</details>

**Comment by elfringham** [comment]
@angerson

**Comment by elfringham** [comment]
Introduced by https://github.com/tensorflow/tensorflow/commit/397570c85afa4dacd0a10869a1463bac8872bfd7

**Comment by gaikwadrahul8** [comment]
Hi, @elfringham 

Thank you for noticing the issue and I see you've submitted PR [#59681](https://github.com/tensorflow/tensorflow/pull/59681) for this issue so this issue will be taken care once PR got merged after following the PR process. I really appreciate your efforts and time. Thank you!
