### ISSUE TITLE
Failing to build libtensorflow_cc.so for v2.10.0

### ISSUE THREAD

**Issue by lreiher** [tensorflow/tensorflow#57826]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2.10.0

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.8.10

### Bazel version

5.3.1

### GCC/Compiler version

9.4.0

### CUDA/cuDNN version

11.2.152

### GPU model and memory

NVIDIA RTX 3090 TI (24GB)

### Current Behaviour?

I am trying to build the TensorFlow C++ library `libtensorflow_cc.so` from source. The same build commands that succeeded for versions below 2.10.0 now fail with the latest 2.10.0 tag of the TensorFlow repository.

I'm building inside a Docker container of the official `devel-gpu` image, which is [defined in devel-gpu.Dockerfile](https://github.com/tensorflow/tensorflow/blob/v2.10.0/tensorflow/tools/dockerfiles/dockerfiles/devel-gpu.Dockerfile).

For the build, I am calling the following. The build output is attached as the log in this issue.

```shell
bazel build --jobs ${JOBS} --config=cuda --config=opt --config=monolithic --verbose_failures tensorflow:libtensorflow_cc.so tensorflow:install_headers
```

The error message reads:

```
ERROR: /tensorflow/tensorflow/BUILD:1156:21: in cc_shared_library rule //tensorflow:libtensorflow_cc.so.2.10.0: 
Traceback (most recent call last):
        File "/virtual_builtins_bzl/common/cc/experimental_cc_shared_library.bzl", line 416, column 105, in _cc_shared_library_impl
        File "/virtual_builtins_bzl/common/cc/experimental_cc_shared_library.bzl", line 340, column 37, in _filter_inputs
        File "/virtual_builtins_bzl/common/cc/experimental_cc_shared_library.bzl", line 360, column 9, in _throw_error_if_unaccounted_libs
Error in fail: The following libraries cannot be linked either statically or dynamically:
@nccl_archive//:nccl
@nccl_archive//:device
@nccl_archive//:net
@nccl_archive//:include_hdrs
@nccl_archive//:src_hdrs
To ignore which libraries get linked statically for now, add the following to 'static_deps':
        "@nccl_archive//:__subpackages__",
ERROR: /tensorflow/tensorflow/BUILD:1156:21: Analysis of target '//tensorflow:libtensorflow_cc.so.2.10.0' failed
ERROR: Analysis of target '//tensorflow:libtensorflow_cc.so' failed; build aborted: 
INFO: Elapsed time: 41.228s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (277 packages loaded, 28806 targets configured)
FAILED: Build did NOT complete successfully (277 packages loaded, 28806 targets configured)
```

### Standalone code to reproduce the issue

First build the official GPU devel image with [devel-gpu.Dockerfile](https://github.com/tensorflow/tensorflow/blob/v2.10.0/tensorflow/tools/dockerfiles/dockerfiles/devel-gpu.Dockerfile).

```shell
docker build -t tensorflow/tensorflow:2.10.0-devel-gpu -f devel-gpu.Dockerfile .
```

Then try to build the `libtensorflow_cc.so` with the following Dockerfile.

```docker
ARG TF_VERSION=2.10.0
FROM tensorflow/tensorflow:${TF_VERSION}-devel-gpu AS build

ARG TF_VERSION
ARG JOBS="auto"

# clone TensorFlow
RUN git clone --branch v${TF_VERSION} --depth=1 https://github.com/tensorflow/tensorflow.git /tensorflow
WORKDIR /tensorflow

# configure compilation
ENV PYTHON_BIN_PATH=/usr/bin/python3
ENV PYTHON_LIB_PATH=/usr/lib/python3/dist-packages
ENV TF_NEED_ROCM=0
ENV TF_CUDA_COMPUTE_CAPABILITIES=5.3,6.0,6.1,7.0,7.2,7.5,8.0,8.6
ENV TF_CUDA_CLANG=0
ENV GCC_HOST_COMPILER_PATH=/usr/bin/gcc
ENV CC_OPT_FLAGS="-march=native -Wno-sign-compare"
ENV TF_SET_ANDROID_WORKSPACE=0
RUN ./configure

# build C++ library
RUN bazel build --jobs ${JOBS} --config=cuda --config=opt --config=monolithic --verbose_failures tensorflow:libtensorflow_cc.so tensorflow:install_headers
```

```shell
docker build -t tensorflow/tensorflow:2.10.0-libtensorflow-cc .
```

### Relevant log output

```shell
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'build' from /tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /tensorflow/.bazelrc:
  'build' options: --define framework_shared_object=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library --experimental_link_static_libraries_once=false
INFO: Reading rc options for 'build' from /tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env PYTHON_LIB_PATH=/usr/lib/python3/dist-packages --python_path=/usr/bin/python3 --config=tensorrt --action_env TF_CUDA_VERSION=11.2 --action_env TF_CUDNN_VERSION=8 --action_env CUDA_TOOLKIT_PATH=/usr/local/cuda-11.2 --action_env TF_CUDA_COMPUTE_CAPABILITIES=5.3,6.0,6.1,7.0,7.2,7.5,8.0,8.6 --action_env LD_LIBRARY_PATH=/usr/local/cuda-11.0/targets/x86_64-linux/lib:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:/usr/include/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64/stubs:/usr/local/cuda-11.0/lib64:/usr/local/cuda-11.2/lib64 --action_env GCC_HOST_COMPILER_PATH=/usr/bin/x86_64-linux-gnu-gcc-9 --config=cuda
INFO: Reading rc options for 'build' from /tensorflow/.bazelrc:
  'build' options: --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/ir,tensorflow/compiler/mlir/tfrt/tests/analysis,tensorflow/compiler/mlir/tfrt/tests/jit,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_tfrt,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_jitrt,tensorflow/compiler/mlir/tfrt/tests/tf_to_corert,tensorflow/compiler/mlir/tfrt/tests/tf_to_tfrt_data,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/common,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/graph_executor,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils
INFO: Found applicable config definition build:short_logs in file /tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:tensorrt in file /tensorflow/.bazelrc: --repo_env TF_NEED_TENSORRT=1
INFO: Found applicable config definition build:cuda in file /tensorflow/.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
INFO: Found applicable config definition build:cuda in file /tensorflow/.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
INFO: Found applicable config definition build:opt in file /tensorflow/.tf_configure.bazelrc: --copt=-march=native --host_copt=-march=native --copt=-Wno-sign-compare --host_copt=-Wno-sign-compare
INFO: Found applicable config definition build:monolithic in file /tensorflow/.bazelrc: --define framework_shared_object=false --experimental_link_static_libraries_once=false
INFO: Found applicable config definition build:linux in file /tensorflow/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++17 --host_cxxopt=-std=c++17 --config=dynamic_kernels --distinct_host_configuration=false --experimental_guard_against_concurrent_changes
INFO: Found applicable config definition build:dynamic_kernels in file /tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/6ca793b5d862ef6c50f242d77a811f06cce9b60a.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/0538e5431afdb1fa05bdcedf70ee502ccfcd112a.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
DEBUG: /root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:118:10: 
Auto-Configuration Warning: 'TMP' environment variable is not set, using 'C:\Windows\Temp' as default
Loading: 
Loading: 1 packages loaded
Analyzing: 2 targets (2 packages loaded, 0 targets configured)
Analyzing: 2 targets (46 packages loaded, 34 targets configured)
WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/rules_cc/archive/081771d4a0e9d7d3aa0eed2ef389fa4700dfb23e.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/nvidia/nccl/archive/v2.12.12-1.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
Analyzing: 2 targets (275 packages loaded, 26073 targets configured)
ERROR: /tensorflow/tensorflow/BUILD:1156:21: in cc_shared_library rule //tensorflow:libtensorflow_cc.so.2.10.0: 
Traceback (most recent call last):
        File "/virtual_builtins_bzl/common/cc/experimental_cc_shared_library.bzl", line 416, column 105, in _cc_shared_library_impl
        File "/virtual_builtins_bzl/common/cc/experimental_cc_shared_library.bzl", line 340, column 37, in _filter_inputs
        File "/virtual_builtins_bzl/common/cc/experimental_cc_shared_library.bzl", line 360, column 9, in _throw_error_if_unaccounted_libs
Error in fail: The following libraries cannot be linked either statically or dynamically:
@nccl_archive//:nccl
@nccl_archive//:device
@nccl_archive//:net
@nccl_archive//:include_hdrs
@nccl_archive//:src_hdrs
To ignore which libraries get linked statically for now, add the following to 'static_deps':
        "@nccl_archive//:__subpackages__",
ERROR: /tensorflow/tensorflow/BUILD:1156:21: Analysis of target '//tensorflow:libtensorflow_cc.so.2.10.0' failed
ERROR: Analysis of target '//tensorflow:libtensorflow_cc.so' failed; build aborted: 
INFO: Elapsed time: 41.228s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (277 packages loaded, 28806 targets configured)
FAILED: Build did NOT complete successfully (277 packages loaded, 28806 targets configured)
```
</details>

**Comment by lreiher** [comment]
Working again with v2.11.0-rc1.

**Comment by donglinz** [comment]
Same issue.

**Comment by njzjz** [comment]
Same error, so I roll back to 2.9.2.

**Comment by mohantym** [comment]
@lreiher @njzjz !
I could replicate this issue in [master ](https://colab.sandbox.google.com/gist/mohantym/0428967b7a85d88775b4707fdfc6a8c6/tensorflow-ranking.ipynb)branch too .
Thank you!

**Comment by aburgm** [comment]
I ran into this issue as well and with `git bisect` learned that the issue was introduced in 71b5cdf6718bc3c4a96f4be9760b2918252df64f. Reverting this particular commit allowed me to build the library (but I don't have enough context to understand what the consequences of it are). [Here](https://gist.github.com/aburgm/4287393ff6822f3fa7135de9f494a48d) is a patch doing that against TF 2.10.0.

**Comment by njzjz** [comment]
da2606aaf152055dd1996f374dd541aa9bc4a479

**Comment by lreiher** [comment]
Hi @njzjz, thank you for the fix, this indeed helped me to build the library again.

I did however notice that `libtensorflow_cc.so` seems to now be linking to `libtensorflow_framework.so`, which is also built in the process. That was not the case with v2.9.2 and below. Actually I thought that `--config=monolithic` should result in only `libtensorflow_cc.so`, but it looks like `libtensorflow_framework.so` is a dependency since https://github.com/tensorflow/tensorflow/commit/843c02fe06983ac0f4382a93fff9ffd07eb93d27? I didn't find where `--config=monolithic` is coming into play at the moment.

My main problem at the moment is that I cannot successfully compile and run a test C++ program. Previously this worked:

```
g++ -I /usr/local/include/tensorflow \
    hello_tensorflow.cpp \
    -ltensorflow_cc -lprotobuf \
    -o hello_tensorflow
```

With v2.10.0+ it is giving me the following error instead.

```
/usr/bin/ld: /tmp/ccVj5SwH.o: undefined reference to symbol '_ZN10tensorflow6TensorC1ENS_8DataTypeERKNS_11TensorShapeE'
/usr/bin/ld: /usr/local/lib//libtensorflow_framework.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

Now if I add `libtensorflow_framework.so` to the list of libs to link against, compilation works.

```
g++ -I /usr/local/include/tensorflow \
    hello_tensorflow.cpp \
    -ltensorflow_cc -ltensorflow_framework -lprotobuf \
    -o hello_tensorflow
```

This time however, I am getting the following runtime error:

```
[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/descriptor_database.cc:118] File already exists in database: google/protobuf/any.proto
[libprotobuf FATAL external/com_google_protobuf/src/google/protobuf/descriptor.cc:1379] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
Aborted (core dumped)
```

Any clues?

**Comment by mohantym** [comment]
Hi @lreiher !

We are  checking to see if you are still looking for assistance in this issue.
Build seems to be passing with[ nightly branch (2.12dev).](https://colab.sandbox.google.com/gist/mohantym/abdd6d8077b1f887cb92a43509e855f9/tensorflow-ranking.ipynb#scrollTo=OhQLwy_n-Re3) Could you let us know from your side.

Thank you!

**Comment by lreiher** [comment]
Hi @mohantym!

First of all, building `2.10.0`, `2.10.1`, `2.11.0` is working when cherry-picking `tensorflow/BUILD` from b1bd1d6beeac169ce669f81dcbf3c48899ca1ed0. There's still another issue for which I have created #59081.

I can also confirm that the build is succeeding with `nightly`. When compiling my example application with the `nightly` build, I'm getting application build time errors though.

```
/usr/local/include/tensorflow/tensorflow/tsl/platform/float8.h: In instantiation of ‘static To tsl::float8_internal::float8_base<Derived>::ConvertTo(const Derived&) [with To = Eigen::bfloat16; bool kSaturate = false; bool kTruncate = false; Derived = tsl::float8_internal::float8_e5m2]’:
/usr/local/include/tensorflow/tensorflow/tsl/platform/float8.h:245:44:   required from here
/usr/local/include/tensorflow/tensorflow/tsl/platform/float8.h:802:61: error: incomplete type ‘tsl::float8_internal::ConvertImpl<tsl::float8_internal::float8_e5m2, Eigen::bfloat16, false, false, void>’ used in nested name specifier
```

**Comment by mohantym** [comment]
@lreiher !
Can we consider this as resolved for build process and track the runtime  issues there in #59081 .
Thank you!
