### ISSUE TITLE
AttributeError: 'module' object has no attribute 'gfile'

### ISSUE THREAD

**Issue by akhld** [tensorflow/tensorflow#1121]
I'm on an Ubuntu machine, installed tensorflow and ran the image processing example as in the website but it failed complaining about gFile not found,

Here's the exception stack:

		Traceback (most recent call last):
		  File "classify_image.py", line 213, in <module>
		    tf.app.run()
		  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/default/_app.py", line 30, in run
		    sys.exit(main(sys.argv))
		  File "classify_image.py", line 209, in main
		    run_inference_on_image(image)
		  File "classify_image.py", line 154, in run_inference_on_image
		    if not tf.gfile.Exists(image):
		AttributeError: 'module' object has no attribute 'gfile'

**Comment by manucarbonell** [comment]
Same here, got this error when running cifar10_eval.py

**Comment by vrv** [comment]
My guess is that you are running source code from HEAD with a pip install from 0.6.0.  Either check out the code at the same branch / tag as the pip install, or compile from sources at HEAD to use code at head.

**Comment by akhld** [comment]
Let me check that, thanks for looking into it.

**Comment by Kecksdose** [comment]
I had the same problem executing the file classify_image.py. Changing the branch to 0.6.0 solved this problem. Thanks!

**Comment by zszhong** [comment]
@akhld @Kecksdose 

Yes, using r0.7.0, and run
$ cd tensorflow/models/image/mnist
$ python convolutional.py
will have this problem.

When changing to 0.6.0, no this problem.

**Comment by murraymack** [comment]
So the temporary fix for this is to use 0.6.0 for TensorFlow?

**Comment by vrv** [comment]
Try upgrading to 0.7.1
pip uninstall tensorflow
pip uninstall protobuf
pip install path/to/0.7.1.wheel

**Comment by BentoCG** [comment]
It works fine on 0.8

**Comment by BiondiVini** [comment]
Was with this error to run ptb_word_lm.py in the old version.
Really, after upgrading worked properly 
thanks! @vrv
