### ISSUE TITLE
Tensorflow 2.11.0 is incompatible with python 3.10.8

### ISSUE THREAD

**Issue by aleck099** [tensorflow/tensorflow#58773]
`pip install -U --user tensorflow`
does not work on python 3.10.8

Tensorflow 2.11.0 depends on numpy==1.19.3
But that version of numpy is incompatible with python 3.10.8

There is a call `_Py_HashDouble((double) PyArrayScalar_VAL(obj, @name@))` in numpy 1.19.3, but that function is changed to `_Py_HashDouble(PyObject *, double)` at https://github.com/python/cpython/commit/a07da09ad5bd7d234ccd084a3a0933c290d1b592

<details>
<summary> Compiler Output</summary>

#### In numpy/core/src/multiarray/scalartypes.c.src:

```
numpy/core/src/multiarray/scalartypes.c.src: In function ‘float_arrtype_hash’:
numpy/core/src/multiarray/scalartypes.c.src:2967:27: error: incompatible type for argument 1 of ‘_Py_HashDouble’
 2967 |     return _Py_HashDouble((double) PyArrayScalar_VAL(obj, @name@));
In file included from /usr/include/python3.10/Python.h:77,
                 from numpy/core/src/multiarray/scalartypes.c.src:3:
/usr/include/python3.10/pyhash.h:10:38: note: expected ‘PyObject *’ {aka ‘struct _object *’} but argument is of type ‘double’
   10 | PyAPI_FUNC(Py_hash_t) _Py_HashDouble(PyObject *, double);
      |                                      ^~~~~~~~~~
numpy/core/src/multiarray/scalartypes.c.src:2967:12: error: too few arguments to function ‘_Py_HashDoubl ’
 2967 |     return _Py_HashDouble((double) PyArrayScalar_VAL(obj, @name@));
      |            ^~~~~~~~~~~~~~
/usr/include/python3.10/pyhash.h:10:23: note: declared here
   10 | PyAPI_FUNC(Py_hash_t) _Py_HashDouble(PyObject *, double);
      |                       ^~~~~~~~~~~~~~
numpy/core/src/multiarray/scalartypes.c.src: In function ‘cfloat_arrtype_hash’:
numpy/core/src/multiarray/scalartypes.c.src:2975:31: error: incompatible type for argument 1 of ‘_Py_HashDouble’
 2975 |     hashreal = _Py_HashDouble((double)
      |                               ^~~~~~~~
      |                               |
      |                               double
 2976 |             PyArrayScalar_VAL(obj, C@name@).real);
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/python3.10/pyhash.h:10:38: note: expected ‘PyObject *’ {aka ‘struct _object *’} but argument is of type ‘double’
   10 | PyAPI_FUNC(Py_hash_t) _Py_HashDouble(PyObject *, double);
      |                                      ^~~~~~~~~~
numpy/core/src/multiarray/scalartypes.c.src:2975:16: error: too few arguments to function ‘_Py_HashDoubl ’
 2975 |     hashreal = _Py_HashDouble((double)
      |                ^~~~~~~~~~~~~~
/usr/include/python3.10/pyhash.h:10:23: note: declared here
   10 | PyAPI_FUNC(Py_hash_t) _Py_HashDouble(PyObject *, double);
      |                       ^~~~~~~~~~~~~~
numpy/core/src/multiarray/scalartypes.c.src:2981:31: error: incompatible type for argument 1 of ‘_Py_HashDouble’
 2981 |     hashimag = _Py_HashDouble((double)
      |                               ^~~~~~~~
      |                               |
      |                               double
 2982 |             PyArrayScalar_VAL(obj, C@name@).imag);
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/python3.10/pyhash.h:10:38: note: expected ‘PyObject *’ {aka ‘struct _object *’} but argument is of type ‘double’
   10 | PyAPI_FUNC(Py_hash_t) _Py_HashDouble(PyObject *, double);
      |                                      ^~~~~~~~~~
numpy/core/src/multiarray/scalartypes.c.src:2981:16: error: too few arguments to function ‘_Py_HashDoubl ’
 2981 |     hashimag = _Py_HashDouble((double)
      |                ^~~~~~~~~~~~~~
/usr/include/python3.10/pyhash.h:10:23: note: declared here
   10 | PyAPI_FUNC(Py_hash_t) _Py_HashDouble(PyObject *, double);
      |                       ^~~~~~~~~~~~~~
numpy/core/src/multiarray/scalartypes.c.src: In function ‘longdouble_arrtype_hash’:
numpy/core/src/multiarray/scalartypes.c.src:2967:27: error: incompatible type for argument 1 of ‘_Py_HashDouble’
 2967 |     return _Py_HashDouble((double) PyArrayScalar_VAL(obj, @name@));
/usr/include/python3.10/pyhash.h:10:38: note: expected ‘PyObject *’ {aka ‘struct _object *’} but argument is of type ‘double’
   10 | PyAPI_FUNC(Py_hash_t) _Py_HashDouble(PyObject *, double);
      |                                      ^~~~~~~~~~
numpy/core/src/multiarray/scalartypes.c.src:2967:12: error: too few arguments to function ‘_Py_HashDoubl ’
 2967 |     return _Py_HashDouble((double) PyArrayScalar_VAL(obj, @name@));
      |            ^~~~~~~~~~~~~~
/usr/include/python3.10/pyhash.h:10:23: note: declared here
   10 | PyAPI_FUNC(Py_hash_t) _Py_HashDouble(PyObject *, double);
      |                       ^~~~~~~~~~~~~~
numpy/core/src/multiarray/scalartypes.c.src: In function ‘clongdouble_arrtype_hash’:
numpy/core/src/multiarray/scalartypes.c.src:2975:31: error: incompatible type for argument 1 of ‘_Py_HashDouble’
 2975 |     hashreal = _Py_HashDouble((double)
      |                               ^~~~~~~~
      |                               |
      |                               double
 2976 |             PyArrayScalar_VAL(obj, C@name@).real);
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
/usr/include/python3.10/pyhash.h:10:38: note: expected ‘PyObject *’ {aka ‘struct _object *’} but argument is of type ‘double’
   10 | PyAPI_FUNC(Py_hash_t) _Py_HashDouble(PyObject *, double);
      |                                      ^~~~~~~~~~
numpy/core/src/multiarray/scalartypes.c.src:2975:16: error: too few arguments to function ‘_Py_HashDoubl ’
 2975 |     hashreal = _Py_HashDouble((double)
      |                ^~~~~~~~~~~~~~
/usr/include/python3.10/pyhash.h:10:23: note: declared here
   10 | PyAPI_FUNC(Py_hash_t) _Py_HashDouble(PyObject *, double);
      |                       ^~~~~~~~~~~~~~
numpy/core/src/multiarray/scalartypes.c.src:2981:31: error: incompatible type for argument 1 of ‘_Py_HashDouble’
 2981 |     hashimag = _Py_HashDouble((double)
      |                               ^~~~~~~~
      |                               |
      |                               double
 2982 |             PyArrayScalar_VAL(obj, C@name@).imag);
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
/usr/include/python3.10/pyhash.h:10:38: note: expected ‘PyObject *’ {aka ‘struct _object *’} but argument is of type ‘double’
   10 | PyAPI_FUNC(Py_hash_t) _Py_HashDouble(PyObject *, double);
      |                                      ^~~~~~~~~~
numpy/core/src/multiarray/scalartypes.c.src:2981:16: error: too few arguments to function ‘_Py_HashDoubl ’
 2981 |     hashimag = _Py_HashDouble((double)
      |                ^~~~~~~~~~~~~~
/usr/include/python3.10/pyhash.h:10:23: note: declared here
   10 | PyAPI_FUNC(Py_hash_t) _Py_HashDouble(PyObject *, double);
      |                       ^~~~~~~~~~~~~~
numpy/core/src/multiarray/scalartypes.c.src: In function ‘half_arrtype_hash’:
numpy/core/src/multiarray/scalartypes.c.src:2997:27: error: incompatible type for argument 1 of ‘_Py_HashDouble’
 2997 |     return _Py_HashDouble(npy_half_to_double(PyArrayScalar_VAL(obj, Half)));
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                           |
      |                           double
/usr/include/python3.10/pyhash.h:10:38: note: expected ‘PyObject *’ {aka ‘struct _object *’} but argument is of type ‘double’
   10 | PyAPI_FUNC(Py_hash_t) _Py_HashDouble(PyObject *, double);
      |                                      ^~~~~~~~~~
numpy/core/src/multiarray/scalartypes.c.src:2997:12: error: too few arguments to function ‘_Py_HashDoubl ’
 2997 |     return _Py_HashDouble(npy_half_to_double(PyArrayScalar_VAL(obj, Half)));
      |            ^~~~~~~~~~~~~~
/usr/include/python3.10/pyhash.h:10:23: note: declared here
   10 | PyAPI_FUNC(Py_hash_t) _Py_HashDouble(PyObject *, double);
      |                       ^~~~~~~~~~~~~~
numpy/core/src/multiarray/scalartypes.c.src: In function ‘longdouble_arrtype_hash’:
numpy/core/src/multiarray/scalartypes.c.src:2968:1: warning: control reaches end of non-void function [-Wreturn-type]
 2968 | }
      | ^
numpy/core/src/multiarray/scalartypes.c.src: In function ‘float_arrtype_hash’:
numpy/core/src/multiarray/scalartypes.c.src:2968:1: warning: control reaches end of non-void function [-Wreturn-type]
 2968 | }
      | ^
numpy/core/src/multiarray/scalartypes.c.src: In function ‘half_arrtype_hash’:
numpy/core/src/multiarray/scalartypes.c.src:2998:1: warning: control reaches end of non-void function [-Wreturn-type]
 2998 | }
      | ^

```
</details>

It is fixed in https://github.com/numpy/numpy/commit/ad2a73c18dcff95d844c382c94ab7f73b5571cf3, which is of numpy version 1.22.0
I guess updating numpy dependency may fix this

**Comment by mihaimaruseac** [comment]
CC @learning-to-play @rishikasinha-tf 

Upgrading numpy will fix this issue too, besides several others.

**Comment by aleck099** [comment]
tf-nightly works well

**Comment by mohantym** [comment]
Hi @aleck099 !
Thanks for sharing your observations. But Numpy version has been upgraded to >=1.20 since 2.8. [Ref](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/pip_package/setup.py).

Could we consider fixed in nightly version then?

**Comment by mihaimaruseac** [comment]
Since nightly works, there's nothing left to do here. TF 2.12 will work too.
