### ISSUE TITLE
tf.keras.estimator.model_to_estimator giving error in TensorFlow >= 1.8.0

### ISSUE THREAD

**Issue by Youki** [tensorflow/tensorflow#20552]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Custom code
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Colab
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: 1.8.0 and 1.9.0-rc2
- **Python version**: Python3
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**:
`estimator = tf.keras.estimator.model_to_estimator(model, model_dir=MODEL_DIR)`

### Describe the problem
When calling tf.keras.estimator.model_to_estimator, I got following error. However, it works fine with TensorFlow == 1.7.0.

```
INFO:tensorflow:Using the Keras model provided.
INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': './model', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f61f0ede908>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-176d5ff06eb1> in <module>()
     13 
     14 model = get_keras_model()
---> 15 estimator = tf.keras.estimator.model_to_estimator(model, model_dir='./model')

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/_impl/keras/estimator.py in model_to_estimator(keras_model, keras_model_path, custom_objects, model_dir, config)
    502                            estimator,
    503                            custom_objects,
--> 504                            keras_weights)
    505   elif keras_model.built:
    506     logging.warning('You are creating an Estimator from a Keras model '

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/_impl/keras/estimator.py in _save_first_checkpoint(keras_model, estimator, custom_objects, keras_weights)
    413           model.set_weights(keras_weights)
    414         # Make update ops and initialize all variables.
--> 415         if not model.train_function:
    416           # pylint: disable=protected-access
    417           model._make_train_function()

AttributeError: 'Sequential' object has no attribute 'train_function'
```

### Source code / logs
Here is the code to reproduce the problem.

```
import tensorflow as tf

def get_keras_model():
  model = tf.keras.Sequential()
  model.add(tf.keras.layers.InputLayer(input_shape=[28*28]))
  model.add(tf.keras.layers.Dense(300, activation='relu'))
  model.add(tf.keras.layers.Dense(100, activation='relu'))
  model.add(tf.keras.layers.Dense(10, activation='softmax'))
  model.compile(loss='categorical_crossentropy',
                optimizer=tf.keras.optimizers.SGD(lr=0.005),
                metrics=['accuracy'])
  return model

model = get_keras_model()
estimator = tf.keras.estimator.model_to_estimator(model, model_dir='./model')
```

**Comment by facaiy** [comment]
The bug can be reproduced. It seems that `input_tensor` gets lost when cloning model here:

https://github.com/tensorflow/tensorflow/blob/b2fe2a874bade4782aaca5c44bf29e7ff6c39200/tensorflow/python/estimator/keras.py#L310

**Comment by facaiy** [comment]
@bhack Thanks for cc me. The analysis of @tanzhenyu is really useful. I'll look into the issue at weekend.

**Comment by facaiy** [comment]
@Youki Hi, could you test tf.keras.Model and see if the same error is raised ? Thanks.

**Comment by Youki** [comment]
@facaiy Found that the problem can't be reproducible now. Both with/without tf.keras.Model are now working with TF >= 1.8.0. Is there any update that fix this problem???

**In TensorFlow >= 1.8.0 (tested with 1.8.0 and 1.9.0-rc2) without tf.keras.Model**

```
def get_keras_model():
  model = tf.keras.Sequential()
  model.add(tf.keras.layers.InputLayer(input_shape=[28*28]))
  model.add(tf.keras.layers.Dense(300, activation='relu'))
  model.add(tf.keras.layers.Dense(100, activation='relu'))
  model.add(tf.keras.layers.Dense(10, activation='softmax'))
  model.compile(loss='categorical_crossentropy',
                optimizer=tf.keras.optimizers.SGD(lr=0.005),
                metrics=['accuracy'])
  return model

model = get_keras_model()
estimator = tf.keras.estimator.model_to_estimator(model, model_dir='./model')
```

```
INFO:tensorflow:Using the Keras model provided.
INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': './model', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fed725a5828>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
```

**In TensorFlow >= 1.8.0 (tested with 1.8.0 and 1.9.0-rc2) with tf.keras.Model**

```
def get_keras_model():
  _model = tf.keras.Sequential()
  _model.add(tf.keras.layers.InputLayer(input_shape=[28*28]))
  _model.add(tf.keras.layers.Dense(300, activation='relu'))
  _model.add(tf.keras.layers.Dense(100, activation='relu'))
  _model.add(tf.keras.layers.Dense(10, activation='softmax'))
  model = tf.keras.Model(inputs=_model.input, outputs=_model.output)
  model.compile(loss='categorical_crossentropy',
                optimizer=tf.keras.optimizers.SGD(lr=0.005),
                metrics=['accuracy'])
  return model

model = get_keras_model()
estimator = tf.keras.estimator.model_to_estimator(model, model_dir='./model')
```

```
INFO:tensorflow:Using the Keras model provided.
INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': './model', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fed6d9ceb38>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
```

**Comment by FarhanTejani** [comment]
I am having this same issue and I can still reproduce the problem.

**Comment by facaiy** [comment]
@Youki Thank you for feedback. I run both examples you provided with tf1.9-rc2, and find that Sequence still raises the exception, while Model is OK.

**Comment by Youki** [comment]
@facaiy You're right. The information I provided above was incorrect. I still have the same issue without tf.keras.Model. So sorry to confuse you.

**Comment by facaiy** [comment]
@Youki Hi, according to [official document](https://keras.io/getting-started/sequential-model-guide/), it seems better to pass an input_shape argument to the first layer. I modify the first layer of your code and it runs well. Is the workaround useful for you?

```python
def get_keras_model():
  model = tf.keras.Sequential()
  model.add(tf.keras.layers.Dense(300, activation='relu', input_shape=[28*28]))
  model.add(tf.keras.layers.Dense(100, activation='relu'))
```

And I also check the unit test case, and find that they don't test Sequential model with `InputLayer`. 
cc @fchollet what do you think?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @asimshankar: It has been 22 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @fchollet, @pavithrasv: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @fchollet, @pavithrasv: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by Youki** [comment]
@facaiy 
Sorry for the very late reply. The workaround you suggested is very useful.

**Comment by Pari-singh** [comment]
I am also getting an error model_to_estimator() got an unexpected keyword argument 'checkpoint_format' with the newly changed model_to_estimator function in keras. 
TF version - 2.0.0b1
Keras - 2.2
I tried reproducing the example given in https://github.com/kashif/tf-keras-tutorial/blob/master/7-estimators-multi-gpus.ipynb and the line
estimator = tf.keras.estimator.model_to_estimator(keras_model=model, config=config) throws the above error

**Comment by pavithrasv** [comment]
Adding Kathy who is working on the model to estimator API.
