### ISSUE TITLE
Custom C++ operator compilation error with Tensorflow 2.1

### ISSUE THREAD

**Issue by Lillypucien** [tensorflow/tensorflow#36064]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.1
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip
- CUDA/cuDNN version: CUDA 10.1, cuDNN 7.6.5.32
- GPU model and memory: NVIDIA Quadro M2000 4GB

**Describe the problem**
Compilation error in tensorblockv2.h (see log below) when building a custom C++ operator for Tensorflow 2.1 on Microsoft Visual Studio 2017. Note that the same custom operator compiles without any error for Tensorflow 2.0, this issue is specific to Tensorflow 2.1.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
1>e:\programfiles\anaconda3\envs\tensorflow2_python36\lib\site-packages\tensorflow_core\include\unsupported\eigen\cxx11\src\tensor\tensorblockv2.h(736): warning C4346: 'Eigen::internal::StridedLinearBufferCopy<Scalar,IndexType>::Kind': dependent name is not a type
1>e:\programfiles\anaconda3\envs\tensorflow2_python36\lib\site-packages\tensorflow_core\include\unsupported\eigen\cxx11\src\tensor\tensorblockv2.h(736): note: prefix with 'typename' to indicate a type
1>e:\programfiles\anaconda3\envs\tensorflow2_python36\lib\site-packages\tensorflow_core\include\unsupported\eigen\cxx11\src\tensor\tensorblockv2.h(842): note: see reference to class template instantiation 'Eigen::internal::StridedLinearBufferCopy<Scalar,IndexType>' being compiled
1>e:\programfiles\anaconda3\envs\tensorflow2_python36\lib\site-packages\tensorflow_core\include\unsupported\eigen\cxx11\src\tensor\tensorblockv2.h(736): error C2061: syntax error: identifier 'Kind'
1>e:\programfiles\anaconda3\envs\tensorflow2_python36\lib\site-packages\tensorflow_core\include\unsupported\eigen\cxx11\src\tensor\tensorblockv2.h(745): warning C4346: 'Eigen::internal::StridedLinearBufferCopy<Scalar,IndexType>::Kind': dependent name is not a type
1>e:\programfiles\anaconda3\envs\tensorflow2_python36\lib\site-packages\tensorflow_core\include\unsupported\eigen\cxx11\src\tensor\tensorblockv2.h(745): note: prefix with 'typename' to indicate a type
1>e:\programfiles\anaconda3\envs\tensorflow2_python36\lib\site-packages\tensorflow_core\include\unsupported\eigen\cxx11\src\tensor\tensorblockv2.h(745): error C2061: syntax error: identifier 'Kind'
```

**Comment by vistart** [comment]
Would you like to show your custom operator source code and its compilation process? It would be better if there was test code.

**Comment by Lillypucien** [comment]
Thank you for your interest in my issue, but the problem seems to be explicitely due to the compilation of this tensorblockv2.h header and not to my custom operator themselves.
All of my custom operators used to compile fine with Tensorflow 2.0 and with Tensorflow 2.1 none of them (including a simple identity test operator) compile, with the same error in the tensorblockv2 header.

**Comment by josdewitte** [comment]
Comparable issue here; also in TensorBlock.h; Win10 x64; TF2.1; seems to have something to do with Eigen library? Should we include our own version somehow? Following anyway

\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorBlock.h(1028): error C2061: syntax error: identifier 'Kind'
\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorBlock.h(1134): note: see reference to class template instantiation 'Eigen::internal::StridedLinearBufferCopy<Scalar,IndexType>' being compiled
\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorBlock.h(1037): error C2061: syntax error: identifier 'Kind'

**Comment by fbobital** [comment]
I have the same error in my macOS Catalina v10.15.2

**Comment by josdewitte** [comment]
No. Building on Win10 x64 using Bazel and TF2.1, no XLA, CUDA, and the likes, CPU only. No custom operators. Both master and r2.1 versions do not build. Tried VS2017 and VS2019.

**Comment by Lillypucien** [comment]
Any news on this issue? Unfortunately, we are unable to switch to TF 2.1 if we are not able to build our custom operators anymore.

**Comment by gunan** [comment]
Sorry for missing this issue so far.
@yifeif is our custom ops expert. Yifei, any ideas on this one?

**Comment by Lillypucien** [comment]
Any update on this issue?

**Comment by Lillypucien** [comment]
Any update ?

**Comment by 07rafix** [comment]
I had the similar problems with TF2.1 and Eigen (_tensorblockv2.h_ file from _unsupported_ module).

You can upgrade your compiler to VS 2019 or in older varsions you could put the keyword **typename** to all places where the errors come from, for example:

`template <StridedLinearBufferCopy::Kind kind>`

should be replaced by

`template <typename StridedLinearBufferCopy::Kind kind>`

**Kind** is dependent name, so it should be preceded by **typename**.

**Comment by yifeif** [comment]
+1 on what @07rafix said, we did [switched to VS2019](https://github.com/tensorflow/tensorflow/issues/35036#issuecomment-565611549) when building TF 2.1. Would you mind give that a try @Lillypucien?

**Comment by Lillypucien** [comment]
Both solutions given by @07rafix indeed work, thanks. 
By the way, I had another issue while building my custom operators: files located in "tensorflow_core/include/tensorflow_core/core" still have includes to "tensorflow/core",  which doesn't exist anymore.

**Comment by ruddyscent** [comment]
The solution using VS2019 works for me. However, be sure to remove 'MSVC v* - VS 2015 C++ build tools.'
