### ISSUE TITLE
Tensorflow 2.0: where is tf.contrib.layers.layer_norm?

### ISSUE THREAD

**Issue by chwang85** [tensorflow/tensorflow#26854]
Cannot find tf.contrib.layers.layer_norm in TF 2.0

**Comment by facaiy** [comment]
Hi, it has been moved to addons: https://github.com/tensorflow/addons/tree/master/tensorflow_addons/layers

**Comment by facaiy** [comment]
@martinwicke @seanpmorgan Hi, Martin, Sean, can we find a way to let users easily know where those modules of contrib have gone?

I know we have had https://github.com/tensorflow/community/pull/37 and https://github.com/tensorflow/community/pull/18 , but unfortunately, it seems that not all users would like to read it.

**Comment by seanpmorgan** [comment]
It's been discussed that we should add deprecation warnings to tf.contrib which instruct users of the move to addons for certain functions/classes. We would need to get these in before the 1.14 release I believe, so still some time but we should probably create an issue to track that. 

Also, those same warnings should be added to the t2_convert script which instruct users where they can be found.

**Comment by dynamicwebpaige** [comment]
We could also add the replacements to the [1:1 Symbols Map](https://docs.google.com/spreadsheets/d/1FLFJLzg7WNP6JHODX5q8BDgptKafq_slHpnHVbJIteQ/edit#gid=0).

**Comment by chwang85** [comment]
I have noticed that it is `tf.keras.layers.experimental.LayerNormalization` in TF 2.0
But `tf.keras.layers.experimental.LayerNormalization` is not in TF 1.13
Will it appear in TF 1.14?

**Comment by seanpmorgan** [comment]
> I have noticed that it is `tf.keras.layers.experimental.LayerNormalization` in TF 2.0
> But `tf.keras.layers.experimental.LayerNormalization` is not in TF 1.13
> Will it appear in TF 1.14?

I would not expect tf.keras.layers.experiment.LayerNormalization to continue to exist in TF 2.0 for much longer. See the conversation in https://github.com/tensorflow/addons/pull/14 . Its on our TODO to request the removal of it.

**Comment by chwang85** [comment]
So what to use instead of it???

**Comment by seanpmorgan** [comment]
For TF2.x
https://github.com/tensorflow/addons
https://github.com/tensorflow/addons/blob/master/tensorflow_addons/layers/normalizations.py#L277

**Comment by chwang85** [comment]
So finally there will be only `tf.keras.xxx.GroupNormalization`?
`tf.keras.xxx.LayerNormalization` will be removed?

**Comment by seanpmorgan** [comment]
Sorry I'll try to explain more clearly. TensorFlow addons is an additional python package that contains extra functionality for core tensorflow. One of the layers available in that package is LayerNormalization. Our implementation utilizes the fact that LayerNormalization is just one configuration of GroupNormalization. Feel free to use the `LayerNormalization` end point though.

```
import tensorflow as tf
import tensorflow_addons as tfa

tfa.layers.LayerNormalization()
```

**Comment by chwang85** [comment]
My understanding is that tfa is to replace tf.contrib, and tf.keras is to replace tf.layers?

**Comment by seanpmorgan** [comment]
Yeah that's true enough. One thing to note is that layers/optimizers/etc. in tensorflow_addons all subclass a tf.keras base class so they'll have the same api structure.

**Comment by chwang85** [comment]
Thanks a lot...
But I prefer the previous TF, which is simpler.

**Comment by seanpmorgan** [comment]
Entitled to your opinion, but I think you'll find tf.keras API spec is very intuitive and a better user experience now that everything is unified under one design.

 If you are referring to the fact that contrib got to exist in the same package as core.. thats true, but it  also [became unmanagable](https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md) and there were very little guarantees that the code you were running was behaving correctly. I think [you'll see going forward [all of tensorflow is moving to a more modular approach](https://github.com/tensorflow/community/pull/77)

**Comment by chwang85** [comment]
tf.keras still has a lot of problems in combining with other tf components...
see #27016 for example

**Comment by martinwicke** [comment]
@chwang85 -- variable_scope had a nasty habit of not being very composable. We have removed it from the 2.0 API (it remains available in `compat.v1` just like everything else). 

If you prefer the "simpler" lower level API, it's still all there, you can absolutely still use it. In fact, it's likely easier to use, since we cleaned up a bunch so similar things don't appear in several places any more.

I think this issue is resolved, right?

**Comment by chwang85** [comment]
These lower level API (e.g. tf.layers.dense) is the most useful part of TF (at least for me, a ML developer), but now every time I use them, there will be a disgusting message: `xxx (from tensorflow.python.layers.core) is deprecated and will be removed in a future version. Use keras.layers.xxx instead.` However, it seems that tf.keras.layers is not equivalent with tf.layers (see the variable scope issue), are your message fooling users?

**Comment by martinwicke** [comment]
No, the Keras layers are pretty much equivalent in functionality. That does not mean they are drop in replacements. For a drop-in replacement, use tf.compat.v1.layers. 

Note also that tf.layers.* are not lower level than Keras layers in any meaningful way. They are definitely more magic, since they rely on a lot of global (or graph) state to work at all.

In keras layers, we removed support for this graph based state, most visibly with variable_scope. We have also changed the way variables were exposed (not via collections any longer). We believe these changes are highly beneficial for code quality and improve your ability to reason about your code. The message therefore suggests you move to keras layers.

**Comment by chwang85** [comment]
I strongly wish TF 1.x should stick on "Graph". TF 2.x may focus on "Eager". Just like Python 2.x vs Python 3.x

**Comment by martinwicke** [comment]
It will. The only thing we're doing to 1.x is to add deprecation notices. 

If you'd like you can disable the deprecation warnings, you can use (it's not part of the public API, but hey):

```
import tensorflow.python.util.deprecation as deprecation
deprecation._PRINT_DEPRECATION_WARNINGS = False
```

**Comment by chwang85** [comment]
Two questions to confirm:
1. Will TF 1.X still be updated after TF 2.X is officially issued? 
2. Will tf.layers.dense (and so on) always stay in TF 1.X?

**Comment by chwang85** [comment]
By the way, before deprecating old components, would you please complete the current functionality? See #27042. It seems that TF is very good at deprecating widely used functions, but poor at improving its weak points

**Comment by Oktai15** [comment]
@seanpmorgan I can't find layer normalization if tfa. 

module 'tensorflow_addons.layers' has no attribute 'LayerNormalization'

**Comment by seanpmorgan** [comment]
@Oktai15  apologies these comments are a bit stale. TensorFlow core actually pull LayerNormalization in so we removed it from Addons. In the future we'll have a more stable deprecation process this was just very early on in our growth.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/layers/normalization.py#L843

`tf.keras.layers.LayerNormalization`

**Comment by adiv5** [comment]
tf.keras.layers.LayerNormalization takes layer as input.How can i provide similar input structure to that of tf 1.x? eg. What to do in this case.
```


def layer_norm(input_tensor, name=None):
  """Run layer normalization on the last dimension of the tensor."""
  return tf.contrib.layers.layer_norm(
      inputs=input_tensor, begin_norm_axis=-1, begin_params_axis=-1, scope=name)


def layer_norm_and_dropout(input_tensor, dropout_prob, name=None):
  """Runs layer normalization followed by dropout."""
  output_tensor = layer_norm(input_tensor, name)
  output_tensor = dropout(output_tensor, dropout_prob)
  return output_tensor
```

**Comment by ibrahimishag** [comment]
> tf.keras.layers.LayerNormalization takes layer as input.How can i provide similar input structure to that of tf 1.x? eg. What to do in this case.
> 
> ```
> 
> 
> def layer_norm(input_tensor, name=None):
>   """Run layer normalization on the last dimension of the tensor."""
>   return tf.contrib.layers.layer_norm(
>       inputs=input_tensor, begin_norm_axis=-1, begin_params_axis=-1, scope=name)
> 
> 
> def layer_norm_and_dropout(input_tensor, dropout_prob, name=None):
>   """Runs layer normalization followed by dropout."""
>   output_tensor = layer_norm(input_tensor, name)
>   output_tensor = dropout(output_tensor, dropout_prob)
>   return output_tensor
> ```
> 
> How to convert this snippet?
Hello adiv5,
Were you able to work around this? I assume you are trying to upgrade BERT to work in Tensnorflow 2.0.

**Comment by luvwinnie** [comment]
Hi! @adiv5, I;m working on converting BERT to tensorflow 2.0, i faced the same problem with this, have you been able to work around with this? if so please share the solution. If this is not able to do so, i think to rewrite the BERT to tensorflow 2.0 keras....but at least run it on pretraining..

**Comment by saberkun** [comment]
Hi.
tf.keras.layers.LayerNormalization is the replacement.
You may need to wrap the layer_norm_and_dropout function as a layer and
create a layer norm instance attaching to self.
For BERT, you should not have problem to rewrite.
We have the bert model in TF official models.
See the LayerNormalization usage in this library
https://github.com/tensorflow/models/blob/master/official/nlp/modeling/networks/transformer_encoder.py#L134

Thanks

**Comment by luvwinnie** [comment]
@saberkun Thank you ! I have been able to change the below code to working on pretraning.

```
def layer_norm(input_tensor, name=None):
  """Run layer normalization on the last dimension of the tensor."""
  return tf.keras.layers.LayerNormalization(name=name,axis=-1,epsilon=1e-12,dtype=tf.float32)(input_tensor)
  # return tf.contrib.layers.layer_norm(
  #     inputs=input_tensor, begin_norm_axis=-1, begin_params_axis=-1, scope=name)
```

**Comment by someAdjectiveNoun** [comment]
> My understanding is that tfa is to replace tf.contrib, and tf.keras is to replace tf.layers?

AttributeError: module 'tensorflow_addons.layers' has no attribute 'LayerNormalization'

**Comment by seanpmorgan** [comment]
> > My understanding is that tfa is to replace tf.contrib, and tf.keras is to replace tf.layers?
> 
> AttributeError: module 'tensorflow_addons.layers' has no attribute 'LayerNormalization'

LayerNorm was moved to TF-core:
https://www.tensorflow.org/api_docs/python/tf/keras/layers/LayerNormalization

Sorry for the stale information.

**Comment by someAdjectiveNoun** [comment]
> > > My understanding is that tfa is to replace tf.contrib, and tf.keras is to replace tf.layers?
> > 
> > 
> > AttributeError: module 'tensorflow_addons.layers' has no attribute 'LayerNormalization'
> 
> LayerNorm was moved to TF-core:
> https://www.tensorflow.org/api_docs/python/tf/keras/layers/LayerNormalization
> 
> Sorry for the stale information.

Thanks for the update.
Unfortunately, the inputs to LayerNormalization are different from layer_norm. Is there a workaround for it or?

**Comment by jojivk73** [comment]
@luvwinnie Is you model converging for fine-tuning. I see that the model does not converge for SQuAD with this change for TF 1.x model.

**Comment by luvwinnie** [comment]
@jojivk73 yeah my model is converging, i reference this [repo](https://github.com/yoheikikuta/bert-japanese) for fine tuning Japanese corpus, below is my graph.
<img width="1544" alt="Screen Shot 2020-03-18 at 10 31 26" src="https://user-images.githubusercontent.com/13714992/76916441-c50cf300-6903-11ea-9715-bddcb6320503.png">

**Comment by evelynphang88** [comment]
def instance_norm(x, scope='instance_norm'):
         return tf_contrib.layers.instance_norm(x,epsilon=1e-05,center=True, scale=True,scope=scope)

How to convert this tensorflow 2.2 ??
