### ISSUE TITLE
TypeError: metaclass conflict in Python 2 and 3

### ISSUE THREAD

**Issue by pronobis** [tensorflow/tensorflow#487]
TF 0.6.0 installed using PIP gives the following error on import in both Python 2 and 3:

```
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.4/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/home/user/.local/lib/python3.4/site-packages/tensorflow/python/__init__.py", line 37, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/home/user/.local/lib/python3.4/site-packages/tensorflow/core/framework/graph_pb2.py", line 10, in <module>
    from google.protobuf import descriptor_pb2
  File "/home/user/.local/lib/python3.4/site-packages/google/protobuf/descriptor_pb2.py", line 1533, in <module>
    __module__ = 'google.protobuf.descriptor_pb2'
  File "/home/user/.local/lib/python3.4/site-packages/google/protobuf/reflection.py", line 123, in __new__
    new_class = superclass.__new__(cls, name, bases, dictionary)
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

**Comment by vrv** [comment]
This error seems to be in the protobuf library (and wasn't something we ran into when testing python 3).  Do you think you could file this bug over at https://github.com/google/protobuf ? I don't think we know enough about protobuf ... :(

**Comment by pronobis** [comment]
Ok, I have no idea what that was, but deleting and re-installing protobuf solved the problem.

**Comment by PeterARBork** [comment]
Pronobis can you tell how you deleted and re-installed protobuf?

I uninstalled and re-installed protobuf with pip3, but got a new error out of that ("AttributeError: 'module' object has no attribute 'MutableMapping').

Your help would be greatly appreciated :-).

**Comment by Vesnica** [comment]
sudo pip uninstall protobuf
sudo pip install protobuf==3.0.0a3
sudo pip uninstall tensorflow
sudo pip install tensorflow-xxx-xxx.whl

Works for me. @PeterARBork

**Comment by arcecio** [comment]
Thank you @Vesnica !

**Comment by dcunited001** [comment]
+1 😀

**Comment by EricGT** [comment]
+1

**Comment by lifematrix** [comment]
Thanks, @Vesnica 
I encountered the same issue, and solved by following your instruction.

**Comment by junluan** [comment]
thanks

**Comment by hsaito** [comment]
I'm encountering this problem as of 0.7.0 (was working fine on 0.6.0) which seems to be not resolving even after reinstallation of protobut as shown above. Anyone else seeing the same problem?

**Comment by rob2001** [comment]
^Hsaito, this didn't fix the problem for me either

**Comment by hsaito** [comment]
After some investigation, I think I see what's going on. You have to uninstall protobuf (and you may have to run this several types just to make sure it's completely gone.) and then install protobuf==3.0.0b2 instead of protobuf==3.0.0a3, and looks like it's working.

**Comment by danijar** [comment]
Had the same error when importing Tensorflow 0.7.0 with Python3. What worked for me is adding an alias to my `~/.profile` that set Python 3 as default.

    alias python="python3"

**Comment by PhoenixDai** [comment]
+1 I just uninstalled protobuf and reinstalled with protobuf==3.0.0b2 and it's working now

**Comment by LeonardSellam** [comment]
+1 I had the same issue. 
I just had to reinstall protobuf : pip uninstall protobuf then pip install protobuf==3.0.0b2 and it would be able to import TensorFlow;)

**Comment by theludachris** [comment]
Would there be any reason that this procedure would be different for python 2.7 instead of python3? I've gone through all the steps above, but am still getting this error:

```
Python 2.7.10 (default, Oct 23 2015, 18:05:06) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/Library/Python/2.7/site-packages/tensorflow/python/__init__.py", line 35, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/Library/Python/2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 10, in <module>
    from google.protobuf import descriptor_pb2
  File "/Library/Python/2.7/site-packages/google/protobuf/descriptor_pb2.py", line 1533, in <module>
    __module__ = 'google.protobuf.descriptor_pb2'
  File "/Library/Python/2.7/site-packages/google/protobuf/reflection.py", line 123, in __new__
    new_class = superclass.__new__(cls, name, bases, dictionary)
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

Any ideas?  Thanks for any pointers.

**Comment by hsaito** [comment]
@theludachris As long as you are doing the procedure with correct version of pip (and pip3 for Pythob3) it should work. Is python symlinked to the same version of python as shown on the very first line of pip script?

**Comment by seansaito** [comment]
+1 @hsaito 's solution works for me too. Using Ubuntu 14.04.4

**Comment by theludachris** [comment]
Thanks for the tips. I think I figured it out - separately, I was getting
some earlier errors in the install process ('operation not permitted'), and
discovered that OSX El Capitan last month added something called SIP which
was partially screwing up my installation.  I went ahead and tried the
virtualenv installation and everything is working.

**Comment by gbouchar** [comment]
+1
great thanks !
