### ISSUE TITLE
tensorflow/core/framework/op_def.pb.h:10:40: fatal error: google/protobuf/port_def.inc: No such file or directory

### ISSUE THREAD

**Issue by alsrgv** [tensorflow/tensorflow#27697]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): use plugin
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): tensorflow/tensorflow:latest-gpu-py3
- TensorFlow version (use command below): 1.14.1-dev20190409
- Python version: 3.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
As of `1.14.1-dev20190409`, custom plugins fail to build with the following error:

```
  In file included from /usr/local/lib/python2.7/dist-packages/tensorflow/include/tensorflow/core/framework/op_def_builder.h:24:0,
                   from /usr/local/lib/python2.7/dist-packages/tensorflow/include/tensorflow/core/framework/op.h:23,
                   from horovod/tensorflow/mpi_ops.cc:22:
  /usr/local/lib/python2.7/dist-packages/tensorflow/include/tensorflow/core/framework/op_def.pb.h:10:40: fatal error: google/protobuf/port_def.inc: No such file or directory
   #include <google/protobuf/port_def.inc>
                                          ^
  compilation terminated.
```

This seems to be related to https://github.com/tensorflow/tensorflow/commit/6168f476b52d6d40eeff1823943ed2c0ea28adde.  It appears that not all the files are placed in the proper locations after the installation.

**Describe the expected behavior**
Plugins should build successfully.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```
$ docker run -it --rm tensorflow/tensorflow:latest-gpu-py3
# apt install -y mpich
# HOROVOD_WITH_TENSORFLOW=1 pip install -v horovod
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

cc @martinwicke @gunan

**Comment by seanpmorgan** [comment]
This is also breaking https://github.com/tensorflow/addons on tf2-nightly.

Logs:
https://source.cloud.google.com/results/invocations/1fcf8227-5161-4cb8-a017-a1a906c9429d/targets/tensorflow_addons%2Fubuntu%2Fgpu%2Fpy3%2Fcontinuous/log

**Comment by qlzh727** [comment]
Assigning to @yifeif who reviewed cl/242492263, and also cc @gunan.

**Comment by angersson** [comment]
Un-assigning so this'll get into the issue-assignee system.

**Comment by angersson** [comment]
Also: @meteorcloudy

**Comment by meteorcloudy** [comment]
@seanpmorgan @gunan Is tf addons somehow using this BUILD file?
https://github.com/tensorflow/tensorflow/blob/3fb94abb517fc054bc299aeac841c87be326b88a/third_party/systemlibs/protobuf.BUILD#L15-L25
@acozzette Dose it make sense to you to add `google/protobuf/port_def.inc` here?

**Comment by seanpmorgan** [comment]
We don't use the BUILD file itself. We link to the pre-compiled `libtensorflow_framework`. 

It looks like the op_def.pb header file is referencinng a file which is not where it is expected after the new protobuf install.
```
tensorflow/core/framework/op_def.pb.h:10:40: fatal error: google/protobuf/port_def.inc: No such file or directory
 #include <google/protobuf/port_def.inc>
```

**Comment by alsrgv** [comment]
Same here, we're not using Bazel.

**Comment by meteorcloudy** [comment]
Looks like the problem is when creating the pip package, we missed to copy header files that has `.inc` extension.
https://github.com/tensorflow/tensorflow/blob/1cdae4922cfe6821eafb163d9f825e29b4f1fc80/tensorflow/tools/pip_package/build_pip_package.sh#L128-L130

I'll send a fix for this.

**Comment by seanpmorgan** [comment]
Still seeing this issue in the 20190412 nightly. Was this merged in yet? If so I'm not sure the correct fix is in place.


`https://files.pythonhosted.org/packages/d4/c9/0fb753c0d182cfa10294edaa610d19f236da0396c636c24dccaa669bc81d/tf_nightly_2.0_preview-2.0.0.dev20190412-cp34-cp34m-manylinux1_x86_64.whl (86.5MB)`

`bazel-out/k8-opt/genfiles/external/local_config_tf/include/tensorflow/core/framework/types.pb.h:10:40: fatal error: google/protobuf/port_def.inc: No such file or directory`

https://source.cloud.google.com/results/invocations/fb7847e9-3cd6-4b07-9394-efe9f948f42e/targets/tensorflow_addons%2Fubuntu%2Fgpu%2Fpy3%2Fcontinuous/log

**Comment by alsrgv** [comment]
+1, it's still broken in the current tf-nightly.

**Comment by meteorcloudy** [comment]
Turned out we also need to fix `steup.py`:
https://github.com/tensorflow/tensorflow/blob/1cdae4922cfe6821eafb163d9f825e29b4f1fc80/tensorflow/tools/pip_package/setup.py#L240

**Comment by meteorcloudy** [comment]
I verified on my local machine, fixing this file works. Sending a fix from internal.

**Comment by seanpmorgan** [comment]
@meteorcloudy today I tried building our package on OS X and ran into this error again

```
In file included from bazel-out/darwin-fastbuild/genfiles/external/local_config_tf/include/tensorflow/core/framework/op.h:23:
In file included from bazel-out/darwin-fastbuild/genfiles/external/local_config_tf/include/tensorflow/core/framework/op_def_builder.h:24:
bazel-out/darwin-fastbuild/genfiles/external/local_config_tf/include/tensorflow/core/framework/op_def.pb.h:10:10: fatal error: 'google/protobuf/port_def.inc' file not found
#include <google/protobuf/port_def.inc>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
```
$ pip list | grep tf-nightly
tf-nightly-2.0-preview           2.0.0.dev20190419 
```

This isn't immedietely obvious to me why this would be happening unless the regex was failing, or osx protobuf is different? I tried purging bazel cache etc. to make sure it wasn't a my environment issue.

**Comment by seanpmorgan** [comment]
Just saw https://github.com/tensorflow/custom-op/issues/13 which looks to be another example of this happening on OSX nightly.

**Comment by gunan** [comment]
pb.h looks suspicious to me. I think we only try to use proto.h headers for protos.
@yifeif @martinwicke

**Comment by meteorcloudy** [comment]
@seanpmorgan I don't know why mac should be any different, but I don't have a mac machine to debug this. Can you try to build the pip package on mac and check if the head files are correctly included in the whl file? (You can just unzip it and check the include folder).

**Comment by meteorcloudy** [comment]
@gunan Where can I download the nightly binaries for all platforms?

**Comment by seanpmorgan** [comment]
@meteorcloudy binaries:
https://pypi.org/project/tf-nightly/#files

So the linux whl has `port_def.inc` in both:
```
tf_nightly-1.14.1.dev20190423.data/purelib/tensorflow/include/external/protobuf_archive/src/google/protobuf
tf_nightly-1.14.1.dev20190423.data/purelib/tensorflow/include/google/protobuf
```

While mac has `port_def.inc` in only:
```
tf_nightly-1.14.1.dev20190423.data/purelib/tensorflow/include/external/protobuf_archive/src/google/protobuf
```

**Comment by meteorcloudy** [comment]
@seanpmorgan 
Looks like `regex` in `find` does behave differently on macos:
https://stackoverflow.com/questions/5905493/why-isnt-this-regex-working-find-regex-m-h

https://github.com/tensorflow/tensorflow/blob/d65760b805cdd729743ba3d7c7b4ae8897304dd6/tensorflow/tools/pip_package/build_pip_package.sh#L128

I will change it to 
```
find protobuf_archive -type f \( -name "*.h" -o -name "*.inc" \)
```

**Comment by uber-gc** [comment]
@meteorcloudy, I'm afraid the latest change has broken Linux and did not fix Mac:

```
$ unzip -l tf_nightly-1.14.1.dev20190425-cp27-cp27m-macosx_10_9_x86_64.whl | grep \\.inc | grep port_def
    11642  04-26-2019 00:53   tf_nightly-1.14.1.dev20190425.data/purelib/tensorflow/include/external/protobuf_archive/src/google/protobuf/port_def.inc
$ unzip -l tf_nightly-1.14.1.dev20190425-cp27-cp27mu-manylinux1_x86_64.whl | grep \\.inc | grep port_def
    11642  04-26-2019 00:37   tf_nightly-1.14.1.dev20190425.data/purelib/tensorflow/include/external/protobuf_archive/src/google/protobuf/port_def.inc
$ unzip -l tf_nightly-1.14.1.dev20190424-cp27-cp27mu-manylinux1_x86_64.whl | grep \\.inc | grep port_def
    11642  04-24-2019 08:45   tf_nightly-1.14.1.dev20190424.data/purelib/tensorflow/include/google/protobuf/port_def.inc
    11642  04-24-2019 08:45   tf_nightly-1.14.1.dev20190424.data/purelib/tensorflow/include/external/protobuf_archive/src/google/protobuf/port_def.inc
```

**Comment by alsrgv** [comment]
@meteorcloudy, I'm afraid the latest change has broken Linux and did not fix Mac:

```
$ unzip -l tf_nightly-1.14.1.dev20190425-cp27-cp27m-macosx_10_9_x86_64.whl | grep \\.inc | grep port_def
    11642  04-26-2019 00:53   tf_nightly-1.14.1.dev20190425.data/purelib/tensorflow/include/external/protobuf_archive/src/google/protobuf/port_def.inc
$ unzip -l tf_nightly-1.14.1.dev20190425-cp27-cp27mu-manylinux1_x86_64.whl | grep \\.inc | grep port_def
    11642  04-26-2019 00:37   tf_nightly-1.14.1.dev20190425.data/purelib/tensorflow/include/external/protobuf_archive/src/google/protobuf/port_def.inc
$ unzip -l tf_nightly-1.14.1.dev20190424-cp27-cp27mu-manylinux1_x86_64.whl | grep \\.inc | grep port_def
    11642  04-24-2019 08:45   tf_nightly-1.14.1.dev20190424.data/purelib/tensorflow/include/google/protobuf/port_def.inc
    11642  04-24-2019 08:45   tf_nightly-1.14.1.dev20190424.data/purelib/tensorflow/include/external/protobuf_archive/src/google/protobuf/port_def.inc
```

**Comment by meteorcloudy** [comment]
@alsrgv This is strange.. I tested locally, let me take a look now

**Comment by alsrgv** [comment]
@meteorcloudy, I do see this warning in your `devel-gpu` container during pip package build, perhaps it will help diagnose the issue:
```
find: Arguments to -type should contain only one letter
```

**Comment by meteorcloudy** [comment]
Ah, I see. The `find` command is different on all kinds of platform. I'll try to figure out a fix.

**Comment by meteorcloudy** [comment]
Can anyone verify `find protobuf_archive -name "*.h" -o -name "*.inc"` works for their platform?

**Comment by alsrgv** [comment]
It worked on my Mac, Ubuntu 18.04 and your `devel` container, so seems promising :-)

**Comment by meteorcloudy** [comment]
@alsrgv Thanks! Hopefully this time it will work

**Comment by alsrgv** [comment]
@meteorcloudy, I can confirm that both Mac and Linux nightly builds are operational.  Could you pick this fix to the 1.4 branch?

**Comment by meteorcloudy** [comment]
@gunan @yifeif Can you help pick this fix to 1.4 branch?

**Comment by martinwicke** [comment]
@bananabowl can you cherry-pick this fix?

**Comment by bananabowl** [comment]
Sure - this is part of https://github.com/tensorflow/tensorflow/pull/28296

**Comment by andreyhristov** [comment]
Hi,
I experience this problem with 1.14.0 . From what I see in the sources, as well as bananabowl's comment / reference to the cherry picks, the needed changes are in 1.14.0. Still getting the problem.
Here is the error:
```
In file included from ./deps/tensorflow-headers-1.14.0/tensorflow/core/framework/tensor_shape.h:22:0,
                 from ./deps/tensorflow-headers-1.14.0/tensorflow/core/framework/tensor.h:23,
                 from ./deps/tensorflow-headers-1.14.0/tensorflow/cc/framework/ops.h:21,
                 from ./deps/tensorflow-headers-1.14.0/tensorflow/cc/client/client_session.h:24,
                 from ./include/detect_tensorflow.hpp:5,
                 from src/detect_tensorflow.cpp:1:
./deps/tensorflow-headers-1.14.0/tensorflow/core/framework/types.pb.h:10:10: fatal error: google/protobuf/port_def.inc: No such file or directory
 #include <google/protobuf/port_def.inc>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
I am using the headers generated by //tensorflow:install_headers .
Platform : AARCH64
OS : Ubuntu 18.04 LTS
Hardware: Nvidia Xavier AGX
Software: TensorFlow 1.14.0 from a source release. Compiled with Bazel 0.24.1 (from a dist package).

**Comment by bananabowl** [comment]
Sorry to hear that Andrey :(

@mihaimaruseac - I noticed you made some changes since the original fix,
was this
<https://github.com/tensorflow/tensorflow/commit/fd5d844765a1d41f18c4f3f712f28a7c0220dc33#diff-aa53f753fc372beaeb504d505c278203>
or
a subsequent change meant to fix this issue?

**Comment by mihaimaruseac** [comment]
Hi, the fd5d844765a1d41f18c4f3f712f28a7c0220dc33 change is for virtual pip, should be on master only, not on a release branch.

There's also some changes related with moving protobuf definitions around, but again, that should only be on master.

**Comment by mihaimaruseac** [comment]
So, the commits that I know can affect this are fd5d844765a1d41f18c4f3f712f28a7c0220dc33, 338c2f269b1dfc13fe8f94c6cf9c64b4ae82b928 and 508f76b1d9925304cedd56d51480ec380636cb82

Could try patching each one of these manually and see which works

**Comment by andreyhristov** [comment]
I tried the master branch. Interestingly it seems to be 1.13.1 (because the generated PIP file is tensorflow-1.13.1-cp36-cp36m-linux_aarch64.whl). The problem persist but it could be that master is not the right branch (is not actively used). Is it?

**Comment by meteorcloudy** [comment]
@andreyhristov The master branch is the develop branch. 
I tried to build `//tensorflow:include_headers` on the latest master branch, it does contain the `port_def.inc`

```
$ bazel build --config=opt //tensorflow:install_headers
...
Target //tensorflow:install_headers up-to-date:
  bazel-genfiles/tensorflow/include
INFO: Elapsed time: 0.239s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
$ ls ./bazel-genfiles/tensorflow/include/external/com_google_protobuf/src/google/protobuf/port_def.inc
./bazel-genfiles/tensorflow/include/external/com_google_protobuf/src/google/protobuf/port_def.inc
```

**Comment by meteorcloudy** [comment]
And in 1.14 branch, the ".inc" file headers also exist but under `external/protobuf_archive` directory.
```
ls ./bazel-genfiles/tensorflow/include/external/protobuf_archive/src/google/protobuf/port_def.inc
./bazel-genfiles/tensorflow/include/external/protobuf_archive/src/google/protobuf/port_def.inc
```

**Comment by andreyhristov** [comment]
ok guys, right, I found the file. The problem was that I needed to add the path to protobuf_archive to the include path of the compiler. I compiles now and it works! (I had asserts with 1.12.0 on batch inferencing which are gone).

Last question, why does master seem to be with version 1.13.1 ? Do you guys change the version after branching for release?

**Comment by meteorcloudy** [comment]
Yes, it's embedded here:
https://github.com/tensorflow/tensorflow/blob/c19265ba0ee2622e391bd319a74c14ad2eb79017/tensorflow/tools/pip_package/setup.py#L50

@gunan Is this intentionally?

**Comment by mihaimaruseac** [comment]
Fixed the version number in 4a017ecb42f536a63de9387c67dbec704dfd9188

**Comment by andreyhristov** [comment]
Hi,
what I did for my program was to pass a -I param to the compiler, so it does know where to look for the files.
I use a Makefile, and also export a TENSORFLOW_PATH variable, which contains the path to the headers. The headers can be extracted with a bazel target. For me the flag to gcc is :
-I$(TENSORFLOW_PATH)/external/protobuf_archive/src

**Comment by suyashbakshi** [comment]
Hello, I'm still seeing this issue with tf1.14.0 while compiling a custom op kernel. 
`fatal error: google/protobuf/port_def.inc: No such file or directory
 #include <google/protobuf/port_def.inc>
compilation terminated.`

I'm on windows, installed TF using pip. 
The .inc files still reside in "site-packages\tensorflow\include\google\protobuf_archive\src\google\protobuf".

Is there a way to fix this issue without building the sources manually (by using bazel)?

Any help is appreciated. Thanks!

**Comment by songmeixu** [comment]
> Hello, I'm still seeing this issue with tf1.14.0 while compiling a custom op kernel.
> `site-packages/tensorflow/include/tensorflow/core/framework/op_def.pb.h:10:10: fatal error: google/protobuf/port_def.inc: No such file or directory #include <google/protobuf/port_def.inc> compilation terminated.`
> 
> I'm on windows, installed TF using pip.
> The .inc files still reside in "site-packages\tensorflow\include\google\protobuf_archive\src\google\protobuf".
> 
> Is there a way to fix this issue without building the sources manually (by using bazel)?
> 
> Any help is appreciated. Thanks!

try include the dir solve this issue? like: `-I..\site-packages\tensorflow\include\google\protobuf_archive\src`
