### ISSUE TITLE
Build tensorflow-lite for armv7-a (embedded linux) failed

### ISSUE THREAD

**Issue by wireless-road** [tensorflow/tensorflow#50029]
**System information**
- Host platform - Ubuntu 20.04.1 LTS:
- target platform - embedded linux - OS Openwrt, CPU - IMX6ULL;
- TensorFlow installed from source:
- TensorFlow version: 2.6.0
- Cross compilation using C++ and CMake. CMake version - 3.16.0



**Describe the problem**

Trying to cross-compile Tensorflow-lite minimal c++ example using CMake.

```
-DCMAKE_SYSTEM_PROCESSOR=armv7-a
```

Checked my target hardware as explained here: 
https://www.tensorflow.org/lite/guide/build_cmake_arm#check_your_target_environment
Here my target device /proc/cpuinfo output:
```
root@OpenWrt:/# cat /proc/cpuinfo                                                                                                                                                        
processor       : 0                                                                                                                                                                      
model name      : ARMv7 Processor rev 5 (v7l)                                                                                                                                            
BogoMIPS        : 109.09                                                                                                                                                                 
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae                                                                                              
CPU implementer : 0x41                                                                                                                                                                   
CPU architecture: 7                                                                                                                                                                      
CPU variant     : 0x0                                                                                                                                                                    
CPU part        : 0xc07                                                                                                                                                                  
CPU revision    : 5                                                                                                                                                                      
                                                                                                                                                                                         
Hardware        : Freescale i.MX6 Ultralite (Device Tree)                                                                                                                                
Revision        : 0000                                                                                                                                                                   
Serial          : 0000000000000000         
```                                                                                                                                              

Build fails with following error:

```
[ 85%] Building C object _deps/xnnpack-build/CMakeFiles/XNNPACK.dir/src/math/roundz-neonv8.c.o
[ 85%] Building C object _deps/xnnpack-build/CMakeFiles/XNNPACK.dir/src/qs8-gemm/gen/1x8c4-minmax-neondot.c.o
arm-openwrt-linux-muslgnueabi-gcc: error: unrecognized argument in option '-march=armv8.2-a+dotprod'
arm-openwrt-linux-muslgnueabi-gcc: note: valid arguments to '-march=' are: armv2 armv2a armv3 armv3m armv4 armv4t armv5 armv5e armv5t armv5te armv5tej armv6 armv6-m armv6j armv6k armv6kz armv6s-m armv6t2 armv6z armv6zk armv7 armv7-a armv7-m armv7-r armv7e-m armv7ve armv8-a armv8-a+crc armv8-m.base armv8-m.main armv8-m.main+dsp armv8.1-a armv8.2-a armv8.2-a+fp16 iwmmxt iwmmxt2 native; did you mean 'armv8.2-a+fp16'?
make[5]: *** [_deps/xnnpack-build/CMakeFiles/XNNPACK.dir/build.make:14766: _deps/xnnpack-build/CMakeFiles/XNNPACK.dir/src/qs8-gemm/gen/1x8c4-minmax-neondot.c.o] Error 1
make[5]: Leaving directory '/home/al/imx6ull-openwrt2/imx6ull-openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/tensorflow/tensorflow-sdk-build'
make[4]: *** [CMakeFiles/Makefile2:4062: _deps/xnnpack-build/CMakeFiles/XNNPACK.dir/all] Error 2
make[4]: Leaving directory '/home/al/imx6ull-openwrt2/imx6ull-openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/tensorflow/tensorflow-sdk-build'
make[3]: *** [Makefile:152: all] Error 2
make[3]: Leaving directory '/home/al/imx6ull-openwrt2/imx6ull-openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/tensorflow/tensorflow-sdk-build'
make[2]: *** [Makefile:67: /home/al/imx6ull-openwrt2/imx6ull-openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/tensorflow/.built] Error 2
make[2]: Leaving directory '/home/al/imx6ull-openwrt2/imx6ull-openwrt/package/tensorflow'
time: package/tensorflow/compile#211.83#30.92#311.67
make[1]: *** [package/Makefile:113: package/tensorflow/compile] Error 2
make[1]: Leaving directory '/home/al/imx6ull-openwrt2/imx6ull-openwrt'
make: *** [/home/al/imx6ull-openwrt2/imx6ull-openwrt/include/toplevel.mk:227: package/tensorflow/compile] Error 2
```

seems that error produced by following lines in `xnnpack/CMakeLists.txt` file:

```
IF(CMAKE_SYSTEM_PROCESSOR MATCHES "^armv[5-8]" OR IOS_ARCH MATCHES "^armv7")
  SET_PROPERTY(SOURCE ${XNNPACK_MICROKERNEL_SRCS} APPEND_STRING PROPERTY COMPILE_FLAGS " -marm ")
  SET_PROPERTY(SOURCE ${XNNPACK_NEON_MICROKERNEL_SRCS} APPEND_STRING PROPERTY COMPILE_FLAGS " -march=armv7-a -mfpu=neon ")
  SET_PROPERTY(SOURCE ${XNNPACK_NEONFMA_MICROKERNEL_SRCS} APPEND_STRING PROPERTY COMPILE_FLAGS " -march=armv7-a -mfpu=neon-vfpv4 ")
  IF(IOS)
    SET_PROPERTY(SOURCE ${XNNPACK_NEONV8_MICROKERNEL_SRCS} APPEND_STRING PROPERTY COMPILE_FLAGS " -mcpu=cyclone -mtune=generic ")
    SET_PROPERTY(SOURCE ${XNNPACK_AARCH32_ASM_MICROKERNEL_SRCS} APPEND_STRING PROPERTY COMPILE_FLAGS " -arch ${IOS_ARCH} ")
  ELSE()
    SET_PROPERTY(SOURCE ${XNNPACK_NEONV8_MICROKERNEL_SRCS} APPEND_STRING PROPERTY COMPILE_FLAGS " -march=armv8-a -mfpu=neon-fp-armv8 ")
    SET_PROPERTY(SOURCE ${XNNPACK_NEONDOT_MICROKERNEL_SRCS} APPEND_STRING PROPERTY COMPILE_FLAGS " -march=armv8.2-a+dotprod -mfpu=neon-fp-armv8 ")
  ENDIF()
```
Tried to edit `xnnpack/CMakeLists.txt` manually by replacing `armv8.2-a+dotprod` to `armv7-a` and `neon-fp-armv8` to `neon-vfpv4` without luck. New errors happens like `incompatible types when assigning to type 'int32x4_t' from type 'int'`.

Could you please point me to some solution of that issue?
As I understand target hardware CPU supports tensorflow lite.

**Comment by abattery** [comment]
@terryheo could you take a look?

**Comment by wireless-road** [comment]
Was able to cross compile and run on target hardware using flag `-DTFLITE_ENABLE_XNNPACK=OFF`.
But not with XNNPACK unfortunately.

**Comment by terryheo** [comment]
What's the build commands and toolchains you used? I think the current XNNPACK build only works with `-march=armv7-a`, not `armv8.2-a+dotprod`.
Is there any issue on using `-march=armv7-a`?

https://www.tensorflow.org/lite/guide/build_cmake_arm#run_cmake_2

**Comment by zxdposter** [comment]
@terryheo I have this issue too,  my cmd is 
```bash
cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_PROCESSOR=armv7 -DCMAKE_CXX_FLAGS="-march=armv7" ../tensorflow/tensorflow/lite/
```

why add **-march=armv8.2-a+dotprod** when compile
```
[ 85%] Building C object _deps/xnnpack-build/CMakeFiles/XNNPACK.dir/src/qs8-gemm/gen/1x8c4-minmax-fp32-neondot.c.o
cd /opt/module_src/tflite_build/_deps/xnnpack-build && /opt/build_env/toolchain-sunxi-musl/toolchain/bin/arm-openwrt-linux-muslgnueabi-gcc -DCPUINFO_SUPPORTED_PLATFORM=1 -DEIGEN_MPL2_ONLY -DFXDIV_USE_INLINE_ASSEMBLY=0 -DNOMINMAX=1 -DPTHREADPOOL_NO_DEPRECATED_API=1 -DXNN_ENABLE_ASSEMBLY=1 -DXNN_ENABLE_MEMOPT=1 -DXNN_ENABLE_SPARSE=1 -DXNN_LOG_LEVEL=0 -I/opt/module_src/tflite_build/xnnpack/include -I/opt/module_src/tflite_build/xnnpack/src -I/opt/module_src/tflite_build/clog-source/deps/clog/include -I/opt/module_src/tflite_build/cpuinfo-source/include -I/opt/module_src/tflite_build/pthreadpool-source/include -I/opt/module_src/tflite_build/FXdiv-source/include -I/opt/module_src/tflite_build/FP16-source/include -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/mfs/mtkslt0207/mtk71589/mt8516_rel/build/tmp/work/x86_64-nativesdk-oesdk-linux/meta-environment-aud8516-ali-slc/1.0-r8=/usr/src/debug/meta-environment-aud8516-ali-slc/1.0-r8 -fdebug-prefix-map=/mfs/mtkslt0207/mtk71589/mt8516_rel/build/tmp/sysroots/x86_64-linux= -fdebug-prefix-map=/mfs/mtkslt0207/mtk71589/mt8516_rel/build/tmp/sysroots/x86_64-nativesdk-oesdk-linux= -O3 -DNDEBUG -fPIC -Wno-psabi -pthread -std=gnu99  -marm  -march=armv8.2-a+dotprod -mfpu=neon-fp-armv8  -O2  -MD -MT _deps/xnnpack-build/CMakeFiles/XNNPACK.dir/src/qs8-gemm/gen/1x8c4-minmax-fp32-neondot.c.o -MF CMakeFiles/XNNPACK.dir/src/qs8-gemm/gen/1x8c4-minmax-fp32-neondot.c.o.d -o CMakeFiles/XNNPACK.dir/src/qs8-gemm/gen/1x8c4-minmax-fp32-neondot.c.o -c /opt/module_src/tflite_build/xnnpack/src/qs8-gemm/gen/1x8c4-minmax-fp32-neondot.c
```

**Comment by wireless-road** [comment]
Finally was able to build `tensorflow-lite` for `armv-7` by applying following patch:

```
Index: tensorflow/tensorflow-sdk-build/xnnpack/CMakeLists.txt
===================================================================
--- tensorflow.orig/tensorflow-sdk-build/xnnpack/CMakeLists.txt
+++ tensorflow/tensorflow-sdk-build/xnnpack/CMakeLists.txt
@@ -34,6 +34,8 @@ IF(XNNPACK_BUILD_TESTS)
   ENABLE_TESTING()
 ENDIF()

+ADD_DEFINITIONS(-DXNN_NO_QS8_OPERATORS)
+
 IF(XNNPACK_ENABLE_ASSEMBLY)
   ADD_DEFINITIONS(-DXNN_ENABLE_ASSEMBLY=1)
 ELSE()
@@ -2916,7 +2918,7 @@ IF(CMAKE_SYSTEM_PROCESSOR MATCHES "^armv
   LIST(APPEND XNNPACK_MICROKERNEL_SRCS ${XNNPACK_NEON_MICROKERNEL_SRCS})
   LIST(APPEND XNNPACK_MICROKERNEL_SRCS ${XNNPACK_NEONFMA_MICROKERNEL_SRCS})
   LIST(APPEND XNNPACK_MICROKERNEL_SRCS ${XNNPACK_NEONV8_MICROKERNEL_SRCS})
-  IF(NOT IOS)
+  IF(NOT IOS AND NOT CMAKE_SYSTEM_PROCESSOR MATCHES "^armv[5-8]")
     LIST(APPEND XNNPACK_MICROKERNEL_SRCS ${XNNPACK_NEONDOT_MICROKERNEL_SRCS})
   ENDIF()
   IF(XNNPACK_ENABLE_ASSEMBLY)
```

I guess that issue might be closed.

**Comment by yangyuimmerse** [comment]
My problem is very similar to yours. I didn't perform the build after cmake
