### ISSUE TITLE
import tf fails in "imp.find_module('_pywrap_tensorflow_internal',"

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#8107]
I get error below trying to import TensorFlow built at commit 7e9f2dc ([head](https://github.com/yaroslavvb/tensorflow/tree/dev) as of Sat 4).

I haven't made any changes to my [build procedure](https://github.com/yaroslavvb/tensorflow-community-wheels) in last month, and installing similarly built wheel from Mar 1 works.

Looking at relevant differences between Mar 1 and Mar 4 I see that @jhseu 's  718812c refactored Python module loading in https://github.com/tensorflow/tensorflow/blob/b10f50ff15944badb7262a207f6628dfa52d6a9d/tensorflow/python/pywrap_tensorflow.py

Stack trace
```
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "/home/yaroslav/.conda/envs/tf-mar4/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow_internal', [dirname(__file__)])
  File "/home/yaroslav/.conda/envs/tf-mar4/lib/python3.5/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yaroslav/.conda/envs/tf-mar4/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/yaroslav/.conda/envs/tf-mar4/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/yaroslav/.conda/envs/tf-mar4/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    import _pywrap_tensorflow_internal
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yaroslav/.conda/envs/tf-mar4/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/yaroslav/.conda/envs/tf-mar4/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 51, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/yaroslav/.conda/envs/tf-mar4/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/yaroslav/.conda/envs/tf-mar4/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow_internal', [dirname(__file__)])
  File "/home/yaroslav/.conda/envs/tf-mar4/lib/python3.5/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yaroslav/.conda/envs/tf-mar4/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/yaroslav/.conda/envs/tf-mar4/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/yaroslav/.conda/envs/tf-mar4/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    import _pywrap_tensorflow_internal
ImportError: No module named '_pywrap_tensorflow_internal'


Failed to load the native TensorFlow runtime.

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by yaroslavvb** [comment]
Same problem using today's head.

Looking at the failure, it happens in `pywrap_tensorflow_internal.py` trying to load `__pywrap_tensorflow_internal` module. I did a search and there's nothing called `_pywrap_tensorflow_internal` that was included in wheel installation


```
      try:
            fp, pathname, description = imp.find_module('_pywrap_tensorflow_internal', [dirname(__file__)])

```
This is the wheel that got built (Ubuntu 14.04, Python 3)
https://storage.cloud.google.com/tensorflow-community-wheels/mar5.xla.tensorflow-1.0.0-cp35-cp35m-linux_x86_64.whl

**Comment by jhseu** [comment]
I'm having trouble reproducing this issue. Your .whl is indeed missing _pywrap_tensorflow_internal.so, but it exists when I create it in a fresh Docker container:
```bash
$ unzip tensorflow-1.0.0-cp35-cp35m-linux_x86_64.whl
$ find . -name _pywrap_tensorflow_internal.so
./tensorflow-1.0.0.data/purelib/tensorflow/python/_pywrap_tensorflow_internal.so
```

Have you tried on a freshly cloned tensorflow? If you're reusing an existing tree, it's possible it's picking up older artifacts.

**Comment by jhseu** [comment]
Do you get this file after the build?
```bash
$ ls -l bazel-out/local-py3-opt/bin/tensorflow/python/_pywrap_tensorflow_internal.so
-r-xr-xr-x 1 user user 76380704 Mar  6 20:09 bazel-out/local-py3-opt/bin/tensorflow/python/_pywrap_tensorflow_internal.so
```

**Comment by jhseu** [comment]
Note: it gets copied for packaging here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/pip_package/build_pip_package.sh#L118

So a symlink should exist at `bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so` after build.

I verified that deleting that file still allows us to build the .whl package successfully since we don't do any explicit checks.

**Comment by yaroslavvb** [comment]
OK, looking closer at logs, it looks like compilation failed because of a syntax error. So the wheel was getting built with an incomplete file set, probably left over from previous build. 

The error is that one of the files has
`size_typ i = 0;`  which should be `size_type i = 0;`
😮 

Isn't this kind of thing supposed to get caught by continuous tests?

Someone else is trying to fix it in: https://github.com/tensorflow/tensorflow/pull/8039

**Comment by yaroslavvb** [comment]
I'll close this issue since there's already a PR in flight to fix it

**Comment by jhseu** [comment]
Yeah, I think the issue is that we disable XLA in our OSS tests since it's experimental.

Not sure people would want to add a separate run just for XLA.

**Comment by 345ishaan** [comment]
Hi,
I want to develop a sequence to sequence attention model using tensorflow. I am trying to install tensorflow from source. Hence following this tutorial https://www.tensorflow.org/tutorials/seq2seq which asks me to clone tensorflow from a git repo.

I am trying to build through bazel and then installing the wheel using the pip. But I get the same error as mentioned above. Please help me by pointing to a stable, I am working on Ubuntu 16.04

**Comment by mhamilton723** [comment]
I have the same problem ad @345ishaan

**Comment by jhseu** [comment]
Note: if you're getting this error, then you're ignoring an error that occurred during the build step. Scroll up and find the underlying error :)

**Comment by countzyx** [comment]
This 1.0.0 build was such a pain! After hours of working on it, I got something that works on MacOS.

1.  First I had to deal with a Mac-specific issue where a protection scheme, SIP, prevents you from defining DYLD_ anything in env, so it could not find libcudart.8.0.dylib. This dude blogged a workaround - [https://srikanthpagadala.github.io/notes/2016/11/07/enable-gpu-support-for-tensorflow-on-macos](https://srikanthpagadala.github.io/notes/2016/11/07/enable-gpu-support-for-tensorflow-on-macos)

2. Then I ran into an issue where it could not find another library, libcublas. Since I used Homebrew (as per all guidance everywhere) to get bazel, it got 0.4.4 which doesn't work with this source. Someone posted on this issue how to roll back to 0.4.3 - [https://github.com/tensorflow/tensorflow/issues/7227](https://github.com/tensorflow/tensorflow/issues/7227)

3. Finally, the problem you are all having here. After finally getting the build and installing the wheel in my conda env, I ran into an error trying to find pywrap_tensorflow_internal.so when I ran the interpreter and tried to import tensorflow. Turns out the wheel had one error while being assembled. I looked at the conda env site packages to see if the .so is actually there. It was, but it was named _pywrap_tensorflow_internal.so (notice the initial underscore). I removed the underscore by hand and it finally worked. :/

**Comment by jhseu** [comment]
I have a fix for #1 where we the path to CUDA to the rpath of the shared library on macOS. I'll ping on the change. No clue how moving the file is fixing it for #3. It's intentionally named with the underscore.

**Comment by robmsylvester** [comment]
make sure you aren't getting this error as a result of running python from the actual git directory where you downloaded tensorflow. 

if you're following the step-by-step install from the documentation page, and get to the final step where you verify the install, you start python from the terminal and run 'import tensorflow', and you would get this error. go to any other directory and you're fine.

**Comment by pedropgusmao** [comment]
It could be that you are calling import tensorflow from inside a directory that contains a tensorflow directory itself. Try to run python from a different directory.

**Comment by eliethesaiyan** [comment]
@robmsylvester Thank you very much for point this out...would you mind sharing what might be the probable cause for this

**Comment by AimainaHito** [comment]
@eliethesaiyan In my case it tried to load the tensorflow library from the local tensorflow folder in the build directory instead of the global one. That should be obvious from the stack trace though.

**Comment by barotdhrumil21** [comment]
@robmsylvester @AimainaHito I tried to moving to other directory and even tried to load from idle but it's still not working.

**Comment by nick-jonas** [comment]
I'm outside of the tensorflow repo, and I'm still getting this issue when doing ```import tensorflow``` in the python interpreter:

```ImportError: /usr/local/google/home/njonas/tensorflow/local/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: cuDevicePrimaryCtxRetain```

My CUDA paths are exported, and here are my system specs:

Ubuntu 14.04 x86-64
Intel Xeon CPU E5-2690 @ 2.60 GHz x 12
NVIDIA GM107GL Quadro K2200
NVIDIA GM200 GTX TITAN X

Python version 3.5.3
tensorflow_gpu-1.2.1-cp35-cp35m-manylinux1_x86_64.whl
Cuda compilation tools, release 8.0, V8.0.61

**Comment by yaroslavvb** [comment]
Perhaps wrong CUDA version?
The errors means dynamic linker found a reference to `cuDevicePrimaryCtxRetain` in the `.so` library, but this symbol was not present in any other library it loaded, which could happen if your cuda .so's are too old
