### PR TITLE
Add shape function SingleImageRandomDotStereograms

### LINKED ISSUE #15429: RuntimeError: No C++ shape function registered for standard op: SingleImageRandomDotStereograms
single_image_random_dot_stereograms (windows bug)
the function works fine on ubuntu 16.04 / tf 1.4.0 (CPU)

I know, that the support for unsupported libraries in tf.contrib on Windows is incomplete, and left up to the individual contributors. I found some sketchy solutions by editing gen_single_image_random_dot_stereograms_ops.py, but i could not figure it out correctly.

**Source code**
```
import tensorflow as tf
from tensorflow.contrib.image import single_image_random_dot_stereograms
img=[[1,2,3,3,2,1],
     [1,2,3,4,5,2],
     [1,2,3,4,5,3],
     [1,2,3,4,5,4],
     [6,5,4,4,5,5]]
session = tf.InteractiveSession()
sirds = single_image_random_dot_stereograms(
    img,
    convergence_dots_size=8,
    number_colors=256,normalize=True)
out = sirds.eval()
png = tf.image.encode_png(out).eval()
with open('picture_out.png', 'wb') as f:
  f.write(png)
```

**Error**
Windows 10 Pro, 1709
conda version : 4.3.30
python version: 3.6.3
tensorflow-gpu 1.4.0

```
File "C:\Users\###\Anaconda3\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 696, in _call_cpp_shape_fn_impl
    "No C++ shape function registered for standard op: %s" % op.type)
RuntimeError: No C++ shape function registered for standard op: SingleImageRandomDotStereograms
```

Windows 10 Pro, 1709
conda version : 4.3.30
python version: 3.5.4
tensorflow 1.3.0/tensorflow 1.2.0

`AttributeError: 'NoneType' object has no attribute 'single_image_random_dot_stereograms`

### PR DESCRIPTION
**Pull request by yongtang**
This fix tries to address the issue raised in #15429 where there is no shape function for SingleImageRandomDotStereograms.

This fix adds the shape function for `SingleImageRandomDotStereograms`.

NOTE: `SingleImageRandomDotStereograms` takes an attribute of `output_image_shape` which is in the format of `[X, Y, C]` (`[ImageX, ImageY, Channel]`. However, the actual
data output is in the format of `[ImageY, ImageX, Channel]` (`[h, w, c]`). So by default the output_image_shape has the value of [1024, 768, 1] but the output data will be [768, 1024, 1].
And if `[1200, 800, 1]` is used explicitly then the output data shape will be `[800, 1200, 1]`.

This fix does not change the behavior for now.

This fix fixes #15429.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by drpngx** [comment]
Jenkins, test this please.

File: tensorflow/contrib/image/ops/single_image_random_dot_stereograms_ops.cc [hunk 1]
```diff
@@ -37,6 +41,31 @@ REGISTER_OP("SingleImageRandomDotStereograms")
         "output_image_shape: shape = { dim {size:1024} dim {size: 768} dim "
         "{size: 1}}")
     .Attr("output_data_window: shape = { dim {size:1022} dim {size: 757}}")
+    .SetShapeFn([](InferenceContext* c) {
+      // Validate that the output_image_shape attr is correct.
+      // NOTE: The output_image_shape is [X, Y, C]
+      // while the output data is [Y, X, C] (or [H, W, C])
+      // so by default the output_image_shape has the value
+      // of [1024, 768, 1] but the output data will be [768, 1024, 1]
```
Comment (drpngx) [inline tensorflow/contrib/image/ops/single_image_random_dot_stereograms_ops.cc]: Please add punctuation as per style guide.

File: tensorflow/contrib/image/ops/single_image_random_dot_stereograms_ops.cc [hunk 2]
```diff
@@ -37,6 +41,31 @@ REGISTER_OP("SingleImageRandomDotStereograms")
...
+      TF_RETURN_IF_ERROR(
+          c->MakeShapeFromPartialTensorShape(shape, &output_image_shape));
+      DimensionHandle x_dim = c->Dim(output_image_shape, 0);
+      DimensionHandle y_dim = c->Dim(output_image_shape, 1);
+      DimensionHandle c_dim = c->Dim(output_image_shape, 2);
+
+      int colors;
+      TF_RETURN_IF_ERROR(c->GetAttr("number_colors", &colors));
+
+      std::vector<DimensionHandle> dims(3);
```
Comment (drpngx) [inline tensorflow/contrib/image/ops/single_image_random_dot_stereograms_ops.cc]: probably more readable as
`c->set_output(0, c->MakeShape({y_dim, x_dim, colors > 256? c->MakeDim(3) : c->MakeDim(1)}));`

File: tensorflow/contrib/image/python/kernel_tests/single_image_random_dot_stereograms_ops_test.py [hunk 3]
```diff
@@ -0,0 +1,87 @@
...
+    so by default the output_image_shape has the value
+    of [1024, 768, 1], but the output data will be [768, 1024, 1]
+    """
+    x_np = [[1, 2, 3, 3, 2, 1],
+            [1, 2, 3, 4, 5, 2],
+            [1, 2, 3, 4, 5, 3],
+            [1, 2, 3, 4, 5, 4],
+            [6, 5, 4, 4, 5, 5]]
+    x_tf = constant_op.constant(x_np)
+    # By default [1024, 768, 1] => [768, 1024, 1]
```
Comment (drpngx) [inline tensorflow/contrib/image/python/kernel_tests/single_image_random_dot_stereograms_ops_test.py]: Here and below, please add punctuation.

**Review by drpngx — CHANGES_REQUESTED** [review]

**Review by drpngx — APPROVED** [review]
Thanks for adding a test!
