### ISSUE TITLE
ABSL_HAVE_ADDRESS_SANITIZER use in Tensorflow headers breaks build for MSVC 16.11 with /fsanitize=address

### ISSUE THREAD

**Issue by libbooze** [tensorflow/tensorflow#51685]
**System information**
- TensorFlow installed from (source or binary): source, but does not really matter
- TensorFlow version (use command below): 2.5

**Describe the current behavior**
When compiling in MSVC with address sanitizer TF enables code guarded by ABSL_HAVE_ADDRESS_SANITIZER.
That guarded code (header includes, calls of functions) break the compile.

I would guess this happens since till recently only clang and gcc had sanitizers, and I presume they support all the functionality TF uses. 

**Describe the expected behavior**
Either ABSL_HAVE_ADDRESS_SANITIZER  should be fixed to be 1 only on gcc/clang or TF should use the ABSL_HAVE_ADDRESS_SANITIZER  only when gcc/clang are used. On MSVC this causes a ton of problems.
Alternatively ask MSFT if they plan to add all the headers soon, I doubt it, but if they do you can close as WONTFIX.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing): I would discuss this with Abseil team and decide to either fix a macro in Abseil, or define a TF_SOMETHING macro that logically maps to ABSL_HAVE_ADDRESS_SANITIZER==1  &&  compiler_is_not_msvc

**Standalone code to reproduce the issue**
Include any header that will transitively include headers that use ABSL_HAVE_ADDRESS_SANITIZER  and compile on MSVC 16.11 with /fsanitize=address
Example of problematic header:
cpu\include\absl\base\internal\dynamic_annotations.h

**Comment by DoDoENT** [comment]
This is not strictly related to TensforFlow - I get the same error when trying to use abseil directly in my project with ASan enabled on MSVC.

**Comment by DoDoENT** [comment]
I've also reported this issue to [Microsoft](https://developercommunity.visualstudio.com/t/ASan-API-headers-not-in-include-path-whe/1517192?space=62&q=sanitizer%2Fcommon_interface_defs.h&entry=myfeedback). Feel free to upvote the report.

**Comment by libbooze** [comment]
@DoDoENT Thank you very much for taking time to report this and make MS issue. 
Did you use the latest Abseil?
If so I can skip the request from @sushreebarsa  for testing 2.6 since if it is not fixed in latest Abseil it is for sure still broken in TF.

**Comment by DoDoENT** [comment]
I'm using 202103.24.2. However, after hardcoding the include directory path in my `CMakeLists.txt` to `C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\crt\src` just to test the build in case MSVC added that path correctly to default includes, but abseil still doesn't build. 

This time I get the following error:

```
absl/container/fixed_array.h(432): error C3646: '__attribute__': unknown override specifier
```

As far as I see, the line 432 of `fixed_array.h` is 

```
   private:
    ABSL_ADDRESS_SANITIZER_REDZONE(redzone_begin_);  // line 432
    alignas(StorageElement) char buff_[sizeof(StorageElement[inline_elements])];
    ABSL_ADDRESS_SANITIZER_REDZONE(redzone_end_);
```

and `ABSL_ADDRESS_SANITIZER_REDZONE` is defined as

```
#define ABSL_ADDRESS_SANITIZER_REDZONE(name) \
  struct {                                   \
    char x[8] __attribute__((aligned(8)));   \
  } name
```

in case when `ABSL_HAVE_ADDRESS_SANITIZER` is defined (i.e. when ASan is detected). I think this attribute should be set differently with MSVC - ideally with `alignas` specifier, which is compiler agnostic.

I believe this is an abseil bug that needs to be resolved.

**Comment by mihaimaruseac** [comment]
This is not related to TF, so I'd move we close this

**Comment by DoDoENT** [comment]
I agree. I reported that directly to [abseil](https://github.com/abseil/abseil-cpp/issues/1010).

**Comment by mihaimaruseac** [comment]
When ABSL releases a new stable version with this patched, we'll patch it into TF
