### ISSUE TITLE
Compile TensorFlow 1.0 on Windows 10 for Python 3.6 (Anaconda) cause compile issues

### ISSUE THREAD

**Issue by pavelbulanov** [tensorflow/tensorflow#7966]
As per agreement in #6999 [specific comment](https://github.com/tensorflow/tensorflow/issues/6999#issuecomment-280749568), I'm creating a new issue for compilation errors for TF 1.0 under Windows for Python 3.6

**Pre-requisites:**
Windows 10 v.14986
Python 3.6 64 bit (Anaconda 4.3)
git version 2.11.0.windows.1
Visual Studio Build Tools (called "Build Tools for Visual Studio 2017 RC" in the [download](https://www.visualstudio.com/downloads/#build-tools-for-visual-studio-2017-rc) section)
cmake-3.8.0-rc1 and swigwin-3.0.12 (just downloaded latest version at that moment)
TensorFlow 1.0.0 from source (master branch from github)

**Reproduction**. I followed [instruction](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cmake/README.md) for CMake just running two commands - CMake first and MSBuild second.

To compile, I made two changes in sources. I found them based on compilation errors.
One was adding `#include <intrin.h>` to `tensorflow\core\platform\windows\cpu_info.h` inside of `#ifndef` block because of the following error:
> error C3861: '__cpuidex': identifier not found 

I found [commit](https://github.com/tensorflow/tensorflow/commit/a672cb166dae93ae955c1d38f3de8903dd242373) introduced usage of `__cpuidex` function. Based on [this](https://msdn.microsoft.com/en-us/library/hskdteyh.aspx) MSDN link, I discovered that Header file `<intrin.h>` has to be included.  That's why I put it inside `cpu_info.h` (not sure if it's exactly perfect place).

**Second issue** was commenting out procedures `_mm256_extract_epi32` and `_mm256_insert_epi32` in `tensorflow\core\platform\windows\intrinsics_port.h` due to error

> error C2169: '_mm256_extract_epi32': intrinsic function, cannot be defined 

The second issue with `_mm256_extract_epi32` may be connected with the same reason, I don't know. 
In the meantime, `platform/windows/intrinsics_port.h` [references](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/windows/intrinsics_port.h#L22) `immintrin.h`, but I don't see it's actually included anywhere. I assume it may correlate with `instrih.h` inclusion (based on [this](https://msdn.microsoft.com/en-us/library/26td21ds.aspx) link). Meanwhile, `_mm256_extract_epi32 `can be found in `avxintrin.h` which may be is included by `immintrin.h`.

> // the following avx intrinsics are not defined on windows
> // in immintrin.h so we define them here.

After fixing those two issues, that, I was able to successfully run
> MSBuild /p:Configuration=Release tf_python_build_pip_package.vcxproj

Which gave me `tensorflow-1.0.0-cp36-cp36m-win_amd64.whl`, that I successfully installed into Python using `pip`. It seems to be working - I was able to run couple of jupyter notebooks, including udacity assignments.

BTW, compilation took about 2-3 hours on my week laptop (i5-4200U).

**Comment by gunan** [comment]
GPU compilation on windows does take a long time, due to Visual Studio not properly parallelizing the compilation when using an external compiler (nvcc).
Looks like you already have a solution to the reported issue. We would be happy to review and accept your solution to the repository. Would you like to create a Pull Request?

**Comment by pavelbulanov** [comment]
@gunan I created PR #8008, but I'm not totally sure about the fix. 
It allows me to successfully compile under my environment, but it seems it won't be generic.

The thing is that two functions from `intrinsics_port.h` (`_mm256_extract_epi32` and `_mm256_insert_epi32`) are declared in `immintrin.h` for VS2017 build tools, but I didn't found them in the same header file for VS2015 (VS14). There is no `#define` before these new declarations so no easy way to put a check in `intrinsics_port.h` to avoid double declaration.

**Comment by gunan** [comment]
CC @mrry @guschmue any ideas?

AFAIK immintrin.h is a header file for intel SIMD intrinsics.
Maybe the compilation issues are related to VS2017 as we are not seeing them in our builds that use vs2015?
The files you edited should be specific to windows. We should be able to test if your changes are OK on older versions of VS (2015 update 3 is the only one we actually test on).

**Comment by guschmue** [comment]
intrinsics_port.h is there because vs2015 does not implement all of them.
but vs2017 does have them. So maybe something like
#if _MSC_VER < 1910
in intrinsics_port.h will make both vs2015 and vs2017 work.

**Comment by guschmue** [comment]
btw, #8008 will pass CI for windows because CI does not build for /arch:avx2. 
If you'd turn on avx2 it would fail on vs2015.
But avx2 fails anyway since https://github.com/tensorflow/tensorflow/commit/ed6357cbd4f6e47ab87b219a0e0840739c92c970 which I was planning to fix (I only noticed because we build for avx2).

**Comment by pavelbulanov** [comment]
@guschmue I changed precompiler check to `#if _MSC_VER < 1910` and it expectedly works for VS2017 build tools.

Meanwhile, is it OK that inclusion of `immintrin.h` is implicit? It's only mentioned in `intrinsics_port.h`, but not included directly anywhere.
It seems inclusion of immintrin is passed by usage of external `highwayhash`. But these operations (`_mm256_extract_epi32 `and `_mm256_insert_epi32`) are used in `core/kernels/sparse_matmul_op.h`

**Comment by guschmue** [comment]
Might be better to use intrin.h, by don't think its critical.
The calls in sparse_matmul.h are not used in the default windows build: EIGEN_VECTORIZE_AVX is not set. I think if you'd compile with /arch:avx2 or so those become hot. But I know /arch:avx2 has some issue since a week ... will look at it soon.

**Comment by gunan** [comment]
I think this is resolved? Or are we still seeing this build failure with avx2?

**Comment by guschmue** [comment]
yes, avx2 build are still failing - looking at it.

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
