### ISSUE TITLE
tf.repeat AttributeError: module 'tensorflow' has no attribute 'repeat' on versions 2.0.0 and 2.0.1

### ISSUE THREAD

**Issue by miguelgfierro** [tensorflow/tensorflow#38839]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Tried on Windows 10 and on Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): tried 2.0.0 and 2.0.1
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
```
>>> tf.repeat(['a', 'b', 'c'], repeats=[3, 0, 2], axis=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'repeat'
```
**Describe the expected behavior**
I found that this works on 2.1.0 and 1.15.2

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by oke-aditya** [comment]
It works in tf 2.2 as well. Also as you mentioned in tf 2.1 and 1.15 as well. 
It does not work in 2.0.1. I checked it. Here is gist to reproduce error. [error_test](https://colab.research.google.com/gist/oke-aditya/d7d29ab4362dbb67fff7149bcc795390/test2.ipynb)

**Comment by Saduf2019** [comment]
@miguelgfierro
we ran your code over nightly and it does not have any errors,please find the[ gist here](https://colab.sandbox.google.com/gist/Saduf2019/a54afe6ca3b701d71af0432083c642df/38839.ipynb)
is there any particular reason to run on 2.0.1, can you upgrade to later versions.

**Comment by miguelgfierro** [comment]
> is there any particular reason to run on 2.0.1, can you upgrade to later versions.

I can definitely use other versions, up to you :-0. Just FYI, at the moment, version 2.0.1 and 2.0.0 don't work. Furthermore, 2.1.0 has `repeat` and work in Linux, however, if I try to install 2.1.0 on my local windows laptop, it fails. 

The summary is that, given that I only use stable releases, from the recent versions I can only use 1.15.2. I'll do that for the time being.
