### ISSUE TITLE
[MLIR] compile error

### ISSUE THREAD

**Issue by zzpmiracle** [tensorflow/tensorflow#46630]
when I build the latest tensorflow mlir, commit id c30ad4ae0ca1a6240ec8619d5027a272394726a5, 
with 
`bazel build --override_repository=llvm-project=$LLVM_SRC -c opt tensorflow/compiler/mlir:tf-opt` or even 
`bazel build -c opt tensorflow/compiler/mlir:tf-opt`
I always get the message as below :
`tensorflow/tensorflow/compiler/mlir/xla/BUILD:176:11: C++ compilation of rule '//tensorflow/compiler/mlir/xla:mhlo_to_lhlo_with_xla' failed (Exit 1): gcc failed: error executing command /path/to/gcc650/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' ... (remaining 320 argument(s) skipped)                                                                                                                                                                                                                                    tensorflow/compiler/mlir/xla/transforms/mhlo_to_lhlo_with_xla.cc: In instantiation of 'mlir::LhloDialectEmitter::EmitGemm(const xla::HloCustomCallInstruction*)::<lambda(auto:10)> [with auto:10 = mlir::lmhlo_gpu::GEMMOp]':         tensorflow/compiler/mlir/xla/transforms/mhlo_to_lhlo_with_xla.cc:670:38:   required from here                                                                                                                                         tensorflow/compiler/mlir/xla/transforms/mhlo_to_lhlo_with_xla.cc:651:32: error: cannot call member function 'mlir::DenseIntElementsAttr mlir::LhloDialectEmitter::GetI64DenseElementsAttr(const T&) [with T = google::protobuf::RepeatedField<long int>]' without object                                                                                                                                                                                                             GetI64DenseElementsAttr(hlo_dims.lhs_batch_dimensions()),                                                                                                                                                                             ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                     tensorflow/compiler/mlir/xla/transforms/mhlo_to_lhlo_with_xla.cc:652:32: error: cannot call member function 'mlir::DenseIntElementsAttr mlir::LhloDialectEmitter::GetI64DenseElementsAttr(const T&) [with T = google::protobuf::RepeatedField<long int>]' without object                                                                                                                                                                                                             GetI64DenseElementsAttr(hlo_dims.rhs_batch_dimensions()),                                                                                                                                                                             ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                     tensorflow/compiler/mlir/xla/transforms/mhlo_to_lhlo_with_xla.cc:653:32: error: cannot call member function 'mlir::DenseIntElementsAttr mlir::LhloDialectEmitter::GetI64DenseElementsAttr(const T&) [with T = google::protobuf::RepeatedField<long int>]' without object                                                                                                                                                                                                             GetI64DenseElementsAttr(hlo_dims.lhs_contracting_dimensions()),                                                                                                                                                                       ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                               tensorflow/compiler/mlir/xla/transforms/mhlo_to_lhlo_with_xla.cc:654:32: error: cannot call member function 'mlir::DenseIntElementsAttr mlir::LhloDialectEmitter::GetI64DenseElementsAttr(const T&) [with T = google::protobuf::RepeatedField<long int>]' without object                                                                                                                                                                                                             GetI64DenseElementsAttr(hlo_dims.rhs_contracting_dimensions()),                                                                                                                                                                       ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                               tensorflow/compiler/mlir/xla/transforms/mhlo_to_lhlo_with_xla.cc: In instantiation of 'mlir::LhloDialectEmitter::EmitGemm(const xla::HloCustomCallInstruction*)::<lambda(auto:10)> [with auto:10 = mlir::lmhlo_gpu::GEMM_BiasOp]':    tensorflow/compiler/mlir/xla/transforms/mhlo_to_lhlo_with_xla.cc:678:43:   required from here                                                                                                                                         tensorflow/compiler/mlir/xla/transforms/mhlo_to_lhlo_with_xla.cc:651:32: error: cannot call member function 'mlir::DenseIntElementsAttr mlir::LhloDialectEmitter::GetI64DenseElementsAttr(const T&) [with T = google::protobuf::RepeatedField<long int>]' without object                                                                                                                                                                                                             GetI64DenseElementsAttr(hlo_dims.lhs_batch_dimensions()),                                                                                                                                                                             ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                     tensorflow/compiler/mlir/xla/transforms/mhlo_to_lhlo_with_xla.cc:652:32: error: cannot call member function 'mlir::DenseIntElementsAttr mlir::LhloDialectEmitter::GetI64DenseElementsAttr(const T&) [with T = google::protobuf::RepeatedField<long int>]' without object                                                                                                                                                                                                             GetI64DenseElementsAttr(hlo_dims.rhs_batch_dimensions()),                                                                                                                                                                             ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                     tensorflow/compiler/mlir/xla/transforms/mhlo_to_lhlo_with_xla.cc:653:32: error: cannot call member function 'mlir::DenseIntElementsAttr mlir::LhloDialectEmitter::GetI64DenseElementsAttr(const T&) [with T = google::protobuf::RepeatedField<long int>]' without object                                                                                                                                                                                                             GetI64DenseElementsAttr(hlo_dims.lhs_contracting_dimensions()),`

I have remove all the unrelated enviroment variables in the bash, but it still occurs. I have no idea, could anyone give some suggestions?

**System information**
- OS Platform and Distribution : CentOS Linux release 7.8.2003
- GCC/Compiler version : 6.5.0
- CUDA/cuDNN version: V10.0.130

**Comment by hunbssfy** [comment]
@zzpmiracle Hey have you solved this problem? I got the same error...

**Comment by njzjz** [comment]
I got the same error - have you resolved it? Related codes were introduced in bea9ecb9aad42dde0816a6e451320fdf5601f0a0, but I have no idea what's the problem.

**Comment by njzjz** [comment]
Finally, I turned off XLA to get a successful build...
