### ISSUE TITLE
Has this issue been solved for all containers - ImportError: cannot import name audio_ops

### ISSUE THREAD

**Issue by serendipity24** [tensorflow/tensorflow#13031]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: I am running the tutorial "audio recognition network"
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 14.04
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**:('v1.0.0-rc2-15-g47bba63-dirty', '1.0.0')
- **Python version**: 2.7.6
- **Bazel version (if compiling from source)**:NA
- **CUDA/cuDNN version**:NA
- **GPU model and memory**:NA
- **Exact command to reproduce**: python tensorflow/examples/speech_commands/train.py

### Describe the problem
I pip-installed tensorflow using virtualenv. Then I run -  

python tensorflow/examples/speech_commands/train.py       for which the following error message appears: 

  Traceback (most recent call last):
  File "/home/cogknit/tensorflow/tensorflow/examples/speech_commands/train.py", line 79, in <module>
    import input_data
  File "/home/cogknit/tensorflow/tensorflow/examples/speech_commands/input_data.py", line 35, in <module>
    from tensorflow.contrib.framework.python.ops import audio_ops as contrib_audio
ImportError: cannot import name audio_ops

In stack overflow, I came across the same issue only with anaconda install in the following link -
https://stackoverflow.com/questions/45952387/anaconda-install-of-tensorflow-missing-audio-ops-from-contrib-framework 
There, the answer indicated that the "audio_ops.py" file is missing from the framework and hasn't been released yet .This indication seems to be validated by a developer in the following link and recently an update seems to have been made/released per the same link  : https://github.com/tensorflow/tensorflow/issues/11339

My question in particular is does the release solve the error in virtualenv installation too? Or hasn't it been solved at all? Is it better to move to a docker installation?Are there any alternatives/commands that   I can use to circumvent this error?

#12722  dealt with the same error but the solution seems to have worked only for tensorflow built from source. Is there anything that I should check again?

Thank you,

**Comment by reedwm** [comment]
You are using TensorFlow 1.0, but I believe you need the master branch, which requires compiling from source.

@petewarden can you confirm this? If it doesn't work with 1.3, we should probably document that in the tutorial.

**Comment by chuan9** [comment]
I use python3.6.2 to install tensowflow1.3 on win10, the issue can also be reproduced. and there has no file name audio_ops.py in the folder "Python\Python36\Lib\site-packages\tensorflow\python\ops" which is the tensorflow's location.
Reproduce steps:
command: python .\tensorflow\examples\speech_commands\train.py
The error is as bellows:
Traceback (most recent call last):
File ".\tensorflow\examples\speech_commands\train.py", line 80, in <module>
import input_dataFile "C:\Users\**\Desktop\tensorflow\tensorflow\tensorflow\examples\speech_commands\input_data.py", line 35, in <module>
from tensorflow.contrib.framework.python.ops import audio_ops as contrib_audio
ImportError: cannot import name 'audio_ops'

**Comment by TongShanHui** [comment]
I have to admit, I am getting the same error, using python 3.5, Tensorflow 1.3, on Debian 9
(tensorflow) charles@Kong-Zi:~$ python tensorflow/examples/speech_commands/train.py
Traceback (most recent call last):
  File "tensorflow/examples/speech_commands/train.py", line 80, in <module>
    import input_data
  File "/home/charles/tensorflow/examples/speech_commands/input_data.py", line 35, in <module>
    from tensorflow.contrib.framework.python.ops import audio_ops as contrib_audio
ImportError: cannot import name 'audio_ops'
(tensorflow) charles@Kong-Zi:~$ python3 tensorflow/examples/speech_commands/train.py
Traceback (most recent call last):
  File "tensorflow/examples/speech_commands/train.py", line 80, in <module>
    import input_data
  File "/home/charles/tensorflow/examples/speech_commands/input_data.py", line 35, in <module>
    from tensorflow.contrib.framework.python.ops import audio_ops as contrib_audio
ImportError: cannot import name 'audio_ops'

**Comment by tenapril** [comment]
I have the same error using Windows 10, Python 3.5, tensorflow 1.3

C:\tensorflow-master>python tensorflow/examples/speech_commands/train.py
Traceback (most recent call last):
  File "tensorflow/examples/speech_commands/train.py", line 80, in <module>
    import input_data
  File "C:\tensorflow-master\tensorflow\examples\speech_commands\input_data.py", line 35, in <module>
    from tensorflow.contrib.framework.python.ops import audio_ops as contrib_audio
ImportError: cannot import name 'audio_ops'

**Comment by daemon** [comment]
audio_ops is available in their docker builds. This is somewhat along the lines of what I did:
1. `docker pull tensorflow/tensorflow:nightly-gpu-py3`
2. `nvidia-docker run -it -p 8888:8888 tensorflow/tensorflow:nightly-gpu-py3`
3. `docker exec -it jolly_lamport bash` (assuming Linux)
4. If you want to run the speech command example, it isn't Python 3 compatible. You'll need to fix the errors manually. I believe it's just like 4 lines of changes...

**Comment by serendipity24** [comment]
@everybody, along the lines of suggestions by @reedwm ,the following steps seems to have solved the issue : 
  1. Install anaconda for python
  2. Compile tensorflow from the source 

A few errors crop up during training as @daemon mentioned above due to incompatibility of train.py with Python 3. It has to do with the usage of map and xrange in particular.(while calculating len, len(list( )) has to be used and xrange has to be replaced with range)  

Thank you @reedwm for your help earlier.

**Comment by daemon** [comment]
Yep, https://github.com/tensorflow/tensorflow/pull/13111 should fix it.

**Comment by adityakusupati** [comment]
Hi all,

The issue of audio_ops is not yet resolved even for python2.7. It throws the same error as mentioned in the issue that started the thread.

Please resolve it at the earliest.

**Comment by NikolayStarikov** [comment]
Hi guys,

the solution is to install:
pip install tf-nightly

prior to 
python train.py

**Comment by adityakusupati** [comment]
Hi @NikolayStarikov ,

I have original tf installed. I installed tf-nightly over that and still, the problem persists.

**Comment by vclteam** [comment]
problem still there.
even on google cloud

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by jayeshrane2107** [comment]
used GCP datalab - python 2&3
audio_ops is not yet resolved.

**Comment by reedwm** [comment]
According to #14004, this requires a recently nightly build from the last month or so. The issue is not yet fixed with TensorFlow 1.4, but will be with Tensorflow 1.5 once it comes out.

Closing this since the issue seems to be resolved in nightly.

**Comment by KyrieHee** [comment]
can slove it by using 

> sudo pip3 install tf-nightly -i https://pypi.tuna.tsinghua.edu.cn/simple/
