### ISSUE TITLE
V1.3.1 undefined reference to `clock_gettime' Error

### ISSUE THREAD

**Issue by channingxiao** [tensorflow/tensorflow#13413]
Please go to Stack Overflow for help and support:

https://stackoverflow.com/questions/tagged/tensorflow

If you open a GitHub issue, here is our policy:

1. It must be a bug or a feature request.
2. The form below must be filled out.
3. It shouldn't be a TensorBoard issue. Those go [here](https://github.com/tensorflow/tensorboard/issues).

**Here's why we have that policy**: TensorFlow developers respond to issues. We want to focus on work that benefits the whole community, e.g., fixing bugs and adding features. Support only helps individuals. GitHub also notifies thousands of people when issues are filed. We want them to see you communicating an interesting problem, rather than being redirected to Stack Overflow.

------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
ReaHat 6.5 with self compiled gcc 4.8.2 installed locally
- **TensorFlow installed from (source or binary)**:
Compile from source
- **TensorFlow version (use command below)**:
- **Python version**: 
2.7.14 compiled from source
- **Bazel version (if compiling from source)**:
5.4.0 Compiled from source
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:
bazel build //tensorflow/examples/label_image:label_image
You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

I working on Redhat 6.5, with gcc 4.8.2 compiled from source and installed locally, binutiles like ld, as were not updated, glic was 2.12.

I managed to compile tensorflow 1.3.1 shared C++ libs libtensorflow_cc.so, but when Iinking to my projects, it encounted with "undefined reference to `clock_gettime' error. This error can also be reproduced by compiling label image examples with command 
``` 
bazel build //tensorflow/examples/label_image:label_image
``` 
Here are the error details:

/home/xxxxxxx/opensource/tensorflow/tensorflow/tensorflow/examples/label_image/BUILD:10:1: Linking of rule '//tensorflow/examples/label_image:label_image' failed (Exit 1).
bazel-out/local-opt/bin/tensorflow/core/kernels/libattention_ops.lo(attention_ops.o): In function `void Eigen::(anonymous namespace)::GlimpseExtractionOp<long>::eval<Eigen::TensorLayoutSwapOp<Eigen::TensorMap<Eigen::Tensor<float const, 4, 1, long>, 16, Eigen::MakePointer> const>, Eigen::TensorMap<Eigen::Tensor<float, 4, 0, long>, 0, Eigen::MakePointer>, Eigen::ThreadPoolDevice>(Eigen::TensorLayoutSwapOp<Eigen::TensorMap<Eigen::Tensor<float const, 4, 1, long>, 16, Eigen::MakePointer> const> const&, Eigen::TensorMap<Eigen::Tensor<float, 4, 0, long>, 0, Eigen::MakePointer>&, Eigen::ThreadPoolDevice const&) const':
attention_ops.cc:(.text.unlikely._ZNK5Eigen12_GLOBAL__N_119GlimpseExtractionOpIlE4evalINS_18TensorLayoutSwapOpIKNS_9TensorMapINS_6TensorIKfLi4ELi1ElEELi16ENS_11MakePointerEEEEENS5_INS6_IfLi4ELi0ElEELi0ES9_EENS_16ThreadPoolDeviceEEEvRKT_RT0_RKT1_+0xbb): undefined reference to `clock_gettime'
attention_ops.cc:(.text.unlikely._ZNK5Eigen12_GLOBAL__N_119GlimpseExtractionOpIlE4evalINS_18TensorLayoutSwapOpIKNS_9TensorMapINS_6TensorIKfLi4ELi1ElEELi16ENS_11MakePointerEEEEENS5_INS6_IfLi4ELi0ElEELi0ES9_EENS_16ThreadPoolDeviceEEEvRKT_RT0_RKT1_+0xdf): undefined reference to `clock_gettime'
collect2: error: ld returned 1 exit status
Target //tensorflow/examples/label_image:label_image failed to build
Use --verbose_failures to see the command lines of failed build steps.

I compiled python lib on the exactly the same environment. I had this error when running " import tensorflow". The error was fixed by modifying  "return []" to 'return ["-lrt"] ' in tensorflow/tensorflow.bzl line 975.

I tried the same trick for label_image example, but it didn't work out.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by cy89** [comment]
@javiribera please take a look.

**Comment by galv** [comment]
@channingxiao I encountered the same issue on RHEL6 in tensorflow 1.3.1. You need to link explicitly the librt library in RHEL6, since it uses glibc 2.12, while Google apparently uses a glibc newer than glibc 2.17, which changed the location of the time_* functions from librt to glibc itself. See [here](https://blog.flameeyes.eu/2012/12/glibc-2-17-what-s-going-to-be-a-trouble/) for more details.

The work-around is to change:

```
        "//conditions:default": [
            "-z defs",
            "-s",
            "-Wl,--version-script",  #  This line must be directly followed by LINKER_VERSION_SCRIPT
            LINKER_VERSION_SCRIPT,
        ],
```

to

```
        "//conditions:default": [
            "-lrt",
            "-z defs",
            "-s",
            "-Wl,--version-script",  #  This line must be directly followed by LINKER_VERSION_SCRIPT
            LINKER_VERSION_SCRIPT,
        ],
```

in tensorflow/java/BUILD.

Let me know if it works for you.

I'm happy to make a PR like #10717 (which fixed the same problem for the C++ build on RHEL6) to fix this problem.

**Comment by wangyum** [comment]
Try to build  tensorflow add `-linkopt='-lrt'`:
```
bazel build  --linkopt='-lrt' -c opt //tensorflow/tools/pip_package:build_pip_package
```

https://github.com/wangyum/Anaconda/blob/master/doc/installing-tensorflow-from-sources.md#package-tensorflow

**Comment by danxiangjie** [comment]
@wangyum，that's work ,thank you

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by asimshankar** [comment]
Thanks @galv @wangyum 
Closing this out. If someone would like to make a PR, feel free to send one.
Thanks!
