### ISSUE TITLE
Tensorflow 1.14.0 can not be built from source on Nvidia Jetson

### ISSUE THREAD

**Issue by doruksonmez** [tensorflow/tensorflow#35582]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: L4T 32.3.1 Ubuntu 18.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: 1.14.0
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: 0.24.1
- **GCC/Compiler version (if compiling from source)**: GCC 7.4
- **CUDA/cuDNN version**: 10.0.326 / 7.6.3
- **GPU model and memory**: Tegra Xavier / 16 GB
- **Exact command to reproduce**: 
```
export TMP=/tmp
PYTHON_BIN_PATH=$(which python3) \
PYTHON_LIB_PATH=$(python3 -c 'import site; print(site.getsitepackages()[0])') \
TF_CUDA_COMPUTE_CAPABILITIES=${cuda_compute} \
TF_CUDA_VERSION=10.0 \
TF_CUDA_CLANG=0 \
TF_CUDNN_VERSION=7 \
TF_TENSORRT_VERSION=${trt_version} \
CUDA_TOOLKIT_PATH=/usr/local/cuda \
CUDNN_INSTALL_PATH=/usr/lib/aarch64-linux-gnu \
TENSORRT_INSTALL_PATH=/usr/lib/aarch64-linux-gnu \
TF_NEED_IGNITE=0 \
TF_ENABLE_XLA=0 \
TF_NEED_OPENCL_SYCL=0 \
TF_NEED_COMPUTECPP=0 \
TF_NEED_ROCM=0 \
TF_NEED_CUDA=1 \
TF_NEED_TENSORRT=1 \
TF_NEED_OPENCL=0 \
TF_NEED_MPI=0 \
GCC_HOST_COMPILER_PATH=$(which gcc) \
CC_OPT_FLAGS="-march=native" \
TF_SET_ANDROID_WORKSPACE=0 \
    ./configure
```
```
bazel build --config=opt \
	    --config=cuda \
	    --local_resources=${local_resources} \
            //tensorflow/tools/pip_package:build_pip_package
```

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.
Hi, I am currently trying to build tensorflow 1.14.0 on Nvidia Jetson platform for TensorRT 6.0.1. But it is too painful to do so because it keep throwing errors and fails. I have applied some patches to the source code as described in below links:

- https://github.com/tensorflow/tensorflow/issues/19956#issuecomment-397212193
- https://github.com/tensorflow/tensorflow/issues/28277#issuecomment-517469318
- https://github.com/tensorflow/tensorflow/issues/32925#issuecomment-537593098

However, after all of the above patches, I still get the following errors shown on the logs section below. It is not the full log but if it is required, I can provide the full log too. Thanks in advance.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

```
In file included from ./tensorflow/compiler/tf2tensorrt/utils/trt_allocator.h:25:0,
                 from ./tensorflow/compiler/tf2tensorrt/convert/convert_nodes.h:26,
                 from tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc:16:
bazel-out/host/bin/external/local_config_tensorrt/_virtual_includes/tensorrt_headers/third_party/tensorrt/NvInfer.h:5611:33: note: declared here
     TRT_DEPRECATED virtual void setInt8Calibrator(IInt8Calibrator* calibrator) TRTNOEXCEPT = 0;
                                 ^~~~~~~~~~~~~~~~~
tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc:4939:77: warning: 'virtual nvinfer1::INetworkDefinition* nvinfer1::IBuilder::createNetwork()' is deprecated [-Wdeprecated-declarations]
       TrtUniquePtrType<nvinfer1::INetworkDefinition>(builder->createNetwork());
                                                                             ^
In file included from ./tensorflow/compiler/tf2tensorrt/utils/trt_allocator.h:25:0,
                 from ./tensorflow/compiler/tf2tensorrt/convert/convert_nodes.h:26,
                 from tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc:16:
bazel-out/host/bin/external/local_config_tensorrt/_virtual_includes/tensorrt_headers/third_party/tensorrt/NvInfer.h:5431:58: note: declared here
     TRT_DEPRECATED virtual nvinfer1::INetworkDefinition* createNetwork() TRTNOEXCEPT = 0;
                                                          ^~~~~~~~~~~~~
tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc:5011:62: warning: 'virtual nvinfer1::ICudaEngine* nvinfer1::IBuilder::buildCudaEngine(nvinfer1::INetworkDefinition&)' is deprecated [-Wdeprecated-declarations]
   engine->reset(builder->buildCudaEngine(*converter.network()));
                                                              ^
In file included from ./tensorflow/compiler/tf2tensorrt/utils/trt_allocator.h:25:0,
                 from ./tensorflow/compiler/tf2tensorrt/convert/convert_nodes.h:26,
                 from tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc:16:
bazel-out/host/bin/external/local_config_tensorrt/_virtual_includes/tensorrt_headers/third_party/tensorrt/NvInfer.h:5566:51: note: declared here
     TRT_DEPRECATED virtual nvinfer1::ICudaEngine* buildCudaEngine(
                                                   ^~~~~~~~~~~~~~~
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 6315.216s, Critical Path: 450.27s
INFO: 5761 processes: 5761 local.
FAILED: Build did NOT complete successfully
```

**Comment by andreyhristov** [comment]
Confirming that. Cannot build TF 1.14.0 on aarch64 when using nvcr.io/nvidia/l4t-base:r32.3.1 as base container and adding TRT 6.0.1

**Comment by ymodak** [comment]
Does switching to TF 1.15 help to solve this problem?

**Comment by doruksonmez** [comment]
@ymodak I didn't try to build 1.15 from source but I have tried to build TF 2.0 on Jetson and it was successful. Nvidia provides official TF 1.15 wheel for Jetson so I didn't need to build it myself.

**Comment by andreyhristov** [comment]
Yes, 1.15 builds fine with Bazel 0.24.1 and JetPack 4.3 ( I am building it in a container )

**Comment by andreyhristov** [comment]
1.14 fails (after patching) with :
tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc: At global scope:
tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc:797:8: error: 'bool tensorflow::tensorrt::convert::TRT_TensorOrWeights::SimpleITensor::isShape() const' marked 'override', but does not override
   bool isShape() const override { return false; }
        ^~~~~~~
tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc: In constructor 'tensorflow::tensorrt::convert::TRT_TensorOrWeights::TRT_TensorOrWeights(nvinfer1::DataType, const nvinfer1::Dims&, int)':
tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc:815:60: error: invalid new-expression of abstract class type 'tensorflow::tensorrt::convert::TRT_TensorOrWeights::SimpleITensor'
     : simple_itensor_(new SimpleITensor(trt_dtype, trt_dims)),

Here  is the patch:
```
--- tensorflow/BUILD       2019-02-25 20:37:04.000000000 +0000                                                                                                                                                                                
+++ tensorflow/BUILD       2019-04-04 16:45:53.441354395 +0000                                                                                                                                                                                
@@ -511,6 +511,9 @@                                                                                                                                                                                                                           
         "//tensorflow/cc:scope",
         "//tensorflow/cc/profiler",
         "//tensorflow/core:tensorflow",
+        "//tensorflow/compiler/tf2tensorrt:trt_conversion",
+        "//tensorflow/compiler/tf2tensorrt:trt_op_kernels",
+        "//tensorflow/compiler/tf2tensorrt:trt_engine_op_op_lib",
     ] + if_ngraph(["@ngraph_tf//:ngraph_tf"]),
 )
 
--- third_party/toolchains/cpus/arm/BUILD~      2019-06-19 00:48:23.000000000 +0200
+++ third_party/toolchains/cpus/arm/BUILD       2019-09-30 14:28:29.124554000 +0200
@@ -10,6 +10,7 @@
         "armeabi|compiler": ":cc-compiler-armeabi",
         "local|compiler": ":cc-compiler-local",
         "armeabi": ":cc-compiler-armeabi",
+        "aarch64": ":cc-compiler-local",
         "k8": ":cc-compiler-local",
         "piii": ":cc-compiler-local",
         "arm": ":cc-compiler-local",
--- third_party/gpus/crosstool/BUILD.tpl~       2019-06-19 00:48:23.000000000 +0200
+++ third_party/gpus/crosstool/BUILD.tpl        2019-09-30 14:28:59.516554000 +0200
@@ -29,6 +29,7 @@
         "x64_windows|msvc-cl": ":cc-compiler-windows",
         "x64_windows": ":cc-compiler-windows",
         "arm": ":cc-compiler-local",
+        "aarch64": ":cc-compiler-local",
         "k8": ":cc-compiler-local",
         "piii": ":cc-compiler-local",
         "ppc": ":cc-compiler-local",
commit 851b3f5a467bdd1f41c32a6b346940980530898d
Author: A. Unique TensorFlower <gardener@tensorflow.org>
Date:   Wed Jun 26 07:11:29 2019 -0700

    Disable dot-product depthwise conv when not compiling for Android with Clang.
    
    PiperOrigin-RevId: 255181633

diff --git a/tensorflow/lite/kernels/internal/depthwiseconv_quantized_test.cc b/tensorflow/lite/kernels/internal/depthwiseconv_quantized_test.cc
index 8baf2c7253..fd5b89eaf7 100644
--- tensorflow/lite/kernels/internal/depthwiseconv_quantized_test.cc
+++ tensorflow/lite/kernels/internal/depthwiseconv_quantized_test.cc
@@ -170,7 +170,8 @@ inline void DispatchDepthwiseConv(
       // This is compiled-in even if dot-product instructions are unavailable.
       // However, tests should skip dot-product testing in that case and not
       // call this code.
-#if defined(__aarch64__) && !defined(GOOGLE_L4T)
+#if defined(__aarch64__) && !defined(GOOGLE_L4T) && defined(__ANDROID__) && \
+    defined(__clang__)
       DotProduct3x3KernelType kernel_type =
           optimized_ops::depthwise_conv::CategorizeDotProductKernel(
               input_shape, filter_shape, params);
@@ -683,7 +684,8 @@ void TestOneDepthwiseConv3x3Filter(
 }
 
 void TestOneNeonDot3x3(const TestParam& test_param) {
-#if defined(__aarch64__) && !defined(GOOGLE_L4T)
+#if defined(__aarch64__) && !defined(GOOGLE_L4T) && defined(__ANDROID__) && \
+    defined(__clang__)
   CpuBackendContext backend_context;
   ruy::Context* ruy_context = backend_context.ruy_context();
   const auto ruy_paths = ruy_context != nullptr
@@ -854,7 +856,8 @@ INSTANTIATE_TEST_SUITE_P(
     TestParam::TestNameSuffix);
 #endif
 
-#if defined(__aarch64__) && !defined(GOOGLE_L4T)
+#if defined(__aarch64__) && !defined(GOOGLE_L4T) && defined(__ANDROID__) && \
+    defined(__clang__)
 INSTANTIATE_TEST_SUITE_P(
     NeonAsm, DepthwiseConvTest,
     testing::Combine(
diff --git a/tensorflow/lite/kernels/internal/optimized/depthwiseconv_uint8.h b/tensorflow/lite/kernels/internal/optimized/depthwiseconv_uint8.h
index 23940e3c33..8b57c3ed65 100644
--- tensorflow/lite/kernels/internal/optimized/depthwiseconv_uint8.h
+++ tensorflow/lite/kernels/internal/optimized/depthwiseconv_uint8.h
@@ -2006,7 +2006,8 @@ inline void DepthwiseConvWithRounding(
 
 // Enable for arm64 except for the Nvidia Linux 4 Tegra (L4T) running on
 // Jetson TX-2. This compiler does not support the offsetof() macro.
-#if defined(__aarch64__) && !defined(GOOGLE_L4T)
+#if defined(__aarch64__) && !defined(GOOGLE_L4T) && defined(__ANDROID__) && \
+    defined(__clang__)
   // Dispatch to dot-product 3x3 kernels when supported.
   if (cpu_flags.neon_dotprod) {
     using optimized_ops::depthwise_conv::DotProduct3x3KernelType;
@@ -2025,6 +2026,8 @@ inline void DepthwiseConvWithRounding(
     }
   }
 
+#elif defined(__aarch64__) && !defined(GOOGLE_L4T)
+
   // Dispatch to non-dot-product 3x3 kernels when supported.
 
   const int stride_width = params.stride_width;
diff --git a/tensorflow/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h b/tensorflow/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h
index cf2bcb2279..9f827e988a 100644
--- tensorflow/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h
+++ tensorflow/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h
@@ -5786,7 +5786,8 @@ struct WorkspacePrefetchWrite<
 
 #endif  // __aarch64__
 
-#if defined(__aarch64__) && !defined(GOOGLE_L4T)
+#if defined(__aarch64__) && !defined(GOOGLE_L4T) && defined(__ANDROID__) && \
+    defined(__clang__)
 // Dot product ops hard-coded
 
 template <>

--- third_party/tensorrt/tensorrt_configure.bzl~        2019-06-18 22:48:23.000000000 +0000
+++ third_party/tensorrt/tensorrt_configure.bzl 2020-01-05 16:32:05.452000000 +0000
@@ -27,8 +27,8 @@
     "NvUtils.h",
     "NvInferPlugin.h",
     "NvInferVersion.h",
-    "NvInferRTSafe.h",
-    "NvInferRTExt.h",
+    "NvInferRuntime.h",
+    "NvInferRuntimeCommon.h",
     "NvInferPluginUtils.h",
 ]
```

**Comment by edf-spire** [comment]
Thank you for this, it was very helpful.

I'm running TX2 with JetPack 4.3 (comes with TensorRT 6.0.1). I tried to compile Tensorflow 1.14.1. This is the patch I had to apply (one difference with the previous one):

```
diff --git tensorflow/BUILD tensorflow/BUILD
index 1e0cc9207b..9a90069ddf 100644
--- tensorflow/BUILD
+++ tensorflow/BUILD
@@ -594,6 +594,9 @@ tf_cc_shared_object(
         "//tensorflow/cc:scope",
         "//tensorflow/cc/profiler",
         "//tensorflow/core:tensorflow",
+        "//tensorflow/compiler/tf2tensorrt:trt_conversion",
+        "//tensorflow/compiler/tf2tensorrt:trt_op_kernels",
+        "//tensorflow/compiler/tf2tensorrt:trt_engine_op_op_lib",
     ] + if_ngraph(["@ngraph_tf//:ngraph_tf"]),
 )
 
diff --git tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc
index 306341301b..dfd65f6a3c 100644
--- tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc
+++ tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc
@@ -794,7 +794,9 @@ class TRT_TensorOrWeights::SimpleITensor : public nvinfer1::ITensor {
 
   nvinfer1::TensorFormats getAllowedFormats() const override { return 1; }
 
-  bool isShape() const override { return false; }
+  bool isShapeTensor() const override { return false; }
+
+  bool isExecutionTensor() const override { return true; }
 #endif
 
  private:
diff --git tensorflow/lite/kernels/internal/BUILD tensorflow/lite/kernels/internal/BUILD
index 5bafcdc00c..a749a5316b 100644
--- tensorflow/lite/kernels/internal/BUILD
+++ tensorflow/lite/kernels/internal/BUILD
@@ -22,15 +22,12 @@ HARD_FP_FLAGS_IF_APPLICABLE = select({
 NEON_FLAGS_IF_APPLICABLE = select({
     ":arm": [
         "-O3",
-        "-mfpu=neon",
     ],
     ":armeabi-v7a": [
         "-O3",
-        "-mfpu=neon",
     ],
     ":armv7a": [
         "-O3",
-        "-mfpu=neon",
     ],
     "//conditions:default": [
         "-O3",
diff --git tensorflow/lite/kernels/internal/depthwiseconv_quantized_test.cc tensorflow/lite/kernels/internal/depthwiseconv_quantized_test.cc
index 287f0a46be..c9bcb35c94 100644
--- tensorflow/lite/kernels/internal/depthwiseconv_quantized_test.cc
+++ tensorflow/lite/kernels/internal/depthwiseconv_quantized_test.cc
@@ -167,7 +167,8 @@ inline void DispatchDepthwiseConv(
       // This is compiled-in even if dot-product instructions are unavailable.
       // However, tests should skip dot-product testing in that case and not
       // call this code.
-#if defined(__aarch64__) && !defined(GOOGLE_L4T)
+#if defined(__aarch64__) && !defined(GOOGLE_L4T) && defined(__ANDROID__) && \
+    defined(__clang__)
       DotProduct3x3KernelType kernel_type =
           optimized_ops::depthwise_conv::CategorizeDotProductKernel(
               input_shape, filter_shape, params);
@@ -691,7 +692,8 @@ void TestOneDepthwiseConv3x3Filter(
 }
 
 void TestOneNeonDot3x3(const TestParam& test_param) {
-#if defined(__aarch64__) && !defined(GOOGLE_L4T)
+#if defined(__aarch64__) && !defined(GOOGLE_L4T) && defined(__ANDROID__) && \
+    defined(__clang__)
   CpuBackendContext backend_context;
   ruy::Context* ruy_context = backend_context.ruy_context();
   const auto ruy_paths = ruy_context != nullptr
@@ -856,7 +858,8 @@ INSTANTIATE_TEST_SUITE_P(
     TestParam::TestNameSuffix);
 #endif
 
-#if defined(__aarch64__) && !defined(GOOGLE_L4T)
+#if defined(__aarch64__) && !defined(GOOGLE_L4T) && defined(__ANDROID__) && \
+    defined(__clang__)
 INSTANTIATE_TEST_SUITE_P(
     NeonAsm, DepthwiseConvTest,
     testing::Combine(
diff --git tensorflow/lite/kernels/internal/optimized/depthwiseconv_uint8.h tensorflow/lite/kernels/internal/optimized/depthwiseconv_uint8.h
index edf59248e1..8957425d34 100644
--- tensorflow/lite/kernels/internal/optimized/depthwiseconv_uint8.h
+++ tensorflow/lite/kernels/internal/optimized/depthwiseconv_uint8.h
@@ -2007,7 +2007,8 @@ inline void DepthwiseConvWithRounding(
 
 // Enable for arm64 except for the Nvidia Linux 4 Tegra (L4T) running on
 // Jetson TX-2. This compiler does not support the offsetof() macro.
-#if defined(__aarch64__) && !defined(GOOGLE_L4T)
+#if defined(__aarch64__) && !defined(GOOGLE_L4T) && defined(__ANDROID__) && \
+    defined(__clang__)
   // Dispatch to dot-product 3x3 kernels when supported.
 
   ruy::Context* ruy_context = cpu_backend_context->ruy_context();
@@ -2030,6 +2031,8 @@ inline void DepthwiseConvWithRounding(
     }
   }
 
+#elif defined(__aarch64__) && !defined(GOOGLE_L4T)
+
   // Dispatch to non-dot-product 3x3 kernels when supported.
 
   const int stride_width = params.stride_width;
diff --git tensorflow/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h tensorflow/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h
index 5b570eed18..eef46efe96 100644
--- tensorflow/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h
+++ tensorflow/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h
@@ -5790,7 +5790,8 @@ struct WorkspacePrefetchWrite<
 
 #endif  // USE_NEON &&__aarch64__
 
-#if defined(__aarch64__) && !defined(GOOGLE_L4T)
+#if defined(__aarch64__) && !defined(GOOGLE_L4T) && defined(__ANDROID__) && \
+    defined(__clang__)
 // Dot product ops hard-coded
 
 template <>
diff --git third_party/tensorrt/tensorrt_configure.bzl third_party/tensorrt/tensorrt_configure.bzl
index 81612e5212..959391997b 100644
--- third_party/tensorrt/tensorrt_configure.bzl
+++ third_party/tensorrt/tensorrt_configure.bzl
@@ -27,8 +27,8 @@ _TF_TENSORRT_HEADERS_V6 = [
     "NvUtils.h",
     "NvInferPlugin.h",
     "NvInferVersion.h",
-    "NvInferRTSafe.h",
-    "NvInferRTExt.h",
+    "NvInferRuntime.h",
+    "NvInferRuntimeCommon.h",
     "NvInferPluginUtils.h",
 ]
 
diff --git third_party/toolchains/cpus/arm/BUILD third_party/toolchains/cpus/arm/BUILD
index 237c2357d8..62c1e7b3f4 100644
--- third_party/toolchains/cpus/arm/BUILD
+++ third_party/toolchains/cpus/arm/BUILD
@@ -13,6 +13,7 @@ cc_toolchain_suite(
         "k8": ":cc-compiler-local",
         "piii": ":cc-compiler-local",
         "arm": ":cc-compiler-local",
+        "aarch64": ":cc-compiler-local",
         "s390x": ":cc-compiler-local",
     },
 )
```

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
