### ISSUE TITLE
Tensorflow Lite build for Android results in issue - class file not found

### ISSUE THREAD

**Issue by jaemin-shin** [tensorflow/tensorflow#55572]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: master repo / nightly repo
- Python version: 3.7.3
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 5.1.1
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: not using cuda
- GPU model and memory: not using GPU

**Describe the problem**

I am trying to use custom-built tensorflow lite AAR on model personalization example of official tensorflow repo from the [link](https://github.com/tensorflow/examples/tree/master/lite/examples/model_personalization)

Before I change anything from the master repository, I followed the steps in this [link](https://www.tensorflow.org/lite/guide/build_android) to build Tensorflow Lite AAR with bazel.

Actually the bazel build did not flawlessly work at once; I had to change the visibility option of 'op_resolver_internal' to public in tensorflow/lite/core/api/BUILD to successfully build the AAR.

Anyways, when I substituted the tensorflow-lite api with my built AARs, I get the following error:

Error 1:
android\transfer_api\src\main\java\org\tensorflow\lite\examples\transfer\api\LiteMultipleSignatureModel.java:57: error: cannot access InterpreterApi
    this.interpreter.runSignature(inputs, outputs, "load");
                    ^
  class file for org.tensorflow.lite.InterpreterApi not found

Error 2:
android\transfer_api\src\main\java\org\tensorflow\lite\examples\transfer\api\LiteMultipleSignatureModel.java:105: error: cannot access Tensor
    return this.interpreter.getInputTensorFromSignature("bottleneck", "train").shape()[1];
                                                       ^
  class file for org.tensorflow.lite.Tensor not found

Why does this happen?? Is there anything wrong with the current bazel build?

I also built the tensorflow-lite-select-tf-ops.aar and included that in build.gradle.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Described above

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by mohantym** [comment]
Hi @jaemin-shin ! Could you please share your command on bazel build  method too?

**Comment by jaemin-shin** [comment]
**Hello! Here is the bazel command that I used:**

bazel build -c opt --fat_apk_cpu=arm64-v8a  --host_crosstool_top=@bazel_tools//tools/cpp:toolchain //tensorflow/lite/java:tensorflow-lite

**For ./configure in the tensorflow root directory, I configured as follows:**

(base) jmshin@ubuntu:~/tensorflow > ./configure
You have bazel 5.1.1 installed.
Please specify the location of python. [Default is /home/jmshin/miniconda3/bin/python3]:


Found possible Python library paths:
  /home/jmshin/miniconda3/lib/python3.7/site-packages
Please input the desired Python library path to use.  Default is [/home/jmshin/miniconda3/lib/python3.7/site-packages]

Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: n
No CUDA support will be enabled for TensorFlow.

Do you wish to download a fresh release of clang? (Experimental) [y/N]: n
Clang will not be downloaded.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -Wno-sign-compare]: -O3


Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: y
Searching for NDK and SDK installations.

Please specify the home path of the Android NDK to use. [Default is /home/jmshin/Android/Sdk/ndk-bundle]: /home/jmshin/Android/Sdk/ndk/19.2.5345600


Please specify the (min) Android NDK API level to use. [Available levels: ['16', '17', '18', '19', '21', '22', '23', '24', '26', '27', '28']] [Default is 21]:


Please specify the home path of the Android SDK to use. [Default is /home/jmshin/Android/Sdk]:


Please specify the Android SDK API level to use. [Available levels: ['32']] [Default is 32]:


Please specify an Android build tools version to use. [Available versions: ['30.0.3', '32.0.0', '32.1.0-rc1']] [Default is 32.1.0-rc1]: 30.0.3


Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=mkl_aarch64    # Build with oneDNN and Compute Library for the Arm Architecture (ACL).
        --config=monolithic     # Config for mostly static monolithic build.
        --config=numa           # Build with NUMA support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
        --config=v1             # Build with TensorFlow 1 API instead of TF 2 API.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=nogcp          # Disable GCP support.
        --config=nonccl         # Disable NVIDIA NCCL support.
Configuration finished

**Comment by mohantym** [comment]
Ok @jaemin-shin ! I think it is [missing a dependency](https://stackoverflow.com/questions/66880515/cannot-access-tensorflow-lite-support-tensorbuffer)  of lite support in the build.gradle file.  

Did you try after adding aar files [to the project ](https://www.tensorflow.org/lite/guide/build_android#add_aar_directly_to_project)and [local maven repository](https://www.tensorflow.org/lite/guide/build_android#install_aar_to_local_maven_repository)?

 If that does not work please try again after adding more architecture and let us know the results.
 
` bazel build -c opt --fat_apk_cpu=arm64-v8a armeabi-v7a --host_crosstool_top=@bazel_tools//tools/cpp:toolchain //tensorflow/lite/java:tensorflow-lite`

Thanks!

**Comment by jaemin-shin** [comment]
Dear @mohantym,

Thank you for the suggestion! Unfortunately, it all did not work; I tried adding them by aar file, or adding them through local maven repository, and repeated all process with adding more architecture in bazel config. All was out of luck.

I think the aar is well recognized by the Android Studio, since it does not show on error on
`import org.tensorflow.lite.Interpreter;`

but shows error on followings:

Error 1:
android\transfer_api\src\main\java\org\tensorflow\lite\examples\transfer\api\LiteMultipleSignatureModel.java:57: error: cannot access InterpreterApi
this.interpreter.runSignature(inputs, outputs, "load");
^
class file for org.tensorflow.lite.InterpreterApi not found

Error 2:
android\transfer_api\src\main\java\org\tensorflow\lite\examples\transfer\api\LiteMultipleSignatureModel.java:105: error: cannot access Tensor
return this.interpreter.getInputTensorFromSignature("bottleneck", "train").shape()[1];
^
class file for org.tensorflow.lite.Tensor not found


I also tried bazel build on release branch r2.8 as they should be stable,
but the same error occurred...

**Comment by mohantym** [comment]
Hi @chunduriv ! Could you please look at this issue?

**Comment by jaemin-shin** [comment]
Hi @chunduriv! May I ask if there's any update on this?! Have a nice day :)

**Comment by pjpratik** [comment]
Hi @jaemin-shin 

The [model personalization](https://github.com/tensorflow/examples/tree/master/lite/examples/model_personalization) example has been updated with commit https://github.com/tensorflow/examples/commit/7cb2b4dd5858c44cf8ab2c691bc646eaaf28713e

Could you please try with latest version and let us know if you are still facing the issue?

Thanks.
