### ISSUE TITLE
Keras 'Model' object has no attribute '_callable_losses'

### ISSUE THREAD

**Issue by danielfllaneza** [tensorflow/tensorflow#41233]
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS inux release 7.6.1810
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.14.0
- Python version: 3.7.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: V9.1.85
- GPU model and memory: Tesla K80 24C

I have a class with a model and I want to add a custom loss with three arguments.  Upon building the model, the following error is raised:
```
<ipython-input-124-46b9e7f916ce> in _build(self)
     50 
     51         self.get_optimiser()
---> 52         model = self.get_loss(inputs, x)
     53 
     54         return model

<ipython-input-124-46b9e7f916ce> in get_loss(self, inputs, outputs)
    151             model = Model(inputs=[inputs, y_true, is_weight], outputs=[outputs])
    152 
--> 153             model.add_loss(weighted_dice_loss(y_true, outputs, is_weight))
    154             self._model.compile(optimizer = self._optimiser, loss = None, metrics = [dice_coef])
    155 

~/miniconda3/envs/segment/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py in add_loss(self, losses, inputs)
    899         eager_losses.append(_tag_unconditional(loss))
    900 
--> 901     self._callable_losses += callable_losses
    902 
    903     call_context = base_layer_utils.is_in_call_context()

AttributeError: 'Model' object has no attribute '_callable_losses'
```
The expected behaviour is, thus, that the model accepts this custom loss, since it has three arguments instead of two when calling unet._build() without getting thrown an error:
```
unet = UNet()
unet._build()

```

The minimum reproducible code is as follows:
```
class UNet():

    def __init__(self, **kwargs):
        
        self._input_shape = kwargs.get('input_shape', (12, 86, 98,1))
        self._blocks = kwargs.get('blocks', 2)
        self._layers = kwargs.get('layers', 8)
        self._n_filters = kwargs.get('n_filters', 16)
        self._patch = kwargs.get('patch', (3,3,3))
        self._activation = kwargs.get('activation', 'elu')
        self._activation_last = kwargs.get('activation_last', 'sigmoid')
        self._kernel_initializer = kwargs.get('kernel_initializer', 'glorot_normal')
        self._padding = kwargs.get('padding', 'same')
        self._learnrate = kwargs.get('learnrate',0.001)
        self._momentum = kwargs.get('momentum',0.99)
        self._decay = kwargs.get('decay',0.0)
        self._mode = kwargs.get('mode','train')
           
    def _build(self):
        
        # Initialise array to keep skip connections
        self.skips = []
        
        inputs = Input(shape = self._input_shape)
        
        x = self.first_layers(inputs)
        x = self.contractive_path(x)
        x = self.middle_path(x)
        x = self.expansive_path(x)
        
        self.get_optimiser()
        model = self.get_loss(inputs, x)
            
        return model
    
    def first_layers(self, inputs):
       
        layer = Conv3D(filters = self._n_filters, kernel_size = self._patch, activation = self._activation, kernel_initializer = self._kernel_initializer,
                padding = self._padding)(inputs)
        
        return layer
    
    def contractive_path(self, layer):

        for b in range(0,self._blocks):
            for i in range(0,self._layers):
                layer = Conv3D(filters = self._n_filters, kernel_size = self._patch, activation = self._activation, kernel_initializer = self._kernel_initializer,
                padding = self._padding)(layer)
            
            #append for later use in up-sampling
            self.skips.append(layer)
            
            #downsampling (using patch(2,2,2) and stride of 2, similar to MaxPooling3D but uses less parameters)
            layer = Conv3D(filters = self._n_filters, kernel_size = (2,2,2), strides = (2, 2, 2), activation = self._activation, kernel_initializer = self._kernel_initializer,
                padding = self._padding)(layer)

            #post-pooling, double number of filters
            self._n_filters = int(self._n_filters*2)
     
        return layer 
        
    def middle_path(self, layer):
   
        for i in range(0,self._layers):
            layer = Conv3D(filters = self._n_filters, kernel_size = self._patch, activation = self._activation, kernel_initializer = self._kernel_initializer,
                padding = self._padding)(layer)
        
        return layer

    def expansive_path(self, layer):

        for u in range(0,self._blocks):
            layer = UpSampling3D(size = (2,2,2), data_format = None)(layer) 
            
            # skip connection from DOWN_PATH
            concat_lr = self.skips[-1]

            layer, concat_lr = cropping_tensor(layer, concat_lr)
            layer = Concatenate()([layer, concat_lr])
            
            for i in range(0,(self._layers)):
                layer = Conv3D(filters = self._n_filters, kernel_size = self._patch, activation = self._activation, kernel_initializer = self._kernel_initializer,
                padding = self._padding)(layer)
                
            self._n_filters = int(self._n_filters/2)
            #print('UpBlock',str(u),' : end_n_filters ', str(n_filters))
            
            self.skips = self.skips[:-1] # get rid of last skip connection 
            
        ### output layer 
        y_pred = Conv3D(1, (1,1,1), activation = self._activation_last)(layer)    
        
        return y_pred
    
    def get_optimiser(self):
            self._optimiser = SGD(lr = self._learnrate, momentum = self._momentum, decay = self._decay, nesterov = False)
    
    def get_loss(self, inputs, outputs):
            
            y_true = Input(self._input_shape, name = 'y_true')
            is_weight = Input(self._input_shape, name = 'is_weight')

            model = Model(inputs=[inputs, y_true, is_weight], outputs=[outputs])
            
            model.add_loss(weighted_dice_loss(y_true, outputs, is_weight))
            self._model.compile(optimizer = self._optimiser, loss = None, metrics = [dice_coef])
        
        return self._model
```
The weighted_dice_loss function is defined as follows:
```
def weighted_dice_loss(y_true, y_pred, w):
    
    return -weighted_dice_coef(y_true, y_pred, w)
```

**Comment by danielfllaneza** [comment]
Upon updating tensorflow, I got the following error:
```
---> 44         inputs = Input(shape = self._input_shape)
     45 
     46         x = self.first_layers(inputs)

~/miniconda3/envs/segment/lib/python3.7/site-packages/keras/engine/input_layer.py in Input(shape, batch_shape, name, dtype, sparse, tensor)
    176                              name=name, dtype=dtype,
    177                              sparse=sparse,
--> 178                              input_tensor=tensor)
    179     # Return tensor including _keras_shape and _keras_history.
    180     # Note that in this case train_output and test_output are the same pointer.

~/miniconda3/envs/segment/lib/python3.7/site-packages/keras/legacy/interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name + '` call to the ' +
     90                               'Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

~/miniconda3/envs/segment/lib/python3.7/site-packages/keras/engine/input_layer.py in __init__(self, input_shape, batch_size, batch_input_shape, dtype, input_tensor, sparse, name)
     37         if not name:
     38             prefix = 'input'
---> 39             name = prefix + '_' + str(K.get_uid(prefix))
     40         super(InputLayer, self).__init__(dtype=dtype, name=name)
     41 

~/miniconda3/envs/segment/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py in get_uid(prefix)
     72     """
     73     global _GRAPH_UID_DICTS
---> 74     graph = tf.get_default_graph()
     75     if graph not in _GRAPH_UID_DICTS:
     76         _GRAPH_UID_DICTS[graph] = defaultdict(int)

AttributeError: module 'tensorflow' has no attribute 'get_default_graph'
```

**Comment by danielfllaneza** [comment]
Of note, I was importing tensorflow as follows:
```
import tensorflow.v1.compat as tf
```
Upon updating tensorflow and running the code again I get thrown this
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-3f26c80035c9> in <module>
      1 #graph = tf.get_default_graph()
----> 2 unet_model = unet._build()

<ipython-input-8-9245d04f54db> in _build(self)
     42         self.skips = []
     43 
---> 44         inputs = Input(shape = self._input_shape)
     45 
     46         x = self.first_layers(inputs)

~/miniconda3/envs/segment/lib/python3.7/site-packages/keras/engine/input_layer.py in Input(shape, batch_shape, name, dtype, sparse, tensor)
    176                              name=name, dtype=dtype,
    177                              sparse=sparse,
--> 178                              input_tensor=tensor)
    179     # Return tensor including _keras_shape and _keras_history.
    180     # Note that in this case train_output and test_output are the same pointer.

~/miniconda3/envs/segment/lib/python3.7/site-packages/keras/legacy/interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name + '` call to the ' +
     90                               'Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

~/miniconda3/envs/segment/lib/python3.7/site-packages/keras/engine/input_layer.py in __init__(self, input_shape, batch_size, batch_input_shape, dtype, input_tensor, sparse, name)
     37         if not name:
     38             prefix = 'input'
---> 39             name = prefix + '_' + str(K.get_uid(prefix))
     40         super(InputLayer, self).__init__(dtype=dtype, name=name)
     41 

~/miniconda3/envs/segment/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py in get_uid(prefix)
     72     """
     73     global _GRAPH_UID_DICTS
---> 74     graph = tf.get_default_graph()
     75     if graph not in _GRAPH_UID_DICTS:
     76         _GRAPH_UID_DICTS[graph] = defaultdict(int)

AttributeError: module 'tensorflow' has no attribute 'get_default_graph'
```

**Comment by mash2612** [comment]
Hi, instead of using :
`
from keras.layers.convolutional import Conv3D, Conv3DTranspose
from keras.layers.normalization import BatchNormalization
from keras.layers import Cropping3D, UpSampling3D, AveragePooling3D`

use : 
`
from tensorflow.keras.layers.convolutional import Conv3D, Conv3DTranspose
from tensorflow.keras.layers.normalization import BatchNormalization
from tensorflow.keras.layers import Cropping3D, UpSampling3D, AveragePooling3D` while working with tf2.0 or higher.

**Comment by Saduf2019** [comment]
@mash2612 
Please refer to [this comment](https://github.com/keras-team/keras/issues/12379#issuecomment-486207178) with same error to resolve the issue.
[link](https://github.com/keras-team/keras/issues/12783#issuecomment-499870218) [link1](https://stackoverflow.com/questions/55496289/how-to-fix-attributeerror-module-tensorflow-has-no-attribute-get-default-gr).
and us know if it helps.

**Comment by mash2612** [comment]
@Saduf2019 this issue was raised by @danielfllaneza . I was just suggesting a way to solve this and I think the links also indicate a solution in the same direction.
@danielfllaneza let us know if the solution helped you.

**Comment by Saduf2019** [comment]
@ danielfllaneza 
Please update as per above comment.

**Comment by danielfllaneza** [comment]
Thanks for the suggestions, It only worked when importing it like this:
 ```
import tensorflow as tf

from tensorflow.keras import Input
from tensorflow.keras.models import Model
from tensorflow.keras.layers import (AveragePooling3D,
                                    BatchNormalization,
                                    Concatenate, 
                                    Conv3D, 
                                    Conv3DTranspose,
                                    Cropping3D,
                                    UpSampling3D)
```

**Comment by Saduf2019** [comment]
@danielfllaneza 
Please confirm if the issue is resolved can we move this to closed status.
