### ISSUE TITLE
AttributeError: module 'tensorflow.compat.v2.__internal__.tracking' has no attribute 'DelegatingTrackableMixin'

### ISSUE THREAD

**Issue by JanderHungrige** [tensorflow/tensorflow#51992]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **Yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Ubuntu 20.04.2 LTS** 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **no**
- TensorFlow installed from (source or binary): **pip**
- TensorFlow version (use command below): **2.7.0-dev20210806**
- Python version: **3.6**
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: **no GPU in use**
- GPU model and memory:

**Describe the current behavior**

**Error when trying to load model.Worked in 2.6.0 and previouse.**

Error message in short: 

**AttributeError: module 'tensorflow.compat.v2.__internal__.tracking' has no attribute 'DelegatingTrackableMixin'**
**logs below** 

**Describe the expected behavior**

**Should just load a model** 

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
```
import tensorflow as tf
tfVersion=tf.version.VERSION.replace(".", "")
print('TensorFlow Version: '+tf.version.VERSION)
import pathlib as path

if __name__ == '__main__':
     saved_model_dir= path.Path.cwd() / 'model' / 'Pump_LSTM_Fapi_OOP_1_tf_260' 
     model=tf.keras.models.load_model(saved_model_dir)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**MODEL**
[Pump_LSTM_Fapi_OOP_1_tf_260.zip](https://github.com/tensorflow/tensorflow/files/7163177/Pump_LSTM_Fapi_OOP_1_tf_260.zip)

**TRACEBACK**

> TensorFlow Version: 2.7.0-dev20210806
> Traceback (most recent call last):
> 
>   File "/home/base/Documents/Git/KundenProjekte2021/Ginko/pump_sensor/untitled0.py", line 41, in <module>
>     model=tf.keras.models.load_model(saved_model_dir)
> 
>   File "/home/base/anaconda3/envs/AInight/lib/python3.6/site-packages/tensorflow/python/util/lazy_loader.py", line 62, in __getattr__
>     module = self._load()
> 
>   File "/home/base/anaconda3/envs/AInight/lib/python3.6/site-packages/tensorflow/python/util/lazy_loader.py", line 45, in _load
>     module = importlib.import_module(self.__name__)
> 
>   File "/home/base/anaconda3/envs/AInight/lib/python3.6/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
> 
>   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
> 
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
> 
>   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
> 
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
> 
>   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
> 
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
> 
>   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
> 
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
> 
>   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
> 
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
> 
>   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
> 
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
> 
>   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
> 
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
> 
>   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
> 
>   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
> 
>   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
> 
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
> 
>   File "/home/base/anaconda3/envs/AInight/lib/python3.6/site-packages/keras/__init__.py", line 25, in <module>
>     from keras import models
> 
>   File "/home/base/anaconda3/envs/AInight/lib/python3.6/site-packages/keras/models.py", line 20, in <module>
>     from keras import metrics as metrics_module
> 
>   File "/home/base/anaconda3/envs/AInight/lib/python3.6/site-packages/keras/metrics.py", line 26, in <module>
>     from keras import activations
> 
>   File "/home/base/anaconda3/envs/AInight/lib/python3.6/site-packages/keras/activations.py", line 20, in <module>
>     from keras.layers import advanced_activations
> 
>   File "/home/base/anaconda3/envs/AInight/lib/python3.6/site-packages/keras/layers/__init__.py", line 23, in <module>
>     from keras.engine.input_layer import Input
> 
>   File "/home/base/anaconda3/envs/AInight/lib/python3.6/site-packages/keras/engine/input_layer.py", line 21, in <module>
>     from keras.engine import base_layer
> 
>   File "/home/base/anaconda3/envs/AInight/lib/python3.6/site-packages/keras/engine/base_layer.py", line 43, in <module>
>     from keras.mixed_precision import loss_scale_optimizer
> 
>   File "/home/base/anaconda3/envs/AInight/lib/python3.6/site-packages/keras/mixed_precision/loss_scale_optimizer.py", line 257, in <module>
>     class LossScaleOptimizer(tf.__internal__.tracking.DelegatingTrackableMixin,
> 
> AttributeError: module 'tensorflow.compat.v2.__internal__.tracking' has no attribute 'DelegatingTrackableMixin'

**Comment by tilakrayal** [comment]
@JanderHungrige ,
Can you please take a look at this [comment](https://github.com/tensorflow/tensorflow/issues/51850#issuecomment-913445468) from the issue with similar error and let us know if you are facing same issue.Thanks

**Comment by JanderHungrige** [comment]
Yes it is indeed. Thank you for your quick help.

**Comment by tilakrayal** [comment]
@JanderHungrige ,
 Glad the issue is resolved for you, please feel free to move this to closed status.Thanks!
