### ISSUE TITLE
Build from v1.12.0 failed

### ISSUE THREAD

**Issue by yann-yy** [tensorflow/tensorflow#24794]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): centos 4.4.131-1.el7.elrepo.x86_64
- TensorFlow installed from (source or binary): source
- TensorFlow version: tag v1.12.0
- Python version: python2.7
- Bazel version (if compiling from source): 0.21.0
- GCC/Compiler version (if compiling from source): gcc 4.9.2

**Describe the problem**
try to build from source enable avx512f while local cpu not support
**Provide the exact sequence of commands / steps that you executed before running into the problem**
- Build command:
`bazel build --config=opt  --copt=-mavx512f --incompatible_package_name_is_a_function=false  //tensorflow:libtensorflow_cc.so`
- Build error:
`ERROR: /home/tensorflow/tensorflow/compiler/xla/client/lib/BUILD:67:1: C++ compilation of rule '//tensorflow/compiler/xla/client/lib:conv_grad_size_util' failed (Exit 1)
In file included from external/eigen_archive/Eigen/Core:403:0,
                 from ./third_party/eigen3/Eigen/Core:1,
                 from ./tensorflow/compiler/xla/types.h:21,
                 from ./tensorflow/compiler/xla/client/padding.h:24,
                 from ./tensorflow/compiler/xla/client/lib/conv_grad_size_util.h:19,
                 from tensorflow/compiler/xla/client/lib/conv_grad_size_util.cc:16:
external/eigen_archive/Eigen/src/Core/arch/AVX512/PacketMath.h:120:1: error: 'Packet Eigen::internal::pset1(const typename Eigen::internal::unpacket_traits<Packet>::type&) [with Packet = __vector(16) float; typename Eigen::internal::unpacket_traits<Packet>::type = float]' conflicts with a previous declaration
 }
 ^
In file included from external/eigen_archive/Eigen/Core:402:0,
                 from ./third_party/eigen3/Eigen/Core:1,
                 from ./tensorflow/compiler/xla/types.h:21,
                 from ./tensorflow/compiler/xla/client/padding.h:24,
                 from ./tensorflow/compiler/xla/client/lib/conv_grad_size_util.h:19,
                 from tensorflow/compiler/xla/client/lib/conv_grad_size_util.cc:16:
external/eigen_archive/Eigen/src/Core/arch/AVX/PacketMath.h:120:41: note: previous declaration 'Packet Eigen::internal::pset1(const typename Eigen::internal::unpacket_traits<Packet>::type&) [with Packet = __vector(8) float; typename Eigen::internal::unpacket_traits<Packet>::type = float]'
 template<> EIGEN_STRONG_INLINE Packet8f pset1<Packet8f>(const float&  from) { return _mm256_set1_ps(from); }
                                         ^
In file included from external/eigen_archive/Eigen/Core:403:0,
                 from ./third_party/eigen3/Eigen/Core:1,
                 from ./tensorflow/compiler/xla/types.h:21,
                 from ./tensorflow/compiler/xla/client/padding.h:24,
                 from ./tensorflow/compiler/xla/client/lib/conv_grad_size_util.h:19,
                 from tensorflow/compiler/xla/client/lib/conv_grad_size_util.cc:16:
external/eigen_archive/Eigen/src/Core/arch/AVX512/PacketMath.h:118:31: note: -fabi-version=6 (or =0) avoids this error with a change in mangling`

- Build command:
`bazel build --config=opt  --copt=-mavx512f --cxxopt=-fabi-version=6 --incompatible_package_name_is_a_function=false  //tensorflow:libtensorflow_cc.so`
- Build error:
`ERROR: /home/tensorflow/tensorflow/core/BUILD:2551:1: C++ compilation of rule '//tensorflow/core:framework_internal_impl' failed (Exit 1)
In file included from external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/Core:403:0,
                 from external/eigen_archive/unsupported/Eigen/CXX11/Tensor:14,
                 from ./third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1,
                 from ./tensorflow/core/framework/tensor_shape.h:21,
                 from ./tensorflow/core/framework/partial_tensor_shape.h:20,
                 from ./tensorflow/core/framework/attr_value_util.h:23,
                 from tensorflow/core/framework/op_def_builder.cc:21:
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/AVX512/PacketMath.h: In function 'Packet Eigen::internal::ploaddup(const typename Eigen::internal::unpacket_traits<Packet>::type*) [with Packet = __vector(16) float; typename Eigen::internal::unpacket_traits<Packet>::type = float]':
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/AVX512/PacketMath.h:470:77: error: '_mm512_castsi512_ps' was not declared in this scope
   __m512 even_elements = _mm512_castsi512_ps(_mm512_cvtepu32_epi64(low_half));`

**Comment by msymp** [comment]
Hello @yann-yy , Please step back and try building with bazel 0.15.0 , gcc 4.8 , and let us know. Thanks.

**Comment by yann-yy** [comment]
@msymp , I have built successfully with `bazel 0.21.0` and `gcc 4.8.5`. I'm trying to build with `-mavx512f` to have better performance( `CPU： 3.2GHz Intel Xeon® Skylake 6146` supports AVX512) while `-mavx512f` option is only support by `gcc 4.9` and later. I also have built successfully with `bazel 0.21.0` and `gcc 4.9.2` without `-mavx512f`. And I found `_mm512_castsi512_ps` function in `gcc 5+` and `clang`, and also in documents of Intel c++ compiler. I tried to re-compile tensorflow with `clang` instead of `gcc`, but got some errors about incompatible compile options only supports by gcc. Now I'm trying to build with gcc 5.3.1, and post later. And I'm not pretty sure about the consequences after I introduced `--cxxopt=-fabi-version=6`. Thanks.

**Comment by yann-yy** [comment]
Finally, I built successfully with `bazel 0.21.0` and `gcc 5.3.1`. It seems `eigen` requires `gcc 5+` when compile with `-mavx512f`.
My build command is `bazel build --config=opt --copt=-mavx512f --cxxopt=-fabi-version=6 --incompatible_package_name_is_a_function=false //tensorflow:libtensorflow_cc.so`
I'm testing the binary now.

**Comment by msymp** [comment]
@yann-yy , glad to hear that. Since we have addressed your initial query, we shall close the issue now. Thanks.
