### ISSUE TITLE
Latest code in master branch won't compile on CentOS

### ISSUE THREAD

**Issue by shengfuintel** [tensorflow/tensorflow#24457]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
CentOS Linux release 7.5.1804
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
N/A
- TensorFlow installed from (source or binary):
Source
- TensorFlow version:
Latest code in master branch
- Python version:
2.7
- Installed using virtualenv? pip? conda?:
pip
- Bazel version (if compiling from source):
1.9
- GCC/Compiler version (if compiling from source):
6.3.0
- CUDA/cuDNN version:
N/A
- GPU model and memory:
N/A

**Describe the problem**
When compile with the following command line: 
bazel build -c dbg //tensorflow/tools/pip_package:build_pip_package
I got the following error:
external/eigen_archive/Eigen/src/Core/products/GeneralBlockPanelKernel.h: In member function 'void Eigen::internal::gebp_kernel<LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs>::operator()(const DataMapper&, const LhsScalar*, const RhsScalar*, Index, Index, Index, Eigen::internal::gebp_kernel<LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs>::ResScalar, Index, Index, Index, Index) [with LhsScalar = float; RhsScalar = float; Index = long int; DataMapper = Eigen::internal::blas_data_mapper<float, long int, 0, 0>; int mr = 8; int nr = 4; bool ConjugateLhs = false; bool ConjugateRhs = false]':
external/eigen_archive/Eigen/src/Core/products/GeneralBlockPanelKernel.h:1419:13: error: inconsistent operand constraints in an 'asm'
             EIGEN_GEBGP_ONESTEP(0);
             ^
and more similar errors.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
see the commands above

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by shengfuintel** [comment]
It can be fixed temporary with change the line 1394 in external/eigen_archive/Eigen/src/Core/productsGeneralBlockPanelKernel.h:

Change line 1394 from 
#if EIGEN_GNUC_AT_LEAST(6,0) 
to
#if EIGEN_GNUC_AT_LEAST(6,0) && NDEBUG

Basically disable EIGEN_GEBP_2PX4_SPILLING_WORKAROUND when compile debug version

**Comment by mwoehlke-kitware** [comment]
Was this with Eigen 3.3.6? Does Eigen 3.3.5 work? If so, please report back to upstream (see http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1651).

**Comment by chhtz** [comment]
Could you check if it works with Eigen 3.3.7? Otherwise, feel free to re-open http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1651 with more details.
