### ISSUE TITLE
AttributeError: 'KerasTPUModel' object has no attribute '_ckpt_saved_epoch'

### ISSUE THREAD

**Issue by ssable** [tensorflow/tensorflow#29791]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.14.0-rc1
- Python version: 3.6.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

Code is running in Colab and was working fine with tensorflow 1.13.1.
Colab was updated to tensorflow 1.14.0-rc1 today apparently which is causing the regression.
Running tpu_model.fit for a TPU model that was generated with tf.contrib.tpu.keras_to_tpu_model, I get:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-bbab49a84214> in <module>()
     14 
     15 print(datetime.now())
---> 16 history = tpu_model.fit(train_dataset_fn, epochs=nb_epochs, steps_per_epoch=total_samples // batch_size, validation_data=val_dataset_fn, validation_steps=batch_size) # , verbose=2)
     17 print(datetime.now())

3 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/callbacks.py in configure_callbacks(callbacks, model, do_validation, batch_size, epochs, steps_per_epoch, samples, verbose, count_mode, mode)
    118   callback_list.model.stop_training = False
    119   # pylint: disable=protected-access
--> 120   if callback_list.model._ckpt_saved_epoch is not None:
    121     # The attribute `_ckpt_saved_epoch` is supposed to be None at the start of
    122     # training (it should be made None at the end of successful multi-worker

AttributeError: 'KerasTPUModel' object has no attribute '_ckpt_saved_epoch'

**Comment by gadagashwini** [comment]
@ssable In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by ssable** [comment]
I tried to reproduce the issue with a minimal code snippet, but while doing that I found another bug #29798.
Once that other bug is resolved, the code provided there should raise this issue or I should be able to come up with a simple example how to reproduce.

**Comment by giovannibaratta** [comment]
I have the same issue. This example code should raise the error. Instead, in version 1.13.1 should work fine. I tried it in colab.

```
#!pip install -q tensorflow==1.13.1
import tensorflow as tf
import numpy as np
import os

print(tf.__version__)

tpu_address = 'grpc://' + os.environ['COLAB_TPU_ADDR']

randomImages = np.random.rand(128,50,50,3)
randomLabels = np.random.randint(2, size=128)

#model
inputs = tf.keras.layers.Input(shape=(50, 50, 3))
outputLayer = inputs
for i in range(0,3):
  outputLayer = tf.keras.layers.Conv2D(filters=64, kernel_size = 3, padding = 'valid')(outputLayer)
  outputLayer = tf.keras.layers.BatchNormalization()(outputLayer)
  outputLayer = tf.keras.layers.ReLU()(outputLayer)
outputLayer = tf.keras.layers.Flatten()(outputLayer)
outputLayer = tf.keras.layers.Dense(2)(outputLayer)

model = tf.keras.Model(inputs = inputs, outputs = outputLayer)

#tpu_model 
tpu_model = tf.contrib.tpu.keras_to_tpu_model(
    model,
    strategy=tf.contrib.tpu.TPUDistributionStrategy(
    tf.contrib.cluster_resolver.TPUClusterResolver(tpu_address))
  )

tpu_model.compile(
    optimizer=tf.train.AdamOptimizer(learning_rate = 0.0001),
    loss=tf.keras.losses.sparse_categorical_crossentropy,
    metrics=['sparse_categorical_accuracy']
  )


tpu_model.fit(
              x = randomImages,
              y = randomLabels,
              batch_size = 64,
              epochs = 10
            )
```

**Comment by gadagashwini** [comment]
@giovannibaratta I tried reproducing the issue on colab with Tf 1.14.1 but I am getting different error, ValueError: Variable tpu_140309960546512//kernel/0 already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope?. 
Is this same error what you are getting?. Thanks!

**Comment by giovannibaratta** [comment]
> @giovannibaratta I tried reproducing the issue on colab with Tf 1.14.1 but I am getting different error, ValueError: Variable tpu_140309960546512//kernel/0 already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope?.
> Is this same error what you are getting?. Thanks!

No, I get this error : 

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-54cc81aef34f> in <module>()
     40               y = randomLabels,
     41               batch_size = 64,
---> 42               epochs = 10
     43             )



3 frames

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/callbacks.py in configure_callbacks(callbacks, model, do_validation, batch_size, epochs, steps_per_epoch, samples, verbose, count_mode, mode)
    118   callback_list.model.stop_training = False
    119   # pylint: disable=protected-access
--> 120   if callback_list.model._ckpt_saved_epoch is not None:
    121     # The attribute `_ckpt_saved_epoch` is supposed to be None at the start of
    122     # training (it should be made None at the end of successful multi-worker

AttributeError: 'KerasTPUModel' object has no attribute '_ckpt_saved_epoch'
```
There are also some warnings ("Keras support is now deprecated in support of TPU Strategy") but it's not clear to me how I should migrate to the new distribution strategy.

**Comment by javicivit** [comment]
I get exactly the same error
`%%time 
history=tpu_model.fit_generator(
                           train_generator(),
                           steps_per_epoch = 150,
                           validation_data = test_generator(),
                           validation_steps = 30,
                           epochs=15,
                           callbacks=[cp_callback]
)`
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-45-89e3eb7c573a> in <module>()
----> 1 get_ipython().run_cell_magic('time', '', 'history=tpu_model.fit_generator(\n                           train_generator(),\n                           steps_per_epoch = 150,\n                           validation_data = test_generator(),\n                           validation_steps = 30,\n                           epochs=15,\n                           callbacks=[cp_callback]\n)')

5 frames
</usr/local/lib/python3.6/dist-packages/decorator.py:decorator-gen-60> in time(self, line, cell, local_ns)

<timed exec> in <module>()

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/callbacks.py in configure_callbacks(callbacks, model, do_validation, batch_size, epochs, steps_per_epoch, samples, verbose, count_mode, mode)
    118   callback_list.model.stop_training = False
    119   # pylint: disable=protected-access
--> 120   if callback_list.model._ckpt_saved_epoch is not None:
    121     # The attribute `_ckpt_saved_epoch` is supposed to be None at the start of
    122     # training (it should be made None at the end of successful multi-worker

AttributeError: 'KerasTPUModel' object has no attribute '_ckpt_saved_epoch'`

**Comment by gadagashwini** [comment]
I could able to reproduce the issue on Colab with tensorflow 1.14.0-rc1. Thanks!

**Comment by giovannibaratta** [comment]
Following the MNIST example (https://colab.research.google.com/github/tensorflow/tpu/blob/master/tools/colab/fashion_mnist.ipynb#scrollTo=xLeZATVaNAnE) I was able to run the code in the new version.

```
resolver = tf.contrib.cluster_resolver.TPUClusterResolver('grpc://' + os.environ['COLAB_TPU_ADDR'])
tf.contrib.distribute.initialize_tpu_system(resolver)
strategy = tf.contrib.distribute.TPUStrategy(resolver)

with strategy.scope():
  #define model
  #compile model
  #fit model
```

Now, I have an other issue related to `tf.keras.layers.concatenate` that seems to be not implemented, or at least this is what the error says.

**Comment by javicivit** [comment]
If I rollback to tensorflow 1.13.1 (!pip install tensorflow==1.13.1) my code (above) works in colaboratory, however it becomes very slow. In fact it is quicker to run on GPU

**Comment by TimSmole** [comment]
@javicivit I am not completely sure since I never run code on TPU, but perhaps you should install tensorflow-gpu  (!pip install tensorflow-gpu==1.13.1)?

**Comment by jasoriya** [comment]
> @javicivit I am not completely sure since I never run code on TPU, but perhaps you should install tensorflow-gpu (!pip install tensorflow-gpu==1.13.1)?

Not if we are running on TPU, which is when this error arise. TPU uses `tensorflow `and not `tensorflow-gpu`

**Comment by rjpower** [comment]
By default the training loop for distribution strategy is running on the Colab host, not the TPU host. For larger models this isn't a problem, but for small models like MNIST, the latency between the 2 hosts can dominate the model execution time.

I believe DistributionStrategy performance has improved in the upcoming TF 2.1 release as well. I'm closing this for now as I believe the original question is answered, feel free to re-open if I missed something.
