### ISSUE TITLE
XNNPACK fails to crosscompile for `elinux_armhf`

### ISSUE THREAD

**Issue by lgeiger** [tensorflow/tensorflow#57364]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

master / v2.10.0-rc1

### Custom Code

No

### OS Platform and Distribution

elinux_armhf

### Python version

3.9

### Bazel version

5.1.1

### Current Behaviour?

```shell
XNNPACK fails to build on `master` and `v2.10.0-rc1` with `--config=elinux_armhf` which is required to build for Raspberry Pi 3. The same command worked well for `v2.9.1` but unfortunately fails with the latest version of TensorFlow and XNNPACK.

@Maratyszcza do you have any pointers in how to fix this issue or whether there are any flags missing in `.bazelrc`? It would be great if we could fix this for the `v2.10.0` stable release.
```

### Standalone code to reproduce the issue

```shell
bazelisk build  @org_tensorflow//tensorflow/lite:tflite_with_xnnpack --config=elinux_armhf
```
```


### Relevant log output

```shell
ERROR: /home/lgeiger/.cache/bazel/_bazel_lgeiger/8da1bfbfd9537ea4f19db64e1f55bee4/external/XNNPACK/BUILD.bazel:8896:19: Compiling src/qs8-vcvt/gen/vcvt-armv6simd-x8.c failed: (Exit 1): arm-linux-gnueabihf-gcc failed: error executing command /home/lgeiger/.cache/bazel/_bazel_lgeiger/8da1bfbfd9537ea4f19db64e1f55bee4/external/armhf_linux_toolchain/bin/arm-linux-gnueabihf-gcc -fstack-protector -g0 -O2 -DNDEBUG -ffunction-sections ... (remaining 83 arguments skipped)
external/XNNPACK/src/qs8-vcvt/gen/vcvt-armv6simd-x8.c: In function 'xnn_qs8_vcvt_ukernel__armv6simd_x8':
external/XNNPACK/src/qs8-vcvt/gen/vcvt-armv6simd-x8.c:26:9: error: unknown type name 'int16x2_t'
   const int16x2_t vminus_input_zero_point = (int16x2_t) params->armv6simd.minus_input_zero_point;
         ^~~~~~~~~
external/XNNPACK/src/qs8-vcvt/gen/vcvt-armv6simd-x8.c:26:46: error: 'int16x2_t' undeclared (first use in this function); did you mean 'int16_t'?
   const int16x2_t vminus_input_zero_point = (int16x2_t) params->armv6simd.minus_input_zero_point;
                                              ^~~~~~~~~
                                              int16_t
external/XNNPACK/src/qs8-vcvt/gen/vcvt-armv6simd-x8.c:26:46: note: each undeclared identifier is reported only once for each function it appears in
external/XNNPACK/src/qs8-vcvt/gen/vcvt-armv6simd-x8.c:26:57: error: expected ',' or ';' before 'params'
   const int16x2_t vminus_input_zero_point = (int16x2_t) params->armv6simd.minus_input_zero_point;
                                                         ^~~~~~
external/XNNPACK/src/qs8-vcvt/gen/vcvt-armv6simd-x8.c:30:11: error: unknown type name 'int8x4_t'
     const int8x4_t vx0123 = (int8x4_t) unaligned_indexed_load_u32(x, 0);
           ^~~~~~~~
external/XNNPACK/src/qs8-vcvt/gen/vcvt-armv6simd-x8.c:30:30: error: 'int8x4_t' undeclared (first use in this function); did you mean 'int64_t'?
     const int8x4_t vx0123 = (int8x4_t) unaligned_indexed_load_u32(x, 0);
                              ^~~~~~~~
                              int64_t
external/XNNPACK/src/qs8-vcvt/gen/vcvt-armv6simd-x8.c:30:40: error: expected ',' or ';' before 'unaligned_indexed_load_u32'
     const int8x4_t vx0123 = (int8x4_t) unaligned_indexed_load_u32(x, 0);
                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
external/XNNPACK/src/qs8-vcvt/gen/vcvt-armv6simd-x8.c:31:20: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'vx4567'
     const int8x4_t vx4567 = (int8x4_t) unaligned_indexed_load_u32(x, 1);
                    ^~~~~~
external/XNNPACK/src/qs8-vcvt/gen/vcvt-armv6simd-x8.c:31:20: error: 'vx4567' undeclared (first use in this function)
external/XNNPACK/src/qs8-vcvt/gen/vcvt-armv6simd-x8.c:31:39: error: expected ';' before 'unaligned_indexed_load_u32'
     const int8x4_t vx4567 = (int8x4_t) unaligned_indexed_load_u32(x, 1);
                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                                       ;
external/XNNPACK/src/qs8-vcvt/gen/vcvt-armv6simd-x8.c:34:21: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'vx02'
     const int16x2_t vx02 = __sxtab16(vminus_input_zero_point, vx0123);
                     ^~~~
external/XNNPACK/src/qs8-vcvt/gen/vcvt-armv6simd-x8.c:34:21: error: 'vx02' undeclared (first use in this function); did you mean 'vx0123'?
     const int16x2_t vx02 = __sxtab16(vminus_input_zero_point, vx0123);
                     ^~~~
                     vx0123
external/XNNPACK/src/qs8-vcvt/gen/vcvt-armv6simd-x8.c:35:21: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'vx13'
     const int16x2_t vx13 = __sxtab16(vminus_input_zero_point, __ror(vx0123, 8));
                     ^~~~
external/XNNPACK/src/qs8-vcvt/gen/vcvt-armv6simd-x8.c:35:21: error: 'vx13' undeclared (first use in this function); did you mean 'vx0123'?
     const int16x2_t vx13 = __sxtab16(vminus_input_zero_point, __ror(vx0123, 8));
                     ^~~~
                     vx0123
external/XNNPACK/src/qs8-vcvt/gen/vcvt-armv6simd-x8.c:36:21: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'vx46'
     const int16x2_t vx46 = __sxtab16(vminus_input_zero_point, vx4567);
                     ^~~~
external/XNNPACK/src/qs8-vcvt/gen/vcvt-armv6simd-x8.c:36:21: error: 'vx46' undeclared (first use in this function)
external/XNNPACK/src/qs8-vcvt/gen/vcvt-armv6simd-x8.c:37:21: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'vx57'
     const int16x2_t vx57 = __sxtab16(vminus_input_zero_point, __ror(vx4567, 8));
                     ^~~~
external/XNNPACK/src/qs8-vcvt/gen/vcvt-armv6simd-x8.c:37:21: error: 'vx57' undeclared (first use in this function)
external/XNNPACK/src/qs8-vcvt/gen/vcvt-armv6simd-x8.c:68:20: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'vx0123'
     const int8x4_t vx0123 = (int8x4_t) unaligned_load_u32(x);
                    ^~~~~~
external/XNNPACK/src/qs8-vcvt/gen/vcvt-armv6simd-x8.c:68:20: error: 'vx0123' undeclared (first use in this function)
external/XNNPACK/src/qs8-vcvt/gen/vcvt-armv6simd-x8.c:68:39: error: expected ';' before 'unaligned_load_u32'
     const int8x4_t vx0123 = (int8x4_t) unaligned_load_u32(x);
                                       ^~~~~~~~~~~~~~~~~~~
                                       ;
external/XNNPACK/src/qs8-vcvt/gen/vcvt-armv6simd-x8.c:71:21: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'vx02'
     const int16x2_t vx02 = __sxtab16(vminus_input_zero_point, vx0123);
                     ^~~~
external/XNNPACK/src/qs8-vcvt/gen/vcvt-armv6simd-x8.c:72:21: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'vx13'
     const int16x2_t vx13 = __sxtab16(vminus_input_zero_point, __ror(vx0123, 8));
                     ^~~~
external/XNNPACK/src/qs8-vcvt/gen/vcvt-armv6simd-x8.c:91:20: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'vx0123'
     const int8x4_t vx0123 = (int8x4_t) unaligned_load_u32(x);
                    ^~~~~~
external/XNNPACK/src/qs8-vcvt/gen/vcvt-armv6simd-x8.c:91:39: error: expected ';' before 'unaligned_load_u32'
     const int8x4_t vx0123 = (int8x4_t) unaligned_load_u32(x);
                                       ^~~~~~~~~~~~~~~~~~~
                                       ;
external/XNNPACK/src/qs8-vcvt/gen/vcvt-armv6simd-x8.c:93:21: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'vx02'
     const int16x2_t vx02 = __sxtab16(vminus_input_zero_point, vx0123);
                     ^~~~
external/XNNPACK/src/qs8-vcvt/gen/vcvt-armv6simd-x8.c:94:21: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'vx13'
     const int16x2_t vx13 = __sxtab16(vminus_input_zero_point, __ror(vx0123, 8));
                     ^~~~
Target //tensorflow/lite:tflite_with_xnnpack failed to build
```
</details>

**Comment by mohantym** [comment]
@sachinprasadhs !

Could you look at this issue . 
It is passing in [2.9](https://colab.sandbox.google.com/gist/mohantym/6ab81dc34c85e5fb0856d2e98ed688a2/tensorflow-ranking.ipynb#scrollTo=skRg4_WPi616) and failing in [master](https://colab.sandbox.google.com/gist/mohantym/1694a4841773864b871152838db72de2/tensorflow-ranking.ipynb#scrollTo=tlf7PgzQ2JtS).

Thank you!

**Comment by sachinprasadhs** [comment]
This seems to be included in the commit here https://github.com/tensorflow/tensorflow/commit/4ec84aa99372ca7899fb12715edd2bfe3c947c88, could you please try to downgrade the bazel version to 5.0 or 4.2.1 and let us know if that works. Thanks!

**Comment by lgeiger** [comment]
@sachinprasadhs Thanks for the fast reply.

> could you please try to downgrade the bazel version to 5.0 or 4.2.1 and let us know if that works

Tensorflow 2.10 and newer is not compatible with Bazel 5.0. It requires [5.1.1 as mentioned here](https://github.com/tensorflow/tensorflow/blob/v2.10.0-rc2/.bazelrc). Trying to build with 5.0.0 gives the following unrelated error:
```
ERROR: /home/lgeiger/tensorflow/tensorflow/BUILD:1034:21: //tensorflow:libtensorflow_framework.so.2.10.0: no such attribute 'shared_lib_name' in 'cc_shared_library' rule
ERROR: /home/lgeiger/tensorflow/tensorflow/BUILD:1034:21: //tensorflow:libtensorflow_framework.so.2.10.0: no such attribute 'win_def_file' in 'cc_shared_library' rule
ERROR: /home/lgeiger/tensorflow/tensorflow/BUILD:1034:21: //tensorflow:libtensorflow_framework.2.10.0.dylib: no such attribute 'shared_lib_name' in 'cc_shared_library' rule
ERROR: /home/lgeiger/tensorflow/tensorflow/BUILD:1034:21: //tensorflow:libtensorflow_framework.2.10.0.dylib: no such attribute 'win_def_file' in 'cc_shared_library' rule
ERROR: /home/lgeiger/tensorflow/tensorflow/BUILD:1034:21: //tensorflow:tensorflow_framework.dll: no such attribute 'shared_lib_name' in 'cc_shared_library' rule
ERROR: /home/lgeiger/tensorflow/tensorflow/BUILD:1034:21: //tensorflow:tensorflow_framework.dll: no such attribute 'win_def_file' in 'cc_shared_library' rule
ERROR: /home/lgeiger/tensorflow/tensorflow/BUILD:1156:21: //tensorflow:libtensorflow_cc.so.2.10.0: no such attribute 'shared_lib_name' in 'cc_shared_library' rule
ERROR: /home/lgeiger/tensorflow/tensorflow/BUILD:1156:21: //tensorflow:libtensorflow_cc.so.2.10.0: no such attribute 'win_def_file' in 'cc_shared_library' rule
ERROR: /home/lgeiger/tensorflow/tensorflow/BUILD:1156:21: //tensorflow:libtensorflow_cc.2.10.0.dylib: no such attribute 'shared_lib_name' in 'cc_shared_library' rule
ERROR: /home/lgeiger/tensorflow/tensorflow/BUILD:1156:21: //tensorflow:libtensorflow_cc.2.10.0.dylib: no such attribute 'win_def_file' in 'cc_shared_library' rule
ERROR: /home/lgeiger/tensorflow/tensorflow/BUILD:1156:21: //tensorflow:tensorflow_cc.dll: no such attribute 'shared_lib_name' in 'cc_shared_library' rule
ERROR: /home/lgeiger/tensorflow/tensorflow/BUILD:1156:21: //tensorflow:tensorflow_cc.dll: no such attribute 'win_def_file' in 'cc_shared_library' rule
ERROR: /home/lgeiger/tensorflow/tensorflow/lite/BUILD:736:11: errors encountered resolving select() keys for //tensorflow/lite:tflite_with_xnnpack
ERROR: Analysis of target '//tensorflow/lite:tflite_with_xnnpack' failed; build aborted: 
```
And bazel 4.2.1 fails with even more bazel version related errors.

I am not sure whether this is really related to 4ec84aa99372ca7899fb12715edd2bfe3c947c88 since it was already included in TF 2.9.0 which builds correctly. To me it looks more like an update in XNNPACK broke the build with the `elinux_armhf` config.

**Comment by sachinprasadhs** [comment]
I see, thanks for clarifying. Will look into it in detail.

**Comment by lgeiger** [comment]
Looks like the build failure is due to the outdated GCC 8.3 based Embedded Linux toolchain. Upgrading to GCC 11.3.1 fixed this. I opened #57585 which seems to fix this issue.
