### ISSUE TITLE
wide_n_deep tutorial issues

### ISSUE THREAD

**Issue by stevehorn** [tensorflow/tensorflow#6648]
Please help. Running into an issue running the wide_n_deep.py tutorial.

**Tensorflow Version:**
$ python -c 'import tensorflow as tf; print(tf.__version__)'  # for Python 2
=> 0.12.1

**wide_n_deep_tutorial.py was downloaded from here:** https://raw.githubusercontent.com/tensorflow/tensorflow/master/tensorflow/examples/learn/wide_n_deep_tutorial.py)

**Command and output**
$ python wide_n_deep_tutorial.py --model_type=wide
=>
```
Training data is downloaded to /var/folders/7y/s1y_wxt93xj5l784mcn2sf380000gn/T/tmpvWXvU2
Test data is downloaded to /var/folders/7y/s1y_wxt93xj5l784mcn2sf380000gn/T/tmpL4LH0x
model directory = /var/folders/7y/s1y_wxt93xj5l784mcn2sf380000gn/T/tmpFbBGZe
WARNING:tensorflow:The default value of combiner will change from "sum" to "sqrtn" after 2016/11/01.
WARNING:tensorflow:The default value of combiner will change from "sum" to "sqrtn" after 2016/11/01.
WARNING:tensorflow:The default value of combiner will change from "sum" to "sqrtn" after 2016/11/01.
WARNING:tensorflow:The default value of combiner will change from "sum" to "sqrtn" after 2016/11/01.
WARNING:tensorflow:The default value of combiner will change from "sum" to "sqrtn" after 2016/11/01.
WARNING:tensorflow:The default value of combiner will change from "sum" to "sqrtn" after 2016/11/01.
WARNING:tensorflow:The default value of combiner will change from "sum" to "sqrtn" after 2016/11/01.
WARNING:tensorflow:The default value of combiner will change from "sum" to "sqrtn" after 2016/11/01.
WARNING:tensorflow:The default value of combiner will change from "sum" to "sqrtn" after 2016/11/01.
WARNING:tensorflow:The default value of combiner will change from "mean" to "sqrtn" after 2016/11/01.
WARNING:tensorflow:The default value of combiner will change from "mean" to "sqrtn" after 2016/11/01.
WARNING:tensorflow:The default value of combiner will change from "mean" to "sqrtn" after 2016/11/01.
WARNING:tensorflow:The default value of combiner will change from "mean" to "sqrtn" after 2016/11/01.
WARNING:tensorflow:The default value of combiner will change from "mean" to "sqrtn" after 2016/11/01.
WARNING:tensorflow:The default value of combiner will change from "mean" to "sqrtn" after 2016/11/01.
WARNING:tensorflow:From /usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/linear.py:446 in fit.: calling fit (from tensorflow.contrib.learn.python.learn.estimators.estimator) with x is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:From /usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/linear.py:446 in fit.: calling fit (from tensorflow.contrib.learn.python.learn.estimators.estimator) with y is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:From /usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/linear.py:446 in fit.: calling fit (from tensorflow.contrib.learn.python.learn.estimators.estimator) with batch_size is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
Traceback (most recent call last):
  File "wide_n_deep_tutorial.py", line 208, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "wide_n_deep_tutorial.py", line 204, in main
    train_and_eval()
  File "wide_n_deep_tutorial.py", line 197, in train_and_eval
    m.fit(input_fn=lambda: input_fn(df_train), steps=FLAGS.train_steps)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/linear.py", line 446, in fit
    max_steps=max_steps)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 191, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 355, in fit
    max_steps=max_steps)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 690, in _train_model
    features, labels = input_fn()
  File "wide_n_deep_tutorial.py", line 197, in <lambda>
    m.fit(input_fn=lambda: input_fn(df_train), steps=FLAGS.train_steps)
  File "wide_n_deep_tutorial.py", line 159, in input_fn
    for k in CATEGORICAL_COLUMNS}
  File "wide_n_deep_tutorial.py", line 159, in <dictcomp>
    for k in CATEGORICAL_COLUMNS}
TypeError: __init__() got an unexpected keyword argument 'dense_shape'
```

**Running on Mac Sierra**

**Comment by as1ndu** [comment]
Am having the exact same issue [#6591](https://github.com/tensorflow/tensorflow/issues/6591) am on Ubuntu 16.04 LTS x64

**Comment by nagachika** [comment]
Try the example on the v0.12 branch.

https://github.com/tensorflow/tensorflow/blob/r0.12/tensorflow/examples/learn/wide_n_deep_tutorial.py

tf.TensorShape has breaking change in master branch (rename argument shape -> dense_shape. see https://groups.google.com/a/tensorflow.org/forum/?utm_medium=email&utm_source=footer#!msg/discuss/OePXmC9kJ7o/SRErOoYCDQAJ for more other API changes), and the examples catch up these changes. So examples in master branch could not work with 0.12 or older TensorFlow runtime.

**Comment by stevehorn** [comment]
@nagachika yes I am able to run with the tutorial code from the v0.12 branch. Thanks!
