### ISSUE TITLE
r1.13 multi-gpu towering fails due to DeviceSpec parsing during model creation

### ISSUE THREAD

**Issue by mmajurski** [tensorflow/tensorflow#27259]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): This is a custom written yolov3 model written primarily with the tf.layers api which is soon to deprecated. 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 & Power9
- TensorFlow installed from (source or binary): compiled from r1.13 source branch and Conda tensorflow-gpu package from https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/
- TensorFlow version (use command below): 1.13.1
- Python version: 3.6
- Bazel version (if compiling from source): 0.18.1
- GCC/Compiler version (if compiling from source): 7.3.0
- CUDA/cuDNN version: Cuda 10.0 CuDNN 7.5 NCCL 2.4
- GPU model and memory: GT 1080 Ti 12GB and V100 16GB

**Describe the current behavior**
Under Tensorflow r1.13 my single node multi-gpu training code produces a 
```
splits = [x.split(":") for x in spec.split("/")]
AttributeError: 'DeviceSpec' object has no attribute 'split'
```

Error when constructing the model, before a single forward pass has happened.

The towering code I am using is based on the cifar10_multi_gpu_train.py example:
https://github.com/petewarden/tensorflow_makefile/blob/master/tensorflow/models/image/cifar10/cifar10_multi_gpu_train.py

**Describe the expected behavior**
My codebase works correctly on Tensroflow r1.12

Given the error and my reading of the tensorflow source code throwing the error, my best guess is some op is missing/has a malformed device_spec, or a deivce_spec object is being passed into the `DeviceSpec().parse_from_string(spec)` function. 

The layer that seems to be generating this (see trace below) is 
```
tf.layers.conv2d_transpose
``` 

I am using several: `tf.device('/cpu:0')` and `tf.device('/gpu:#')` statements to control the placement of ops within different towers onto specific devices. and the problematic `tf.layers.conv2d_transpose` is happening once per tower under a 
```with tf.device('/gpu:#'):``` However, if this error were tied to my mishandling of those control statements the many layers of the model that get added before `tf.layers.conv2d_transpose` would have caused an error. 

These issues in the past seem somewhat relevant, but they all refer to much older source code for tensorflow, and this is a change since r1.12. So I am not putting much stock in any of the discussion from these issues:
- https://github.com/keras-team/keras/issues/10008
- https://github.com/keras-team/keras/issues/10490

Does anyone have any pointers where I could look for solutions? My entire codebase will be shifting to tf2.0 api once thats out of alpha. However, it is my understanding that model data parallel training is not fully operational at this time for custom models (non tf.keras.models.Sequential models).

**Other info / logs**
```
Creating model
Building model towers
  tower 0
    building feature map
shutdown complete
  File "train_yolo.py", line 348, in <module>
    train_model()
  File "train_yolo.py", line 169, in train_model
    train_op, all_loss_total_op, all_loss_xy_op, all_loss_wh_op, all_loss_objectness_op, all_loss_class_op, ops_per_gpu, train_init_op, test_init_op, is_training_placeholder = yolov3.build_towered_model(train_reader, test_reader, GPU_IDS, LEARNING_RATE)
  File "/fs/wrk/mmajursk/yolov3/src/yolov3.py", line 562, in build_towered_model
    outputs, total_loss_op, loss_xy_op, loss_wh_op, loss_objectness_op, loss_class_op = tower_loss(image_batch, label_batch, is_training_placeholder)
  File "/fs/wrk/mmajursk/yolov3/src/yolov3.py", line 464, in tower_loss
    pred_feature_map, outputs = add_inference_ops(images, is_training=is_training)
  File "/fs/wrk/mmajursk/yolov3/src/yolov3.py", line 446, in add_inference_ops
    pred_feature_map = build_feature_maps(images, is_training=is_training)
  File "/fs/wrk/mmajursk/yolov3/src/yolov3.py", line 211, in build_feature_maps
    inputs = upsample_2x(inputs)
  File "/fs/wrk/mmajursk/yolov3/src/yolov3.py", line 168, in upsample_2x
    trainable=False)  
  File "/home/mmajursk/.conda/envs/tf/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/mmajursk/.conda/envs/tf/lib/python3.6/site-packages/tensorflow/python/layers/convolutional.py", line 1279, in conv2d_transpose
    return layer.apply(inputs)
  File "/home/mmajursk/.conda/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1227, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/home/mmajursk/.conda/envs/tf/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 530, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/home/mmajursk/.conda/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 554, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/mmajursk/.conda/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/layers/convolutional.py", line 832, in call
    dilation_rate=self.dilation_rate)
  File "/home/mmajursk/.conda/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 4267, in conv2d_transpose
    x, tf_data_format = _preprocess_conv2d_input(x, data_format, force_transpose)
  File "/home/mmajursk/.conda/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 4082, in _preprocess_conv2d_input
    if not _has_nchw_support() or force_transpose:
  File "/home/mmajursk/.conda/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 592, in _has_nchw_support
    explicitly_on_cpu = _is_current_explicit_device('CPU')
  File "/home/mmajursk/.conda/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 561, in _is_current_explicit_device
    device = _get_current_tf_device()
  File "/home/mmajursk/.conda/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 541, in _get_current_tf_device
    graph._apply_device_functions(op)
  File "/home/mmajursk/.conda/envs/tf/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 4246, in _apply_device_functions
    op._set_device(device_spec.function(op))
  File "/home/mmajursk/.conda/envs/tf/lib/python3.6/site-packages/tensorflow/python/framework/device.py", line 314, in _device_function
    current_device = DeviceSpec.from_string(node_def.device or "")
  File "/home/mmajursk/.conda/envs/tf/lib/python3.6/site-packages/tensorflow/python/framework/device.py", line 232, in from_string
    return DeviceSpec().parse_from_string(spec)
  File "/home/mmajursk/.conda/envs/tf/lib/python3.6/site-packages/tensorflow/python/framework/device.py", line 150, in parse_from_string
    splits = [x.split(":") for x in spec.split("/")]
AttributeError: 'DeviceSpec' object has no attribute 'split'
```

Thanks for any help/insights you can provide.
~Michael

**Comment by ppwwyyxx** [comment]
This issue has the same cause as #27259: TF1.13 switch the implementation of `tf.layers.conv2d_transpose` to Keras and the new implementation interacts with devices in a wrong way.

Now I have moved my code to use my own implementation of conv2d_transpose instead while waiting for responses.

**Comment by mmajurski** [comment]
@ppwwyyxx Would you be willing to share your conv2d_transpose code?

**Comment by ppwwyyxx** [comment]
https://github.com/tensorpack/tensorpack/blob/d48cce3aa399db11a4e6fc35a5a896c96a92b641/tensorpack/models/conv2d.py#L205
It has quite some dependencies, though

**Comment by dkuegler** [comment]
Probably should have commented here, but alas: 
I did a bit of digging and working in https://github.com/tensorflow/tensorflow/pull/23197 including a minimal working example of sorts.

**Comment by robieta** [comment]
I believe that this is coming from the fact that `_TfDeviceCaptureOp` is capturing the device as a DeviceSpec, whereas tf Operations capture it as a string. I'm currently working on a cleanup in the device code, and I'll make sure that this gets remedied in that refactor.

**Comment by robieta** [comment]
Can you check whether this has been resolved? (You will need a recent tensorflow; for instance building from head or using the latest `tf-nightly-gpu`)

**Comment by mmajurski** [comment]
I was unable to compile from the latest master branch. I got a nccl compile error. The error persisted when I tried to turn on nccl support in the bazel build.

```
ERROR: /home/mmajursk/.cache/bazel/_bazel_mmajursk/6141fa2ddcb6e0f90a8f011edd6ceac9/external/nccl_archive/BUILD.bazel:67:1: error while parsing .d file: /home/mmajursk/.cache/bazel/_bazel_mmajursk/6141fa2ddcb6e0f90a8f011edd6ceac9/execroot/org_tensorflow/bazel-out/host/bin/external/nccl_archive/_objs/device_lib/max_all_reduce.cu.pic.d (No such file or directory)
In file included from <command-line>:0:0:
/usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_runtime.h:83:10: fatal error: crt/host_config.h: No such file or directory
 #include "crt/host_config.h"
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 4.786s, Critical Path: 0.57s
INFO: 29 processes: 29 local.
FAILED: Build did NOT complete successfully
```

Moving on, I was able to successfully install tf-nightly-gpu into a brand new python venv.

Running the same code that generated the original error now results in a different error.

```
Running Network
---- Epoch: 0 ----
initializing training data iterator
   iterator init complete
Training:
shutdown complete
Traceback (most recent call last):
  File "/home/mmajursk/envs/tfn/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1339, in _do_call
    return fn(*args)
  File "/home/mmajursk/envs/tfn/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1324, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/mmajursk/envs/tfn/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1412, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: No unary variant device copy function found for direction: 1 and Variant type_index: tensorflow::data::(anonymous namespace)::DatasetVariantWrapper
	 [[{{node n/_3}}]]
	 [[tower_0/IteratorGetNext]]
	 [[all_loss_wh/_49]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_yolo.py", line 353, in <module>
    train_model()
  File "train_yolo.py", line 227, in train_model
    _, loss_total, loss_xy, loss_wh, loss_objectness, loss_class = sess.run([train_op, all_loss_total_op, all_loss_xy_op, all_loss_wh_op, all_loss_objectness_op, all_loss_class_op], feed_dict={is_training_placeholder: True})
  File "/home/mmajursk/envs/tfn/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 933, in run
    run_metadata_ptr)
  File "/home/mmajursk/envs/tfn/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1156, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/mmajursk/envs/tfn/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1333, in _do_run
    run_metadata)
  File "/home/mmajursk/envs/tfn/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1353, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: No unary variant device copy function found for direction: 1 and Variant type_index: tensorflow::data::(anonymous namespace)::DatasetVariantWrapper
	 [[{{node n/_3}}]]
	 [[tower_0/IteratorGetNext]]
	 [[all_loss_wh/_49]]
```

Since this error is coming from the Dataset api, I think it has to do with API changes breaking my I/O pipeline. So I am cautiously optimistic that the underlying bug is fixed. Unlike before, my training script is able to fully construct the towered network. Previously the error occured during model construction, well before any data was fed into the network. This new error occurs when my first batch of data is being handed to the network, indicating that the model was able to be successfully constructed. 

I don't have time right now to dig into fixing my new error, but I will try to update this post next week if I can work around the new Dataset error.

Thank you

**Comment by BEEugene** [comment]
@mmajurski, hi! Could you please provide the workaround?

**Comment by mmajurski** [comment]
@BEEugene My workaround was to never upgrade tensorflow beyond 1.12.

I also moved to TF2.0 which has an entirely different parallelization mechanism with distribution strategies.

**Comment by WangShuaixian** [comment]
open  /tensorflow/python/framework/device.py

change line314  `current_device = DeviceSpec.from_string(node_def.device or "")` to 
`current_device = node_def.device if isinstance(node_def.device, DeviceSpec) else DeviceSpec.from_string(node_def.device or "")`

**Comment by dkuegler** [comment]
> open /tensorflow/python/framework/device.py
> 
> change line314 `current_device = DeviceSpec.from_string(node_def.device or "")` to
> `current_device = node_def.device if isinstance(node_def.device, DeviceSpec) else DeviceSpec.from_string(node_def.device or "")`

This is the same solution that worked for me https://github.com/tensorflow/tensorflow/pull/23197#issuecomment-478297037

**Comment by rmothukuru** [comment]
@mmajurski,
 Can we close this issue as it is resolved by using **`Tensorflow Version 2.x`**, as per [this comment](https://github.com/tensorflow/tensorflow/issues/27259#issuecomment-525301138) and as per [this comment](https://github.com/tensorflow/tensorflow/issues/27259#issuecomment-570552675)?

**Comment by mmajurski** [comment]
This issue can absolutely be closed. It was obsoleted with the full transition to Tensorflow 2.x.
