### ISSUE TITLE
using bazel to build tensorflow.dll

### ISSUE THREAD

**Issue by taotaolin** [tensorflow/tensorflow#22338]
i try using bazel to build on windows, but tips:

**Have I written custom code** No
**OS Platform and Distribution** WIN7 Visual Studio 2015
**TensorFlow installed from** source master
**Bazel version** 0.17.1
**CUDA/cuDNN version** CUDA9.0 / CUDNN 7.2.1
**GPU model and memory** 1080Ti / 11G
**Mobile device** N/A
**Exact command to reproduce**
1. python ./configure.py
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/C:/U
sers/tao/_bazel_tao/install/360a69cc0fef41d83a4dd948c0474ca5/_embedded_binaries/
A-server.jar) to field java.lang.String.value
WARNING: Please consider reporting this to the maintainers of com.google.protobu
f.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflect
ive access operations
WARNING: All illegal access operations will be denied in a future release
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Ba
zel server using the command "bazel shutdown".
You have bazel 0.17.1 installed.
Please specify the location of python. [Default is C:\Users\tao\AppData\Local\Pr
ograms\Python\Python35\python.exe]:

Found possible Python library paths:
  C:\Users\tao\AppData\Local\Programs\Python\Python35\lib\site-packages
Please input the desired Python library path to use.  Default is [C:\Users\tao\A
ppData\Local\Programs\Python\Python35\lib\site-packages]

Do you wish to build TensorFlow with nGraph support? [y/N]:
No nGraph support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Please specify the CUDA SDK version you want to use. [Leave empty to default to
CUDA 9.0]:

Please specify the location where CUDA 9.0 toolkit is installed. Refer to README
.md for more details. [Default is C:/Program Files/NVIDIA GPU Computing Toolkit/
CUDA/v9.0]:


Please specify the cuDNN version you want to use. [Leave empty to default to cuD
NN 7.0]:


Please specify the location where cuDNN 7 library is installed. Refer to README.
md for more details. [Default is C:/Program Files/NVIDIA GPU Computing Toolkit/C
UDA/v9.0]:

Please specify a list of comma-separated Cuda compute capabilities you want to b
uild with.
You can find the compute capability of your device at: https://developer.nvidia.
com/cuda-gpus.
Please note that each additional compute capability significantly increases your
 build time and binary size. [Default is: 3.5,7.0]:

Please specify optimization flags to use during compilation when bazel option "-
-config=opt" is specified [Default is /arch:AVX]:

Would you like to override eigen strong inline for some C++ compilation to reduc
e the compilation time? [Y/n]:
Eigen strong inline overridden.
```

2.bazel build --config=opt --config=cuda //tensorflow:libtensorflow.so
```
bazel build --config=opt --config=cuda //tensorflow:libtensorflow.so will be generated tensorflow.so and tensorflow.lib ?
```
Then rename the libtensorflow.so to tensorflow.dll, it can be work? @meteorcloudy

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
TensorFlow version

**Comment by taotaolin** [comment]
> Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
> TensorFlow version

**TensorFlow version**   master   maybe r1.10

**Comment by meteorcloudy** [comment]
Yes, it should work.

**Comment by meteorcloudy** [comment]
You might find this script useful:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/windows/libtensorflow_cpu.sh

**Comment by taotaolin** [comment]
> You might find this script useful:
> https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/windows/libtensorflow_cpu.sh

How should I choose to compile the debug version or the realse version?

**Comment by taotaolin** [comment]
i try using `bazel build --config=fastbuild --config=cuda //tensorflow:libtensorflow.so` or `bazel build --config=debug --config=cuda //tensorflow:libtensorflow.so` but it's have some mistake, tips:
```
ERROR: Config value fastbuild is not defined in any .rc file   
or 
ERROR: Config value debug is not defined in any .rc file
```

**Comment by meteorcloudy** [comment]
Sorry, I meant you need to pass `-c debug` or `-c fastbuild`, it's different from `--config`

**Comment by taotaolin** [comment]
> fastbuild

Thank you  very much

**Comment by taotaolin** [comment]
> Sorry, I meant you need to pass `-c debug` or `-c fastbuild`, it's different from `--config`
 realse version can sucess build, but debug version tops:
```
脳垄脪芒: 掳眉潞卢脦脛录镁:      C:\Program Files (x86)\Microsoft Visual Studio
14.0\VC\INCLUDE\thread
脳垄脪芒: 掳眉潞卢脦脛录镁:       C:\Program Files (x86)\Microsoft Visual Studio
 14.0\VC\INCLUDE\memory
脳垄脪芒: 掳眉潞卢脦脛录镁:    C:\users\tao\_bazel_tao\ic7qrvhc\execroot\org_ten
sorflow\tensorflow/core/platform/thread_annotations.h
脳垄脪芒: 掳眉潞卢脦脛录镁:     C:\users\tao\_bazel_tao\ic7qrvhc\execroot\org_te
nsorflow\tensorflow/core/platform/default/thread_annotations.h
c:\users\tao\_bazel_tao\ic7qrvhc\execroot\org_tensorflow\tensorflow\core\lib\io\
path.cc(290) : error C4716: 隆掳tensorflow::io::GetTempFilename隆卤: 卤脴脨毛路
碌禄脴脪禄赂枚脰碌
Target //tensorflow:libtensorflow.so failed to build
INFO: Elapsed time: 439.737s, Critical Path: 427.30s
INFO: 806 processes: 806 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

**Comment by Croolman** [comment]
I have very similar issue:

**Have I written custom code** No
**OS Platform and Distribution** WIN10 Visual Studio 2015
**TensorFlow installed from** stable release v1.10.1.0
**Bazel version** 0.17.1
**CUDA/cuDNN version** CUDA8.0 / CUDNN 7.0
**GPU model and memory** 1050Ti / 8G
**Mobile device**  N/A
**Exact command to reproduce**
 bazel build -c opt //tensorflow/tools/lib_package:libtensorflow
- ran after python ./configure.py

I have tried the script located in 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/windows/libtensorflow_gpu.sh --- the GPU version. Ended again after a long build with similiar error. Whole bunch of Eigen and protobuf errors.

**Comment by meteorcloudy** [comment]
@taotaolin Looks like this function `tensorflow::io::GetTempFilename` failed, can you show me what's the value of your `TEMP`, `TMP` environment variable?

**Comment by meteorcloudy** [comment]
@Croolman Can you provide the exact error message? 
Does https://github.com/tensorflow/tensorflow/issues/19198 seem to be related?

**Comment by Croolman** [comment]
@meteorcloudy The issue you re reffering to might be related.  The error message is way too long and it is hard to find the exact position where it started.

Way above, it starts with some INFO, but this should not be a problem

`bazel-out/x64_windows-opt/genfiles/external/protobuf_archive/src: warning: directory does not exist`

The final error message:

```
1 error detected in the compilation of "[...]/AppData/Local/Temp/nvcc_inter_files_tmp_dir/gather_functor_gpu.cu.cpp1.ii.
Target //tensorflow/tools/lib_package:libtensorflow failed to build
```

And before that a reoccuring pattern that looks like this - the no return at the nonvoid func:

```
[...]\eviletzq\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\src/SpecialFunctions/SpecialFunctionsImpl.h(651): warning: missing return statement at end of non-void function "Eigen::internal::igammac_cf_impl<Scalar, mode>::run [with Scalar=float, mode=Eigen::internal::DERIVATIVE]"
          detected during:
            instantiation of "Scalar Eigen::internal::igammac_cf_impl<Scalar, mode>::run(Scalar, Scalar) [with Scalar=float, mode=Eigen::internal::DERIVATIVE]"
(855): here
            instantiation of "Scalar Eigen::internal::igamma_generic_impl<Scalar, mode>::run(Scalar, Scalar) [with Scalar=float, mode=Eigen::internal::DERIVATIVE]"
(2102): here
```

**Comment by meteorcloudy** [comment]
@Croolman The error you showed here are warnings. You can redirect the output to a file and search for `error:`

**Comment by Croolman** [comment]
@meteorcloudy  Allrighty, this should be it

```
ERROR: [...]/tensorflow/tensorflow/core/kernels/BUILD:4245:1: C++ compilation of rule '//tensorflow/core/kernels:scatter_nd_op_gpu' failed (Exit 2): msvc_wrapper_for_nvcc.bat failed: error executing command 
  cd [...]/eviletzq/execroot/org_tensorflow
  SET CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0
    SET CUDNN_INSTALL_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0
    SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\winrt;
    SET LIB=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\um\x64;
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64;C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;;C:\WINDOWS\system32
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C:/Program Files/Anaconda3/python.exe
    SET PYTHON_LIB_PATH=C:/Program Files/Anaconda3/lib/site-packages
    SET TEMP=[...]\AppData\Local\Temp
    SET TF_CUDA_CLANG=0
    SET TF_CUDA_COMPUTE_CAPABILITIES=6.1
    SET TF_CUDA_VERSION=8.0
    SET TF_CUDNN_VERSION=7
    SET TF_NEED_CUDA=1
    SET TF_NEED_OPENCL_SYCL=0
    SET TMP=[...]\AppData\Local\Temp
```
The second one:
`  external/protobuf_archive/src\google/protobuf/arena.h(338): error: static assertion failed with "CreateArray requires a trivially destructible type"`

This first one seems like an incompatible configuration settings. The only extra thing I have set is the compute capability - 6.1. I have tried building it with default - 3.5 and 7.0 which yields `nvcc fatal   : Unsupported gpu architecture 'compute_70' ` That might be because of CUDA v8.0. Then I tried it with 5.0 and ended up with the same error as the first one again.

**Comment by meteorcloudy** [comment]
Can you try to build with CUDA v9.0? That is a known working version.

**Comment by taotaolin** [comment]
> @taotaolin Looks like this function `tensorflow::io::GetTempFilename` failed, can you show me what's the value of your `TEMP`, `TMP` environment variable?

What is TMP environment variable?My Realse version has been compiled successfully, and the Debug version has gone wrong. I think there should be no problem with environment variables.

**Comment by Croolman** [comment]
@meteorcloudy I cant really use cuda v9 in my enviroment, so I cannot try to build with v9

**Comment by taotaolin** [comment]
@meteorcloudy 
I tried to use the realse version of the dll file but an error message:
```
错误	LNK2019	无法解析的外部符号 "char const * __cdecl tensorflow::core::GetVarint32PtrFallback(char const *,char const *,unsigned int *)" (?GetVarint32PtrFallback@core@tensorflow@@YAPEBDPEBD0PEAI@Z)，该符号在函数 "char const * __cdecl tensorflow::core::GetVarint32Ptr(char const *,char const *,unsigned int *)" (?GetVarint32Ptr@core@tensorflow@@YAPEBDPEBD0PEAI@Z) 中被引用	ConsoleApplication1	C:\Users\tao\Desktop\tensorflow-test\ConsoleApplication1\ConsoleApplication1\ConsoleApplication1.obj	1	

```

**Comment by meteorcloudy** [comment]
I guess you need to add the import library to the link command.
Find this file `tensorflow\bazel-bin\tensorflow\libtensorflow.so.if.lib`

**Comment by taotaolin** [comment]
> I guess you need to add the import library to the link command.
> Find this file `tensorflow\bazel-bin\tensorflow\libtensorflow.so.if.lib`

i don't have `tensorflow\bazel-bin\tensorflow\libtensorflow.so.if.lib` file

**Comment by taotaolin** [comment]
> I guess you need to add the import library to the link command.
> Find this file `tensorflow\bazel-bin\tensorflow\libtensorflow.so.if.lib`

only `liblibtensorflow.so`  `liblibtensorflow.so.ifso` `libtensorflow.so` `libtensorflow.so-2.params` and `libtensorflow.so.runfiles_manifest`

**Comment by meteorcloudy** [comment]
Oh, you must be using an old version of Bazel?  `liblibtensorflow.so.ifso` is the import library you want.

**Comment by taotaolin** [comment]
> Oh, you must be using an old version of Bazel? `liblibtensorflow.so.ifso` is the import library you want.

I tried to rename the `liblibtensorflow.so.ifso` to ` libtensorflow.so.if.lib` and import it in Visual Studio, but this error still occurred.

**Comment by meteorcloudy** [comment]
@taotaolin Sorry, I'm not sure what the problem is exactly. But seems people are having lot of troubles to use TensorFlow's C++ library. I'll look into this a next few days, hopefully I can find a good solution for you.

**Comment by taotaolin** [comment]
> @taotaolin Sorry, I'm not sure what the problem is exactly. But seems people are having lot of troubles to use TensorFlow's C++ library. I'll look into this a next few days, hopefully I can find a good solution for you.

thanks

**Comment by yjcn** [comment]
I meet the same problem. @taotaolin @meteorcloudy @Roffild 
I use the `tensorflow\bazel-bin\tensorflow\libtensorflow.so.if.lib` in VS 2015. And there are errors.
` error LNK2001: 无法解析的外部符号 "private: void __cdecl tensorflow::Tensor::CopyFromInternal(class tensorflow::Tensor const &,class tensorflow::TensorShape const &)" (?CopyFromInternal@Tensor@tensorflow@@AEAAXAEBV12@AEBVTensorShape@2@@Z)`
Does anyone know how to use the libtensorflow_cc.so??

**Comment by meteorcloudy** [comment]
@yicn Can you provide your source code or a minimal repo of this error?

**Comment by yjcn** [comment]
@meteorcloudy  Of course. This is the test code.
```
#define _SCL_SECURE_NO_WARNINGS
#define NOMINMAX
#define COMPILER_MSVC

#include "tensorflow/cc/client/client_session.h"
#include "tensorflow/cc/ops/standard_ops.h"
#include "tensorflow/core/framework/tensor.h"

int main() {
	using namespace tensorflow;
	using namespace tensorflow::ops;
	Scope root = Scope::NewRootScope();
	auto A = Const(root, { { 3.f, 2.f },{ -1.f, 0.f } });
	auto b = Const(root, { { 3.f, 5.f } });
	auto v = MatMul(root.WithOpName("v"), A, b, MatMul::TransposeB(true));
	std::vector<Tensor> outputs;
	ClientSession session(root);
	TF_CHECK_OK(session.Run({ v }, &outputs));
	std::cout << outputs[0].matrix<float>();
	getchar();
	return 0;
}
```
I also compile the code with the tensorflow r1.4 's dll and lib which is built using cmake, and it works well.

**Comment by Croolman** [comment]
@meteorcloudy So I have tried to build it with CUDA 9.0 and I got similar error
```
ERROR: E:/tsf1.10/tensorflow/tensorflow/core/kernels/BUILD:775:1: C++ compilation of rule '//tensorflow/core/kernels:pad_op_gpu' failed (Exit 1): msvc_wrapper_for_nvcc.bat failed: error executing command 
  cd [...]/62ehlahw/execroot/org_tensorflow
  SET CUDA_TOOLKIT_PATH=E:/Programs/Nvidia
    SET CUDNN_INSTALL_PATH=E:/Programs/Nvidia
    SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt;
    SET LIB=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.17134.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.17134.0\um\x64;
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64;C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;;C:\WINDOWS\system32
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C:/Programs/Anaconda/python.exe
    SET PYTHON_LIB_PATH=C:/Programs/Anaconda/lib/site-packages
    SET TEMP=C:\Users\[...]\AppData\Local\Temp
    SET TF_CUDA_CLANG=0
    SET TF_CUDA_COMPUTE_CAPABILITIES=6.1
    SET TF_CUDA_VERSION=9.0
    SET TF_CUDNN_VERSION=7
    SET TF_NEED_CUDA=1
    SET TF_NEED_OPENCL_SYCL=0
    SET TMP=C:\Users\[...]\AppData\Local\Temp 
```

**Comment by meteorcloudy** [comment]
I believe only API defined in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/c_api.h are available. 
@EdwardVincentMa @Croolman Can you explain to me how did you build the library with CMake and how were you using it?

**Comment by taotaolin** [comment]
> I believe only API defined in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/c_api.h are available.
> @EdwardVincentMa @Croolman Can you explain to me how did you build the library with CMake and how were you using it?

I can use the 1.6 version of tensorflow to successfully compile with cmake and use the C++ API, but the bazel compiled dll files can only be used at  Functions defined in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/c_api.h

**Comment by EdwardVincentMa** [comment]
> > I believe only API defined in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/c_api.h are available.
> > @EdwardVincentMa @Croolman Can you explain to me how did you build the library with CMake and how were you using it?
> 
> I can use the 1.6 version of tensorflow to successfully compile with cmake and use the C++ API, but the bazel compiled dll files can only be used at Functions defined in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/c_api.h

TF 1.9+ has LKN error when using.

**Comment by EdwardVincentMa** [comment]
> > I believe only API defined in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/c_api.h are available.
> > @EdwardVincentMa @Croolman Can you explain to me how did you build the library with CMake and how were you using it?
> 
> I can use the 1.6 version of tensorflow to successfully compile with cmake and use the C++ API, but the bazel compiled dll files can only be used at Functions defined in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/c_api.h

兄弟你qq多少

**Comment by taotaolin** [comment]
> > > I believe only API defined in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/c_api.h are available.
> > > @EdwardVincentMa @Croolman Can you explain to me how did you build the library with CMake and how were you using it?
> > 
> > 
> > I can use the 1.6 version of tensorflow to successfully compile with cmake and use the C++ API, but the bazel compiled dll files can only be used at Functions defined in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/c_api.h
> 
> 兄弟你qq多少

`NzUyNzM5MDg2` base64解一下

**Comment by tensorflowbutler** [comment]
Nagging Assignee @meteorcloudy: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by dl8207531** [comment]
请问最后怎么解决的？@taotaolin

**Comment by taotaolin** [comment]
> 请问最后怎么解决的？@taotaolin

这个最新版没有解决。。装旧版本的tensorflow用cmake编译就可以解决这个问题

**Comment by guikarist** [comment]
I've worked on it for several days...

1. I must denote that if you want a C++ API library, you should build with '//tensorflow:libtensorflow_cc.so' instead of '//tensorflow:libtensorflow.so'.
1. Then you should encounter a problem like #23542 and somebody provide a way to solve it in [this comment](https://github.com/tensorflow/tensorflow/issues/22047#issuecomment-421452033). But I have no idea whether it is good or not.

**Comment by Steroes** [comment]
See my [post](https://github.com/tensorflow/tensorflow/issues/22047#issuecomment-447992343). Let me know if it doesnt work.

**Comment by yunghoy** [comment]
Some people in this thread still don't understand what OP said.
Most instructions in Tensorflow sites are saying about how to build "so" file, which is used for Linux or Unix system.
The question of OP is how to build "lib" or "dll" file by using Bazel for Windows system.

**Comment by Steroes** [comment]
Well, the topic description states that it is about building the library on windows. 
Bazel builds an so file, which is actually a dll. It also creates a lib file against which you can link with CMake. See my previous comment which links to the build scripts for windows (10).

**Comment by guikarist** [comment]
See my [comment](https://github.com/tensorflow/tensorflow/issues/7258#issuecomment-450802749) which provides a way to build on Windows.

**Comment by Steroes** [comment]
@guikarist Nice to see the acknowledgements. 
Nice cleanup of the script and parsing of the parameters by the way.

**Comment by matthewbundala** [comment]
@guikarist @Steroes Thank you for the script, it makes the environment preparation much easier. However, it does not address the original issue: if I try to compile the debug version (with `-c dbg` parameter), I get a `error C4716: 'tensorflow::io::GetTempFilename': must return a value` error - this happens regardless whether I use the script or not.

**Comment by guikarist** [comment]
@matthewbundala I have built without this flag but succeeded to use VS debug tools or build debug Tensorflow program.

**Comment by taotaolin** [comment]
@Steroes @guikarist Thank you for the script and i will try to compile the latest version again.

**Comment by guikarist** [comment]
@taotaolin This script cannot work on the latest Tensorflow. To be exact, it can only work on Tensorflow 1.11.0 at least now.

**Comment by guikarist** [comment]
> @meteorcloudy
> I tried to use the realse version of the dll file but an error message:
> 
> ```
> 错误	LNK2019	无法解析的外部符号 "char const * __cdecl tensorflow::core::GetVarint32PtrFallback(char const *,char const *,unsigned int *)" (?GetVarint32PtrFallback@core@tensorflow@@YAPEBDPEBD0PEAI@Z)，该符号在函数 "char const * __cdecl tensorflow::core::GetVarint32Ptr(char const *,char const *,unsigned int *)" (?GetVarint32Ptr@core@tensorflow@@YAPEBDPEBD0PEAI@Z) 中被引用	ConsoleApplication1	C:\Users\tao\Desktop\tensorflow-test\ConsoleApplication1\ConsoleApplication1\ConsoleApplication1.obj	1	
> ```

Have you resolved this problem? Which seems that it cannot be solved by [my solution](https://github.com/guikarist/tensorflow-windows-build-script#prerequisites) according to [this issue](https://github.com/guikarist/tensorflow-windows-build-script/issues/3).

**Comment by guikarist** [comment]
> This script cannot work on the latest Tensorflow. To be exact, it can only work on Tensorflow 1.11.0 at least now.

@taotaolin Now [the script](https://github.com/guikarist/tensorflow-windows-build-script) has supported Tensorflow 1.12.0!

**Comment by Roffild** [comment]
```error C4716: must return a value error```
https://github.com/tensorflow/tensorflow/blob/3751264e3a1a91159c68603476461dfe164e92ce/tensorflow/core/lib/io/path.cc#L255
https://github.com/tensorflow/tensorflow/blob/3751264e3a1a91159c68603476461dfe164e92ce/tensorflow/core/framework/device_base.cc#L28
https://github.com/tensorflow/tensorflow/blob/3751264e3a1a91159c68603476461dfe164e92ce/tensorflow/core/framework/device_base.cc#L32

**Comment by Steroes** [comment]
@Roffild Did you use the script from [here](https://github.com/guikarist/tensorflow-windows-build-script)?
I think you build in debug, is that correct. Debug is still not working properly.

**Comment by wangxuesong29** [comment]
@taotaolin hi. my question is how do we use tensorflow.dll? where can we find the functions inside?  Or can you share some example?

**Comment by guikarist** [comment]
@wangxuesong29 
Here is an example from [the official doc](https://www.tensorflow.org/guide/extend/cc):

```cpp
// tensorflow/cc/example/example.cc

#include "tensorflow/cc/client/client_session.h"
#include "tensorflow/cc/ops/standard_ops.h"
#include "tensorflow/core/framework/tensor.h"

int main() {
  using namespace tensorflow;
  using namespace tensorflow::ops;
  Scope root = Scope::NewRootScope();
  // Matrix A = [3 2; -1 0]
  auto A = Const(root, { {3.f, 2.f}, {-1.f, 0.f} });
  // Vector b = [3 5]
  auto b = Const(root, { {3.f, 5.f} });
  // v = Ab^T
  auto v = MatMul(root.WithOpName("v"), A, b, MatMul::TransposeB(true));
  std::vector<Tensor> outputs;
  ClientSession session(root);
  // Run and fetch v
  TF_CHECK_OK(session.Run({v}, &outputs));
  // Expect outputs[0] == [19; -3]
  LOG(INFO) << outputs[0].matrix<float>();
  return 0;
}
```

**Comment by taotaolin** [comment]
> @taotaolin嗨。我的问题是我们如何使用tensorflow.dll？我们在哪里可以找到里面的功能？或者你能分享一些例子吗？

I have an example of MNIST recognition, which I can show you tomorrow.

**Comment by taotaolin** [comment]
> @taotaolin hi. my question is how do we use tensorflow.dll? where can we find the functions inside? Or can you share some example?

Please tell me your contact information

**Comment by wangxuesong29** [comment]
@taotaolin wangxuesong29@gmail.com

Thanks.

**Comment by taotaolin** [comment]
> @taotaolin [wangxuesong29@gmail.com](mailto:wangxuesong29@gmail.com)
> 
> Thanks.

It's too big. I put the code on github. The data set is MNIST.

[https://github.com/taotaolin/MNIST_tensorflow_C](MNIST_tensorflow_C)

**Comment by taotaolin** [comment]
> > This script cannot work on the latest Tensorflow. To be exact, it can only work on Tensorflow 1.11.0 at least now.
> 
> @taotaolin Now [the script](https://github.com/guikarist/tensorflow-windows-build-script) has supported Tensorflow 1.12.0!

ERROR LNK2019 .  Have you resolved this problem? I don't seem to have solved this problem in the latest edition

**Comment by AndreyPlotkinOr** [comment]
@Roffild You may replace the fatal message with this code, and it will work:

#if defined(PLATFORM_WINDOWS)
  for (const char* dir : std::vector<const char*>(
           {getenv("TEST_TMPDIR"), getenv("TMPDIR"), getenv("TMP"), getenv("TEMP"), "/tmp"})) {
    if (!dir || !dir[0]) {
      continue;
    }
    struct stat statbuf;
    if (!stat(dir, &statbuf) && S_ISDIR(statbuf.st_mode)) {
      string tmp_filepath;
      tmp_filepath = io::JoinPath(
          dir,
          strings::StrCat("tmp_file_tensorflow_", UniqueId(), "_XXXXXX", extension));
	  //TODO Switch to secured method _mktemp_s
	  //int sizeInChars = strnlen(names[i], 9) + 1; 
	  //int err = _mktemp_s( names[i], sizeInChars );
      char* fd = _mktemp(&tmp_filepath[0]);
      if (fd == nullptr) {
        LOG(FATAL) << "Failed to create temp file.";
      } else {
        return tmp_filepath;
      }
    }
  }
  LOG(FATAL) << "No temp directory found.";

**Comment by yuc8939** [comment]
> `error C4716: must return a value error`
> https://github.com/tensorflow/tensorflow/blob/3751264e3a1a91159c68603476461dfe164e92ce/tensorflow/core/lib/io/path.cc#L255
> 
> 
> https://github.com/tensorflow/tensorflow/blob/3751264e3a1a91159c68603476461dfe164e92ce/tensorflow/core/framework/device_base.cc#L28
> 
> 
> https://github.com/tensorflow/tensorflow/blob/3751264e3a1a91159c68603476461dfe164e92ce/tensorflow/core/framework/device_base.cc#L32

I'm having this problem too. Simply does not compile on Windows. Do you finally have a solution?

**Comment by yuc8939** [comment]
You may add `--copt=/w34716` to the bazel build command line, e.g.
`bazel build --copt=/w34716 --experimental_shortened_obj_file_path //moco:moco`
This makes the MSVC compiler happy.
Inspired by: https://stackoverflow.com/a/11386226/12338026

> `error C4716: must return a value error`
> https://github.com/tensorflow/tensorflow/blob/3751264e3a1a91159c68603476461dfe164e92ce/tensorflow/core/lib/io/path.cc#L255
> 
> 
> https://github.com/tensorflow/tensorflow/blob/3751264e3a1a91159c68603476461dfe164e92ce/tensorflow/core/framework/device_base.cc#L28
> 
> 
> https://github.com/tensorflow/tensorflow/blob/3751264e3a1a91159c68603476461dfe164e92ce/tensorflow/core/framework/device_base.cc#L32

**Comment by kumariko** [comment]
@taotaolin We are checking to see if you still need help on this issue. We recommend that you upgrade to 2.6 which is latest stable version of TF and let us know if the issue still persists in newer versions. check comment: https://github.com/tensorflow/tensorflow/issues/22338#issuecomment-590247503 Thanks!'
