### ISSUE TITLE
wide_n_deep  tutorial not work

### ISSUE THREAD

**Issue by sddi** [tensorflow/tensorflow#11256]
Run the wide_n_deep_tutorial.py,  I got the msg like that:

  **## File "wide_n_deep_tutorial.py", line 147, in build_estimator
    m = tf.estimator.DNNLinearCombinedClassifier(
AttributeError: 'module' object has no attribute 'DNNLinearCombinedClassifier'**

**## it shows that DNNLinearCombinedClassifier not in estimator, In the previous version, it seems in tf.contrib.learn** 

**## is it a bug ?**

**Comment by ScorpioCPH** [comment]
In `wide_n_deep_tutorial.py` (r1.2), I can't find any code looks like `tf.estimator.DNNLinearCombinedClassifier`.

Please show me the version which contains `tf.estimator.DNNLinearCombinedClassifier`.

PS, `tf.contrib.learn.DNNLinearCombinedClassifier` works to me.

**Comment by sddi** [comment]
@ScorpioCPH  I use the code from the url :https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/learn/wide_n_deep_tutorial.py

in line 147 there is tf.estimator.DNNLinearCombinedClassifier 

and is it the newest?

**Comment by ScorpioCPH** [comment]
Yes, your code is newest.

In this [commit](https://github.com/tensorflow/tensorflow/commit/e766804ba7c711ff785b7e14311b56d0d3c9b487)
 3 days ago.

- changes: 
<img width="1020" alt="screen shot 2017-07-04 at 11 24 18" src="https://user-images.githubusercontent.com/5319646/27813891-8da12c5a-60ab-11e7-8e56-2575ee947c51.png">

I work on r1.2 instead of `master` branch.

**Comment by sddi** [comment]
oh,  @ScorpioCPH is it the bug of the newest tutorial？ and how can I run the newest ?

**Comment by ScorpioCPH** [comment]
I don't think this is a bug, because master branch is ongoing.

Maybe you can use `released` version, such as [v1.2.0](https://github.com/tensorflow/tensorflow/releases/tag/v1.2.0).

**Comment by sddi** [comment]
OK, I will try the released version~~~thank you~~:D

**Comment by ScorpioCPH** [comment]
My pleasure~

**Comment by amandajliu** [comment]
@ScorpioCPH when I run `wide_n_deep_tutorial.py` on r1.2, I get a ValueError:

```
Traceback (most recent call last):
  File "wide_n_deep_tutorial.py", line 234, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/usr/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "wide_n_deep_tutorial.py", line 197, in main
    FLAGS.train_data, FLAGS.test_data)
  File "wide_n_deep_tutorial.py", line 186, in train_and_eval
    m.fit(input_fn=lambda: input_fn(df_train), steps=train_steps)
  File "/home/usr/tensorflow/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 289, in new_func
    return func(*args, **kwargs)
  File "/home/usr/tensorflow/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 455, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "/home/usr/tensorflow/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 953, in _train_model
    features, labels = input_fn()
  File "wide_n_deep_tutorial.py", line 186, in <lambda>
    m.fit(input_fn=lambda: input_fn(df_train), steps=train_steps)
  File "wide_n_deep_tutorial.py", line 148, in input_fn
    for k in CATEGORICAL_COLUMNS}
  File "wide_n_deep_tutorial.py", line 148, in <dictcomp>
    for k in CATEGORICAL_COLUMNS}
  File "/home/usr/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/sparse_tensor.py", line 132, in __init__
    indices_shape = indices.get_shape().with_rank(2)
  File "/home/usr/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 632, in with_rank
    raise ValueError("Shape %s must have rank %d" % (self, rank))
ValueError: Shape (0,) must have rank 2
```

Any advice on this? Thanks.

**Comment by cy89** [comment]
@amandajliu please see #11328.
