### PR TITLE
fix 'ImportError: cannot import name synthetic'

### PR DESCRIPTION
**Pull request by comicchang**
fix 'ImportError: cannot import name synthetic' error introduced in #5315

see also #6281

```
>>> import tensorflow.examples.tutorials.mnist.input_data as input_data
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/tensorflow/examples/tutorials/mnist/__init__.py", line 21, in <module>
    from tensorflow.examples.tutorials.mnist import input_data
  File "/usr/lib/python3.5/site-packages/tensorflow/examples/tutorials/mnist/input_data.py", line 29, in <module>
    from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets
  File "/usr/lib/python3.5/site-packages/tensorflow/contrib/__init__.py", line 29, in <module>
    from tensorflow.contrib import factorization
  File "/usr/lib/python3.5/site-packages/tensorflow/contrib/factorization/__init__.py", line 24, in <module>
    from tensorflow.contrib.factorization.python.ops.gmm import *
  File "/usr/lib/python3.5/site-packages/tensorflow/contrib/factorization/python/ops/gmm.py", line 30, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/usr/lib/python3.5/site-packages/tensorflow/contrib/learn/__init__.py", line 66, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/usr/lib/python3.5/site-packages/tensorflow/contrib/learn/python/__init__.py", line 23, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/usr/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 26, in <module>
    from tensorflow.contrib.learn.python.learn import datasets
  File "/usr/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/__init__.py", line 29, in <module>
    from tensorflow.contrib.learn.python.learn.datasets import synthetic
ImportError: cannot import name 'synthetic'
```

### CODE REVIEW

**Comment by comicchang** [comment]
@googlebot 
I signed it

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Comment by martinwicke** [comment]
The original change was already reverted, can you add this commit onto a new version of that?

**Comment by comicchang** [comment]
hello martin,

Should I revert the 'revert commit' and rebase my patch to it?
Martin Wicke <notifications@github.com>于2016年12月14日 周三上午12:56写道：

**Comment by martinwicke** [comment]
Yes, that is the easiest way. 

Jenkins, test this please!

**Comment by martinwicke** [comment]
Can you run buildifier (I suspect some tabs have crept in)?

**Comment by comicchang** [comment]
@martinwicke did you mean this ?
https://github.com/tensorflow/tensorflow/pull/6283/commits/2409471010687383328b308f3236cb9443a44a5c

**Comment by martinwicke** [comment]
Jenkins, test this please.

**Review by martinwicke — DISMISSED** [review]

**Review by martinwicke — APPROVED** [review]
Splendid. Thank you!

**Comment by martinwicke** [comment]
Jenkins, test this once more please.

**Comment by martinwicke** [comment]
Jenkins, test this please.
