### ISSUE TITLE
No attribute batch_matmul

### ISSUE THREAD

**Issue by ludovic-pl** [tensorflow/tensorflow#6279]
Hello,
When i run this following python code, i get the error, 

> 'module' object has no attribute 'batch_matmul'

`a = tf.batch_matmul(None,None)`

NB:
I use the bazel build command for CPU optimization

### Environment info
Operating System: Debian jessy

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
9c41d5f64efedf44d30e5cc21f900ea07097395c

**Comment by ludovic-pl** [comment]
In the new documentation this OP is missing also.
Do matmul support some kind of broadcasting now ?

**Comment by andydavis1** [comment]
I think that the batch versions of some ops by making the non-batch versions handle tensors. Rasmus can correct me or add details...

**Comment by ludovic-pl** [comment]
I think you are right. I did my "batch_matmul" with matmul correctly. I close the issue.
Thank you for your reply.

**Comment by siebertlooije** [comment]
Hello,

After the update to 0.12.1, I run into some problems with the "batch_matmul":

>>> import tensorflow as tf
>>> a = tf.batch_matmul(None, None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'batch_matmul'

Is there changed anything in the latest version ?
(Maybe one of the collaborator can re-open this issue?)

Thanks

**Comment by ludovic-pl** [comment]
Please refer to the [issue](https://github.com/tensorflow/tensorflow/issues/6560).

**Comment by sluggishcrow** [comment]
from the release notes of tensorflow 1.5: 

> Prebuilt binaries are now built against CUDA 9 and cuDNN"
